# -*- coding: utf-8 -*-
"""Banco de oraciones para el ejercicio «Encontrá el error».

Cada entrada tiene UNA oración en portugués de Brasil con un error típico de
hispanohablantes (sobre todo rioplatenses), la oración corregida, el
fragmento mal (`bad`), la corrección (`good`), la categoría, la explicación
en español rioplatense (voseo), el nivel MCER y la semana mínima (`w`): la
primera semana del temario (tools/curriculo.py) en la que ya se enseñó todo
lo que usa la oración corregida.

Áreas de interferencia: los «pontos críticos» de la bibliografía de
Português para Falantes de Espanhol (Almeida Filho 1995; Grannier 2002;
Akerberg 2004; Ferreira 1995; Durão 1999): contracciones, heterogenéricos,
plurales en -ões/-ães/-ãos, muito/mais/tudo, gostar de, «a» personal,
perfeito composto, subjuntivo, futuro do subjuntivo, infinitivo pessoal,
pronombres y su colocación, crase, grafía del Acuerdo de 1990, palabras
españolas, falsos amigos, tiempos, persona verbal, participios e
irregulares.

Formato de _RAW: (w, cat, wrong, bad, good, why).  El nivel sale de la
semana (A1 1-8, A2 9-16, B1 17-27, B2 28-40, C1 41-52).  ALT guarda otras
correcciones aceptadas para `bad`.
"""
import re as _re

CATS = (
    "contraccion", "articulo", "genero", "plural", "concordancia", "preposicion",
    "regencia", "muito", "gostar", "a_personal", "perfeito_composto", "subjuntivo",
    "futuro_subj", "inf_pessoal", "pronome", "colocacao", "crase", "ortografia",
    "espanol", "falso_amigo", "tempo", "persona", "participio", "verbo_irregular",
)

_B = r"(?<![\w'])"
_A = r"(?![\w])"


def _lvl(w):
    return "A1" if w <= 8 else "A2" if w <= 16 else "B1" if w <= 27 else "B2" if w <= 40 else "C1"


def _fix(wrong, bad, good):
    pat = _B + _re.escape(bad) + _A
    found = list(_re.finditer(pat, wrong))
    if len(found) != 1:
        raise ValueError("bad %r appears %d times in %r" % (bad, len(found), wrong))
    m = found[0]
    out = wrong[:m.start()] + good + wrong[m.end():]
    return _re.sub(r"\s+", " ", out).replace(" ,", ",").replace(" .", ".").strip()


_RAW = [
    # ------------------------------------------------------------------
    # CONTRACCIONES
    # ------------------------------------------------------------------
    (3, "contraccion", "O livro está em a mesa.", "em a", "na",
     "em + a = na, siempre: está na mesa. En portugués la contracción es obligatoria, nunca «em a»."),
    (5, "contraccion", "Moro em o Rio de Janeiro desde março.", "em o", "no",
     "em + o = no: moro no Rio. «Em o» no se escribe nunca."),
    (3, "contraccion", "Meu irmão está em o Brasil.", "em o", "no",
     "em + o = no: estou no Brasil, ele está no Rio."),
    (5, "contraccion", "A casa de o João fica em Botafogo.", "de o", "do",
     "de + o = do: a casa do João. Como el español «del», pero también con femenino: da, das."),
    (6, "contraccion", "Vamos a o mercado amanhã?", "a o", "ao",
     "a + o = ao: vamos ao mercado. Es el «al» español."),
    (5, "contraccion", "Passo por a praia todos os dias.", "por a", "pela",
     "por + a = pela; por + o = pelo: passo pela praia, pelo centro."),
    (10, "contraccion", "Gosto muito de este bairro.", "de este", "deste",
     "de + este = deste; em + este = neste. Con los demostrativos también se contrae."),
    (11, "contraccion", "Em esse dia, choveu muito em Copacabana.", "Em esse", "Nesse",
     "em + esse = nesse: nesse dia, naquela noite."),
    (10, "contraccion", "O carro de ele é vermelho.", "de ele", "dele",
     "de + ele = dele: o carro dele (su auto, de él). Siempre junto."),
    (10, "contraccion", "A mãe de ela mora em Niterói.", "de ela", "dela",
     "de + ela = dela: a mãe dela. Así se evita la ambigüedad de «seu»."),
    (5, "contraccion", "As crianças brincam em a areia.", "em a", "na",
     "em + a = na: brincam na areia."),
    (3, "contraccion", "Os livros estão em as mochilas.", "em as", "nas",
     "em + as = nas: nas mochilas, nas férias."),
    (5, "contraccion", "Trabalho em os fins de semana.", "em os", "nos",
     "em + os = nos: nos fins de semana, nos domingos."),
    (5, "contraccion", "O metrô passa por o centro da cidade.", "por o", "pelo",
     "por + o = pelo: passa pelo centro."),
    (5, "contraccion", "Obrigado por a ajuda!", "por a", "pela",
     "por + a = pela: obrigado pela ajuda, obrigada pelo convite."),
    (10, "contraccion", "Não gosto de aquele restaurante.", "de aquele", "daquele",
     "de + aquele = daquele; em + aquele = naquele."),
    (10, "contraccion", "Moro em aquela rua perto do Arpoador.", "em aquela", "naquela",
     "em + aquela = naquela: moro naquela rua."),
    (5, "contraccion", "Ele sempre toma café em o bar da esquina.", "em o", "no",
     "em + o = no: toma café no bar."),
    (14, "contraccion", "Penso muito em a minha família.", "em a", "na",
     "pensar em + a = na: penso na minha família."),
    (3, "contraccion", "A capital de o Brasil é Brasília.", "de o", "do",
     "de + o = do: a capital do Brasil."),
    (14, "contraccion", "Você gosta de o Rio?", "de o", "do",
     "gostar de + o = do: gosto do Rio, gosto da Bahia."),
    (5, "contraccion", "Moramos perto de a Lagoa Rodrigo de Freitas.", "de a", "da",
     "perto de + a = perto da: perto da Lagoa."),
    (9, "contraccion", "O ônibus para em a frente do hotel.", "em a frente", "na frente",
     "em + a = na: na frente do hotel."),
    (12, "contraccion", "Coloque o celular em o bolso.", "em o", "no",
     "em + o = no: no bolso. La contracción va también en las órdenes."),

    # ------------------------------------------------------------------
    # ARTÍCULO (países, estados, ciudades con artículo; em casa; horas)
    # ------------------------------------------------------------------
    (4, "articulo", "Brasil é um país enorme.", "Brasil", "O Brasil",
     "Casi todos los países llevan artículo: o Brasil, a Argentina, os Estados Unidos. Sin artículo: Portugal, Angola, Cuba."),
    (4, "articulo", "Argentina é um país muito grande.", "Argentina", "A Argentina",
     "Los países llevan artículo: a Argentina é linda, eu adoro a Argentina."),
    (4, "articulo", "O Portugal é um país pequeno.", "O Portugal", "Portugal",
     "Portugal, como Angola, Moçambique, Cuba o Israel, va sin artículo: Portugal é pequeno."),
    (5, "articulo", "Moro em Brasil há dois anos.", "em Brasil", "no Brasil",
     "Brasil lleva artículo, así que em + o = no: moro no Brasil."),
    (11, "articulo", "Ela nasceu em Rio de Janeiro.", "em Rio", "no Rio",
     "Rio de Janeiro lleva artículo (es «o rio»): no Rio, do Rio, para o Rio. São Paulo, en cambio, no: em São Paulo."),
    (8, "articulo", "Vou para Rio amanhã de manhã.", "para Rio", "para o Rio",
     "O Rio lleva artículo: vou para o Rio, venho do Rio."),
    (5, "articulo", "O meu tio mora em Porto, em Portugal.", "em Porto", "no Porto",
     "La ciudad de Porto lleva artículo: no Porto, do Porto. Lisboa, no: em Lisboa."),
    (5, "articulo", "Salvador fica em Bahia.", "em Bahia", "na Bahia",
     "Algunos estados llevan artículo: a Bahia, o Paraná, o Ceará, o Rio Grande do Sul. Otros no: Pernambuco, Minas Gerais, São Paulo."),
    (4, "articulo", "Porto Alegre é a capital de Rio Grande do Sul.", "de Rio", "do Rio",
     "O Rio Grande do Sul lleva artículo: a capital do Rio Grande do Sul."),
    (5, "articulo", "Manaus fica em Amazonas.", "em Amazonas", "no Amazonas",
     "O Amazonas (el estado) lleva artículo: no Amazonas."),
    (5, "articulo", "A gente mora em Ceará, perto de Fortaleza.", "em Ceará", "no Ceará",
     "O Ceará lleva artículo: no Ceará, do Ceará."),
    (11, "articulo", "Viajei para Estados Unidos em 2019.", "para Estados Unidos", "para os Estados Unidos",
     "Os Estados Unidos, con artículo plural: fui para os Estados Unidos."),
    (7, "articulo", "São as três horas da tarde.", "as", "",
     "Al decir la hora no va artículo: são três horas, é uma hora. El artículo aparece con la preposición: às três."),
    (5, "articulo", "Hoje fico na casa, estou cansado.", "na casa", "em casa",
     "El propio hogar va sin artículo: fico em casa, estou em casa. «Na casa» necesita un dueño: na casa da Ana."),
    (6, "articulo", "Depois do trabalho vou para a casa.", "para a casa", "para casa",
     "Volver al propio hogar: vou para casa, sin artículo."),
    (11, "articulo", "Morei três anos em Espírito Santo.", "em Espírito Santo", "no Espírito Santo",
     "O Espírito Santo (el estado) lleva artículo: no Espírito Santo."),

    # ------------------------------------------------------------------
    # GÉNERO (heterogenéricos)
    # ------------------------------------------------------------------
    (3, "genero", "A leite está na geladeira.", "A leite", "O leite",
     "Leite es masculino: o leite. Como o sangue, o mel, o sal, o nariz, o costume."),
    (3, "genero", "Tenho um dor de cabeça terrível.", "um dor", "uma dor",
     "Dor es femenino: a dor, uma dor de cabeça."),
    (11, "genero", "Foi um viagem incrível pela Bahia.", "um viagem", "uma viagem",
     "Las palabras en -agem son femeninas: a viagem, a mensagem, a garagem, a paisagem."),
    (10, "genero", "A nariz dele é igual ao do pai.", "A nariz", "O nariz",
     "Nariz es masculino en portugués: o nariz."),
    (11, "genero", "Ele perdeu muita sangue no acidente.", "muita sangue", "muito sangue",
     "Sangue es masculino: o sangue, muito sangue."),
    (3, "genero", "Tem um árvore enorme na praça.", "um árvore", "uma árvore",
     "Árvore es femenino: a árvore, uma árvore."),
    (3, "genero", "O ponte Rio-Niterói tem treze quilômetros.", "O ponte", "A ponte",
     "Ponte es femenino: a ponte Rio-Niterói."),
    (10, "genero", "Essa mel é de abelhas nativas.", "Essa mel", "Esse mel",
     "Mel es masculino: o mel, esse mel."),
    (3, "genero", "A sal está em cima da mesa.", "A sal", "O sal",
     "Sal es masculino: o sal. Pedilo así: me passa o sal?"),
    (3, "genero", "O samba de roda é uma costume baiana.", "uma costume baiana", "um costume baiano",
     "Costume es masculino: o costume, um costume baiano."),
    (8, "genero", "Qual é o origem do samba?", "o origem", "a origem",
     "Origem es femenino (como todas en -gem): a origem."),
    (5, "genero", "O garagem fica embaixo do prédio.", "O garagem", "A garagem",
     "Las palabras en -agem son femeninas: a garagem."),
    (11, "genero", "Recebi um mensagem da Bia.", "um mensagem", "uma mensagem",
     "Mensagem es femenino: uma mensagem."),
    (4, "genero", "Qual é o cor da sua camisa?", "o cor", "a cor",
     "Cor es femenino: a cor, as cores."),
    (11, "genero", "O equipe venceu o campeonato.", "O equipe", "A equipe",
     "Equipe es femenino: a equipe. El equipo de fútbol también se dice o time."),
    (11, "genero", "Comprei uma computador novo.", "uma computador", "um computador",
     "Computador es masculino: o computador."),
    (3, "genero", "Ela tem uma sorriso lindo.", "uma sorriso", "um sorriso",
     "Sorriso es masculino: o sorriso."),
    (40, "genero", "O análise dos dados foi publicada ontem.", "O análise", "A análise",
     "Análise es femenino: a análise, como a crise, a tese, a síntese."),
    (20, "genero", "Houve um fraude nas eleições do clube.", "um fraude", "uma fraude",
     "Fraude es femenino en portugués: a fraude."),
    (5, "genero", "Ela adora a samba de raiz.", "a samba", "o samba",
     "Samba es masculino en Brasil: o samba, um samba."),
    (4, "genero", "O paisagem do Arpoador é linda.", "O paisagem", "A paisagem",
     "Paisagem es femenino: a paisagem."),
    (7, "genero", "Hoje é um segunda-feira.", "um segunda-feira", "uma segunda-feira",
     "Los días -feira son femeninos: uma segunda-feira, a terça."),
    (5, "genero", "O cadeira da cozinha está quebrada.", "O cadeira", "A cadeira",
     "Cadeira (silla) es femenino: a cadeira."),

    # ------------------------------------------------------------------
    # PLURAL
    # ------------------------------------------------------------------
    (4, "plural", "Os limãos da feira estão caros.", "limãos", "limões",
     "La mayoría de -ão hace -ões: limão → limões, avião → aviões."),
    (11, "plural", "Comprei dois pãos na padaria.", "pãos", "pães",
     "Pão hace pães (como cão → cães, alemão → alemães)."),
    (4, "plural", "Minhas mões estão frias.", "mões", "mãos",
     "Mão hace mãos (como irmão → irmãos, cidadão → cidadãos)."),
    (11, "plural", "Os alemãos chegaram ontem ao Rio.", "alemãos", "alemães",
     "Alemão hace alemães."),
    (3, "plural", "Os animals do zoológico estão dormindo.", "animals", "animais",
     "-al hace -ais: animal → animais, jornal → jornais."),
    (3, "plural", "Os papels estão em cima da mesa.", "papels", "papéis",
     "-el hace -éis: papel → papéis, hotel → hotéis."),
    (4, "plural", "Os hotels de Copacabana são caros.", "hotels", "hotéis",
     "Hotel → hotéis, con tilde."),
    (3, "plural", "Os homems estão na praia.", "homems", "homens",
     "-m hace -ns: homem → homens, jovem → jovens."),
    (3, "plural", "As viagems de ônibus são longas.", "viagems", "viagens",
     "-agem hace -agens: viagem → viagens."),
    (3, "plural", "Os jardims do Palácio são lindos.", "jardims", "jardins",
     "-im hace -ins: jardim → jardins."),
    (4, "plural", "Os exercícios são fácils.", "fácils", "fáceis",
     "-il átono hace -eis: fácil → fáceis, difícil → difíceis."),
    (4, "plural", "Ela tem olhos azuls.", "azuls", "azuis",
     "Azul hace azuis."),
    (11, "plural", "Comprei dois jornals no aeroporto.", "jornals", "jornais",
     "Jornal hace jornais."),
    (11, "plural", "Os cidadões votaram em outubro.", "cidadões", "cidadãos",
     "Cidadão hace cidadãos."),
    (4, "plural", "As liçãos são fáceis.", "liçãos", "lições",
     "Lição hace lições."),
    (3, "plural", "Os meus irmões são altos.", "irmões", "irmãos",
     "Irmão hace irmãos."),
    (11, "plural", "Os capitões dos dois times conversaram.", "capitões", "capitães",
     "Capitão hace capitães."),
    (4, "plural", "Os espanhois são simpáticos.", "espanhois", "espanhóis",
     "-ol hace -óis con tilde: espanhol → espanhóis, farol → faróis."),
    (3, "plural", "Os lápises estão na mochila.", "lápises", "lápis",
     "Lápis no cambia en plural: o lápis, os lápis (como o ônibus, os ônibus)."),
    (5, "plural", "Os ônibuses passam na orla.", "ônibuses", "ônibus",
     "Ônibus es invariable: os ônibus."),
    (3, "plural", "Os anels são de prata.", "anels", "anéis",
     "Anel hace anéis."),
    (11, "plural", "Fui duas vez ao Maracanã.", "vez", "vezes",
     "Vez hace vezes: duas vezes, às vezes."),
    (11, "plural", "Fiquei três mês em Florianópolis.", "mês", "meses",
     "Mês hace meses (sin tilde en plural)."),
    (3, "plural", "Os caminhãos estão na estrada.", "caminhãos", "caminhões",
     "Caminhão hace caminhões."),
    (3, "plural", "Os cãos da vizinha são bravos.", "cãos", "cães",
     "Cão hace cães."),
    (4, "plural", "Os túnels do Rio são longos.", "túnels", "túneis",
     "-el átono hace -eis: túnel → túneis."),

    # ------------------------------------------------------------------
    # CONCORDANCIA
    # ------------------------------------------------------------------
    (3, "concordancia", "A praia está cheio hoje.", "cheio", "cheia",
     "El adjetivo concuerda con el sustantivo: a praia está cheia."),
    (4, "concordancia", "As meninas são alto.", "alto", "altas",
     "Femenino plural: as meninas são altas."),
    (4, "concordancia", "Minha avó é muito simpático.", "simpático", "simpática",
     "Avó es femenino: simpática."),
    (4, "concordancia", "Os turistas são argentino.", "argentino", "argentinos",
     "Plural: os turistas são argentinos."),
    (4, "concordancia", "A casa da Bia é bonito.", "bonito", "bonita",
     "Casa es femenino: bonita."),
    (3, "concordancia", "Elas estão cansados.", "cansados", "cansadas",
     "Elas → cansadas."),
    (5, "concordancia", "Meus irmãs moram em Rosario.", "Meus", "Minhas",
     "El posesivo concuerda con lo poseído: minhas irmãs, meus irmãos."),
    (11, "concordancia", "Comprei dois camisas na feira.", "dois", "duas",
     "Dois / duas concuerdan en género: duas camisas, dois vestidos."),
    (11, "concordancia", "Duzentos pessoas foram ao show.", "Duzentos", "Duzentas",
     "Las centenas también concuerdan: duzentas pessoas, trezentas casas."),
    (4, "concordancia", "Estou com as mãos frios.", "frios", "frias",
     "Mãos es femenino: frias."),
    (4, "concordancia", "O problema é sério e a solução é caro.", "caro", "cara",
     "Solução es femenino: cara."),
    (11, "concordancia", "As fotos da viagem ficaram lindos.", "lindos", "lindas",
     "Foto es femenino (a foto): lindas."),
    (4, "concordancia", "Os problemas são complicadas.", "complicadas", "complicados",
     "Problema es masculino, como en español: complicados."),
    (4, "concordancia", "O sistema é muito antiga.", "antiga", "antigo",
     "Sistema es masculino: antigo."),
    (5, "concordancia", "Todas os dias acordo cedo.", "Todas", "Todos",
     "Todos os dias: dia es masculino."),
    (3, "concordancia", "Meu mãe é professora.", "Meu", "Minha",
     "Minha mãe, meu pai: el posesivo concuerda con lo poseído."),
    (3, "concordancia", "Nosso cidade é pequena.", "Nosso", "Nossa",
     "Cidade es femenino: nossa cidade."),
    (10, "concordancia", "Esse praia é a mais bonita do Rio.", "Esse", "Essa",
     "Praia es femenino: essa praia."),
    (10, "concordancia", "Essas sapatos são novos.", "Essas", "Esses",
     "Sapato es masculino: esses sapatos."),
    (10, "concordancia", "Aquela livro é do meu pai.", "Aquela", "Aquele",
     "Livro es masculino: aquele livro."),
    (4, "concordancia", "A água do mar está gelado.", "gelado", "gelada",
     "Água es femenino: gelada."),
    (4, "concordancia", "O leite está quente e a sopa está frio.", "frio", "fria",
     "Sopa es femenino: fria."),
    (22, "concordancia", "As casas foram vendido em um mês.", "vendido", "vendidas",
     "En la pasiva el participio concuerda con el sujeto: as casas foram vendidas."),

    # ------------------------------------------------------------------
    # MUITO / MAIS / TUDO
    # ------------------------------------------------------------------
    (4, "muito", "Ela é muy bonita.", "muy", "muito",
     "«Muy» no existe: muito sirve para «muy» y para «mucho». Ela é muito bonita."),
    (4, "muito", "O Rio é mucho bonito.", "mucho", "muito",
     "Muy y mucho son muito: muito bonito, muito dinheiro."),
    (3, "muito", "Estou com muito fome.", "muito", "muita",
     "Ante sustantivo, muito concuerda: muita fome, muitos amigos. Ante adjetivo, no cambia."),
    (3, "muito", "Tem muitos gente na praia hoje.", "muitos", "muita",
     "Gente es femenino singular: muita gente."),
    (5, "muito", "Obrigado por todo!", "todo", "tudo",
     "Todo (pronombre, «todo esto») = tudo: obrigado por tudo. Todo va con un sustantivo: todo dia."),
    (3, "muito", "Todo está bem, não se preocupe.", "Todo", "Tudo",
     "Todo (pronombre) = tudo: tudo bem, tudo está bem."),
    (11, "muito", "Comi todo e ainda estou com fome.", "todo", "tudo",
     "«Comí todo» = comi tudo."),
    (11, "muito", "Trabalhei tudo o dia ontem.", "tudo", "todo",
     "Con un sustantivo va todo: todo o dia, o dia todo. Tudo es solo pronombre."),
    (5, "muito", "Eu ligo mas tarde para você.", "mas", "mais",
     "Más = mais (con i). «Mas» sin i es «pero»."),
    (5, "muito", "Quero mas café, por favor.", "mas", "mais",
     "Más = mais: mais café, mais tarde."),
    (19, "muito", "Salvador é mais grande que Recife.", "mais grande", "maior",
     "Más grande = maior. «Mais grande» es error en portugués, como «mais bom»."),
    (19, "muito", "O Rio é mais pequeno que São Paulo.", "mais pequeno", "menor",
     "En Brasil, más pequeño = menor (mais pequeno se oye en Portugal)."),
    (19, "muito", "Esse restaurante é mais bom que o outro.", "mais bom", "melhor",
     "Más bueno / mejor = melhor."),
    (19, "muito", "Hoje o tempo está mais mau que ontem.", "mais mau", "pior",
     "Peor = pior."),
    (11, "muito", "Ontem choveu mucho no Rio.", "mucho", "muito",
     "Mucho = muito: choveu muito."),
    (3, "muito", "Tenho muito amigos em Buenos Aires.", "muito", "muitos",
     "Ante un sustantivo plural: muitos amigos, muitas amigas."),
    (3, "muito", "Muito pessoas estão na fila.", "Muito", "Muitas",
     "Pessoa es femenino: muitas pessoas."),
    (19, "muito", "Ela canta tan bem quanto a mãe.", "tan", "tão",
     "Tan = tão: tão bem quanto, tão bonito."),
    (20, "muito", "Tudo mundo sabe disso.", "Tudo", "Todo",
     "Todo el mundo = todo mundo (o todo o mundo): todo va con sustantivo."),

    # ------------------------------------------------------------------
    # GOSTAR
    # ------------------------------------------------------------------
    (14, "gostar", "Eu gosto o samba.", "gosto o", "gosto do",
     "Gostar pide de: gosto de samba / gosto do samba (de + o)."),
    (14, "gostar", "Me gosta a praia de Ipanema.", "Me gosta a", "Gosto da",
     "En portugués el que gusta es el sujeto: eu gosto da praia (no «me gosta»)."),
    (14, "gostar", "Ela gosta dançar forró.", "gosta", "gosta de",
     "Gostar de + infinitivo: ela gosta de dançar."),
    (14, "gostar", "Eu gostam dos livros de Jorge Amado.", "gostam", "gosto",
     "El verbo concuerda con la persona que gusta, no con lo que gusta: eu gosto dos livros."),
    (14, "gostar", "A ela gosta de café sem açúcar.", "A ela gosta", "Ela gosta",
     "Sin «a»: ela gosta de café. La persona es el sujeto."),
    (14, "gostar", "Te gosta o futebol?", "Te gosta o", "Você gosta de",
     "¿Te gusta? = você gosta de…? La persona es sujeto y gostar lleva de."),
    (18, "gostar", "Eu gostaria um café, por favor.", "gostaria", "gostaria de",
     "Gostaria de + sustantivo o infinitivo: gostaria de um café."),
    (14, "gostar", "Gostei muito o filme.", "o filme", "do filme",
     "Gostar de + o = do: gostei do filme."),
    (14, "gostar", "Vocês gostaram a festa?", "a festa", "da festa",
     "Gostar de + a = da: gostaram da festa?"),
    (14, "gostar", "Me encanta o carnaval do Rio.", "Me encanta", "Adoro",
     "Me encanta = adoro, amo. «Me encanta» calca el español."),
    (16, "gostar", "Acho que ele me gosta.", "me gosta", "gosta de mim",
     "«Le gusto» = ele gosta de mim: la persona que gusta es el objeto de «de»."),
    (14, "gostar", "Me gosta cozinhar para os amigos.", "Me gosta", "Gosto de",
     "Me gusta cocinar = gosto de cozinhar."),
    (14, "gostar", "Nós gostamos muito a comida mineira.", "a comida", "da comida",
     "Gostar de + a = da: gostamos da comida mineira."),
    (14, "gostar", "Os meus pais gosta de bossa nova.", "gosta", "gostam",
     "Os meus pais (ellos) → gostam."),

    # ------------------------------------------------------------------
    # «A» PERSONAL
    # ------------------------------------------------------------------
    (5, "a_personal", "Conheço a Pedro desde criança.", "a Pedro", "o Pedro",
     "No hay «a» personal: conheço o Pedro. Delante del nombre va el artículo (o Pedro, a Ana)."),
    (11, "a_personal", "Vi a meu irmão ontem na praia.", "a meu irmão", "meu irmão",
     "Sin «a» personal: vi meu irmão (o vi o meu irmão)."),
    (11, "a_personal", "Chamei a um médico.", "a um médico", "um médico",
     "Sin «a» personal: chamei um médico."),
    (11, "a_personal", "Visitei a meus avós em Mendoza.", "a meus avós", "meus avós",
     "Visitar alguém, sin preposición: visitei meus avós."),
    (20, "a_personal", "Não conheço a ninguém aqui.", "a ninguém", "ninguém",
     "Sin «a»: não conheço ninguém."),
    (20, "a_personal", "Vi a alguém na janela.", "a alguém", "alguém",
     "Sin «a»: vi alguém."),
    (5, "a_personal", "Amo a meus filhos.", "a meus filhos", "meus filhos",
     "Amar alguém, sin preposición: amo meus filhos."),
    (11, "a_personal", "Encontrei ao Rafa no metrô.", "ao Rafa", "o Rafa",
     "Encontrar alguém: encontrei o Rafa. «Ao» sería a + o."),
    (11, "a_personal", "Convidei ao meu chefe para o churrasco.", "ao meu chefe", "o meu chefe",
     "Convidar alguém, sin «a»: convidei o meu chefe."),
    (5, "a_personal", "Levo aos meninos para a escola.", "aos meninos", "os meninos",
     "Levar alguém: levo os meninos."),
    (11, "a_personal", "Escutei ao presidente na televisão.", "ao presidente", "o presidente",
     "Escutar alguém, sin «a»: escutei o presidente."),
    (11, "a_personal", "Buscamos a nossos amigos no aeroporto.", "a nossos amigos", "nossos amigos",
     "Buscar alguém: buscamos nossos amigos."),
    (11, "a_personal", "Esperei a Lucas uma hora.", "a Lucas", "o Lucas",
     "Esperar alguém: esperei o Lucas (o, artículo)."),
    (11, "a_personal", "Conheci ao pai dela no casamento.", "ao pai", "o pai",
     "Conhecer alguém: conheci o pai dela."),
    (16, "a_personal", "Ajudei a meus colegas com o relatório.", "a meus colegas", "meus colegas",
     "Ajudar alguém, sin preposición: ajudei meus colegas."),

    # ------------------------------------------------------------------
    # PREPOSICIONES
    # ------------------------------------------------------------------
    (6, "preposicion", "Vou em pé para o trabalho.", "em pé", "a pé",
     "Caminando = a pé. «Em pé» significa parado, de pie."),
    (11, "preposicion", "Viajei em avião para Recife.", "em avião", "de avião",
     "Los medios de transporte van con de: de avião, de ônibus, de carro, de metrô. Solo a pé."),
    (6, "preposicion", "Vou para a praia em bicicleta.", "em bicicleta", "de bicicleta",
     "Medio de transporte: de bicicleta."),
    (5, "preposicion", "Moro a Copacabana.", "a", "em",
     "Estar o vivir en un lugar: em. Moro em Copacabana."),
    (3, "preposicion", "Estou a casa agora.", "a casa", "em casa",
     "Estar en casa = estar em casa."),
    (11, "preposicion", "Nasci no 1995, em Córdoba.", "no", "em",
     "Con los años va em, sin artículo: nasci em 1995."),
    (5, "preposicion", "Moro no Rio desde três anos.", "desde", "há",
     "Duración hasta hoy: há três anos (o faz três anos). Desde va con una fecha: desde 2021."),
    (8, "preposicion", "Vou a viajar amanhã.", "a viajar", "viajar",
     "Ir + infinitivo va sin «a»: vou viajar."),
    (8, "preposicion", "Ela vai a estudar medicina.", "a estudar", "estudar",
     "Sin «a»: ela vai estudar."),
    (7, "preposicion", "Trabalho por a manhã e estudo à noite.", "por a manhã", "de manhã",
     "Por la mañana = de manhã; por la tarde = à tarde; por la noche = à noite."),
    (7, "preposicion", "Estudo português por a noite.", "por a noite", "à noite",
     "Por la noche = à noite (con crase)."),
    (6, "preposicion", "O sábado vou ao Maracanã.", "O sábado", "No sábado",
     "El sábado (este) = no sábado: no sábado vou ao jogo."),
    (5, "preposicion", "No janeiro faz muito calor no Rio.", "No janeiro", "Em janeiro",
     "Con los meses: em janeiro, sin artículo."),
    (5, "preposicion", "Obrigado para tudo!", "para", "por",
     "Agradecer: obrigado por tudo, pela ajuda."),
    (5, "preposicion", "Moro em frente o mar.", "em frente o", "em frente ao",
     "Em frente a / em frente de: em frente ao mar."),
    (5, "preposicion", "O hotel fica perto a praia.", "perto a", "perto da",
     "Perto de + a = perto da praia."),
    (5, "preposicion", "Depois o almoço, descanso um pouco.", "Depois o", "Depois do",
     "Depois de + o = depois do almoço."),
    (11, "preposicion", "Entrei a sala sem bater.", "a sala", "na sala",
     "Entrar em: entrei na sala."),
    (9, "preposicion", "Chego de Buenos Aires a as oito.", "a as", "às",
     "a + as = às: chego às oito."),

    # ------------------------------------------------------------------
    # REGENCIA
    # ------------------------------------------------------------------
    (14, "regencia", "Preciso um táxi para o aeroporto.", "Preciso", "Preciso de",
     "Precisar de + sustantivo: preciso de um táxi. Ante infinitivo, sin de: preciso sair."),
    (14, "regencia", "Você se lembra a minha irmã?", "a minha", "da minha",
     "Lembrar-se de: você se lembra da minha irmã?"),
    (14, "regencia", "Sonhei em você ontem à noite.", "em você", "com você",
     "Sonhar com: sonhei com você."),
    (14, "regencia", "Penso sempre de você.", "de você", "em você",
     "Pensar em: penso em você."),
    (35, "regencia", "Ela namora com o Rafa há dois anos.", "namora com o", "namora o",
     "Namorar alguém, sin preposición en la norma: ela namora o Rafa."),
    (35, "regencia", "Ontem assisti o jogo do Flamengo.", "assisti o", "assisti ao",
     "Assistir (ver) pide a en la norma: assisti ao jogo. En el habla se oye «assisti o jogo»."),
    (35, "regencia", "As crianças devem obedecer os pais.", "os pais", "aos pais",
     "Obedecer a alguém: obedecer aos pais."),
    (35, "regencia", "Prefiro praia do que montanha.", "do que", "a",
     "Preferir X a Y: prefiro praia a montanha. «Do que» es del habla."),
    (35, "regencia", "Chegamos no aeroporto às seis.", "no aeroporto", "ao aeroporto",
     "En la norma, chegar a: chegamos ao aeroporto (en el habla, chegar em)."),
    (14, "regencia", "Tudo depende o tempo.", "o tempo", "do tempo",
     "Depender de: depende do tempo."),
    (14, "regencia", "Confio de você.", "de você", "em você",
     "Confiar em: confio em você."),
    (14, "regencia", "Me interesso de política.", "de política", "por política",
     "Interessar-se por: me interesso por política."),
    (14, "regencia", "Ela se apaixonou de um carioca.", "de um carioca", "por um carioca",
     "Apaixonar-se por: ela se apaixonou por um carioca."),
    (35, "regencia", "Ele aspira o cargo de diretor.", "o cargo", "ao cargo",
     "Aspirar a (desear): aspira ao cargo. Aspirar o pó = aspirar el polvo."),
    (35, "regencia", "Essa decisão implica em mudanças.", "implica em", "implica",
     "En la norma, implicar (= acarrear) va sin preposición: implica mudanças."),
    (35, "regencia", "Ainda não respondi o e-mail do diretor.", "respondi o", "respondi ao",
     "Responder a algo: respondi ao e-mail."),
    (35, "regencia", "Já paguei o garçom.", "o garçom", "ao garçom",
     "Pagar algo a alguém: paguei ao garçom (en el habla, «paguei o garçom»)."),
    (35, "regencia", "Ótimo: a proposta vai de encontro aos nossos interesses.", "de encontro aos", "ao encontro dos",
     "Ir ao encontro de = coincidir con; ir de encontro a = chocar contra. Acá es lo primero."),
    (35, "regencia", "Simpatizo-me muito com ela.", "Simpatizo-me", "Simpatizo",
     "Simpatizar com no es pronominal: simpatizo com ela."),
    (35, "regencia", "Esqueci de que tinha reunião.", "de que", "que",
     "Esquecer algo o esquecer-se de algo: esqueci que tinha reunião."),

    # ------------------------------------------------------------------
    # PRETÉRITO PERFEITO COMPOSTO
    # ------------------------------------------------------------------
    (21, "perfeito_composto", "Hoje eu tenho acordado às seis.", "tenho acordado", "acordei",
     "«Hoy me desperté / me he despertado» = hoje acordei. Tenho acordado = vengo despertándome."),
    (21, "perfeito_composto", "Você já tem visto o Cristo Redentor?", "tem visto", "viu",
     "¿Ya viste / has visto? = você já viu? El perfeito cubre el «he visto» español."),
    (21, "perfeito_composto", "Nunca tenho estado em Salvador.", "tenho estado", "estive",
     "«Nunca he estado» = nunca estive."),
    (21, "perfeito_composto", "Ainda não tenho terminado o relatório.", "tenho terminado", "terminei",
     "«Todavía no terminé / he terminado» = ainda não terminei."),
    (21, "perfeito_composto", "Esta manhã tenho falado com o chefe.", "tenho falado", "falei",
     "Una acción puntual de hoy va en perfeito: esta manhã falei com o chefe."),
    (21, "perfeito_composto", "Já tenho lido esse livro da Clarice.", "tenho lido", "li",
     "«Ya lo he leído» = já li."),
    (11, "perfeito_composto", "Hemos ido ao Maracanã no domingo.", "Hemos ido", "Fomos",
     "El «he ido» español es el perfeito: fomos. «Hemos» no existe."),
    (11, "perfeito_composto", "He comido feijoada no sábado.", "He comido", "Comi",
     "«He comido» = comi."),
    (21, "perfeito_composto", "Tenho acabado de chegar do trabalho.", "Tenho acabado", "Acabei",
     "«Acabo de llegar» = acabei de chegar."),
    (21, "perfeito_composto", "Hoje tenho almoçado num boteco da Lapa.", "tenho almoçado", "almocei",
     "Almuerzo de hoy, una vez: almocei."),
    (21, "perfeito_composto", "Você já tem ido a Portugal?", "tem ido", "foi",
     "¿Ya fuiste / has ido? = você já foi?"),
    (21, "perfeito_composto", "Tenho nascido em Rosario.", "Tenho nascido", "Nasci",
     "Nacer es puntual: nasci em Rosario."),
    (21, "perfeito_composto", "Tenho perdido a chave hoje de manhã.", "Tenho perdido", "Perdi",
     "Una vez, hoy: perdi a chave."),
    (21, "perfeito_composto", "Ontem tenho trabalhado até tarde.", "tenho trabalhado", "trabalhei",
     "Ontem pide perfeito simple: trabalhei. Tenho trabalhado = vengo trabajando."),
    (21, "perfeito_composto", "Nas últimas semanas estudei muito todos os dias.", "estudei", "tenho estudado",
     "Una repetición que llega hasta hoy va en perfeito composto: tenho estudado muito."),

    # ------------------------------------------------------------------
    # SUBJUNTIVO
    # ------------------------------------------------------------------
    (23, "subjuntivo", "Espero que você vem ao jantar.", "vem", "venha",
     "Esperar que + subjuntivo: espero que você venha."),
    (23, "subjuntivo", "Quero que ele faz o jantar.", "faz", "faça",
     "Querer que + subjuntivo: quero que ele faça."),
    (23, "subjuntivo", "É importante que vocês estudam.", "estudam", "estudem",
     "É importante que + subjuntivo: estudem."),
    (23, "subjuntivo", "Talvez ele está em casa.", "está", "esteja",
     "Talvez delante del verbo pide subjuntivo: talvez esteja."),
    (23, "subjuntivo", "Tomara que não chove no domingo.", "chove", "chova",
     "Tomara que (ojalá) + subjuntivo: tomara que não chova."),
    (23, "subjuntivo", "Acho que ele venha amanhã.", "venha", "vem",
     "Achar que afirma algo: indicativo. Acho que ele vem (o que ele vai vir)."),
    (23, "subjuntivo", "Duvido que ela sabe a resposta.", "sabe", "saiba",
     "Duvidar que + subjuntivo: saiba."),
    (24, "subjuntivo", "Embora está cansado, ele vai trabalhar.", "está", "esteja",
     "Embora siempre con subjuntivo: embora esteja cansado."),
    (24, "subjuntivo", "Falo devagar para que você entende.", "entende", "entenda",
     "Para que + subjuntivo: para que você entenda."),
    (24, "subjuntivo", "Caso chove, a gente fica em casa.", "chove", "chova",
     "Caso + subjuntivo presente: caso chova."),
    (24, "subjuntivo", "Vamos embora antes que é tarde.", "é", "seja",
     "Antes que + subjuntivo: antes que seja tarde."),
    (23, "subjuntivo", "Não acho que é verdade.", "é", "seja",
     "Não achar que (duda) pide subjuntivo: não acho que seja verdade."),
    (23, "subjuntivo", "Peço que você me liga amanhã.", "liga", "ligue",
     "Pedir que + subjuntivo: ligue."),
    (23, "subjuntivo", "É possível que eles chegam tarde.", "chegam", "cheguem",
     "É possível que + subjuntivo: cheguem."),
    (23, "subjuntivo", "Quero que você está feliz.", "está", "esteja",
     "Estar en subjuntivo: esteja."),
    (28, "subjuntivo", "Se eu tenho tempo, viajaria mais.", "tenho", "tivesse",
     "Hipótesis irreal: se + imperfeito do subjuntivo, futuro do pretérito: se eu tivesse tempo, viajaria."),
    (28, "subjuntivo", "Se eu seria rico, moraria em Ipanema.", "seria", "fosse",
     "Nunca condicional después de se: se eu fosse rico."),
    (28, "subjuntivo", "Queria que você vem comigo.", "vem", "viesse",
     "Queria que + imperfeito do subjuntivo: viesse."),
    (28, "subjuntivo", "Se eu saberia a resposta, te diria.", "saberia", "soubesse",
     "Se + imperfeito do subjuntivo: soubesse."),
    (28, "subjuntivo", "Era importante que eles chegam cedo.", "chegam", "chegassem",
     "Principal en pasado → imperfeito do subjuntivo: chegassem."),
    (24, "subjuntivo", "Vou para a praia mesmo que chove.", "chove", "chova",
     "Mesmo que + subjuntivo: mesmo que chova."),
    (47, "subjuntivo", "Por mais que tenta, não consegue.", "tenta", "tente",
     "Por mais que + subjuntivo: por mais que tente."),
    (28, "subjuntivo", "Saí sem que ninguém sabe.", "sabe", "soubesse",
     "Sem que + subjuntivo; con el principal en pasado, imperfeito: sem que ninguém soubesse."),
    (30, "subjuntivo", "Se eu teria sabido, teria ido.", "teria sabido", "tivesse sabido",
     "Hipótesis del pasado: se eu tivesse sabido, teria ido."),
    (41, "subjuntivo", "Se Machado de Assis viveria hoje, escreveria crônicas na internet?", "viveria", "vivesse",
     "Se + imperfeito do subjuntivo: se Machado vivesse hoje."),
    (28, "subjuntivo", "O professor pediu que lêssemos Vidas Secas e que fazemos um resumo.", "fazemos", "fizéssemos",
     "Los dos verbos dependen de pediu que: lêssemos e fizéssemos."),

    # ------------------------------------------------------------------
    # FUTURO DO SUBJUNTIVO
    # ------------------------------------------------------------------
    (27, "futuro_subj", "Quando eu chegue ao Rio, te ligo.", "chegue", "chegar",
     "Cuando + futuro = quando + futuro do subjuntivo: quando eu chegar."),
    (27, "futuro_subj", "Quando você possa, me liga.", "possa", "puder",
     "«Cuando puedas» = quando você puder."),
    (27, "futuro_subj", "Quando eu seja grande, vou ser médico.", "seja", "for",
     "«Cuando sea grande» = quando eu for grande."),
    (27, "futuro_subj", "Assim que ela tenha tempo, vai responder.", "tenha", "tiver",
     "Assim que + futuro do subjuntivo: tiver."),
    (27, "futuro_subj", "Enquanto você esteja aqui, fique tranquilo.", "esteja", "estiver",
     "Enquanto (futuro) + futuro do subjuntivo: estiver."),
    (27, "futuro_subj", "Se Deus queira, a gente se vê em março.", "queira", "quiser",
     "Se Deus quiser: se + futuro do subjuntivo."),
    (27, "futuro_subj", "Quando vocês venham ao Rio, fiquem lá em casa.", "venham", "vierem",
     "Vir → vierem (de vieram)."),
    (27, "futuro_subj", "Se você veja a Ana, manda um abraço.", "veja", "vir",
     "Ver → vir en futuro do subjuntivo (de viram): se você vir a Ana."),
    (27, "futuro_subj", "Quem queira pode sair mais cedo.", "queira", "quiser",
     "Quien quiera = quem quiser."),
    (27, "futuro_subj", "Onde você vá, eu vou.", "vá", "for",
     "Donde vayas = onde você for."),
    (27, "futuro_subj", "Quando fazer frio, uso casaco.", "fazer", "fizer",
     "El futuro do subjuntivo sale de la 3.ª plural del perfeito: fizeram → fizer."),
    (27, "futuro_subj", "Se eu poder, vou à festa.", "poder", "puder",
     "Poder → puderam → puder."),
    (27, "futuro_subj", "Quando ele saber a verdade, vai ficar bravo.", "saber", "souber",
     "Saber → souberam → souber."),
    (27, "futuro_subj", "Se vocês trazerem vinho, eu faço o jantar.", "trazerem", "trouxerem",
     "Trazer → trouxeram → trouxerem."),
    (27, "futuro_subj", "Quando eu ter tempo, vou aprender a surfar.", "ter", "tiver",
     "Ter → tiveram → tiver."),
    (27, "futuro_subj", "Se você ir para a Lapa, prove a caipirinha.", "ir", "for",
     "Ir → foram → for: se você for."),
    (27, "futuro_subj", "Logo que eu termine a faculdade, vou morar em Lisboa.", "termine", "terminar",
     "Logo que (futuro) + futuro do subjuntivo: terminar."),
    (27, "futuro_subj", "Se eles verem o pôr do sol no Arpoador, vão aplaudir.", "verem", "virem",
     "Ver → viram → virem."),

    # ------------------------------------------------------------------
    # INFINITIVO PESSOAL
    # ------------------------------------------------------------------
    (29, "inf_pessoal", "É melhor vocês chegar cedo.", "chegar", "chegarem",
     "Con sujeto propio (vocês), el infinitivo se conjuga: vocês chegarem."),
    (29, "inf_pessoal", "Trouxe o carro para nós ir juntos.", "ir", "irmos",
     "Para nós + infinitivo pessoal: para nós irmos."),
    (29, "inf_pessoal", "Antes de eles sair, feche a janela.", "sair", "saírem",
     "Antes de eles saírem (con tilde en la í)."),
    (29, "inf_pessoal", "Fizeram tudo sem nós saber.", "saber", "sabermos",
     "Sem nós sabermos."),
    (29, "inf_pessoal", "Comprei o livro para eles leiam.", "leiam", "lerem",
     "Para + sujeto + infinitivo pessoal: para eles lerem (o para que eles leiam)."),
    (29, "inf_pessoal", "É importante nós fazer isso hoje.", "fazer", "fazermos",
     "É importante nós fazermos."),
    (29, "inf_pessoal", "Depois de vocês jantar, a gente conversa.", "jantar", "jantarem",
     "Depois de vocês jantarem."),
    (29, "inf_pessoal", "O professor pediu para os alunos fazer silêncio.", "fazer", "fazerem",
     "Os alunos es el sujeto del infinitivo: fazerem."),
    (29, "inf_pessoal", "Trouxe cadeiras para a gente irmos para a praia.", "irmos", "ir",
     "A gente conjuga en 3.ª singular: para a gente ir."),
    (29, "inf_pessoal", "Espero até vocês entender.", "entender", "entenderem",
     "Até vocês entenderem."),
    (29, "inf_pessoal", "Por eles ser jovens, ninguém os escuta.", "ser", "serem",
     "Por eles serem jovens."),
    (29, "inf_pessoal", "Apesar de nós ter pouco tempo, visitamos Santa Teresa.", "ter", "termos",
     "Apesar de nós termos."),
    (29, "inf_pessoal", "Foi um erro vocês não vir ao samba.", "vir", "virem",
     "Vir → virem (infinitivo pessoal)."),
    (42, "inf_pessoal", "Ao chegar os turistas, a guia explicou a história do Paço Imperial.", "chegar", "chegarem",
     "Ao + infinitivo con sujeto propio (os turistas) se conjuga: ao chegarem os turistas."),
    (29, "inf_pessoal", "Para nós entender Freyre, é preciso ler Casa-Grande & Senzala.", "entender", "entendermos",
     "Para nós entendermos."),

    # ------------------------------------------------------------------
    # PRONOMBRES
    # ------------------------------------------------------------------
    (16, "pronome", "Para mí, está ótimo.", "mí", "mim",
     "Para mí = para mim, con m final."),
    (16, "pronome", "Esse presente é para eu.", "eu", "mim",
     "Tras preposición va mim: é para mim. «Para eu» solo delante de un infinitivo: para eu ler."),
    (16, "pronome", "Ela foi com eu ao cinema.", "com eu", "comigo",
     "Con + yo = comigo."),
    (16, "pronome", "Vem com nós para a Lapa!", "com nós", "conosco",
     "Con nosotros = conosco (o com a gente)."),
    (16, "pronome", "Eu le disse a verdade.", "le", "lhe",
     "Le = lhe (o, en el habla, disse para ele)."),
    (16, "pronome", "Eu lo vi ontem no calçadão.", "lo", "o",
     "Lo = o: eu o vi (en el habla, vi ele)."),
    (33, "pronome", "Vou comprar-o amanhã.", "comprar-o", "comprá-lo",
     "Tras -r el pronombre es -lo y la r cae: comprá-lo, vendê-lo, abri-lo."),
    (33, "pronome", "Quero ver-o de novo.", "ver-o", "vê-lo",
     "Ver + o = vê-lo."),
    (33, "pronome", "Fiz-o ontem.", "Fiz-o", "Fi-lo",
     "Tras -z la consonante cae: fiz + o = fi-lo."),
    (33, "pronome", "Os alunos dão-o ao professor.", "dão-o", "dão-no",
     "Tras nasal el pronombre es -no: dão-no, põe-no."),
    (16, "pronome", "Isso fica entre eu e você.", "eu", "mim",
     "Tras entre: entre mim e você."),
    (16, "pronome", "Ele trouxe o livro para mim ler.", "mim", "eu",
     "Delante de un infinitivo va eu (es el sujeto): para eu ler."),
    (16, "pronome", "Eu lhe vi na praia.", "lhe", "o",
     "Lhe es objeto indirecto; el directo es o/a: eu o vi (habla: vi ele)."),
    (12, "pronome", "Ela se chama-se Beatriz.", "chama-se", "chama",
     "El pronombre va una sola vez: ela se chama o chama-se."),
    (16, "pronome", "Conmigo não tem problema.", "Conmigo", "Comigo",
     "Conmigo = comigo."),

    # ------------------------------------------------------------------
    # COLOCACIÓN PRONOMINAL (norma escrita)
    # ------------------------------------------------------------------
    (33, "colocacao", "Ele não disse-me nada.", "disse-me", "me disse",
     "Não atrae el pronombre: não me disse."),
    (33, "colocacao", "Quem contou-lhe a novidade?", "contou-lhe", "lhe contou",
     "Los interrogativos atraen el pronombre: quem lhe contou?"),
    (33, "colocacao", "Nunca vi-o tão feliz.", "vi-o", "o vi",
     "Nunca atrae el pronombre: nunca o vi."),
    (33, "colocacao", "Eu já tinha avisado-o.", "tinha avisado-o", "o tinha avisado",
     "Nunca pronombre después de participio: já o tinha avisado (o tinha-o avisado)."),
    (33, "colocacao", "Direi-lhe a verdade amanhã.", "Direi-lhe", "Dir-lhe-ei",
     "Con futuro, en la norma: mesóclise (dir-lhe-ei) o próclise con sujeto (Eu lhe direi)."),
    (33, "colocacao", "Faria-se tudo por ela.", "Faria-se", "Far-se-ia",
     "Con condicional, mesóclise: far-se-ia."),
    (33, "colocacao", "Talvez digam-nos a verdade.", "digam-nos", "nos digam",
     "Talvez atrae el pronombre: talvez nos digam."),
    (33, "colocacao", "Espero que ajude-me.", "ajude-me", "me ajude",
     "Que atrae el pronombre: espero que me ajude."),
    (33, "colocacao", "Tudo fez-se como previsto.", "fez-se", "se fez",
     "Tudo (pronombre indefinido) atrae el pronombre: tudo se fez."),
    (33, "colocacao", "Quando viu-me, sorriu.", "viu-me", "me viu",
     "Las subordinadas atraen el pronombre: quando me viu."),
    (33, "colocacao", "Ninguém avisou-me da reunião.", "avisou-me", "me avisou",
     "Ninguém atrae el pronombre: ninguém me avisou."),
    (33, "colocacao", "Sempre esqueço-me do nome dela.", "esqueço-me", "me esqueço",
     "Sempre (adverbio) atrae el pronombre: sempre me esqueço."),
    (33, "colocacao", "Já deram-lhe o prêmio.", "deram-lhe", "lhe deram",
     "Já atrae el pronombre: já lhe deram."),
    (43, "colocacao", "Prezado senhor, me dirijo a V. Sa. para solicitar informações.", "me dirijo", "dirijo-me",
     "En una carta formal no se empieza la oración con pronombre átono: dirijo-me."),
    (33, "colocacao", "Me parece, senhor diretor, que os dados estão incompletos.", "Me parece", "Parece-me",
     "En la escritura formal no se empieza con pronombre: parece-me. (En el habla de Brasil, me parece es normal.)"),

    # ------------------------------------------------------------------
    # CRASE
    # ------------------------------------------------------------------
    (7, "crase", "Chegamos as três da tarde.", "as", "às",
     "Con las horas va crase: às três, às oito (a + as)."),
    (36, "crase", "Amanhã vou a praia com a Bia.", "a praia", "à praia",
     "Ir a + a praia = à praia. Truco: con un masculino sería «ao mar»."),
    (36, "crase", "Fui à Portugal em 2019.", "à", "a",
     "Portugal no lleva artículo: fui a Portugal. Sin artículo no hay crase."),
    (36, "crase", "Entreguei o relatório à ele.", "à", "a",
     "Nunca crase ante pronombre personal: a ele, a você."),
    (36, "crase", "De repente começou à chover.", "à", "a",
     "Nunca crase ante verbo: começou a chover."),
    (36, "crase", "Fomos à pé até o Arpoador.", "à", "a",
     "Pé es masculino: a pé, sin crase."),
    (36, "crase", "Refiro-me a aquela casa amarela.", "a aquela", "àquela",
     "a + aquela = àquela."),
    (36, "crase", "Assisti a peça no Theatro Municipal.", "a peça", "à peça",
     "Assistir a + a peça = à peça."),
    (36, "crase", "Pedi um bife a milanesa.", "a milanesa", "à milanesa",
     "À moda de: bife à milanesa, frango à passarinho."),
    (36, "crase", "Trabalho de segunda à sexta.", "à", "a",
     "De… a… sin artículo, sin crase: de segunda a sexta. Con artículo: da segunda à sexta."),
    (36, "crase", "A loja abre das nove as seis.", "as", "às",
     "Das… às…: das nove às seis."),
    (36, "crase", "Amanhã vou à Brasília.", "à", "a",
     "Brasília no lleva artículo (vim de Brasília): vou a Brasília."),
    (36, "crase", "Dei o livro à você.", "à", "a",
     "Nunca crase ante você."),
    (36, "crase", "Obedeça as regras do condomínio.", "as regras", "às regras",
     "Obedecer a + as regras = às regras."),
    (36, "crase", "Estou disposto à ajudar.", "à", "a",
     "Ante infinitivo no hay crase: disposto a ajudar."),
    (36, "crase", "Vou a Bahia nas férias.", "a Bahia", "à Bahia",
     "A Bahia lleva artículo (venho da Bahia): vou à Bahia."),
    (36, "crase", "Fez tudo as pressas.", "as pressas", "às pressas",
     "Locuciones femeninas llevan crase: às pressas, à noite, às vezes."),
    (41, "crase", "Machado de Assis dedicou a vida à literatura e a Academia.", "a Academia", "à Academia",
     "Dedicar a + a Academia = à Academia."),
]
