# -*- coding: utf-8 -*-
"""Ejemplos para las palabras de la semana que ningún ejercicio ni oración del
banco ilustra.  Una frase corta por palabra, con la gramática de su semana o
anterior (build_course.py las usa como último recurso, después de las
oraciones de la semana y de las del banco cuyo «w» ya se enseñó)."""

ESEMPI = {
    # semanas 1-4: essere, avere, sustantivos, artículos, adjetivos
    "volere": "Vuole un caffè, signore?",
    "prendere": "Prendo un caffè, grazie.",
    "cugino": "Mio cugino ha vent'anni.",
    "dovere": "Devo studiare stasera.",
    "signore": "Buongiorno, signore!",
    "zia": "Mia zia è di Roma.",
    "valigia": "La valigia è grande.",
    "zucchero": "Un caffè con zucchero, per favore.",
    "bambina": "La bambina ha sette anni.",
    "scrivere": "Scrivo una mail al professore.",
    "portare": "Porto il vino alla festa.",
    "camicia": "La camicia è bianca.",
    "burro": "Pane e burro per colazione.",
    "insegnante": "L'insegnante è simpatica.",
    "bravo": "Marco è un bravo studente.",
    "donna": "Quella donna è mia madre.",
    # 5-10: presente, números, preguntas, preposiciones, pronombres
    "sera": "Ci vediamo domani sera.",
    "compito": "Faccio i compiti dopo cena.",
    "chilo": "Un chilo di mele, per favore.",
    "zero": "Il numero comincia con zero.",
    "albero": "L'albero davanti a casa mia è altissimo.",
    # 11-13: passato prossimo, reflexivos
    "scegliere": "Ho scelto il vino rosso.",
    "nonno": "Mio nonno ha novant'anni.",
    "ritornare": "Siamo ritornati a casa tardi.",
    "fermarsi": "Il treno si ferma a Bologna.",
    "povero": "Povero Luca, ha perso il treno!",
    "cartolina": "Ti ho mandato una cartolina da Venezia.",
    "scendere": "Scendo alla prossima fermata.",
    "cappotto": "Mettiti il cappotto, fa freddo.",
    # 14-18: piacere, imperfetto, posesivos
    "meraviglioso": "Il tramonto era meraviglioso.",
    "pochissimo": "Ho dormito pochissimo stanotte.",
    "biscotto": "I miei biscotti preferiti sono quelli al cioccolato.",
    "cappello": "Questo cappello è di mio nonno.",
    "parola": "Non capisco questa parola.",
    "magari": "Magari domani non piove!",
    "carità": "Per carità, non parlarmi di lavoro!",
    "figurati": "Grazie mille! — Figurati!",
    "pasticcio": "Che pasticcio, ho perso le chiavi!",
    "boh": "Dov'è Marco? — Boh, non lo so.",
    # 19-23: futuro, condicional, ne/ci, combinados, comparativos
    "stipendio": "Lo stipendio arriverà il ventisette.",
    "leggero": "Stasera vorrei una cena leggera.",
    "inquinare": "Le macchine inquinano l'aria della città.",
    "sistemare": "Domani sistemerò la camera.",
    "abituarsi": "Mi sono abituato al caffè senza zucchero.",
    "cipolla": "Ne vuoi un po'? Sono cipolle di Tropea.",
    "tonno": "Una scatola di tonno, per favore.",
    "scatola": "Ne ho comprate due scatole.",
    "salsiccia": "Un panino con la salsiccia, per favore.",
    "vongola": "Gli spaghetti alle vongole sono buonissimi.",
    "dappertutto": "Ho cercato le chiavi dappertutto.",
    "etto": "Due etti di prosciutto, per favore.",
    "prosciutto": "Me lo dai il prosciutto crudo?",
    "panino": "Te lo preparo io, il panino.",
    "permettere": "Non me lo permettono.",
    "stretto": "Questa strada è più stretta di quella.",
    "accomodarsi": "Prego, si accomodi!",
    "laurearsi": "Mi sono laureata in giugno.",
    "prete": "Il prete del paese è più giovane di me.",
    # 27-31: adverbios, conectores, congiuntivo pasado, condicional pasado
    "raro": "È un caso raro.",
    "singolarmente": "Ha salutato tutti singolarmente.",
    "commessa": "La commessa mi ha risposto gentilmente.",
    "vincere": "Tuttavia, la nostra squadra ha vinto.",
    "affare": "È stato un buon affare.",
    "guadagnare": "Vorrei che guadagnassi di più.",
    "assicurare": "Le avrei assicurato che tutto andava bene.",
    "bolletta": "Non ho ancora pagato la bolletta della luce.",
    # 32-38: concordancia, hipotético, relativos, pasiva, si, remoto, indirecto
    "fallo": "L'arbitro ha fischiato un fallo.",
    "squadra": "Pensavo che la squadra avesse già giocato.",
    "litigare": "Se non avessero litigato, sarebbero ancora insieme.",
    "debito": "Ha pagato tutti i debiti.",
    "pigro": "Il ragazzo che conosci è pigro.",
    "magazzino": "La merce che hai ordinato è nel magazzino.",
    "affittare": "La casa che affittiamo è in centro.",
    "esaurire": "I biglietti sono esauriti.",
    "punire": "Il ladro è stato punito.",
    "vigile": "Il vigile ha fermato la macchina.",
    "soffitto": "Il soffitto è stato dipinto di bianco.",
    "rifare": "Il lavoro va rifatto.",
    "stampare": "Il documento è stato stampato ieri.",
    "palazzo": "In quel palazzo si affittano appartamenti.",
    "giù": "Scese giù in fretta.",
    "disperato": "Era disperato: aveva perso tutto.",
    "operaio": "Gli operai lavorarono tutta la notte.",
    "dichiarare": "Dichiarò di non saperne niente.",
    "finanziario": "Il direttore finanziario ha detto che i conti sono in ordine.",
    # 40-52: C1
    "riscaldamento": "Ho fatto riparare il riscaldamento.",
    "gas": "La bolletta del gas è arrivata.",
    "prestito": "Mi ha fatto avere un prestito dalla banca.",
    "tifare": "Tifo per il Napoli da bambino.",
    "pettegolezzi": "Sento i vicini fare pettegolezzi.",
    "chiacchierare": "Le ho viste chiacchierare al bar.",
    "onda": "Guardavamo le onde infrangersi sugli scogli.",
    "infrangersi": "Ho sentito le onde infrangersi sulla scogliera.",
    "scogliera": "La casa è in cima alla scogliera.",
    "bevanda": "Che bevanda preferisci con la pizza?",
    "cioccolatino": "Ti ho portato dei cioccolatini per ringraziarti.",
    "attraversare": "Attraversando la strada, ho visto Anna.",
    "risparmiare": "Risparmiando un po', potremo viaggiare.",
    "cittadino": "Ogni cittadino ha il diritto di votare.",
    "baciare": "Si sono baciati sotto la pioggia.",
    "battere": "Ha battuto il pugno sul tavolo.",
    "prenotazione": "Ho una prenotazione a nome Parrino.",
    "naso": "Ha un nasone enorme, poverino.",
    "caratteraccio": "Ha un caratteraccio, ma è buono.",
    "debolina": "La connessione è un po' debolina.",
    "paroloni": "Usa sempre dei paroloni per sembrare colto.",
    "maluccio": "Come va? — Maluccio, sono stanco.",
    "undicesimo": "Abito all'undicesimo piano.",
    "oltre": "Oltre al lavoro, studia il francese.",
    "spiegazione": "Pertanto, esigo una spiegazione.",
    "server": "Il server ospita i dati di tutti i clienti.",
    "backup": "Ho fatto il backup prima di aggiornare.",
    "sedersi": "Si è seduto in prima fila.",
    "parcheggiare": "Ho parcheggiato in doppia fila.",
    "destro": "Mi fa male il ginocchio destro.",
    "pasticceria": "Compro i cornetti nella pasticceria sotto casa.",
    "biondo": "Ha i capelli biondi e gli occhi verdi.",
    "baffo": "Mio nonno aveva i baffi.",
    "tradire": "Non tradirò mai la sua fiducia.",
    "ristrutturare": "Faremo ristrutturare la cucina dall'architetto.",
    "pitturare": "Abbiamo fatto pitturare le camere di bianco.",
    "imbianchino": "L'imbianchino viene lunedì a pitturare le camere.",
    "stoffa": "Questa stoffa è di ottima qualità.",
    # revisión: ejemplos que usan la palabra con el sentido que muestra la lista
    "sposarsi": "Si sono sposati l'anno scorso.",
    "salire": "Salgo le scale a piedi.",
    "purtroppo": "Purtroppo non posso venire alla festa.",
    "gonna": "Ho scelto quella gonna rossa.",
    "successo": "Il libro ha avuto un grande successo.",
    "seccato": "Sono un po' seccato con Marco.",
    "lieti": "Siamo lieti che siate venuti.",
    "comunque": "Piove, ma usciamo comunque.",
    "pregare": "Ti prego, non dirlo a nessuno.",
    "formaggio": "Sono tre etti di formaggio, signore. Gliene tolgo un po'?",
    "bocciati": "Siamo stati bocciati tutti quanti. – Davvero? Chi ve l'ha detto?",
    "soltanto": "Ce n'è soltanto uno: non ci basta.",
    "bistecca": "A Mario piace la bistecca alla fiorentina.",
    "postino": "Il postino passa ogni mattina alle dieci.",
    "mattone": "La casa è fatta di mattoni rossi.",
    "uscire": "Esco di casa alle otto.",
    "trovare": "Non trovo le chiavi.",
    "dipinto": "Questo dipinto è di Caravaggio.",
}

# Formas y nombres que el índice del glosario trae como si fueran palabras y
# que no son vocabulario de la semana (nombres propios, formas conjugadas).
NON_PAROLE = {
    "luigi", "renzo", "realma", "cinzia", "edoardo", "cyrano",
    "miagolavano", "sgriderò", "sgridato", "dimetta", "ritenuto", "distrutta",
    "sorvolano", "ospita", "ringraziarti", "ricoperto",
}
