# -*- coding: utf-8 -*-
"""Ejemplos para las palabras de la semana que ningún ejercicio ni oración del
banco ilustra.  Una frase corta por palabra, con la gramática de su semana o
anterior (build_course.py las usa como último recurso, después de las
oraciones de la semana y de las del banco cuyo «w» ya se enseñó).

Criterio de gramática por nivel de la palabra (curriculo.TENSE_WEEK):
- A1: sin verbo, o ser / estar / ter / há en presente (semanas 1-4); los
  verbos, en presente (desde la 5).
- A2 (desde la semana 9): presente, ir + infinitivo, perfeito.
- B1 (desde la 19): además imperfeito, futuro y condicional.
- B2 / C1 (desde la 31): cualquier tiempo, subjuntivos incluidos.
Ambientación carioca, como el resto del curso.
"""

ESEMPI = {
    # --- A1: sustantivos y adjetivos (ser, estar, ter, há) ---
    "praia": "A praia de Copacabana está cheia hoje.",
    "cidade": "O Rio é uma cidade linda.",
    "bairro": "Santa Teresa é um bairro antigo.",
    "rua": "A minha rua é tranquila.",
    "casa": "A casa da Ana tem uma varanda grande.",
    "apartamento": "O apartamento é pequeno, mas tem vista para o mar.",
    "quarto": "O quarto do hotel tem ar-condicionado.",
    "cozinha": "A cozinha é pequena.",
    "banheiro": "O banheiro fica no corredor.",
    "janela": "Da janela, há uma vista do Pão de Açúcar.",
    "mesa": "Há uma mesa livre no boteco.",
    "cadeira": "A cadeira está quebrada.",
    "chave": "A chave está na bolsa.",
    "geladeira": "A cerveja está na geladeira.",
    "leite": "O leite está na geladeira.",
    "pão": "O pão francês está quentinho.",
    "queijo": "O pão de queijo é de Minas.",
    "café": "O café do Brasil é famoso.",
    "suco": "O suco de maracujá é o meu favorito.",
    "água": "A água de coco está gelada.",
    "cerveja": "A cerveja está bem gelada.",
    "comida": "A comida baiana é muito boa.",
    "fruta": "Há muita fruta na feira.",
    "feira": "A feira de domingo tem frutas e pastel.",
    "mercado": "O mercado fica perto da estação.",
    "metrô": "O metrô está lotado.",
    "ônibus": "O ônibus para Ipanema está atrasado.",
    "carro": "O carro do João é branco.",
    "trem": "O trem para o Maracanã está cheio.",
    "família": "A família da Bia é de Salvador.",
    "irmão": "O meu irmão tem vinte anos.",
    "irmã": "A minha irmã é médica.",
    "avó": "A minha avó tem noventa anos.",
    "avô": "O meu avô é português.",
    "filho": "O filho da Carla tem cinco anos.",
    "amigo": "O Rafa é um amigo do trabalho.",
    "namorado": "O namorado da Sofía é carioca.",
    "vizinho": "O meu vizinho é muito simpático.",
    "criança": "A criança está na praia com a mãe.",
    "nome": "O meu nome é Martín.",
    "sobrenome": "O meu sobrenome é Pérez.",
    "aniversário": "Hoje é o aniversário da Ana.",
    "dia": "O dia está lindo.",
    "noite": "A noite na Lapa é animada.",
    "manhã": "A manhã está fresca.",
    "tarde": "A tarde está quente.",
    "semana": "A semana tem sete dias.",
    "calor": "Estou com calor.",
    "fome": "Estou com fome.",
    "sede": "Você está com sede?",
    "sono": "As crianças estão com sono.",
    "dinheiro": "Não tenho dinheiro.",
    "preço": "O preço está bom.",
    "conta": "A conta, por favor.",
    "tempo": "Hoje o tempo está bom.",
    "chuva": "Há muita chuva no verão.",
    "sol": "O sol está forte.",
    "mar": "O mar está calmo hoje.",
    "árvore": "A árvore da praça é muito alta.",
    "cachorro": "O cachorro do vizinho é pequeno.",
    "gato": "O gato está no sofá.",
    "médico": "O médico é muito bom.",
    "escritório": "O escritório fica no centro.",
    "trabalho": "O meu trabalho é perto de casa.",
    "escola": "A escola fica em Botafogo.",
    "aula": "A aula de português é às oito.",
    "professor": "O professor é de Recife.",
    "livro": "O livro está em cima da mesa.",
    "palavra": "Esta palavra é difícil.",
    "pergunta": "Tenho uma pergunta.",
    "óculos": "Os óculos estão na mesa.",
    "bonito": "O Arpoador é muito bonito.",
    "lindo": "O pôr do sol é lindo.",
    "legal": "O professor é muito legal.",
    "chato": "O filme é chato.",
    "grande": "O Maracanã é um estádio grande.",
    "pequeno": "O quarto é pequeno.",
    "barato": "O pastel da feira é barato.",
    "caro": "O restaurante é caro.",
    "cansado": "Estou muito cansado.",
    "feliz": "A Bia está feliz.",
    "gostoso": "O açaí é muito gostoso.",
    "quente": "O café está quente.",
    "gelado": "O chope está gelado.",
    "cheio": "O ônibus está cheio.",
    "fechado": "O museu está fechado hoje.",
    "aberto": "O mercado está aberto.",
    "novo": "O celular é novo.",
    "velho": "O prédio é muito velho.",
    "vermelho": "O vestido é vermelho.",
    "roxo": "O céu está roxo no pôr do sol.",
    "esquisito": "Este sorvete tem um gosto esquisito.",

    # --- A1: verbos (presente) ---
    "morar": "Moro em Copacabana, perto da praia.",
    "trabalhar": "Trabalho no centro do Rio.",
    "gostar": "Eu gosto muito de samba.",
    "precisar": "Preciso de um café.",
    "falar": "Você fala português?",
    "comer": "A gente come feijoada no sábado.",
    "beber": "Bebo água de coco na praia.",
    "abrir": "A loja abre às nove.",
    "chegar": "O ônibus chega às oito.",
    "voltar": "Volto para casa à noite.",
    "ficar": "O museu fica na praça.",
    "começar": "A aula começa às sete.",
    "tomar": "Tomo café com leite de manhã.",
    "pagar": "Pago com cartão.",
    "ligar": "Ligo para você amanhã.",
    "acordar": "Acordo cedo durante a semana.",
    "almoçar": "Almoço num restaurante a quilo.",
    "jantar": "A gente janta tarde.",
    "achar": "Acho que vai chover.",
    "conhecer": "Você conhece o Rio?",
    "entender": "Não entendo esta palavra.",
    "ouvir": "Ouço bossa nova de manhã.",
    "fazer": "O que você faz no fim de semana?",
    "ir": "Vou à praia no domingo.",
    "vir": "Você vem com a gente?",
    "querer": "Quero um pão de queijo, por favor.",
    "poder": "Posso entrar?",
    "saber": "Não sei o nome da rua.",
    "dar": "Dá para ir a pé?",
    "dizer": "O que você diz?",
    "pedir": "Peço um chope e uma porção de pastel.",
    "dormir": "Durmo oito horas por noite.",
    "sair": "Saio do trabalho às seis.",
    "ver": "Da janela, vejo o Cristo.",
    "ler": "Leio o jornal no metrô.",
    "trazer": "Trago a sobremesa.",

    # --- A2 (presente, ir + infinitivo, perfeito) ---
    "saudade": "Estou com saudade do Rio.",
    "calçadão": "Caminhei no calçadão de Copacabana.",
    "boteco": "Encontrei os amigos no boteco da esquina.",
    "chope": "Pedimos dois chopes bem gelados.",
    "pastel": "Comi um pastel de queijo na feira.",
    "biscoito": "Comprei biscoito Globo na praia.",
    "garrafa": "Compramos uma garrafa de vinho.",
    "copo": "Me dá um copo de água, por favor?",
    "xícara": "Tomei uma xícara de café.",
    "sobremesa": "De sobremesa, vou pedir pudim.",
    "presunto": "Comprei presunto e queijo para o lanche.",
    "salada": "Vou pedir uma salada de frutas.",
    "cardápio": "O garçom trouxe o cardápio.",
    "gorjeta": "Deixamos a gorjeta na mesa.",
    "troco": "O vendedor me deu o troco errado.",
    "passagem": "Comprei a passagem para Salvador.",
    "viagem": "A viagem para Paraty foi ótima.",
    "mala": "Fiz a mala ontem à noite.",
    "praça": "Nos encontramos na praça.",
    "ponte": "Atravessamos a ponte Rio–Niterói.",
    "calçada": "O carro está parado na calçada.",
    "sinal": "Vire à direita no sinal.",
    "morro": "Subimos o morro para ver o pôr do sol.",
    "barulho": "Tem muito barulho na rua.",
    "lixo": "Jogue o lixo na lixeira.",
    "dor": "Estou com dor de cabeça.",
    "remédio": "Comprei um remédio na farmácia.",
    "time": "O meu time ganhou ontem.",
    "torcida": "A torcida do Flamengo cantou o jogo inteiro.",
    "academia": "Vou à academia três vezes por semana.",
    "borracha": "Você tem uma borracha?",
    "polvo": "Comemos polvo num restaurante português.",
    "rato": "Vi um rato na cozinha!",
    "apelido": "O apelido dele é Rafa.",
    "férias": "Passei as férias em Búzios.",
    "novela": "A minha avó assiste à novela das nove.",
    "ingresso": "Comprei os ingressos para o show.",
    "celular": "Esqueci o celular em casa.",
    "senha": "Esqueci a senha do banco.",
    "mensagem": "Mandei uma mensagem para a Bia.",
    "tela": "A tela do celular quebrou.",
    "descobrir": "Descobri um bar ótimo na Lapa.",
    "esquecer": "Esqueci a chave do carro.",
    "lembrar": "Você lembra do nome dele?",
    "perder": "Perdi o ônibus de novo.",
    "ganhar": "Ganhei um livro de presente.",
    "pegar": "Peguei o metrô em Botafogo.",
    "levar": "Levei o guarda-chuva, mas não choveu.",
    "tirar": "Tirei muitas fotos no Cristo.",
    "passear": "Passeamos pela orla no domingo.",
    "procurar": "Estou procurando a chave.",
    "brincar": "As crianças brincam na areia.",
    "jogar": "Jogamos futevôlei em Ipanema.",
    "sonhar": "Sonhei com você esta noite.",
    "pensar": "Penso muito em você.",
    "casar": "O João casou com a Maria.",
    "namorar": "A Bia namora o Lucas há dois anos.",
    "assistir": "Assisti a um filme ótimo ontem.",
    "convidar": "A Ana me convidou para a festa.",
    "fechar": "O museu fecha às cinco.",
    "puxar": "Para abrir a porta, puxe.",
    "subir": "Subimos a escadaria Selarón.",
    "descer": "Desço do ônibus na próxima parada.",
    "chato": "Que chato! O show foi cancelado.",
    "pronto": "O jantar está pronto.",
    "ruim": "O filme foi muito ruim.",
    "comprido": "O calçadão é bem comprido.",
    "largo": "A avenida é larga.",
    "sozinho": "Viajei sozinho para o Rio.",
    "atrasado": "Cheguei atrasado na aula.",
    "ainda": "Ainda não conheço o Corcovado.",
    "logo": "Já volto, logo, logo!",
    "já": "Você já foi ao Maracanã?",
    "cadê": "Cadê o meu celular?",
    "demais": "O show foi demais!",
    "embora": "Já vou embora, gente.",

    # --- B1 (también imperfeito, futuro, condicional) ---
    "infância": "Na infância, eu passava as férias na praia.",
    "antigamente": "Antigamente, o bonde subia até Santa Teresa todo dia.",
    "costume": "Era costume almoçar na casa da avó aos domingos.",
    "bondinho": "O bondinho do Pão de Açúcar tinha fila enorme.",
    "escadaria": "A escadaria tem azulejos de muitos países.",
    "ladeira": "A ladeira era tão íngreme que parei no meio.",
    "orla": "Amanhã vamos correr na orla.",
    "previsão do tempo": "Segundo a previsão do tempo, vai chover amanhã.",
    "tempestade": "Vai ter uma tempestade à noite.",
    "promoção": "Ela vai receber uma promoção no trabalho.",
    "salário": "O salário vai sair no quinto dia útil.",
    "prazo": "O prazo termina na sexta-feira.",
    "reunião": "A reunião seria às dez, mas foi adiada.",
    "escritor": "Machado de Assis foi um grande escritor carioca.",
    "crônica": "Rubem Braga escrevia crônicas sobre o Rio.",
    "carnaval": "No carnaval, os blocos tomavam as ruas.",
    "escola de samba": "A escola de samba ensaiava na quadra toda semana.",
    "choro": "O choro nasceu no Rio no século XIX.",
    "golpe": "Cuidado com o golpe do pix.",
    "carona": "Você me daria uma carona até a Barra?",
    "encontro": "O nosso primeiro encontro foi num bar da Lapa.",
    "sucesso": "A música fez muito sucesso.",
    "pelada": "Todo sábado a gente jogava uma pelada na praia.",
    "preguiça": "Que preguiça de sair hoje!",
    "bagunça": "O quarto das crianças estava uma bagunça.",
    "jeito": "Vamos dar um jeito.",
    "esperto": "O menino era muito esperto.",
    "bravo": "A minha mãe ficou brava comigo.",
    "chateado": "Fiquei chateado com o atraso.",
    "maneiro": "O show de ontem foi muito maneiro.",
    "engraçado": "O filme era muito engraçado.",
    "abafado": "O dia estava abafado e úmido.",
    "lotado": "O metrô estava lotado.",
    "acostumar": "Já me acostumei com o calor do Rio.",
    "reclamar": "Ele reclamava de tudo.",
    "desistir": "Não vou desistir do meu sonho.",
    "confiar": "Confio muito em você.",
    "acreditar": "Eu não acreditava em nada daquilo.",
    "concordar": "Concordo com você.",
    "depender": "Tudo vai depender do tempo.",
    "torcer": "Você torce para qual time?",
    "apaixonar": "Ela se apaixonou pelo Rio.",
    "mudar": "Vamos mudar para Niterói no ano que vem.",
    "trocar": "Troquei a camisa por uma maior.",
    "emprestar": "Você me emprestaria o seu guarda-chuva?",
    "consertar": "O mecânico vai consertar o carro amanhã.",
    "desenhar": "Quando era criança, eu desenhava muito.",
    "curtir": "A gente curtiu muito o carnaval.",
    "paquerar": "Eles paqueravam na praia.",

    # --- B2 / C1 ---
    "prejuízo": "A enchente causou um prejuízo enorme.",
    "preconceito": "Não há espaço para preconceito aqui.",
    "desigualdade": "A desigualdade é visível entre o morro e o asfalto.",
    "tentativa": "Depois de três tentativas, ele conseguiu.",
    "êxito": "A campanha teve êxito.",
    "embora": "Embora chova, vamos à praia.",
    "caso": "Caso você precise, me ligue.",
    "desde que": "Pode ir, desde que volte cedo.",
    "tomara": "Tomara que faça sol amanhã!",
    "talvez": "Talvez eles venham mais tarde.",
    "quando": "Quando você for ao Rio, suba o Corcovado.",
    "se": "Se você quiser, a gente vai à Lapa.",
    "aliás": "Aliás, você já conhece o Arpoador?",
    "todavia": "O plano era bom; todavia, não funcionou.",
    "à toa": "Fiquei à toa o dia inteiro.",
    "saneamento": "O saneamento básico ainda não chegou a todos os bairros.",
    "cartório": "Tive que reconhecer firma no cartório.",
    "cafuné": "O filho dormiu com o cafuné da mãe.",
    "pechincha": "Aquele apartamento foi uma pechincha.",
    "fraude": "A polícia descobriu a fraude.",
}

# Formas y nombres que el índice del glosario trae como si fueran palabras y
# que no son vocabulario de la semana (nombres propios, formas coloquiales o
# conjugadas, siglas).
NON_PAROLE = {
    "joão", "bia", "rafa", "martín", "sofía", "lucas", "copacabana", "ipanema", "arpoador",
    "lapa", "botafogo", "leblon", "niterói", "maracanã", "corcovado", "flamengo", "vasco",
    "fluminense", "tijuca", "urca", "enem", "cpf", "rg", "sus",
    "tô", "tá", "tava", "tavam", "tamo", "cê", "cês", "vamo", "peraí", "vambora", "coé",
    "fizera", "dissera",
}
