# -*- coding: utf-8 -*-
"""Banco de oraciones español (rioplatense) → portugués de Brasil para los
ejercicios de traducción y de «verbo en contexto», con corrección automática.

Cada entrada: dict(es, it[list], lvl, w, tags[list], gap=(forma, lema) | None,
note).  La clave «it» (las traducciones aceptadas) conserva el nombre del
esquema italiano porque la leen app.js, banca.js y scrivi.js.

- `w`: semana mínima según la gramática que usa la traducción principal
  (tools/curriculo.py, TENSE_WEEK y WEEKS): nada antes de su teoría.  El
  contenido cultural (historia, literatura, sociología, filosofía y política
  de Brasil y Portugal) va desde la semana 27 y pesa más en la 40-52.
- `lvl`: sale de la semana (A1 1-8, A2 9-16, B1 17-27, B2 28-40, C1 41-52).
- `it`: la primera es la respuesta modelo; las demás, variantes aceptadas
  (con y sin pronombre sujeto, nós / a gente, vou + infinitivo / futuro,
  você / tu, contracción coloquial…).  Para escribirlas sin repetir, cada
  cadena admite alternativas entre llaves: «{Eu |}moro» = «Eu moro» y
  «moro».  La primera opción de cada llave arma la respuesta modelo.
- `gap`: (forma, lema) para el ejercicio de completar; la forma aparece tal
  cual en la respuesta modelo.

Las citas son reales y verificables; cuando una frase famosa es apócrifa, la
nota lo dice.
"""
import itertools as _it
import re as _re

_BRACE = _re.compile(r"\{([^{}]*)\}")
_MAX = 48


def _x(pattern):
    """Expande «{a|b}» en todas las combinaciones (primero, la modelo)."""
    parts = _BRACE.split(pattern)
    fixed, opts = parts[0::2], [p.split("|") for p in parts[1::2]]
    out = []
    for combo in _it.product(*opts):
        s = fixed[0]
        for o, f in zip(combo, fixed[1:]):
            s += o + f
        s = _re.sub(r"\s+", " ", s).strip()
        s = s[:1].upper() + s[1:]
        if s not in out:
            out.append(s)
        if len(out) >= _MAX:
            break
    return out


def _lvl(w):
    return "A1" if w <= 8 else "A2" if w <= 16 else "B1" if w <= 27 else "B2" if w <= 40 else "C1"


def _mk(rows):
    out = []
    for w, es, pt, tags, gap, note in rows:
        pats = [pt] if isinstance(pt, str) else list(pt)
        its = []
        for p in pats:
            for s in _x(p):
                if s.lower() not in [t.lower() for t in its]:
                    its.append(s)
        d = dict(es=es, it=its, lvl=_lvl(w), w=w, tags=tags.split(), note=note)
        if gap:
            d["gap"] = tuple(gap)
        out.append(d)
    return out


_ROWS = [
    # ================================================================ A1
    # --- semana 1: saludos, ser, estar, ter
    (1, "Hola, me llamo Martín.", ["{Oi|Olá}, {eu |}me chamo Martín.", "{Oi|Olá}, meu nome é Martín.", "{Oi|Olá}, chamo-me Martín."],
     "ser_estar lexico", None,
     "Me llamo = (eu) me chamo o meu nome é. Hola = oi (informal) u olá."),
    (1, "Soy argentino, de Buenos Aires.", "{Eu |}sou argentino, de Buenos Aires.",
     "ser_estar", ("sou", "ser"),
     "Soy = sou. El origen va con ser de: sou de Buenos Aires."),
    (1, "¿Vos sos brasileña?", ["Você é brasileira?", "Tu és brasileira?", "Tu é brasileira?"],
     "ser_estar", ("é", "ser"),
     "Vos = você, con el verbo en 3.ª persona: você é. Tu és existe, pero en Río se oye más você."),
    (3, "Ella es de Río; es carioca.", "Ela é do Rio{| de Janeiro}, {|ela }é carioca.",
     "ser_estar contracciones", ("é", "ser"),
     "Carioca = de la ciudad de Río (fluminense = del estado). Do Rio: el Rio lleva artículo."),
    (1, "Estoy bien, gracias.", "{Eu |}estou bem, {obrigado|obrigada}.",
     "ser_estar", ("estou", "estar"),
     "Gracias = obrigado si lo dice un hombre, obrigada si lo dice una mujer."),
    (1, "¿Cómo estás?", ["Como você está?", "Como vai?", "Como vai você?", "Tudo bem?", "Como tu estás?"],
     "ser_estar", ("está", "estar"),
     "¿Cómo estás? = como você está? o, más natural, tudo bem? / como vai?"),
    (1, "Tengo veinte años.", "{Eu |}tenho vinte anos.",
     "ter", ("tenho", "ter"),
     "La edad va con ter: tenho vinte anos. Año = ano (sin ñ)."),
    (1, "Tenemos un perro y un gato.", "{Nós temos|Temos|A gente tem} um {cachorro|cão} e um gato.",
     "ter lexico", ("temos", "ter"),
     "Perro = cachorro (o cão). A gente tem = nosotros tenemos, con verbo en singular."),
    (3, "Ellos están en la playa.", "Eles estão na praia.",
     "ser_estar contracciones", ("estão", "estar"),
     "em + a = na: na praia. Estão lleva tilde nasal."),
    (3, "Mi madre es profesora.", "{A |}minha mãe é professora.",
     "ser_estar posesivos", ("é", "ser"),
     "Ante posesivo el artículo es optativo en Brasil: minha mãe o a minha mãe."),
    (1, "Somos amigos.", "{Nós somos|Somos|A gente é} amigos.",
     "ser_estar", ("somos", "ser"),
     "Somos = somos; con a gente, el verbo va en singular: a gente é amigo(s)."),
    (3, "¿Dónde está el baño?", ["Onde {está|fica|é} o banheiro?"],
     "ser_estar lexico", ("está", "estar"),
     "El baño = o banheiro. Para ubicar se usa mucho ficar: onde fica o banheiro?"),
    (1, "Buen día, señora.", "Bom dia, {senhora|dona}.",
     "lexico", None,
     "Buen día = bom dia (en singular). Señora = senhora; ante nombre de pila, dona: dona Maria."),
    (1, "¡Chau, hasta mañana!", "Tchau, até amanhã!",
     "lexico", None,
     "Chau = tchau; hasta = até; mañana = amanhã."),
    (1, "Muchas gracias.", "Muito {obrigado|obrigada}.",
     "muito lexico", None,
     "Muchas gracias = muito obrigado / obrigada (no «muitas»)."),
    (1, "Estamos muy contentos.", "{Nós estamos|Estamos|A gente está} muito {contentes|felizes}.",
     "ser_estar muito", ("estamos", "estar"),
     "Muy = muito; contento = contente o feliz."),
    (1, "¿Tenés hermanos?", ["Você tem irmãos?", "Tu tens irmãos?", "Tu tem irmãos?"],
     "ter", ("tem", "ter"),
     "Vos tenés = você tem. Hermanos = irmãos."),

    # --- semana 2: sustantivos, género y número
    (3, "Hay un libro en la mesa.", ["{Tem|Há} um livro {na|em cima da} mesa."],
     "ter articulos contracciones", ("Tem", "ter"),
     "Hay = tem (habla) o há (escrito)."),
    (4, "La leche está fría.", "O leite está {frio|gelado}.",
     "genero concordancia", ("está", "estar"),
     "Leite es masculino: o leite está frio."),
    (2, "Tengo dolor de cabeza.", ["{Eu |}{estou com|tenho} dor de cabeça."],
     "genero ter", None,
     "Dor es femenino (a dor). Me duele la cabeza = estou com dor de cabeça."),
    (2, "Tengo dos hermanos y una hermana.", "{Eu |}tenho dois irmãos e uma irmã.",
     "plurales genero", ("tenho", "ter"),
     "Irmão → irmãos; irmã, con tilde nasal."),
    (4, "El viaje es largo.", "A viagem é {longa|comprida}.",
     "genero falsos_amigos", ("é", "ser"),
     "Viagem es femenino. Largo = longo, comprido («largo» en portugués es ancho)."),
    (2, "La ciudad tiene muchos árboles.", "A cidade tem muitas árvores.",
     "genero muito", ("tem", "ter"),
     "Árvore es femenino: muitas árvores. Ciudad = cidade."),
    (4, "Mis manos están frías.", "{As |}minhas mãos estão {frias|geladas}.",
     "plurales concordancia", ("estão", "estar"),
     "Mão → mãos (no «mões»)."),
    (3, "Hay tres limones en la heladera.", "{Tem|Há} três limões na geladeira.",
     "plurales lexico", None,
     "Limão → limões. Heladera = geladeira."),
    (3, "El mensaje es de Bia.", "A mensagem é da Bia.",
     "genero contracciones", ("é", "ser"),
     "Las palabras en -agem son femeninas: a mensagem, a viagem."),
    (3, "La sal está en la mesa.", "O sal está na mesa.",
     "genero contracciones", ("está", "estar"),
     "Sal es masculino en portugués: o sal."),
    (4, "El puente es muy lindo.", "A ponte é muito {bonita|linda}.",
     "genero concordancia", ("é", "ser"),
     "Ponte es femenino: a ponte é bonita."),
    (2, "Tengo una pregunta.", "{Eu |}tenho uma pergunta.",
     "ter lexico", None,
     "Pregunta = pergunta."),
    (3, "Los hombres están en el bar.", "Os homens estão no bar.",
     "plurales contracciones", ("estão", "estar"),
     "Homem → homens (-m → -ns)."),
    (4, "Los hoteles de Copacabana son caros.", "Os hotéis de Copacabana são caros.",
     "plurales", ("são", "ser"),
     "Hotel → hotéis (-el → -éis)."),
    (2, "La computadora es nueva.", "O computador é novo.",
     "genero", ("é", "ser"),
     "Computador es masculino: o computador é novo."),

    # --- semana 3: artículos y contracciones
    (3, "Estoy en la playa de Copacabana.", "{Eu |}estou na praia de Copacabana.",
     "contracciones", ("estou", "estar"),
     "em + a = na: na praia."),
    (3, "El libro de João está en la mochila.", "O livro do João está na mochila.",
     "contracciones articulos", ("está", "estar"),
     "de + o = do; em + a = na. Ante nombre de persona el artículo es común en Río: o João."),
    (3, "La casa de Ana está en el centro.", "A casa da Ana {está|fica|é} no centro.",
     "contracciones", ("está", "estar"),
     "de + a = da; em + o = no."),
    (3, "Estamos en el bar de la esquina.", "{Nós estamos|Estamos|A gente está} no bar da esquina.",
     "contracciones", ("estamos", "estar"),
     "em + o = no; de + a = da."),
    (3, "Mi celular está en la cartera.", "{O |}meu celular está na bolsa.",
     "contracciones falsos_amigos", ("está", "estar"),
     "La cartera (de mujer) = a bolsa. La carteira es la billetera."),
    (3, "La capital de Brasil es Brasilia.", "A capital do Brasil é Brasília.",
     "contracciones articulos", ("é", "ser"),
     "O Brasil lleva artículo: do Brasil."),
    (3, "El Cristo está en el Corcovado.", "O Cristo{| Redentor} está no Corcovado.",
     "contracciones", ("está", "estar"),
     "em + o = no: no Corcovado."),
    (3, "Las llaves están en la puerta.", "As chaves estão na porta.",
     "contracciones lexico", ("estão", "estar"),
     "Llave = chave; puerta = porta."),
    (3, "Los chicos están en los cuartos.", "{Os meninos|As crianças} estão nos quartos.",
     "contracciones", ("estão", "estar"),
     "em + os = nos. Los chicos (niños) = as crianças, os meninos."),
    (3, "El Pan de Azúcar está en Urca.", "O Pão de Açúcar {está|fica} na Urca.",
     "contracciones", ("está", "estar"),
     "A Urca, el barrio, lleva artículo: na Urca."),
    (3, "Estoy en casa.", "{Eu |}estou em casa.",
     "articulos", ("estou", "estar"),
     "El propio hogar va sin artículo: em casa."),
    (3, "¿Estás en el trabajo?", ["Você está no trabalho?", "Tu estás no trabalho?", "Tá no trabalho?"],
     "contracciones", ("está", "estar"),
     "em + o = no trabalho."),
    (3, "El vaso está en la mesa.", "O copo está {na|em cima da|sobre a} mesa.",
     "falsos_amigos contracciones", ("está", "estar"),
     "El vaso = o copo. El vaso portugués es una maceta."),
    (3, "Los turistas están en el hotel.", "Os turistas estão no hotel.",
     "contracciones", ("estão", "estar"),
     "em + o = no."),
    (3, "El perro de los vecinos está en la calle.", "O cachorro dos vizinhos está na rua.",
     "contracciones lexico", ("está", "estar"),
     "de + os = dos; calle = rua; vecino = vizinho."),
    (3, "La Lagoa está cerca de Ipanema.", "A Lagoa {está|fica} perto de Ipanema.",
     "preposiciones", ("está", "estar"),
     "Cerca de = perto de."),

    # --- semana 4: adjetivos, colores, nacionalidades, muito
    (4, "Ella es muy simpática.", "Ela é muito simpática.",
     "muito concordancia", ("é", "ser"),
     "Muy = muito: muito simpática."),
    (4, "Somos argentinos, pero ella es portuguesa.", "{Nós somos|Somos|A gente é} argentinos, mas ela é portuguesa.",
     "concordancia ser_estar", ("somos", "ser"),
     "Pero = mas. Português → portuguesa."),
    (4, "El mar está muy azul hoy.", ["O mar está muito azul hoje.", "Hoje o mar está muito azul."],
     "muito", ("está", "estar"),
     "Hoy = hoje; muy = muito."),
    (4, "Las remeras son blancas.", "As camisetas são brancas.",
     "concordancia lexico", ("são", "ser"),
     "Remera = camiseta; blanco = branco."),
    (4, "El departamento es chico pero lindo.", "O apartamento é pequeno, mas {é |}{bonito|lindo}.",
     "concordancia lexico", ("é", "ser"),
     "Departamento = apartamento; chico = pequeno."),
    (4, "Mi abuela es alemana.", "{A |}minha avó é alemã.",
     "concordancia", ("é", "ser"),
     "Alemão → alemã. Avó (abuela) con o abierta."),
    (4, "Los ejercicios son fáciles.", "Os exercícios são fáceis.",
     "plurales", ("são", "ser"),
     "Fácil → fáceis."),
    (4, "Ella tiene ojos azules.", "Ela tem olhos azuis.",
     "plurales ter", ("tem", "ter"),
     "Azul → azuis; ojo = olho."),
    (4, "El hotel es caro, pero es muy cómodo.", "O hotel é caro, mas é muito confortável.",
     "muito lexico", ("é", "ser"),
     "Cómodo = confortável; muy = muito."),
    (4, "La playa está llena.", "A praia está {cheia|lotada}.",
     "concordancia", ("está", "estar"),
     "Lleno = cheio (llena = cheia)."),
    (4, "Ellos son muy altos.", "Eles são muito altos.",
     "muito concordancia", ("são", "ser"),
     "Son = são."),
    (4, "Estoy muy cansada.", "{Eu |}estou muito cansada.",
     "muito ser_estar", ("estou", "estar"),
     "Estoy = estou."),
    (4, "Río es una ciudad muy linda.", "O Rio é uma cidade muito {linda|bonita}.",
     "muito articulos", ("é", "ser"),
     "O Rio lleva artículo."),
    (4, "Tengo mucho trabajo.", "{Eu |}tenho muito trabalho.",
     "muito ter", ("tenho", "ter"),
     "Mucho = muito; trabajo = trabalho."),
    (4, "Hay mucha gente en la feria.", "{Tem|Há} muita gente na feira.",
     "muito", None,
     "Mucha gente = muita gente (femenino singular)."),
    (4, "El agua está fría.", "A água está {fria|gelada}.",
     "concordancia", ("está", "estar"),
     "Água es femenino: fria."),
    (4, "Los pasteles de la feria son buenísimos.", ["Os pastéis da feira são {ótimos|muito bons|deliciosos}."],
     "plurales falsos_amigos", ("são", "ser"),
     "Pastel → pastéis: la empanada frita de la feira."),
    (4, "La remera roja es de Rafa.", "A camiseta vermelha é do Rafa.",
     "concordancia lexico", ("é", "ser"),
     "Rojo = vermelho (roxo es morado)."),
    (4, "Mis amigos son uruguayos.", "{Os |}meus amigos são uruguaios.",
     "concordancia", ("são", "ser"),
     "Uruguayo = uruguaio."),
]

_ROWS += [
    # --- semana 5: presente regular, você, a gente
    (5, "Vivo en Botafogo.", "{Eu |}{moro|vivo} em Botafogo.",
     "presente preposiciones", ("moro", "morar"),
     "Vivir (residir) = morar: moro em Botafogo."),
    (5, "¿Dónde vivís?", ["Onde você mora?", "Você mora onde?", "Onde tu moras?", "Onde você vive?"],
     "presente preguntas", ("mora", "morar"),
     "Vos vivís = você mora (verbo en 3.ª persona)."),
    (5, "Trabajo en una oficina en el centro.", "{Eu |}trabalho {num|em um} escritório no centro.",
     "presente falsos_amigos", ("trabalho", "trabalhar"),
     "Oficina = escritório. La oficina portuguesa es un taller."),
    (5, "Hablamos portugués y español.", "{Nós falamos|Falamos|A gente fala} português e espanhol.",
     "presente", ("falamos", "falar"),
     "Hablar = falar. A gente fala = nosotros hablamos."),
    (5, "Ella estudia medicina en la UFRJ.", "Ela estuda medicina na UFRJ.",
     "presente contracciones", ("estuda", "estudar"),
     "Estudiar = estudar."),
    (5, "Comemos arroz y porotos todos los días.", "{Nós comemos|Comemos|A gente come} arroz e feijão {todos os dias|todo dia}.",
     "presente lexico", ("comemos", "comer"),
     "Porotos = feijão; todos los días = todos os dias o todo dia."),
    (5, "¿Tomás café?", ["Você toma café?", "Você bebe café?", "Tu tomas café?"],
     "presente", ("toma", "tomar"),
     "Vos tomás = você toma."),
    (5, "Mis padres viven en Rosario.", "{Os |}meus pais moram em Rosario.",
     "presente posesivos", ("moram", "morar"),
     "Padres = pais; viven = moram."),
    (5, "Compramos fruta en la feria.", "{Nós compramos|Compramos|A gente compra} fruta na feira.",
     "presente", ("compramos", "comprar"),
     "La feria = a feira (el mercado callejero)."),
    (5, "Los chicos escuchan samba.", "{Os meninos|As crianças|Os garotos} escutam samba.",
     "presente", ("escutam", "escutar"),
     "Escuchar = escutar (u ouvir)."),
    (5, "Ustedes trabajan mucho.", "Vocês trabalham muito.",
     "presente muito", ("trabalham", "trabalhar"),
     "Ustedes = vocês, con verbo en 3.ª plural."),
    (5, "Siempre almuerzo en casa.", ["{Eu |}sempre almoço em casa.", "Almoço sempre em casa."],
     "presente", ("almoço", "almoçar"),
     "Almorzar = almoçar."),
    (5, "Ana corre en el calçadão todas las mañanas.", "{A |}Ana corre no calçadão {todas as manhãs|toda manhã|todo dia de manhã}.",
     "presente contracciones", ("corre", "correr"),
     "El calçadão es la rambla de Copacabana e Ipanema."),
    (5, "Vivimos cerca de la playa.", "{Nós moramos|Moramos|A gente mora} perto da praia.",
     "presente preposiciones", ("moramos", "morar"),
     "Cerca de = perto de; de + a = da."),
    (5, "¿Ustedes hablan inglés?", "Vocês falam inglês?",
     "presente", ("falam", "falar"),
     "Ustedes hablan = vocês falam."),
    (5, "Mi hermano vende helado en la playa.", "{O |}meu irmão vende sorvete na praia.",
     "presente lexico", ("vende", "vender"),
     "Helado = sorvete."),
    (5, "Escribo mails en portugués.", "{Eu |}escrevo e-mails em português.",
     "presente", ("escrevo", "escrever"),
     "Escribir = escrever."),
    (5, "Ella no fuma.", "Ela não fuma.",
     "presente", ("fuma", "fumar"),
     "No = não."),
    (5, "Abrimos la ventana porque hace calor.", "{Nós abrimos|Abrimos|A gente abre} a janela porque {está|faz} calor.",
     "presente", ("abrimos", "abrir"),
     "Ventana = janela; hace calor = está calor / faz calor."),
    (5, "¿A qué te dedicás? — Soy mozo.", ["O que você faz? — Sou garçom.", "Você trabalha com o quê? — Sou garçom."],
     "presente lexico", None,
     "Mozo = garçom."),
    (7, "A la noche miramos la tele.", ["À noite {nós assistimos|assistimos|a gente assiste} televisão.", "À noite {nós vemos|vemos|a gente vê} televisão."],
     "presente", ("assistimos", "assistir"),
     "Ver la tele = assistir (à) televisão o ver televisão. A la noche = à noite."),
    (5, "Bia vive sola.", "{A |}Bia mora sozinha.",
     "presente lexico", ("mora", "morar"),
     "Solo (sin compañía) = sozinho, sozinha."),
    (5, "Ustedes necesitan descansar.", "Vocês precisam descansar.",
     "presente", ("precisam", "precisar"),
     "Necesitar = precisar; ante infinitivo, sin de."),
    (5, "Los domingos cocino para la familia.", "{Aos|Nos} domingos {eu |}cozinho para a família.",
     "presente", ("cozinho", "cozinhar"),
     "Cocinar = cozinhar."),
    (5, "El museo cierra a las cinco.", "O museu fecha às cinco.",
     "presente falsos_amigos", ("fecha", "fechar"),
     "Cerrar = fechar («fecha» es cierra, no la fecha)."),
    (5, "Pago con tarjeta.", "{Eu |}pago {com|no} cartão.",
     "presente", ("pago", "pagar"),
     "Tarjeta = cartão."),

    # --- semana 6: presente irregular
    (6, "Voy a la playa los domingos.", ["{Eu |}vou {para a|à} praia {aos|nos} domingos.", "{Eu |}vou {para a|à} praia todo domingo."],
     "irregulares presente", ("vou", "ir"),
     "Voy = vou. Ir a la playa = ir para a praia (o à praia)."),
    (6, "¿Qué hacés los fines de semana?", ["O que você faz {nos|aos} fins de semana?", "O que tu fazes {nos|aos} fins de semana?"],
     "irregulares preguntas", ("faz", "fazer"),
     "Hacer = fazer: você faz."),
    (6, "No puedo salir hoy.", ["{Eu |}não posso sair hoje.", "Hoje {eu |}não posso sair."],
     "irregulares", ("posso", "poder"),
     "Puedo = posso."),
    (6, "Quiero un jugo de naranja.", "{Eu |}quero um suco de laranja.",
     "irregulares lexico", ("quero", "querer"),
     "Jugo = suco; naranja = laranja."),
    (6, "No sé.", "{Eu |}não sei.",
     "irregulares", ("sei", "saber"),
     "Sé = sei."),
    (6, "Vengo de Córdoba.", "{Eu |}venho de Córdoba.",
     "irregulares", ("venho", "vir"),
     "Venir = vir: eu venho, você vem."),
    (6, "Él dice que sí.", "Ele diz que sim.",
     "irregulares", ("diz", "dizer"),
     "Decir = dizer: ele diz."),
    (6, "Doy clases de español.", "{Eu |}dou aulas de espanhol.",
     "irregulares falsos_amigos", ("dou", "dar"),
     "La clase = a aula (el aula = a sala de aula)."),
    (7, "Salgo del trabajo a las seis.", "{Eu |}saio do trabalho às seis.",
     "irregulares horas", ("saio", "sair"),
     "Salir = sair: eu saio."),
    (6, "Pido una caipirinha.", "{Eu |}peço uma caipirinha.",
     "irregulares", ("peço", "pedir"),
     "Pedir = pedir, pero eu peço."),
    (6, "Duermo poco.", "{Eu |}durmo pouco.",
     "irregulares", ("durmo", "dormir"),
     "Dormir → eu durmo."),
    (6, "Hacemos un asado el sábado.", "{Nós fazemos|Fazemos|A gente faz} um churrasco no sábado.",
     "irregulares lexico", ("fazemos", "fazer"),
     "Asado = churrasco."),
    (6, "¿Podés repetir, por favor?", ["{Você |}pode repetir, por favor?", "Tu podes repetir, por favor?"],
     "irregulares", ("pode", "poder"),
     "Podés = você pode."),
    (6, "Traigo el vino.", "{Eu |}trago o vinho.",
     "irregulares", ("trago", "trazer"),
     "Traer = trazer: eu trago."),
    (6, "Leo un libro de Jorge Amado.", "{Eu |}{leio|estou lendo} um livro {de|do} Jorge Amado.",
     "irregulares", ("leio", "ler"),
     "Leer = ler: eu leio."),
    (6, "Escucho música en el metro.", "{Eu |}{ouço|escuto} música no metrô.",
     "irregulares", ("ouço", "ouvir"),
     "Oír = ouvir: eu ouço."),
    (6, "Prefiero el mar.", "{Eu |}prefiro o mar.",
     "irregulares", ("prefiro", "preferir"),
     "Preferir → eu prefiro."),
    (6, "Ellos van al Maracanã.", "Eles vão ao Maracanã.",
     "irregulares contracciones", ("vão", "ir"),
     "Van = vão; a + o = ao."),
    (6, "Ponemos la mesa.", "{Nós pomos|Pomos|A gente põe} a mesa.",
     "irregulares", ("pomos", "pôr"),
     "Poner la mesa = pôr a mesa."),
    (6, "Veo el mar desde la ventana.", "{Eu |}vejo o mar da janela.",
     "irregulares", ("vejo", "ver"),
     "Ver → eu vejo."),
    (6, "Vamos en metro.", "{Nós vamos|Vamos|A gente vai} de metrô.",
     "irregulares preposiciones", ("vamos", "ir"),
     "En metro = de metrô."),
    (6, "Ella sube la escalera corriendo.", "Ela sobe a escada correndo.",
     "irregulares", ("sobe", "subir"),
     "Subir → ele sobe (u → o)."),
    (6, "¿Sabés dónde queda la estación?", ["Você sabe onde fica a estação?", "Tu sabes onde fica a estação?"],
     "irregulares", ("sabe", "saber"),
     "Quedar (estar ubicado) = ficar."),
    (6, "Ellos no quieren salir.", "Eles não querem sair.",
     "irregulares", ("querem", "querer"),
     "Quieren = querem."),
    (6, "¿Ustedes vienen a la fiesta?", "Vocês vêm {para a|à|na} festa?",
     "irregulares", ("vêm", "vir"),
     "Ellos vienen = eles vêm (con circunflejo)."),

    # --- semana 7: números, horas, fechas, precios
    (7, "Son las tres y media.", "São três {e meia|horas e meia|e trinta}.",
     "horas numeros", ("São", "ser"),
     "Las horas: são três e meia; é uma hora."),
    (7, "Es la una.", ["É uma hora.", "É uma."],
     "horas", ("É", "ser"),
     "Una sola hora: é uma hora (singular)."),
    (7, "Llego a las ocho.", "{Eu |}chego às oito.",
     "horas", ("chego", "chegar"),
     "A las ocho = às oito (con crase)."),
    (7, "Hoy es lunes, 15 de marzo.", "Hoje é segunda{-feira|}, {dia |}15 de março.",
     "numeros lexico", ("é", "ser"),
     "Lunes = segunda-feira; marzo = março."),
    (7, "El café cuesta cinco reales.", "O café custa cinco reais.",
     "numeros", ("custa", "custar"),
     "Real → reais."),
    (7, "Tengo dos hijas.", "{Eu |}tenho duas filhas.",
     "numeros concordancia", ("tenho", "ter"),
     "Dos = dois / duas: duas filhas."),
    (7, "Mi cumpleaños es en julio.", "{O |}meu aniversário é em julho.",
     "numeros lexico", ("é", "ser"),
     "Cumpleaños = aniversário; julio = julho."),
    (7, "La feria abre el miércoles.", "A feira abre na quarta{-feira|}.",
     "numeros", ("abre", "abrir"),
     "Miércoles = quarta-feira."),
    (7, "Son doscientas personas.", "São duzentas pessoas.",
     "numeros concordancia", ("São", "ser"),
     "Las centenas concuerdan: duzentas pessoas."),
    (7, "¿Cuánto cuesta?", ["Quanto custa?", "Quanto é?"],
     "numeros preguntas", ("custa", "custar"),
     "¿Cuánto cuesta? = quanto custa?"),
    (7, "Es mediodía.", "É meio-dia.",
     "horas", ("É", "ser"),
     "Mediodía = meio-dia; medianoche = meia-noite."),
    (7, "Trabajo de lunes a viernes.", "{Eu |}trabalho de segunda a sexta{-feira|}.",
     "numeros", ("trabalho", "trabalhar"),
     "De lunes a viernes = de segunda a sexta."),
    (7, "El carnaval es en febrero.", "O carnaval é em fevereiro.",
     "numeros", ("é", "ser"),
     "Febrero = fevereiro."),
    (7, "Son las once de la noche.", "São onze {horas |}da noite.",
     "horas", ("São", "ser"),
     "Once = onze."),
    (7, "El vuelo sale a las diez y cuarto.", "O voo sai às dez e quinze.",
     "horas", ("sai", "sair"),
     "Voo, sin circunflejo desde 1990."),
    (7, "Mi teléfono es nueve, seis, seis, uno...", "{O |}meu telefone é nove, meia, meia, um...",
     "numeros", None,
     "Al dictar números, el seis se dice meia (de meia dúzia)."),
    (7, "Tenemos clase los martes y los jueves.", "{Nós temos|Temos|A gente tem} aula {às terças e às quintas|nas terças e nas quintas|terça e quinta}.",
     "numeros", ("temos", "ter"),
     "Martes = terça; jueves = quinta."),
    (7, "Hace treinta grados en Río.", ["Está fazendo trinta graus no Rio.", "{Faz|Está} trinta graus no Rio."],
     "numeros", None,
     "El calor: está fazendo trinta graus."),

    # --- semana 8: preguntas, ir + infinitivo, estar + gerundio
    (8, "¿Qué estás haciendo?", ["O que você está fazendo?", "{O |}que é que você está fazendo?", "Você está fazendo o quê?", "O que tu estás fazendo?"],
     "gerundio preguntas", ("fazendo", "fazer"),
     "Estar + gerúndio, como en español: está fazendo."),
    (8, "Estoy estudiando portugués.", "{Eu |}estou estudando português.",
     "gerundio", ("estudando", "estudar"),
     "En Portugal: estou a estudar."),
    (8, "Voy a viajar a Salvador en enero.", "{Eu |}vou viajar {para|a} Salvador em janeiro.",
     "ir_inf", ("vou", "ir"),
     "Ir + infinitivo sin «a»: vou viajar."),
    (8, "¿Dónde vas a cenar?", ["Onde você vai jantar?", "Você vai jantar onde?"],
     "ir_inf preguntas", ("vai", "ir"),
     "Cenar = jantar."),
    (8, "¿Por qué no venís?", ["Por que você não vem?", "Por que tu não vens?"],
     "preguntas irregulares", ("vem", "vir"),
     "Por qué (pregunta) = por que, separado."),
    (8, "Porque estoy cansado.", "Porque {eu |}estou cansado.",
     "preguntas", ("estou", "estar"),
     "Porque (respuesta) = porque, junto."),
    (8, "¿Quién es él?", "Quem é ele?",
     "preguntas", ("é", "ser"),
     "Quién = quem."),
    (8, "¿Cuál es tu nombre?", ["Qual é o seu nome?", "Qual é seu nome?", "Qual o seu nome?", "Qual é o teu nome?"],
     "preguntas", ("é", "ser"),
     "¿Cuál es? = qual é?"),
    (8, "¿Cuántos años tenés?", ["Quantos anos você tem?", "Quantos anos tu tens?"],
     "preguntas", ("tem", "ter"),
     "Cuántos = quantos."),
    (8, "Vamos a comer feijoada el sábado.", "{Nós vamos|Vamos|A gente vai} comer feijoada no sábado.",
     "ir_inf", ("vamos", "ir"),
     "La feijoada es el plato del sábado en Río."),
    (8, "Está lloviendo en Río.", "Está chovendo no Rio.",
     "gerundio", ("chovendo", "chover"),
     "Llover = chover."),
    (8, "Los chicos están jugando en la playa.", "{As crianças|Os meninos} estão brincando na praia.",
     "gerundio falsos_amigos", ("brincando", "brincar"),
     "Jugar (los chicos) = brincar; jugar un deporte = jogar."),
    (8, "¿Cuándo vas a volver?", ["Quando você vai voltar?", "Quando tu vais voltar?"],
     "ir_inf preguntas", ("vai", "ir"),
     "Volver = voltar."),
    (8, "Voy a llamar a mi madre.", "{Eu |}vou ligar para {a |}minha mãe.",
     "ir_inf", ("vou", "ir"),
     "Llamar por teléfono = ligar para."),
    (8, "¿Cómo se dice «esquina» en portugués?", "Como se diz «esquina» em português?",
     "preguntas", ("diz", "dizer"),
     "¿Cómo se dice? = como se diz?"),
    (8, "Estamos esperando el colectivo.", "{Nós estamos|Estamos|A gente está} esperando o ônibus.",
     "gerundio", ("esperando", "esperar"),
     "Colectivo = ônibus."),
    (8, "¿Qué vas a hacer el fin de semana?", ["O que você vai fazer no fim de semana?", "O que tu vais fazer no fim de semana?"],
     "ir_inf preguntas", ("vai", "ir"),
     "Fin de semana = fim de semana."),
    (8, "Ella está hablando por teléfono.", "Ela está falando {ao|no|pelo} telefone.",
     "gerundio", ("falando", "falar"),
     "Hablar por teléfono = falar ao telefone (o no telefone)."),
    (8, "¿Adónde van?", ["Aonde vocês vão?", "Para onde vocês vão?", "Vocês vão para onde?"],
     "preguntas irregulares", ("vão", "ir"),
     "Adónde = aonde o para onde."),
    (8, "¿Cuál de los dos preferís?", ["Qual dos dois você prefere?", "Qual dos dois tu preferes?"],
     "preguntas", ("prefere", "preferir"),
     "Cuál = qual; preferís = você prefere."),
    (8, "Mañana voy a trabajar temprano.", ["Amanhã {eu |}vou trabalhar cedo.", "{Eu |}vou trabalhar cedo amanhã."],
     "ir_inf", ("vou", "ir"),
     "Temprano = cedo."),

    # --- semana 9: preposiciones de lugar y movimiento, transporte
    (9, "Voy al trabajo en colectivo.", "{Eu |}vou {para o|ao} trabalho de ônibus.",
     "preposiciones", ("vou", "ir"),
     "Medio de transporte: de ônibus."),
    (9, "Voy a pie.", "{Eu |}vou a pé.",
     "preposiciones", ("vou", "ir"),
     "A pie = a pé (sin crase: pé es masculino)."),
    (9, "Llegamos a Río en avión.", "{Nós chegamos|Chegamos|A gente chega} {ao|no} Rio de avião.",
     "preposiciones", ("chegamos", "chegar"),
     "Chegar a (norma) / em (habla); de avião."),
    (9, "Salimos de casa a las siete.", "{Nós saímos|Saímos|A gente sai} de casa às sete.",
     "preposiciones horas", ("saímos", "sair"),
     "Salir de casa = sair de casa."),
    (9, "El metro pasa por Botafogo.", "O metrô passa por Botafogo.",
     "preposiciones", ("passa", "passar"),
     "Pasar = passar (con ss)."),
    (9, "¿Cómo llego a la estación?", ["Como {eu |}faço para chegar {na|à} estação?", "Como {eu |}chego {na|à} estação?"],
     "preposiciones", ("faço", "fazer"),
     "Chegar em (habla) / chegar a (norma)."),
    (9, "Vengo de la playa.", "{Eu |}venho da praia.",
     "preposiciones contracciones", ("venho", "vir"),
     "de + a = da."),
    (9, "Pasamos por la Lapa.", "{Nós passamos|Passamos|A gente passa} pela Lapa.",
     "preposiciones contracciones", ("passamos", "passar"),
     "por + a = pela."),
    (9, "El hotel queda cerca del metro.", "O hotel fica perto do metrô.",
     "preposiciones", ("fica", "ficar"),
     "Quedar (ubicación) = ficar; cerca de = perto de."),
    (9, "Vamos a Niterói en barco.", "{Nós vamos|Vamos|A gente vai} {para|a} Niterói de {barca|barco}.",
     "preposiciones", ("vamos", "ir"),
     "La barca Rio-Niterói cruza la bahía de Guanabara."),
    (9, "Voy a lo de mi abuela.", "{Eu |}vou {para a|à|na} casa da minha avó.",
     "preposiciones", ("vou", "ir"),
     "A lo de = para a casa de."),
    (9, "Volvemos a casa tarde.", "{Nós voltamos|Voltamos|A gente volta} para casa tarde.",
     "preposiciones", ("voltamos", "voltar"),
     "A casa (el propio hogar) = para casa, sin artículo."),
    (9, "El colectivo para enfrente del hotel.", "O ônibus para {em frente ao|na frente do|em frente do} hotel.",
     "preposiciones", ("para", "parar"),
     "Enfrente de = em frente a / na frente de."),
    (9, "Estamos en camino.", "{Nós estamos|Estamos|A gente está} a caminho.",
     "preposiciones", ("estamos", "estar"),
     "En camino = a caminho."),
    (9, "Voy hasta la esquina y vuelvo.", "{Eu |}vou até a esquina e volto.",
     "preposiciones", ("volto", "voltar"),
     "Hasta = até."),
    (9, "La farmacia está entre el banco y el bar.", "A farmácia {está|fica} entre o banco e o bar.",
     "preposiciones", ("está", "estar"),
     "Entre = entre."),
    (9, "Subimos al Pan de Azúcar en teleférico.", "{Nós subimos|Subimos|A gente sobe} {ao|o|no} Pão de Açúcar de bondinho.",
     "preposiciones", ("subimos", "subir"),
     "El teleférico del Pão de Açúcar = o bondinho."),
    (9, "El tren sale de la Central.", "O trem sai da Central.",
     "preposiciones", ("sai", "sair"),
     "La Central do Brasil es la estación de trenes de Río."),

    # --- semana 10: posesivos y demostrativos
    (10, "Este es mi hermano.", "{Este|Esse} é {o |}meu irmão.",
     "demostrativos posesivos", ("é", "ser"),
     "En el habla, esse se usa por este."),
    (10, "Esa casa es de ella.", "Essa casa é dela.",
     "demostrativos posesivos", ("é", "ser"),
     "De ella = dela."),
    (10, "El auto de él es nuevo.", "O carro dele é novo.",
     "posesivos", ("é", "ser"),
     "Auto = carro; de él = dele."),
    (10, "¿Esto es tuyo?", ["{Isso|Isto} é seu?", "{Isso|Isto} é teu?"],
     "demostrativos posesivos", ("é", "ser"),
     "Esto = isto / isso; tuyo = seu (de você)."),
    (10, "Aquel edificio es muy antiguo.", "Aquele {prédio|edifício} é muito antigo.",
     "demostrativos", ("é", "ser"),
     "Aquel = aquele; edificio = prédio."),
    (10, "Nuestra casa está en Santa Teresa.", "{A |}nossa casa {fica|está|é} em Santa Teresa.",
     "posesivos", ("fica", "ficar"),
     "Nuestra = nossa."),
    (10, "Los hijos de ellos viven en Recife.", "Os filhos deles moram em Recife.",
     "posesivos", ("moram", "morar"),
     "De ellos = deles."),
    (10, "Mis abuelos viven en este barrio.", "{Os |}meus avós moram {neste|nesse} bairro.",
     "posesivos demostrativos contracciones", ("moram", "morar"),
     "em + este = neste."),
    (10, "¿De quién es este libro?", "De quem é {este|esse} livro?",
     "demostrativos preguntas", ("é", "ser"),
     "¿De quién? = de quem?"),
    (10, "Eso es muy importante.", "Isso é muito importante.",
     "demostrativos", ("é", "ser"),
     "Eso = isso."),
    (10, "Me gusta este barrio.", "{Eu |}gosto {deste|desse} bairro.",
     "demostrativos contracciones gostar", ("gosto", "gostar"),
     "de + este = deste."),
    (10, "La novia de mi hermano es carioca.", "A namorada do meu irmão é carioca.",
     "posesivos falsos_amigos", ("é", "ser"),
     "Novia = namorada; noiva es la prometida."),
    (10, "Tu familia es muy simpática.", ["{A |}sua família é muito simpática.", "{A |}tua família é muito simpática."],
     "posesivos", ("é", "ser"),
     "Tu = seu / sua (de você)."),
    (10, "Aquella chica es la hermana de Rafa.", "Aquela {menina|garota|moça} é a irmã do Rafa.",
     "demostrativos", ("é", "ser"),
     "Chica = menina, garota, moça."),
    (10, "Esas ojotas son mías.", ["Esses chinelos são meus.", "Essas sandálias são minhas."],
     "demostrativos posesivos", ("são", "ser"),
     "Las ojotas (Havaianas) = os chinelos."),
    (10, "En esa calle hay un bar muy bueno.", "Nessa rua {tem|há} um bar muito bom.",
     "demostrativos contracciones", None,
     "em + essa = nessa."),
    (10, "Esta es nuestra hija, Luna.", "{Esta|Essa} é {a |}nossa filha, Luna.",
     "demostrativos posesivos", ("é", "ser"),
     "Nuestra = nossa."),
    (10, "El perro de ellas se llama Bob.", "O cachorro delas se chama Bob.",
     "posesivos", ("chama", "chamar"),
     "De ellas = delas."),
]

_ROWS += [
    # ================================================================ A2
    # --- semana 11: pretérito perfeito
    (11, "Ayer fui a la playa.", "Ontem {eu |}fui {para a|à} praia.",
     "perfeito", ("fui", "ir"),
     "Fui sirve para ir y para ser: fui à praia, fui feliz."),
    (11, "Comí feijoada el sábado.", "{Eu |}comi feijoada no sábado.",
     "perfeito", ("comi", "comer"),
     "Comer → comi, comeu, comemos, comeram."),
    (11, "Hoy me desperté temprano.", "Hoje {eu |}acordei cedo.",
     "perfeito falsos_amigos", ("acordei", "acordar"),
     "Despertarse = acordar (sin pronombre). Acordarse = lembrar."),
    (11, "¿Ya viste el Cristo?", ["Você já viu o Cristo{| Redentor}?", "Tu já viste o Cristo{| Redentor}?"],
     "perfeito perfeito_composto", ("viu", "ver"),
     "«¿Ya viste / has visto?» = você já viu? El perfeito cubre los dos pasados."),
    (11, "Hicimos un asado en la casa de Rafa.", "{Nós fizemos|Fizemos|A gente fez} um churrasco na casa do Rafa.",
     "perfeito irregulares", ("fizemos", "fazer"),
     "Fazer → fiz, fez, fizemos, fizeram."),
    (11, "No pude dormir.", "{Eu |}não {consegui|pude} dormir.",
     "perfeito irregulares", ("consegui", "conseguir"),
     "No pude (no logré) = não consegui (o não pude)."),
    (11, "Ella tuvo un problema en el trabajo.", "Ela teve um problema no trabalho.",
     "perfeito irregulares", ("teve", "ter"),
     "Ter → tive, teve, tivemos, tiveram."),
    (11, "Estuvimos en Bahía en enero.", "{Nós estivemos|Estivemos|A gente esteve} na Bahia em janeiro.",
     "perfeito irregulares articulos", ("estivemos", "estar"),
     "A Bahia lleva artículo: na Bahia."),
    (11, "¿Qué dijiste?", ["O que você disse?", "Você disse o quê?", "O que tu disseste?"],
     "perfeito irregulares", ("disse", "dizer"),
     "Dizer → disse (eu y ele)."),
    (11, "Él vino ayer.", "Ele veio ontem.",
     "perfeito irregulares", ("veio", "vir"),
     "Vir → vim, veio, viemos, vieram."),
    (11, "Llegué tarde al trabajo.", "{Eu |}cheguei {atrasado|atrasada|tarde} {ao|no} trabalho.",
     "perfeito", ("cheguei", "chegar"),
     "Chegar → cheguei (con u, para mantener el sonido)."),
    (11, "¿Dónde pusiste las llaves?", ["Onde você {pôs|colocou|botou} as chaves?", "Onde tu puseste as chaves?"],
     "perfeito irregulares", ("pôs", "pôr"),
     "Pôr → pus, pôs, pusemos, puseram."),
    (11, "Trajo un regalo para Bia.", "{Ele |Ela |}trouxe um presente para {a |}Bia.",
     "perfeito irregulares lexico", ("trouxe", "trazer"),
     "Trazer → trouxe. Regalo = presente."),
    (11, "El año pasado viajamos a Portugal.", "{No |}ano passado {nós viajamos|viajamos|a gente viajou} para Portugal.",
     "perfeito", ("viajamos", "viajar"),
     "Portugal va sin artículo: para Portugal."),
    (11, "Quise llamarte, pero no pude.", ["{Eu |}quis ligar para você, mas não {consegui|pude}.", "{Eu |}quis te ligar, mas não {consegui|pude}."],
     "perfeito irregulares", ("quis", "querer"),
     "Querer → quis."),
    (11, "Supe la noticia ayer.", ["{Eu |}soube da notícia ontem.", "{Eu |}fiquei sabendo da notícia ontem."],
     "perfeito irregulares", ("soube", "saber"),
     "Saber → soube; me enteré = fiquei sabendo."),
    (11, "Le di mi número.", ["{Eu |}dei meu número para {ele|ela}.", "{Eu |}lhe dei meu número."],
     "perfeito irregulares", ("dei", "dar"),
     "Dar → dei, deu, demos, deram."),
    (11, "Ellos fueron al show de Caetano.", "Eles foram ao show do Caetano.",
     "perfeito irregulares", ("foram", "ir"),
     "Fueron = foram."),
    (11, "Hoy he comido demasiado.", "Hoje {eu |}comi demais.",
     "perfeito perfeito_composto", ("comi", "comer"),
     "«He comido» = comi. Tenho comido significa «vengo comiendo»."),
    (11, "¿Leíste el mensaje?", ["Você leu a mensagem?", "Tu leste a mensagem?"],
     "perfeito", ("leu", "ler"),
     "Ler → li, leu."),
    (11, "Nació en Buenos Aires en 1990.", "{Ele |Ela |}nasceu em Buenos Aires em 1990.",
     "perfeito", ("nasceu", "nascer"),
     "Nacer = nascer (sc)."),
    (11, "Perdí el celular en el colectivo.", "{Eu |}perdi o celular no ônibus.",
     "perfeito", ("perdi", "perder"),
     "Perder → perdi."),
    (11, "Bailamos samba hasta las tres.", "{Nós dançamos|Dançamos|A gente dançou} samba até as três.",
     "perfeito", ("dançamos", "dançar"),
     "Bailar = dançar; hasta = até."),
    (11, "¿Te gustó el Pan de Azúcar?", ["Você gostou do Pão de Açúcar?", "Tu gostaste do Pão de Açúcar?"],
     "perfeito gostar", ("gostou", "gostar"),
     "Gostar de + o = do."),
    (11, "Empecé a estudar portugués en marzo.", "{Eu |}comecei a estudar português em março.",
     "perfeito", ("comecei", "começar"),
     "Começar → comecei (ç → c ante e)."),
    (11, "Ellos vieron el partido en un bar.", "Eles viram o jogo {num|em um} bar.",
     "perfeito irregulares", ("viram", "ver"),
     "Ver → vi, viu, vimos, viram."),
    (11, "Vine en taxi.", "{Eu |}vim de táxi.",
     "perfeito irregulares", ("vim", "vir"),
     "Vir → eu vim."),
    (11, "Pagué la cuenta.", "{Eu |}paguei a conta.",
     "perfeito", ("paguei", "pagar"),
     "Pagar → paguei."),

    # --- semana 12: imperativo, reflexivos, rutina
    (12, "Me levanto a las siete.", ["{Eu |}me levanto às sete.", "{Eu |}levanto às sete."],
     "reflexivos", ("levanto", "levantar"),
     "En Brasil el pronombre va delante: eu me levanto."),
    (12, "Me ducho y desayuno.", "{Eu |}tomo banho e tomo café{ da manhã|}.",
     "reflexivos lexico", ("tomo", "tomar"),
     "Ducharse = tomar banho; desayunar = tomar café (da manhã)."),
    (12, "¡Hablá más despacio, por favor!", ["Fale mais devagar, por favor!", "Fala mais devagar, por favor!"],
     "imperativo", ("Fale", "falar"),
     "Imperativo de você: fale; en el habla: fala."),
    (12, "Tomá este remedio dos veces por día.", "{Tome|Toma} {este|esse} remédio duas vezes por dia.",
     "imperativo", ("Tome", "tomar"),
     "Tomar → tome (formal) / toma (habla)."),
    (12, "No te preocupes.", ["Não se preocupe.", "Não se preocupa.", "Não te preocupes."],
     "imperativo reflexivos", ("preocupe", "preocupar"),
     "Não se preocupe (a você)."),
    (12, "Sentate, por favor.", ["Sente-se, por favor.", "Senta, por favor.", "Pode sentar, por favor.", "Se senta, por favor."],
     "imperativo reflexivos", ("Sente-se", "sentar"),
     "Sentar-se: sente-se (escrito) / senta (habla)."),
    (12, "Venga mañana a las nueve.", "Venha amanhã às nove.",
     "imperativo irregulares", ("Venha", "vir"),
     "Vir → venha (o senhor, a senhora)."),
    (12, "Cerrá la ventana.", ["Feche a janela.", "Fecha a janela."],
     "imperativo", ("Feche", "fechar"),
     "Cerrar = fechar."),
    (12, "¿Cómo se llama tu hermana?", ["Como se chama {a |}sua irmã?", "Como {a |}sua irmã se chama?", "Qual é o nome da sua irmã?"],
     "reflexivos", ("chama", "chamar"),
     "Chamar-se: ela se chama Bia."),
    (12, "Me acuesto tarde.", ["{Eu |}me deito tarde.", "{Eu |}vou dormir tarde."],
     "reflexivos", ("deito", "deitar"),
     "Acostarse = deitar-se, ir dormir."),
    (12, "Nos vestimos rápido.", ["{Nós nos vestimos|A gente se veste} rápido."],
     "reflexivos irregulares", ("vestimos", "vestir"),
     "Vestir-se: nós nos vestimos, a gente se veste."),
    (12, "Doblá a la izquierda en la segunda calle.", ["Vire à esquerda na segunda rua.", "Vira à esquerda na segunda rua.", "Dobre à esquerda na segunda rua."],
     "imperativo", ("Vire", "virar"),
     "Doblar = virar; a la izquierda = à esquerda."),
    (12, "No toques eso.", ["Não {toque|mexa|toca|mexe} nisso."],
     "imperativo", ("toque", "tocar"),
     "Tocar → não toque (qu ante e)."),
    (12, "Ponete protector solar.", ["{Passe|Passa} protetor solar.", "{Coloque|Coloca|Bota} protetor solar."],
     "imperativo lexico", ("Passe", "passar"),
     "Ponerse crema = passar (protetor solar)."),
    (12, "Traé la guitarra.", ["{Traga|Traz} o violão."],
     "imperativo irregulares", ("Traga", "trazer"),
     "Trazer → traga (formal) / traz (habla). La guitarra criolla = o violão."),
    (12, "Me duele la espalda.", ["Estou com dor nas costas.", "{As |}minhas costas {doem|estão doendo}."],
     "reflexivos lexico", None,
     "La espalda = as costas (plural)."),
    (12, "Andá hasta la farmacia.", ["{Vá|Vai} até a farmácia."],
     "imperativo irregulares", ("Vá", "ir"),
     "Ir → vá (formal) / vai (habla)."),
    (12, "Lavate las manos antes de comer.", ["Lave as mãos antes de comer.", "Lava as mãos antes de comer."],
     "imperativo reflexivos", ("Lave", "lavar"),
     "En portugués no hace falta el pronombre: lave as mãos."),
    (12, "Hagan silencio, por favor.", "Façam silêncio, por favor.",
     "imperativo irregulares", ("Façam", "fazer"),
     "Fazer → façam (vocês)."),
    (12, "No se olvide del pasaporte.", ["Não se esqueça do passaporte.", "Não esqueça o passaporte.", "Não esqueça do passaporte."],
     "imperativo reflexivos", ("esqueça", "esquecer"),
     "Olvidarse = esquecer(-se)."),
    (12, "Me acuerdo temprano los lunes.", "{Eu |}acordo cedo às segundas.",
     "reflexivos falsos_amigos", ("acordo", "acordar"),
     "Ojo: acordar = despertarse. «Me despierto temprano» = acordo cedo."),

    # --- semana 13: repaso A2
    (13, "Ayer comí en un restaurante de Ipanema.", "Ontem {eu |}comi {num|em um} restaurante {de|em} Ipanema.",
     "perfeito contracciones", ("comi", "comer"),
     "em + um = num (o em um)."),
    (13, "El sábado vamos a hacer un asado.", "No sábado {nós vamos|vamos|a gente vai} fazer um churrasco.",
     "ir_inf", ("vamos", "ir"),
     "El sábado = no sábado."),
    (13, "Ella está trabajando en un hotel.", "Ela está trabalhando {num|em um} hotel.",
     "gerundio", ("trabalhando", "trabalhar"),
     "em + um = num."),
    (13, "Los chicos de mi hermana son muy lindos.", "Os filhos da minha irmã são muito {lindos|bonitos|fofos}.",
     "posesivos muito", ("são", "ser"),
     "Los chicos (hijos) = os filhos."),
    (13, "No conozco a nadie aquí.", "{Eu |}não conheço ninguém aqui.",
     "a_personal indefinidos", ("conheço", "conhecer"),
     "Sin «a» personal: não conheço ninguém."),
    (13, "Conocí a João en la facultad.", "{Eu |}conheci o João na faculdade.",
     "a_personal perfeito", ("conheci", "conhecer"),
     "No hay «a» personal: conheci o João."),
    (13, "Visitamos a nuestros abuelos.", "{Nós visitamos|Visitamos|A gente visitou} {os |}nossos avós.",
     "a_personal perfeito", ("visitamos", "visitar"),
     "Visitar alguém, sin «a»."),
    (13, "Poné la mochila en el auto.", ["{Ponha|Põe|Coloque|Coloca|Bota} a mochila no carro."],
     "imperativo irregulares", ("Ponha", "pôr"),
     "Pôr → ponha (formal) / põe (habla)."),
    (13, "¿Cuánto cuestan los mangos?", "Quanto custam as mangas?",
     "numeros", ("custam", "custar"),
     "La fruta es a manga."),
    (13, "Mis padres llegaron ayer de Buenos Aires.", "{Os |}meus pais chegaram ontem de Buenos Aires.",
     "perfeito", ("chegaram", "chegar"),
     "Chegar → chegaram."),

    # --- semana 14: gostar de y verbos con preposición
    (14, "Me gusta el samba.", "{Eu |}gosto {de|do} samba.",
     "gostar", ("gosto", "gostar"),
     "Me gusta = eu gosto de: la persona es el sujeto."),
    (14, "¿Te gusta la comida bahiana?", ["Você gosta da comida baiana?", "Tu gostas da comida baiana?"],
     "gostar", ("gosta", "gostar"),
     "Gostar de + a = da."),
    (14, "A ella le gusta bailar forró.", "Ela gosta de dançar forró.",
     "gostar", ("gosta", "gostar"),
     "Gostar de + infinitivo: gosta de dançar."),
    (14, "Me gustan los libros de Clarice Lispector.", "{Eu |}gosto dos livros {da|de} Clarice Lispector.",
     "gostar", ("gosto", "gostar"),
     "El verbo no pasa a plural: eu gosto dos livros."),
    (14, "No nos gusta el frío.", "{Nós não gostamos|Não gostamos|A gente não gosta} do frio.",
     "gostar", ("gostamos", "gostar"),
     "Gostar de + o = do."),
    (14, "Necesito un taxi.", "{Eu |}preciso de um táxi.",
     "regencia", ("preciso", "precisar"),
     "Precisar de + sustantivo."),
    (14, "Necesito trabajar mañana.", "{Eu |}preciso trabalhar amanhã.",
     "regencia", ("preciso", "precisar"),
     "Ante infinitivo, precisar va sin de."),
    (14, "Me acuerdo de mi abuelo.", ["{Eu |}me lembro do meu avô.", "{Eu |}lembro do meu avô.", "Lembro-me do meu avô."],
     "regencia reflexivos", ("lembro", "lembrar"),
     "Acordarse de = lembrar(-se) de."),
    (14, "Pienso en vos.", ["{Eu |}penso em você.", "{Eu |}penso em ti."],
     "regencia", ("penso", "pensar"),
     "Pensar em."),
    (14, "Creo que sí.", "Acho que sim.",
     "lexico", ("Acho", "achar"),
     "Creer (opinar) = achar."),
    (14, "Soñé con el mar.", "{Eu |}sonhei com o mar.",
     "regencia perfeito", ("sonhei", "sonhar"),
     "Soñar con = sonhar com."),
    (14, "Depende del tiempo.", "Depende do tempo.",
     "regencia", ("Depende", "depender"),
     "Depender de."),
    (14, "¿Qué te parece?", ["O que você acha?", "O que tu achas?"],
     "lexico", ("acha", "achar"),
     "¿Qué te parece? = o que você acha?"),
    (14, "Encontré las llaves.", "{Eu |}{achei|encontrei} as chaves.",
     "lexico perfeito", ("achei", "achar"),
     "Achar también es encontrar."),
    (14, "Me encanta la música de Tom Jobim.", "{Eu |}{adoro|amo} a música do Tom Jobim.",
     "gostar", ("adoro", "adorar"),
     "Me encanta = adoro."),
    (14, "A mis padres les gusta la bossa nova.", "{Os |}meus pais gostam {de|da} bossa nova.",
     "gostar", ("gostam", "gostar"),
     "La persona es el sujeto: os meus pais gostam."),
    (14, "Me gustó mucho la película.", "{Eu |}gostei muito do filme.",
     "gostar perfeito", ("gostei", "gostar"),
     "Película = filme."),
    (14, "Confío en vos.", ["{Eu |}confio em você.", "{Eu |}confio em ti."],
     "regencia", ("confio", "confiar"),
     "Confiar em."),
    (14, "Ella se enamoró de un carioca.", "Ela se apaixonou por um carioca.",
     "regencia perfeito", ("apaixonou", "apaixonar"),
     "Enamorarse de = apaixonar-se por."),
    (14, "¿Te acordás de mí?", ["Você se lembra de mim?", "Você lembra de mim?", "Tu te lembras de mim?"],
     "regencia pronombres", ("lembra", "lembrar"),
     "De mí = de mim."),
    (14, "Me interesa la historia de Brasil.", ["{Eu |}me interesso pela história do Brasil.", "A história do Brasil me interessa."],
     "regencia", ("interesso", "interessar"),
     "Interessar-se por."),

    # --- semana 15: imperfeito
    (15, "Cuando era chico, vivía en Mendoza.", "Quando {eu |}era {criança|pequeno}, {eu |}morava em Mendoza.",
     "imperfeito perf_imperf", ("morava", "morar"),
     "Descripción del pasado: imperfeito."),
    (15, "Todos los veranos íbamos a Mar del Plata.", "{Todo verão|Todos os verões} {nós íamos|íamos|a gente ia} para Mar del Plata.",
     "imperfeito", ("íamos", "ir"),
     "Hábito del pasado: íamos."),
    (15, "Mi abuela cocinaba muy bien.", "{A |}minha avó cozinhava muito bem.",
     "imperfeito", ("cozinhava", "cozinhar"),
     "Cozinhar → cozinhava."),
    (15, "Llovía cuando salí.", ["{Estava chovendo|Chovia} quando {eu |}saí."],
     "imperfeito perf_imperf", ("chovendo", "chover"),
     "Fondo (imperfeito) + acción puntual (perfeito)."),
    (15, "Eran las diez cuando llegaste.", ["Eram dez {horas |}quando você chegou.", "Eram dez {horas |}quando tu chegaste."],
     "imperfeito horas perf_imperf", ("Eram", "ser"),
     "La hora en el pasado: imperfeito (eram dez horas)."),
    (15, "Antes la gente escribía cartas.", "{Antigamente|Antes} as pessoas escreviam cartas.",
     "imperfeito", ("escreviam", "escrever"),
     "La gente = as pessoas (o a gente, en otro sentido)."),
    (15, "Tenía diez años cuando conocí el mar.", "{Eu |}tinha dez anos quando conheci o mar.",
     "imperfeito perf_imperf", ("tinha", "ter"),
     "Edad en el pasado: imperfeito."),
    (15, "Mientras yo cocinaba, él ponía la mesa.", "Enquanto eu cozinhava, ele punha a mesa.",
     "imperfeito irregulares", ("punha", "pôr"),
     "Pôr → punha (irregular)."),
    (15, "Río era la capital de Brasil.", "O Rio era a capital do Brasil.",
     "imperfeito historia", ("era", "ser"),
     "Río fue capital de 1763 a 1960, cuando se inauguró Brasília."),
    (15, "¿Qué hacías en Buenos Aires?", ["O que você fazia em Buenos Aires?", "O que tu fazias em Buenos Aires?"],
     "imperfeito", ("fazia", "fazer"),
     "Fazer → fazia."),
    (15, "La casa tenía un jardín enorme.", "A casa tinha um jardim enorme.",
     "imperfeito", ("tinha", "ter"),
     "Jardín = jardim."),
    (15, "Yo quería un café.", "{Eu |}queria um café.",
     "imperfeito", ("queria", "querer"),
     "Queria sirve de pedido cortés, como en español."),
    (15, "Cuando llegué, ella dormía.", "Quando {eu |}cheguei, ela {dormia|estava dormindo}.",
     "imperfeito perf_imperf", ("dormia", "dormir"),
     "Acción en curso interrumpida: imperfeito."),
    (15, "De chico jugaba al fútbol en la calle.", "Quando {eu |}era {criança|pequeno}, {eu |}jogava futebol na rua.",
     "imperfeito", ("jogava", "jogar"),
     "Jugar al fútbol = jogar futebol (sin «a»)."),
    (15, "Había mucha gente en la playa.", ["{Tinha|Havia} muita gente na praia."],
     "imperfeito", ("Tinha", "ter"),
     "Había = tinha (habla) / havia."),
    (15, "Vinicius vivía en Ipanema.", "{O |}Vinicius morava em Ipanema.",
     "imperfeito cultura", ("morava", "morar"),
     "Vinicius de Moraes, poeta y letrista de Garota de Ipanema."),

    # --- semana 16: pronombres objeto
    (16, "Te amo.", "{Eu |}te amo.",
     "pronombres", ("amo", "amar"),
     "En Brasil el pronombre va antes del verbo: te amo."),
    (16, "Lo vi en la playa.", ["{Eu |}o vi na praia.", "{Eu |}vi ele na praia."],
     "pronombres coloquial", ("vi", "ver"),
     "Norma: eu o vi; habla: vi ele."),
    (16, "¿Me ayudás?", ["Você me ajuda?", "Me ajuda?", "Tu me ajudas?"],
     "pronombres", ("ajuda", "ajudar"),
     "Ayudar = ajudar."),
    (16, "Le di el libro a Ana.", "{Eu |}dei o livro para {a |}Ana.",
     "pronombres perfeito", ("dei", "dar"),
     "Objeto indirecto: para a Ana (o à Ana)."),
    (16, "Este regalo es para mí.", "{Este|Esse} presente é para mim.",
     "pronombres", ("é", "ser"),
     "Para mí = para mim."),
    (16, "¿Venís conmigo?", ["Você vem comigo?", "Tu vens comigo?"],
     "pronombres", ("vem", "vir"),
     "Conmigo = comigo."),
    (16, "Vamos con ustedes.", "{Nós vamos|Vamos|A gente vai} com vocês.",
     "pronombres", ("vamos", "ir"),
     "Con ustedes = com vocês."),
    (16, "No lo conozco.", ["{Eu |}não o conheço.", "{Eu |}não conheço ele."],
     "pronombres", ("conheço", "conhecer"),
     "Norma: não o conheço; habla: não conheço ele."),
    (16, "Te llamo mañana.", ["{Eu |}te ligo amanhã.", "{Eu |}ligo para você amanhã.", "Amanhã {eu |}te ligo."],
     "pronombres", ("ligo", "ligar"),
     "Llamar por teléfono = ligar."),
    (16, "Ella nos invitó a la fiesta.", "Ela nos convidou para a festa.",
     "pronombres perfeito", ("convidou", "convidar"),
     "Invitar = convidar."),
    (16, "¿Me pasás la sal?", ["Você me passa o sal?", "Me passa o sal?"],
     "pronombres genero", ("passa", "passar"),
     "O sal: masculino."),
    (16, "Quiero verla.", ["{Eu |}quero vê-la.", "{Eu |}quero ver ela."],
     "pronombres colocacao", ("vê-la", "ver"),
     "Ver + a = vê-la; en el habla, ver ela."),
    (16, "Lo compré en la feria.", ["{Eu |}o comprei na feira.", "{Eu |}comprei na feira."],
     "pronombres", ("comprei", "comprar"),
     "En el habla el objeto a menudo se omite: comprei na feira."),
    (16, "Esto queda entre vos y yo.", ["Isso fica entre mim e você.", "Isso fica entre você e mim.", "Isso fica entre nós."],
     "pronombres", ("fica", "ficar"),
     "Tras entre: mim."),
    (16, "Contámelo todo.", ["Me conta tudo.", "Conte-me tudo.", "Me conte tudo."],
     "pronombres imperativo", ("conta", "contar"),
     "Contámelo todo = me conta tudo."),
    (16, "Le escribí a la profesora.", ["{Eu |}escrevi para a professora.", "{Eu |}escrevi à professora."],
     "pronombres perfeito", ("escrevi", "escrever"),
     "Escrever para alguém."),
]
