# -*- coding: utf-8 -*-
"""Glosario: las palabras de los ejercicios que no están en el banco.

Cada entrada es forma → (significado en castellano, nivel).  El nivel dice
desde qué semana se puede pedir escribirla (tools/lessico.py: A1 semana 1,
A2 la 9, B1 la 19, B2 la 31, C1 la 43).  Dos niveles especiales:

- "N": nombre propio (persona, lugar, marca): se lee, no se aprende.
- "ES": palabra castellana dentro de una consigna o pista.

El glosario también alimenta el toque en la palabra: en cualquier ejercicio,
tocás una palabra italiana y ves qué significa.
"""

GLOSS = {
    # --- nombres propios y siglas ---
    "tonio": ("nombre", "N"), "edo": ("nombre", "N"), "luigi": ("nombre", "N"),
    "micia": ("nombre (de una gata)", "N"), "javier": ("nombre", "N"),
    "gianna": ("nombre", "N"), "eduardo": ("nombre", "N"), "angela": ("nombre", "N"),
    "amalia": ("nombre", "N"), "corrado": ("nombre", "N"), "edoardo": ("nombre", "N"),
    "alberta": ("nombre", "N"), "ada": ("nombre", "N"), "alfonso": ("nombre", "N"),
    "renato": ("nombre", "N"), "antonella": ("nombre", "N"), "renzo": ("nombre", "N"),
    "realma": ("nombre", "N"), "gigi": ("nombre", "N"), "lavinia": ("nombre", "N"),
    "cinzia": ("nombre", "N"), "nino": ("nombre", "N"), "pierluigi": ("nombre", "N"),
    "donald": ("nombre", "N"), "alistair": ("nombre", "N"), "cyrano": ("nombre", "N"),
    "cagliari": ("Cagliari (ciudad)", "N"), "avana": ("La Habana", "N"),
    "cipro": ("Chipre", "N"), "bratislava": ("Bratislava", "N"), "europa": ("Europa", "N"),
    "enel": ("ENEL (la empresa de electricidad)", "N"),
    "iva": ("IVA (impuesto)", "N"),
    "mariuccia": ("Mariíta", "N"),
    # --- castellano dentro de pistas y consignas ---
    "mariíta": ("", "ES"), "cariño": ("", "ES"), "horita": ("", "ES"),
    "avenidón": ("", "ES"), "callecita": ("", "ES"), "vos": ("", "ES"), "son": ("", "ES"),
    "tus": ("", "ES"), "fue": ("", "ES"), "ese": ("", "ES"), "hacelo": ("", "ES"),
    "decile": ("", "ES"), "pedile": ("", "ES"), "mañana": ("", "ES"),

    # --- A1 ---
    "studentessa": ("estudiante (mujer)", "A1"), "studentesse": ("estudiantes (mujeres)", "A1"),
    "professoressa": ("profesora", "A1"), "dottoressa": ("doctora", "A1"),
    "quarta": ("cuarta", "A1"), "bus": ("colectivo, autobús", "A1"),
    "trent'anni": ("treinta años", "A1"), "novant'anni": ("noventa años", "A1"),
    "sessant'anni": ("sesenta años", "A1"), "aranciata": ("naranjada", "A1"),
    "mezz'ora": ("media hora", "A1"), "anch'io": ("yo también", "A1"),
    "quand'è": ("cuándo es", "A1"), "cos'ha": ("qué tiene", "A1"),
    "sud": ("sur", "A1"), "nord": ("norte", "A1"), "ovest": ("oeste", "A1"),
    "chilometri": ("kilómetros", "A1"), "vuol": ("quiere (vuole)", "A1"),
    "ben": ("bien (bene)", "A1"), "nevica": ("nieva", "A1"), "tivvù": ("tele", "A1"),
    "elementare": ("primaria (escuela)", "A1"), "tortellini": ("tortellini", "A1"),
    "laptop": ("notebook, laptop", "A1"), "trekking": ("trekking", "A1"),
    "spritz": ("spritz (trago)", "A1"), "bridge": ("bridge (juego de cartas)", "A1"),
    "baby": ("baby", "A1"), "sitter": ("sitter", "A1"), "backup": ("copia de seguridad", "A1"),
    "fan": ("fans, hinchas", "A1"), "beh": ("bueno… (muletilla)", "A1"),

    # --- A2 ---
    "babbo": ("papá (en Toscana)", "A2"), "assai": ("muy, mucho", "A2"),
    "invii": ("envías", "A2"), "gassata": ("con gas", "A2"), "ristretto": ("corto, cargado (café)", "A2"),
    "barbiere": ("peluquero de hombres", "A2"), "parecchie": ("bastantes", "A2"),
    "furbo": ("vivo, pícaro", "A2"), "pochissimo": ("poquísimo", "A2"),
    "pochissimi": ("poquísimos", "A2"), "pochissime": ("poquísimas", "A2"),
    "bimbi": ("nenes", "A2"), "segretaria": ("secretaria", "A2"),
    "avanti": ("adelante", "A2"), "commessa": ("vendedora", "A2"),
    "domattina": ("mañana a la mañana", "A2"), "facilissimo": ("facilísimo", "A2"),
    "cagnolino": ("perrito", "A2"), "mezz'oretta": ("media horita", "A2"),
    "paesino": ("pueblito", "A2"), "mesetto": ("un mesecito", "A2"),
    "maluccio": ("medio mal", "A2"), "arrivederla": ("adiós (a usted)", "A2"),
    "ringrazio": ("agradezco", "A2"), "ringraziarti": ("agradecerte", "A2"),
    "ringraziati": ("agradecidos", "A2"), "cameriera": ("moza, camarera", "A2"),
    "documentario": ("documental", "A2"), "affascinante": ("fascinante", "A2"),
    "meraviglia": ("maravilla", "A2"), "francobolli": ("estampillas", "A2"),
    "lieto": ("contento", "A2"), "lieti": ("contentos", "A2"), "bell'uomo": ("hombre lindo", "A2"),
    "promosso": ("aprobado", "A2"), "promossi": ("aprobados", "A2"),
    "bocciato": ("reprobado", "A2"), "bocciati": ("reprobados", "A2"),
    "bucato": ("ropa para lavar (fare il bucato = lavar la ropa)", "A2"),
    "qualcun": ("alguien (qualcun altro = otro)", "A2"), "terrazzo": ("terraza", "A2"),
    "ricoverato": ("internado (en el hospital)", "A2"), "servizio": ("servicio", "A2"),
    "passaggio": ("aventón, que te lleven", "A2"), "indietro": ("atrás", "A2"),
    "richiamerò": ("volveré a llamar", "A2"), "distratto": ("distraído", "A2"),
    "distratta": ("distraída", "A2"), "sbadato": ("despistado", "A2"),
    "vattene": ("andate, irte", "A2"), "prendertela": ("enojarte (prendersela)", "A2"),
    "posticino": ("lugarcito", "A2"), "debolina": ("flojita", "A2"),
    "grassottello": ("gordito", "A2"), "febbrone": ("fiebre alta", "A2"),
    "nuvoloni": ("nubarrones", "A2"), "risposa": ("se vuelve a casar", "A2"),
    "riporto": ("te lo devuelvo, lo traigo de vuelta", "A2"), "ridata": ("devuelta", "A2"),
    "tal": ("tal", "A2"), "altrimenti": ("si no, de lo contrario", "A2"),
    "piuttosto": ("bastante; más bien", "A2"), "senz'altro": ("sin duda", "A2"),
    "nient'affatto": ("para nada", "A2"), "nessun'altra": ("ninguna otra", "A2"),
    "carità": ("caridad (per carità = ¡ni loco!)", "A2"), "pasticcio": ("lío", "A2"),
    "scemo": ("tonto", "A2"), "macchiato": ("manchado; cortado (café)", "A2"),
    "macinato": ("molido", "A2"), "frizzante": ("con gas", "A2"),
    "sporchissima": ("suciísima", "A2"), "esperta": ("experta", "A2"),
    "straordinaria": ("extraordinaria", "A2"), "impiega": ("tarda (tiempo)", "A2"),
    "trattengo": ("me quedo (trattenersi)", "B1"), "trattengono": ("se quedan (trattenersi)", "B1"),
    "separati": ("separados", "A2"), "affrettata": ("apurada (affrettarsi = apurarse)", "B1"),

    # --- B1 ---
    "milionesimo": ("millonésimo", "B1"), "tuorli": ("yemas", "B1"),
    "singolarmente": ("uno por uno", "B1"), "assegno": ("cheque", "B1"),
    "convenuto": ("convenido", "B1"), "miagolavano": ("maullaban", "B1"),
    "rilassante": ("relajante", "B1"), "violentemente": ("violentamente", "B1"),
    "caratteraccio": ("mal carácter", "B1"), "giallastro": ("amarillento", "B1"),
    "scarponi": ("borcegos, botas de montaña", "B1"), "innevate": ("nevadas", "B1"),
    "ragù": ("ragú, salsa de carne", "B1"), "scattate": ("sacadas (fotos)", "B1"),
    "scattato": ("sacado (fotos)", "B1"), "prigionieri": ("prisioneros", "B1"),
    "torturati": ("torturados", "B1"), "manico": ("manija, mango", "B1"),
    "buca": ("pozo; foso (de la orquesta)", "B1"), "capoluogo": ("capital de región o provincia", "B1"),
    "situata": ("situada", "B1"), "proclamato": ("proclamado", "B1"),
    "affreschi": ("frescos (pinturas)", "B1"), "eccezionali": ("excepcionales", "B1"),
    "settecentesca": ("del siglo XVIII", "B1"), "sformato": ("deformado; budín", "B1"),
    "paroloni": ("palabras rimbombantes", "B1"), "mulino": ("molino", "B1"),
    "lacchiamo": ("pintamos (las uñas)", "B1"), "disonesti": ("deshonestos", "B1"),
    "aggiustare": ("arreglar", "B1"), "sconvolto": ("conmocionado", "B1"),
    "gliel'": ("se lo (gliel'ha detto = se lo dijo)", "B1"),
    "imbucare": ("echar al buzón", "B1"), "imbuco": ("echo al buzón", "B1"),
    "incarto": ("envuelvo", "B1"), "bucata": ("agujereada", "B1"),
    "sporcata": ("ensuciada", "B1"), "staccato": ("despegado, salido", "B1"),
    "innaffiato": ("regado", "B1"), "innaffiate": ("regadas", "B1"),
    "innaffiare": ("regar", "B1"), "stuzzicadenti": ("escarbadientes", "B1"),
    "rovinato": ("arruinado", "B1"), "rovinata": ("arruinada", "B1"),
    "distrutto": ("destruido", "B1"), "distrutta": ("destruida", "B1"),
    "raccolto": ("juntado, recogido", "B1"), "slogato": ("dislocado, torcido", "B1"),
    "slogata": ("dislocada, torcida", "B1"), "sciando": ("esquiando", "B1"),
    "storta": ("torcida", "B1"), "storto": ("torcido", "B1"), "cadendo": ("cayéndose", "B1"),
    "soddisfazione": ("satisfacción", "B1"), "coscienza": ("conciencia", "B1"),
    "giustifichi": ("justificás", "B1"), "gigli": ("lirios", "B1"),
    "rieletta": ("reelegida", "B1"), "lussuosi": ("lujosos", "B1"),
    "corrotti": ("corruptos", "B1"), "reperibile": ("ubicable, localizable", "B1"),
    "padrona": ("dueña", "B1"), "bombardata": ("bombardeada", "B1"),
    "emigrato": ("emigrado", "B1"), "paglia": ("paja", "B1"), "intesa": ("entendimiento", "B1"),
    "videocassette": ("videocasetes", "B1"), "imbottiti": ("rellenos, acolchados", "B1"),
    "ripiena": ("rellena", "B1"), "ricoperto": ("cubierto", "B1"),
    "pandoro": ("pandoro (pan dulce de Verona)", "B1"), "puzzolente": ("apestoso", "B1"),
    "baccalà": ("bacalao", "B1"), "obiettato": ("objetado", "B1"),
    "appartengono": ("pertenecen", "B1"), "automobilisti": ("automovilistas", "B1"),
    "moltiplicato": ("multiplicado", "B1"), "quattordicesimo": ("decimocuarto", "B1"),
    "quindicesimo": ("decimoquinto", "B1"), "diciannovesimo": ("decimonoveno", "B1"),
    "stupidità": ("estupidez", "B1"), "propongono": ("proponen", "B1"),
    "affolleranno": ("llenarán, abarrotarán", "B1"), "otterranno": ("obtendrán", "B1"),
    "madornale": ("garrafal", "B1"), "guasta": ("descompuesta", "B1"),
    "successe": ("sucedidas", "B1"), "furgoncino": ("camioneta", "B1"),
    "funzionario": ("funcionario", "B1"), "ventiquattr'ore": ("veinticuatro horas", "B1"),
    "scoppiato": ("estallado (scoppiare a ridere = largar la risa)", "B1"),
    "nascosto": ("escondido", "B1"), "sgridato": ("retado", "B1"), "sgriderò": ("retaré", "B1"),
    "disperato": ("desesperado", "B1"), "seccato": ("molesto, fastidiado", "B1"),
    "impiegarla": ("emplearla, contratarla", "B1"), "convinto": ("convencido", "B1"),
    "inviato": ("enviado", "B1"), "decollo": ("despegue", "B1"),
    "rapinatore": ("asaltante", "B1"), "sparato": ("disparado", "B1"),
    "brano": ("fragmento, texto", "B1"), "dispiaciuto": ("dado pena (dispiacere)", "B1"),
    "disastro": ("desastre", "B1"), "colpevole": ("culpable", "B1"),
    "riavvia": ("reinicia", "B1"), "archivia": ("archiva", "B1"),
    "abbaiare": ("ladrar", "B1"), "arrampicarsi": ("treparse", "B1"),
    "fischiare": ("silbar, abuchear", "B1"), "pettegolezzi": ("chismes", "B1"),
    "sforzato": ("esforzado", "B1"), "stufato": ("harto (stufarsi = hartarse)", "B1"),
    "imbrogliare": ("estafar, engañar", "B1"), "imbrogliato": ("engañado", "B1"),
    "convegno": ("congreso", "B1"), "costretto": ("obligado", "B1"),
    "munirsi": ("proveerse", "B2"), "sventola": ("orejas a sventola = orejas de soplillo", "B2"),
    "vizia": ("malcría", "B1"), "biasimare": ("culpar, reprochar", "B2"),
    "intitola": ("titula", "B1"), "vanvera": ("a vanvera = a tontas y a locas", "B2"),
    "infischio": ("me importa un bledo (infischiarsene)", "B2"),
    "usignolo": ("ruiseñor", "B2"), "sorvolano": ("sobrevuelan", "B2"),
    "infrangersi": ("romperse (las olas)", "B2"), "scogliera": ("acantilado, rompiente", "B2"),
    "giustificarmi": ("justificarme", "B1"), "sgomberare": ("vaciar, despejar", "B2"),
    "ristrutturare": ("refaccionar", "B1"), "pitturare": ("pintar (paredes)", "B1"),
    "imbianchino": ("pintor de paredes", "B2"), "catena": ("cadena", "B1"),
    "ospita": ("aloja", "B1"), "iraniana": ("iraní", "B1"), "manovre": ("maniobras; medidas económicas", "B2"),
    "smentire": ("desmentir", "B2"), "ritenuto": ("considerado", "B2"),
    "insistito": ("insistido", "B1"), "dimetta": ("renuncie (dimettersi)", "B2"),
    "dimettesse": ("renunciara (dimettersi)", "B2"), "produca": ("produzca", "B2"),
    "attragga": ("atraiga", "C1"), "sedettero": ("se sentaron", "C1"),
    "scoppiò": ("estalló", "C1"), "nascose": ("escondió", "C1"),
    "reazione": ("reacción", "A2"), "seicentododicimilaquattrocentoventitré": ("612.423", "A2"),
}
