# -*- coding: utf-8 -*-
"""Glosario: palabras de los ejercicios que no están en el banco.

Cada entrada es forma → (significado en castellano, nivel).  El nivel dice
desde qué semana se puede pedir escribirla (tools/lessico.py: A1 semana 1,
A2 la 9, B1 la 19, B2 la 31, C1 la 43).  Dos niveles especiales:

- "N": nombre propio (persona, lugar, marca): se lee, no se aprende.
- "ES": palabra castellana dentro de una consigna o pista.

El glosario también alimenta el toque en la palabra: en cualquier ejercicio,
tocás una palabra portuguesa y ves qué significa.  Las claves van en
minúscula; las formas flexionadas que el banco no genera (formas coloquiales
como tô, tava, cê; diminutivos como cafezinho; superlativos en -íssimo)
también van acá.  Lo marcado «coloquial» se enseña como tal.
"""

GLOSS = {
    # --- nombres de persona ---
    "joão": ("nombre", "N"), "bia": ("nombre (Beatriz)", "N"), "rafa": ("nombre (Rafael, Rafaela)", "N"),
    "lucas": ("nombre", "N"), "ana": ("nombre", "N"), "martín": ("nombre", "N"), "sofía": ("nombre", "N"),
    "sofia": ("nombre", "N"), "pedro": ("nombre", "N"), "maria": ("nombre", "N"), "carla": ("nombre", "N"),
    "tiago": ("nombre", "N"), "thiago": ("nombre", "N"), "juliana": ("nombre", "N"),
    "camila": ("nombre", "N"), "gabriel": ("nombre", "N"), "fernanda": ("nombre", "N"), "marcelo": ("nombre", "N"),
    "luana": ("nombre", "N"), "beatriz": ("nombre", "N"), "joana": ("nombre", "N"), "felipe": ("nombre", "N"),
    "mariana": ("nombre", "N"), "diego": ("nombre", "N"), "valentina": ("nombre", "N"), "santiago": ("nombre", "N"),
    "lucía": ("nombre", "N"), "mateo": ("nombre", "N"), "facundo": ("nombre", "N"), "agustina": ("nombre", "N"),
    "julia": ("nombre", "N"), "júlia": ("nombre", "N"), "carlos": ("nombre", "N"), "renata": ("nombre", "N"),
    "rodrigo": ("nombre", "N"), "patrícia": ("nombre", "N"), "ricardo": ("nombre", "N"), "clara": ("nombre", "N"),
    "daniel": ("nombre", "N"), "daniela": ("nombre", "N"), "bruno": ("nombre", "N"), "leticia": ("nombre", "N"),
    "letícia": ("nombre", "N"), "gustavo": ("nombre", "N"), "vitória": ("nombre / victoria", "N"),
    "zé": ("nombre (José)", "N"), "tonho": ("nombre (Antônio)", "N"), "antônio": ("nombre", "N"),
    "francisco": ("nombre", "N"), "chico": ("nombre (Francisco)", "N"), "dona": ("doña", "A1"),
    "seu": ("tu / su; también «don» ante nombre: seu João", "A1"), "tia": ("tía; también señora (niños a una adulta)", "A1"),
    "leo": ("nombre", "N"), "léo": ("nombre", "N"), "nina": ("nombre", "N"), "caio": ("nombre", "N"),
    "marina": ("nombre / marina", "N"), "andré": ("nombre", "N"), "luiza": ("nombre", "N"), "luísa": ("nombre", "N"),
    "helena": ("nombre", "N"), "miguel": ("nombre", "N"), "isabel": ("nombre", "N"), "raquel": ("nombre", "N"),
    "vinícius": ("nombre", "N"), "vinicius": ("Vinicius de Moraes (poeta y músico)", "N"),
    "jobim": ("Tom Jobim (compositor)", "N"), "tom": ("Tom Jobim (compositor)", "N"),
    "caetano": ("Caetano Veloso (músico)", "N"), "gil": ("Gilberto Gil (músico)", "N"),
    "chico buarque": ("Chico Buarque (músico y escritor)", "N"), "buarque": ("Chico Buarque", "N"),
    "elis": ("Elis Regina (cantante)", "N"), "cartola": ("Cartola (sambista)", "N"),
    "pixinguinha": ("Pixinguinha (músico de choro)", "N"), "noel": ("Noel Rosa (sambista)", "N"),
    "machado": ("Machado de Assis (escritor)", "N"), "assis": ("Machado de Assis", "N"),
    "clarice": ("Clarice Lispector (escritora)", "N"), "lispector": ("Clarice Lispector", "N"),
    "drummond": ("Carlos Drummond de Andrade (poeta)", "N"), "amado": ("Jorge Amado (escritor) / amado", "N"),
    "guimarães": ("Guimarães Rosa (escritor)", "N"), "bandeira": ("Manuel Bandeira (poeta) / bandera", "A2"),
    "pelé": ("Pelé", "N"), "garrincha": ("Garrincha (futbolista)", "N"), "zico": ("Zico (futbolista)", "N"),
    "marielle": ("nombre", "N"), "selarón": ("Jorge Selarón (artista de la escalinata)", "N"),
    "lula": ("Lula (político) / calamar", "N"), "getúlio": ("Getúlio Vargas (presidente)", "N"),
    "tiradentes": ("Tiradentes (prócer)", "N"), "iemanjá": ("Iemanjá (orixá del mar)", "N"),

    # --- Río de Janeiro ---
    "rio": ("Río de Janeiro / río", "N"), "janeiro": ("enero; Rio de Janeiro", "A1"),
    "copacabana": ("Copacabana (barrio y playa)", "N"), "ipanema": ("Ipanema (barrio y playa)", "N"),
    "leblon": ("Leblon (barrio)", "N"), "arpoador": ("Arpoador (playa y piedra)", "N"),
    "lapa": ("Lapa (barrio)", "N"), "botafogo": ("Botafogo (barrio y club)", "N"),
    "flamengo": ("Flamengo (barrio y club)", "N"), "fluminense": ("Fluminense (club) / del estado de Río", "N"),
    "vasco": ("Vasco da Gama (club)", "N"), "urca": ("Urca (barrio)", "N"), "leme": ("Leme (barrio)", "N"),
    "glória": ("Glória (barrio) / gloria", "N"), "catete": ("Catete (barrio)", "N"), "gávea": ("Gávea (barrio)", "N"),
    "tijuca": ("Tijuca (barrio y selva)", "N"), "vidigal": ("Vidigal (favela)", "N"), "rocinha": ("Rocinha (favela)", "N"),
    "santa teresa": ("Santa Teresa (barrio)", "N"), "teresa": ("Santa Teresa (barrio) / nombre", "N"),
    "laranjeiras": ("Laranjeiras (barrio)", "N"), "humaitá": ("Humaitá (barrio)", "N"),
    "madureira": ("Madureira (barrio del samba)", "N"), "méier": ("Méier (barrio)", "N"),
    "niterói": ("Niterói (ciudad)", "N"), "maracanã": ("Maracanã (estadio)", "N"),
    "corcovado": ("Corcovado (cerro)", "N"), "cristo": ("Cristo (Redentor)", "N"),
    "redentor": ("Cristo Redentor", "N"), "sambódromo": ("Sambódromo", "N"),
    "guanabara": ("Bahía de Guanabara", "N"), "galeão": ("Galeão (aeropuerto)", "N"),
    "dumont": ("Santos Dumont (aeropuerto; inventor)", "N"), "saara": ("Saara (mercado popular del centro)", "N"),
    "mangueira": ("Mangueira (escuela de samba)", "N"), "portela": ("Portela (escuela de samba)", "N"),
    "salgueiro": ("Salgueiro (escuela de samba)", "N"), "paraty": ("Paraty (ciudad)", "N"),
    "búzios": ("Búzios (balneario)", "N"), "petrópolis": ("Petrópolis (ciudad)", "N"),
    "cinelândia": ("Cinelândia (plaza)", "N"), "carioca": ("carioca (de la ciudad de Río)", "A1"),
    "zona": ("zona (zona sul, zona norte)", "A2"),

    # --- otras ciudades, países y marcas ---
    "brasil": ("Brasil", "N"), "argentina": ("Argentina", "N"), "uruguai": ("Uruguay", "N"),
    "paraguai": ("Paraguay", "N"), "chile": ("Chile", "N"), "portugal": ("Portugal", "N"),
    "angola": ("Angola", "N"), "moçambique": ("Mozambique", "N"), "espanha": ("España", "N"),
    "itália": ("Italia", "N"), "frança": ("Francia", "N"), "alemanha": ("Alemania", "N"),
    "inglaterra": ("Inglaterra", "N"), "estados unidos": ("Estados Unidos", "N"), "eua": ("EE. UU.", "N"),
    "europa": ("Europa", "N"), "áfrica": ("África", "N"), "américa": ("América", "N"),
    "paulo": ("nombre; São Paulo", "N"), "são": ("san / santo (São Paulo); también son", "A1"),
    "salvador": ("Salvador (ciudad)", "N"), "recife": ("Recife (ciudad) / arrecife", "N"),
    "florianópolis": ("Florianópolis (ciudad)", "N"), "floripa": ("Florianópolis (coloquial)", "N"),
    "alegre": ("alegre; Porto Alegre", "A2"), "horizonte": ("horizonte; Belo Horizonte", "B1"),
    "brasília": ("Brasilia", "N"), "manaus": ("Manaos", "N"), "fortaleza": ("Fortaleza (ciudad) / fortaleza", "N"),
    "curitiba": ("Curitiba", "N"), "belém": ("Belém (ciudad) / Belén", "N"), "natal": ("Navidad; Natal (ciudad)", "A1"),
    "bahia": ("Bahía (estado)", "N"), "minas": ("Minas Gerais (estado)", "N"), "gerais": ("Minas Gerais", "N"),
    "amazônia": ("Amazonia", "N"), "amazonas": ("Amazonas", "N"), "pantanal": ("Pantanal", "N"),
    "nordeste": ("Nordeste", "B1"), "lisboa": ("Lisboa", "N"), "porto": ("puerto; Oporto", "A2"),
    "montevidéu": ("Montevideo", "N"), "córdoba": ("Córdoba", "N"), "rosário": ("Rosario (ciudad) / rosario", "N"),
    "buenos": ("Buenos Aires", "N"), "aires": ("Buenos Aires / aires", "N"), "mendoza": ("Mendoza", "N"),
    "bariloche": ("Bariloche", "N"), "havaianas": ("Havaianas (ojotas)", "N"), "enem": ("ENEM (examen nacional)", "N"),
    "sus": ("SUS (sistema público de salud)", "N"), "celpe-bras": ("Celpe-Bras (examen de portugués)", "N"),
    "globo": ("Globo (canal de TV) / globo", "N"), "netflix": ("Netflix", "N"), "uber": ("Uber", "N"),
    "whatsapp": ("WhatsApp", "N"), "instagram": ("Instagram", "N"), "rg": ("RG (documento de identidad)", "N"),
    "cep": ("CEP (código postal)", "N"), "detran": ("DETRAN (oficina de tránsito)", "N"),

    # --- castellano dentro de pistas y consignas ---
    "vos": ("", "ES"), "che": ("", "ES"), "acá": ("", "ES"), "sos": ("", "ES"), "tenés": ("", "ES"),
    "querés": ("", "ES"), "podés": ("", "ES"), "decile": ("", "ES"), "mañana": ("", "ES"),
    "ustedes": ("", "ES"), "ojalá": ("", "ES"), "colectivo": ("", "ES"), "heladera": ("", "ES"),
    "pibe": ("", "ES"), "piba": ("", "ES"), "fue": ("", "ES"), "hay": ("", "ES"), "muy": ("", "ES"),
    "más": ("", "ES"), "pero": ("", "ES"), "gusta": ("", "ES"), "tengo": ("", "ES"), "hacer": ("", "ES"),
    "llamar": ("", "ES"), "decir": ("", "ES"), "yo": ("", "ES"), "ella": ("", "ES"), "ellos": ("", "ES"),

    # --- formas coloquiales (se leen; se escriben solo si la consigna pide registro coloquial) ---
    "tô": ("estoy (coloquial de estou)", "A2"), "tá": ("está (coloquial)", "A1"), "tão": ("tan; están (coloquial)", "A2"),
    "tamo": ("estamos (coloquial)", "B1"), "tava": ("estaba (coloquial de estava)", "B1"),
    "tavam": ("estaban (coloquial)", "B1"), "cê": ("vos (coloquial de você)", "B1"),
    "cês": ("ustedes (coloquial de vocês)", "B1"), "pra": ("para (coloquial)", "A1"), "pro": ("para el (coloquial)", "A2"),
    "pras": ("para las (coloquial)", "B1"), "pros": ("para los (coloquial)", "B1"), "prum": ("para un (coloquial)", "B2"),
    "numa": ("en una", "A2"), "né": ("¿no? (de não é)", "A1"), "vamo": ("vamos (coloquial)", "B1"),
    "bora": ("vamos (coloquial)", "B1"), "cadê": ("¿dónde está?", "A2"), "ó": ("mirá (coloquial de olha)", "B1"),
    "olha": ("mirá", "A1"), "peraí": ("esperá (de espera aí)", "B1"), "vambora": ("vámonos (de vamos embora)", "B2"),
    "coé": ("¿qué onda? (carioca, de qual é)", "C1"), "sussa": ("tranqui (coloquial)", "C1"),
    "firmeza": ("firmeza; ¡dale! (coloquial)", "B2"), "sinistro": ("siniestro; buenísimo (carioca)", "B2"),
    "irado": ("enojado; buenísimo (coloquial)", "B2"), "bolado": ("preocupado / enojado (carioca)", "C1"),
    "mané": ("gil, tonto (carioca)", "C1"), "vacilão": ("el que se manda macanas (coloquial)", "C1"),
    "vacilar": ("mandarse una macana (coloquial)", "C1"), "caô": ("mentira, verso (carioca)", "C1"),
    "biscoito": ("galletita", "A2"), "mate": ("mate helado (en la playa de Río)", "B1"),
    "globo de biscoito": ("rosquitas Globo (de la playa)", "N"), "cafezinho": ("cafecito", "A1"),
    "chopinho": ("chop (diminutivo)", "B1"), "cervejinha": ("cervecita", "B1"), "pouquinho": ("poquito", "A1"),
    "rapidinho": ("rapidito", "A2"), "pertinho": ("cerquita", "A2"), "agorinha": ("recién / hace un ratito", "B1"),
    "cedinho": ("tempranito", "B1"), "devagarinho": ("despacito", "B1"), "bonitinho": ("lindito / tierno", "A2"),
    "gatinho": ("gatito", "A1"), "casinha": ("casita", "A1"), "jeitinho": ("modo, maña (el jeitinho brasileiro)", "B1"),
    "obrigadinho": ("gracias (cariñoso)", "B2"), "beijinho": ("besito", "A2"), "tempinho": ("ratito", "B1"),
    "filhinho": ("hijito", "B1"), "amorzinho": ("amorcito", "B1"), "lindinho": ("lindito", "B1"),
    "sozinha": ("sola (sin compañía)", "A2"), "lindíssimo": ("lindísimo", "B1"), "muitíssimo": ("muchísimo", "B1"),
    "ótimo": ("excelente", "A1"), "caríssimo": ("carísimo", "B1"), "facílimo": ("facilísimo", "B2"),
    "dificílimo": ("dificilísimo", "B2"), "baratinho": ("baratito", "B1"), "friozinho": ("fresquito", "B1"),
    "calorzão": ("calorazo", "B1"), "golaço": ("golazo", "B1"), "carrão": ("autazo", "B1"),
    "festão": ("fiestón", "B1"), "paredão": ("paredón", "B2"),

    # --- A1 ---
    "senhor": ("señor", "A1"), "senhora": ("señora", "A1"), "moço": ("joven / muchacho (al llamar)", "A2"),
    "praça": ("plaza", "A1"), "alô": ("¿hola? (al atender el teléfono)", "A1"), "tchau": ("chau", "A1"),
    "ok": ("ok", "A1"), "tipo": ("tipo; como que (muletilla)", "A2"), "gente": ("gente; ¡che!", "A1"),
    "cara": ("cara; el tipo, che (coloquial)", "A1"), "mano": ("hermano, che (paulista)", "B2"),
    "véi": ("viejo, che (coloquial)", "C1"), "brother": ("hermano, che", "B2"),
    "sul": ("sur", "A1"), "norte": ("norte", "A1"), "leste": ("este (punto cardinal)", "A2"),
    "oeste": ("oeste", "A2"), "quilômetro": ("kilómetro", "A1"), "quilômetros": ("kilómetros", "A1"),
    "metro": ("metro (medida)", "A1"), "metros": ("metros", "A1"), "grama": ("gramo; pasto", "A2"),
    "litro": ("litro", "A1"), "real": ("real (moneda); real, verdadero", "A1"), "reais": ("reales (moneda)", "A1"),
    "e-mails": ("mails", "A1"), "wi-fi": ("wifi", "A1"), "tevê": ("tele", "A1"), "tv": ("tele", "A1"),
    "pizza": ("pizza", "A1"), "hambúrguer": ("hamburguesa", "A1"), "pão de queijo": ("pan de queso", "A1"),
    "guaraná": ("guaraná (gaseosa)", "A1"), "tapioca": ("tapioca", "B1"), "açaí": ("açaí", "A2"),
    "picolé": ("palito helado", "A2"), "mate gelado": ("mate helado", "B1"), "caipira": ("de campo / paisano", "B1"),
    "ônibus": ("colectivo", "A1"), "vans": ("combis", "B1"),

    # --- A2 ---
    "embora": ("aunque; ir embora = irse", "A2"), "aliás": ("por cierto", "B2"),
    "mesmo": ("mismo; en serio", "A2"), "gostoso": ("rico, sabroso", "A1"),
    "à beça": ("un montón (carioca)", "C1"), "pô": ("¡uh! / ¡che! (carioca)", "B2"),
    "oxe": ("¡uh! (nordestino)", "C1"), "uai": ("¡uh! (mineiro)", "C1"), "bah": ("¡bah! (gaúcho)", "C1"),
    "tri": ("re, muy (gaúcho)", "C1"), "trem": ("tren; cosa (mineiro)", "A1"),
    "guri": ("pibe (gaúcho)", "C1"), "guria": ("piba (gaúcho)", "C1"),
    "mulherada": ("las chicas (coloquial)", "C1"), "rapaziada": ("los muchachos (coloquial)", "C1"),
    "pessoal": ("personal; la gente, los chicos", "A2"), "galera": ("la barra, la gente", "B1"),
    "praiano": ("playero", "B2"), "praieira": ("playera", "B2"), "boêmia": ("bohemia (la noche de la Lapa)", "B2"),
    "boêmio": ("bohemio", "B2"), "sambista": ("sambista", "B1"), "passista": ("bailarina/o de samba del desfile", "C1"),
    "mestre-sala": ("maestro de sala (pareja de la bandera en el desfile)", "C1"),
    "porta-bandeira": ("portabandera (del desfile)", "C1"), "bateria": ("batería (también de la escuela de samba)", "B1"),
    "tamborim": ("tamborín", "C1"), "cuíca": ("cuíca (instrumento)", "C1"), "surdo": ("sordo; bombo del samba", "B2"),
    "sunga": ("malla de hombre", "B1"), "canga": ("lona de playa", "B1"), "guarda-sol": ("sombrilla", "A2"),
    "cadeira de praia": ("reposera", "B1"), "protetor solar": ("protector solar", "A2"), "protetor": ("protector", "B1"),
    "bronzeado": ("bronceado", "B1"), "salva-vidas": ("guardavidas", "B1"), "posto": ("puesto (de guardavidas); estación de servicio", "A2"),
    "ciclovia": ("bicisenda", "B1"), "bicicletário": ("estacionamiento de bicis", "C1"),
    "bilhete único": ("tarjeta de transporte", "B1"), "vlt": ("tranvía del centro de Río (VLT)", "N"),
    "brt": ("colectivo rápido (BRT)", "N"), "bonde": ("tranvía (el de Santa Teresa)", "B1"),
    "orelhão": ("teléfono público (en desuso)", "C1"), "padoca": ("panadería (coloquial paulista)", "C1"),
    "lanchonete": ("casa de sándwiches", "A2"), "self-service": ("tenedor libre", "B1"),
    "quentinha": ("vianda (comida para llevar)", "B2"), "marmita": ("vianda", "B2"),
    "prato feito": ("plato del día", "B1"), "pf": ("plato del día (prato feito)", "B2"),
    "saideira": ("la última (copa)", "B2"), "caipivodka": ("caipiroska", "B2"),
    "empada": ("empanadita", "B1"), "esfiha": ("empanada árabe", "B1"), "pastelaria": ("puesto de pastéis", "B2"),
    "aipim": ("mandioca (en Río)", "B1"), "macaxeira": ("mandioca (en el Nordeste)", "C1"),
    "biscoito globo": ("rosquitas Globo", "N"),

    # --- B1 ---
    "saudoso": ("añorado; querido que ya no está", "B2"), "garoto": ("pibe", "A2"),
    "malandro": ("vivo, pícaro (el malandro carioca)", "B1"), "malandragem": ("picardía", "C1"),
    "gambiarra": ("atado con alambre (arreglo improvisado)", "C1"), "puxadinho": ("ampliación precaria de una casa", "C1"),
    "desenrolar": ("resolver, arreglárselas (carioca)", "C1"), "zoeira": ("joda, cachondeo (coloquial)", "C1"),
    "perrengue": ("apuro, lío (coloquial)", "C1"), "treta": ("pelea, lío (coloquial)", "C1"),
    "crush": ("persona que te gusta", "B2"), "ficante": ("relación casual (coloquial)", "C1"),
    "balada": ("salida nocturna, boliche (paulista)", "B2"), "rolezinho": ("salidita", "C1"),
    "happy hour": ("after office", "B1"), "chopp": ("chop (grafía de marca)", "B1"),
    "garçonete": ("moza", "A2"), "gringo": ("extranjero (cualquiera)", "B1"), "hermano": ("argentino (coloquial)", "B2"),
    "hermanos": ("argentinos (coloquial)", "B2"), "portunhol": ("portuñol", "B1"),
    "réveillon": ("Año Nuevo", "B1"), "virada": ("cambio; la noche de Año Nuevo", "B2"),
    "fogos": ("fuegos artificiales", "B1"), "oferenda": ("ofrenda", "C1"),
    "jogo do bicho": ("quiniela clandestina", "C1"), "bicheiro": ("capo del jogo do bicho", "C1"),
    "chorinho": ("choro (música)", "B2"), "roda": ("ronda (de samba, de capoeira)", "B1"),
    "berimbau": ("berimbau (instrumento de la capoeira)", "C1"), "axé": ("axé (música bahiana; buena energía)", "B2"),
    "orixá": ("orixá (divinidad afrobrasileña)", "C1"), "terreiro": ("templo afrobrasileño; patio", "C1"),
    "quilombo": ("quilombo (comunidad de esclavos fugados)", "C1"), "sertão": ("sertón (interior semiárido)", "C1"),
    "caatinga": ("caatinga (bioma)", "C1"), "cerrado": ("cerrado (bioma)", "C1"), "jangada": ("balsa de pescadores", "C1"),
    "cordel": ("literatura de cordel", "C1"), "repentista": ("payador", "C1"),

    # --- B2 / C1: registro formal y escrito ---
    "outrossim": ("asimismo (formal)", "C1"), "destarte": ("de este modo (formal)", "C1"),
    "porquanto": ("porque (formal)", "C1"), "conquanto": ("aunque (formal)", "C1"),
    "mormente": ("sobre todo (formal)", "C1"), "doravante": ("de ahora en adelante", "C1"),
    "vossa": ("vuestra (Vossa Senhoria, Vossa Excelência)", "C1"), "excelência": ("excelencia", "B2"),
    "senhoria": ("señoría", "C1"), "prezado": ("estimado (en cartas)", "B2"), "prezada": ("estimada", "B2"),
    "atenciosamente": ("atentamente (en cartas)", "B2"), "cordialmente": ("cordialmente", "B2"),
    "anexo": ("adjunto", "B2"), "segue": ("sigue; va adjunto (segue em anexo)", "B2"),
    "encaminhar": ("reenviar / derivar", "B2"), "solicitar": ("solicitar", "B1"), "mediante": ("mediante", "C1"),
    "supracitado": ("arriba citado", "C1"), "referente": ("referente", "B2"), "tendo em vista": ("teniendo en cuenta", "C1"),
    "no tocante": ("en lo que respecta", "C1"), "à luz": ("a la luz (de)", "C1"),
    "fizera": ("había hecho (literario)", "C1"), "dissera": ("había dicho (literario)", "C1"),
    "fora": ("afuera; había sido/ido (literario)", "A2"),
    "capitu": ("Capitu (personaje de Dom Casmurro)", "N"), "casmurro": ("Dom Casmurro (novela de Machado)", "N"),
    "brás cubas": ("Brás Cubas (personaje de Machado)", "N"), "macabéa": ("Macabéa (personaje de Clarice)", "N"),
    "sertanejo": ("del sertón; música country brasileña", "B2"), "cronista": ("cronista", "B2"),
    "tupi": ("tupí (lengua indígena)", "C1"), "guarani": ("guaraní", "C1"),
    "lusófono": ("de lengua portuguesa", "C1"), "lusofonia": ("lusofonía", "C1"),
    "gerúndio": ("gerundio", "A2"), "infinitivo": ("infinitivo", "A2"), "subjuntivo": ("subjuntivo", "B1"),
    "crase": ("crase (a + a = à)", "B2"), "próclise": ("próclisis (pronombre antes del verbo)", "C1"),
    "ênclise": ("enclisis (pronombre después del verbo)", "C1"), "mesóclise": ("mesoclisis (dir-lhe-ei)", "C1"),
    "regência": ("régimen (preposición que pide el verbo)", "C1"), "concordância": ("concordancia", "B2"),
}
