# -*- coding: utf-8 -*-
"""Banco de sustantivos portugueses (PB) para hispanohablantes rioplatenses.

Cada entrada: (singular, género, plural, español, tema, nivel, nota)

Mismo esquema que el banco italiano (build_bank.py y banca.js lo leen así):
el tema usa las mismas claves que en italiano (casa, cibo, corpo, famiglia,
lavoro, città, negozi, viaggio, tempo, natura, animali, salute, tecnologia,
vestiti, sentimenti, sport, scuola, cultura, società, astratti) para que el
motor no cambie.

La nota es contrastiva: heterogenéricos (o leite, a árvore, a viagem),
heterotónicos (polícia, cérebro, nível), heterosemánticos o falsos amigos
(escritório, oficina, polvo, borracha, apelido) y plurales que traban
(-ões / -ães / -ãos, -is, -ns).

Se escriben seis campos por palabra (sin el tema, que da la sección) y el
plural se calcula con las reglas regulares cuando va vacío (""):

- vocal (también tónica o nasal -ã) → +s: casa / casas, café / cafés, irmã / irmãs;
- -m → -ns: homem / homens;
- -r, -z → +es: mulher / mulheres, luz / luzes;
- -al → -ais, -ol → -óis, -ul → -uis; -el → -éis si es aguda (hotel /
  hotéis) y -eis si ya lleva tilde (nível / níveis).

Los plurales en -ão, -il, -s, -x y -n se escriben siempre a mano (no hay
regla segura): _plural() se niega a adivinarlos.
"""
import re

_ACC = "áéíóúâêôãõà"


def _plural(s):
    last = s.split(" ")[0] if " " in s else s
    rest = s[len(last):]
    w = last
    if w.endswith("ão") or re.search(r"(il|s|x|n)$", w):
        raise ValueError("plural a mano: " + s)
    if re.search(r"[aeiouáéíóúâêôã]$", w):
        p = w + "s"
    elif w.endswith("m"):
        p = w[:-1] + "ns"
    elif re.search(r"[rz]$", w):
        p = w + "es"
    elif w.endswith("al"):
        p = w[:-2] + "ais"
    elif w.endswith("ol"):
        p = w[:-2] + "óis"
    elif w.endswith("ul"):
        p = w[:-2] + "uis"
    elif w.endswith("el"):
        p = w[:-2] + ("eis" if any(c in _ACC for c in w[:-2]) else "éis")
    else:
        raise ValueError("plural a mano: " + s)
    return p + rest


_RAW = {}

# ------------------------------------------------------------------ casa
_RAW["casa"] = [
    ("casa", "f", "", "casa", "A1", ""),
    ("apartamento", "m", "", "departamento", "A1", "En Brasil se abrevia apê (coloquial)."),
    ("quarto", "m", "", "habitación / dormitorio", "A1", "Quarto también es «cuarto» (un cuarto, a quarta parte)."),
    ("sala", "f", "", "living / sala", "A1", "Sala de estar, sala de jantar; sala de aula = aula."),
    ("cozinha", "f", "", "cocina", "A1", "nh = ñ: co-zi-ña."),
    ("banheiro", "m", "", "baño", "A1", "Banheira es la bañera; banho, el baño que te das."),
    ("cama", "f", "", "cama", "A1", ""),
    ("mesa", "f", "", "mesa", "A1", ""),
    ("cadeira", "f", "", "silla", "A1", "Falso amigo: cadeira = silla; la cadera es o quadril."),
    ("porta", "f", "", "puerta", "A1", "Sin diptongo: porta (no «puerta»)."),
    ("janela", "f", "", "ventana", "A1", ""),
    ("parede", "f", "", "pared", "A1", ""),
    ("chão", "m", "chãos", "piso / suelo", "A2", "Plural en -ãos: chãos."),
    ("teto", "m", "", "techo (interior)", "A2", "El techo de afuera es o telhado."),
    ("telhado", "m", "", "techo (exterior) / tejado", "B1", ""),
    ("andar", "m", "", "piso (de un edificio)", "A2", "Moro no terceiro andar. También es el verbo andar."),
    ("escada", "f", "", "escalera", "A1", ""),
    ("elevador", "m", "", "ascensor", "A1", ""),
    ("varanda", "f", "", "balcón / galería", "A2", ""),
    ("sacada", "f", "", "balcón", "B1", ""),
    ("quintal", "m", "", "patio (de atrás) / fondo", "A2", "Quintal: el fondo de la casa, con plantas."),
    ("jardim", "m", "", "jardín", "A1", "Plural en -ns: jardins."),
    ("garagem", "f", "", "garaje / cochera", "A1", "Género distinto: el garaje → a garagem (todas las -agem son femeninas)."),
    ("porão", "m", "porões", "sótano", "B1", "Falso amigo: el sótano es o porão; o sótão es el altillo."),
    ("sótão", "m", "sótãos", "altillo / buhardilla", "B2", "Falso amigo: sótão = altillo, no «sótano» (porão). Plural sótãos."),
    ("armário", "m", "", "armario / placard", "A1", ""),
    ("guarda-roupa", "m", "guarda-roupas", "ropero", "A2", "Compuesto: plural guarda-roupas."),
    ("sofá", "m", "", "sillón / sofá", "A1", ""),
    ("poltrona", "f", "", "sillón individual", "A2", "Género distinto: el sillón → a poltrona."),
    ("estante", "f", "", "estante / biblioteca (mueble)", "A2", ""),
    ("gaveta", "f", "", "cajón", "A2", ""),
    ("espelho", "m", "", "espejo", "A2", "lh = ll antigua: es-pe-llo."),
    ("tapete", "m", "", "alfombra", "A2", "Género distinto: la alfombra → o tapete."),
    ("cortina", "f", "", "cortina", "A2", ""),
    ("lâmpada", "f", "", "lamparita / foco", "A2", "Lâmpada es la bombita; el velador es o abajur."),
    ("abajur", "m", "", "velador (lámpara de mesa)", "B1", ""),
    ("geladeira", "f", "", "heladera", "A1", "En Portugal, o frigorífico."),
    ("fogão", "m", "fogões", "cocina (el artefacto)", "A2", "Plural fogões."),
    ("forno", "m", "", "horno", "A2", "Forno: la o se abre en el plural (fornos, «fórnos»)."),
    ("micro-ondas", "m", "micro-ondas", "microondas", "A2", "Invariable, con guion."),
    ("máquina de lavar", "f", "máquinas de lavar", "lavarropas", "A2", "Género distinto: el lavarropas → a máquina de lavar."),
    ("pia", "f", "", "pileta / bacha (de cocina o baño)", "A2", ""),
    ("torneira", "f", "", "canilla", "A2", "Género distinto: el grifo → a torneira."),
    ("chuveiro", "m", "", "ducha (el aparato)", "A2", "Tomar banho = ducharse o bañarse."),
    ("banheira", "f", "", "bañera", "B1", ""),
    ("vaso sanitário", "m", "vasos sanitários", "inodoro", "B1", "Falso amigo: vaso es inodoro o maceta; el vaso de tomar es o copo."),
    ("toalha", "f", "", "toalla", "A2", ""),
    ("sabonete", "m", "", "jabón (de tocador)", "A2", "Sabão es el jabón para lavar ropa."),
    ("sabão", "m", "sabões", "jabón (de lavar)", "B1", ""),
    ("travesseiro", "m", "", "almohada", "A2", "Género distinto: la almohada → o travesseiro."),
    ("almofada", "f", "", "almohadón", "B1", "Falso amigo: almofada = almohadón; la almohada es o travesseiro."),
    ("cobertor", "m", "", "frazada / manta", "A2", ""),
    ("lençol", "m", "", "sábana", "A2", "Género distinto: la sábana → o lençol. Plural lençóis."),
    ("chave", "f", "", "llave", "A1", ""),
    ("fechadura", "f", "", "cerradura", "B1", ""),
    ("campainha", "f", "", "timbre", "B1", "Tocar a campainha = tocar el timbre."),
    ("vizinho", "m", "", "vecino", "A1", ""),
    ("aluguel", "m", "", "alquiler", "A2", "Plural aluguéis."),
    ("condomínio", "m", "", "edificio o barrio cerrado / expensas", "B1", "Pagar o condomínio = pagar las expensas."),
    ("porteiro", "m", "", "portero", "A2", "Personaje fijo de los prédios de Copacabana."),
    ("prédio", "m", "", "edificio", "A1", "Prédio = edificio; edifício también existe, más formal."),
    ("mudança", "f", "", "mudanza / cambio", "A2", "Mudança = mudanza y también cambio."),
    ("móvel", "m", "", "mueble", "A2", "Plural móveis. Como adjetivo: celular = telefone móvel."),
    ("vassoura", "f", "", "escoba", "B1", ""),
    ("balde", "m", "", "balde", "B1", ""),
    ("lixo", "m", "", "basura", "A2", "Género distinto: la basura → o lixo. Lixeira = tacho de basura."),
    ("lixeira", "f", "", "tacho de basura", "B1", ""),
    ("ventilador", "m", "", "ventilador", "A2", ""),
    ("ar-condicionado", "m", "ares-condicionados", "aire acondicionado", "A2", ""),
    ("tomada", "f", "", "enchufe (en la pared)", "B1", ""),
    ("interruptor", "m", "", "interruptor / llave de luz", "B1", ""),
    ("prateleira", "f", "", "estante", "B1", ""),
    ("berço", "m", "", "cuna", "B1", ""),
    ("cabide", "m", "", "percha", "B2", ""),
    ("ferro de passar", "m", "ferros de passar", "plancha", "B1", "Passar roupa = planchar."),
    ("faxina", "f", "", "limpieza general", "B1", "Fazer faxina; a faxineira = la señora de la limpieza."),
    ("goteira", "f", "", "gotera", "B2", ""),
    ("azulejo", "m", "", "azulejo", "B1", ""),
    ("fachada", "f", "", "fachada", "B2", ""),
    ("terraço", "m", "", "terraza", "B1", ""),
    ("cerca", "f", "", "cerco / alambrado", "B2", "Falso amigo: cerca = cerco; «cerca de» = cerca de, alrededor de."),
    ("portão", "m", "portões", "portón", "A2", ""),
    ("muro", "m", "", "muro / tapia", "B1", ""),
]

# ---------------------------------------------------------------------- cibo
_RAW["cibo"] = [
    ("comida", "f", "", "comida", "A1", ""),
    ("pão", "m", "pães", "pan", "A1", "Plural en -ães: pães. Pão francês = el pancito de todos los días."),
    ("arroz", "m", "", "arroz", "A1", ""),
    ("feijão", "m", "feijões", "poroto", "A1", "Arroz com feijão: la base del plato brasileño."),
    ("feijoada", "f", "", "feijoada (guiso de porotos negros)", "A2", "En Río, feijoada los sábados en el boteco."),
    ("farofa", "f", "", "farofa (harina de mandioca tostada)", "B1", ""),
    ("mandioca", "f", "", "mandioca", "A2", "En Río aipim; en el Nordeste macaxeira."),
    ("carne", "f", "", "carne", "A1", ""),
    ("frango", "m", "", "pollo", "A1", ""),
    ("peixe", "m", "", "pescado / pez", "A1", "Peixe = pescado y pez."),
    ("camarão", "m", "camarões", "camarón / langostino", "A2", "Plural camarões."),
    ("polvo", "m", "", "pulpo", "B1", "Falso amigo: polvo = pulpo; el polvo es a poeira o o pó."),
    ("lula", "f", "", "calamar", "B2", ""),
    ("ovo", "m", "", "huevo", "A1", "Singular «ôvo», plural «óvos»: la o se abre."),
    ("leite", "m", "", "leche", "A1", "Género distinto: la leche → o leite."),
    ("queijo", "m", "", "queso", "A1", "Pão de queijo: el bocado mineiro."),
    ("manteiga", "f", "", "manteca", "A2", "Falso amigo: manteiga = manteca (de leche)."),
    ("presunto", "m", "", "jamón", "A2", "Falso amigo: presunto = jamón; «presunto» en español es suposto."),
    ("açúcar", "m", "", "azúcar", "A1", "Masculino: o açúcar."),
    ("sal", "m", "", "sal", "A1", "Género distinto: la sal → o sal. Plural sais."),
    ("pimenta", "f", "", "pimienta / ají picante", "A2", "Pimentão = morrón."),
    ("pimentão", "m", "pimentões", "morrón", "B1", ""),
    ("azeite", "m", "", "aceite de oliva", "A2", "Falso amigo: azeite = aceite de oliva; o óleo = aceite de cocina."),
    ("óleo", "m", "", "aceite (de cocina, de motor)", "B1", ""),
    ("vinagre", "m", "", "vinagre", "A2", ""),
    ("molho", "m", "", "salsa", "A2", "Falso amigo: la salsa (de tomate) es o molho; salsa es perejil."),
    ("salsa", "f", "", "perejil", "B1", "Falso amigo: salsa = perejil; la salsa es o molho."),
    ("alho", "m", "", "ajo", "A2", ""),
    ("cebola", "f", "", "cebolla", "A2", ""),
    ("tomate", "m", "", "tomate", "A1", ""),
    ("batata", "f", "", "papa", "A1", "Batata-doce = batata."),
    ("cenoura", "f", "", "zanahoria", "A2", ""),
    ("alface", "f", "", "lechuga", "A2", "Femenino: a alface."),
    ("legume", "m", "", "verdura / hortaliza", "A2", "Género distinto: la legumbre → o legume (y significa verdura en general)."),
    ("verdura", "f", "", "verdura de hoja", "A2", ""),
    ("salada", "f", "", "ensalada", "A1", "Salada de frutas = ensalada de frutas."),
    ("fruta", "f", "", "fruta", "A1", ""),
    ("maçã", "f", "", "manzana", "A1", "Plural maçãs."),
    ("banana", "f", "", "banana", "A1", ""),
    ("laranja", "f", "", "naranja", "A1", ""),
    ("limão", "m", "limões", "limón / lima", "A1", "Plural limões. Na caipirinha va limão (lima)."),
    ("abacaxi", "m", "", "ananá", "A2", ""),
    ("manga", "f", "", "mango", "A2", "Manga también es la manga de la camisa. Género distinto: el mango → a manga."),
    ("mamão", "m", "mamões", "papaya / mamón", "A2", ""),
    ("uva", "f", "", "uva", "A1", ""),
    ("morango", "m", "", "frutilla", "A2", ""),
    ("melancia", "f", "", "sandía", "A2", ""),
    ("abacate", "m", "", "palta", "A2", ""),
    ("coco", "m", "", "coco", "A1", "Água de coco, la bebida de la praia."),
    ("açaí", "m", "", "açaí (fruto amazónico)", "A2", ""),
    ("maracujá", "m", "", "maracuyá / mburucuyá", "B1", ""),
    ("goiaba", "f", "", "guayaba", "B1", "Goiabada com queijo = «Romeu e Julieta»."),
    ("caju", "m", "", "cajú", "B1", ""),
    ("massa", "f", "", "pasta / masa", "A2", ""),
    ("macarrão", "m", "macarrões", "fideos", "A1", ""),
    ("sopa", "f", "", "sopa", "A1", ""),
    ("bolo", "m", "", "torta / bizcochuelo", "A1", "Bolo de aniversário = torta de cumpleaños."),
    ("torta", "f", "", "tarta / pastel (salado o dulce)", "A2", ""),
    ("biscoito", "m", "", "galletita", "A2", "En Río biscoito; en São Paulo bolacha."),
    ("bolacha", "f", "", "galletita", "B1", ""),
    ("doce", "m", "", "dulce / postre", "A1", "Doce de leite = dulce de leche."),
    ("sobremesa", "f", "", "postre", "A2", "Falso amigo: sobremesa = postre."),
    ("sorvete", "m", "", "helado", "A1", ""),
    ("chocolate", "m", "", "chocolate", "A1", ""),
    ("brigadeiro", "m", "", "brigadeiro (dulce de chocolate)", "A2", ""),
    ("pastel", "m", "", "empanada frita de feria", "A2", "Falso amigo: pastel es la empanada de la feira; la torta es o bolo. Plural pastéis."),
    ("coxinha", "f", "", "coxinha (croqueta de pollo)", "A2", ""),
    ("salgado", "m", "", "bocadito salado", "B1", ""),
    ("lanche", "m", "", "merienda / sándwich", "A2", "Lanche = merienda o sándwich; lanchonete = casa de sándwiches."),
    ("sanduíche", "m", "", "sándwich", "A1", ""),
    ("café", "m", "", "café", "A1", "Café da manhã = desayuno."),
    ("café da manhã", "m", "cafés da manhã", "desayuno", "A1", ""),
    ("almoço", "m", "", "almuerzo", "A1", ""),
    ("jantar", "m", "", "cena", "A1", "Falso amigo: la cena es o jantar; cena es escena."),
    ("chá", "m", "", "té", "A1", ""),
    ("suco", "m", "", "jugo", "A1", "En Portugal, sumo."),
    ("água", "f", "", "agua", "A1", "A água (el agua en español lleva «el»)."),
    ("refrigerante", "m", "", "gaseosa", "A2", ""),
    ("cerveja", "f", "", "cerveza", "A1", "Chope = cerveza tirada."),
    ("chope", "m", "", "chop / cerveza tirada", "A2", ""),
    ("vinho", "m", "", "vino", "A1", "nh = ñ: vi-ño."),
    ("cachaça", "f", "", "cachaza (aguardiente de caña)", "A2", ""),
    ("caipirinha", "f", "", "caipiriña", "A2", ""),
    ("gelo", "m", "", "hielo", "A2", ""),
    ("garrafa", "f", "", "botella", "A2", "Falso amigo: garrafa = botella; la garrafa de gas es o botijão."),
    ("copo", "m", "", "vaso (para tomar)", "A1", "Falso amigo: copo = vaso; a taça = copa; o vaso = maceta o inodoro."),
    ("taça", "f", "", "copa (de vino)", "A2", "Falso amigo: taça = copa; la taza es a xícara."),
    ("xícara", "f", "", "taza", "A2", "Falso amigo: la taza es a xícara (en Portugal, chávena)."),
    ("prato", "m", "", "plato", "A1", ""),
    ("talher", "m", "", "cubierto", "B1", ""),
    ("garfo", "m", "", "tenedor", "A2", ""),
    ("faca", "f", "", "cuchillo", "A2", "Género distinto: el cuchillo → a faca."),
    ("colher", "f", "", "cuchara", "A2", "Femenina: a colher (se dice «coLLÉR»). También es el verbo cosechar."),
    ("guardanapo", "m", "", "servilleta", "B1", "Género distinto: la servilleta → o guardanapo."),
    ("panela", "f", "", "olla", "B1", "Falso amigo: panela = olla."),
    ("frigideira", "f", "", "sartén", "B1", "Género distinto: el sartén → a frigideira."),
    ("receita", "f", "", "receta", "A2", "También la receta del médico."),
    ("cardápio", "m", "", "menú / carta", "A2", "Em Portugal, ementa."),
    ("conta", "f", "", "cuenta", "A1", "A conta, por favor."),
    ("gorjeta", "f", "", "propina", "B1", "Falso amigo: la propina es a gorjeta; propina en PB es soborno."),
    ("garçom", "m", "", "mozo / camarero", "A1", "Plural garçons. Femenino: garçonete."),
    ("restaurante", "m", "", "restaurante", "A1", ""),
    ("boteco", "m", "", "bar de barrio / bodegón", "A2", "El boteco carioca: chope, petiscos y mesa en la vereda."),
    ("botequim", "m", "", "bar de barrio (en Río)", "B1", "Plural botequins."),
    ("petisco", "m", "", "picada / tapa", "B1", ""),
    ("churrasco", "m", "", "asado", "A2", "Churrascaria: parrilla con rodízio."),
    ("churrascaria", "f", "", "parrilla (restaurante)", "B1", ""),
    ("tempero", "m", "", "condimento / sazón", "B1", ""),
    ("farinha", "f", "", "harina", "A2", ""),
    ("milho", "m", "", "maíz / choclo", "A2", ""),
    ("pipoca", "f", "", "pochoclo", "A2", ""),
    ("mel", "m", "", "miel", "A2", "Género distinto: la miel → o mel. Plural méis."),
    ("amendoim", "m", "", "maní", "B1", "Plural amendoins."),
    ("castanha", "f", "", "castaña / nuez", "B1", "Castanha-do-pará = nuez de Brasil."),
    ("linguiça", "f", "", "chorizo / longaniza", "A2", "Sin diéresis desde 1990: linguiça."),
    ("salsicha", "f", "", "salchicha", "A2", ""),
    ("carne moída", "f", "carnes moídas", "carne picada", "B1", ""),
    ("bife", "m", "", "bife / filete", "A2", ""),
    ("costela", "f", "", "costilla", "B1", ""),
    ("fome", "f", "", "hambre", "A1", "Femenino: a fome (el hambre). Estar com fome."),
    ("sede", "f", "", "sed", "A1", "Con e cerrada («sêde») = sed; con e abierta («séde») = sede, oficina central."),
    ("gosto", "m", "", "gusto / sabor", "A2", ""),
    ("sabor", "m", "", "sabor", "A2", ""),
    ("fatia", "f", "", "feta / rebanada / porción", "B1", ""),
    ("pedaço", "m", "", "pedazo", "A2", ""),
    ("quilo", "m", "", "kilo", "A1", "Restaurante a quilo: pagás lo que pesa el plato."),
    ("dieta", "f", "", "dieta", "B1", ""),
    ("tapioca", "f", "", "tapioca (panqueque de almidón de mandioca)", "B1", ""),
    ("acarajé", "m", "", "acarajé (buñuelo bahiano)", "B2", ""),
    ("moqueca", "f", "", "moqueca (guiso de pescado)", "B1", ""),
    ("quindim", "m", "", "quindim (dulce de yema y coco)", "B2", "Plural quindins."),
    ("padaria", "f", "", "panadería", "A1", ""),
    ("iogurte", "m", "", "yogur", "A2", ""),
    ("cereal", "m", "", "cereal", "B1", ""),
    ("azeitona", "f", "", "aceituna", "B1", ""),
    ("cogumelo", "m", "", "hongo / champiñón", "B1", ""),
    ("ervilha", "f", "", "arveja", "B1", ""),
    ("abóbora", "f", "", "zapallo / calabaza", "B1", ""),
    ("berinjela", "f", "", "berenjena", "B1", ""),
    ("pepino", "m", "", "pepino", "B1", ""),
    ("repolho", "m", "", "repollo", "B1", ""),
    ("couve", "f", "", "col / berza", "B1", "Couve refogada acompaña la feijoada."),
    ("pêssego", "m", "", "durazno", "B1", ""),
    ("pera", "f", "", "pera", "A2", "Sin tilde desde 1990: pera."),
    ("ameixa", "f", "", "ciruela", "B1", ""),
    ("cereja", "f", "", "cereza", "B1", ""),
    ("jabuticaba", "f", "", "jabuticaba (fruta)", "C1", ""),
    ("rodízio", "m", "", "tenedor libre con servicio en la mesa", "B1", ""),
]

# --------------------------------------------------------------------- corpo
_RAW["corpo"] = [
    ("corpo", "m", "", "cuerpo", "A1", "Plural corpos con o abierta."),
    ("cabeça", "f", "", "cabeza", "A1", "ç = s: ca-BE-sa."),
    ("cabelo", "m", "", "pelo (de la cabeza) / cabello", "A1", "O cabelo = el pelo de la cabeza; pelo es el vello del cuerpo."),
    ("rosto", "m", "", "cara / rostro", "A2", ""),
    ("cara", "f", "", "cara", "A1", "O cara (masculino, coloquial) = el tipo, el chabón."),
    ("olho", "m", "", "ojo", "A1", "Olho con o cerrada; plural olhos con o abierta."),
    ("nariz", "m", "", "nariz", "A1", "Género distinto: la nariz → o nariz."),
    ("boca", "f", "", "boca", "A1", ""),
    ("dente", "m", "", "diente", "A1", ""),
    ("língua", "f", "", "lengua (órgano e idioma)", "A2", ""),
    ("lábio", "m", "", "labio", "B1", ""),
    ("orelha", "f", "", "oreja", "A1", "Ouvido = oído (el órgano interno)."),
    ("ouvido", "m", "", "oído", "B1", ""),
    ("pescoço", "m", "", "cuello", "A2", "El cuello de la camisa es a gola o o colarinho."),
    ("garganta", "f", "", "garganta", "A2", ""),
    ("ombro", "m", "", "hombro", "A2", ""),
    ("braço", "m", "", "brazo", "A1", ""),
    ("cotovelo", "m", "", "codo", "B1", ""),
    ("mão", "f", "mãos", "mano", "A1", "Plural en -ãos: mãos. Femenina como en español."),
    ("dedo", "m", "", "dedo", "A1", ""),
    ("unha", "f", "", "uña", "A2", "nh = ñ: u-ña."),
    ("peito", "m", "", "pecho", "A2", ""),
    ("costas", "f", "costas", "espalda", "A2", "Solo plural: as costas. Dor nas costas = dolor de espalda."),
    ("barriga", "f", "", "panza", "A2", ""),
    ("estômago", "m", "", "estómago", "A2", ""),
    ("cintura", "f", "", "cintura", "B1", ""),
    ("quadril", "m", "quadris", "cadera", "B1", "Falso amigo: la cadera es o quadril; cadeira es silla."),
    ("perna", "f", "", "pierna", "A1", "Sin diptongo: perna."),
    ("joelho", "m", "", "rodilla", "A2", ""),
    ("pé", "m", "", "pie", "A1", "A pé = a pie."),
    ("tornozelo", "m", "", "tobillo", "B1", ""),
    ("calcanhar", "m", "", "talón", "B2", ""),
    ("pele", "f", "", "piel", "A2", ""),
    ("osso", "m", "", "hueso", "A2", "Plural ossos con o abierta."),
    ("sangue", "m", "", "sangre", "A2", "Género distinto: la sangre → o sangue."),
    ("coração", "m", "corações", "corazón", "A1", "Plural corações."),
    ("pulmão", "m", "pulmões", "pulmón", "B1", "Plural pulmões."),
    ("fígado", "m", "", "hígado", "B1", ""),
    ("rim", "m", "", "riñón", "B1", "Plural rins."),
    ("cérebro", "m", "", "cerebro", "B1", "Acento distinto: CÉ-re-bro (es. ce-RE-bro)."),
    ("músculo", "m", "", "músculo", "B1", ""),
    ("sobrancelha", "f", "", "ceja", "B1", ""),
    ("cílio", "m", "", "pestaña", "B2", ""),
    ("bochecha", "f", "", "mejilla / cachete", "B1", ""),
    ("queixo", "m", "", "mentón / pera", "B1", "Queixa (f.) es una queja."),
    ("testa", "f", "", "frente", "B1", "Género distinto: la frente → a testa."),
    ("barba", "f", "", "barba", "A2", ""),
    ("bigode", "m", "", "bigote", "B1", ""),
    ("voz", "f", "", "voz", "A2", ""),
    ("suor", "m", "", "sudor", "B1", ""),
    ("lágrima", "f", "", "lágrima", "B1", ""),
    ("respiração", "f", "respirações", "respiración", "B1", ""),
    ("postura", "f", "", "postura", "B2", ""),
    ("umbigo", "m", "", "ombligo", "B2", ""),
    ("punho", "m", "", "puño / muñeca", "B2", ""),
    ("polegar", "m", "", "pulgar", "B2", ""),
    ("nuca", "f", "", "nuca", "B2", ""),
    ("coluna", "f", "", "columna (vertebral)", "B1", ""),
    ("veia", "f", "", "vena", "B2", ""),
    ("nervo", "m", "", "nervio", "B2", ""),
    ("cicatriz", "f", "", "cicatriz", "B2", ""),
    ("careca", "f", "", "pelada (calvicie)", "B2", "Também adjetivo: ele é careca = es pelado."),
]

# ------------------------------------------------------------------ famiglia
_RAW["famiglia"] = [
    ("família", "f", "", "familia", "A1", ""),
    ("pai", "m", "", "padre / papá", "A1", "Os pais = los padres (padre y madre)."),
    ("mãe", "f", "", "madre / mamá", "A1", "Plural mães."),
    ("filho", "m", "", "hijo", "A1", "lh = ll: fi-llo."),
    ("filha", "f", "", "hija", "A1", ""),
    ("irmão", "m", "irmãos", "hermano", "A1", "Plural en -ãos: irmãos."),
    ("irmã", "f", "", "hermana", "A1", "Plural irmãs."),
    ("avô", "m", "", "abuelo", "A1", "Avô (ô cerrada) = abuelo; avó (ó abierta) = abuela. Os avós = los abuelos."),
    ("avó", "f", "", "abuela", "A1", "Avó con ó abierta; avô (abuelo) con ô cerrada."),
    ("neto", "m", "", "nieto", "A2", "Falso amigo: neto = nieto (y también «neto» en sueldo neto)."),
    ("neta", "f", "", "nieta", "A2", ""),
    ("tio", "m", "", "tío", "A1", "Ti suena «chi»: «chíu»."),
    ("tia", "f", "", "tía", "A1", ""),
    ("primo", "m", "", "primo", "A1", ""),
    ("prima", "f", "", "prima", "A1", ""),
    ("sobrinho", "m", "", "sobrino", "A2", ""),
    ("sobrinha", "f", "", "sobrina", "A2", ""),
    ("marido", "m", "", "marido", "A1", ""),
    ("esposa", "f", "", "esposa", "A2", ""),
    ("mulher", "f", "", "mujer / esposa", "A1", "Mulher = mujer y también esposa: a minha mulher."),
    ("homem", "m", "", "hombre", "A1", "Plural homens."),
    ("namorado", "m", "", "novio (pareja)", "A1", "Namorado = novio; noivo = prometido, el que se casa."),
    ("namorada", "f", "", "novia (pareja)", "A1", ""),
    ("noivo", "m", "", "prometido / novio (de la boda)", "B1", ""),
    ("noiva", "f", "", "prometida / novia (de la boda)", "B1", ""),
    ("casamento", "m", "", "casamiento / boda", "A2", ""),
    ("sogro", "m", "", "suegro", "B1", "Plural sogros con o abierta."),
    ("sogra", "f", "", "suegra", "B1", ""),
    ("genro", "m", "", "yerno", "B2", ""),
    ("nora", "f", "", "nuera", "B2", ""),
    ("cunhado", "m", "", "cuñado", "B1", ""),
    ("cunhada", "f", "", "cuñada", "B1", ""),
    ("padrinho", "m", "", "padrino", "B1", ""),
    ("madrinha", "f", "", "madrina", "B1", ""),
    ("parente", "m", "", "pariente", "B1", "Parente = pariente; los padres son os pais."),
    ("bebê", "m", "", "bebé", "A1", "Con circunflejo: bebê (en Portugal bebé)."),
    ("criança", "f", "", "chico / chica / nene (niño)", "A1", "Siempre femenino: a criança, aunque sea varón."),
    ("menino", "m", "", "chico / nene", "A1", ""),
    ("menina", "f", "", "chica / nena", "A1", ""),
    ("garoto", "m", "", "pibe / chico", "A2", "Garota de Ipanema: la chica de la canción de Tom Jobim y Vinicius."),
    ("garota", "f", "", "piba / chica", "A2", ""),
    ("rapaz", "m", "", "muchacho", "B1", ""),
    ("moça", "f", "", "muchacha / chica", "A2", ""),
    ("jovem", "m", "", "joven", "A2", "Plural jovens."),
    ("adulto", "m", "", "adulto", "A2", ""),
    ("idoso", "m", "", "persona mayor / anciano", "B1", "Idoso con o cerrada; plural idosos con o abierta."),
    ("gêmeo", "m", "", "gemelo / mellizo", "B1", ""),
    ("órfão", "m", "órfãos", "huérfano", "B2", "Plural órfãos."),
    ("viúvo", "m", "", "viudo", "B2", ""),
    ("casal", "m", "", "pareja (de dos personas)", "A2", "Um casal = una pareja. Plural casais."),
    ("amigo", "m", "", "amigo", "A1", ""),
    ("amiga", "f", "", "amiga", "A1", ""),
    ("colega", "m", "", "compañero / colega", "A2", "Colega de trabalho, de turma."),
    ("pessoa", "f", "", "persona", "A1", ""),
    ("gente", "f", "", "gente", "A1", "A gente = nosotros (con verbo en singular): a gente vai."),
    ("nome", "m", "", "nombre", "A1", "Género igual, pero ojo: o nome."),
    ("sobrenome", "m", "", "apellido", "A1", "Falso amigo: el apellido es o sobrenome; apelido es apodo."),
    ("apelido", "m", "", "apodo / sobrenombre", "A2", "Falso amigo: apelido = apodo; el apellido es o sobrenome."),
    ("aniversário", "m", "", "cumpleaños / aniversario", "A1", "Feliz aniversário! = ¡feliz cumpleaños!"),
    ("infância", "f", "", "infancia", "A2", ""),
    ("juventude", "f", "", "juventud", "B1", ""),
    ("velhice", "f", "", "vejez", "B2", ""),
    ("geração", "f", "gerações", "generación", "B1", ""),
    ("herança", "f", "", "herencia", "B2", ""),
    ("divórcio", "m", "", "divorcio", "B1", ""),
    ("gravidez", "f", "", "embarazo", "B1", "Grávida = embarazada; embaraçada es avergonzada."),
    ("nascimento", "m", "", "nacimiento", "A2", ""),
    ("antepassado", "m", "", "antepasado", "B2", ""),
    ("enteado", "m", "", "hijastro", "C1", ""),
    ("padrasto", "m", "", "padrastro", "B2", ""),
    ("madrasta", "f", "", "madrastra", "B2", ""),
]

# -------------------------------------------------------------------- salute
_RAW["salute"] = [
    ("saúde", "f", "", "salud", "A2", "Saúde! = ¡salud! (brindis y estornudo)."),
    ("médico", "m", "", "médico", "A1", ""),
    ("médica", "f", "", "médica", "A1", ""),
    ("enfermeiro", "m", "", "enfermero", "A2", ""),
    ("enfermeira", "f", "", "enfermera", "A2", ""),
    ("dentista", "m", "", "dentista", "A2", "Invariable en género: o / a dentista."),
    ("hospital", "m", "", "hospital", "A1", "Plural hospitais."),
    ("farmácia", "f", "", "farmacia", "A1", ""),
    ("remédio", "m", "", "remedio / medicamento", "A2", "Remédio = el remedio de la farmacia."),
    ("comprimido", "m", "", "pastilla / comprimido", "B1", ""),
    ("receita médica", "f", "receitas médicas", "receta médica", "B1", ""),
    ("consulta", "f", "", "consulta / turno médico", "A2", "Marcar uma consulta = pedir turno."),
    ("doença", "f", "", "enfermedad", "A2", ""),
    ("dor", "f", "", "dolor", "A1", "Género distinto: el dolor → a dor. Dor de cabeça."),
    ("febre", "f", "", "fiebre", "A2", ""),
    ("gripe", "f", "", "gripe", "A2", ""),
    ("resfriado", "m", "", "resfrío", "A2", ""),
    ("tosse", "f", "", "tos", "A2", ""),
    ("alergia", "f", "", "alergia", "B1", "Acento distinto: a-ler-GI-a (es. a-LER-gia)."),
    ("ferida", "f", "", "herida", "B1", ""),
    ("machucado", "m", "", "lastimadura / golpe", "B1", ""),
    ("sintoma", "m", "", "síntoma", "B1", "Acento distinto: sin-TO-ma (es. SÍN-to-ma)."),
    ("exame", "m", "", "análisis / estudio médico / examen", "A2", "Exame de sangue = análisis de sangre."),
    ("vacina", "f", "", "vacuna", "B1", ""),
    ("injeção", "f", "injeções", "inyección", "B1", ""),
    ("pronto-socorro", "m", "prontos-socorros", "guardia (de hospital)", "B1", ""),
    ("ambulância", "f", "", "ambulancia", "B1", ""),
    ("paciente", "m", "", "paciente", "B1", ""),
    ("tratamento", "m", "", "tratamiento", "B1", ""),
    ("cirurgia", "f", "", "cirugía", "B1", ""),
    ("plano de saúde", "m", "planos de saúde", "prepaga / obra social", "B1", "El SUS es el sistema público de salud."),
    ("estresse", "m", "", "estrés", "B1", ""),
    ("cansaço", "m", "", "cansancio", "B1", ""),
    ("sono", "m", "", "sueño (ganas de dormir)", "A1", "Estar com sono = tener sueño; el sueño que soñás es o sonho."),
    ("insônia", "f", "", "insomnio", "B2", "Género distinto: el insomnio → a insônia."),
    ("pressão", "f", "pressões", "presión", "B1", "Pressão alta = presión alta."),
    ("infecção", "f", "infecções", "infección", "B2", ""),
    ("diarreia", "f", "", "diarrea", "B1", "Sin tilde desde 1990: diarreia."),
    ("enjoo", "m", "", "mareo / náusea", "B1", "Sin tilde desde 1990: enjoo."),
    ("tontura", "f", "", "mareo", "B2", ""),
    ("gesso", "m", "", "yeso", "B2", ""),
    ("curativo", "m", "", "curita / vendaje", "B2", "El bandaid es o band-aid o o curativo."),
    ("termômetro", "m", "", "termómetro", "B1", ""),
    ("óculos", "m", "óculos", "anteojos", "A2", "Siempre plural: os óculos, meus óculos."),
    ("lente", "f", "", "lente", "B2", "Lente de contato."),
    ("anemia", "f", "", "anemia", "C1", "Acento distinto: a-ne-MI-a (es. a-NE-mia)."),
    ("epidemia", "f", "", "epidemia", "C1", "Acento distinto: e-pi-de-MI-a (es. e-pi-DE-mia)."),
    ("hemorragia", "f", "", "hemorragia", "C1", "Acento distinto: he-mor-ra-GI-a."),
    ("fisioterapia", "f", "", "kinesiología", "B2", "Acento distinto: fi-si-o-te-ra-PI-a."),
    ("psicólogo", "m", "", "psicólogo", "B1", ""),
    ("terapia", "f", "", "terapia", "B2", "Acento distinto: te-ra-PI-a (es. te-RA-pia)."),
    ("prevenção", "f", "prevenções", "prevención", "B2", ""),
    ("cura", "f", "", "cura (curación)", "B2", ""),
    ("vírus", "m", "vírus", "virus", "B1", "Invariable: os vírus."),
    ("máscara", "f", "", "barbijo / máscara", "B1", ""),
    ("ressaca", "f", "", "resaca", "B1", "Ressaca también es la marejada del mar de Río."),
    ("repouso", "m", "", "reposo", "B2", ""),
    ("check-up", "m", "check-ups", "chequeo médico", "B1", ""),
]

# -------------------------------------------------------------------- lavoro
_RAW["lavoro"] = [
    ("trabalho", "m", "", "trabajo", "A1", "lh = ll: tra-ba-llo."),
    ("emprego", "m", "", "empleo / trabajo", "A2", ""),
    ("desemprego", "m", "", "desempleo", "B1", ""),
    ("profissão", "f", "profissões", "profesión", "A1", "Plural profissões."),
    ("empresa", "f", "", "empresa", "A1", ""),
    ("firma", "f", "", "empresa / firma", "B2", "Falso amigo: firma = empresa; la firma (en un papel) es a assinatura."),
    ("escritório", "m", "", "oficina (lugar de trabajo)", "A1", "Falso amigo: escritório = oficina; oficina es taller mecánico."),
    ("oficina", "f", "", "taller (mecánico)", "B1", "Falso amigo: oficina = taller; la oficina es o escritório."),
    ("fábrica", "f", "", "fábrica", "A2", ""),
    ("loja", "f", "", "negocio / tienda", "A1", ""),
    ("chefe", "m", "", "jefe / jefa", "A1", "Invariable en género: o chefe, a chefe."),
    ("patrão", "m", "patrões", "patrón / empleador", "B1", "Plural patrões."),
    ("funcionário", "m", "", "empleado", "A2", "Funcionário público = empleado estatal."),
    ("empregado", "m", "", "empleado", "B1", ""),
    ("salário", "m", "", "sueldo / salario", "A2", ""),
    ("reunião", "f", "reuniões", "reunión", "A2", "Plural reuniões."),
    ("entrevista", "f", "", "entrevista", "A2", ""),
    ("currículo", "m", "", "currículum / CV", "A2", ""),
    ("vaga", "f", "", "puesto vacante / lugar para estacionar", "B1", "Vaga de emprego; vaga de garagem."),
    ("cargo", "m", "", "cargo / puesto", "B1", ""),
    ("carreira", "f", "", "carrera (profesional)", "B1", "La carrera universitaria es o curso."),
    ("contrato", "m", "", "contrato", "B1", ""),
    ("férias", "f", "férias", "vacaciones", "A1", "Siempre plural: as férias."),
    ("folga", "f", "", "franco / día libre", "B1", "Estar de folga = estar de franco."),
    ("feriado", "m", "", "feriado", "A2", ""),
    ("horário", "m", "", "horario", "A2", ""),
    ("hora extra", "f", "horas extras", "hora extra", "B1", ""),
    ("prazo", "m", "", "plazo", "B1", ""),
    ("tarefa", "f", "", "tarea", "A2", "Tarefa de casa = deberes (también dever de casa)."),
    ("projeto", "m", "", "proyecto", "A2", ""),
    ("negócio", "m", "", "negocio / asunto", "A2", "Também «cosa»: que negócio é esse? (coloquial)."),
    ("cliente", "m", "", "cliente", "A2", ""),
    ("vendedor", "m", "", "vendedor", "A2", ""),
    ("professor", "m", "", "profesor / maestro", "A1", ""),
    ("professora", "f", "", "profesora / maestra", "A1", ""),
    ("advogado", "m", "", "abogado", "A2", ""),
    ("engenheiro", "m", "", "ingeniero", "A2", ""),
    ("arquiteto", "m", "", "arquitecto", "A2", ""),
    ("jornalista", "m", "", "periodista", "A2", ""),
    ("motorista", "m", "", "chofer / conductor", "A2", "Motorista = conductor (de auto, colectivo)."),
    ("cozinheiro", "m", "", "cocinero", "A2", ""),
    ("cabeleireiro", "m", "", "peluquero", "B1", ""),
    ("policial", "m", "", "policía (la persona)", "A2", "O policial = el agente; a polícia = la institución. Plural policiais."),
    ("bombeiro", "m", "", "bombero / plomero (en Portugal)", "B1", "En Brasil bombeiro = bombero; el plomero es o encanador."),
    ("encanador", "m", "", "plomero", "B1", ""),
    ("pedreiro", "m", "", "albañil", "B1", ""),
    ("eletricista", "m", "", "electricista", "B1", ""),
    ("carteiro", "m", "", "cartero", "B1", ""),
    ("agricultor", "m", "", "agricultor", "B1", ""),
    ("pescador", "m", "", "pescador", "B1", ""),
    ("ator", "m", "", "actor", "A2", "Femenino atriz."),
    ("atriz", "f", "", "actriz", "A2", ""),
    ("cantor", "m", "", "cantante", "A2", "Femenino cantora."),
    ("cantora", "f", "", "cantante (mujer)", "A2", ""),
    ("músico", "m", "", "músico", "A2", ""),
    ("escritor", "m", "", "escritor", "A2", ""),
    ("pintor", "m", "", "pintor", "B1", ""),
    ("fotógrafo", "m", "", "fotógrafo", "B1", ""),
    ("programador", "m", "", "programador", "B1", ""),
    ("gerente", "m", "", "gerente", "B1", ""),
    ("diretor", "m", "", "director", "B1", ""),
    ("secretária", "f", "", "secretaria", "A2", "Secretária (con tilde) = la persona; secretaria (sin tilde) = la oficina, el ministerio."),
    ("estagiário", "m", "", "pasante", "B1", ""),
    ("estágio", "m", "", "pasantía", "B1", ""),
    ("aposentadoria", "f", "", "jubilación", "B2", ""),
    ("aposentado", "m", "", "jubilado", "B1", ""),
    ("greve", "f", "", "huelga / paro", "B2", "Femenino: a greve."),
    ("sindicato", "m", "", "sindicato", "B2", ""),
    ("lucro", "m", "", "ganancia / lucro", "B2", ""),
    ("prejuízo", "m", "", "pérdida (económica) / daño", "B2", "Falso amigo: prejuízo = pérdida; el prejuicio es o preconceito."),
    ("colega de trabalho", "m", "colegas de trabalho", "compañero de trabajo", "A2", ""),
    ("equipe", "f", "", "equipo (de trabajo)", "B1", "Género distinto: el equipo → a equipe. En Portugal, equipa."),
    ("empreendedor", "m", "", "emprendedor", "B2", ""),
    ("autônomo", "m", "", "trabajador independiente / monotributista", "B2", ""),
    ("bico", "m", "", "changa", "B2", "Coloquial: fazer um bico = hacer una changa. También pico (de ave)."),
    ("expediente", "m", "", "jornada (horario de oficina)", "B2", "Fora do expediente = fuera del horario."),
    ("demissão", "f", "demissões", "despido / renuncia", "B2", "Pedir demissão = renunciar; ser demitido = ser despedido."),
    ("promoção", "f", "promoções", "ascenso / oferta", "B1", "Promoção: ascenso en el trabajo y oferta en la tienda."),
    ("meta", "f", "", "meta / objetivo", "B1", ""),
    ("desafio", "m", "", "desafío", "B1", ""),
    ("filial", "f", "", "sucursal", "B2", "Plural filiais."),
    ("orçamento", "m", "", "presupuesto", "B2", ""),
    ("assinatura", "f", "", "firma / suscripción", "B1", "Falso amigo: la firma es a assinatura; firma es empresa."),
    ("carteira de trabalho", "f", "carteiras de trabalho", "libreta de trabajo (registro laboral)", "B2", "Trabalhar de carteira assinada = trabajar en blanco."),
    ("home office", "m", "home offices", "teletrabajo", "B1", ""),
    ("ferramenta", "f", "", "herramienta", "B1", ""),
    ("mercado de trabalho", "m", "mercados de trabalho", "mercado laboral", "B2", ""),
]

# --------------------------------------------------------------------- città
_RAW["città"] = [
    ("cidade", "f", "", "ciudad", "A1", "-dad → -dade: cidade, verdade, universidade."),
    ("bairro", "m", "", "barrio", "A1", "Copacabana, Ipanema, Lapa, Botafogo: bairros do Rio."),
    ("rua", "f", "", "calle", "A1", ""),
    ("avenida", "f", "", "avenida", "A1", "Avenida Atlântica, frente a la playa de Copacabana."),
    ("praça", "f", "", "plaza", "A1", ""),
    ("esquina", "f", "", "esquina", "A2", ""),
    ("calçada", "f", "", "vereda", "A2", "Falso amigo: calçada = vereda; la calzada es a rua / a pista."),
    ("calçadão", "m", "calçadões", "rambla / costanera peatonal", "A2", "El calçadão de Copacabana, con sus ondas de piedra portuguesa."),
    ("quarteirão", "m", "quarteirões", "cuadra / manzana", "B1", ""),
    ("centro", "m", "", "centro", "A1", ""),
    ("prefeitura", "f", "", "municipalidad / intendencia", "B1", "Prefeito = intendente."),
    ("prefeito", "m", "", "intendente", "B1", ""),
    ("igreja", "f", "", "iglesia", "A2", ""),
    ("museu", "m", "", "museo", "A1", "Plural museus."),
    ("cinema", "m", "", "cine", "A1", ""),
    ("teatro", "m", "", "teatro", "A2", ""),
    ("banco", "m", "", "banco", "A1", ""),
    ("correio", "m", "", "correo", "A2", "Os Correios = el correo postal."),
    ("mercado", "m", "", "mercado", "A1", ""),
    ("supermercado", "m", "", "supermercado", "A1", ""),
    ("feira", "f", "", "feria (de barrio)", "A1", "A feira: puestos en la calle; los días de la semana son segunda-feira, terça-feira..."),
    ("escola", "f", "", "escuela", "A1", ""),
    ("universidade", "f", "", "universidad", "A1", ""),
    ("biblioteca", "f", "", "biblioteca", "A2", ""),
    ("parque", "m", "", "parque", "A1", "Parque Lage, Aterro do Flamengo."),
    ("estádio", "m", "", "estadio", "A2", "O Maracanã."),
    ("hotel", "m", "", "hotel", "A1", "Plural hotéis."),
    ("estação", "f", "estações", "estación", "A1", "Plural estações. También estación del año."),
    ("ponto de ônibus", "m", "pontos de ônibus", "parada de colectivo", "A2", ""),
    ("metrô", "m", "", "subte / metro", "A1", "Con circunflejo: metrô."),
    ("trânsito", "m", "", "tránsito", "A2", ""),
    ("engarrafamento", "m", "", "embotellamiento / atasco", "B1", "Coloquial: engarrafamento; en São Paulo, congestionamento."),
    ("semáforo", "m", "", "semáforo", "A2", "En el Nordeste: sinal o sinaleira."),
    ("sinal", "m", "", "semáforo / señal", "A2", "Plural sinais. No Rio: vira à direita no sinal."),
    ("faixa de pedestres", "f", "faixas de pedestres", "senda peatonal", "B1", ""),
    ("pedestre", "m", "", "peatón", "B1", ""),
    ("ponte", "f", "", "puente", "A2", "Género distinto: el puente → a ponte. A Ponte Rio–Niterói."),
    ("túnel", "m", "", "túnel", "B1", "Plural túneis."),
    ("morro", "m", "", "cerro / morro", "A2", "No Rio, morro = cerro y también favela: o morro do Vidigal."),
    ("favela", "f", "", "favela / villa", "B1", "Hoy también se dice comunidade."),
    ("comunidade", "f", "", "comunidad / barrio popular", "B1", ""),
    ("subúrbio", "m", "", "barrio de la periferia", "B2", "Falso amigo parcial: en Río, subúrbio = zona norte y oeste, barrios populares."),
    ("periferia", "f", "", "periferia", "B2", ""),
    ("zona sul", "f", "zonas sul", "zona sur (de Río)", "B1", "La zona sul: Copacabana, Ipanema, Leblon, Botafogo."),
    ("orla", "f", "", "costanera / borde de la playa", "B1", "A orla de Copacabana."),
    ("mirante", "m", "", "mirador", "B1", "Mirante Dona Marta, en Botafogo."),
    ("bondinho", "m", "", "tranvía / teleférico", "B1", "O bondinho do Pão de Açúcar; o bondinho de Santa Teresa."),
    ("prédio histórico", "m", "prédios históricos", "edificio histórico", "B1", ""),
    ("monumento", "m", "", "monumento", "B1", ""),
    ("estátua", "f", "", "estatua", "B1", ""),
    ("fonte", "f", "", "fuente", "B1", ""),
    ("esgoto", "m", "", "cloaca / desagüe", "B2", ""),
    ("poluição", "f", "poluições", "contaminación", "B1", ""),
    ("barulho", "m", "", "ruido", "A2", ""),
    ("delegacia", "f", "", "comisaría", "B1", ""),
    ("polícia", "f", "", "policía (la institución)", "A2", "Acento distinto: po-LÍ-cia (es. po-li-CÍ-a)."),
    ("posto de gasolina", "m", "postos de gasolina", "estación de servicio", "A2", ""),
    ("estacionamento", "m", "", "estacionamiento", "A2", ""),
    ("rodoviária", "f", "", "terminal de ómnibus", "B1", ""),
    ("bloco", "m", "", "bloque / comparsa de carnaval", "B1", "O bloco de carnaval sale por las calles de Santa Teresa y la Lapa."),
    ("arco", "m", "", "arco", "B1", "Os Arcos da Lapa: el viejo acueducto."),
    ("escadaria", "f", "", "escalinata", "B2", "A Escadaria Selarón, entre Lapa y Santa Teresa."),
    ("ladeira", "f", "", "cuesta / subida", "B1", "As ladeiras de Santa Teresa."),
    ("beco", "m", "", "callejón", "B2", ""),
    ("cidadão", "m", "cidadãos", "ciudadano", "B1", "Plural cidadãos."),
    ("morador", "m", "", "vecino / habitante", "B1", ""),
    ("capital", "f", "", "capital (ciudad)", "A2", "Plural capitais."),
    ("região", "f", "regiões", "región", "A2", ""),
    ("estado", "m", "", "estado / provincia", "A2", "Brasil tiene 26 estados y el Distrito Federal."),
    ("país", "m", "países", "país", "A1", "Plural países (con tilde)."),
    ("interior", "m", "", "interior (fuera de la capital)", "B1", ""),
    ("vila", "f", "", "pueblo / barrio / pasaje", "B1", ""),
    ("aldeia", "f", "", "aldea", "B2", ""),
]

# -------------------------------------------------------------------- negozi
_RAW["negozi"] = [
    ("dinheiro", "m", "", "plata / dinero", "A1", ""),
    ("real", "m", "reais", "real (moneda)", "A1", "Plural reais: dez reais."),
    ("centavo", "m", "", "centavo", "A2", ""),
    ("troco", "m", "", "vuelto", "A2", ""),
    ("preço", "m", "", "precio", "A1", ""),
    ("desconto", "m", "", "descuento", "A2", ""),
    ("oferta", "f", "", "oferta", "A2", ""),
    ("liquidação", "f", "liquidações", "liquidación", "B1", ""),
    ("cartão", "m", "cartões", "tarjeta", "A1", "Plural cartões. Cartão de crédito."),
    ("pix", "m", "pix", "transferencia instantánea (Pix)", "A2", "Te passo um pix = te hago una transferencia."),
    ("boleto", "m", "", "boleta de pago", "B1", "Falso amigo: boleto = factura para pagar; el boleto de colectivo es a passagem."),
    ("nota fiscal", "f", "notas fiscais", "factura / ticket", "B1", "CPF na nota? = ¿Querés el CPF en el ticket?"),
    ("recibo", "m", "", "recibo", "B1", ""),
    ("caixa", "f", "", "caja", "A2", "O caixa = el cajero; a caixa = la caja (el mueble o la caja de cartón)."),
    ("caixa eletrônico", "m", "caixas eletrônicos", "cajero automático", "A2", ""),
    ("fila", "f", "", "cola / fila", "A2", "Fazer fila / entrar na fila."),
    ("compra", "f", "", "compra", "A1", "Fazer compras = hacer las compras."),
    ("sacola", "f", "", "bolsa (de las compras)", "A2", ""),
    ("vitrine", "f", "", "vidriera", "B1", ""),
    ("shopping", "m", "", "shopping", "A2", ""),
    ("tamanho", "m", "", "talle / tamaño", "A2", ""),
    ("provador", "m", "", "probador", "B1", ""),
    ("farmacêutico", "m", "", "farmacéutico", "B1", ""),
    ("açougue", "m", "", "carnicería", "B1", ""),
    ("peixaria", "f", "", "pescadería", "B1", ""),
    ("livraria", "f", "", "librería", "A2", "Falso amigo: livraria = librería; la biblioteca es a biblioteca."),
    ("papelaria", "f", "", "librería (útiles escolares)", "B1", ""),
    ("banca de jornal", "f", "bancas de jornal", "kiosco de diarios", "B1", ""),
    ("quiosque", "m", "", "quiosco (de playa)", "B1", "Los quiosques de la orla venden água de coco."),
    ("barraca", "f", "", "puesto (de playa o feria) / carpa", "B1", "A barraca de praia alquila sombrilla y reposera."),
    ("camelô", "m", "", "vendedor ambulante", "B1", ""),
    ("ambulante", "m", "", "vendedor ambulante", "B1", ""),
    ("mercadoria", "f", "", "mercadería", "B1", ""),
    ("produto", "m", "", "producto", "A2", ""),
    ("marca", "f", "", "marca", "A2", ""),
    ("qualidade", "f", "", "calidad", "A2", ""),
    ("embalagem", "f", "", "envase / empaque", "B1", "Género distinto: el embalaje → a embalagem."),
    ("pacote", "m", "", "paquete", "A2", ""),
    ("lata", "f", "", "lata", "A2", ""),
    ("pote", "m", "", "pote / frasco", "B1", ""),
    ("dúzia", "f", "", "docena", "A2", ""),
    ("pagamento", "m", "", "pago", "B1", ""),
    ("parcela", "f", "", "cuota", "B1", "Em três parcelas sem juros = en tres cuotas sin interés."),
    ("juros", "m", "juros", "intereses", "B2", "Siempre plural: os juros."),
    ("conta bancária", "f", "contas bancárias", "cuenta bancaria", "B1", ""),
    ("poupança", "f", "", "ahorro / caja de ahorro", "B1", ""),
    ("dívida", "f", "", "deuda", "B1", ""),
    ("empréstimo", "m", "", "préstamo", "B1", ""),
    ("gasto", "m", "", "gasto", "B1", ""),
    ("custo", "m", "", "costo", "B1", ""),
    ("taxa", "f", "", "tasa / cargo / comisión", "B1", ""),
    ("imposto", "m", "", "impuesto", "B1", ""),
    ("entrega", "f", "", "entrega / envío a domicilio", "A2", ""),
    ("encomenda", "f", "", "pedido / encomienda", "B1", ""),
    ("reclamação", "f", "reclamações", "reclamo / queja", "B1", ""),
    ("troca", "f", "", "cambio (de un producto)", "B1", ""),
    ("garantia", "f", "", "garantía", "B1", ""),
    ("balcão", "m", "balcões", "mostrador / barra", "B1", "Falso amigo: balcão = mostrador; el balcón es a varanda o a sacada."),
    ("freguês", "m", "fregueses", "cliente habitual", "B2", "Plural fregueses."),
    ("pechincha", "f", "", "ganga / pichincha", "C1", "Pechinchar = regatear."),
]

# ------------------------------------------------------------------- viaggio
_RAW["viaggio"] = [
    ("viagem", "f", "", "viaje", "A1", "Género distinto: el viaje → a viagem. Boa viagem!"),
    ("passagem", "f", "", "pasaje / boleto", "A2", "Género distinto: el pasaje → a passagem."),
    ("bagagem", "f", "", "equipaje", "A2", "Género distinto: el equipaje → a bagagem."),
    ("mala", "f", "", "valija", "A1", "Falso amigo: mala = valija; «mala» (adjetivo) es má."),
    ("mochila", "f", "", "mochila", "A1", ""),
    ("passaporte", "m", "", "pasaporte", "A1", ""),
    ("documento", "m", "", "documento", "A1", ""),
    ("carteira de identidade", "f", "carteiras de identidade", "DNI / cédula", "B1", "Coloquial: a identidade, o RG."),
    ("aeroporto", "m", "", "aeropuerto", "A1", "O Galeão y o Santos Dumont, los aeropuertos de Río."),
    ("avião", "m", "aviões", "avión", "A1", "Plural aviões."),
    ("voo", "m", "", "vuelo", "A2", "Sin tilde desde 1990: voo."),
    ("embarque", "m", "", "embarque", "B1", "Portão de embarque = puerta de embarque."),
    ("trem", "m", "", "tren", "A1", "Plural trens."),
    ("ônibus", "m", "ônibus", "colectivo / ómnibus", "A1", "Invariable: um ônibus, dois ônibus."),
    ("carro", "m", "", "auto", "A1", "rr aspirada, como una j suave: «cajo»."),
    ("moto", "f", "", "moto", "A1", ""),
    ("bicicleta", "f", "", "bicicleta", "A1", "Coloquial: bike."),
    ("táxi", "m", "", "taxi", "A1", ""),
    ("barco", "m", "", "barco", "A1", ""),
    ("navio", "m", "", "buque / barco grande", "B1", ""),
    ("barca", "f", "", "ferry / lancha", "B1", "A barca Rio–Niterói, desde la Praça XV."),
    ("porto", "m", "", "puerto", "A2", ""),
    ("estrada", "f", "", "ruta / carretera", "A2", "Falso amigo: estrada = ruta."),
    ("rodovia", "f", "", "autopista / ruta", "B1", ""),
    ("pedágio", "m", "", "peaje", "B1", ""),
    ("caminho", "m", "", "camino", "A2", ""),
    ("mapa", "m", "", "mapa", "A1", ""),
    ("turista", "m", "", "turista", "A1", ""),
    ("turismo", "m", "", "turismo", "A2", ""),
    ("reserva", "f", "", "reserva", "A2", ""),
    ("pousada", "f", "", "posada / hostería", "A2", ""),
    ("albergue", "m", "", "albergue / hostel", "B1", ""),
    ("hóspede", "m", "", "huésped", "B1", "Acento en la primera: HÓS-pe-de."),
    ("recepção", "f", "recepções", "recepción", "A2", ""),
    ("diária", "f", "", "tarifa por noche", "B1", "A diária do hotel."),
    ("excursão", "f", "excursões", "excursión", "A2", ""),
    ("passeio", "m", "", "paseo", "A2", "Dar um passeio no calçadão."),
    ("guia", "m", "", "guía", "A2", "O guia (persona); o guia / a guia (libro) según el caso."),
    ("lembrança", "f", "", "recuerdo / souvenir", "B1", ""),
    ("cartão-postal", "m", "cartões-postais", "postal", "B1", "El Pão de Açúcar, cartão-postal do Rio."),
    ("foto", "f", "", "foto", "A1", ""),
    ("câmera", "f", "", "cámara (de fotos)", "A2", "Acento circunflejo en Brasil: câmera."),
    ("chegada", "f", "", "llegada", "A2", ""),
    ("partida", "f", "", "salida / partida", "A2", ""),
    ("saída", "f", "", "salida", "A1", ""),
    ("entrada", "f", "", "entrada", "A1", ""),
    ("atraso", "m", "", "demora / retraso", "B1", ""),
    ("destino", "m", "", "destino", "A2", ""),
    ("fronteira", "f", "", "frontera", "B1", ""),
    ("alfândega", "f", "", "aduana", "B2", ""),
    ("visto", "m", "", "visa", "B1", "Género distinto: la visa → o visto."),
    ("estrangeiro", "m", "", "extranjero", "A2", "No exterior = en el extranjero."),
    ("assento", "m", "", "asiento", "A2", ""),
    ("janelinha", "f", "", "ventanilla", "B1", ""),
    ("corredor", "m", "", "pasillo", "A2", ""),
    ("cinto de segurança", "m", "cintos de segurança", "cinturón de seguridad", "B1", ""),
    ("gasolina", "f", "", "nafta", "A2", ""),
    ("pneu", "m", "", "neumático / goma", "B1", "Plural pneus."),
    ("acidente", "m", "", "accidente", "B1", ""),
    ("carona", "f", "", "aventón / que te lleven", "B1", "Dar carona = llevar a alguien; pegar carona = ir de aventón."),
    ("roteiro", "m", "", "itinerario / guion", "B1", ""),
    ("hospedagem", "f", "", "alojamiento", "B1", "Género distinto: el hospedaje → a hospedagem."),
    ("mochileiro", "m", "", "mochilero", "B1", ""),
    ("volta", "f", "", "vuelta / regreso", "A2", "Ida e volta = ida y vuelta."),
    ("ida", "f", "", "ida", "A2", ""),
    ("bilhete", "m", "", "boleto / entrada / nota", "A2", "Bilhete único: la tarjeta del transporte."),
    ("bilheteria", "f", "", "boletería", "B1", ""),
    ("fuso horário", "m", "fusos horários", "huso horario", "B2", ""),
    ("jet lag", "m", "jet lags", "desfase horario", "B2", ""),
    ("cruzeiro", "m", "", "crucero", "B1", ""),
    ("trilha", "f", "", "sendero / caminata", "B1", "Fazer trilha: subir a Pedra da Gávea o el Morro Dois Irmãos."),
    ("barraca de camping", "f", "barracas de camping", "carpa", "B2", ""),
]

# --------------------------------------------------------------------- tempo
_RAW["tempo"] = [
    ("tempo", "m", "", "tiempo (cronológico y clima)", "A1", "Que tempo faz? = ¿qué tiempo hace?"),
    ("dia", "m", "", "día", "A1", "Di suena «yi»: «yía»."),
    ("noite", "f", "", "noche", "A1", "Boa noite."),
    ("manhã", "f", "", "mañana (parte del día)", "A1", "De manhã = a la mañana; mañana (el día siguiente) es amanhã."),
    ("tarde", "f", "", "tarde", "A1", ""),
    ("madrugada", "f", "", "madrugada", "A2", ""),
    ("meia-noite", "f", "meias-noites", "medianoche", "A1", ""),
    ("meio-dia", "m", "meios-dias", "mediodía", "A1", ""),
    ("hora", "f", "", "hora", "A1", ""),
    ("minuto", "m", "", "minuto", "A1", ""),
    ("segundo", "m", "", "segundo", "A1", ""),
    ("semana", "f", "", "semana", "A1", ""),
    ("fim de semana", "m", "fins de semana", "fin de semana", "A1", "Plural fins de semana."),
    ("mês", "m", "meses", "mes", "A1", "Plural meses (sin tilde)."),
    ("ano", "m", "", "año", "A1", "Sin ñ: ano. Tenho vinte anos."),
    ("século", "m", "", "siglo", "B1", ""),
    ("década", "f", "", "década", "B1", ""),
    ("época", "f", "", "época", "B1", ""),
    ("momento", "m", "", "momento", "A2", ""),
    ("vez", "f", "", "vez", "A1", "Uma vez, duas vezes; às vezes = a veces."),
    ("data", "f", "", "fecha", "A2", "Falso amigo: data = fecha; los datos son os dados."),
    ("calendário", "m", "", "calendario", "A2", ""),
    ("agenda", "f", "", "agenda", "A2", ""),
    ("futuro", "m", "", "futuro", "A2", ""),
    ("passado", "m", "", "pasado", "A2", ""),
    ("presente", "m", "", "presente / regalo", "A1", "Presente = regalo: um presente de aniversário."),
    ("primavera", "f", "", "primavera", "A1", ""),
    ("verão", "m", "verões", "verano", "A1", "Plural verões. El verano carioca: calor de 40 grados."),
    ("outono", "m", "", "otoño", "A1", ""),
    ("inverno", "m", "", "invierno", "A1", ""),
    ("clima", "m", "", "clima", "A2", ""),
    ("sol", "m", "", "sol", "A1", "Plural sóis."),
    ("chuva", "f", "", "lluvia", "A1", ""),
    ("vento", "m", "", "viento", "A2", ""),
    ("nuvem", "f", "", "nube", "A2", "Plural nuvens."),
    ("neve", "f", "", "nieve", "A2", ""),
    ("calor", "m", "", "calor", "A1", "Masculino como en español: o calor. Estar com calor."),
    ("frio", "m", "", "frío", "A1", ""),
    ("temperatura", "f", "", "temperatura", "A2", ""),
    ("grau", "m", "", "grado", "A2", "Plural graus: quarenta graus."),
    ("tempestade", "f", "", "tormenta / tempestad", "B1", ""),
    ("temporal", "m", "", "temporal", "B1", "Plural temporais."),
    ("trovão", "m", "trovões", "trueno", "B1", ""),
    ("raio", "m", "", "rayo", "B1", ""),
    ("relâmpago", "m", "", "relámpago", "B1", ""),
    ("umidade", "f", "", "humedad", "B1", "Sin h: umidade."),
    ("seca", "f", "", "sequía", "B2", ""),
    ("previsão do tempo", "f", "previsões do tempo", "pronóstico del tiempo", "B1", ""),
    ("céu", "m", "", "cielo", "A2", "Plural céus."),
    ("garoa", "f", "", "llovizna", "B2", "La garoa es típica de São Paulo."),
    ("arco-íris", "m", "arco-íris", "arco iris", "B1", "Invariable."),
    ("nevoeiro", "m", "", "niebla", "B2", ""),
    ("feriadão", "m", "feriadões", "fin de semana largo", "B2", ""),
    ("véspera", "f", "", "víspera", "B2", ""),
    ("prazo de validade", "m", "prazos de validade", "fecha de vencimiento", "B2", ""),
    ("pôr do sol", "m", "pores do sol", "puesta del sol / atardecer", "A2", "El pôr do sol en el Arpoador se aplaude."),
    ("nascer do sol", "m", "nasceres do sol", "amanecer / salida del sol", "B1", ""),
    ("amanhecer", "m", "", "amanecer", "B1", ""),
    ("entardecer", "m", "", "atardecer", "B2", ""),
    ("segunda-feira", "f", "segundas-feiras", "lunes", "A1", "Los días hábiles se cuentan: segunda, terça, quarta, quinta, sexta."),
    ("terça-feira", "f", "terças-feiras", "martes", "A1", ""),
    ("quarta-feira", "f", "quartas-feiras", "miércoles", "A1", ""),
    ("quinta-feira", "f", "quintas-feiras", "jueves", "A1", ""),
    ("sexta-feira", "f", "sextas-feiras", "viernes", "A1", ""),
    ("sábado", "m", "", "sábado", "A1", ""),
    ("domingo", "m", "", "domingo", "A1", ""),
    ("janeiro", "m", "", "enero", "A1", "Los meses van con minúscula."),
    ("fevereiro", "m", "", "febrero", "A1", ""),
    ("março", "m", "", "marzo", "A1", ""),
    ("abril", "m", "abris", "abril", "A1", ""),
    ("maio", "m", "", "mayo", "A1", ""),
    ("junho", "m", "", "junio", "A1", "Festa junina: fiesta popular de junio."),
    ("julho", "m", "", "julio", "A1", ""),
    ("agosto", "m", "", "agosto", "A1", ""),
    ("setembro", "m", "", "septiembre", "A1", ""),
    ("outubro", "m", "", "octubre", "A1", ""),
    ("novembro", "m", "", "noviembre", "A1", ""),
    ("dezembro", "m", "", "diciembre", "A1", ""),
]

# -------------------------------------------------------------------- natura
_RAW["natura"] = [
    ("natureza", "f", "", "naturaleza", "A2", ""),
    ("praia", "f", "", "playa", "A1", "Ir à praia; estar na praia."),
    ("mar", "m", "", "mar", "A1", "Siempre masculino: o mar."),
    ("onda", "f", "", "ola", "A2", "Pegar onda = surfear (coloquial)."),
    ("areia", "f", "", "arena", "A2", ""),
    ("ilha", "f", "", "isla", "A2", "Ilha Grande, Ilha Fiscal."),
    ("lagoa", "f", "", "laguna", "A2", "A Lagoa Rodrigo de Freitas."),
    ("lago", "m", "", "lago", "A2", ""),
    ("rio", "m", "", "río", "A1", "O Rio (de Janeiro), con mayúscula, es la ciudad."),
    ("cachoeira", "f", "", "cascada", "B1", ""),
    ("montanha", "f", "", "montaña", "A2", ""),
    ("serra", "f", "", "sierra", "B1", "Serra dos Órgãos, Serra do Mar."),
    ("pedra", "f", "", "piedra", "A2", "A Pedra do Arpoador, a Pedra da Gávea."),
    ("floresta", "f", "", "bosque / selva", "A2", "A Floresta da Tijuca: la selva urbana de Río."),
    ("mata", "f", "", "monte / selva", "B1", "Mata Atlântica."),
    ("selva", "f", "", "selva", "B1", ""),
    ("árvore", "f", "", "árbol", "A1", "Género distinto: el árbol → a árvore."),
    ("planta", "f", "", "planta", "A2", ""),
    ("flor", "f", "", "flor", "A1", ""),
    ("folha", "f", "", "hoja", "A2", ""),
    ("galho", "m", "", "rama", "B2", "Género distinto: la rama → o galho."),
    ("raiz", "f", "", "raíz", "B1", "Plural raízes."),
    ("grama", "f", "", "pasto / césped", "B1", "A grama (el pasto); o grama (la unidad de peso)."),
    ("campo", "m", "", "campo", "A2", ""),
    ("terra", "f", "", "tierra", "A2", "Sin diptongo: terra."),
    ("mundo", "m", "", "mundo", "A1", ""),
    ("planeta", "m", "", "planeta", "B1", ""),
    ("lua", "f", "", "luna", "A2", ""),
    ("estrela", "f", "", "estrella", "A2", ""),
    ("ar", "m", "", "aire", "A2", "Plural ares."),
    ("fogo", "m", "", "fuego", "A2", "Fogos = fuegos artificiales del Réveillon."),
    ("fumaça", "f", "", "humo", "B1", "Género distinto: el humo → a fumaça."),
    ("poeira", "f", "", "polvo (suciedad)", "B1", "Falso amigo: el polvo es a poeira; polvo es pulpo."),
    ("paisagem", "f", "", "paisaje", "B1", "Género distinto: el paisaje → a paisagem."),
    ("vista", "f", "", "vista", "A2", ""),
    ("costa", "f", "", "costa", "B1", "Costa Verde, entre Río y Paraty."),
    ("litoral", "m", "", "litoral / costa", "B1", "Plural litorais."),
    ("baía", "f", "", "bahía", "B1", "A Baía de Guanabara."),
    ("enseada", "f", "", "ensenada", "B2", ""),
    ("maré", "f", "", "marea", "B1", ""),
    ("coqueiro", "m", "", "cocotero", "B1", ""),
    ("palmeira", "f", "", "palmera", "B1", ""),
    ("pedra portuguesa", "f", "pedras portuguesas", "baldosa de piedra portuguesa", "C1", "Las ondas del calçadão son de pedra portuguesa."),
    ("rocha", "f", "", "roca", "B1", ""),
    ("caverna", "f", "", "cueva", "B2", ""),
    ("deserto", "m", "", "desierto", "B1", ""),
    ("vulcão", "m", "vulcões", "volcán", "B2", "Plural vulcões."),
    ("terremoto", "m", "", "terremoto", "B2", ""),
    ("enchente", "f", "", "inundación / crecida", "B2", ""),
    ("meio ambiente", "m", "meios ambientes", "medio ambiente", "B1", ""),
    ("oceano", "m", "", "océano", "B1", "Acento distinto: o-ce-A-no (es. o-CÉ-a-no)."),
    ("atmosfera", "f", "", "atmósfera", "B2", "Acento distinto: at-mos-FE-ra (es. at-MÓS-fe-ra)."),
    ("oxigênio", "m", "", "oxígeno", "B2", "Acento distinto: o-xi-GÊ-nio (es. o-XÍ-ge-no)."),
    ("energia", "f", "", "energía", "B1", ""),
    ("reciclagem", "f", "", "reciclaje", "B1", "Género distinto: el reciclaje → a reciclagem."),
    ("desmatamento", "m", "", "deforestación", "B2", ""),
    ("queimada", "f", "", "incendio forestal / quema", "B2", ""),
    ("aquecimento global", "m", "aquecimentos globais", "calentamiento global", "B2", ""),
    ("semente", "f", "", "semilla", "B2", ""),
    ("colheita", "f", "", "cosecha", "B2", ""),
    ("horta", "f", "", "huerta", "B1", ""),
    ("jardinagem", "f", "", "jardinería", "B2", ""),
    ("espécie", "f", "", "especie", "B2", ""),
    ("ecossistema", "m", "", "ecosistema", "C1", ""),
    ("pântano", "m", "", "pantano", "C1", ""),
    ("mangue", "m", "", "manglar", "C1", ""),
    ("recife", "m", "", "arrecife", "B2", "Recife, con mayúscula, es la capital de Pernambuco."),
]

# ------------------------------------------------------------------- animali
_RAW["animali"] = [
    ("animal", "m", "", "animal", "A1", "Plural animais."),
    ("bicho", "m", "", "bicho / animal", "A2", "Jogo do bicho: la quiniela clandestina de Río."),
    ("cachorro", "m", "", "perro", "A1", "Falso amigo: cachorro = perro (adulto); el cachorro es o filhote."),
    ("cão", "m", "cães", "perro (formal)", "B1", "Plural en -ães: cães. En el habla, cachorro."),
    ("filhote", "m", "", "cachorro / cría", "B1", ""),
    ("gato", "m", "", "gato", "A1", ""),
    ("pássaro", "m", "", "pájaro", "A2", ""),
    ("ave", "f", "", "ave", "B1", ""),
    ("peixinho", "m", "", "pececito", "A2", ""),
    ("cavalo", "m", "", "caballo", "A2", ""),
    ("vaca", "f", "", "vaca", "A2", ""),
    ("boi", "m", "", "buey", "B1", ""),
    ("porco", "m", "", "cerdo / chancho", "A2", "Plural porcos con o abierta."),
    ("ovelha", "f", "", "oveja", "B1", ""),
    ("cabra", "f", "", "cabra", "B1", ""),
    ("galinha", "f", "", "gallina", "A2", ""),
    ("galo", "m", "", "gallo", "B1", ""),
    ("pato", "m", "", "pato", "B1", ""),
    ("coelho", "m", "", "conejo", "A2", ""),
    ("rato", "m", "", "ratón / rata", "A2", "Falso amigo: rato = ratón o rata; el rato (tiempo) es um tempinho."),
    ("camundongo", "m", "", "ratoncito", "B2", ""),
    ("macaco", "m", "", "mono", "A2", "Macaco = mono y también el gato (del auto)."),
    ("mico", "m", "", "tití (monito)", "B2", "Pagar mico = hacer el ridículo (coloquial)."),
    ("leão", "m", "leões", "león", "A2", "Plural leões."),
    ("tigre", "m", "", "tigre", "B1", ""),
    ("onça", "f", "", "yaguareté / jaguar", "B1", "La onça-pintada; la onza (peso) también es onça."),
    ("urso", "m", "", "oso", "B1", "Falso amigo de forma: el oso es o urso."),
    ("elefante", "m", "", "elefante", "A2", ""),
    ("girafa", "f", "", "jirafa", "B1", ""),
    ("cobra", "f", "", "víbora / serpiente", "B1", "Cobra = cualquier serpiente."),
    ("jacaré", "m", "", "yacaré", "B1", ""),
    ("tartaruga", "f", "", "tortuga", "B1", ""),
    ("sapo", "m", "", "sapo", "B1", ""),
    ("borboleta", "f", "", "mariposa", "B1", ""),
    ("abelha", "f", "", "abeja", "B1", ""),
    ("mosca", "f", "", "mosca", "B1", ""),
    ("mosquito", "m", "", "mosquito", "A2", "En el Nordeste, muriçoca; en Río, mosquito."),
    ("formiga", "f", "", "hormiga", "B1", ""),
    ("barata", "f", "", "cucaracha", "B1", "Falso amigo: barata = cucaracha; barato es el adjetivo."),
    ("aranha", "f", "", "araña", "B1", ""),
    ("baleia", "f", "", "ballena", "B1", ""),
    ("golfinho", "m", "", "delfín", "B1", ""),
    ("tubarão", "m", "tubarões", "tiburón", "B1", "Plural tubarões."),
    ("caranguejo", "m", "", "cangrejo", "B2", ""),
    ("papagaio", "m", "", "loro / papagayo", "B1", "Também el barrilete (en algunas regiones)."),
    ("arara", "f", "", "guacamayo", "B2", ""),
    ("tucano", "m", "", "tucán", "B1", ""),
    ("beija-flor", "m", "beija-flores", "picaflor / colibrí", "B1", ""),
    ("urubu", "m", "", "buitre negro / jote", "B2", "El urubu es símbolo de la hinchada del Flamengo."),
    ("pombo", "m", "", "paloma", "B1", "Género distinto: la paloma → o pombo (pomba, la hembra o de la paz)."),
    ("coruja", "f", "", "lechuza / búho", "B1", ""),
    ("minhoca", "f", "", "lombriz", "B2", ""),
    ("lagarto", "m", "", "lagarto", "B2", "Lagartixa = lagartija."),
    ("veado", "m", "", "ciervo / venado", "B2", ""),
    ("lobo", "m", "", "lobo", "B1", ""),
    ("raposa", "f", "", "zorro", "B1", "Género distinto: el zorro → a raposa."),
    ("capivara", "f", "", "carpincho", "B1", "Género distinto: el carpincho → a capivara."),
    ("preguiça", "f", "", "perezoso (animal) / pereza", "B1", "Preguiça = pereza y el animal perezoso."),
    ("pata", "f", "", "pata", "B1", ""),
    ("rabo", "m", "", "cola (de animal)", "B1", "Falso amigo: la cola del perro es o rabo; cola es pegamento."),
    ("asa", "f", "", "ala", "B1", ""),
    ("pena", "f", "", "pluma / pena", "B1", "Pena = pluma y también pena (que pena!)."),
    ("ninho", "m", "", "nido", "B2", "nh = ñ: ni-ño; no confundir con el niño (menino)."),
    ("jaula", "f", "", "jaula", "B1", ""),
    ("zoológico", "m", "", "zoológico", "A2", ""),
    ("veterinário", "m", "", "veterinario", "B1", ""),
    ("pet", "m", "", "mascota", "A2", "También animal de estimação."),
]

# ---------------------------------------------------------------- tecnologia
_RAW["tecnologia"] = [
    ("computador", "m", "", "computadora", "A1", "Género distinto: la computadora → o computador."),
    ("notebook", "m", "", "notebook / laptop", "A2", ""),
    ("celular", "m", "", "celular", "A1", "Plural celulares."),
    ("telefone", "m", "", "teléfono", "A1", ""),
    ("tela", "f", "", "pantalla", "A2", "Falso amigo: tela = pantalla (y la tela de pintar); la tela (género) es o tecido."),
    ("teclado", "m", "", "teclado", "A2", ""),
    ("mouse", "m", "", "mouse", "A2", ""),
    ("impressora", "f", "", "impresora", "A2", ""),
    ("internet", "f", "", "internet", "A1", "Femenino: a internet. Plural poco usado."),
    ("rede", "f", "", "red / hamaca", "A2", "Redes sociais; também la hamaca paraguaya."),
    ("site", "m", "", "sitio web", "A2", ""),
    ("página", "f", "", "página", "A2", ""),
    ("aplicativo", "m", "", "aplicación / app", "A2", "Coloquial: app."),
    ("programa", "m", "", "programa", "A2", ""),
    ("arquivo", "m", "", "archivo", "A2", ""),
    ("pasta", "f", "", "carpeta", "B1", "Falso amigo: pasta = carpeta (también la de la compu); la pasta de dientes es pasta de dente."),
    ("senha", "f", "", "contraseña / número de turno", "A2", "Senha = contraseña y también el número que te dan para hacer la fila."),
    ("usuário", "m", "", "usuario", "B1", ""),
    ("e-mail", "m", "", "mail / correo electrónico", "A1", ""),
    ("mensagem", "f", "", "mensaje", "A1", "Género distinto: el mensaje → a mensagem."),
    ("carregador", "m", "", "cargador", "A2", ""),
    ("bateria", "f", "", "batería", "A2", ""),
    ("tomada", "f", "", "enchufe", "B1", ""),
    ("fone de ouvido", "m", "fones de ouvido", "auriculares", "A2", ""),
    ("vídeo", "m", "", "video", "A2", "Con tilde en Brasil: vídeo."),
    ("foto de perfil", "f", "fotos de perfil", "foto de perfil", "B1", ""),
    ("rede social", "f", "redes sociais", "red social", "A2", ""),
    ("postagem", "f", "", "posteo / publicación", "B1", "Género distinto: el posteo → a postagem."),
    ("curtida", "f", "", "me gusta / like", "B1", ""),
    ("seguidor", "m", "", "seguidor", "B1", ""),
    ("download", "m", "", "descarga", "B1", ""),
    ("atualização", "f", "atualizações", "actualización", "B1", ""),
    ("tecnologia", "f", "", "tecnología", "A2", ""),
    ("máquina", "f", "", "máquina", "A2", ""),
    ("aparelho", "m", "", "aparato / equipo", "B1", ""),
    ("controle remoto", "m", "controles remotos", "control remoto", "B1", ""),
    ("televisão", "f", "televisões", "televisión", "A1", "Coloquial: a tevê."),
    ("rádio", "m", "", "radio (el aparato y la emisora)", "A2", "O rádio: masculino en Brasil."),
    ("câmera de segurança", "f", "câmeras de segurança", "cámara de seguridad", "B2", ""),
    ("dados", "m", "dados", "datos", "B1", "Os dados = los datos; data es la fecha."),
    ("nuvem", "f", "", "nube", "B1", ""),
    ("inteligência artificial", "f", "inteligências artificiais", "inteligencia artificial", "B2", ""),
    ("robô", "m", "", "robot", "B1", ""),
    ("algoritmo", "m", "", "algoritmo", "C1", ""),
    ("pesquisa", "f", "", "búsqueda / investigación / encuesta", "B1", ""),
    ("ciência", "f", "", "ciencia", "B1", ""),
    ("cientista", "m", "", "científico", "B1", ""),
    ("laboratório", "m", "", "laboratorio", "B1", ""),
    ("invenção", "f", "invenções", "invento / invención", "B2", ""),
    ("descoberta", "f", "", "descubrimiento", "B2", "Género distinto: el descubrimiento → a descoberta."),
    ("experiência", "f", "", "experiencia / experimento", "B1", ""),
    ("teste", "m", "", "prueba / test", "A2", ""),
    ("erro", "m", "", "error", "A2", ""),
    ("falha", "f", "", "falla", "B1", ""),
    ("conexão", "f", "conexões", "conexión", "B1", ""),
    ("sinal de wi-fi", "m", "sinais de wi-fi", "señal de wifi", "B1", ""),
    ("golpe", "m", "", "golpe / estafa", "B1", "Golpe do pix = estafa por transferencia; também golpe de Estado."),
    ("hacker", "m", "", "hacker", "B2", ""),
    ("print", "m", "", "captura de pantalla", "B1", "Coloquial: tirar um print."),
    ("figurinha", "f", "", "figurita / sticker", "B1", "Mandar figurinha no zap = mandar un sticker."),
    ("zap", "m", "", "WhatsApp (coloquial)", "B1", "Me chama no zap."),
]

# -------------------------------------------------------------------- vestiti
_RAW["vestiti"] = [
    ("roupa", "f", "", "ropa", "A1", ""),
    ("camisa", "f", "", "camisa", "A1", ""),
    ("camiseta", "f", "", "remera", "A1", ""),
    ("blusa", "f", "", "blusa / buzo liviano", "A2", ""),
    ("casaco", "m", "", "abrigo / campera", "A2", ""),
    ("jaqueta", "f", "", "campera", "A2", ""),
    ("suéter", "m", "", "pulóver", "B1", ""),
    ("moletom", "m", "", "buzo (de algodón)", "B1", "Plural moletons."),
    ("calça", "f", "", "pantalón", "A1", "Género distinto: el pantalón → a calça (también as calças)."),
    ("bermuda", "f", "", "bermuda", "A2", ""),
    ("short", "m", "", "short", "A2", ""),
    ("saia", "f", "", "pollera / falda", "A2", ""),
    ("vestido", "m", "", "vestido", "A1", ""),
    ("terno", "m", "", "traje (de hombre)", "B1", "Terno = traje de hombre (saco y pantalón)."),
    ("gravata", "f", "", "corbata", "B1", ""),
    ("cueca", "f", "", "calzoncillo", "B1", ""),
    ("calcinha", "f", "", "bombacha", "B1", ""),
    ("sutiã", "m", "", "corpiño", "B1", "Plural sutiãs."),
    ("meia", "f", "", "media", "A2", "Meia também es «seis» al dar números de teléfono."),
    ("sapato", "m", "", "zapato", "A1", ""),
    ("tênis", "m", "tênis", "zapatillas / tenis", "A1", "Invariable: um tênis, dois tênis."),
    ("chinelo", "m", "", "ojota / chancleta", "A2", "Las havaianas: o chinelo de todo el Brasil."),
    ("sandália", "f", "", "sandalia", "A2", ""),
    ("bota", "f", "", "bota", "A2", ""),
    ("chapéu", "m", "", "sombrero", "A2", "Plural chapéus."),
    ("boné", "m", "", "gorra", "A2", "Género distinto: la gorra → o boné."),
    ("biquíni", "m", "", "bikini", "A2", "Masculino: o biquíni."),
    ("sunga", "f", "", "malla de hombre (slip)", "B1", ""),
    ("maiô", "m", "", "malla enteriza", "B1", ""),
    ("canga", "f", "", "pareo / lona de playa", "B1", "Estender a canga na areia."),
    ("pijama", "m", "", "pijama", "A2", ""),
    ("cinto", "m", "", "cinturón", "B1", ""),
    ("bolsa", "f", "", "cartera (de mujer) / bolso / beca", "A2", "Bolsa = cartera; também bolsa de estudos = beca."),
    ("carteira", "f", "", "billetera", "A2", "Carteira = billetera y también libreta (de motorista, de trabalho)."),
    ("relógio", "m", "", "reloj", "A2", ""),
    ("anel", "m", "", "anillo", "B1", "Plural anéis."),
    ("colar", "m", "", "collar", "B1", "También el verbo pegar (con pegamento)."),
    ("brinco", "m", "", "aro / arete", "B1", "Falso amigo: brinco = aro (joya); el salto es o pulo."),
    ("pulseira", "f", "", "pulsera", "B1", ""),
    ("luva", "f", "", "guante", "B1", "Género distinto: el guante → a luva."),
    ("cachecol", "m", "", "bufanda", "B1", "Plural cachecóis."),
    ("guarda-chuva", "m", "guarda-chuvas", "paraguas", "A2", ""),
    ("bolso", "m", "", "bolsillo", "B1", "Falso amigo: bolso = bolsillo; el bolso es a bolsa."),
    ("botão", "m", "botões", "botón", "B1", ""),
    ("zíper", "m", "", "cierre (de ropa)", "B2", ""),
    ("manga", "f", "", "manga", "B1", ""),
    ("gola", "f", "", "cuello (de ropa)", "B2", ""),
    ("tecido", "m", "", "tela / tejido", "B1", "Falso amigo: la tela es o tecido; tela es pantalla."),
    ("algodão", "m", "algodões", "algodón", "B1", ""),
    ("seda", "f", "", "seda", "B2", ""),
    ("lã", "f", "", "lana", "B1", "Plural lãs."),
    ("couro", "m", "", "cuero", "B1", ""),
    ("moda", "f", "", "moda", "A2", ""),
    ("estilo", "m", "", "estilo", "B1", ""),
    ("fantasia", "f", "", "disfraz / fantasía", "B1", "Fantasia de carnaval = disfraz."),
    ("uniforme", "m", "", "uniforme", "B1", ""),
    ("costura", "f", "", "costura", "B2", ""),
    ("mancha", "f", "", "mancha", "B1", ""),
    ("lavanderia", "f", "", "lavandería / lavadero", "B1", ""),
    ("brechó", "m", "", "tienda de ropa usada", "B2", ""),
]

# ----------------------------------------------------------------- sentimenti
_RAW["sentimenti"] = [
    ("amor", "m", "", "amor", "A1", ""),
    ("paixão", "f", "paixões", "pasión / enamoramiento", "B1", "Plural paixões."),
    ("saudade", "f", "", "nostalgia / extrañar", "A2", "Estar com saudade de alguém = extrañar a alguien. Que saudade!"),
    ("alegria", "f", "", "alegría", "A2", ""),
    ("felicidade", "f", "", "felicidad", "A2", ""),
    ("tristeza", "f", "", "tristeza", "A2", ""),
    ("medo", "m", "", "miedo", "A2", "Ter medo de = tener miedo de."),
    ("raiva", "f", "", "bronca / rabia", "A2", "Estar com raiva = estar enojado."),
    ("vergonha", "f", "", "vergüenza", "A2", "Estar com vergonha. Embaraçado también es avergonzado."),
    ("ciúme", "m", "", "celos", "B1", "Suele ir en plural: ciúmes. Ter ciúme."),
    ("inveja", "f", "", "envidia", "B1", ""),
    ("orgulho", "m", "", "orgullo", "B1", ""),
    ("esperança", "f", "", "esperanza", "B1", ""),
    ("confiança", "f", "", "confianza", "B1", ""),
    ("preocupação", "f", "preocupações", "preocupación", "B1", ""),
    ("ansiedade", "f", "", "ansiedad", "B1", ""),
    ("calma", "f", "", "calma", "A2", ""),
    ("paz", "f", "", "paz", "A2", ""),
    ("surpresa", "f", "", "sorpresa", "A2", ""),
    ("emoção", "f", "emoções", "emoción", "B1", ""),
    ("sentimento", "m", "", "sentimiento", "B1", ""),
    ("humor", "m", "", "humor", "B1", "Bom humor / mau humor."),
    ("sorriso", "m", "", "sonrisa", "A2", "Género distinto: la sonrisa → o sorriso."),
    ("riso", "m", "", "risa", "B1", "Género distinto: la risa → o riso."),
    ("choro", "m", "", "llanto / choro (género musical)", "B1", "O choro: la música de Pixinguinha."),
    ("abraço", "m", "", "abrazo", "A1", "Um abraço: despedida común en mensajes."),
    ("beijo", "m", "", "beso", "A1", "Beijos: despedida afectuosa."),
    ("carinho", "m", "", "cariño / caricia", "A2", "Fazer carinho = hacer mimos."),
    ("saudação", "f", "saudações", "saludo", "B2", ""),
    ("desejo", "m", "", "deseo / antojo", "B1", ""),
    ("sonho", "m", "", "sueño (lo que soñás)", "A2", "Sonho = sueño que se sueña; sono = ganas de dormir."),
    ("tédio", "m", "", "aburrimiento", "B2", ""),
    ("solidão", "f", "solidões", "soledad", "B1", ""),
    ("amizade", "f", "", "amistad", "A2", ""),
    ("relacionamento", "m", "", "relación (de pareja)", "B1", ""),
    ("briga", "f", "", "pelea", "B1", ""),
    ("desculpa", "f", "", "disculpa / excusa", "A1", "Desculpa! = ¡perdón!"),
    ("perdão", "m", "perdões", "perdón", "B1", ""),
    ("culpa", "f", "", "culpa", "B1", ""),
    ("coragem", "f", "", "coraje / valentía", "B1", "Género distinto: el coraje → a coragem."),
    ("gratidão", "f", "gratidões", "gratitud", "B2", ""),
    ("nostalgia", "f", "", "nostalgia", "B2", "Acento distinto: nos-tal-GI-a (es. nos-TAL-gia)."),
    ("susto", "m", "", "susto", "B1", "Levar um susto = pegarse un susto."),
    ("nojo", "m", "", "asco", "B1", "Que nojo! = ¡qué asco!"),
    ("pena", "f", "", "pena / lástima", "A2", "Que pena! = ¡qué lástima! Valer a pena = valer la pena."),
    ("dó", "m", "", "lástima / pena", "C1", "Ter dó de alguém. También la nota do."),
    ("vontade", "f", "", "ganas / voluntad", "A2", "Estar com vontade de = tener ganas de. Fique à vontade = ponete cómodo."),
    ("gosto", "m", "", "gusto", "A2", ""),
    ("ódio", "m", "", "odio", "B1", ""),
    ("felicitação", "f", "felicitações", "felicitación", "C1", ""),
    ("frustração", "f", "frustrações", "frustración", "B2", ""),
    ("estado de espírito", "m", "estados de espírito", "estado de ánimo", "C1", ""),
    ("ânimo", "m", "", "ánimo", "B2", ""),
    ("afeto", "m", "", "afecto", "B2", ""),
    ("desânimo", "m", "", "desánimo", "B2", ""),
    ("encontro", "m", "", "encuentro / cita", "A2", "Encontro = cita romántica también."),
    ("cafuné", "m", "", "caricia en el pelo", "C1", "Palabra famosa por intraducible: fazer cafuné."),
]

# ---------------------------------------------------------------------- sport
_RAW["sport"] = [
    ("esporte", "m", "", "deporte", "A1", "En Portugal, desporto."),
    ("futebol", "m", "", "fútbol", "A1", "Plural futebóis (raro)."),
    ("jogo", "m", "", "partido / juego", "A1", "Jogo con o cerrada; plural jogos con o abierta."),
    ("partida", "f", "", "partido", "A2", ""),
    ("time", "m", "", "equipo (deportivo)", "A1", "Falso amigo: time = equipo. Qual é o seu time? Flamengo, Fluminense, Vasco, Botafogo."),
    ("seleção", "f", "seleções", "selección", "A2", "A seleção brasileira, a canarinho."),
    ("torcida", "f", "", "hinchada", "A2", ""),
    ("torcedor", "m", "", "hincha", "A2", ""),
    ("jogador", "m", "", "jugador", "A1", ""),
    ("técnico", "m", "", "director técnico", "B1", ""),
    ("juiz", "m", "", "árbitro / juez", "B1", "Plural juízes."),
    ("gol", "m", "", "gol", "A1", "Plural gols (en Portugal golos)."),
    ("goleiro", "m", "", "arquero", "A2", ""),
    ("bola", "f", "", "pelota", "A1", ""),
    ("campo", "m", "", "cancha / campo", "A2", ""),
    ("quadra", "f", "", "cancha (de tenis, de básquet)", "B1", "Também la cuadra de una escola de samba."),
    ("campeonato", "m", "", "campeonato", "A2", ""),
    ("campeão", "m", "campeões", "campeón", "A2", "Plural campeões; femenino campeã."),
    ("vitória", "f", "", "victoria", "B1", ""),
    ("derrota", "f", "", "derrota", "B1", ""),
    ("empate", "m", "", "empate", "B1", ""),
    ("placar", "m", "", "marcador / resultado", "B1", ""),
    ("pênalti", "m", "", "penal", "B1", ""),
    ("falta", "f", "", "falta / infracción", "B1", ""),
    ("clássico", "m", "", "clásico", "B1", "O Fla-Flu: el clásico carioca."),
    ("natação", "f", "natações", "natación", "A2", ""),
    ("piscina", "f", "", "pileta / piscina", "A2", ""),
    ("corrida", "f", "", "carrera / correr", "A2", ""),
    ("surfe", "m", "", "surf", "A2", "Pegar onda = surfear."),
    ("prancha", "f", "", "tabla (de surf)", "B1", ""),
    ("vôlei", "m", "", "vóley", "A2", "Vôlei de praia; futevôlei en Ipanema."),
    ("futevôlei", "m", "", "futvóley", "B1", ""),
    ("frescobol", "m", "", "paleta de playa", "B1", "Plural frescobóis. Inventado en las playas de Río."),
    ("basquete", "m", "", "básquet", "A2", ""),
    ("tênis de mesa", "m", "tênis de mesa", "ping-pong", "B1", ""),
    ("capoeira", "f", "", "capoeira", "A2", ""),
    ("academia", "f", "", "gimnasio", "A2", "Falso amigo y acento distinto: a-ca-de-MI-a = gimnasio."),
    ("ginástica", "f", "", "gimnasia", "B1", ""),
    ("musculação", "f", "musculações", "musculación / pesas", "B1", ""),
    ("treino", "m", "", "entrenamiento", "B1", ""),
    ("treinador", "m", "", "entrenador", "B1", ""),
    ("atleta", "m", "", "atleta", "B1", ""),
    ("medalha", "f", "", "medalla", "B1", ""),
    ("prêmio", "m", "", "premio", "B1", ""),
    ("taça", "f", "", "copa / trofeo", "B1", "A Taça Libertadores."),
    ("copa", "f", "", "copa (torneo) / mundial", "A2", "A Copa do Mundo. Falso amigo: la copa de vino es a taça."),
    ("olimpíada", "f", "", "olimpíada", "B2", ""),
    ("bicicleta ergométrica", "f", "bicicletas ergométricas", "bicicleta fija", "B2", ""),
    ("skate", "m", "", "skate / patineta", "B1", ""),
    ("patins", "m", "patins", "patines", "B1", "Invariable: os patins."),
    ("luta", "f", "", "lucha / pelea", "B1", ""),
    ("jiu-jítsu", "m", "jiu-jítsu", "jiu-jitsu", "B2", ""),
    ("remo", "m", "", "remo", "B2", ""),
    ("vela", "f", "", "vela (deporte y de cera)", "B2", ""),
    ("pesca", "f", "", "pesca", "B1", ""),
    ("caminhada", "f", "", "caminata", "A2", ""),
    ("estádio", "m", "", "estadio", "A2", ""),
    ("arquibancada", "f", "", "tribuna / grada", "B2", ""),
    ("uniforme", "m", "", "uniforme", "B1", ""),
    ("camisa dez", "f", "camisas dez", "diez (el mejor del equipo)", "C1", ""),
    ("pelada", "f", "", "picado (partido informal)", "B2", "Falso amigo: pelada = picado de fútbol; pelado es desnudo."),
    ("drible", "m", "", "gambeta", "B2", ""),
    ("chute", "m", "", "remate / patada", "B1", "Chute = patada, remate; chutar = patear."),
    ("xadrez", "m", "", "ajedrez / cuadrillé", "B1", "Camisa xadrez = camisa a cuadros."),
    ("baralho", "m", "", "mazo de cartas", "B2", ""),
    ("hobby", "m", "", "hobby / pasatiempo", "A2", ""),
    ("lazer", "m", "", "ocio / tiempo libre", "B1", ""),
    ("brincadeira", "f", "", "juego (de niños) / broma", "A2", "Brincar = jugar (niños) y bromear; é brincadeira! = ¡es joda!"),
    ("brinquedo", "m", "", "juguete", "A2", ""),
]

# --------------------------------------------------------------------- scuola
_RAW["scuola"] = [
    ("aula", "f", "", "clase (lección)", "A1", "Falso amigo: aula = clase; el aula es a sala de aula."),
    ("sala de aula", "f", "salas de aula", "aula / salón de clase", "A2", ""),
    ("aluno", "m", "", "alumno", "A1", ""),
    ("aluna", "f", "", "alumna", "A1", ""),
    ("estudante", "m", "", "estudiante", "A1", ""),
    ("turma", "f", "", "grupo / curso (los alumnos) / barra de amigos", "A2", "A minha turma = mi curso, mi grupo de amigos."),
    ("curso", "m", "", "curso / carrera", "A2", "Curso de Direito = la carrera de Derecho."),
    ("faculdade", "f", "", "facultad / universidad", "A2", "Fazer faculdade = ir a la universidad."),
    ("matéria", "f", "", "materia / asignatura / nota periodística", "A2", ""),
    ("disciplina", "f", "", "materia / disciplina", "B1", ""),
    ("prova", "f", "", "examen / prueba", "A2", ""),
    ("nota", "f", "", "nota / billete", "A2", "Nota de cem reais = billete de cien."),
    ("dever de casa", "m", "deveres de casa", "deberes / tarea", "A2", ""),
    ("caderno", "m", "", "cuaderno", "A1", ""),
    ("livro", "m", "", "libro", "A1", ""),
    ("caneta", "f", "", "birome / lapicera", "A1", ""),
    ("lápis", "m", "lápis", "lápiz", "A1", "Invariable: os lápis."),
    ("borracha", "f", "", "goma de borrar", "A2", "Falso amigo: borracha = goma; borracho es bêbado."),
    ("régua", "f", "", "regla", "B1", ""),
    ("tesoura", "f", "", "tijera", "B1", ""),
    ("cola", "f", "", "pegamento / machete (en un examen)", "B1", "Falso amigo: cola = pegamento; la cola (fila) es a fila."),
    ("folha", "f", "", "hoja", "A2", ""),
    ("papel", "m", "", "papel", "A1", "Plural papéis."),
    ("quadro", "m", "", "pizarrón / cuadro", "A2", ""),
    ("giz", "m", "", "tiza", "B1", "Plural gizes."),
    ("mochila", "f", "", "mochila", "A1", ""),
    ("dicionário", "m", "", "diccionario", "A2", ""),
    ("palavra", "f", "", "palabra", "A1", ""),
    ("frase", "f", "", "oración / frase", "A1", ""),
    ("texto", "m", "", "texto", "A1", ""),
    ("exercício", "m", "", "ejercicio", "A1", ""),
    ("pergunta", "f", "", "pregunta", "A1", ""),
    ("resposta", "f", "", "respuesta", "A1", ""),
    ("dúvida", "f", "", "duda", "A2", ""),
    ("exemplo", "m", "", "ejemplo", "A1", ""),
    ("erro de português", "m", "erros de português", "error de ortografía o gramática", "B1", ""),
    ("gramática", "f", "", "gramática", "A2", ""),
    ("vocabulário", "m", "", "vocabulario", "A2", ""),
    ("pronúncia", "f", "", "pronunciación", "A2", ""),
    ("sotaque", "m", "", "acento (forma de hablar)", "A2", "Sotaque carioca: la s suena «sh»."),
    ("acento", "m", "", "tilde / acento gráfico", "A2", "Acento agudo (´), circunflexo (^), til (~)."),
    ("idioma", "m", "", "idioma", "A1", ""),
    ("tradução", "f", "traduções", "traducción", "B1", ""),
    ("leitura", "f", "", "lectura", "A2", ""),
    ("redação", "f", "redações", "redacción / composición", "B1", "A redação del ENEM."),
    ("vestibular", "m", "", "examen de ingreso a la universidad", "B1", "Plural vestibulares. Hoy el ENEM."),
    ("diploma", "m", "", "diploma / título", "B1", ""),
    ("formatura", "f", "", "graduación / recibida", "B1", ""),
    ("bolsa de estudos", "f", "bolsas de estudos", "beca", "B1", ""),
    ("mestrado", "m", "", "maestría", "B2", ""),
    ("doutorado", "m", "", "doctorado", "B2", ""),
    ("tese", "f", "", "tesis", "B2", "Plural teses."),
    ("pesquisador", "m", "", "investigador", "B2", ""),
    ("reitor", "m", "", "rector", "C1", ""),
    ("escola pública", "f", "escolas públicas", "escuela pública", "B1", ""),
    ("creche", "f", "", "guardería / jardín maternal", "B1", ""),
    ("ensino", "m", "", "enseñanza", "B1", "Ensino fundamental, ensino médio."),
    ("ensino médio", "m", "", "secundaria", "B1", ""),
    ("educação", "f", "educações", "educación", "A2", ""),
    ("conhecimento", "m", "", "conocimiento", "B1", ""),
    ("aprendizagem", "f", "", "aprendizaje", "B2", "Género distinto: el aprendizaje → a aprendizagem."),
    ("matemática", "f", "", "matemática", "A2", ""),
    ("história", "f", "", "historia", "A2", "Também cuento, relato."),
    ("geografia", "f", "", "geografía", "A2", ""),
    ("física", "f", "", "física", "B1", ""),
    ("química", "f", "", "química", "B1", ""),
    ("biologia", "f", "", "biología", "B1", ""),
    ("filosofia", "f", "", "filosofía", "B1", ""),
    ("direito", "m", "", "derecho", "B1", "Direito = derecho (la carrera y el lado): à direita."),
    ("medicina", "f", "", "medicina", "B1", ""),
    ("recreio", "m", "", "recreo", "B1", ""),
    ("uniforme escolar", "m", "uniformes escolares", "guardapolvo / uniforme escolar", "B2", ""),
    ("merenda", "f", "", "merienda escolar", "B1", ""),
    ("colégio", "m", "", "colegio", "A2", ""),
    ("inscrição", "f", "inscrições", "inscripción", "B1", ""),
    ("matrícula", "f", "", "matrícula / inscripción", "B1", ""),
    ("apostila", "f", "", "apunte / cuadernillo", "B2", ""),
    ("resumo", "m", "", "resumen", "B1", ""),
    ("palestra", "f", "", "charla / conferencia", "B1", "Falso amigo: palestra = conferencia; la palestra (deportiva) no se usa."),
    ("seminário", "m", "", "seminario", "B2", ""),
    ("argumento", "m", "", "argumento", "B1", ""),
]
