# -*- coding: utf-8 -*-
"""Datos de transferencia español → italiano para el motor de diagnóstico de errores.

Pensado para un hablante de español rioplatense que aprende italiano.

- ES_IT:    forma española (minúsculas, sin tildes; la ñ se conserva) → (italiano, nota)
- FALSI:    palabra ITALIANA que parece española → (qué significa en español,
            qué quería decir probablemente el alumno en italiano, nota)
- SPELLING: correspondencias ortográficas (patrón_es, patrón_it, explicación)

Las notas están en español rioplatense (voseo) y tienen como máximo 120 caracteres.
Las claves de varias palabras («me gusta», «hay que»…) representan estructuras.
"""

ES_IT = {}

# ---------------------------------------------------------------------------
# Artículos, contracciones y preposiciones
# ---------------------------------------------------------------------------
ES_IT.update({
    "el": ("il / lo / l' — lui", "Artículo: il (lo ante s+consonante, z, gn; l' ante vocal). «Él» pronombre = lui."),
    "la": ("la / l'", "Igual que en español, pero ante vocal se apostrofa: l'amica."),
    "los": ("i / gli", "Los = i; ante vocal, s+consonante o z: gli (gli amici, gli studenti)."),
    "las": ("le", "Las = le: le ragazze, le case."),
    "lo": ("lo / il", "Pronombre: lo (lo vedo). «Lo bueno» = il bello, il buono."),
    "un": ("un / uno", "Un; ante s+consonante o z: uno (uno studente, uno zaino)."),
    "una": ("una / un'", "Ante vocal lleva apóstrofo: un'amica."),
    "unos": ("dei / degli / alcuni", "Unos = dei (degli ante vocal o s+consonante) o alcuni."),
    "unas": ("delle / alcune", "Unas = delle o alcune: delle amiche."),
    "al": ("al / allo / all'", "a + il = al; a + lo = allo; a + l' = all'."),
    "del": ("del / dello / dell'", "di + il = del; di + lo = dello; di + l' = dell'."),
    "a": ("a / ad", "Igual, pero ante vocal (sobre todo a-) suele ser ad: ad Anna."),
    "de": ("di / da", "De = di (posesión, material); procedencia = da: vengo da Roma."),
    "en": ("in / a", "En = in (in Italia, in cucina); con ciudades, a: a Roma. «En casa» = a casa."),
    "con": ("con", "Igual. Contracciones posibles: col, coi (con il, con i)."),
    "por": ("per / da", "Por = per; el agente de la pasiva es da: scritto da Dante."),
    "para": ("per", "Para = per: per te, per studiare."),
    "sin": ("senza", ""),
    "sobre": ("su / sopra / busta", "Sobre = su (sul tavolo) o sopra. El sobre (de carta) es la busta."),
    "entre": ("tra / fra", "Tra y fra son sinónimos: tra amici, fra un'ora."),
    "hasta": ("fino a / finché", "Hasta = fino a. «¡Hasta luego!» = a dopo / a più tardi."),
    "desde": ("da", "Desde = da: da Roma, dal 2020. Estudio desde hace dos años = studio da due anni."),
    "hacia": ("verso / facevo, faceva", "Hacia = verso; hacía (hacer) = facevo / faceva. Hace años = anni fa."),
    "contra": ("contro", ""),
    "segun": ("secondo", "Según = secondo: secondo me."),
    "bajo": ("sotto / basso", "Bajo (preposición) = sotto; bajo (de altura) = basso."),
    "tras": ("dopo / dietro", ""),
    "ante": ("davanti a / di fronte a", ""),
    "excepto": ("tranne / eccetto", ""),
    "incluso": ("persino / perfino / incluso", "Incluso (hasta, aun) = persino o perfino."),
    "junto": ("accanto / insieme", "Junto a = accanto a; juntos = insieme."),
    "juntos": ("insieme", ""),
    "cerca": ("vicino", "Cerca de = vicino a. Ojo: «cerca» en italiano es «busca» (cercare)."),
    "lejos": ("lontano", ""),
    "encima": ("sopra", ""),
    "debajo": ("sotto", ""),
    "delante": ("davanti", ""),
    "detras": ("dietro", ""),
    "adentro": ("dentro", ""),
    "afuera": ("fuori", ""),
    "fuera": ("fuori", ""),
    "arriba": ("su / sopra", "Arriba = su (vado su) o di sopra."),
    "abajo": ("giù / sotto", "Abajo = giù (vado giù) o di sotto."),
    "alrededor": ("intorno", ""),
    "enfrente": ("di fronte", ""),
    "adelante": ("avanti", "¡Adelante! = avanti!"),
    "atras": ("indietro / dietro", "Ir para atrás = andare indietro; detrás de = dietro."),
})

# ---------------------------------------------------------------------------
# Pronombres, posesivos, demostrativos, indefinidos
# ---------------------------------------------------------------------------
ES_IT.update({
    "yo": ("io", ""),
    "tu": ("tu / il tuo", "Tú = tu (sujeto). Tu (posesivo) = il tuo / la tua, con artículo."),
    "vos": ("tu", "El voseo no existe: vos = tu, y el verbo va en 2ª persona: tu sei, tu hai."),
    "usted": ("Lei", "Usted = Lei, con el verbo en 3ª persona: Lei è, Lei ha."),
    "ustedes": ("voi", "Ustedes = voi, con verbo en 2ª plural: voi siete, voi avete."),
    "ella": ("lei", ""),
    "ello": ("ciò / esso", ""),
    "nosotros": ("noi", ""),
    "nosotras": ("noi", ""),
    "vosotros": ("voi", ""),
    "vosotras": ("voi", ""),
    "ellos": ("loro", ""),
    "ellas": ("loro", ""),
    "me": ("mi", "Me = mi (mi chiamo). «Me» italiano es la forma tónica: a me, per me."),
    "te": ("ti / tè", "Te = ti (ti amo). «Te» italiano es tónico: per te. El té (bebida) = il tè."),
    "se": ("si / so", "Se (pronombre) = si: si chiama. Sé (saber) = so. Ojo: «se» italiano = si condicional."),
    "nos": ("ci", "Nos = ci: ci vediamo."),
    "os": ("vi", ""),
    "le": ("gli / le / Le", "Le (a él) = gli; (a ella) = le; (a usted) = Le."),
    "les": ("gli / loro", "Les = gli (coloquial) o loro después del verbo: do loro."),
    "mi": ("il mio / la mia", "Mi (posesivo) = il mio / la mia, con artículo. «Mi» italiano = me (pronombre)."),
    "mis": ("i miei / le mie", ""),
    "tus": ("i tuoi / le tue", ""),
    "su": ("il suo / la sua / il loro", "Su = il suo / la sua o il loro (de ellos). Ojo: «su» italiano = sobre."),
    "sus": ("i suoi / le sue / i loro", ""),
    "nuestro": ("nostro", "Con artículo: il nostro."),
    "nuestra": ("nostra", ""),
    "nuestros": ("nostri", ""),
    "nuestras": ("nostre", ""),
    "vuestro": ("vostro", ""),
    "vuestra": ("vostra", ""),
    "tuyo": ("tuo", ""),
    "tuya": ("tua", ""),
    "suyo": ("suo", ""),
    "suya": ("sua", ""),
    "conmigo": ("con me", ""),
    "contigo": ("con te", ""),
    "consigo": ("con sé", ""),
    "este": ("questo", ""),
    "esta": ("è / sta / questa", "Está = è o sta (sta bene); esta (demostrativo) = questa."),
    "estos": ("questi", ""),
    "estas": ("sei / stai / queste", "Estás = sei o stai (come stai?); estas (demostrativo) = queste."),
    "esto": ("questo / ciò", ""),
    "ese": ("quello", "Ese y aquel se dicen igual: quello."),
    "esa": ("quella", ""),
    "esos": ("quei / quegli", ""),
    "esas": ("quelle", ""),
    "eso": ("ciò / quello", "Eso = ciò o quello. «¡Eso!» = proprio così!"),
    "aquel": ("quel / quello", ""),
    "aquella": ("quella", ""),
    "aquello": ("quello / ciò", ""),
    "aquellos": ("quei / quegli", ""),
    "aquellas": ("quelle", ""),
    "algun": ("qualche", "Qualche va con singular: qualche giorno (algunos días)."),
    "alguno": ("qualcuno / alcuno", ""),
    "alguna": ("qualche / alcuna", ""),
    "algunos": ("alcuni / qualche", "Algunos días = alcuni giorni o qualche giorno (¡singular!)."),
    "algunas": ("alcune / qualche", ""),
    "ningun": ("nessun", ""),
    "ninguno": ("nessuno", ""),
    "ninguna": ("nessuna", ""),
    "otro": ("altro", "Otro = altro: un altro caffè."),
    "otra": ("altra", ""),
    "otros": ("altri", ""),
    "otras": ("altre", ""),
    "mismo": ("stesso", "El mismo = lo stesso. «Yo mismo» = io stesso."),
    "misma": ("stessa", ""),
    "cada": ("ogni", "Cada = ogni (invariable): ogni giorno."),
    "algo": ("qualcosa", ""),
    "nada": ("niente / nulla", "Nada = niente, con doble negación: non ho niente."),
    "todo": ("tutto", "Todo el día = tutto il giorno."),
    "toda": ("tutta", ""),
    "todos": ("tutti", ""),
    "todas": ("tutte", ""),
    "nadie": ("nessuno", "Nadie = nessuno: non c'è nessuno."),
    "alguien": ("qualcuno", ""),
})

# ---------------------------------------------------------------------------
# Interrogativos y conjunciones
# ---------------------------------------------------------------------------
ES_IT.update({
    "que": ("che / cosa", "Qué = che, cosa o che cosa; que (conjunción/relativo) = che."),
    "quien": ("chi", "Quién = chi. Relativo «quien» = che / il quale."),
    "quienes": ("chi", ""),
    "cual": ("quale", "Cuál = quale; ante es: qual è (¡sin apóstrofo!)."),
    "cuales": ("quali", ""),
    "cuanto": ("quanto", ""),
    "cuanta": ("quanta", ""),
    "cuantos": ("quanti", ""),
    "cuantas": ("quante", ""),
    "donde": ("dove", "Dónde = dove. ¿De dónde sos? = di dove sei?"),
    "adonde": ("dove", ""),
    "cuando": ("quando", ""),
    "como": ("come / mangio", "Cómo/como = come. «Como» (de comer) = mangio."),
    "por que": ("perché", "¿Por qué? = perché? Y la respuesta también: perché."),
    "porque": ("perché", "Porque y por qué se dicen igual: perché (con tilde aguda)."),
    "y": ("e / ed", "Y = e; ante vocal (sobre todo e-) a veces ed: ed ecco."),
    "o": ("o / oppure", "O = o u oppure."),
    "u": ("o", ""),
    "ni": ("né", "Ni… ni = né… né (con tilde)."),
    "pero": ("ma / però", "«Pero» en italiano es ma (o però, con tilde)."),
    "sino": ("ma / bensì", "No A sino B = non A ma B (más formal: bensì)."),
    "aunque": ("anche se / sebbene", "Aunque = anche se (+ indicativo) o sebbene (+ congiuntivo)."),
    "si": ("se / sì", "Si condicional = se; sí afirmativo = sì (con tilde)."),
    "mientras": ("mentre", ""),
    "pues": ("dunque / allora", ""),
    "entonces": ("allora / quindi", ""),
    "ademas": ("inoltre / in più", ""),
    "sin embargo": ("tuttavia / però", ""),
    "o sea": ("cioè", ""),
    "es decir": ("cioè", ""),
    "por eso": ("per questo", ""),
    "asi que": ("quindi / così", ""),
    "ya que": ("visto che / dato che", ""),
})

# ---------------------------------------------------------------------------
# Adverbios frecuentes
# ---------------------------------------------------------------------------
ES_IT.update({
    "muy": ("molto", "Muy y mucho son lo mismo en italiano: molto."),
    "mucho": ("molto", "Mucho = molto; como adjetivo concuerda: molta gente, molti amici."),
    "mucha": ("molta", ""),
    "muchos": ("molti", ""),
    "muchas": ("molte", ""),
    "pocos": ("pochi", ""),
    "pocas": ("poche", ""),
    "mas": ("più / ma", "Más = più (con tilde). Mas (conjunción, «pero») = ma."),
    "menos": ("meno", ""),
    "demasiado": ("troppo", ""),
    "bastante": ("abbastanza / parecchio", "Bastante (suficiente) = abbastanza; (mucho) = parecchio."),
    "tan": ("così / tanto", "Tan grande = così grande. Tan… como = tanto… quanto."),
    "tambien": ("anche", "También = anche; va antes de lo que modifica: anche io."),
    "tampoco": ("neanche / nemmeno", "Yo tampoco = neanch'io / nemmeno io."),
    "siempre": ("sempre", ""),
    "nunca": ("mai / non… mai", "Nunca = mai, con doble negación: non vado mai."),
    "jamas": ("mai", ""),
    "ya": ("già / ormai", "Ya = già. «Ya no» = non… più. «¡Ya voy!» = arrivo!"),
    "todavia": ("ancora", "Todavía = ancora. «Todavía no» = non ancora."),
    "aun": ("ancora / anche", "Aún (todavía) = ancora; aun (incluso) = anche, persino."),
    "ahora": ("ora / adesso", ""),
    "despues": ("dopo / poi", "Después = dopo o poi. Después de = dopo (+ inf. pasado: dopo aver mangiato)."),
    "antes": ("prima", "Antes = prima. Antes de = prima di."),
    "luego": ("poi / dopo", "Luego = poi. «Hasta luego» = a dopo."),
    "hoy": ("oggi", ""),
    "ayer": ("ieri", ""),
    "mañana": ("domani / mattina", "Mañana (día) = domani; la mañana = la mattina."),
    "manana": ("domani / mattina", "Mañana (día) = domani; la mañana = la mattina."),
    "anoche": ("ieri sera", ""),
    "anteayer": ("l'altro ieri", ""),
    "pasado mañana": ("dopodomani", ""),
    "aqui": ("qui / qua", ""),
    "aca": ("qua / qui", ""),
    "ahi": ("lì / là", ""),
    "alli": ("lì", ""),
    "alla": ("là", "Allá = là. Ojo: «alla» italiano = a la (alla stazione)."),
    "bien": ("bene", "Bien = bene; bueno = buono. Estoy bien = sto bene."),
    "mal": ("male", "Mal = male; malo = cattivo."),
    "asi": ("così", ""),
    "casi": ("quasi", "Casi = quasi. Ojo: «casi» en italiano = casos."),
    "quizas": ("forse", ""),
    "quiza": ("forse", ""),
    "tal vez": ("forse", ""),
    "a lo mejor": ("forse", ""),
    "acaso": ("forse / per caso", ""),
    "claro": ("certo / chiaro", "«¡Claro!» = certo! Claro (evidente, luminoso) = chiaro."),
    "obvio": ("ovvio", ""),
    "no": ("no / non", "Delante del verbo va non: non parlo. Como respuesta: no."),
    "tarde": ("tardi / pomeriggio", "Tarde (adverbio) = tardi; la tarde = il pomeriggio (o la sera)."),
    "temprano": ("presto", "Temprano = presto: mi alzo presto."),
    "pronto": ("presto / tra poco", "Pronto = presto. Ojo: «pronto» italiano = listo, o ¿hola? al teléfono."),
    "enseguida": ("subito", ""),
    "despacio": ("piano / lentamente", "Despacio = piano: parla piano."),
    "apenas": ("appena", "Apenas = appena."),
    "recien": ("appena", "Recién llegué = sono appena arrivato."),
    "mejor": ("meglio / migliore", "Mejor (adverbio) = meglio; el mejor (adjetivo) = il migliore."),
    "peor": ("peggio / peggiore", "Peor (adverbio) = peggio; el peor = il peggiore."),
    "mayor": ("maggiore / più grande", "Mi hermano mayor = mio fratello maggiore (o più grande)."),
    "menor": ("minore / più piccolo", ""),
    "medio": ("mezzo / medio", "Medio kilo = mezzo chilo."),
    "media": ("mezza / calza", "Las tres y media = le tre e mezza. La media (prenda) = la calza."),
    "vez": ("volta", "Una vez = una volta; a veces = a volte."),
    "veces": ("volte", ""),
    "a veces": ("a volte", ""),
    "de vez en cuando": ("ogni tanto", ""),
    "otra vez": ("di nuovo / ancora", ""),
    "de nuevo": ("di nuovo", ""),
    "a menudo": ("spesso", ""),
    "seguido": ("spesso", "Seguido (a menudo) = spesso."),
    "sobre todo": ("soprattutto", ""),
    "hace poco": ("poco fa", "Hace poco = poco fa (fa va después)."),
    "por ejemplo": ("per esempio", ""),
    "por supuesto": ("certo / naturalmente", ""),
    "de acuerdo": ("d'accordo", ""),
    "nomas": ("pure / soltanto", "Pasá nomás = entra pure."),
    "esta noche": ("stasera / stanotte", "Esta noche (salida) = stasera; (de madrugada) = stanotte."),
    "esta mañana": ("stamattina", ""),
    "esta tarde": ("oggi pomeriggio", ""),
    "ahora mismo": ("subito / proprio adesso", ""),
    "ojala": ("magari / speriamo", "¡Ojalá! = magari! o speriamo."),
    "cuidado": ("attenzione", "¡Cuidado! = attenzione! o attento!"),
})

# ---------------------------------------------------------------------------
# Saludos y fórmulas
# ---------------------------------------------------------------------------
ES_IT.update({
    "hola": ("ciao / salve", "Hola = ciao (informal) o salve (neutro)."),
    "chau": ("ciao", "Chau viene justamente del italiano ciao, que sirve para saludar y despedirse."),
    "adios": ("arrivederci / addio", "Addio es despedida definitiva; lo normal es arrivederci o ciao."),
    "buenos dias": ("buongiorno", ""),
    "buenas tardes": ("buon pomeriggio / buonasera", "Desde media tarde ya se dice buonasera."),
    "buenas noches": ("buonasera / buonanotte", "Buonanotte solo al irse a dormir; al llegar de noche: buonasera."),
    "gracias": ("grazie", ""),
    "muchas gracias": ("grazie mille", ""),
    "de nada": ("prego / di niente", "De nada = prego (o di niente)."),
    "por favor": ("per favore / per piacere", ""),
    "perdon": ("scusa / scusi", "Perdón = scusa (a vos) / scusi (a usted). Pedir perdón = chiedere scusa."),
    "disculpe": ("scusi", ""),
    "disculpa": ("scusa", ""),
    "permiso": ("permesso", "Con permiso = permesso."),
    "bienvenido": ("benvenuto", ""),
    "felicidades": ("auguri / congratulazioni", "¡Felicidades! = auguri! Por un logro: congratulazioni!"),
    "salud": ("salute / cin cin", "¡Salud! (brindis) = cin cin! o salute! Estornudo: salute!"),
    "dale": ("dai / va bene", "«¡Dale!» = dai! (ánimo) o va bene (acuerdo)."),
    "bueno": ("buono / beh, va bene", "Bueno (adjetivo) = buono; «bueno…» (muletilla) = beh o va bene."),
    "buena": ("buona", ""),
    "buenos": ("buoni", ""),
    "buenas": ("buone", ""),
    "mucho gusto": ("piacere", "Mucho gusto = piacere (di conoscerti)."),
    "encantado": ("piacere / incantato", "Al presentarse: piacere. «Incantato» es embelesado."),
    "que tal": ("come va", "¿Qué tal? = come va?"),
    "como estas": ("come stai", ""),
    "como te llamas": ("come ti chiami", ""),
    "de donde sos": ("di dove sei", ""),
    "cuanto cuesta": ("quanto costa", ""),
    "que hora es": ("che ore sono", "Se pregunta en plural (che ore sono?) o en singular (che ora è?): sono le tre / è l'una."),
})

# ---------------------------------------------------------------------------
# Estructuras que cambian
# ---------------------------------------------------------------------------
ES_IT.update({
    "me gusta": ("mi piace", "Me gusta = mi piace; me gustan = mi piacciono. Mismo esquema que en español."),
    "me gustan": ("mi piacciono", ""),
    "te gusta": ("ti piace", ""),
    "le gusta": ("gli piace / le piace", ""),
    "gusta": ("piace", ""),
    "gustan": ("piacciono", ""),
    "gustar": ("piacere", "Gustar = piacere (mi piace). Mucho gusto = piacere."),
    "encanta": ("piace tantissimo / adoro", "Me encanta = mi piace tantissimo o lo adoro."),
    "tengo que": ("devo", "Tengo que = devo + infinitivo: devo andare."),
    "tenes que": ("devi", "Tenés que = devi + infinitivo."),
    "tiene que": ("deve", ""),
    "tener que": ("dovere", "Tener que = dovere + infinitivo."),
    "hay que": ("bisogna / si deve", "Hay que = bisogna o si deve + infinitivo."),
    "hay": ("c'è / ci sono", "Hay = c'è (singular) / ci sono (plural)."),
    "hace falta": ("serve / bisogna", "Me hace falta = mi serve o ho bisogno di."),
    "hace calor": ("fa caldo", "Hace calor = fa caldo. Ojo: caldo = calor, no sopa."),
    "hace frio": ("fa freddo", ""),
    "acabo de": ("ho appena", "Acabo de comer = ho appena mangiato."),
    "acabar de": ("avere / essere appena", "Acabar de + inf. = passato prossimo + appena: è appena uscito."),
    "volver a": ("ri- / di nuovo", "Volver a hacer = rifare o fare di nuovo."),
    "quedarse": ("rimanere / restare", "Quedarse = rimanere o restare (con essere: sono rimasto)."),
    "quedar": ("restare / stare / vedersi", "Quedar (sobrar) = restare; quedar bien = stare bene; quedar con = vedersi."),
    "me quedo": ("rimango / resto", ""),
    "tengo hambre": ("ho fame", "Tener hambre, sed, frío = avere fame, sete, freddo."),
    "tengo frio": ("ho freddo", ""),
    "tengo sed": ("ho sete", ""),
    "tengo sueño": ("ho sonno", ""),
    "tengo miedo": ("ho paura", ""),
    "tener ganas": ("avere voglia", "Tengo ganas de = ho voglia di."),
    "cuantos años tenes": ("quanti anni hai", ""),
    "ir a": ("futuro / presente", "Voy a comer = mangerò, o en presente: mangio tra poco. Sto per mangiare = estoy por comer (a punto de)."),
    "darse cuenta": ("accorgersi / rendersi conto", "Me di cuenta = mi sono accorto / me ne sono reso conto."),
    "echar de menos": ("sentire la mancanza", "Te echo de menos = mi manchi."),
    "extrañar": ("sentire la mancanza / mancare", "Te extraño = mi manchi (estructura al revés, como gustar)."),
    "te extraño": ("mi manchi", ""),
    "te quiero": ("ti voglio bene", "Te quiero = ti voglio bene; ti amo es más fuerte (de pareja)."),
    "me duele": ("mi fa male", "Me duele la cabeza = mi fa male la testa / ho mal di testa."),
    "necesito": ("ho bisogno di / mi serve", ""),
})

# ---------------------------------------------------------------------------
# Presente de los verbos más frecuentes (incluye voseo)
# ---------------------------------------------------------------------------
ES_IT.update({
    # ser
    "ser": ("essere", "Ser y estar muchas veces son essere; estar también puede ser stare."),
    "soy": ("sono", ""),
    "sos": ("sei", "Vos sos = tu sei."),
    "eres": ("sei", ""),
    "es": ("è", "Es = è (con tilde); sin tilde, «e» significa «y»."),
    "somos": ("siamo", ""),
    "sois": ("siete", ""),
    "son": ("sono", "Son = sono (igual que «soy»: io sono / loro sono)."),
    # estar
    "estar": ("stare / essere", "Estar = stare (sto bene, sto mangiando) o essere (è a casa)."),
    "estoy": ("sto / sono", "Estoy bien = sto bene; estoy en casa = sono a casa."),
    "estamos": ("stiamo / siamo", ""),
    "estais": ("state / siete", ""),
    "estan": ("stanno / sono", ""),
    # tener
    "tener": ("avere", "Tener = avere: ho, hai, ha, abbiamo, avete, hanno."),
    "tengo": ("ho", "Tener = avere: ho, hai, ha… (la h no se pronuncia)."),
    "tenes": ("hai", "Vos tenés = tu hai."),
    "tienes": ("hai", ""),
    "tiene": ("ha", ""),
    "tenemos": ("abbiamo", ""),
    "teneis": ("avete", ""),
    "tienen": ("hanno", ""),
    # haber
    "haber": ("avere / esserci", "Auxiliar haber = avere (o essere con muchos verbos de movimiento o cambio de estado, y con los reflexivos). Hay = c'è."),
    "he": ("ho", "He comido = ho mangiato; con movimiento: sono andato."),
    "has": ("hai", ""),
    "ha": ("ha / è", "Ha comido = ha mangiato; pero ha ido = è andato."),
    "hemos": ("abbiamo", ""),
    "habeis": ("avete", ""),
    "han": ("hanno", ""),
    # ir
    "ir": ("andare", ""),
    "voy": ("vado", ""),
    "vas": ("vai", ""),
    "va": ("va", "Igual: va."),
    "vamos": ("andiamo", "¡Vamos! = andiamo! o dai!"),
    "vais": ("andate", ""),
    "van": ("vanno", ""),
    # hacer
    "hacer": ("fare", "Hacer = fare (la h española viene de la f latina)."),
    "hago": ("faccio", ""),
    "haces": ("fai", ""),
    "hace": ("fa", "Hace = fa. «Hace dos años» = due anni fa (fa va después)."),
    "hacemos": ("facciamo", ""),
    "haceis": ("fate", ""),
    "hacen": ("fanno", ""),
    # poder
    "poder": ("potere", ""),
    "puedo": ("posso", ""),
    "podes": ("puoi", "Vos podés = tu puoi."),
    "puedes": ("puoi", ""),
    "puede": ("può", "Puede = può (con tilde). «Puede ser» = può darsi."),
    "podemos": ("possiamo", ""),
    "podeis": ("potete", ""),
    "pueden": ("possono", ""),
    # querer
    "querer": ("volere / voler bene", "Querer algo = volere; querer a alguien = voler bene (amare es más fuerte)."),
    "quiero": ("voglio", "Quiero = voglio; más cortés: vorrei."),
    "queres": ("vuoi", "Vos querés = tu vuoi."),
    "quieres": ("vuoi", ""),
    "quiere": ("vuole", ""),
    "queremos": ("vogliamo", ""),
    "quereis": ("volete", ""),
    "quieren": ("vogliono", ""),
    # deber
    "deber": ("dovere", ""),
    "debo": ("devo", ""),
    "debes": ("devi", ""),
    "debe": ("deve", ""),
    "debemos": ("dobbiamo", ""),
    "debeis": ("dovete", ""),
    "deben": ("devono", ""),
    # saber
    "saber": ("sapere", "Saber = sapere; conocer a alguien = conoscere."),
    "sabes": ("sai", ""),
    "sabe": ("sa", ""),
    "sabemos": ("sappiamo", ""),
    "sabeis": ("sapete", ""),
    "saben": ("sanno", ""),
    # decir
    "decir": ("dire", ""),
    "digo": ("dico", ""),
    "decis": ("dici / dite", "Vos decís = tu dici; vosotros decís = voi dite."),
    "dices": ("dici", ""),
    "dice": ("dice", "Igual: dice."),
    "decimos": ("diciamo", ""),
    "dicen": ("dicono", ""),
    # venir
    "venir": ("venire", ""),
    "vengo": ("vengo", "Igual: vengo."),
    "venis": ("vieni / venite", "Vos venís = tu vieni; vosotros venís = voi venite."),
    "vienes": ("vieni", ""),
    "viene": ("viene", "Igual: viene."),
    "venimos": ("veniamo", ""),
    "vienen": ("vengono", ""),
    # dar
    "dar": ("dare", ""),
    "doy": ("do", ""),
    "das": ("dai", "Das = dai. «¡Dai!» también es ¡dale!, ¡vamos!"),
    "da": ("dà", "Da (dar) = dà, con tilde; «da» sin tilde es la preposición (desde, de)."),
    "damos": ("diamo", ""),
    "dais": ("date", ""),
    "dan": ("danno", "Dan = danno (ojo: el daño también se dice danno)."),
    # ver
    "ver": ("vedere", ""),
    "veo": ("vedo", ""),
    "ves": ("vedi", ""),
    "ve": ("vede / va'", "Ve (ver) = vede; ¡ve! (ir) = va'!"),
    "vemos": ("vediamo", "Nos vemos = ci vediamo."),
    "veis": ("vedete", ""),
    "ven": ("vedono / vieni", "Ven (ver) = vedono; ¡ven! (venir) = vieni!"),
    # salir
    "salir": ("uscire", "Salir = uscire. Ojo: salire en italiano es subir."),
    "salgo": ("esco", "Salgo = esco. Ojo: «salgo» italiano = subo."),
    "sales": ("esci", ""),
    "salis": ("esci / uscite", "Vos salís = tu esci; vosotros salís = voi uscite."),
    "sale": ("esce", "Sale = esce. Ojo: «sale» italiano = sube, o la sal."),
    "salimos": ("usciamo", ""),
    "salen": ("escono", ""),
    # poner
    "poner": ("mettere", ""),
    "pongo": ("metto", ""),
    "pones": ("metti", ""),
    "pone": ("mette", ""),
    "ponemos": ("mettiamo", ""),
    "poneis": ("mettete", ""),
    "ponen": ("mettono", ""),
    "ponerse": ("mettersi / diventare", "Ponerse (ropa) = mettersi; ponerse triste = diventare triste."),
    # otros presentes muy frecuentes
    "hablo": ("parlo", ""),
    "hablas": ("parli", ""),
    "habla": ("parla", ""),
    "hablamos": ("parliamo", "¡Hablamos! (despedida) = ci sentiamo!"),
    "hablan": ("parlano", ""),
    "trabajo": ("lavoro", "Trabajo (verbo y sustantivo) = lavoro."),
    "estudio": ("studio", ""),
    "llamo": ("chiamo", "Me llamo = mi chiamo."),
    "creo": ("credo / penso", "Creo que = credo che / penso che (+ congiuntivo)."),
    "pienso": ("penso", ""),
    "conozco": ("conosco", ""),
    "parece": ("sembra", "Me parece = mi sembra."),
    "llego": ("arrivo", ""),
    "vuelvo": ("torno", ""),
    "entiendo": ("capisco", "No entiendo = non capisco."),
    "busco": ("cerco", ""),
    "encuentro": ("trovo / incontro", "Encuentro (verbo) = trovo; un encuentro = un incontro."),
    "espero": ("aspetto / spero", "Espero (a alguien) = aspetto; espero que = spero che."),
    "tomo": ("prendo", ""),
    "suelo": ("di solito / pavimento", "Suelo ir = di solito vado. El suelo = il pavimento."),
})

# ---------------------------------------------------------------------------
# Pasados frecuentes y participios
# ---------------------------------------------------------------------------
ES_IT.update({
    "fui": ("sono stato / sono andato", "Fui (ser/ir) = sono stato / sono andato. «Fui» italiano es pasado remoto de essere."),
    "fuiste": ("sei stato / sei andato", ""),
    "fue": ("è stato / è andato", "Fue = è stato / è andato (literario: fu)."),
    "fuimos": ("siamo stati / siamo andati", ""),
    "fueron": ("sono stati / sono andati", ""),
    "estuve": ("sono stato", "Estar y ser comparten pasado: sono stato."),
    "estuvo": ("è stato", ""),
    "tuve": ("ho avuto", ""),
    "tuvo": ("ha avuto", ""),
    "hice": ("ho fatto", ""),
    "hizo": ("ha fatto", "Hizo frío = ha fatto freddo."),
    "dije": ("ho detto", ""),
    "dijo": ("ha detto", ""),
    "pude": ("ho potuto", ""),
    "pudo": ("ha potuto", ""),
    "quise": ("ho voluto", ""),
    "quiso": ("ha voluto", ""),
    "vine": ("sono venuto", "Venire usa essere: sono venuto / venuta."),
    "vino": ("è venuto / vino", "Vino (venir) = è venuto. El vino = il vino."),
    "di": ("ho dato", "Di (dar) = ho dato. Ojo: «di» italiano = de."),
    "dio": ("ha dato", "Dio (dar) = ha dato. Ojo: «Dio» en italiano es Dios."),
    "vi": ("ho visto", "Vi (ver) = ho visto. Ojo: «vi» italiano = os."),
    "vio": ("ha visto", ""),
    "supe": ("ho saputo", ""),
    "puse": ("ho messo", ""),
    "sali": ("sono uscito", "Salí = sono uscito. Ojo: «sali» italiano = subís."),
    "hubo": ("c'è stato / ci sono stati", "Hubo = c'è stato / ci sono stati (literario: ci fu)."),
    "era": ("ero / era", "Era = ero (yo) o era (él/ella)."),
    "eras": ("eri", ""),
    "eramos": ("eravamo", ""),
    "eran": ("erano", ""),
    "estaba": ("stavo / ero / stava / era", ""),
    "estaban": ("stavano / erano", ""),
    "tenia": ("avevo / aveva", ""),
    "tenian": ("avevano", ""),
    "habia": ("c'era / c'erano / avevo", "Había (existencia) = c'era / c'erano; auxiliar = avevo, aveva."),
    "iba": ("andavo / andava", ""),
    "iban": ("andavano", ""),
    "queria": ("volevo / voleva", "Quería = volevo; para pedir con cortesía: vorrei."),
    "podia": ("potevo / poteva", ""),
    "sabia": ("sapevo / sapeva", ""),
    "decia": ("dicevo / diceva", ""),
    "sera": ("sarà", "Será = sarà. Ojo: «sera» italiano es la tarde-noche."),
    "habra": ("ci sarà / avrà", ""),
    "sido": ("stato", "Sido = stato, con essere: sono stato."),
    "estado": ("stato", "Estado (estar, y también país) = stato."),
    "tenido": ("avuto", ""),
    "hecho": ("fatto", ""),
    "dicho": ("detto", ""),
    "puesto": ("messo / posto", "Puesto (poner) = messo; un puesto = un posto."),
    "ido": ("andato", "Ido = andato, con essere: sono andato."),
    "venido": ("venuto", ""),
    "dado": ("dato / dado", "Dado (dar) = dato; el dado (juego) = il dado."),
    "escrito": ("scritto", ""),
    "abierto": ("aperto", ""),
    "vuelto": ("tornato / resto", "Vuelto (volver) = tornato; el vuelto (plata) = il resto."),
    "muerto": ("morto", ""),
    "roto": ("rotto", ""),
    "comido": ("mangiato", ""),
    "bebido": ("bevuto", ""),
    "hablado": ("parlato", ""),
})

# ---------------------------------------------------------------------------
# Infinitivos frecuentes
# ---------------------------------------------------------------------------
ES_IT.update({
    "hablar": ("parlare", ""),
    "comer": ("mangiare", ""),
    "beber": ("bere", ""),
    "tomar": ("prendere / bere", "Tomar (el colectivo, un café) = prendere; tomar (bebida) también bere."),
    "vivir": ("vivere / abitare", "Vivo en Roma = abito a Roma (o vivo a Roma)."),
    "escribir": ("scrivere", ""),
    "leer": ("leggere", ""),
    "trabajar": ("lavorare", "Trabajar = lavorare; el trabajo = il lavoro."),
    "estudiar": ("studiare", ""),
    "aprender": ("imparare", "Aprender = imparare. «Apprendere» existe pero es formal (enterarse)."),
    "enseñar": ("insegnare / mostrare", "Enseñar (dar clase) = insegnare; enseñar algo (mostrar) = far vedere."),
    "llamar": ("chiamare", ""),
    "llamarse": ("chiamarsi", "Me llamo = mi chiamo."),
    "llegar": ("arrivare", ""),
    "llevar": ("portare", "Llevar = portare. «Llevo dos años acá» = sono qui da due anni."),
    "traer": ("portare", "Traer y llevar se dicen igual: portare."),
    "dejar": ("lasciare / smettere", "Dejar algo = lasciare; dejar de fumar = smettere di fumare."),
    "seguir": ("seguire / continuare", "Seguir haciendo = continuare a fare."),
    "encontrar": ("trovare", ""),
    "pensar": ("pensare", ""),
    "creer": ("credere", ""),
    "conocer": ("conoscere", ""),
    "parecer": ("sembrare", "Parecer = sembrare; me parece = mi sembra."),
    "pasar": ("passare / succedere", "¿Qué pasa? = che succede? / cosa c'è?"),
    "entrar": ("entrare", ""),
    "volver": ("tornare", "Volver = tornare. Volver a hacer = rifare o fare di nuovo."),
    "regresar": ("tornare", ""),
    "sentir": ("sentire / provare", ""),
    "sentirse": ("sentirsi", ""),
    "tratar": ("cercare di / trattare", "Tratar de + infinitivo = cercare di."),
    "intentar": ("provare / cercare di", "Intentar = provare a / cercare di."),
    "mirar": ("guardare", "Mirar = guardare. Ojo: «mirare» italiano = apuntar."),
    "contar": ("contare / raccontare", "Contar números = contare; contar una historia = raccontare."),
    "empezar": ("cominciare / iniziare", ""),
    "comenzar": ("cominciare", ""),
    "esperar": ("aspettare / sperare", "Esperar (a alguien) = aspettare; esperar (desear) = sperare."),
    "buscar": ("cercare", "Buscar = cercare. Ojo: «cerca» es «busca», no «cerca de»."),
    "existir": ("esistere", ""),
    "entender": ("capire", "Entender = capire. Ojo: «intendere» es querer decir o proponerse."),
    "pedir": ("chiedere", "Pedir y preguntar = chiedere (preguntar también domandare)."),
    "preguntar": ("chiedere / domandare", ""),
    "recibir": ("ricevere", ""),
    "recordar": ("ricordare", ""),
    "acordarse": ("ricordarsi", ""),
    "olvidar": ("dimenticare", ""),
    "olvidarse": ("dimenticarsi", ""),
    "terminar": ("finire", ""),
    "acabar": ("finire", "Acabar = finire. Acabo de = ho appena."),
    "permitir": ("permettere", ""),
    "aparecer": ("apparire / comparire", ""),
    "conseguir": ("ottenere / riuscire a", "Conseguir hacer algo = riuscire a fare."),
    "lograr": ("riuscire a / ottenere", ""),
    "servir": ("servire", ""),
    "sacar": ("tirare fuori / togliere", "Sacar una foto = fare una foto."),
    "necesitar": ("avere bisogno di", "Necesito = ho bisogno di (o mi serve)."),
    "mantener": ("mantenere", ""),
    "resultar": ("risultare", ""),
    "caer": ("cadere", ""),
    "caerse": ("cadere", "Me caí = sono caduto (sin reflexivo)."),
    "cambiar": ("cambiare", ""),
    "presentar": ("presentare", ""),
    "crear": ("creare", ""),
    "abrir": ("aprire", ""),
    "cerrar": ("chiudere", ""),
    "considerar": ("considerare", ""),
    "oir": ("sentire / udire", "Oír = sentire (udire es formal)."),
    "escuchar": ("ascoltare", ""),
    "convertir": ("trasformare / convertire", ""),
    "ganar": ("vincere / guadagnare", "Ganar un partido = vincere; ganar plata = guadagnare."),
    "perder": ("perdere", ""),
    "partir": ("partire / dividere", "Partir (irse) = partire; partir en dos = dividere o spezzare."),
    "morir": ("morire", ""),
    "nacer": ("nascere", ""),
    "crecer": ("crescere", ""),
    "envejecer": ("invecchiare", ""),
    "aceptar": ("accettare", ""),
    "realizar": ("realizzare", ""),
    "suponer": ("supporre", ""),
    "comprender": ("capire / comprendere", ""),
    "explicar": ("spiegare", ""),
    "tocar": ("toccare / suonare", "Tocar un instrumento = suonare."),
    "reconocer": ("riconoscere", ""),
    "alcanzar": ("raggiungere / bastare", "Alcanzar (llegar) = raggiungere; alcanza (es suficiente) = basta."),
    "dirigir": ("dirigere", ""),
    "correr": ("correre", ""),
    "utilizar": ("utilizzare", ""),
    "usar": ("usare", ""),
    "pagar": ("pagare", ""),
    "ayudar": ("aiutare", ""),
    "jugar": ("giocare", "Jugar = giocare; jugar al fútbol = giocare a calcio."),
    "cumplir": ("compiere / rispettare", "Cumplir años = compiere gli anni."),
    "ofrecer": ("offrire", ""),
    "descubrir": ("scoprire", ""),
    "averiguar": ("scoprire / informarsi", ""),
    "levantar": ("alzare / sollevare", ""),
    "levantarse": ("alzarsi", ""),
    "decidir": ("decidere", ""),
    "repetir": ("ripetere", ""),
    "valer": ("valere", ""),
    "comprar": ("comprare", ""),
    "vender": ("vendere", ""),
    "subir": ("salire", "Subir = salire. Ojo: «subire» es sufrir."),
    "bajar": ("scendere", ""),
    "dormir": ("dormire", ""),
    "despertar": ("svegliare", ""),
    "despertarse": ("svegliarsi", ""),
    "sentarse": ("sedersi", ""),
    "vestirse": ("vestirsi", ""),
    "bañarse": ("fare il bagno", ""),
    "ducharse": ("fare la doccia", ""),
    "lavar": ("lavare", ""),
    "limpiar": ("pulire", ""),
    "cocinar": ("cucinare", ""),
    "manejar": ("guidare", "Manejar (el auto) = guidare."),
    "conducir": ("guidare", "Conducir = guidare. «Condurre» es llevar o dirigir."),
    "viajar": ("viaggiare", ""),
    "caminar": ("camminare", ""),
    "andar": ("andare / camminare", "¿Cómo andás? = come stai? / come va?"),
    "nadar": ("nuotare", ""),
    "bailar": ("ballare", ""),
    "cantar": ("cantare", ""),
    "mostrar": ("mostrare / far vedere", ""),
    "enviar": ("inviare / mandare", ""),
    "mandar": ("mandare", ""),
    "responder": ("rispondere", ""),
    "contestar": ("rispondere", "Contestar = rispondere. Ojo: «contestare» es impugnar, protestar."),
    "alquilar": ("affittare / noleggiare", "Alquilar casa = affittare; auto o bici = noleggiare."),
    "costar": ("costare", ""),
    "gastar": ("spendere", "Gastar plata = spendere soldi."),
    "ahorrar": ("risparmiare", ""),
    "cobrar": ("incassare / far pagare", ""),
    "prestar": ("prestare", ""),
    "devolver": ("restituire / ridare", ""),
    "elegir": ("scegliere", ""),
    "preferir": ("preferire", ""),
    "amar": ("amare", ""),
    "odiar": ("odiare", ""),
    "reir": ("ridere", ""),
    "sonreir": ("sorridere", ""),
    "llorar": ("piangere", ""),
    "gritar": ("gridare / urlare", ""),
    "callar": ("tacere", "¡Callate! = stai zitto!"),
    "oler": ("annusare / avere odore", "Oler algo = annusare; oler a = avere odore di / sapere di."),
    "probar": ("provare / assaggiare", "Probar comida = assaggiare; probarse ropa = provare."),
    "doler": ("fare male", "Me duele = mi fa male."),
    "matar": ("uccidere / ammazzare", ""),
    "cortar": ("tagliare", ""),
    "romper": ("rompere", ""),
    "arreglar": ("aggiustare / sistemare", ""),
    "construir": ("costruire", ""),
    "quitar": ("togliere", ""),
    "agarrar": ("prendere / afferrare", "Agarrar = prendere. Ojo: en italiano «prendere» es el verbo básico para tomar."),
    "tirar": ("buttare / tirare", "Tirar (a la basura) = buttare; tirar de algo = tirare."),
    "empujar": ("spingere", ""),
    "colgar": ("appendere / riattaccare", "Colgar un cuadro = appendere; colgar el teléfono = riattaccare."),
    "esconder": ("nascondere", ""),
    "mover": ("muovere / spostare", ""),
    "llenar": ("riempire", ""),
    "vaciar": ("svuotare", ""),
    "llover": ("piovere", ""),
    "nevar": ("nevicare", ""),
    "dibujar": ("disegnare", ""),
    "pintar": ("dipingere / pitturare", ""),
    "pegar": ("incollare / picchiare", "Pegar (con pegamento) = incollare; pegarle a alguien = picchiare."),
    "guardar": ("mettere via / conservare", "Guardar = mettere via. Ojo: «guardare» italiano = mirar."),
    "cuidar": ("prendersi cura di / badare a", "Cuidar a alguien = prendersi cura di. «Curare» = tratar médicamente."),
    "visitar": ("visitare / andare a trovare", "Visitar a alguien = andare a trovare."),
    "invitar": ("invitare", ""),
    "charlar": ("chiacchierare", ""),
    "mentir": ("mentire", ""),
    "avisar": ("avvisare", ""),
    "prometer": ("promettere", ""),
    "dudar": ("dubitare", ""),
    "soler": ("di solito / solere", "Suelo ir = di solito vado."),
    "quejarse": ("lamentarsi", ""),
    "prender": ("accendere", "Prender la luz = accendere. Ojo: «prendere» italiano es tomar/agarrar."),
    "encender": ("accendere", ""),
    "apagar": ("spegnere", ""),
    "faltar": ("mancare", "Falta pan = manca il pane; faltan dos días = mancano due giorni."),
    "sobrar": ("avanzare", ""),
    "molestar": ("dare fastidio / disturbare", "Molestar = dare fastidio. Ojo: «molestare» existe, pero hoy suena fuerte y se asocia al acoso (le molestie)."),
    "fijarse": ("guardare / fare attenzione", ""),
    "apurarse": ("sbrigarsi", "¡Apurate! = sbrigati!"),
    "tardar": ("metterci / tardare", "Tardo una hora = ci metto un'ora."),
    "demorar": ("metterci", ""),
    "mudarse": ("traslocare / trasferirsi", ""),
    "estacionar": ("parcheggiare", ""),
    "doblar": ("girare / piegare", "Doblar a la derecha = girare a destra."),
    "cruzar": ("attraversare", ""),
    "acompañar": ("accompagnare", ""),
    "saludar": ("salutare", ""),
    "besar": ("baciare", ""),
    "abrazar": ("abbracciare", ""),
    "pelear": ("litigare", ""),
    "discutir": ("discutere / litigare", "Discutir (pelear) = litigare; discutir un tema = discutere."),
    "enamorarse": ("innamorarsi", ""),
    "casarse": ("sposarsi", "Casarse con alguien = sposarsi con / sposare qualcuno."),
    "aburrirse": ("annoiarsi", ""),
    "divertirse": ("divertirsi", ""),
    "disfrutar": ("godersi", ""),
    "descansar": ("riposare", ""),
    "cansarse": ("stancarsi", ""),
    "preocuparse": ("preoccuparsi", ""),
    "enojarse": ("arrabbiarsi", ""),
    "atreverse": ("osare", ""),
    "soñar": ("sognare", ""),
    "sonar": ("suonare", ""),
    "echar": ("buttare / cacciare", ""),
    "producir": ("produrre", ""),
    "ocurrir": ("succedere / accadere", ""),
    "suceder": ("succedere", ""),
    "incluir": ("includere", ""),
    "continuar": ("continuare", ""),
    "laburar": ("lavorare", ""),
})

# ---------------------------------------------------------------------------
# Sustantivos y adjetivos frecuentes con forma italiana distinta
# ---------------------------------------------------------------------------
ES_IT.update({
    # personas y familia
    "hombre": ("uomo", "Plural irregular: gli uomini."),
    "mujer": ("donna / moglie", "Mujer = donna; mi mujer (esposa) = mia moglie."),
    "niño": ("bambino", ""),
    "niña": ("bambina", ""),
    "chico": ("ragazzo / piccolo", "Chico (muchacho) = ragazzo; chico (pequeño) = piccolo."),
    "chica": ("ragazza", ""),
    "pibe": ("ragazzo", ""),
    "piba": ("ragazza", ""),
    "hijo": ("figlio", ""),
    "hija": ("figlia", ""),
    "hijos": ("figli", ""),
    "papa": ("papà / patata / Papa", "Papá = papà; la papa = la patata; el Papa = il Papa."),
    "mama": ("mamma", ""),
    "padres": ("genitori", "Los padres (papá y mamá) = i genitori."),
    "hermano": ("fratello", ""),
    "hermana": ("sorella", ""),
    "hermanos": ("fratelli", ""),
    "abuelo": ("nonno", ""),
    "abuela": ("nonna", ""),
    "tio": ("zio", ""),
    "tia": ("zia", ""),
    "primo": ("cugino", "Primo (pariente) = cugino. Ojo: «primo» italiano = primero."),
    "prima": ("cugina", "Prima (pariente) = cugina. Ojo: «prima» italiano = antes."),
    "sobrino": ("nipote", "Sobrino y nieto se dicen igual: nipote."),
    "nieto": ("nipote", ""),
    "esposo": ("marito", ""),
    "esposa": ("moglie", ""),
    "marido": ("marito", ""),
    "novio": ("fidanzato / ragazzo", ""),
    "novia": ("fidanzata / ragazza", ""),
    "amigo": ("amico", "Plural: amici."),
    "amiga": ("amica", "Plural: amiche."),
    "señor": ("signore", "Ante nombre pierde la -e: il signor Rossi."),
    "señora": ("signora", ""),
    "jefe": ("capo", ""),
    "empleado": ("impiegato", ""),
    "doctor": ("dottore / medico", ""),
    # cuerpo
    "cuerpo": ("corpo", ""),
    "cabeza": ("testa", ""),
    "cara": ("faccia / viso", "La cara = la faccia o il viso. Ojo: «cara» italiano = querida."),
    "ojo": ("occhio", ""),
    "ojos": ("occhi", ""),
    "oreja": ("orecchio", "Masculino: l'orecchio (plural le orecchie)."),
    "nariz": ("naso", "Masculino: il naso."),
    "boca": ("bocca", ""),
    "diente": ("dente", ""),
    "pelo": ("capelli", "El pelo de la cabeza = i capelli (plural). Ojo: «pelo» italiano = vello."),
    "brazo": ("braccio", "Plural irregular: le braccia."),
    "pierna": ("gamba", "Pierna = gamba. Ojo: la gamba (camarón) es il gambero."),
    "pie": ("piede", ""),
    "espalda": ("schiena", ""),
    "hombro": ("spalla", ""),
    "dedo": ("dito", "Plural irregular: le dita."),
    "rodilla": ("ginocchio", ""),
    "corazon": ("cuore", ""),
    "estomago": ("stomaco", ""),
    "panza": ("pancia", ""),
    "cuello": ("collo", ""),
    "piel": ("pelle", ""),
    "hueso": ("osso", "Plural: le ossa."),
    "sangre": ("sangue", "Masculino: il sangue."),
    # casa y ciudad
    "hogar": ("casa / focolare", ""),
    "habitacion": ("stanza / camera", ""),
    "cuarto": ("stanza / quarto", "Cuarto (pieza) = stanza; un cuarto (1/4) = un quarto."),
    "pieza": ("stanza / pezzo", "La pieza (cuarto) = la stanza; pieza (parte) = il pezzo."),
    "dormitorio": ("camera da letto", ""),
    "baño": ("bagno", ""),
    "cocina": ("cucina", ""),
    "ventana": ("finestra", ""),
    "puerta": ("porta", ""),
    "piso": ("piano / pavimento", "Piso (de edificio) = piano; el piso (suelo) = il pavimento."),
    "techo": ("tetto / soffitto", "Techo exterior = tetto; techo de adentro = soffitto."),
    "pared": ("parete / muro", "Femenino: la parete."),
    "mesa": ("tavolo", "Masculino: il tavolo."),
    "silla": ("sedia", ""),
    "cama": ("letto", "Masculino: il letto."),
    "llave": ("chiave", ""),
    "escalera": ("scala / scale", ""),
    "calle": ("strada / via", "La calle = la strada; en direcciones: via Roma."),
    "barrio": ("quartiere", ""),
    "ciudad": ("città", "Ciudad = città (con tilde, invariable: le città)."),
    "pueblo": ("paese / popolo", "Pueblo (lugar) = paese; pueblo (gente) = popolo."),
    "pais": ("paese", "País = paese. Ojo: «paese» también es pueblo."),
    "mundo": ("mondo", ""),
    "tienda": ("negozio", "Tienda = negozio. Ojo: «tenda» es cortina o carpa."),
    "negocio": ("negozio / affare", "Negocio (local) = negozio; un buen negocio = un buon affare."),
    "almacen": ("negozio di alimentari", ""),
    "supermercado": ("supermercato", ""),
    "mercado": ("mercato", ""),
    "iglesia": ("chiesa", ""),
    "escuela": ("scuola", ""),
    "colegio": ("scuola", ""),
    "universidad": ("università", ""),
    "hospital": ("ospedale", ""),
    "plaza": ("piazza", ""),
    "oficina": ("ufficio", "Oficina = ufficio. Ojo: «officina» es taller mecánico."),
    "empresa": ("azienda / impresa", ""),
    "reunion": ("riunione", ""),
    # naturaleza y tiempo
    "playa": ("spiaggia", ""),
    "mar": ("mare", "Masculino: il mare."),
    "rio": ("fiume", ""),
    "montaña": ("montagna", ""),
    "arbol": ("albero", ""),
    "flor": ("fiore", "Masculino: il fiore."),
    "sol": ("sole", ""),
    "estrella": ("stella", ""),
    "lluvia": ("pioggia", ""),
    "nieve": ("neve", ""),
    "viento": ("vento", ""),
    "hielo": ("ghiaccio", ""),
    "tiempo": ("tempo", "Tiempo (clima y duración) = tempo: che tempo fa?"),
    "calor": ("caldo", "Calor = caldo: fa caldo. Ojo: el caldo (sopa) es il brodo."),
    "frio": ("freddo", ""),
    "fuego": ("fuoco", ""),
    "agua": ("acqua", ""),
    "tierra": ("terra", ""),
    "piedra": ("pietra", ""),
    "hierro": ("ferro", ""),
    "madera": ("legno", ""),
    "luz": ("luce", ""),
    "sombra": ("ombra", ""),
    "ruido": ("rumore", "Ruido = rumore. Un rumor = una voce."),
    "voz": ("voce", ""),
    "olor": ("odore", ""),
    "sabor": ("sapore", ""),
    "color": ("colore", ""),
    # tiempo, calendario, números
    "dia": ("giorno", ""),
    "dias": ("giorni", ""),
    "noche": ("notte", ""),
    "semana": ("settimana", ""),
    "mes": ("mese", ""),
    "año": ("anno", "Año = anno (con nn)."),
    "años": ("anni", ""),
    "hora": ("ora", ""),
    "principio": ("inizio / principio", ""),
    "fin": ("fine", "La fine (del cuento) es femenino; il fine = el objetivo."),
    "lunes": ("lunedì", ""),
    "martes": ("martedì", ""),
    "miercoles": ("mercoledì", ""),
    "jueves": ("giovedì", ""),
    "viernes": ("venerdì", ""),
    "sabado": ("sabato", ""),
    "domingo": ("domenica", "Femenino: la domenica."),
    "enero": ("gennaio", ""),
    "febrero": ("febbraio", ""),
    "abril": ("aprile", ""),
    "mayo": ("maggio", ""),
    "junio": ("giugno", ""),
    "julio": ("luglio", ""),
    "septiembre": ("settembre", ""),
    "setiembre": ("settembre", ""),
    "octubre": ("ottobre", ""),
    "noviembre": ("novembre", ""),
    "diciembre": ("dicembre", ""),
    "verano": ("estate", "Verano = l'estate (femenino)."),
    "otoño": ("autunno", ""),
    "invierno": ("inverno", ""),
    "dos": ("due", ""),
    "tres": ("tre", ""),
    "cuatro": ("quattro", ""),
    "cinco": ("cinque", ""),
    "seis": ("sei", "Seis = sei (igual que «sos»: tu sei)."),
    "siete": ("sette", "Siete = sette. Ojo: «siete» en italiano = ustedes son (voi siete)."),
    "ocho": ("otto", ""),
    "nueve": ("nove", ""),
    "diez": ("dieci", ""),
    "once": ("undici", ""),
    "doce": ("dodici", ""),
    "trece": ("tredici", ""),
    "catorce": ("quattordici", ""),
    "quince": ("quindici", ""),
    "veinte": ("venti", ""),
    "treinta": ("trenta", ""),
    "cuarenta": ("quaranta", ""),
    "cincuenta": ("cinquanta", ""),
    "cien": ("cento", ""),
    "ciento": ("cento", ""),
    "mil": ("mille", "Plural: mila (duemila)."),
    "millon": ("milione", ""),
    "primero": ("primo", ""),
    "segundo": ("secondo", ""),
    "tercero": ("terzo", ""),
    # comida
    "pan": ("pane", ""),
    "leche": ("latte", "Femenino en español, masculino en italiano: il latte."),
    "sal": ("sale", "Femenino en español, masculino en italiano: il sale."),
    "miel": ("miele", "Masculino: il miele."),
    "pescado": ("pesce", "Pescado y pez se dicen igual: pesce."),
    "pez": ("pesce", ""),
    "huevo": ("uovo", "Plural irregular: le uova."),
    "queso": ("formaggio", ""),
    "manteca": ("burro", "Manteca = burro. ¡Sí, «burro» es manteca!"),
    "aceite": ("olio", "Aceite = olio. Ojo: «aceto» es vinagre."),
    "vinagre": ("aceto", ""),
    "azucar": ("zucchero", "Masculino: lo zucchero."),
    "cafe": ("caffè", ""),
    "jugo": ("succo", "Jugo = succo. Ojo: «sugo» es salsa."),
    "cerveza": ("birra", ""),
    "manzana": ("mela", ""),
    "naranja": ("arancia / arancione", "Naranja (fruta) = arancia; el color = arancione."),
    "frutilla": ("fragola", ""),
    "tomate": ("pomodoro", ""),
    "cebolla": ("cipolla", ""),
    "ajo": ("aglio", ""),
    "lechuga": ("lattuga", ""),
    "zanahoria": ("carota", ""),
    "arroz": ("riso", ""),
    "sopa": ("zuppa / minestra", ""),
    "jamon": ("prosciutto", ""),
    "helado": ("gelato", ""),
    "galletita": ("biscotto", ""),
    "desayuno": ("colazione", ""),
    "almuerzo": ("pranzo", ""),
    "comida": ("cibo / pasto", "Comida (alimento) = cibo; comida (del día) = pasto."),
    "bebida": ("bevanda / bibita", ""),
    "vaso": ("bicchiere", "Vaso (para tomar) = bicchiere. Ojo: «vaso» italiano = maceta o florero."),
    "taza": ("tazza", ""),
    "plato": ("piatto", ""),
    "cuchara": ("cucchiaio", ""),
    "cuchillo": ("coltello", ""),
    "tenedor": ("forchetta", ""),
    "botella": ("bottiglia", ""),
    "hambre": ("fame", "Tengo hambre = ho fame."),
    "sed": ("sete", ""),
    # ropa y objetos
    "ropa": ("vestiti", "La ropa = i vestiti (plural)."),
    "camisa": ("camicia", ""),
    "remera": ("maglietta", ""),
    "pantalon": ("pantaloni", "Pantalón = i pantaloni (plural)."),
    "pantalones": ("pantaloni", ""),
    "zapato": ("scarpa", ""),
    "zapatos": ("scarpe", ""),
    "zapatilla": ("scarpa da ginnastica", ""),
    "pollera": ("gonna", ""),
    "falda": ("gonna", ""),
    "vestido": ("vestito", ""),
    "abrigo": ("cappotto", ""),
    "campera": ("giacca / giubbotto", ""),
    "sombrero": ("cappello", ""),
    "anteojos": ("occhiali", ""),
    "reloj": ("orologio", ""),
    "bolsa": ("borsa / sacchetto", ""),
    "cartera": ("borsa / portafoglio", "Cartera (de mujer) = borsa; billetera = portafoglio."),
    "billetera": ("portafoglio", ""),
    "papel": ("carta", "Papel = carta. Ojo: la carta (que se manda) = la lettera."),
    "carta": ("lettera", "Carta = lettera. Ojo: «carta» italiano = papel."),
    "hoja": ("foglia / foglio", "Hoja de árbol = foglia; hoja de papel = foglio."),
    "lapiz": ("matita", ""),
    "lapicera": ("penna", ""),
    "birome": ("penna a sfera", ""),
    "cuaderno": ("quaderno", ""),
    "computadora": ("computer", "Computadora = il computer (masculino)."),
    "celular": ("cellulare / telefonino", ""),
    "dinero": ("soldi / denaro", ""),
    "plata": ("soldi / argento", "Plata (dinero) = soldi; plata (metal) = argento."),
    "precio": ("prezzo", ""),
    "cuenta": ("conto", "La cuenta, por favor = il conto, per favore."),
    "compras": ("spesa / acquisti", "Hacer las compras = fare la spesa."),
    # transporte y lugares
    "coche": ("macchina / auto", "Coche = la macchina (femenino)."),
    "auto": ("macchina / auto", "Auto = la macchina o l'auto (femenino en italiano)."),
    "colectivo": ("autobus", ""),
    "tren": ("treno", ""),
    "avion": ("aereo", ""),
    "barco": ("nave / barca", ""),
    "bicicleta": ("bicicletta / bici", ""),
    "subte": ("metropolitana / metro", ""),
    "estacion": ("stazione", ""),
    "aeropuerto": ("aeroporto", ""),
    "boleto": ("biglietto", ""),
    "pasaje": ("biglietto", ""),
    "entrada": ("ingresso / biglietto", ""),
    "salida": ("uscita / partenza", ""),
    "viaje": ("viaggio", ""),
    "vacaciones": ("vacanze", ""),
    "lugar": ("posto / luogo", ""),
    "camino": ("strada / cammino", "Camino = strada o cammino. Ojo: «camino» italiano = chimenea."),
    "derecha": ("destra", ""),
    "izquierda": ("sinistra", ""),
    "derecho": ("dritto / diritto", "Derecho (recto) = dritto; el derecho (ley) = il diritto."),
    "sur": ("sud", ""),
    "oeste": ("ovest", ""),
    # animales
    "perro": ("cane", ""),
    "gato": ("gatto", ""),
    "caballo": ("cavallo", ""),
    "pajaro": ("uccello", ""),
    "raton": ("topo", "Ratón = topo. Ojo: el topo (animal) es la talpa."),
    "vaca": ("mucca / vacca", ""),
    "oveja": ("pecora", ""),
    "cerdo": ("maiale", ""),
    "chancho": ("maiale", ""),
    # abstractos
    "vida": ("vita", ""),
    "muerte": ("morte", ""),
    "amor": ("amore", ""),
    "miedo": ("paura", "Tener miedo = avere paura."),
    "suerte": ("fortuna", "¡Suerte! = in bocca al lupo! (y se responde crepi!)."),
    "verdad": ("verità / vero", "Es verdad = è vero; la verdad = la verità."),
    "mentira": ("bugia", ""),
    "pregunta": ("domanda", ""),
    "respuesta": ("risposta", ""),
    "palabra": ("parola", ""),
    "idioma": ("lingua", ""),
    "lengua": ("lingua", ""),
    "nombre": ("nome", ""),
    "apellido": ("cognome", ""),
    "edad": ("età", ""),
    "historia": ("storia", ""),
    "cuento": ("racconto / favola", "Cuento = racconto. Ojo: «conto» italiano es la cuenta."),
    "juego": ("gioco", ""),
    "fiesta": ("festa", ""),
    "cumpleaños": ("compleanno", ""),
    "tarea": ("compito / compiti", "Tarea (de la escuela) = i compiti."),
    "clase": ("lezione / classe", "Tomar clases = prendere lezioni; el grupo o el aula = la classe."),
    "examen": ("esame", ""),
    "ejemplo": ("esempio", ""),
    "error": ("errore", ""),
    "razon": ("ragione", "Tener razón = avere ragione."),
    "manera": ("modo / maniera", ""),
    "paz": ("pace", ""),
    "ley": ("legge", ""),
    "gobierno": ("governo", ""),
    "sociedad": ("società", ""),
    "libertad": ("libertà", ""),
    "cancion": ("canzone", ""),
    "pelicula": ("film", "La película = il film (masculino)."),
    "diario": ("giornale / diario", "Diario (periódico) = giornale; diario íntimo = diario."),
    "noticia": ("notizia", ""),
    "enfermedad": ("malattia", ""),
    "dolor": ("dolore", ""),
    "remedio": ("medicina", ""),
    "sueño": ("sonno / sogno", "Sueño (ganas de dormir) = sonno; lo que soñás = sogno."),
    "quilombo": ("casino / caos", "Quilombo = casino (coloquial). Ojo: el casino de juego es il casinò."),
    "laburo": ("lavoro", ""),
    # idiomas y lugares
    "español": ("spagnolo", ""),
    "ingles": ("inglese", ""),
    "frances": ("francese", ""),
    "aleman": ("tedesco", ""),
    "españa": ("Spagna", ""),
    "alemania": ("Germania", ""),
    "inglaterra": ("Inghilterra", ""),
    "estados unidos": ("Stati Uniti", ""),
    "brasil": ("Brasile", ""),
    "mexico": ("Messico", ""),
    "londres": ("Londra", ""),
    "paris": ("Parigi", ""),
    "florencia": ("Firenze", ""),
    "venecia": ("Venezia", ""),
    "napoles": ("Napoli", ""),
    "milan": ("Milano", ""),
    "turin": ("Torino", ""),
    # adjetivos
    "pequeño": ("piccolo", ""),
    "chiquito": ("piccolino", ""),
    "largo": ("lungo", "Largo = lungo. Ojo: «largo» italiano es ancho."),
    "ancho": ("largo", "Ancho = largo. ¡Al revés que en español!"),
    "gordo": ("grasso", ""),
    "flaco": ("magro", ""),
    "delgado": ("magro", ""),
    "lindo": ("bello / carino", ""),
    "bonito": ("bello / carino", ""),
    "hermoso": ("bello", ""),
    "feo": ("brutto", "Feo = brutto. Ojo: «brutto» no es bruto."),
    "nuevo": ("nuovo", ""),
    "viejo": ("vecchio", ""),
    "joven": ("giovane", ""),
    "malo": ("cattivo", "Malo = cattivo; mal (adverbio) = male."),
    "barato": ("economico", ""),
    "facil": ("facile", ""),
    "dificil": ("difficile", ""),
    "caliente": ("caldo", "Caliente = caldo. Ojo: el caldo (sopa) es il brodo."),
    "lleno": ("pieno", ""),
    "vacio": ("vuoto", ""),
    "limpio": ("pulito", ""),
    "sucio": ("sporco", ""),
    "cansado": ("stanco", ""),
    "enfermo": ("malato", ""),
    "feliz": ("felice", ""),
    "rico": ("buono / ricco", "Rico (comida) = buono; rico (con plata) = ricco."),
    "pobre": ("povero", ""),
    "fuerte": ("forte", ""),
    "debil": ("debole", ""),
    "verdadero": ("vero", ""),
    "cierto": ("vero / certo", "Es cierto = è vero."),
    "seguro": ("sicuro", ""),
    "listo": ("pronto / furbo", "Estar listo = essere pronto; ser listo = essere furbo."),
    "despierto": ("sveglio", ""),
    "dormido": ("addormentato", ""),
    "ocupado": ("occupato", ""),
    "libre": ("libero", ""),
    "cerrado": ("chiuso", ""),
    "necesario": ("necessario", ""),
    "posible": ("possibile", ""),
    "imposible": ("impossibile", ""),
    "diferente": ("diverso / differente", ""),
    "igual": ("uguale / comunque", "Igual = uguale. «Igual» (de todos modos) = comunque."),
    "distinto": ("diverso", "Distinto = diverso. «Distinto» italiano es más bien separado o distinguido (distinti saluti)."),
    "entero": ("intero", ""),
    "propio": ("proprio", "Propio = proprio. «Proprio» también significa justo o realmente."),
    "cercano": ("vicino", ""),
    "lejano": ("lontano", ""),
    "proximo": ("prossimo", "Próximo = prossimo (con ss)."),
    "pasado": ("scorso / passato", "El año pasado = l'anno scorso."),
    "rojo": ("rosso", ""),
    "azul": ("blu / azzurro", "Azul oscuro = blu; celeste = azzurro."),
    "amarillo": ("giallo", ""),
    "negro": ("nero", ""),
    "blanco": ("bianco", ""),
    "gris": ("grigio", ""),
    "marron": ("marrone", ""),
    "rosado": ("rosa", ""),
    "rubio": ("biondo", ""),
    "morocho": ("moro / bruno", ""),
    "gracioso": ("divertente / buffo", ""),
    "divertido": ("divertente", ""),
    "aburrido": ("noioso / annoiato", "Aburrido (que aburre) = noioso; (que se aburre) = annoiato."),
    "raro": ("strano", "Raro (extraño) = strano. Ojo: «raro» italiano = poco frecuente."),
    "extraño": ("strano", ""),
    "tonto": ("stupido / sciocco", ""),
    "loco": ("pazzo", ""),
    "amable": ("gentile", ""),
    "tranquilo": ("tranquillo", ""),
    "nervioso": ("nervoso", ""),
    "enojado": ("arrabbiato", ""),
    "orgulloso": ("orgoglioso", ""),
    "embarazada": ("incinta", "Embarazada = incinta. Ojo: «imbarazzata» es avergonzada."),
    "avergonzado": ("imbarazzato", "Avergonzarse = vergognarsi."),
    "celoso": ("geloso", ""),
})


# ---------------------------------------------------------------------------
# Falsos amigos: palabra ITALIANA que parece española
#   italiano → (qué significa en español, qué quería decir el alumno, nota)
# ---------------------------------------------------------------------------
FALSI = {
    "burro": ("manteca", "asino", "Burro en italiano es manteca. El animal es asino."),
    "salire": ("subir", "uscire", "Salire = subir. Salir es uscire."),
    "salgo": ("subo", "esco", "Salgo (de salire) = subo. «Salgo de casa» = esco di casa."),
    "sali": ("subís / subí (imperativo)", "esci", "Sali = subís. «Salís» es esci."),
    "sale": ("sube / la sal", "esce", "Sale = sube, o la sal. «Sale de casa» = esce di casa."),
    "caldo": ("caliente / calor", "brodo", "Caldo = caliente. El caldo es brodo."),
    "largo": ("ancho", "lungo", "Largo = ancho. Largo (de longitud) es lungo."),
    "camera": ("habitación / cuarto", "macchina fotografica", "Camera = habitación. La cámara de fotos es la macchina fotografica."),
    "guardare": ("mirar", "mettere via / conservare", "Guardare = mirar. Guardar algo es mettere via o conservare."),
    "mirare": ("apuntar", "guardare", "Mirare = apuntar. Mirar es guardare."),
    "aceto": ("vinagre", "olio", "Aceto = vinagre. El aceite es olio."),
    "topo": ("ratón", "talpa", "Topo = ratón. El topo (animal) es la talpa."),
    "gamba": ("pierna", "gambero", "Gamba = pierna. La gamba (camarón) es il gambero."),
    "morbido": ("blando / suave", "morboso", "Morbido = suave, blando. Morboso (enfermizo) es morboso."),
    "subire": ("sufrir / padecer", "salire", "Subire = sufrir. Subir es salire."),
    "fermare": ("detener / parar", "firmare", "Fermare = parar. Firmar es firmare."),
    "pronto": ("listo / ¿hola? (teléfono)", "presto", "Pronto = listo, o ¿hola? al teléfono. «Pronto» (en breve) es presto."),
    "subito": ("enseguida / ya", "improvviso", "Subito = enseguida. Súbito (repentino) es improvviso."),
    "tasca": ("bolsillo", "osteria / bar", "Tasca = bolsillo. Una tasca (bar) es un'osteria."),
    "carta": ("papel", "lettera", "Carta = papel. La carta que mandás es una lettera."),
    "cantina": ("sótano / bodega", "bar / mensa", "Cantina = sótano o bodega. La cantina (comedor) es la mensa."),
    "bravo": ("capo / hábil", "feroce / arrabbiato", "Bravo = hábil, capo. Un perro bravo es feroce."),
    "vaso": ("maceta / florero", "bicchiere", "Vaso = maceta o florero. El vaso para tomar es il bicchiere."),
    "equipaggio": ("tripulación", "bagaglio", "Equipaggio = tripulación. El equipaje es il bagaglio."),
    "imbarazzata": ("avergonzada / incómoda", "incinta", "Imbarazzata = avergonzada. Embarazada es incinta."),
    "imbarazzato": ("avergonzado / incómodo", "incinta", "Imbarazzato = avergonzado. Embarazada es incinta."),
    "rumore": ("ruido", "voce / diceria", "Rumore = ruido. Un rumor es una voce."),
    "genero": ("yerno", "genere", "Genero = yerno. Género es genere."),
    "nudo": ("desnudo", "nodo", "Nudo = desnudo. Un nudo es un nodo."),
    "tenda": ("cortina / carpa", "negozio", "Tenda = cortina o carpa. La tienda es il negozio."),
    "cura": ("cuidado / tratamiento", "prete", "Cura = cuidado o tratamiento. El cura es il prete."),
    "curare": ("tratar (médicamente)", "prendersi cura di", "Curare = tratar a un enfermo. Cuidar a alguien es prendersi cura di."),
    "pasto": ("comida (del día)", "erba / prato", "Pasto = comida. El pasto es l'erba o il prato."),
    "sembrare": ("parecer", "seminare", "Sembrare = parecer. Sembrar es seminare."),
    "intendere": ("querer decir / proponerse", "capire", "Intendere = querer decir. Entender es capire."),
    "carino": ("lindo / simpático", "affetto", "Carino = lindo. El cariño es l'affetto."),
    "pretendere": ("exigir", "aspirare / sperare", "Pretendere = exigir. Pretender (aspirar) es aspirare o sperare di."),
    "mancia": ("propina", "macchia", "Mancia = propina. Una mancha es una macchia."),
    "coda": ("cola (fila o de animal)", "gomito", "Coda = cola. El codo es il gomito."),
    "colla": ("pegamento", "coda", "Colla = pegamento. La cola (fila) es la coda."),
    "parata": ("desfile / atajada", "fermata", "Parata = desfile. La parada del colectivo es la fermata."),
    "parare": ("atajar / proteger", "fermare / fermarsi", "Parare = atajar. Parar es fermare (o fermarsi)."),
    "officina": ("taller mecánico", "ufficio", "Officina = taller. La oficina es l'ufficio."),
    "patente": ("registro de conducir", "targa", "Patente = registro de conducir. La patente del auto es la targa."),
    "ancora": ("todavía / otra vez", "adesso / ora", "Ancora = todavía. «Ahora» es adesso u ora."),
    "attendere": ("esperar", "servire / assistere", "Attendere = esperar. Atender (a un cliente) es servire."),
    "esito": ("resultado", "successo", "Esito = resultado. Éxito es successo."),
    "successo": ("éxito / sucedido", "avvenimento / fatto", "Successo = éxito (o «pasó»). Un suceso es un avvenimento."),
    "autista": ("chofer", "autistico", "Autista = chofer. Autista (TEA) es autistico."),
    "compito": ("tarea", "complimento", "Compito = tarea. Un cumplido es un complimento."),
    "estate": ("verano", "state / stai", "Estate = verano. «Estate quieto» sería stai fermo."),
    "camino": ("chimenea", "strada / cammino", "Camino = chimenea. El camino es la strada o il cammino."),
    "casi": ("casos", "quasi", "Casi = casos. «Casi» (por poco) es quasi."),
    "come": ("cómo / como", "mangia", "Come = cómo. «Él come» es lui mangia."),
    "seta": ("seda", "fungo", "Seta = seda. La seta (hongo) es il fungo."),
    "rata": ("cuota (de un pago)", "ratto", "Rata = cuota. La rata (animal) es il ratto."),
    "bolla": ("burbuja", "palla", "Bolla = burbuja. Una bola es una palla."),
    "cara": ("querida / cara (precio)", "faccia / viso", "Cara = querida o costosa. La cara es la faccia o il viso."),
    "rostro": ("pico (de ave)", "volto / viso", "Rostro = pico. El rostro es il volto o il viso."),
    "sera": ("tarde-noche", "sarà", "Sera = la tarde-noche. «Será» es sarà."),
    "prima": ("antes / primera", "cugina", "Prima = antes (o primera). Tu prima es tua cugina."),
    "primo": ("primero", "cugino", "Primo = primero. Tu primo es tuo cugino."),
    "oso": ("me atrevo", "orso", "Oso (de osare) = me atrevo. El oso es l'orso."),
    "volta": ("vez", "giro / ritorno", "Volta = vez (una volta). Una vuelta es un giro."),
    "volto": ("rostro", "resto / tornato", "Volto = rostro. El vuelto (plata) es il resto."),
    "stufo": ("harto", "stufa", "Stufo = harto. La estufa es la stufa."),
    "tovaglia": ("mantel", "asciugamano", "Tovaglia = mantel. La toalla es l'asciugamano."),
    "zucca": ("zapallo / calabaza", "zucchero", "Zucca = zapallo. El azúcar es lo zucchero."),
    "cappello": ("sombrero", "capelli", "Cappello = sombrero. El cabello es i capelli."),
    "pelo": ("vello (del cuerpo)", "capelli", "Pelo = vello. El pelo de la cabeza es i capelli."),
    "accidente": ("maldición / desgracia", "incidente", "Un accidente de tránsito es un incidente. «Accidenti!» = ¡caramba!"),
    "domanda": ("pregunta", "richiesta / causa", "Domanda = pregunta. Una demanda es una richiesta (o una causa)."),
    "contestare": ("impugnar / protestar", "rispondere", "Contestare = protestar, impugnar. Contestar es rispondere."),
    "direzione": ("rumbo / gerencia", "indirizzo", "Direzione = rumbo o gerencia. Tu dirección es l'indirizzo."),
    "magazzino": ("depósito", "rivista", "Magazzino = depósito. Una revista es una rivista."),
    "ginnasio": ("secundario clásico", "palestra", "Ginnasio = primeros años del liceo. El gimnasio es la palestra."),
    "conto": ("cuenta", "racconto", "Conto = cuenta (il conto, per favore). Un cuento es un racconto."),
    "sugo": ("salsa (para pasta)", "succo", "Sugo = salsa. El jugo es il succo."),
    "negozio": ("tienda / local", "affare", "Negozio = tienda. Un buen negocio es un buon affare."),
    "lampo": ("relámpago", "lampada", "Lampo = relámpago. La lámpara es la lampada."),
    "polso": ("muñeca (del brazo) / pulso", "bambola", "Polso = muñeca del brazo. La muñeca (juguete) es la bambola."),
    "tirare": ("tirar de / lanzar", "buttare", "Tirare = tirar de. Tirar a la basura es buttare."),
    "prendere": ("tomar / agarrar", "accendere", "Prendere = tomar. Prender la luz es accendere."),
    "molestare": ("acosar", "dare fastidio", "Molestare = importunar y, sobre todo hoy, acosar (le molestie). Para el «molestar» cotidiano: dare fastidio o disturbare."),
    "raro": ("poco frecuente", "strano", "Raro = poco común. Raro (extraño) es strano."),
    "distinto": ("separado / distinguido", "diverso", "Distinto = separado o distinguido. Para «diferente» lo normal es diverso."),
    "brutto": ("feo", "rozzo / brutale", "Brutto = feo. Bruto (tosco) es rozzo o brutale."),
    "vela": ("vela (de barco)", "candela", "Vela = vela de barco. La vela para iluminar es la candela."),
    "alla": ("a la", "là", "Alla = a la (alla stazione). «Allá» es là."),
    "cerca": ("busca (de cercare)", "vicino", "Cerca = busca. «Cerca de» es vicino a."),
    "su": ("sobre / arriba", "suo / sua", "Su = sobre. «Su» posesivo es il suo / la sua."),
    "vi": ("os / allí", "ho visto", "Vi = os (o allí). «Vi» (ver) es ho visto."),
    "di": ("de", "ho dato", "Di = de. «Di» (dar) es ho dato."),
    "dio": ("Dios", "ha dato", "Dio = Dios. «Dio» (dar) es ha dato."),
    "siete": ("sois / ustedes son", "sette", "Siete = ustedes son (voi siete). El número 7 es sette."),
    "fui": ("fui (de essere, pasado remoto)", "sono stato / sono andato", "Fui existe pero es literario. En el habla: sono stato / sono andato."),
    "gusto": ("sabor / gusto", "piacere", "Gusto = sabor. «Mucho gusto» es piacere."),
}

# ---------------------------------------------------------------------------
# Correspondencias ortográficas español → italiano
#   (patrón_es, patrón_it, explicación)
# ---------------------------------------------------------------------------
SPELLING = [
    ("ñ", "gn", "El sonido ñ en italiano se escribe gn: montagna, bagno, sogno."),
    ("ll", "gli", "El sonido ll/ʎ se escribe gli (gl ante i): figlio, famiglia, luglio."),
    ("que", "che", "Para el sonido /ke/ el italiano usa ch: che, perché, anche."),
    ("qui", "chi", "Para /ki/ el italiano usa chi: chi, chilo, chiave."),
    ("cua", "qua", "Cua → qua: quando, quattro, quadro."),
    ("cue", "que", "Cue → que (se pronuncia /kwe/): questo, questione."),
    ("cuo", "quo", "Cuo → quo: quota, quotidiano. Ojo: cuore y cuoco se escriben con c."),
    ("cui", "qui", "Cui → qui (/kwi/): quindi, quinto. «Cui» italiano existe: il ragazzo di cui parlo."),
    ("j", "gi", "La j española no existe: se usa gi/g (giardino, Giovanni, giovane)."),
    ("ch", "ci", "El sonido ch (/tʃ/) ante a, o, u se escribe ci: ciao, cioccolato."),
    ("che", "ce", "El sonido /tʃe/ se escribe ce, no che (che suena /ke/): cena, cento."),
    ("chi", "ci", "El sonido /tʃi/ se escribe ci, no chi (chi suena /ki/): cinema, città."),
    ("gue", "ghe", "Para el sonido /ge/ el italiano usa gh: spaghetti, laghetto."),
    ("gui", "ghi", "Para el sonido /gi/ el italiano usa gh: ghiaccio, laghi."),
    ("güe", "gue", "La diéresis no existe: seguente, pinguino; gue y gui ya suenan /gwe/, /gwi/."),
    ("ción", "zione", "-ción → -zione: stazione, lezione, informazione."),
    ("ciones", "zioni", "-ciones → -zioni: le stazioni, le lezioni."),
    ("cción", "zione", "-cción → -zione: azione, lezione, direzione."),
    ("sión", "sione", "-sión → -sione: televisione, decisione, occasione."),
    ("dad", "tà", "-dad → -tà (con tilde): città, università, libertà, età."),
    ("tud", "tù", "-tud → -tù (con tilde): virtù, gioventù, schiavitù."),
    ("aje", "aggio", "-aje → -aggio: viaggio, messaggio, coraggio, paesaggio."),
    ("ble", "bile", "-ble → -bile: possibile, responsabile, incredibile."),
    ("dor", "tore", "-dor → -tore: giocatore, lavoratore, compratore."),
    ("y", "i", "La y como vocal o semivocal se escribe i: io, noi, lei, Maiorca."),
    ("ph", "f", "Ph → f: filosofia, fotografia, telefono."),
    ("th", "t", "Th → t: teatro, tema, teoria."),
    ("k", "ch", "La k casi no se usa: ante e/i es ch (chilo, chilometro)."),
    ("ct", "tt", "Ct → tt: atto, dottore, ottobre, effetto."),
    ("pt", "tt", "Pt → tt: settembre, concetto, adatto."),
    ("bs", "ss", "Bs → ss: assoluto, assurdo, osservare."),
    ("dm", "mm", "Dm → mm: ammirare, amministrare."),
    ("dv", "vv", "Dv → vv: avverbio, avvertire, avvento."),
    ("gm", "mm", "Gm → mm: frammento."),
    ("mn", "nn", "Mn → nn: colonna, inno, alunno."),
    ("ns", "s", "Ns ante consonante → s: trasporto, istituto, costante."),
    ("x", "ss", "La x entre vocales suele ser ss: prossimo, massimo, Messico."),
    ("ex", "es", "Ex- ante vocal → es-: esame, esempio, esatto (y exc- → ecc-: eccellente)."),
    ("es", "s", "Al principio, es + consonante → s: scuola, studiare, Spagna, stella."),
    ("ue", "uo", "El diptongo ue suele ser uo: buono, nuovo, fuoco, scuola."),
    ("ie", "e", "El diptongo ie suele ser e: tempo, terra, festa, ferro."),
    ("h", "f", "Muchas h iniciales vienen de f latina: fare, figlio, farina, ferro, fumo."),
    ("h", "", "La h muda española desaparece: ora, uomo, storia, ospedale (solo ho, hai, ha, hanno)."),
    ("cl", "chi", "Cl latino → chi: chiave, chiaro, chiesa, chiamare."),
    ("pl", "pi", "Pl latino → pi: piazza, pieno, piatto, piangere."),
    ("fl", "fi", "Fl latino → fi: fiore, fiamma, fiume."),
    ("bl", "bi", "Bl → bi: bianco, biondo."),
    ("b", "v", "Muchas b entre vocales son v en italiano: cavallo, avere, dovere, scrivere."),
    ("z", "zz", "La z entre vocales suele ser doble: piazza, pizza, bellezza, ragazzo."),
]
