# -*- coding: utf-8 -*-
"""Datos de transferencia español → portugués (Brasil) para el motor de diagnóstico.

Pensado para un hablante de español rioplatense que aprende portugués de
Brasil.  Lo usa docs/js/diagnosi.js (vía data/bank.json, claves esIt,
falsi y spelling) para reconocer una palabra española que se coló en una
respuesta y explicar cómo se dice en portugués.

- ES_IT:    forma española (minúsculas, sin tildes; la ñ se conserva) →
            (portugués, nota).  Varias traducciones van separadas por « / ».
            El nombre ES_IT se mantiene por compatibilidad con el motor.
- FALSI:    palabra PORTUGUESA que parece española → (qué significa en
            español, qué quería decir probablemente el alumno en portugués,
            nota).  Son los heterosemánticos de la bibliografía de PFE.
- SPELLING: correspondencias ortográficas (patrón_es, patrón_pt,
            explicación): el motor prueba el reemplazo sobre la palabra que
            escribió el alumno y, si da la esperada, la marca como grafía
            «a la española».

Las notas están en español rioplatense (voseo) y tienen como máximo unos
120 caracteres.  Las claves de varias palabras («me gusta», «hay que»…)
representan estructuras.  Solo entran palabras que se escriben distinto en
portugués (o que cambian de sentido): la clave nunca es igual a la forma
portuguesa esperada, salvo en las que el portugués usa con otro valor.
"""

ES_IT = {}

# ---------------------------------------------------------------------------
# Artículos, contracciones y preposiciones
# ---------------------------------------------------------------------------
ES_IT.update({
    "el": ("o / ele", "Artículo: o (o livro). «Él» pronombre = ele."),
    "la": ("a", "Artículo femenino: a (a casa). Pronombre objeto: a (vi-a) o, en el habla, ela."),
    "los": ("os", "Los = os: os livros. Pronombre: os (vi-os) o, en el habla, eles."),
    "las": ("as", "Las = as: as casas."),
    "lo": ("o", "Pronombre: o (eu o vi) o, en el habla, ele (vi ele). «Lo bueno» = o bom."),
    "un": ("um", "Un = um, con m final: um livro, um amigo."),
    "unos": ("uns", "Unos = uns: uns amigos."),
    "unas": ("umas", "Unas = umas: umas amigas."),
    "al": ("ao", "a + o = ao: vou ao mercado. «Al llegar» = ao chegar."),
    "del": ("do", "de + o = do: o livro do professor."),
    "en el": ("no", "em + o = no: estou no Rio. La contracción es obligatoria."),
    "en la": ("na", "em + a = na: moro na praia. Nunca «em a»."),
    "en los": ("nos", "em + os = nos: nos domingos."),
    "en las": ("nas", "em + as = nas: nas férias."),
    "de la": ("da", "de + a = da: a casa da Maria."),
    "de los": ("dos", "de + os = dos: o carro dos meus pais."),
    "de las": ("das", "de + as = das: a cor das flores."),
    "por el": ("pelo", "por + o = pelo: passei pelo centro."),
    "por la": ("pela", "por + a = pela: andei pela praia."),
    "a la": ("à", "a + a = à (crase): vou à praia, às três."),
    "a las": ("às", "a + as = às: às oito horas."),
    "en un": ("num / em um", "em + um = num (habla y escrita), o em um: num bar de Lapa."),
    "en una": ("numa / em uma", "em + uma = numa o em uma: numa praia de Búzios."),
    "en": ("em", "En = em (con m final). Con artículo se contrae: no, na, nos, nas."),
    "con": ("com", "Con = com, con m: com você. Y conmigo = comigo, con nosotros = conosco."),
    "sin": ("sem", "Sin = sem: café sem açúcar."),
    "hasta": ("até", "Hasta = até (con tilde): até amanhã, até o fim."),
    "desde": ("desde / a partir de / de", "Desde existe; «desde las 8» = a partir das 8; «desde Río» = do Rio."),
    "hacia": ("para / em direção a", "Hacia = para o em direção a: foi para o centro."),
    "segun": ("segundo / conforme / de acordo com", "Según = segundo o de acordo com: segundo o jornal."),
    "sobre": ("sobre / em cima de / envelope", "Sobre el tema = sobre; encima de = em cima de; el sobre (carta) = o envelope."),
    "bajo": ("sob / debaixo de / baixo", "Bajo (preposición) = sob, debaixo de; bajo (altura) = baixo."),
    "tras": ("após / depois de / atrás de", "Tras = após o depois de; detrás = atrás de."),
    "ante": ("diante de / perante", "Ante = diante de o perante (formal)."),
    "excepto": ("exceto / menos / fora", "Excepto = exceto (sin p) o menos: todos, menos ele."),
    "incluso": ("inclusive / até / mesmo", "Incluso = até, mesmo, inclusive: até ele veio."),
    "junto a": ("junto de / ao lado de", "Junto a = ao lado de, junto de."),
    "cerca": ("perto / cerca", "Cerca de (lugar) = perto de. «Cerca» en portugués = valla, o «cerca de» = aproximadamente."),
    "cerca de": ("perto de / cerca de", "Cerca de un lugar = perto de; cerca de 10 (aprox.) = cerca de 10."),
    "lejos": ("longe", "Lejos = longe: fica longe daqui."),
    "encima": ("em cima", "Encima = em cima (separado): em cima da mesa."),
    "debajo": ("embaixo / debaixo", "Debajo = embaixo o debaixo: embaixo da cama."),
    "delante": ("na frente / diante", "Delante de = na frente de, diante de."),
    "detras": ("atrás", "Detrás de = atrás de: atrás da porta."),
    "adentro": ("dentro", "Adentro = dentro: fica lá dentro."),
    "afuera": ("fora / lá fora", "Afuera = fora, lá fora."),
    "fuera": ("fora", "Fuera = fora: fora de casa."),
    "arriba": ("em cima / lá em cima", "Arriba = em cima, lá em cima; subir = subir."),
    "abajo": ("embaixo / lá embaixo", "Abajo = embaixo, lá embaixo."),
    "alrededor": ("em volta / ao redor", "Alrededor de = em volta de, ao redor de."),
    "enfrente": ("em frente", "Enfrente de = em frente a / de."),
    "adelante": ("em frente / adiante", "¡Adelante! = em frente!, pode entrar!"),
    "atras": ("atrás / para trás", "Para atrás = para trás."),
    "entre": ("entre", ""),
    "mediante": ("mediante / por meio de", ""),
    "durante": ("durante", ""),
})

# ---------------------------------------------------------------------------
# Pronombres, posesivos, demostrativos, indefinidos
# ---------------------------------------------------------------------------
ES_IT.update({
    "yo": ("eu", "Yo = eu: eu sou argentino."),
    "tu": ("você / tu / seu, sua", "Tú/vos = você (verbo en 3.ª) o tu. Tu (posesivo) = seu, sua o teu, tua."),
    "vos": ("você / tu", "Vos = você, con el verbo en 3.ª persona: você é, você tem."),
    "usted": ("o senhor / a senhora / você", "Usted = o senhor, a senhora (formal) o você."),
    "ustedes": ("vocês / os senhores", "Ustedes = vocês, con verbo en 3.ª plural: vocês são."),
    "ella": ("ela", "Ella = ela."),
    "ello": ("isso", "Ello = isso: por isso."),
    "nosotros": ("nós / a gente", "Nosotros = nós; en el habla, a gente (con verbo en singular)."),
    "nosotras": ("nós / a gente", "Nosotras = nós o a gente."),
    "vosotros": ("vocês", "Vosotros = vocês."),
    "ellos": ("eles", "Ellos = eles."),
    "ellas": ("elas", "Ellas = elas."),
    "me": ("me", ""),
    "te": ("te / você / chá", "Te (pronombre) = te; el té = o chá."),
    "nos": ("nos / a gente", "Nos = nos (nos vemos = a gente se vê)."),
    "le": ("lhe / para ele / para ela", "Le = lhe (formal); en el habla, para ele / para ela: dei para ela."),
    "les": ("lhes / para eles", "Les = lhes (formal) o para eles / para elas."),
    "mi": ("meu / minha / mim", "Mi = meu, minha (con artículo: o meu livro). Para mí = para mim."),
    "mis": ("meus / minhas", "Mis = meus, minhas: os meus pais."),
    "tus": ("seus / suas / teus / tuas", "Tus = seus, suas (de você) o teus, tuas."),
    "su": ("seu / sua / dele / dela", "Su = seu, sua; si es «de él/ella», mejor dele / dela."),
    "sus": ("seus / suas / deles / delas", "Sus = seus, suas o deles / delas."),
    "mio": ("meu", "Mío = meu: é meu."),
    "mia": ("minha", "Mía = minha, con nh."),
    "mios": ("meus", ""),
    "mias": ("minhas", ""),
    "tuyo": ("seu / teu", "Tuyo = seu (de você) o teu."),
    "tuya": ("sua / tua", ""),
    "suyo": ("seu / dele / dela", "Suyo = seu, o dele / dela para evitar la ambigüedad."),
    "suya": ("sua / dele / dela", ""),
    "nuestro": ("nosso", "Nuestro = nosso, con ss."),
    "nuestra": ("nossa", "Nuestra = nossa, con ss."),
    "nuestros": ("nossos", ""),
    "nuestras": ("nossas", ""),
    "conmigo": ("comigo", "Conmigo = comigo."),
    "contigo": ("com você / contigo", "Contigo = com você (o contigo, con tu)."),
    "consigo": ("consigo / com ele", ""),
    "con nosotros": ("conosco / com a gente", "Con nosotros = conosco (Brasil) o com a gente."),
    "para mi": ("para mim", "Para mí = para mim, con m final."),
    "a mi": ("a mim / para mim", "A mí = a mim: a mim me parece = para mim, acho que…"),
    "este": ("este", ""),
    "esta": ("esta / está", ""),
    "esto": ("isto / isso", "Esto = isto (escrito) o isso (habla)."),
    "eso": ("isso", "Eso = isso, con ss: por isso."),
    "aquello": ("aquilo", "Aquello = aquilo."),
    "ese": ("esse", "Ese = esse, con ss."),
    "esa": ("essa", "Esa = essa."),
    "esos": ("esses", ""),
    "esas": ("essas", ""),
    "estos": ("estes", "Estos = estes."),
    "aquel": ("aquele", "Aquel = aquele."),
    "aquella": ("aquela", ""),
    "aquellos": ("aqueles", ""),
    "aquellas": ("aquelas", ""),
    "en este": ("neste", "em + este = neste."),
    "en esta": ("nesta", ""),
    "en ese": ("nesse", "em + esse = nesse: nesse dia."),
    "en esa": ("nessa", ""),
    "de este": ("deste", "de + este = deste."),
    "de ese": ("desse", "de + esse = desse."),
    "de esa": ("dessa", ""),
    "de aquel": ("daquele", ""),
    "algo": ("algo / alguma coisa", "Algo = alguma coisa (más común) o algo."),
    "nada": ("nada", ""),
    "alguien": ("alguém", "Alguien = alguém (con tilde y m)."),
    "nadie": ("ninguém", "Nadie = ninguém."),
    "alguno": ("algum", "Alguno/algún = algum."),
    "algun": ("algum", "Algún = algum."),
    "alguna": ("alguma", ""),
    "algunos": ("alguns", "Algunos = alguns."),
    "algunas": ("algumas", ""),
    "ninguno": ("nenhum", "Ninguno/ningún = nenhum."),
    "ningun": ("nenhum", "Ningún = nenhum: nenhum problema."),
    "ninguna": ("nenhuma", ""),
    "todo": ("tudo / todo", "Todo (pronombre, «todo esto») = tudo; todo el día = o dia todo / todo o dia."),
    "toda": ("toda", ""),
    "todos": ("todos", ""),
    "cada": ("cada", ""),
    "otro": ("outro", "Otro = outro."),
    "otra": ("outra", ""),
    "otros": ("outros", ""),
    "otras": ("outras", ""),
    "mismo": ("mesmo", "Mismo = mesmo: o mesmo."),
    "misma": ("mesma", ""),
    "cualquier": ("qualquer", "Cualquier = qualquer."),
    "cualquiera": ("qualquer um / qualquer uma", ""),
    "quien": ("quem", "Quien = quem: quem é?"),
    "quienes": ("quem", "Quienes = quem (invariable)."),
    "cual": ("qual", "Cuál = qual."),
    "cuales": ("quais", "Cuáles = quais."),
    "cuanto": ("quanto", "Cuánto = quanto."),
    "cuanta": ("quanta", ""),
    "cuantos": ("quantos", ""),
    "cuantas": ("quantas", ""),
    "que": ("que / o que", "¿Qué? = o que? (o que você quer?)."),
    "lo que": ("o que", "Lo que = o que: o que você disse."),
    "cuyo": ("cujo", "Cuyo = cujo."),
    "cuya": ("cuja", ""),
    "demas": ("demais", "Los demás = os demais, os outros."),
    "ambos": ("ambos / os dois", ""),
    "varios": ("vários", ""),
    "poco": ("pouco", "Poco = pouco."),
    "poca": ("pouca", ""),
    "pocos": ("poucos", ""),
    "mucho": ("muito", "Mucho = muito: muito trabalho."),
    "mucha": ("muita", "Mucha = muita: muita gente."),
    "muchos": ("muitos", ""),
    "muchas": ("muitas", ""),
    "demasiado": ("demais / demasiado", "Demasiado = demais (detrás): é caro demais."),
    "bastante": ("bastante", ""),
})

# ---------------------------------------------------------------------------
# Adverbios, conjunciones y marcadores
# ---------------------------------------------------------------------------
ES_IT.update({
    "muy": ("muito", "Muy = muito: muito bom. «Muy» no existe en portugués."),
    "mas": ("mais / mas", "Más = mais (con i). En portugués «mas» es «pero»."),
    "menos": ("menos", ""),
    "pero": ("mas / porém", "Pero = mas: é caro, mas é bom. «Pero» no existe en portugués."),
    "sino": ("mas / e sim", "Sino = mas sim, e sim: não é azul, e sim verde."),
    "y": ("e", "Y = e: pão e manteiga."),
    "o": ("ou", "O (conjunción) = ou: café ou chá."),
    "ni": ("nem", "Ni = nem: nem eu."),
    "tambien": ("também", "También = também (con m final y tilde)."),
    "tampoco": ("também não / tampouco", "Tampoco = também não: eu também não."),
    "si": ("se / sim", "Si (condicional) = se: se chover; sí = sim."),
    "no": ("não", "No = não, con tilde nasal: não sei."),
    "porque": ("porque", ""),
    "por que": ("por que", ""),
    "pues": ("pois / então", "Pues = pois o então."),
    "entonces": ("então", "Entonces = então."),
    "luego": ("depois / logo", "Luego (después) = depois. Ojo: «logo» = enseguida."),
    "despues": ("depois", "Después = depois: depois do almoço."),
    "antes": ("antes", ""),
    "ahora": ("agora", "Ahora = agora."),
    "ahorita": ("agorinha / já", ""),
    "hoy": ("hoje", "Hoy = hoje."),
    "ayer": ("ontem", "Ayer = ontem."),
    "anteayer": ("anteontem", "Anteayer = anteontem."),
    "mañana": ("amanhã / manhã", "Mañana (día) = amanhã; la mañana = a manhã."),
    "pasado mañana": ("depois de amanhã", ""),
    "anoche": ("ontem à noite", "Anoche = ontem à noite."),
    "temprano": ("cedo", "Temprano = cedo."),
    "tarde": ("tarde", ""),
    "pronto": ("logo / em breve / cedo", "Pronto (en breve) = logo, em breve. «Pronto» en portugués = listo."),
    "enseguida": ("logo / já / em seguida", "Enseguida = já, logo."),
    "ya": ("já", "Ya = já: já comi."),
    "todavia": ("ainda", "Todavía = ainda. «Todavia» en portugués = sin embargo."),
    "aun": ("ainda / até", "Aún = ainda; aun (incluso) = até, mesmo."),
    "siempre": ("sempre", "Siempre = sempre."),
    "nunca": ("nunca", ""),
    "jamas": ("jamais", "Jamás = jamais."),
    "a veces": ("às vezes", "A veces = às vezes (con crase)."),
    "casi": ("quase", "Casi = quase."),
    "solo": ("só / sozinho / somente", "Solo (solamente) = só; solo (sin compañía) = sozinho."),
    "solamente": ("somente / só / apenas", "Solamente = somente, só, apenas."),
    "unicamente": ("unicamente / apenas", ""),
    "aqui": ("aqui", ""),
    "aca": ("aqui / cá", "Acá = aqui; vem cá = vení para acá."),
    "ahi": ("aí", "Ahí = aí."),
    "alli": ("ali / lá", "Allí = ali."),
    "alla": ("lá", "Allá = lá."),
    "donde": ("onde", "Donde = onde."),
    "adonde": ("aonde / para onde", "Adónde = aonde, para onde."),
    "cuando": ("quando", "Cuando = quando."),
    "como": ("como", ""),
    "asi": ("assim", "Así = assim."),
    "bien": ("bem", "Bien = bem."),
    "mal": ("mal", ""),
    "mejor": ("melhor", "Mejor = melhor."),
    "peor": ("pior", "Peor = pior."),
    "tan": ("tão", "Tan = tão: tão bonito."),
    "tanto": ("tanto", ""),
    "quizas": ("talvez", "Quizás = talvez."),
    "quiza": ("talvez", ""),
    "tal vez": ("talvez", "Tal vez = talvez (una sola palabra)."),
    "ojala": ("tomara que / oxalá", "Ojalá = tomara que (+ subjuntivo); oxalá es más formal."),
    "claro": ("claro", ""),
    "vale": ("tá bom / beleza / ok", "¡Vale! = tá bom, beleza."),
    "dale": ("beleza / bora / tá bom", "¡Dale! = beleza!, bora!, fechado!"),
    "che": ("ô / cara / meu", "¡Che! = ô, cara (habla)."),
    "bueno": ("bom / bem / então", "Bueno (muletilla) = bom, bem, então."),
    "igual": ("mesmo assim / igual", "Igual (de todos modos) = mesmo assim."),
    "ademas": ("além disso / também", "Además = além disso."),
    "sin embargo": ("no entanto / porém / entretanto", "Sin embargo = no entanto, porém, entretanto."),
    "aunque": ("embora / mesmo que / ainda que", "Aunque = embora (+ subjuntivo) o mesmo que."),
    "mientras": ("enquanto", "Mientras = enquanto."),
    "mientras tanto": ("enquanto isso", ""),
    "por eso": ("por isso", "Por eso = por isso."),
    "o sea": ("ou seja", "O sea = ou seja."),
    "es decir": ("isto é / ou seja", ""),
    "por ejemplo": ("por exemplo", ""),
    "sobre todo": ("sobretudo / principalmente", ""),
    "de repente": ("de repente", ""),
    "de nuevo": ("de novo", "De nuevo = de novo."),
    "otra vez": ("outra vez / de novo", ""),
    "enseguida vuelvo": ("já volto", ""),
    "al fin": ("enfim / finalmente", ""),
    "por fin": ("finalmente / enfim", ""),
    "a lo mejor": ("talvez / de repente", "A lo mejor = talvez (en el habla, «de repente»)."),
    "apenas": ("mal / assim que / apenas", "Apenas (en cuanto) = assim que; apenas (casi no) = mal. «Apenas» en portugués = solo."),
    "recien": ("acabar de / recém", "Recién llegué = acabei de chegar; recién nacido = recém-nascido."),
    "acaso": ("por acaso", ""),
    "encima de": ("em cima de", ""),
    "ojo": ("cuidado / olho", "¡Ojo! = cuidado!, atenção!; el ojo = o olho."),
    "hola": ("oi / olá", "Hola = oi (habla) u olá."),
    "chau": ("tchau", "Chau = tchau."),
    "adios": ("adeus / tchau", "Adiós = tchau; adeus es definitivo."),
    "gracias": ("obrigado / obrigada", "Gracias = obrigado (hombre), obrigada (mujer)."),
    "de nada": ("de nada / por nada", ""),
    "perdon": ("desculpa / perdão / com licença", "Perdón = desculpa; para pasar = com licença."),
    "disculpa": ("desculpa", ""),
    "por favor": ("por favor", ""),
    "buenos dias": ("bom dia", "Buenos días = bom dia (en singular)."),
    "buenas tardes": ("boa tarde", "Buenas tardes = boa tarde."),
    "buenas noches": ("boa noite", "Buenas noches = boa noite."),
    "buenas": ("oi / e aí", ""),
    "que tal": ("tudo bem? / como vai?", "¿Qué tal? = tudo bem?"),
    "como estas": ("como vai? / tudo bem?", ""),
    "encantado": ("prazer / muito prazer", "Encantado = muito prazer."),
    "mucho gusto": ("muito prazer", "Mucho gusto = muito prazer."),
    "hasta luego": ("até logo / até mais", ""),
    "hasta mañana": ("até amanhã", ""),
    "felicidades": ("parabéns / felicidades", "Felicidades (cumpleaños) = parabéns."),
    "feliz cumpleaños": ("feliz aniversário / parabéns", ""),
    "salud": ("saúde", "¡Salud! (brindis, estornudo) = saúde!"),
    "buen provecho": ("bom apetite", ""),
    "suerte": ("sorte / boa sorte", ""),
    "genial": ("legal / ótimo / genial", "¡Genial! = que legal!, ótimo!"),
    "barbaro": ("legal / ótimo / maravilha", "¡Bárbaro! = ótimo!, maravilha!"),
    "copado": ("legal / maneiro", "Copado = legal; en Río, maneiro."),
})

# ---------------------------------------------------------------------------
# Verbos: estructuras y formas conjugadas frecuentes
# ---------------------------------------------------------------------------
ES_IT.update({
    "hay": ("tem / há", "Hay = tem (habla) o há (escrito): tem um bar aqui."),
    "hay que": ("é preciso / tem que", "Hay que = é preciso o tem que + infinitivo."),
    "habia": ("tinha / havia", "Había = tinha (habla) o havia."),
    "hubo": ("houve / teve", "Hubo = houve (o teve, en el habla)."),
    "habra": ("haverá / vai ter", ""),
    "tengo": ("tenho", "Tengo = tenho, con nh."),
    "tenes": ("tem / tens", "Vos tenés = você tem (o tu tens)."),
    "tienes": ("tem / tens", "Tú tienes = você tem / tu tens."),
    "tiene": ("tem", "Tiene = tem: ela tem vinte anos."),
    "tenemos": ("temos", "Tenemos = temos."),
    "tienen": ("têm", "Tienen = têm (con circunflejo, plural de tem)."),
    "tengo que": ("tenho que / preciso", "Tengo que = tenho que o preciso + infinitivo."),
    "tuve": ("tive", "Tuve = tive."),
    "tuvo": ("teve", "Tuvo = teve."),
    "tenia": ("tinha", "Tenía = tinha."),
    "soy": ("sou", "Soy = sou."),
    "sos": ("é / és", "Vos sos = você é (o tu és)."),
    "eres": ("é / és", "Eres = você é / tu és."),
    "es": ("é", "Es = é, con tilde aguda: ele é."),
    "somos": ("somos", ""),
    "son": ("são", "Son = são: eles são."),
    "era": ("era", ""),
    "fue": ("foi", "Fue = foi (de ser y de ir)."),
    "fui": ("fui", ""),
    "fueron": ("foram", "Fueron = foram."),
    "estoy": ("estou / tô", "Estoy = estou (habla: tô)."),
    "estas": ("está / estás", "Estás = você está (o tu estás)."),
    "estamos": ("estamos", ""),
    "estan": ("estão", "Están = estão."),
    "estuve": ("estive", "Estuve = estive."),
    "estuvo": ("esteve", "Estuvo = esteve."),
    "voy": ("vou", "Voy = vou."),
    "vas": ("vai / vais", "Vas = você vai."),
    "va": ("vai", "Va = vai."),
    "vamos": ("vamos / bora", ""),
    "van": ("vão", "Van = vão."),
    "iba": ("ia", "Iba = ia."),
    "voy a": ("vou", "Voy a + infinitivo = vou + infinitivo, sin «a»: vou viajar."),
    "vas a": ("vai", "Vas a comer = você vai comer (sin a)."),
    "va a": ("vai", "Va a llover = vai chover (sin a)."),
    "vamos a": ("vamos / a gente vai", "Vamos a ver = vamos ver (sin a)."),
    "van a": ("vão", "Van a salir = vão sair (sin a)."),
    "hago": ("faço", "Hago = faço, con ç."),
    "hace": ("faz", "Hace = faz; hace dos años = há dois anos / faz dois anos."),
    "hacemos": ("fazemos", ""),
    "hacen": ("fazem", ""),
    "hice": ("fiz", "Hice = fiz."),
    "hizo": ("fez", "Hizo = fez."),
    "hicimos": ("fizemos", ""),
    "hicieron": ("fizeram", ""),
    "hecho": ("feito", "Hecho = feito."),
    "hacer": ("fazer", "Hacer = fazer."),
    "digo": ("digo", ""),
    "dice": ("diz", "Dice = diz."),
    "dicen": ("dizem", "Dicen = dizem."),
    "dije": ("disse", "Dije = disse."),
    "dijo": ("disse", "Dijo = disse."),
    "dijeron": ("disseram", ""),
    "dicho": ("dito", "Dicho = dito."),
    "decir": ("dizer", "Decir = dizer."),
    "puedo": ("posso", "Puedo = posso."),
    "podes": ("pode / podes", "Podés = você pode."),
    "puede": ("pode", "Puede = pode."),
    "pueden": ("podem", "Pueden = podem."),
    "pude": ("pude", ""),
    "pudo": ("pôde", "Pudo = pôde (con circunflejo, ≠ pode)."),
    "poder": ("poder", ""),
    "quiero": ("quero", "Quiero = quero."),
    "queres": ("quer / queres", "Querés = você quer."),
    "quiere": ("quer", "Quiere = quer."),
    "quieren": ("querem", "Quieren = querem."),
    "quise": ("quis", "Quise = quis."),
    "quiso": ("quis", "Quiso = quis."),
    "se": ("sei / se", "Sé (saber) = sei."),
    "sabes": ("sabe / sabes", "Sabés = você sabe."),
    "sabe": ("sabe", ""),
    "supe": ("soube", "Supe = soube."),
    "supo": ("soube", ""),
    "veo": ("vejo", "Veo = vejo."),
    "ves": ("vê / vês", "Ves = você vê."),
    "ve": ("vê", "Ve = vê (con circunflejo)."),
    "ven": ("veem / vem", "Ven (ver) = veem; ¡ven! (venir) = vem!, vem cá!"),
    "vi": ("vi", ""),
    "vio": ("viu", "Vio = viu."),
    "vieron": ("viram", ""),
    "visto": ("visto", ""),
    "vengo": ("venho", "Vengo = venho."),
    "viene": ("vem", "Viene = vem."),
    "vienen": ("vêm", "Vienen = vêm (con circunflejo)."),
    "vine": ("vim", "Vine = vim."),
    "vino": ("veio / vinho", "Vino (venir) = veio; el vino = o vinho."),
    "venir": ("vir", "Venir = vir."),
    "doy": ("dou", "Doy = dou."),
    "da": ("dá", "Da (dar) = dá, con tilde; «da» sin tilde es de + a."),
    "di": ("dei", "Di (dar) = dei."),
    "dio": ("deu", "Dio = deu."),
    "pongo": ("ponho", "Pongo = ponho."),
    "pone": ("põe", "Pone = põe."),
    "puse": ("pus", "Puse = pus."),
    "puso": ("pôs", "Puso = pôs."),
    "poner": ("pôr / colocar", "Poner = pôr (con circunflejo) o colocar."),
    "salgo": ("saio", "Salgo = saio."),
    "sale": ("sai", "Sale = sai."),
    "salir": ("sair", "Salir = sair."),
    "traigo": ("trago", "Traigo = trago."),
    "trae": ("traz", "Trae = traz."),
    "traje": ("trouxe / terno", "Traje (traer) = trouxe; el traje = o terno."),
    "trajo": ("trouxe", "Trajo = trouxe."),
    "traer": ("trazer", "Traer = trazer."),
    "oigo": ("ouço", "Oigo = ouço."),
    "oye": ("ouve", "Oye = ouve. ¡Oíme! = escuta!, olha!"),
    "oir": ("ouvir", "Oír = ouvir."),
    "leo": ("leio", "Leo = leio."),
    "lee": ("lê", "Lee = lê."),
    "leer": ("ler", "Leer = ler."),
    "creo": ("acho / creio", "Creo que = acho que (habla)."),
    "creo que": ("acho que", "Creo que sí = acho que sim."),
    "crei": ("achei / pensei", ""),
    "pido": ("peço", "Pido = peço."),
    "pide": ("pede", "Pide = pede."),
    "duermo": ("durmo", "Duermo = durmo."),
    "duerme": ("dorme", "Duerme = dorme."),
    "dormir": ("dormir", ""),
    "prefiero": ("prefiro", "Prefiero = prefiro."),
    "siento": ("sinto", "Siento = sinto."),
    "lo siento": ("sinto muito / desculpa", "Lo siento = sinto muito."),
    "sigo": ("sigo", ""),
    "sigue": ("segue", "Sigue = segue."),
    "seguir": ("seguir / continuar", ""),
    "pienso": ("penso / acho", "Pienso = penso; «pienso que» = acho que."),
    "piensa": ("pensa", ""),
    "entiendo": ("entendo", "Entiendo = entendo."),
    "entiende": ("entende", ""),
    "empiezo": ("começo", "Empiezo = começo."),
    "empieza": ("começa", "Empieza = começa."),
    "empezar": ("começar", "Empezar = começar."),
    "comienzo": ("começo / início", ""),
    "cierro": ("fecho", "Cierro = fecho."),
    "cierra": ("fecha", "Cierra = fecha."),
    "cerrar": ("fechar", "Cerrar = fechar."),
    "vuelvo": ("volto", "Vuelvo = volto."),
    "vuelve": ("volta", "Vuelve = volta."),
    "volver": ("voltar", "Volver = voltar."),
    "puedes": ("pode / podes", ""),
    "juego": ("jogo / brinco / brincadeira", "Juego (deporte) = jogo; (niños) = brinco, brincadeira."),
    "juega": ("joga / brinca", ""),
    "jugar": ("jogar / brincar", "Jugar un deporte = jogar; jugar (niños) = brincar."),
    "cuesta": ("custa", "Cuesta = custa."),
    "costar": ("custar", "Costar = custar."),
    "encuentro": ("encontro", "Encuentro = encontro."),
    "encontrar": ("encontrar / achar", ""),
    "muestro": ("mostro", ""),
    "recuerdo": ("lembro / lembrança", "Recuerdo = lembro (verbo) o lembrança (sustantivo)."),
    "recordar": ("lembrar", "Recordar = lembrar (de)."),
    "acordarse": ("lembrar-se / lembrar", "Acordarse de = lembrar de. «Acordar» en portugués = despertarse."),
    "me acuerdo": ("lembro / me lembro", "Me acuerdo = (eu) lembro."),
    "despertarse": ("acordar", "Despertarse = acordar: acordo às sete."),
    "me despierto": ("acordo", "Me despierto = acordo (sin pronombre)."),
    "levantarse": ("levantar-se / levantar", ""),
    "me levanto": ("me levanto / levanto", ""),
    "acostarse": ("deitar-se / ir dormir", "Acostarse = deitar-se, ir dormir."),
    "me acuesto": ("me deito / vou dormir", ""),
    "ducharse": ("tomar banho", "Ducharse = tomar banho."),
    "bañarse": ("tomar banho", "Bañarse = tomar banho (en el mar: tomar banho de mar)."),
    "vestirse": ("vestir-se / se vestir", ""),
    "sentarse": ("sentar-se / sentar", ""),
    "llamarse": ("chamar-se", "Llamarse = chamar-se: me chamo Ana."),
    "me llamo": ("me chamo / chamo-me / meu nome é", "Me llamo = me chamo o meu nome é."),
    "llamar": ("chamar / ligar", "Llamar por teléfono = ligar (para)."),
    "llamo": ("chamo / ligo", ""),
    "llegar": ("chegar", "Llegar = chegar."),
    "llego": ("chego", "Llego = chego."),
    "llega": ("chega", ""),
    "llegue": ("cheguei", "Llegué = cheguei."),
    "llego a": ("chego em / chego a", ""),
    "llevar": ("levar", "Llevar = levar."),
    "llevo": ("levo", ""),
    "lleva": ("leva", ""),
    "llover": ("chover", "Llover = chover."),
    "llueve": ("chove", "Llueve = chove."),
    "llorar": ("chorar", "Llorar = chorar."),
    "llenar": ("encher", "Llenar = encher."),
    "gustar": ("gostar", "Gustar = gostar de; la persona es el sujeto: eu gosto de café."),
    "me gusta": ("gosto de", "Me gusta X = (eu) gosto de X: gosto de samba."),
    "me gustan": ("gosto de", "Me gustan los libros = gosto dos livros (el verbo no pasa a plural)."),
    "te gusta": ("você gosta de", "¿Te gusta? = você gosta?"),
    "le gusta": ("gosta de", "Le gusta = ele / ela gosta de."),
    "nos gusta": ("gostamos de / a gente gosta de", ""),
    "les gusta": ("gostam de", ""),
    "me gustaria": ("gostaria de", "Me gustaría = (eu) gostaria de."),
    "me encanta": ("adoro / amo", "Me encanta = adoro."),
    "encanta": ("adora", ""),
    "me duele": ("dói / está doendo", "Me duele la cabeza = estou com dor de cabeça / minha cabeça dói."),
    "necesitar": ("precisar", "Necesitar = precisar de: preciso de ajuda."),
    "necesito": ("preciso", "Necesito = preciso (de)."),
    "necesita": ("precisa", ""),
    "trabajar": ("trabalhar", "Trabajar = trabalhar (lh)."),
    "trabaja": ("trabalha", ""),
    "vivir": ("morar / viver", "Vivir (residir) = morar: moro em Niterói."),
    "vivo": ("moro / vivo", "Vivo en = moro em."),
    "vive": ("mora / vive", ""),
    "viven": ("moram / vivem", ""),
    "hablar": ("falar", "Hablar = falar."),
    "hablo": ("falo", "Hablo = falo."),
    "habla": ("fala", "Habla = fala."),
    "hablamos": ("falamos", ""),
    "hablan": ("falam", ""),
    "hable": ("falei", "Hablé = falei."),
    "hablo portugues": ("falo português", ""),
    "escuchar": ("escutar / ouvir", "Escuchar = escutar u ouvir."),
    "escucho": ("escuto / ouço", ""),
    "mirar": ("olhar / ver / assistir", "Mirar = olhar; mirar la tele = ver / assistir televisão."),
    "miro": ("olho / vejo", ""),
    "mira": ("olha", "¡Mirá! = olha!"),
    "mira vos": ("olha só", ""),
    "buscar": ("procurar / buscar", "Buscar (algo perdido) = procurar; ir a buscar a alguien = buscar."),
    "busco": ("procuro", "Busco = procuro."),
    "tomar": ("tomar / beber / pegar", "Tomar el colectivo = pegar o ônibus."),
    "agarrar": ("pegar", "Agarrar = pegar."),
    "coger": ("pegar", ""),
    "tirar": ("jogar fora / atirar", "Tirar (a la basura) = jogar fora."),
    "tiro": ("jogo fora", ""),
    "sacar": ("tirar", "Sacar = tirar: tirar uma foto, tirar a roupa."),
    "saco": ("tiro / paletó / casaco", "Saco (verbo) = tiro; el saco = o paletó."),
    "quitar": ("tirar", "Quitar = tirar."),
    "dejar": ("deixar", "Dejar = deixar."),
    "dejo": ("deixo", ""),
    "echar": ("jogar / botar / pôr", ""),
    "cambiar": ("mudar / trocar", "Cambiar = mudar (de idea) o trocar (una cosa por otra)."),
    "mudarse": ("mudar-se / mudar", "Mudarse = mudar(-se): mudei para o Rio."),
    "esperar": ("esperar", ""),
    "espero": ("espero", ""),
    "conocer": ("conhecer", "Conocer = conhecer (nh)."),
    "conozco": ("conheço", "Conozco = conheço."),
    "conoce": ("conhece", ""),
    "parecer": ("parecer", ""),
    "parece": ("parece", ""),
    "me parece": ("acho / me parece", "Me parece que = acho que."),
    "ofrecer": ("oferecer", "Ofrecer = oferecer."),
    "ofrezco": ("ofereço", ""),
    "agradecer": ("agradecer", ""),
    "nacer": ("nascer", "Nacer = nascer (sc)."),
    "naci": ("nasci", "Nací = nasci."),
    "nacio": ("nasceu", "Nació = nasceu."),
    "crecer": ("crescer", "Crecer = crescer (sc)."),
    "creci": ("cresci", ""),
    "merecer": ("merecer", ""),
    "desaparecer": ("desaparecer", ""),
    "conducir": ("dirigir", "Conducir (auto) = dirigir."),
    "manejar": ("dirigir", "Manejar (auto) = dirigir."),
    "manejo": ("dirijo", "Manejo = dirijo."),
    "traducir": ("traduzir", "Traducir = traduzir."),
    "traduzco": ("traduzo", "Traduzco = traduzo."),
    "producir": ("produzir", "Producir = produzir."),
    "construir": ("construir", ""),
    "construyo": ("construo", "Construyo = construo."),
    "incluir": ("incluir", ""),
    "incluye": ("inclui", "Incluye = inclui."),
    "destruir": ("destruir", ""),
    "huir": ("fugir", "Huir = fugir."),
    "oler": ("cheirar", "Oler = cheirar."),
    "huele": ("cheira", "Huele = cheira."),
    "morir": ("morrer", "Morir = morrer (rr)."),
    "murio": ("morreu", "Murió = morreu."),
    "muerto": ("morto", "Muerto = morto."),
    "mover": ("mover / mexer", ""),
    "mueve": ("move / mexe", ""),
    "soler": ("costumar", "Soler = costumar: costumo acordar cedo."),
    "suelo": ("costumo / chão", "Suelo (soler) = costumo; el suelo = o chão."),
    "suele": ("costuma", "Suele = costuma."),
    "acabar de": ("acabar de", ""),
    "acabo de": ("acabei de", "Acabo de llegar = acabei de chegar (en pasado)."),
    "volver a": ("voltar a / de novo", "Volver a hacer = fazer de novo o voltar a fazer."),
    "ponerse": ("ficar / pôr", "Ponerse (nervioso) = ficar nervoso."),
    "me puse": ("fiquei", "Me puse triste = fiquei triste."),
    "quedarse": ("ficar", "Quedarse = ficar: fiquei em casa."),
    "me quedo": ("fico", "Me quedo = fico."),
    "se quedo": ("ficou", ""),
    "quedar": ("ficar", "Quedar (ubicarse) = ficar: fica perto da praia."),
    "queda": ("fica", "¿Dónde queda? = onde fica?"),
    "enojarse": ("ficar com raiva / zangar-se / ficar bravo", "Enojarse = ficar com raiva, ficar bravo."),
    "enojado": ("bravo / com raiva / zangado", ""),
    "enfermarse": ("ficar doente", "Enfermarse = ficar doente."),
    "casarse": ("casar / casar-se", "Casarse con = casar com."),
    "divertirse": ("divertir-se / se divertir", ""),
    "aburrirse": ("ficar entediado / entediar-se", ""),
    "preocuparse": ("preocupar-se / se preocupar", ""),
    "equivocarse": ("errar / enganar-se / se enganar", "Equivocarse = errar, enganar-se."),
    "me equivoque": ("errei / me enganei", ""),
    "olvidar": ("esquecer", "Olvidar = esquecer."),
    "olvide": ("esqueci", "Olvidé = esqueci."),
    "me olvide": ("esqueci", "Me olvidé = esqueci (sin pronombre)."),
    "apurarse": ("apressar-se / correr", "¡Apurate! = anda logo!, corre!"),
    "apurate": ("anda logo / corre", ""),
    "enviar": ("enviar / mandar", ""),
    "mandar": ("mandar", ""),
    "pagar": ("pagar", ""),
    "pague": ("paguei", "Pagué = paguei."),
    "comprar": ("comprar", ""),
    "compre": ("comprei", "Compré = comprei."),
    "vender": ("vender", ""),
    "alquilar": ("alugar", "Alquilar = alugar."),
    "alquiler": ("aluguel", "El alquiler = o aluguel."),
    "cobrar": ("cobrar", ""),
    "ahorrar": ("economizar / poupar", "Ahorrar = economizar, poupar."),
    "gastar": ("gastar", ""),
    "cocinar": ("cozinhar", "Cocinar = cozinhar."),
    "cocino": ("cozinho", ""),
    "almorzar": ("almoçar", "Almorzar = almoçar."),
    "cenar": ("jantar", "Cenar = jantar. «Cena» en portugués es escena."),
    "ceno": ("janto", ""),
    "desayunar": ("tomar café da manhã", "Desayunar = tomar café (da manhã)."),
    "merendar": ("lanchar", "Merendar = lanchar."),
    "beber": ("beber / tomar", ""),
    "comer": ("comer", ""),
    "probar": ("provar / experimentar", "Probar = provar (comida) o experimentar (ropa)."),
    "pruebo": ("provo / experimento", ""),
    "elegir": ("escolher", "Elegir = escolher."),
    "elijo": ("escolho", "Elijo = escolho."),
    "decidir": ("decidir", ""),
    "intentar": ("tentar", "Intentar = tentar."),
    "intento": ("tento / tentativa", ""),
    "tratar de": ("tentar", "Tratar de = tentar: tento dormir."),
    "lograr": ("conseguir", "Lograr = conseguir."),
    "logre": ("consegui", ""),
    "conseguir": ("conseguir", ""),
    "ganar": ("ganhar", "Ganar = ganhar."),
    "gane": ("ganhei", ""),
    "perder": ("perder", ""),
    "pierdo": ("perco", "Pierdo = perco."),
    "perdi": ("perdi", ""),
    "enseñar": ("ensinar / mostrar", "Enseñar (clases) = ensinar; (mostrar) = mostrar."),
    "aprender": ("aprender", ""),
    "estudiar": ("estudar", "Estudiar = estudar."),
    "estudio": ("estudo", "Estudio = estudo."),
    "estudia": ("estuda", ""),
    "escribir": ("escrever", "Escribir = escrever."),
    "escribo": ("escrevo", "Escribo = escrevo."),
    "escribe": ("escreve", ""),
    "escrito": ("escrito", ""),
    "abrir": ("abrir", ""),
    "abierto": ("aberto", "Abierto = aberto."),
    "romper": ("quebrar", "Romper = quebrar (el vidrio se quebró = o vidro quebrou)."),
    "roto": ("quebrado", "Roto = quebrado."),
    "arreglar": ("consertar / arrumar", "Arreglar (reparar) = consertar; (ordenar) = arrumar."),
    "limpiar": ("limpar", "Limpiar = limpar."),
    "lavar": ("lavar", ""),
    "planchar": ("passar roupa", "Planchar = passar (a roupa)."),
    "ayudar": ("ajudar", "Ayudar = ajudar."),
    "ayudo": ("ajudo", ""),
    "ayuda": ("ajuda", ""),
    "preguntar": ("perguntar", "Preguntar = perguntar."),
    "pregunto": ("pergunto", ""),
    "pregunta": ("pergunta", ""),
    "contestar": ("responder", "Contestar = responder. «Contestar» en portugués es cuestionar."),
    "responder": ("responder", ""),
    "caminar": ("caminhar / andar", "Caminar = caminhar o andar."),
    "camino": ("caminho / caminhada", ""),
    "correr": ("correr", ""),
    "nadar": ("nadar", ""),
    "bailar": ("dançar", "Bailar = dançar."),
    "bailo": ("danço", ""),
    "cantar": ("cantar", ""),
    "viajar": ("viajar", ""),
    "viaje": ("viagem / viajei", "El viaje = a viagem (femenino); viajé = viajei."),
    "visitar": ("visitar", ""),
    "pasear": ("passear", "Pasear = passear (ss)."),
    "paseo": ("passeio", "Paseo = passeio."),
    "subir": ("subir", ""),
    "bajar": ("descer / baixar", "Bajar = descer; bajar (un archivo) = baixar."),
    "bajo del": ("desço do", ""),
    "entrar": ("entrar", ""),
    "pasar": ("passar", "Pasar = passar (ss)."),
    "paso": ("passo", ""),
    "pasa": ("passa / acontece", "¿Qué pasa? = o que está acontecendo?, o que houve?"),
    "que pasa": ("o que houve / o que foi", ""),
    "pasar por": ("passar por", ""),
    "suceder": ("acontecer", "Suceder = acontecer."),
    "ocurrir": ("acontecer / ocorrer", "Ocurrir = acontecer."),
    "cruzar": ("atravessar / cruzar", "Cruzar la calle = atravessar a rua."),
    "doblar": ("virar / dobrar", "Doblar a la derecha = virar à direita."),
    "girar": ("virar / girar", ""),
    "estacionar": ("estacionar", ""),
    "reservar": ("reservar", ""),
    "invitar": ("convidar", "Invitar = convidar."),
    "invito": ("convido", ""),
    "prestar": ("emprestar", "Prestar (dar prestado) = emprestar."),
    "pedir prestado": ("pedir emprestado", ""),
    "devolver": ("devolver", ""),
    "regalar": ("dar de presente", "Regalar = dar de presente."),
    "cumplir": ("cumprir / fazer (anos)", "Cumplir años = fazer aniversário; cumplo 30 = faço 30 anos."),
    "cumplo": ("cumpro / faço", ""),
    "festejar": ("comemorar / festejar", "Festejar = comemorar."),
    "celebrar": ("comemorar / celebrar", ""),
    "firmar": ("assinar", "Firmar (un documento) = assinar. «Firmar» en portugués = afirmar, fijar."),
    "firmo": ("assino", ""),
    "sonar": ("soar / tocar", "Sonar (teléfono) = tocar."),
    "soñar": ("sonhar", "Soñar con = sonhar com."),
    "sueño": ("sonho / sono", "El sueño (lo que soñás) = o sonho; tener sueño = estar com sono."),
    "enamorarse": ("apaixonar-se / se apaixonar", "Enamorarse de = apaixonar-se por."),
    "salir con": ("sair com / namorar", "Salir con alguien (novios) = namorar alguém."),
    "extrañar": ("sentir falta de / sentir saudade de", "Te extraño = sinto sua falta, estou com saudade de você."),
    "extraño": ("sinto falta / estranho", "Te extraño = sinto saudade; extraño (raro) = estranho."),
    "odiar": ("odiar", ""),
    "odio": ("odeio / ódio", "Odio (verbo) = odeio."),
    "querer": ("querer / amar / gostar", "Te quiero = te amo o gosto de você."),
    "te quiero": ("te amo / gosto muito de você", ""),
    "besar": ("beijar", "Besar = beijar."),
    "beso": ("beijo", "Beso = beijo."),
    "abrazar": ("abraçar", "Abrazar = abraçar."),
    "abrazo": ("abraço", "Abrazo = abraço."),
    "caer": ("cair", "Caer = cair."),
    "caigo": ("caio", ""),
    "cayo": ("caiu", "Cayó = caiu."),
    "sentir": ("sentir", ""),
    "reir": ("rir", "Reír = rir."),
    "rio": ("rio / riu", "Río = rio; rió = riu."),
    "sonreir": ("sorrir", "Sonreír = sorrir."),
    "cuidar": ("cuidar", "Cuidar a alguien = cuidar de alguém."),
    "valer": ("valer", ""),
    "vale la pena": ("vale a pena", ""),
    "caber": ("caber", ""),
    "quepo": ("caibo", "Quepo = caibo."),
    "obtener": ("obter", "Obtener = obter."),
    "mantener": ("manter", "Mantener = manter."),
    "contener": ("conter", ""),
    "proponer": ("propor", "Proponer = propor."),
    "suponer": ("supor", "Suponer = supor."),
    "componer": ("compor", ""),
    "disponer": ("dispor", ""),
    "prever": ("prever", ""),
    "intervenir": ("intervir", "Intervenir = intervir."),
    "convenir": ("convir", ""),
    "conviene": ("convém", ""),
    "prevenir": ("prevenir", ""),
    "exigir": ("exigir", ""),
    "sugerir": ("sugerir", ""),
    "requerir": ("requerer", ""),
    "adquirir": ("adquirir", ""),
    "atender": ("atender", ""),
    "asistir": ("assistir", "Asistir = assistir (ss); asistir a un partido = assistir ao jogo."),
    "asisti": ("assisti", ""),
    "ver la tele": ("ver televisão / assistir televisão", ""),
    "aprovechar": ("aproveitar", "Aprovechar = aproveitar."),
    "aprovecho": ("aproveito", ""),
    "disfrutar": ("aproveitar / curtir", "Disfrutar = aproveitar; en el habla, curtir."),
    "disfruto": ("aproveito / curto", ""),
    "descansar": ("descansar", ""),
    "charlar": ("conversar / bater papo", "Charlar = conversar, bater papo."),
    "charla": ("conversa / papo / palestra", "Una charla (entre amigos) = um papo; (conferencia) = palestra."),
    "chatear": ("conversar / bater papo", ""),
    "enterarse": ("ficar sabendo / saber", "Me enteré = fiquei sabendo."),
    "me entere": ("fiquei sabendo / soube", ""),
    "darse cuenta": ("perceber", "Darse cuenta = perceber: percebi que…"),
    "me di cuenta": ("percebi", "Me di cuenta = percebi."),
    "tener ganas": ("ter vontade / estar a fim", "Tener ganas de = estar com vontade de, estar a fim de."),
    "tengo ganas": ("estou com vontade / estou a fim", ""),
    "tener razon": ("ter razão", ""),
    "tener hambre": ("estar com fome", "Tener hambre = estar com fome."),
    "tengo hambre": ("estou com fome", "Tengo hambre = estou com fome."),
    "tengo sed": ("estou com sede", "Tengo sed = estou com sede."),
    "tengo frio": ("estou com frio", "Tengo frío = estou com frio."),
    "tengo calor": ("estou com calor", "Tengo calor = estou com calor."),
    "tengo miedo": ("estou com medo / tenho medo", ""),
    "tengo sueño": ("estou com sono", "Tengo sueño = estou com sono."),
    "tengo prisa": ("estou com pressa", ""),
    "tengo años": ("tenho anos", ""),
    "hace frio": ("está frio / faz frio", "Hace frío = está frio / faz frio."),
    "hace calor": ("está calor / faz calor", "Hace calor = está calor / faz calor."),
    "hace sol": ("está sol / faz sol", ""),
    "hace falta": ("é preciso / falta", "Hace falta = é preciso."),
    "vuelvo a casa": ("volto para casa", ""),
    "en casa": ("em casa", ""),
    "a casa": ("para casa", "Ir a casa = ir para casa."),
})

# ---------------------------------------------------------------------------
# Sustantivos: tiempo, ciudad, casa, comida, cuerpo, gente
# ---------------------------------------------------------------------------
ES_IT.update({
    "año": ("ano", "Año = ano (la ñ no existe; ano no tiene nada de raro en portugués)."),
    "años": ("anos", "Años = anos: tenho trinta anos."),
    "dia": ("dia", ""),
    "semana": ("semana", ""),
    "mes": ("mês", "Mes = mês, con circunflejo."),
    "meses": ("meses", ""),
    "hora": ("hora", ""),
    "horas": ("horas", ""),
    "minuto": ("minuto", ""),
    "vez": ("vez", ""),
    "veces": ("vezes", "Veces = vezes."),
    "fin de semana": ("fim de semana", "Fin de semana = fim de semana."),
    "fin": ("fim", "Fin = fim, con m."),
    "lunes": ("segunda-feira", "Lunes = segunda-feira (o segunda)."),
    "martes": ("terça-feira", "Martes = terça-feira (o terça)."),
    "miercoles": ("quarta-feira", "Miércoles = quarta-feira."),
    "jueves": ("quinta-feira", "Jueves = quinta-feira."),
    "viernes": ("sexta-feira", "Viernes = sexta-feira."),
    "sabado": ("sábado", ""),
    "domingo": ("domingo", ""),
    "enero": ("janeiro", "Enero = janeiro (Rio de Janeiro: «río de enero»)."),
    "febrero": ("fevereiro", "Febrero = fevereiro."),
    "marzo": ("março", "Marzo = março."),
    "abril": ("abril", ""),
    "mayo": ("maio", "Mayo = maio."),
    "junio": ("junho", "Junio = junho."),
    "julio": ("julho", "Julio = julho."),
    "agosto": ("agosto", ""),
    "septiembre": ("setembro", "Septiembre = setembro."),
    "setiembre": ("setembro", ""),
    "octubre": ("outubro", "Octubre = outubro."),
    "noviembre": ("novembro", "Noviembre = novembro."),
    "diciembre": ("dezembro", "Diciembre = dezembro."),
    "primavera": ("primavera", ""),
    "verano": ("verão", "Verano = verão."),
    "otoño": ("outono", "Otoño = outono."),
    "invierno": ("inverno", "Invierno = inverno."),
    "noche": ("noite", "Noche = noite."),
    "madrugada": ("madrugada", ""),
    "mediodia": ("meio-dia", "Mediodía = meio-dia."),
    "medianoche": ("meia-noite", "Medianoche = meia-noite."),
    "cumpleaños": ("aniversário", "Cumpleaños = aniversário."),
    "aniversario": ("aniversário", ""),
    "fecha": ("data", "Fecha = data. «Fecha» en portugués = cierra (fechar)."),
    "ciudad": ("cidade", "Ciudad = cidade."),
    "calle": ("rua", "Calle = rua."),
    "barrio": ("bairro", "Barrio = bairro."),
    "esquina": ("esquina", ""),
    "cuadra": ("quarteirão", "Cuadra = quarteirão."),
    "vereda": ("calçada", "Vereda = calçada (el calçadão de Copacabana)."),
    "acera": ("calçada", ""),
    "plaza": ("praça", "Plaza = praça."),
    "puente": ("ponte", "El puente = a ponte (femenino)."),
    "iglesia": ("igreja", "Iglesia = igreja."),
    "edificio": ("prédio / edifício", "Edificio = prédio (habla) o edifício."),
    "departamento": ("apartamento", "Departamento (vivienda) = apartamento."),
    "piso": ("andar / chão", "Piso (de un edificio) = andar; el piso (suelo) = o chão."),
    "techo": ("teto / telhado", "Techo (interior) = teto; (exterior) = telhado."),
    "pared": ("parede", "Pared = parede."),
    "ventana": ("janela", "Ventana = janela."),
    "puerta": ("porta", "Puerta = porta."),
    "habitacion": ("quarto", "Habitación (dormitorio) = quarto."),
    "dormitorio": ("quarto", ""),
    "cuarto": ("quarto / quarta parte", ""),
    "cocina": ("cozinha / fogão", "La cocina (lugar) = a cozinha; (aparato) = o fogão."),
    "baño": ("banheiro", "Baño = banheiro."),
    "living": ("sala", "Living = sala (de estar)."),
    "comedor": ("sala de jantar", ""),
    "jardin": ("jardim", "Jardín = jardim."),
    "llave": ("chave", "Llave = chave."),
    "cama": ("cama", ""),
    "almohada": ("travesseiro", "Almohada = travesseiro."),
    "sabana": ("lençol", "Sábana = lençol."),
    "manta": ("cobertor", ""),
    "silla": ("cadeira", "Silla = cadeira."),
    "sillon": ("poltrona / sofá", ""),
    "mesa": ("mesa", ""),
    "heladera": ("geladeira", "Heladera = geladeira."),
    "nevera": ("geladeira", ""),
    "lavarropas": ("máquina de lavar", ""),
    "espejo": ("espelho", "Espejo = espelho."),
    "basura": ("lixo", "Basura = lixo."),
    "tacho": ("lixeira", ""),
    "luz": ("luz", ""),
    "agua": ("água", "Agua = água, con tilde."),
    "leche": ("leite", "La leche = o leite (masculino)."),
    "sangre": ("sangue", "La sangre = o sangue (masculino)."),
    "miel": ("mel", "La miel = o mel (masculino)."),
    "sal": ("sal", "La sal = o sal (masculino)."),
    "pan": ("pão", "Pan = pão (plural pães)."),
    "queso": ("queijo", "Queso = queijo."),
    "jamon": ("presunto", "Jamón = presunto."),
    "manteca": ("manteiga", "Manteca = manteiga."),
    "mantequilla": ("manteiga", ""),
    "huevo": ("ovo", "Huevo = ovo."),
    "carne": ("carne", ""),
    "pollo": ("frango", "Pollo = frango."),
    "pescado": ("peixe", "Pescado = peixe."),
    "pez": ("peixe", ""),
    "camaron": ("camarão", "Camarón = camarão."),
    "pulpo": ("polvo", "Pulpo = polvo."),
    "arroz": ("arroz", ""),
    "frijoles": ("feijão", "Porotos/frijoles = feijão."),
    "porotos": ("feijão", "Porotos = feijão (la feijoada)."),
    "fideos": ("macarrão", "Fideos = macarrão."),
    "papa": ("batata / pai / papai", "Papa = batata; papá = pai o papai."),
    "papas fritas": ("batata frita", ""),
    "batata": ("batata-doce", "Batata (dulce) = batata-doce."),
    "choclo": ("milho", "Choclo = milho."),
    "zanahoria": ("cenoura", "Zanahoria = cenoura."),
    "cebolla": ("cebola", "Cebolla = cebola."),
    "ajo": ("alho", "Ajo = alho."),
    "tomate": ("tomate", ""),
    "lechuga": ("alface", "Lechuga = alface (femenino)."),
    "ensalada": ("salada", "Ensalada = salada."),
    "fruta": ("fruta", ""),
    "manzana": ("maçã", "Manzana = maçã."),
    "naranja": ("laranja", "Naranja = laranja."),
    "frutilla": ("morango", "Frutilla = morango."),
    "fresa": ("morango", ""),
    "durazno": ("pêssego", "Durazno = pêssego."),
    "anana": ("abacaxi", "Ananá = abacaxi."),
    "piña": ("abacaxi", "Piña = abacaxi."),
    "palta": ("abacate", "Palta = abacate."),
    "sandia": ("melancia", "Sandía = melancia."),
    "limon": ("limão", "Limón = limão."),
    "platano": ("banana", ""),
    "azucar": ("açúcar", "Azúcar = açúcar (masculino)."),
    "aceite": ("azeite / óleo", "Aceite de oliva = azeite; aceite (de cocina, motor) = óleo."),
    "vinagre": ("vinagre", ""),
    "pimienta": ("pimenta", "Pimienta = pimenta."),
    "helado": ("sorvete / gelado", "Helado = sorvete; helado (muy frío) = gelado."),
    "torta": ("bolo / torta", "Torta (de cumpleaños) = bolo."),
    "pastel": ("bolo / pastel", "Pastel (dulce) = bolo; el pastel brasileño es una empanada frita."),
    "galletita": ("biscoito / bolacha", "Galletita = biscoito o bolacha."),
    "galleta": ("biscoito / bolacha", ""),
    "desayuno": ("café da manhã", "Desayuno = café da manhã."),
    "almuerzo": ("almoço", "Almuerzo = almoço."),
    "cena": ("jantar", "Cena = jantar. «Cena» en portugués = escena."),
    "merienda": ("lanche", "Merienda = lanche."),
    "postre": ("sobremesa", "Postre = sobremesa."),
    "comida": ("comida", ""),
    "bebida": ("bebida", ""),
    "cerveza": ("cerveja", "Cerveza = cerveja."),
    "jugo": ("suco", "Jugo = suco."),
    "zumo": ("suco", ""),
    "cafe": ("café", ""),
    "vaso": ("copo", "Vaso (para beber) = copo. «Vaso» en portugués = maceta o inodoro."),
    "copa": ("taça", "Copa (de vino) = taça. «Copa» en portugués = alacena o copa de un árbol."),
    "taza": ("xícara / caneca", "Taza = xícara (o caneca, la grande)."),
    "plato": ("prato", "Plato = prato."),
    "cuchara": ("colher", "Cuchara = colher."),
    "cucharita": ("colherzinha", ""),
    "tenedor": ("garfo", "Tenedor = garfo."),
    "cuchillo": ("faca", "Cuchillo = faca."),
    "servilleta": ("guardanapo", "Servilleta = guardanapo."),
    "botella": ("garrafa", "Botella = garrafa."),
    "cuenta": ("conta", "La cuenta = a conta."),
    "propina": ("gorjeta", "Propina = gorjeta. «Propina» en portugués = soborno."),
    "mozo": ("garçom", "Mozo = garçom."),
    "camarero": ("garçom", ""),
    "cuerpo": ("corpo", "Cuerpo = corpo."),
    "cabeza": ("cabeça", "Cabeza = cabeça."),
    "cara": ("rosto / cara", "Cara = rosto (o cara); ojo: «cara» en Brasil también = tipo, chabón."),
    "ojos": ("olhos", ""),
    "oreja": ("orelha", "Oreja = orelha."),
    "oido": ("ouvido", "Oído = ouvido."),
    "nariz": ("nariz", "La nariz = o nariz (masculino)."),
    "boca": ("boca", ""),
    "diente": ("dente", "Diente = dente."),
    "lengua": ("língua", "Lengua = língua."),
    "cuello": ("pescoço", "Cuello = pescoço."),
    "hombro": ("ombro", "Hombro = ombro."),
    "brazo": ("braço", "Brazo = braço."),
    "codo": ("cotovelo", "Codo = cotovelo."),
    "mano": ("mão", "Mano = mão (plural mãos)."),
    "dedo": ("dedo", ""),
    "uña": ("unha", "Uña = unha."),
    "pierna": ("perna", "Pierna = perna."),
    "rodilla": ("joelho", "Rodilla = joelho."),
    "pie": ("pé", "Pie = pé."),
    "espalda": ("costas", "La espalda = as costas (plural)."),
    "pecho": ("peito", "Pecho = peito."),
    "corazon": ("coração", "Corazón = coração."),
    "estomago": ("estômago", ""),
    "panza": ("barriga", "Panza = barriga."),
    "pelo": ("cabelo / pelo", "Pelo (de la cabeza) = cabelo. «Pelo» en portugués también = por el."),
    "cabello": ("cabelo", ""),
    "piel": ("pele", "Piel = pele."),
    "hueso": ("osso", "Hueso = osso."),
    "dolor": ("dor", "El dolor = a dor (femenino)."),
    "dolor de cabeza": ("dor de cabeça", ""),
    "fiebre": ("febre", "Fiebre = febre."),
    "gripe": ("gripe", ""),
    "resfrio": ("resfriado", "Resfrío = resfriado."),
    "medico": ("médico", ""),
    "hospital": ("hospital", ""),
    "farmacia": ("farmácia", ""),
    "remedio": ("remédio", ""),
    "pastilla": ("comprimido / pílula", ""),
    "receta": ("receita", "Receta = receita."),
    "gente": ("gente / pessoas", "La gente = as pessoas; «a gente» en portugués también = nosotros."),
    "persona": ("pessoa", "Persona = pessoa."),
    "hombre": ("homem", "Hombre = homem (plural homens)."),
    "mujer": ("mulher", "Mujer = mulher."),
    "chico": ("menino / garoto / rapaz", "Chico = menino, garoto, rapaz."),
    "chica": ("menina / garota / moça", ""),
    "niño": ("criança / menino", "Niño = criança (siempre femenino) o menino."),
    "niña": ("menina", "Niña = menina."),
    "niños": ("crianças", "Niños = crianças."),
    "bebe": ("bebê", "Bebé = bebê."),
    "pibe": ("garoto / moleque", ""),
    "piba": ("garota / menina", ""),
    "novio": ("namorado / noivo", "Novio = namorado; «noivo» es el prometido."),
    "novia": ("namorada / noiva", "Novia = namorada; «noiva» es la prometida o la novia en la boda."),
    "esposo": ("marido / esposo", ""),
    "marido": ("marido", ""),
    "esposa": ("esposa / mulher", ""),
    "padre": ("pai / padre", "Padre = pai; «padre» en portugués es sacerdote."),
    "madre": ("mãe", "Madre = mãe."),
    "padres": ("pais", "Padres = pais."),
    "mama": ("mãe / mamãe", "Mamá = mãe o mamãe."),
    "hijo": ("filho", "Hijo = filho."),
    "hija": ("filha", "Hija = filha."),
    "hijos": ("filhos", ""),
    "hermano": ("irmão", "Hermano = irmão."),
    "hermana": ("irmã", "Hermana = irmã."),
    "hermanos": ("irmãos", ""),
    "abuelo": ("avô", "Abuelo = avô (o cerrada)."),
    "abuela": ("avó", "Abuela = avó (o abierta)."),
    "abuelos": ("avós", ""),
    "nieto": ("neto", "Nieto = neto."),
    "nieta": ("neta", ""),
    "tio": ("tio", ""),
    "tia": ("tia", ""),
    "primo": ("primo", ""),
    "suegro": ("sogro", "Suegro = sogro."),
    "suegra": ("sogra", ""),
    "cuñado": ("cunhado", "Cuñado = cunhado."),
    "cuñada": ("cunhada", ""),
    "sobrino": ("sobrinho", "Sobrino = sobrinho."),
    "amigo": ("amigo", ""),
    "vecino": ("vizinho", "Vecino = vizinho."),
    "vecina": ("vizinha", ""),
    "jefe": ("chefe", "Jefe = chefe."),
    "compañero": ("colega / companheiro", "Compañero de trabajo = colega."),
    "familia": ("família", ""),
    "perro": ("cachorro / cão", "Perro = cachorro (o cão). «Perro» no existe."),
    "cachorro": ("filhote", "Cachorro (cría) = filhote. «Cachorro» en portugués = perro."),
    "gato": ("gato", ""),
    "raton": ("rato / camundongo", "Ratón = camundongo; rato = rata. El del compu = mouse."),
    "pajaro": ("pássaro", "Pájaro = pássaro."),
    "caballo": ("cavalo", "Caballo = cavalo."),
    "vaca": ("vaca", ""),
    "cerdo": ("porco", "Cerdo = porco."),
    "chancho": ("porco", ""),
    "oveja": ("ovelha", "Oveja = ovelha."),
    "mono": ("macaco", "Mono = macaco."),
    "arbol": ("árvore", "El árbol = a árvore (femenino)."),
    "flor": ("flor", ""),
    "hoja": ("folha", "Hoja = folha."),
    "mar": ("mar", ""),
    "playa": ("praia", "Playa = praia."),
    "arena": ("areia", "Arena = areia."),
    "ola": ("onda", "Ola = onda."),
    "cielo": ("céu", "Cielo = céu."),
    "sol": ("sol", ""),
    "luna": ("lua", "Luna = lua."),
    "estrella": ("estrela", "Estrella = estrela."),
    "nube": ("nuvem", "Nube = nuvem."),
    "lluvia": ("chuva", "Lluvia = chuva."),
    "nieve": ("neve", "Nieve = neve."),
    "viento": ("vento", "Viento = vento."),
    "tiempo": ("tempo", "Tiempo = tempo."),
    "clima": ("clima / tempo", ""),
    "tierra": ("terra", "Tierra = terra."),
    "montaña": ("montanha", "Montaña = montanha."),
    "cerro": ("morro", "Cerro = morro (el Morro da Urca)."),
    "isla": ("ilha", "Isla = ilha."),
    "lago": ("lago", ""),
    "bosque": ("floresta / bosque", ""),
    "selva": ("selva / floresta", ""),
    "campo": ("campo / interior", ""),
    "pueblo": ("povo / cidadezinha / vilarejo", "Pueblo (gente) = povo; (lugar chico) = cidadezinha."),
    "pais": ("país", ""),
    "mundo": ("mundo", ""),
    "auto": ("carro", "Auto = carro."),
    "coche": ("carro", ""),
    "colectivo": ("ônibus", "Colectivo = ônibus."),
    "autobus": ("ônibus", "Autobús = ônibus."),
    "micro": ("ônibus", ""),
    "subte": ("metrô", "Subte = metrô."),
    "metro": ("metrô / metro", "Metro (transporte) = metrô; metro (medida) = metro."),
    "tren": ("trem", "Tren = trem."),
    "avion": ("avião", "Avión = avião."),
    "barco": ("barco", ""),
    "bici": ("bicicleta / bike", ""),
    "moto": ("moto", ""),
    "camion": ("caminhão", "Camión = caminhão."),
    "taxi": ("táxi", ""),
    "estacion": ("estação", "Estación = estação."),
    "parada": ("ponto / parada", "Parada de colectivo = ponto de ônibus."),
    "aeropuerto": ("aeroporto", "Aeropuerto = aeroporto."),
    "pasaje": ("passagem", "Pasaje = passagem (femenino)."),
    "boleto": ("passagem / bilhete / boleto", "Boleto = passagem, bilhete. «Boleto» en Brasil = factura para pagar."),
    "entrada": ("ingresso / entrada", "Entrada (cine, show) = ingresso."),
    "valija": ("mala", "Valija = mala."),
    "maleta": ("mala", ""),
    "mochila": ("mochila", ""),
    "billetera": ("carteira", "Billetera = carteira."),
    "cartera": ("bolsa / carteira", "Cartera (de mujer) = bolsa."),
    "bolsa": ("sacola / bolsa", "Bolsa (de súper) = sacola."),
    "plata": ("dinheiro / grana / prata", "Plata (dinero) = dinheiro; en el habla, grana."),
    "dinero": ("dinheiro", "Dinero = dinheiro."),
    "billete": ("nota / cédula", "Billete = nota, cédula."),
    "moneda": ("moeda", "Moneda = moeda."),
    "tarjeta": ("cartão", "Tarjeta = cartão."),
    "precio": ("preço", "Precio = preço."),
    "negocio": ("loja / negócio", "Negocio (tienda) = loja."),
    "tienda": ("loja", "Tienda = loja."),
    "almacen": ("mercadinho / armazém", ""),
    "supermercado": ("supermercado / mercado", ""),
    "feria": ("feira", "Feria = feira (la feira de los sábados)."),
    "mercado": ("mercado", ""),
    "carniceria": ("açougue", "Carnicería = açougue."),
    "panaderia": ("padaria", "Panadería = padaria."),
    "kiosco": ("banca / quiosque", "Kiosco de diarios = banca de jornal."),
    "ropa": ("roupa", "Ropa = roupa."),
    "camisa": ("camisa", ""),
    "remera": ("camiseta", "Remera = camiseta."),
    "camiseta": ("camiseta", ""),
    "pantalon": ("calça", "Pantalón = calça."),
    "pantalones": ("calça", "Los pantalones = a calça (singular)."),
    "pollera": ("saia", "Pollera = saia."),
    "falda": ("saia", ""),
    "vestido": ("vestido", ""),
    "zapato": ("sapato", "Zapato = sapato."),
    "zapatos": ("sapatos", ""),
    "zapatillas": ("tênis", "Zapatillas = tênis."),
    "ojotas": ("chinelos", "Ojotas = chinelos (las Havaianas)."),
    "medias": ("meias", "Medias = meias."),
    "sombrero": ("chapéu", "Sombrero = chapéu."),
    "gorra": ("boné", "Gorra = boné."),
    "anteojos": ("óculos", "Anteojos = óculos."),
    "gafas": ("óculos", ""),
    "reloj": ("relógio", "Reloj = relógio."),
    "traje de baño": ("maiô / sunga / biquíni", "Traje de baño = maiô (mujer), sunga (hombre)."),
    "malla": ("biquíni / maiô / sunga", ""),
    "campera": ("jaqueta", "Campera = jaqueta."),
    "abrigo": ("casaco", "Abrigo = casaco."),
    "bufanda": ("cachecol", "Bufanda = cachecol."),
    "trabajo": ("trabalho / emprego", "Trabajo = trabalho; (puesto) = emprego."),
    "empleo": ("emprego", "Empleo = emprego."),
    "empresa": ("empresa", ""),
    "oficina": ("escritório", "Oficina (lugar de trabajo) = escritório. «Oficina» en portugués = taller."),
    "taller": ("oficina", "Taller (mecánico) = oficina."),
    "sueldo": ("salário", "Sueldo = salário."),
    "reunion": ("reunião", "Reunión = reunião."),
    "escuela": ("escola", "Escuela = escola."),
    "colegio": ("escola / colégio", ""),
    "universidad": ("universidade / faculdade", "Universidad = universidade (o faculdade)."),
    "facultad": ("faculdade", ""),
    "profesor": ("professor", ""),
    "alumno": ("aluno", "Alumno = aluno."),
    "clase": ("aula / classe", "La clase (lección) = a aula."),
    "aula": ("sala de aula", "Aula (salón) = sala de aula. «Aula» en portugués = clase."),
    "tarea": ("tarefa / dever de casa", ""),
    "examen": ("prova / exame", "Examen = prova (escuela) o exame."),
    "prueba": ("prova / teste", ""),
    "nota": ("nota", ""),
    "libro": ("livro", "Libro = livro."),
    "cuaderno": ("caderno", "Cuaderno = caderno."),
    "lapiz": ("lápis", "Lápiz = lápis."),
    "lapicera": ("caneta", "Lapicera = caneta."),
    "birome": ("caneta", "Birome = caneta."),
    "goma": ("borracha", "Goma (de borrar) = borracha."),
    "hoja de papel": ("folha de papel", ""),
    "diario": ("jornal / diário", "Diario (periódico) = jornal."),
    "periodico": ("jornal", ""),
    "revista": ("revista", ""),
    "noticia": ("notícia", ""),
    "pelicula": ("filme", "Película = filme."),
    "cine": ("cinema", "Cine = cinema."),
    "teatro": ("teatro", ""),
    "musica": ("música", ""),
    "cancion": ("canção / música", "Canción = música, canção."),
    "fiesta": ("festa", "Fiesta = festa."),
    "baile": ("baile / dança", ""),
    "partido": ("jogo / partida / partido", "Partido (fútbol) = jogo, partida."),
    "futbol": ("futebol", "Fútbol = futebol."),
    "cancha": ("campo / quadra", "Cancha (fútbol) = campo; (tenis) = quadra."),
    "equipo": ("time / equipe", "Equipo (deporte) = time."),
    "gol": ("gol", ""),
    "celular": ("celular", ""),
    "computadora": ("computador", "Computadora = computador (masculino)."),
    "ordenador": ("computador", ""),
    "pantalla": ("tela", "Pantalla = tela."),
    "teclado": ("teclado", ""),
    "contraseña": ("senha", "Contraseña = senha."),
    "correo": ("correio / e-mail", ""),
    "mensaje": ("mensagem", "Mensaje = mensagem (femenino)."),
    "llamada": ("ligação / chamada", "Llamada (teléfono) = ligação."),
    "idioma": ("idioma / língua", ""),
    "palabra": ("palavra", "Palabra = palavra."),
    "respuesta": ("resposta", "Respuesta = resposta."),
    "problema": ("problema", ""),
    "cosa": ("coisa", "Cosa = coisa."),
    "cosas": ("coisas", ""),
    "nombre": ("nome", "Nombre = nome."),
    "apellido": ("sobrenome", "Apellido = sobrenome. «Apelido» en portugués = apodo."),
    "apodo": ("apelido", "Apodo = apelido."),
    "direccion": ("endereço / direção", "Dirección (domicilio) = endereço."),
    "lugar": ("lugar", ""),
    "vacaciones": ("férias", "Vacaciones = férias."),
    "hotel": ("hotel", ""),
    "costumbre": ("costume", "La costumbre = o costume (masculino)."),
    "origen": ("origem", "El origen = a origem (femenino)."),
    "color": ("cor", "El color = a cor (femenino)."),
    "calor": ("calor", ""),
    "frio": ("frio", ""),
    "hambre": ("fome", "Hambre = fome."),
    "sed": ("sede", "Sed = sede (con e cerrada; sede con e abierta = sede de una empresa)."),
    "miedo": ("medo", "Miedo = medo."),
    "ganas": ("vontade", "Ganas = vontade."),
    "cuidado": ("cuidado", ""),
    "paz": ("paz", ""),
    "guerra": ("guerra", ""),
    "verdad": ("verdade", "Verdad = verdade."),
    "mentira": ("mentira", ""),
    "libertad": ("liberdade", "Libertad = liberdade."),
    "sociedad": ("sociedade", "Sociedad = sociedade."),
    "historia": ("história", ""),
    "esclavitud": ("escravidão", "Esclavitud = escravidão."),
    "esclavo": ("escravo", ""),
    "independencia": ("independência", ""),
    "dictadura": ("ditadura", "Dictadura = ditadura."),
    "gobierno": ("governo", "Gobierno = governo."),
    "ley": ("lei", "Ley = lei."),
    "pueblo brasileño": ("povo brasileiro", ""),
    "derecho": ("direito", "Derecho = direito."),
    "izquierda": ("esquerda", "Izquierda = esquerda."),
    "derecha": ("direita", "Derecha = direita."),
    "elecciones": ("eleições", ""),
    "voto": ("voto", ""),
    "pensamiento": ("pensamento", ""),
    "saudade": ("saudade", ""),
    "nostalgia": ("saudade / nostalgia", ""),
})

# ---------------------------------------------------------------------------
# Adjetivos
# ---------------------------------------------------------------------------
ES_IT.update({
    "buena": ("boa", "Buena = boa."),
    "buenos": ("bons", "Buenos = bons."),
    "buen": ("bom", "Buen = bom: um bom dia."),
    "malo": ("mau / ruim", "Malo = ruim (cosa) o mau (persona)."),
    "mala": ("má / ruim", ""),
    "grande": ("grande", ""),
    "gran": ("grande", "Gran = grande (no se apocopa)."),
    "pequeño": ("pequeno", "Pequeño = pequeno."),
    "nuevo": ("novo", "Nuevo = novo."),
    "nueva": ("nova", ""),
    "viejo": ("velho", "Viejo = velho."),
    "vieja": ("velha", ""),
    "joven": ("jovem", "Joven = jovem (plural jovens)."),
    "lindo": ("lindo / bonito", ""),
    "hermoso": ("lindo / formoso", ""),
    "feo": ("feio", "Feo = feio."),
    "alto": ("alto", ""),
    "gordo": ("gordo", ""),
    "flaco": ("magro", "Flaco = magro. «Fraco» en portugués = débil."),
    "delgado": ("magro", ""),
    "largo": ("comprido / longo", "Largo = comprido, longo. «Largo» en portugués = ancho."),
    "ancho": ("largo", "Ancho = largo."),
    "corto": ("curto", "Corto = curto."),
    "rapido": ("rápido", ""),
    "lento": ("lento / devagar", ""),
    "facil": ("fácil", ""),
    "dificil": ("difícil", ""),
    "caro": ("caro", ""),
    "barato": ("barato", ""),
    "lleno": ("cheio", "Lleno = cheio."),
    "vacio": ("vazio", "Vacío = vazio."),
    "limpio": ("limpo", "Limpio = limpo."),
    "sucio": ("sujo", "Sucio = sujo."),
    "caliente": ("quente", "Caliente = quente."),
    "cansado": ("cansado", ""),
    "enfermo": ("doente", "Enfermo = doente."),
    "contento": ("contente / feliz", ""),
    "triste": ("triste", ""),
    "listo": ("pronto / esperto", "Listo (preparado) = pronto; (inteligente) = esperto."),
    "raro": ("estranho / esquisito", "Raro (extraño) = estranho, esquisito. «Raro» en portugués = poco frecuente."),
    "exquisito": ("delicioso / requintado", "Exquisito = delicioso. «Esquisito» en portugués = raro."),
    "rico": ("gostoso / rico", "Rico (sabroso) = gostoso; rico (con plata) = rico."),
    "sabroso": ("gostoso / saboroso", ""),
    "embarazada": ("grávida", "Embarazada = grávida. «Embaraçada» = avergonzada."),
    "avergonzado": ("envergonhado / com vergonha", ""),
    "celoso": ("ciumento", "Celoso = ciumento."),
    "simpatico": ("simpático", ""),
    "amable": ("gentil / amável", "Amable = gentil, amável."),
    "gracioso": ("engraçado", "Gracioso (que hace reír) = engraçado."),
    "divertido": ("divertido / engraçado", ""),
    "aburrido": ("chato / entediado", "Aburrido (que aburre) = chato; (que se aburre) = entediado."),
    "pesado": ("chato / pesado", ""),
    "tranquilo": ("tranquilo / de boa", ""),
    "seguro": ("seguro / certo", "Estoy seguro = tenho certeza."),
    "cierto": ("certo", "Cierto = certo."),
    "oscuro": ("escuro", "Oscuro = escuro."),
    "blanco": ("branco", "Blanco = branco."),
    "negro": ("preto / negro", "Negro (color) = preto; negro (persona) = negro."),
    "rojo": ("vermelho", "Rojo = vermelho."),
    "amarillo": ("amarelo", "Amarillo = amarelo."),
    "azul": ("azul", ""),
    "verde": ("verde", ""),
    "marron": ("marrom", "Marrón = marrom."),
    "gris": ("cinza", "Gris = cinza."),
    "rosa": ("rosa", ""),
    "celeste": ("azul-claro", "Celeste = azul-claro."),
    "violeta": ("roxo / violeta", "Violeta = roxo."),
    "rubio": ("loiro", "Rubio = loiro."),
    "morocho": ("moreno", "Morocho = moreno."),
    "pelado": ("careca", "Pelado = careca. «Pelado» en portugués = desnudo."),
    "calvo": ("careca", ""),
    "ciego": ("cego", "Ciego = cego."),
    "sordo": ("surdo", "Sordo = surdo."),
    "mudo": ("mudo", ""),
    "juntos": ("juntos", ""),
    "primero": ("primeiro", "Primero = primeiro."),
    "primer": ("primeiro", "Primer = primeiro (no se apocopa)."),
    "tercero": ("terceiro", ""),
    "tercer": ("terceiro", ""),
    "segundo": ("segundo", ""),
    "ultimo": ("último", ""),
    "proximo": ("próximo / que vem", "La semana próxima = a semana que vem."),
    "pasado": ("passado", "Pasado = passado (ss)."),
    "anterior": ("anterior", ""),
    "siguiente": ("seguinte", "Siguiente = seguinte."),
    "importante": ("importante", ""),
    "necesario": ("necessário", "Necesario = necessário."),
    "posible": ("possível", "Posible = possível."),
    "imposible": ("impossível", ""),
    "probable": ("provável", "Probable = provável."),
    "agradable": ("agradável", "Agradable = agradável."),
    "increible": ("incrível", ""),
    "terrible": ("terrível", ""),
    "horrible": ("horrível", ""),
    "responsable": ("responsável", ""),
    "brasileño": ("brasileiro", "Brasileño = brasileiro."),
    "brasileña": ("brasileira", ""),
    "argentino": ("argentino", ""),
    "portugues": ("português", ""),
    "español": ("espanhol", "Español = espanhol."),
    "ingles": ("inglês", ""),
    "frances": ("francês", ""),
    "aleman": ("alemão", "Alemán = alemão; alemana = alemã."),
    "italiano": ("italiano", ""),
    "uruguayo": ("uruguaio", "Uruguayo = uruguaio."),
    "paraguayo": ("paraguaio", ""),
    "chileno": ("chileno", ""),
    "carioca": ("carioca", ""),
    "paulista": ("paulista / paulistano", ""),
    "mayor": ("maior / mais velho", "Mayor = maior; (edad) = mais velho."),
    "menor": ("menor / mais novo", ""),
    "feliz": ("feliz", ""),
    "libre": ("livre", "Libre = livre."),
    "lleno de": ("cheio de", ""),
    "listo para": ("pronto para", ""),
})


# ---------------------------------------------------------------------------
# Falsos amigos (heterosemánticos): palabra PORTUGUESA que parece española
#   portugués → (qué significa en español, qué quería decir el alumno, nota)
# ---------------------------------------------------------------------------
FALSI = {
    "esquisito": ("raro, extraño", "delicioso / requintado", "Esquisito = raro. Exquisito (comida) = delicioso, gostoso; (elegante) = requintado."),
    "esquisita": ("rara, extraña", "deliciosa / requintada", "Esquisita = rara. Una comida exquisita = uma comida deliciosa."),
    "polvo": ("pulpo", "pó / poeira", "Polvo = pulpo. El polvo = o pó, a poeira."),
    "borracha": ("goma de borrar, caucho", "bêbada", "Borracha = goma. Borracha (ebria) = bêbada."),
    "borrachas": ("gomas de borrar", "bêbadas", "Borracha = goma de borrar."),
    "apelido": ("apodo", "sobrenome", "Apelido = apodo. El apellido = o sobrenome."),
    "oficina": ("taller (mecánico)", "escritório", "Oficina = taller. La oficina donde trabajás = o escritório."),
    "escritório": ("oficina", "escrivaninha", "Escritório = oficina. El escritorio (mueble) = a escrivaninha."),
    "largo": ("ancho", "comprido / longo", "Largo = ancho. Largo (de longitud) = comprido, longo."),
    "larga": ("ancha", "comprida / longa", "Larga = ancha. Una calle larga = uma rua comprida."),
    "pelado": ("desnudo", "careca", "Pelado = desnudo. Pelado (sin pelo) = careca."),
    "pelada": ("desnuda / picado de fútbol", "careca", "Pelada = desnuda o un picado de fútbol. Calva = careca."),
    "cena": ("escena", "jantar", "Cena = escena (de película, teatro). La cena = o jantar."),
    "sobremesa": ("postre", "conversa depois da refeição", "Sobremesa = postre. La sobremesa (charla) = o papo depois do almoço."),
    "rato": ("rata, ratón", "momento / tempinho", "Rato = rata. Un rato = um tempinho, um pouco, um momento."),
    "taça": ("copa (de vino, trofeo)", "xícara", "Taça = copa. La taza = a xícara (o a caneca)."),
    "copo": ("vaso (para beber)", "floco", "Copo = vaso. Un copo de nieve = um floco de neve."),
    "vaso": ("maceta, florero; inodoro", "copo", "Vaso = maceta o inodoro. El vaso de agua = o copo d'água."),
    "salada": ("ensalada", "salgada", "Salada = ensalada. Salado = salgado, salgada."),
    "embaraçada": ("avergonzada, enredada", "grávida", "Embaraçada = avergonzada. Embarazada = grávida."),
    "embaraçado": ("avergonzado, enredado", "grávida", "Embaraçado = avergonzado, incómodo. Embarazada = grávida."),
    "embaraço": ("vergüenza, apuro", "gravidez", "Embaraço = apuro, vergüenza. El embarazo = a gravidez."),
    "contestar": ("cuestionar, impugnar", "responder", "Contestar = cuestionar. Contestar (responder) = responder."),
    "contestou": ("cuestionó", "respondeu", "Contestar = cuestionar. «Me contestó» = me respondeu."),
    "ninho": ("nido", "criança / menino", "Ninho = nido. El niño = a criança, o menino."),
    "balcão": ("mostrador, barra", "sacada / varanda", "Balcão = mostrador. El balcón = a sacada, a varanda."),
    "brincar": ("jugar (los chicos); bromear", "pular", "Brincar = jugar o bromear. Brincar (saltar) = pular."),
    "brinco": ("aro, aros (pendientes)", "pulo", "Brinco = aro (arete). Un brinco (salto) = um pulo."),
    "cadeira": ("silla", "quadril", "Cadeira = silla. La cadera = o quadril."),
    "cola": ("pegamento", "fila / rabo", "Cola = pegamento. La cola (de gente) = a fila; (de animal) = o rabo."),
    "fechar": ("cerrar", "datar", "Fechar = cerrar. Fechar (poner fecha) = datar."),
    "fecha": ("cierra", "data", "Fecha = cierra (de fechar). La fecha = a data."),
    "fechado": ("cerrado", "datado", "Fechado = cerrado. Fechado (con fecha) = datado."),
    "firmar": ("afirmar, fijar, establecer", "assinar", "Firmar = afirmar, consolidar. Firmar un documento = assinar."),
    "firma": ("empresa", "assinatura", "Firma = empresa. La firma (en un papel) = a assinatura."),
    "latido": ("ladrido", "batida", "Latido = ladrido (del perro). El latido del corazón = a batida."),
    "logo": ("enseguida, pronto; luego (por lo tanto)", "depois", "Logo = enseguida. Luego (después) = depois."),
    "novela": ("telenovela", "romance", "Novela = telenovela. La novela (libro) = o romance."),
    "romance": ("novela (libro); romance", "caso / namoro", "Romance = novela literaria (y también romance amoroso)."),
    "prender": ("sujetar; arrestar", "acender", "Prender = sujetar, arrestar. Prender la luz = acender a luz."),
    "presunto": ("jamón", "suposto", "Presunto = jamón. Presunto (supuesto) = suposto."),
    "propina": ("soborno", "gorjeta", "Propina = soborno (coima). La propina al mozo = a gorjeta."),
    "rubrica": ("firma abreviada, iniciales", "assinatura", "Rubrica = iniciales o firma corta (rubricar cada hoja). La firma completa = a assinatura."),
    "aula": ("clase (lección)", "sala de aula", "Aula = clase. El aula (salón) = a sala de aula."),
    "acordar": ("despertarse", "lembrar / combinar", "Acordar = despertarse. Acordarse = lembrar(-se); acordar algo = combinar."),
    "acordei": ("me desperté", "lembrei / combinei", "Acordei = me desperté. Me acordé = lembrei."),
    "batata": ("papa", "batata-doce", "Batata = papa. La batata = a batata-doce."),
    "cachorro": ("perro", "filhote", "Cachorro = perro. El cachorro (cría) = o filhote."),
    "chulo": ("grosero, vulgar", "bonito / metido", "Chulo = grosero. Chulo (lindo) = bonito, bacana."),
    "criança": ("niño, niña (chico)", "criação", "Criança = niño o niña. La crianza = a criação."),
    "desenvolver": ("desarrollar", "desembrulhar", "Desenvolver = desarrollar. Desenvolver un paquete = desembrulhar."),
    "distinto": ("distinguido, elegante", "diferente", "Distinto = distinguido (formal). Distinto (diferente) = diferente."),
    "escova": ("cepillo", "vassoura", "Escova = cepillo. La escoba = a vassoura."),
    "garrafa": ("botella", "jarra", "Garrafa = botella. La garrafa (jarra) = a jarra."),
    "ligar": ("llamar por teléfono; encender", "paquerar", "Ligar = llamar por teléfono o encender. Ligar (seducir) = paquerar."),
    "mala": ("valija", "má / ruim", "Mala = valija. Mala (mal) = má, ruim."),
    "pasta": ("carpeta; pasta (dental)", "massa", "Pasta = carpeta. La pasta (comida) = a massa, o macarrão."),
    "raro": ("poco frecuente", "estranho", "Raro = poco común. Raro (extraño) = estranho, esquisito."),
    "reparar": ("notar, fijarse; reparar", "consertar", "Reparar = notar, fijarse (reparei que…). Arreglar algo = consertar."),
    "sítio": ("chacra, finca; sitio (web)", "lugar", "Sítio = chacra. Un sitio (lugar) = um lugar."),
    "tirar": ("sacar, quitar", "jogar", "Tirar = sacar (tirar uma foto). Tirar (arrojar) = jogar; a la basura = jogar fora."),
    "todavia": ("sin embargo", "ainda", "Todavia = sin embargo. Todavía = ainda."),
    "acreditar": ("creer", "credenciar / comprovar", "Acreditar = creer (acredito em você). Acreditar (probar) = comprovar."),
    "berro": ("grito, bramido", "agrião", "Berro = grito. El berro (planta) = o agrião."),
    "bolsa": ("cartera (de mujer); beca; bolsa de valores", "sacola", "Bolsa = cartera o beca. La bolsa del súper = a sacola."),
    "bolso": ("bolsillo", "bolsa", "Bolso = bolsillo. El bolso = a bolsa."),
    "cigarro": ("cigarrillo", "charuto", "Cigarro = cigarrillo. El cigarro (puro) = o charuto."),
    "desquite": ("separación legal (antiguo)", "revanche", "Desquite = separación. El desquite (revancha) = a revanche."),
    "exprimir": ("expresar", "espremer", "Exprimir = expresar. Exprimir una naranja = espremer."),
    "largar": ("soltar, dejar, abandonar", "ir embora", "Largar = soltar, dejar (largou o emprego). Largarse = ir embora."),
    "mas": ("pero", "mais", "Mas = pero. Más = mais."),
    "pegar": ("agarrar, tomar (el colectivo)", "bater / colar", "Pegar = agarrar, tomar (pegar o ônibus). Pegar (golpear) = bater; (adherir) = colar."),
    "pelo": ("por el (contracción); vello", "cabelo", "Pelo = por + o (pelo centro) o vello. El pelo de la cabeza = o cabelo."),
    "procurar": ("buscar", "tentar", "Procurar = buscar. Procurar (tratar de) = tentar."),
    "pronto": ("listo, preparado", "logo / em breve", "Pronto = listo (está pronto). Pronto (en breve) = logo, em breve."),
    "quitar": ("saldar (una deuda)", "tirar", "Quitar = saldar una deuda. Quitar algo = tirar."),
    "reclamar": ("quejarse", "exigir / reivindicar", "Reclamar = quejarse. Reclamar (exigir) = exigir, reivindicar."),
    "roxo": ("morado, violeta", "vermelho", "Roxo = morado. Rojo = vermelho."),
    "rubro": ("rojo (formal)", "setor / ramo", "Rubro = rojo intenso. El rubro (de un negocio) = o ramo, o setor."),
    "salsa": ("perejil", "molho", "Salsa = perejil. La salsa = o molho."),
    "sótão": ("desván, altillo", "porão", "Sótão = altillo. El sótano = o porão."),
    "tapa": ("bofetada, cachetada", "tampa", "Tapa = cachetada. La tapa (de una olla) = a tampa."),
    "tenda": ("carpa", "loja", "Tenda = carpa. La tienda = a loja."),
    "cueca": ("calzoncillo", "cueca (dança chilena)", "Cueca = calzoncillo en Brasil."),
    "abono": ("bonificación, justificación de falta", "adubo / passe", "Abono = bono, bonificación. El abono (fertilizante) = o adubo; (pase) = o passe."),
    "aceite": ("aceptación (formal)", "azeite / óleo", "Aceite = aceptación. El aceite de oliva = o azeite; de cocina o motor = o óleo."),
    "bilhete": ("nota corta; boleto, pasaje", "nota / cédula", "Bilhete = nota o pasaje. El billete de dinero = a nota, a cédula."),
    "carpete": ("alfombra, moqueta", "pasta", "Carpete = alfombra. La carpeta = a pasta."),
    "cartão": ("tarjeta", "papelão", "Cartão = tarjeta. El cartón = o papelão."),
    "chato": ("aburrido, pesado, molesto", "achatado", "Chato = pesado, aburrido (que chato!). Chato (plano) = achatado."),
    "conserto": ("arreglo, reparación", "concerto", "Conserto = arreglo. El concierto = o concerto."),
    "costas": ("espalda", "costa / litoral", "Costas = espalda. Las costas = o litoral."),
    "estofado": ("tapizado", "ensopado", "Estofado = tapizado. El estofado (guiso) = o ensopado."),
    "gracioso": ("encantador, lindo", "engraçado", "Gracioso = lindo, con gracia. Gracioso (que hace reír) = engraçado."),
    "jornal": ("diario, periódico", "diária", "Jornal = diario. El jornal (paga diaria) = a diária."),
    "pino": ("perno, clavija", "pinheiro", "Pino = perno. El pino = o pinheiro."),
    "sacar": ("entender (coloquial); sacar (tenis)", "tirar", "Sacar = entender (sacou?). Sacar algo = tirar."),
    "tomada": ("enchufe; toma (de una ciudad)", "tomada", "Tomada = enchufe: carregar o celular na tomada."),
    "carro": ("auto", "carrinho", "Carro = auto. El carrito del súper = o carrinho."),
    "coxa": ("muslo", "manca", "Coxa = muslo. Coja = manca."),
    "doce": ("dulce", "doze", "Doce = dulce. Doce (12) = doze."),
    "bala": ("caramelo; bala", "bala", "Bala = caramelo en Brasil (y también bala)."),
    "cerca": ("valla, cerco", "perto", "Cerca = valla. Cerca de (lugar) = perto de."),
    "funda": ("honda, profunda", "capa / fronha", "Funda = honda. La funda (del celu) = a capa; de la almohada = a fronha."),
    "noivo": ("prometido; novio en la boda", "namorado", "Noivo = prometido. El novio (pareja) = o namorado."),
    "noiva": ("prometida; novia en la boda", "namorada", "Noiva = prometida. La novia (pareja) = a namorada."),
    "padre": ("sacerdote", "pai", "Padre = cura, sacerdote. El padre = o pai."),
    "parado": ("detenido, quieto", "em pé", "Parado = quieto, detenido. Estar parado (de pie) = estar em pé."),
    "película": ("película (film fino), membrana", "filme", "Película = lámina fina. La película de cine = o filme."),
    "saco": ("bolsa grande; ¡qué embole! (que saco!)", "paletó", "Saco = bolsa. El saco (prenda) = o paletó."),
    "torpe": ("infame, indigno", "desajeitado", "Torpe = vil, infame. Torpe (poco hábil) = desajeitado."),
    "vaga": ("vacante; lugar para estacionar", "preguiçosa", "Vaga = vacante (vaga de emprego). Vaga (perezosa) = preguiçosa."),
    "esperto": ("vivo, listo, astuto", "especialista", "Esperto = vivo, pícaro. Experto = especialista, perito."),
    "batido": ("trillado, común", "vitamina / milk-shake", "Batido = trillado. El licuado = a vitamina."),
    "espantoso": ("asombroso, admirable", "horrível", "Espantoso = asombroso. Espantoso (horrible) = horrível, horroroso."),
    "logro": ("engaño, estafa", "conquista / êxito", "Logro = engaño. Un logro = uma conquista."),
    "lograr": ("engañar; conseguir", "conseguir", "Lograr a alguien = engañarlo. Lograr algo = conseguir."),
    "tela": ("pantalla; lienzo", "tecido / pano", "Tela = pantalla o lienzo. La tela (género) = o tecido, o pano."),
    "pastel": ("empanada frita", "bolo", "Pastel = empanada frita de feria. El pastel (dulce) = o bolo."),
    "fraco": ("débil", "magro", "Fraco = débil. Flaco = magro."),
    "desenho": ("dibujo", "design / projeto", "Desenho = dibujo. El diseño = o design, o projeto."),
    "sucesso": ("éxito", "acontecimento", "Sucesso = éxito. Un suceso = um acontecimento."),
    "cerrar": ("apretar (los dientes, las filas)", "fechar", "Cerrar existe (cerrar os punhos), pero cerrar la puerta = fechar a porta."),
    "botar": ("poner (coloquial)", "jogar fora", "Botar = poner (bota aí). Botar (a la basura) = jogar fora."),
    "carteira": ("billetera; pupitre; registro", "bolsa", "Carteira = billetera. La cartera (de mujer) = a bolsa."),
    "ligeiro": ("rápido", "leve", "Ligeiro = rápido. Ligero (liviano) = leve."),
    "prenda": ("regalo, talento", "peça de roupa", "Prenda = don, talento. Una prenda de ropa = uma peça de roupa."),
    "morro": ("cerro; en Río, también favela", "focinho", "Morro = cerro (Morro da Urca). El morro (hocico) = o focinho."),
    "copa": ("alacena; copa (de árbol); el Mundial", "taça", "Copa = antecocina o el Mundial. La copa de vino = a taça."),
    "escritura": ("escritura notarial o sagrada", "escrita", "Escritura = documento notarial. La escritura (acción) = a escrita."),
    "colar": ("pegar; collar; copiarse en un examen", "coar", "Colar = pegar (o copiarse). Colar (filtrar) = coar."),
    "exquisito": ("(no se usa)", "delicioso", "En portugués se dice delicioso, gostoso; esquisito (con s) = raro."),
    "competência": ("competencia (capacidad)", "competição", "Competência = capacidad. La competencia deportiva = a competição."),
    "sobrado": ("casa de dos plantas", "de sobra", "Sobrado = casa de dos pisos. Tener de sobra = ter de sobra."),
    "apagar": ("borrar; apagar", "desligar", "Apagar = borrar (y la luz). Apagar la tele = desligar."),
    "tarado": ("obseso, pervertido", "bobo", "Tarado = obseso, depravado; ojo, no es solo «tonto»."),
    "gozado": ("gracioso, raro (coloquial)", "divertido", "Gozado = raro o chistoso (que gozado!)."),
    "aborrecido": ("molesto, fastidiado", "entediado", "Aborrecido = molesto, disgustado. Aburrido = entediado, chato."),
    "esposas": ("esposas (mujeres)", "algemas", "Esposas = esposas (mujeres). Las esposas (de la policía) = as algemas."),
    "vitamina": ("licuado de fruta (y vitamina)", "vitamina", "Una vitamina de banana = un licuado de banana."),
    "farol": ("faro; semáforo (en São Paulo)", "poste", "Farol = faro o semáforo (paulista). En Río el semáforo es o sinal."),
    "fila": ("cola (de gente)", "fileira", "Fila = cola (fazer fila). Una fila (de butacas) = uma fileira."),
    "quadra": ("cancha; manzana", "quarteirão", "Quadra = cancha (o manzana en algunas ciudades)."),
    "rapariga": ("chica (Portugal); en Brasil, insulto", "moça / garota", "En Portugal, rapariga = chica; en Brasil es ofensivo: decí moça, garota."),
    "cacho": ("racimo; rulo", "pedaço", "Cacho = racimo o rulo. Un cacho (pedazo) = um pedaço."),
    "trago": ("sorbo; traigo (de trazer)", "drinque", "Trago = sorbo o «traigo». Un trago (bebida) = um drinque."),
    "vulgar": ("común, corriente", "vulgar", "Vulgar puede ser solo «común» (o nome vulgar de uma planta)."),
    "ordenado": ("sueldo (Portugal); ordenado", "salário", "En Portugal, ordenado = sueldo; en Brasil, salário."),
}


# ---------------------------------------------------------------------------
# Grafías españolas que se cuelan (patrón_es, patrón_pt, explicación)
# ---------------------------------------------------------------------------
SPELLING = [
    ("ñ", "nh", "La ñ no existe: se escribe nh (vinho, amanhã, espanhol)."),
    ("ll", "lh", "La ll española se escribe lh cuando suena como ella: brilho, olho, mulher."),
    ("ll", "ch", "Muchas ll iniciales son ch en portugués: chave, chamar, chegar, chover, cheio."),
    ("ll", "l", "Muchas ll se simplifican: ela, aquela, belo, cavalo, castelo."),
    ("j", "lh", "La j de hijo, ojo, mujer, trabajo es lh: filho, olho, mulher, trabalho."),
    ("ción", "ção", "-ción → -ção: estação, informação, canção."),
    ("ciones", "ções", "-ciones → -ções: estações, canções, informações."),
    ("cción", "ção", "-cción → -ção: ação, lição, direção (sin la c)."),
    ("sión", "são", "-sión → -são: televisão, decisão, ocasião."),
    ("siones", "sões", "-siones → -sões: decisões, ocasiões."),
    ("ión", "ião", "-ión → -ião: religião, região, opinião, avião."),
    ("ón", "ão", "-ón → -ão: coração, limão, razão, avião."),
    ("ones", "ões", "-ones → -ões: corações, limões, razões."),
    ("án", "ão", "-án → -ão: capitão, alemão."),
    ("an", "ão", "-an final → -ão: pão, mão."),
    ("ano", "ão", "-ano → -ão en muchas palabras: verão, irmão, mão, cristão."),
    ("ana", "ã", "-ana → -ã en muchas palabras: irmã, lã, maçã, manhã."),
    ("ino", "inho", "-ino → -inho: vinho, caminho, vizinho, moinho."),
    ("ina", "inha", "-ina → -inha: cozinha, farinha, rainha."),
    ("ona", "oa", "-ona → -oa: pessoa, coroa, boa, Lisboa."),
    ("eno", "eio", "-eno → -eio: cheio, freio, alheio, seio."),
    ("ena", "eia", "-ena → -eia: ceia, veia, areia, baleia, sereia."),
    ("una", "ua", "La n entre vocales a veces cae: lua (luna), coroa (corona)."),
    ("dad", "dade", "-dad → -dade: cidade, verdade, universidade."),
    ("tad", "dade", "-tad → -dade: liberdade, vontade, metade."),
    ("tud", "tude", "-tud → -tude: juventude, atitude, virtude."),
    ("ble", "vel", "-ble → -vel: possível, agradável, responsável."),
    ("bles", "veis", "-bles → -veis: possíveis, agradáveis, responsáveis."),
    ("aje", "agem", "-aje → -agem (y es femenino): a viagem, a mensagem, a garagem."),
    ("ajes", "agens", "-ajes → -agens: viagens, mensagens."),
    ("ue", "o", "El diptongo ue suele ser o: porta, fogo, novo, forte, bom."),
    ("ie", "e", "El diptongo ie suele ser e: terra, sete, pé, tempo, pedra."),
    ("n", "m", "La n final española suele ser m: um, bem, também, com, sem, algum."),
    ("z", "ç", "La z ante a, o, u suele ser ç: cabeça, braço, açúcar, praça."),
    ("ce", "ze", "Muchas c españolas ante e/i suenan y se escriben z: fazer, dizer, dez, doze."),
    ("nce", "nze", "-nce → -nze en los números: once → onze, quince → quinze."),
    ("ecir", "izer", "-ecir → -izer: dizer, bendizer."),
    ("ener", "er", "-ener → -er en los derivados de tener: ter, manter, obter, conter."),
    ("oner", "or", "-oner → -or en los derivados de poner: pôr, compor, propor, supor."),
    ("enir", "ir", "-enir → -ir en los derivados de venir: vir, intervir, convir."),
    ("olor", "or", "La l entre vocales a veces cae: cor, dor, odor."),
    ("alir", "air", "La l entre vocales a veces cae: sair (salir)."),
    ("ct", "t", "Desde el Acuerdo de 1990, ct → t: ato, direto, exato, correto, fato."),
    ("pt", "t", "pt → t en muchas palabras: ótimo, adotar, Egito."),
    ("cl", "ch", "cl latino → ch: chave (clave)."),
    ("pl", "pr", "pl → pr en muchas palabras: praia, prata, praça, prazer."),
    ("bl", "br", "bl → br en muchas palabras: branco, obrigado, nobre."),
    ("cl", "cr", "cl → cr en algunas palabras: cravo, escravo."),
    ("fl", "fr", "fl → fr en algunas palabras: fraco, frouxo."),
    ("b", "v", "Muchas b españolas son v: dever, haver, escrever, governo, cavalo."),
    ("h", "f", "Muchas h iniciales españolas vienen de una f latina que el portugués conserva: falar, fazer, filho, farinha."),
    ("ed", "ede", "-ed final → -ede: parede, rede, sede."),
    ("mbre", "me", "-mbre → -me: nome, fome."),
    ("umbre", "ume", "-umbre → -ume: costume, cume."),
    ("eo", "eu", "-eo final → -eu: museu, troféu, europeu, ateu."),
    ("ero", "eiro", "-ero → -eiro: primeiro, dinheiro, janeiro, carteiro."),
    ("era", "eira", "-era → -eira: carreira, madeira, fronteira, primeira."),
    ("ch", "it", "El ch de noche, leche, ocho, mucho es it en portugués: noite, leite, oito, muito."),
    ("o", "ou", "Muchas o españolas son ou: ouro, outro, pouco, touro, louco."),
    ("y", "j", "La y de ayudar, ya, mayo a veces es j o i: ajudar, já, maio."),
    ("y", "i", "La y española como vocal o semivocal se escribe i: maio, praia, rei, lei."),
    ("s", "ss", "La s sorda entre vocales se escribe ss: passar, pessoa, nosso, assim."),
    ("isimo", "íssimo", "El superlativo es -íssimo, con doble s: lindíssimo, caríssimo."),
    ("ales", "ais", "-ales → -ais en plural: animais, jornais, normais."),
    ("eles", "éis", "-eles → -éis en plural: papéis, hotéis, pastéis."),
    ("oles", "óis", "-oles → -óis en plural: espanhóis, faróis, lençóis."),
    ("iles", "eis", "-iles (átono) → -eis en plural: fáceis, difíceis, úteis."),
]
