# -*- coding: utf-8 -*-
"""Ejercicios de la estação 2 — Pé na Estrada (semanas 14-26, prefijo s2-).

Cada ítem nombra su semana («w») y la parte de la lección («part») a la que
corresponde.  Regla de oro: un ítem de la semana N solo usa tiempos con
TENSE_WEEK <= N (tools/curriculo.py).  La semana 26 (CHEFÃO) mezcla toda la
estación.

Los ids son s2-<semana>-<nn>, numerados en el orden en que aparecen en este
archivo: para no romperlos, agregá ítems nuevos al final de cada semana.
"""

TOPIC = {14: "gostar", 15: "imperfeito", 16: "pronomes", 17: "futuro",
         18: "condicional", 19: "comparativos", 20: "indefinidos",
         21: "perfeito_composto", 22: "passiva", 23: "subjuntivo",
         24: "conjuncoes", 25: "relativos", 26: "chefao_b1"}

P_CH = "Elegí la forma correcta."
P_CL = "Completá."
P_TR = "Traducí al portugués."
P_FX = "Encontrá el error: tocá lo que está mal y corregilo."
P_GD = "Mirá los tres ejemplos y completá el cuarto."
P_SC = "Leé las frases y descubrí la regla."
P_TY = "Escribí la forma."
P_CB = "Uní las frases en una sola usando el conector entre paréntesis."

_N = {}


def _base(w, part, typ, prompt, stem, answer, note, alt=None, **kw):
    _N[w] = _N.get(w, 0) + 1
    d = dict(id="s2-%d-%02d" % (w, _N[w]), w=w, part=part,
             level="A2" if w <= 16 else "B1", type=typ, topic=TOPIC[w],
             prompt=prompt, stem=stem, answer=answer, alt=list(alt or []),
             note=note)
    d.update(kw)
    return d


def ch(w, part, stem, options, answer, note, prompt=P_CH):
    return _base(w, part, "choice", prompt, stem, answer, note, options=options)


def cl(w, part, stem, answer, note, alt=None, prompt=P_CL):
    return _base(w, part, "cloze", prompt, stem, answer, note, alt)


def tr(w, part, stem, answer, alt, note):
    return _base(w, part, "translate", P_TR, stem, answer, note, alt)


def fx(w, part, stem, bad, good, cat, note):
    return _base(w, part, "fixerr", P_FX, stem, stem.replace(bad, good, 1), note,
                 bad=bad, good=good, cat=cat)


def gd(w, part, lead, stem, answer, trap, note, alt=None, prompt=P_GD):
    return _base(w, part, "garden", prompt, stem, answer, note, alt, lead=lead, trap=trap)


def sc(w, part, data, stem, options, answer, note):
    return _base(w, part, "scopri", P_SC, stem, answer, note, data=data, options=options)


def ty(w, part, prompt, stem, answer, note, alt=None):
    return _base(w, part, "typed", prompt, stem, answer, note, alt)


def cb(w, part, stem, answer, alt, note):
    return _base(w, part, "combina", P_CB, stem, answer, note, alt)


ITEMS = []

# ============================================================================
# Semana 14 — Gostar de e verbos com preposição
#   part 0: gostar de · part 1: verbos con preposición · part 2: achar
# ============================================================================
W = 14
ITEMS += [
    # --- part 0: gostar de ---
    ch(W, 0, "Eu ___ muito de pão de queijo.", ["gosto", "gosta", "me gosta"], "gosto",
       "Con gostar, la persona es el sujeto: eu gosto. No hay pronombre «me» delante."),
    ch(W, 0, "Os cariocas ___ de praia no fim de semana.", ["gostam", "gosta", "gostamos"], "gostam",
       "El verbo concuerda con los que sienten el gusto (os cariocas), no con la playa."),
    ch(W, 0, "A Sofía gosta ___ música brasileira.", ["da", "de", "a"], "da",
       "gostar de + a música = da música: la preposición se funde con el artículo."),
    ch(W, 0, "Você gosta ___ biscoito Globo?", ["do", "de o", "o"], "do",
       "de + o = do, siempre contraído: «de o» no se escribe. Y gostar nunca va sin de."),
    ch(W, 0, "— Você gostou do show? — ___!", ["Gostei", "Gostou", "Me gostou"], "Gostei",
       "Se responde repitiendo el verbo en primera persona: gostei (me gustó). «Me gostou» es calco del español."),
    ch(W, 0, "A gente ___ de jogar futevôlei em Copacabana.", ["gosta", "gostamos", "gostam"], "gosta",
       "«a gente» (nosotros) lleva el verbo en tercera del singular: a gente gosta."),
    cl(W, 0, "Eu gosto ___ samba.", "do",
       "gostar de + o samba = do samba.", prompt="Completá con de + artículo."),
    cl(W, 0, "Nós gostamos ___ praias do Rio.", "das",
       "gostar de + as praias = das praias.", prompt="Completá con de + artículo."),
    cl(W, 0, "Ela ___ (gostar) de dançar forró.", "gosta",
       "Ela es el sujeto: ela gosta. Lo que le gusta (dançar) va tras de."),
    cl(W, 0, "Ontem nós ___ (gostar) muito da feijoada.", "gostamos",
       "En los verbos en -ar, la forma de nós es igual en presente y en perfeito: gostamos."),
    cl(W, 0, "Vocês ___ (gostar) do jogo no Maracanã ontem?", "gostaram",
       "Perfeito de vocês: gostaram. «¿Les gustó?» = vocês gostaram?"),
    cl(W, 0, "Não gosto ___ acordar cedo no domingo.", "de",
       "Ante infinitivo va de solo, sin artículo: gosto de acordar, não gosto de correr."),
    tr(W, 0, "Me gusta el mar.", "Eu gosto do mar", ["Gosto do mar"],
       "La persona es el sujeto (eu gosto) y lo que gusta va con de + o = do."),
    tr(W, 0, "A mi hermana le gustan los gatos.", "A minha irmã gosta de gatos",
       ["Minha irmã gosta de gatos", "A minha irmã gosta dos gatos", "Minha irmã gosta dos gatos"],
       "El verbo va en singular porque concuerda con la hermana, no con los gatos: minha irmã gosta."),
    tr(W, 0, "¿Te gustó la película?", "Você gostou do filme?",
       ["Gostou do filme?", "Tu gostaste do filme?", "Você gostou do filme"],
       "«¿Te gustó?» = você gostou? El sujeto es la persona; filme es masculino: do filme."),
    tr(W, 0, "Nos gusta bailar samba.", "A gente gosta de dançar samba",
       ["Nós gostamos de dançar samba", "Gostamos de dançar samba", "A gente gosta de sambar",
        "Nós gostamos de sambar", "Gostamos de sambar"],
       "gostar de + infinitivo, sin artículo. Con a gente, verbo en singular."),
    fx(W, 0, "Me gosta muito o Rio de Janeiro.", "Me gosta muito o", "Eu gosto muito do", "gostar",
       "En portugués no existe «me gosta»: la persona es el sujeto (eu gosto) y lo que gusta va con de (do Rio)."),
    fx(W, 0, "Nós gostamos o show de ontem.", "gostamos o", "gostamos do", "regencia",
       "gostar siempre pide de: gostamos do show. Sin la preposición, la frase queda coja."),
    gd(W, 0, [["o samba", "gosto do samba"], ["a praia", "gosto da praia"], ["os filmes", "gosto dos filmes"]],
       "dançar → ___", "gosto de dançar", "gosto do dançar",
       "Con sustantivo, de se contrae con el artículo; con infinitivo no hay artículo: gosto de dançar."),
    sc(W, 0, ["Eu gosto de café.", "A Bia gosta de café.", "Nós gostamos de café.",
              "Eu gosto dos blocos.", "Os turistas gostam do Rio.", "Você gosta de samba?"],
       "¿Con qué concuerda el verbo gostar?",
       ["Con la persona que siente el gusto.", "Con la cosa que gusta, como en español.",
        "Va siempre en tercera persona del singular."],
       "Con la persona que siente el gusto.",
       "Gostar funciona como «amar»: el sujeto es quien siente el gusto (eu gosto, eles gostam). Lo que gusta va detrás, con de."),
    ty(W, 0, "Escribí «gostar» en perfeito para «eu».", "eu ___ (gostar)", "gostei",
       "Perfeito regular en -ar: gostei, gostou, gostamos, gostaram. «Me gustó» = gostei."),

    # --- part 1: verbos con preposición ---
    ch(W, 1, "Preciso ___ um protetor solar.", ["de", "a", "em"], "de",
       "precisar de + sustantivo: preciso de protetor. La preposición no se puede omitir."),
    ch(W, 1, "Você lembra ___ nome dela?", ["do", "no", "ao"], "do",
       "lembrar de (acordarse de) + o nome = do nome."),
    ch(W, 1, "Eu penso muito ___ minha avó.", ["na", "da", "a"], "na",
       "pensar em + a = na: penso na minha avó. Como «pensar en», pero contraído."),
    ch(W, 1, "O preço da viagem depende ___ dia.", ["do", "de o", "no"], "do",
       "depender de + o = do. La contracción es obligatoria."),
    ch(W, 1, "Ontem sonhei ___ a praia de Ipanema.", ["com", "em", "de"], "com",
       "sonhar com = soñar con: sonhei com a praia."),
    cl(W, 1, "Nós precisamos ___ um táxi para o aeroporto.", "de",
       "precisar de + sustantivo: precisamos de um táxi."),
    cl(W, 1, "Você lembra ___? (de + ele)", "dele",
       "de + ele = dele: lembra dele? (¿te acordás de él?)."),
    cl(W, 1, "Eu penso ___ você todos os dias.", "em",
       "pensar em: penso em você. Ante você no hay contracción."),
    cl(W, 1, "Tudo depende ___ preço.", "do",
       "depender de + o preço = do preço."),
    cl(W, 1, "Ela sonhou ___ o Carnaval.", "com",
       "sonhar com: ela sonhou com o Carnaval."),
    tr(W, 1, "Necesito un café.", "Preciso de um café", ["Eu preciso de um café"],
       "precisar de + sustantivo: preciso de um café. «Preciso um café» es error."),
    tr(W, 1, "¿Te acordás de Ana?", "Você lembra da Ana?",
       ["Você se lembra da Ana?", "Lembra da Ana?", "Se lembra da Ana?", "Você lembra de Ana?",
        "Você se lembra de Ana?", "Tu lembras da Ana?", "Tu te lembras da Ana?", "Você lembra da Ana"],
       "«acordarse de» = lembrar de o lembrar-se de. Con nombre propio, lo normal es el artículo: da Ana."),
    tr(W, 1, "Pienso en vos.", "Penso em você",
       ["Eu penso em você", "Penso em ti", "Eu penso em ti"],
       "pensar em = pensar en: penso em você."),
    fx(W, 1, "Eu preciso dinheiro para o ônibus.", "preciso dinheiro", "preciso de dinheiro", "regencia",
       "Con sustantivo, precisar pide de: preciso de dinheiro."),
    gd(W, 1, [["o Rio", "penso no Rio"], ["a praia", "penso na praia"], ["os amigos", "penso nos amigos"]],
       "ela → ___", "penso nela", "penso em ela",
       "em también se funde con ele / ela: nele, nela. «Penso em ela» no se escribe."),
    gd(W, 1, [["o Pedro", "lembro do Pedro"], ["a Ana", "lembro da Ana"], ["o show", "lembro do show"]],
       "ele → ___", "lembro dele", "lembro de ele",
       "de + ele = dele, de + ela = dela: lembro dele, gosto dela, preciso dele."),
    sc(W, 1, ["Penso no Rio.", "Penso na praia.", "Moro no Leblon.",
              "Acredito nele.", "Confio na Bia.", "Penso em você."],
       "¿Qué pasa con em delante de un artículo o de ele / ela?",
       ["Se funde con ellos: em + o = no, em + ela = nela.",
        "Desaparece: penso o Rio, acredito ele.",
        "Se funde solo con nombres de lugar."],
       "Se funde con ellos: em + o = no, em + ela = nela.",
       "em + o/a/os/as = no/na/nos/nas; em + ele/ela = nele/nela. Ante você no hay contracción: penso em você."),
    ty(W, 1, "Escribí la contracción.", "de + ela = ___", "dela",
       "de + ela = dela; de + ele = dele. Sirven con gostar, lembrar, precisar: gosto dela."),

    # --- part 2: achar ---
    ch(W, 2, "— Você vai à praia amanhã? — Eu ___ que sim.", ["acho", "acha", "achou"], "acho",
       "achar que = creer, opinar: eu acho que sim."),
    ch(W, 2, "Onde você ___ essas fotos antigas?", ["achou", "acha", "achei"], "achou",
       "achar + objeto = encontrar. Perfeito de você: achou."),
    cl(W, 2, "O que vocês ___ (achar) do Pão de Açúcar?", "acham",
       "O que vocês acham? = ¿qué les parece? Presente de vocês: acham."),
    cl(W, 2, "Ontem eu ___ (achar) cem reais na rua!", "achei",
       "achar = encontrar. Perfeito de eu: achei."),
    tr(W, 2, "Creo que no.", "Acho que não", ["Eu acho que não"],
       "Para opinar, lo natural en Brasil es achar que: acho que não."),
    fx(W, 2, "Eu creo que o bar fecha às duas.", "creo", "acho", "espanol",
       "«creo» es español. En portugués sería creio (formal y poco usado); lo natural es acho que."),
]

# ============================================================================
# Semana 15 — Pretérito imperfeito
#   part 0: forma · part 1: imperfeito o perfeito · part 2: interrumpida y cambios de sentido
# ============================================================================
W = 15
_GP15 = "Mirá los tres ejemplos (imperfeito, eu) y completá el cuarto."
ITEMS += [
    # --- part 0: forma ---
    ch(W, 0, "Antigamente nós ___ na rua todo dia.", ["brincávamos", "brincavamos", "brincábamos"], "brincávamos",
       "Imperfeito de -ar: -ava, con v. La forma de nós lleva tilde: brincávamos."),
    ch(W, 0, "Meu avô ___ um bar na Lapa.", ["tinha", "tenia", "tia"], "tinha",
       "ter es irregular en imperfeito: tinha, tinha, tínhamos, tinham. «tenia» es calco del español."),
    ch(W, 0, "Vocês ___ de Niterói de barca todo dia?", ["vinham", "viam", "veniam"], "vinham",
       "vir → vinha, vinham. Viam es de ver (veían)."),
    ch(W, 0, "Naquela época, o bairro ___ muito tranquilo.", ["era", "eram", "éramos"], "era",
       "ser → era (eu, ele), éramos (nós), eram (eles). O bairro es singular: era."),
    ch(W, 0, "Minha mãe ___ a mesa enquanto eu lavava a louça.", ["punha", "ponia", "põe"], "punha",
       "pôr → punha en imperfeito: acción de fondo, simultánea con lavava."),
    cl(W, 0, "Eu ___ (comer) açaí todo dia depois da praia.", "comia",
       "Imperfeito de -er: -ia. Costumbre en el pasado: eu comia."),
    cl(W, 0, "Nós ___ (morar) em Santa Teresa.", "morávamos",
       "morar → morávamos, con tilde en la a."),
    cl(W, 0, "As crianças ___ (sair) da escola às cinco.", "saíam",
       "Los verbos en -air llevan tilde en la i: saía, saíam."),
    cl(W, 0, "Quando eu ___ (ser) criança, adorava o carnaval.", "era",
       "ser → era. Descripción de una etapa de la vida: imperfeito."),
    cl(W, 0, "Eles ___ (ter) uma casa em Búzios.", "tinham",
       "ter → tinham en imperfeito."),
    cl(W, 0, "Minha avó sempre ___ (dizer) que o Rio era outro.", "dizia",
       "dizer es regular en imperfeito: dizia. Sempre + costumbre = imperfeito."),
    tr(W, 0, "Cuando era chico, vivía en Río.", "Quando eu era criança, morava no Rio",
       ["Quando era criança, morava no Rio", "Quando eu era criança, eu morava no Rio",
        "Quando eu era pequeno, morava no Rio", "Quando era pequeno, morava no Rio",
        "Quando eu era pequeno, eu morava no Rio", "Quando eu era menino, morava no Rio",
        "Quando era menino, morava no Rio"],
       "Etapa de la vida y costumbre: los dos verbos en imperfeito. «Río» lleva artículo: no Rio."),
    tr(W, 0, "Teníamos un perro.", "Nós tínhamos um cachorro",
       ["Tínhamos um cachorro", "A gente tinha um cachorro", "Nós tínhamos um cão", "Tínhamos um cão",
        "A gente tinha um cão"],
       "ter → tínhamos (con tilde) o, con a gente, tinha."),
    tr(W, 0, "Mi abuelo iba a la playa todos los días.", "Meu avô ia à praia todo dia",
       ["O meu avô ia à praia todo dia", "Meu avô ia à praia todos os dias", "O meu avô ia à praia todos os dias",
        "Meu avô ia para a praia todo dia", "Meu avô ia pra praia todo dia", "O meu avô ia para a praia todos os dias"],
       "ir es regular en imperfeito: ia, ia, íamos, iam. Costumbre: ia à praia todo dia."),
    fx(W, 0, "Quando eu era pequeno, eu tenia um cachorro.", "tenia", "tinha", "verbo_irregular",
       "Imperfeito de ter: tinha, con nh. «tenia» mezcla el español con el portugués."),
    fx(W, 0, "Nós falavamos português em casa.", "falavamos", "falávamos", "ortografia",
       "La forma de nós del imperfeito lleva tilde: falávamos, comíamos, abríamos."),
    gd(W, 0, [["comer", "comia"], ["beber", "bebia"], ["correr", "corria"]], "ter → ___", "tinha", "tenia",
       "ter es uno de los cuatro irregulares del imperfeito: tinha. El patrón -ia y el español «tenía» empujan a «tenia».",
       prompt=_GP15),
    gd(W, 0, [["abrir", "abria"], ["partir", "partia"], ["dormir", "dormia"]], "vir → ___", "vinha", "venia",
       "vir → vinha (como ter → tinha). Nada de «venia».", prompt=_GP15),
    gd(W, 0, [["querer", "queria"], ["fazer", "fazia"], ["dizer", "dizia"]], "pôr → ___", "punha", "ponia",
       "pôr → punha, punha, púnhamos, punham. Es el cuarto irregular, junto con era, tinha y vinha.",
       prompt=_GP15),
    sc(W, 0, ["Eu falava.", "Ela comia.", "Nós falávamos.", "Nós comíamos.", "Nós abríamos.", "Eles falavam."],
       "¿Qué forma del imperfeito lleva tilde?",
       ["Solo la de nós: falávamos, comíamos, abríamos.",
        "Todas las formas de los verbos en -er e -ir.",
        "Ninguna: el imperfeito nunca lleva tilde."],
       "Solo la de nós: falávamos, comíamos, abríamos.",
       "La tilde marca que nós es esdrújula: falávamos, comíamos. Las otras formas son llanas (falava, comia), salvo los verbos en -air/-uir (saía)."),
    ty(W, 0, "Escribí el imperfeito de «ser» para «nós».", "nós ___ (ser)", "éramos",
       "ser: era, era, éramos, eram. Esdrújula: lleva tilde."),
    ty(W, 0, "Escribí el imperfeito de «vir» para «eles».", "eles ___ (vir)", "vinham",
       "vir: vinha, vinha, vínhamos, vinham."),

    # --- part 1: imperfeito o perfeito ---
    ch(W, 1, "Antigamente, todo verão a gente ___ para Búzios.", ["ia", "foi", "fomos"], "ia",
       "Costumbre en el pasado (todo verão): imperfeito."),
    ch(W, 1, "Ontem ___ à praia e encontrei a Bia.", ["fui", "ia", "era"], "fui",
       "Hecho puntual que avanza el relato (ontem): perfeito."),
    ch(W, 1, "___ três da tarde quando o bloco começou.", ["Eram", "Foram", "Era"], "Eram",
       "La hora en el pasado va en imperfeito, y en plural con más de una hora: eram três."),
    ch(W, 1, "Em 2019 nós ___ para São Paulo.", ["mudamos", "mudávamos", "mudava"], "mudamos",
       "Un hecho fechado y único (em 2019): perfeito. En Brasil mudar (de casa) se usa sin «se»."),
    ch(W, 1, "Eu ___ dez anos em Niterói e depois voltei para o Rio.", ["morei", "morava", "moro"], "morei",
       "Aunque dure diez años, es un período cerrado que el relato deja atrás: perfeito."),
    cl(W, 1, "Quando eu era criança, ___ (costumar) passar o verão em Petrópolis.", "costumava",
       "costumar + infinitivo = soler; en el pasado, costumava."),
    cl(W, 1, "A casa ___ (ser) velha e tinha um quintal enorme.", "era",
       "Descripción del decorado: imperfeito."),
    cl(W, 1, "Um dia, meu pai ___ (chegar) em casa com um cachorro.", "chegou",
       "Um dia introduce un hecho que avanza el relato: perfeito."),
    cl(W, 1, "Eu ___ (ter) oito anos quando vi o mar pela primeira vez.", "tinha",
       "La edad en el pasado va en imperfeito: eu tinha oito anos."),
    tr(W, 1, "Hacía calor y había mucha gente en la playa.", "Fazia calor e tinha muita gente na praia",
       ["Fazia calor e havia muita gente na praia", "Estava calor e tinha muita gente na praia",
        "Estava quente e tinha muita gente na praia", "Fazia calor e tinha muitas pessoas na praia",
        "Fazia calor e havia muitas pessoas na praia", "Fazia muito calor e tinha muita gente na praia"],
       "Clima y escena de fondo: imperfeito. «Había» = tinha (habla) o havia; muita gente, nunca «muy»."),
    tr(W, 1, "Todos los domingos íbamos al Maracanã.", "Todo domingo a gente ia ao Maracanã",
       ["Todo domingo nós íamos ao Maracanã", "Todos os domingos a gente ia ao Maracanã",
        "Todos os domingos nós íamos ao Maracanã", "Todo domingo íamos ao Maracanã",
        "Todos os domingos íamos ao Maracanã", "Todo domingo a gente ia no Maracanã"],
       "Costumbre: imperfeito. a + o = ao; en el habla también ia no Maracanã."),
    tr(W, 1, "Viví dos años en Salvador.", "Morei dois anos em Salvador",
       ["Eu morei dois anos em Salvador", "Eu morei por dois anos em Salvador", "Morei por dois anos em Salvador",
        "Vivi dois anos em Salvador", "Eu vivi dois anos em Salvador"],
       "Período cerrado: perfeito, aunque dure. Con ciudades, em a secas: em Salvador."),
    fx(W, 1, "Ontem eu acordava cedo e fui correr no Aterro.", "acordava", "acordei", "tempo",
       "Ontem + una acción única que abre la secuencia: perfeito (acordei)."),
    sc(W, 1, ["Eu morava em Botafogo.", "Um dia, mudamos para o Leblon.", "Fazia sol.",
              "De repente, começou a chover.", "Ela tinha dez anos.", "Nesse dia, ela ganhou uma bicicleta."],
       "¿Qué cuenta cada tiempo?",
       ["El imperfeito pinta el fondo; el perfeito cuenta los hechos que avanzan.",
        "El imperfeito es para acciones largas; el perfeito, para las cortas.",
        "El perfeito es para el pasado reciente; el imperfeito, para el lejano."],
       "El imperfeito pinta el fondo; el perfeito cuenta los hechos que avanzan.",
       "No decide la duración sino la mirada: decorado, costumbre y estados en imperfeito; lo que pasó, en perfeito."),

    # --- part 2: acción interrumpida y verbos que cambian ---
    ch(W, 2, "Eu ___ dormindo quando você ligou.", ["estava", "estive", "estou"], "estava",
       "Acción en curso interrumpida: estava + gerúndio."),
    ch(W, 2, "Eu não ___ que ela era casada; soube ontem.", ["sabia", "soube", "sabi"], "sabia",
       "Estado de conocimiento (no lo sabía): imperfeito. Soube = me enteré."),
    ch(W, 2, "___ a Bia numa festa em Santa Teresa em 2018.", ["Conheci", "Conhecia", "Conhecí"], "Conheci",
       "El momento de conocer a alguien es un hecho: perfeito, sin tilde (conheci)."),
    cl(W, 2, "Enquanto eu ___ (tomar) banho, o telefone tocou.", "tomava",
       "Acción de fondo interrumpida: imperfeito (o estava tomando).", alt=["estava tomando"]),
    cl(W, 2, "Nós estávamos jantando quando a luz ___ (acabar).", "acabou",
       "Lo que interrumpe la acción en curso va en perfeito."),
    cl(W, 2, "Eu ___ (querer) ir ao show, mas estava doente.", "queria",
       "Un deseo que no se cumplió: imperfeito, como «quería»."),
    tr(W, 2, "Estaba lloviendo cuando salí.", "Estava chovendo quando eu saí",
       ["Estava chovendo quando saí", "Chovia quando eu saí", "Chovia quando saí"],
       "Fondo en curso (estava chovendo) + hecho que ocurre (saí)."),
    tr(W, 2, "Conocí a Rafa en Lapa.", "Conheci o Rafa na Lapa",
       ["Eu conheci o Rafa na Lapa", "Conheci Rafa na Lapa", "Eu conheci Rafa na Lapa"],
       "Sin «a» personal: conheci o Rafa. El barrio lleva artículo: na Lapa."),
    fx(W, 2, "Ontem conheci ao namorado da Ana.", "ao namorado", "o namorado", "a_personal",
       "En portugués no hay «a» personal: conheci o namorado."),
]

# ============================================================================
# Semana 16 — Pronomes objeto
#   part 0: cuadro y posición · part 1: -lo/-la, «vi ele», lhe · part 2: con preposición
# ============================================================================
W = 16
ITEMS += [
    # --- part 0 ---
    ch(W, 0, "A Bia ___ ligou ontem à noite.", ["me", "mi", "eu"], "me",
       "Objeto de primera persona: me. «mi» es el posesivo del español; eu es sujeto."),
    ch(W, 0, "Comprei o livro e ___ li na praia. (escrito)", ["o", "lo", "lhe"], "o",
       "«lo» es o en portugués: igual al artículo. lhe es indirecto."),
    ch(W, 0, "Vi as meninas no calçadão e ___ cumprimentei.", ["as", "las", "lhes"], "as",
       "Directo femenino plural: as. «las» es español; lhes es indirecto."),
    ch(W, 0, "Nós ___ demos um presente, senhor.", ["lhe", "o", "le"], "lhe",
       "Indirecto formal (a usted): lhe. «le» no existe en portugués."),
    ch(W, 0, "Ela ___ na festa.", ["não me viu", "me não viu", "não viu-me"], "não me viu",
       "Con não, el pronombre va entre não y el verbo, en todas las variedades: não me viu."),
    cl(W, 0, "— Você viu o João? — Vi, eu ___ vi no metrô. (escrito)", "o",
       "Objeto directo masculino: o. Eu o vi = lo vi."),
    cl(W, 0, "Eu ___ amo. (a vos)", "te",
       "te sirve para tu y, en el habla de Brasil, también para você: eu te amo."),
    cl(W, 0, "Ele ___ deu o número dele. (a mí)", "me",
       "Indirecto de primera persona: me. Va delante del verbo: ele me deu."),
    cl(W, 0, "Nossos amigos ___ convidaram para o churrasco. (a nosotros)", "nos",
       "nos sirve para directo e indirecto, como en español."),
    tr(W, 0, "Te llamo mañana.", "Te ligo amanhã",
       ["Eu te ligo amanhã", "Ligo para você amanhã", "Eu ligo para você amanhã", "Ligo pra você amanhã",
        "Eu ligo pra você amanhã", "Vou te ligar amanhã", "Eu vou te ligar amanhã"],
       "En Brasil el pronombre va delante: te ligo. También ligo para você."),
    tr(W, 0, "No me vio.", "Ele não me viu", ["Não me viu", "Ela não me viu", "Você não me viu"],
       "não + pronombre + verbo: não me viu."),
    tr(W, 0, "¿Me pasás la sal?", "Me passa o sal?",
       ["Você me passa o sal?", "Me passa o sal", "Você pode me passar o sal?", "Pode me passar o sal?"],
       "En el habla de Brasil se empieza con el pronombre: me passa? Ojo: o sal es masculino."),
    fx(W, 0, "Ela não viu-me na festa.", "não viu-me", "não me viu", "colocacao",
       "La negación atrae el pronombre: não me viu. Ni en Portugal se pega detrás después de não."),
    sc(W, 0, ["Ela me ligou.", "Eu te amo.", "Ele não me viu.", "Você me empresta a caneta?",
              "A gente se vê amanhã.", "Me dá um abraço!"],
       "¿Dónde va el pronombre en el portugués hablado de Brasil?",
       ["Delante del verbo, incluso al comienzo de la frase.",
        "Siempre detrás del verbo, unido con guion.",
        "Delante solo si hay não; si no, detrás."],
       "Delante del verbo, incluso al comienzo de la frase.",
       "La próclise es la marca de Brasil: me dá, te amo. La norma escrita evita empezar la frase con el pronombre (Dê-me)."),

    # --- part 1 ---
    ch(W, 1, "Quero ___ amanhã. (vender + a casa, escrito)", ["vendê-la", "vender-la", "vendé-la"], "vendê-la",
       "Tras -r el pronombre pasa a -la y la r cae: vendê-la. La tilde es circunfleja porque la e es cerrada."),
    ch(W, 1, "Esse bolo? Vou ___ agora. (escrito)", ["comê-lo", "comer-lo", "comê-o"], "comê-lo",
       "comer + o = comê-lo: cae la r, o se vuelve lo y la e lleva circunflejo."),
    ch(W, 1, "— Você comprou o pão? — ___.", ["Comprei", "Comprei-lo", "Lo comprei"], "Comprei",
       "Al hablar se contesta con el verbo solo (objeto nulo): comprei. «Lo» no existe en portugués.",
       prompt="Elegí lo más natural al hablar."),
    ch(W, 1, "Posso ___ fazer uma pergunta, senhora?", ["lhe", "la", "a"], "lhe",
       "Indirecto formal: lhe (le). Fazer uma pergunta a alguém: indirecto."),
    ch(W, 1, "Comprei um presente e dei ___.", ["para ela", "se lo", "la"], "para ela",
       "No existe «se lo»: para el indirecto de tercera se dice para ela / a ela, o lhe en lo escrito."),
    cl(W, 1, "Vou ___ amanhã. (comprar + o, escrito)", "comprá-lo",
       "comprar + o = comprá-lo: cae la r, o pasa a lo y la a lleva tilde."),
    cl(W, 1, "Não consigo ___. (abrir + a, escrito)", "abri-la",
       "abrir + a = abri-la, sin tilde: los verbos en -ir no la llevan."),
    cl(W, 1, "Quero ___ hoje. (ver + a, escrito)", "vê-la",
       "ver + a = vê-la."),
    cl(W, 1, "Eu vi ___ ontem na Lapa. (a Rafa, como se dice al hablar)", "ele",
       "En el habla de Brasil el objeto de tercera es ele / ela: vi ele. Al escribir: eu o vi."),
    cl(W, 1, "Vou ___ contar um segredo. (a usted, formal)", "lhe",
       "Indirecto formal: lhe, delante del infinitivo en Brasil: vou lhe contar."),
    tr(W, 1, "Lo vi ayer. (registro escrito)", "Eu o vi ontem", ["Vi-o ontem"],
       "En lo escrito, o delante del verbo cuando hay sujeto: eu o vi. En la charla: vi ele."),
    tr(W, 1, "Voy a comprarlo mañana. (registro escrito)", "Vou comprá-lo amanhã",
       ["Eu vou comprá-lo amanhã"],
       "Tras infinitivo: comprá-lo. Al hablar se diría vou comprar amanhã (objeto nulo)."),
    tr(W, 1, "Le di el regalo a ella.", "Dei o presente para ela",
       ["Eu dei o presente para ela", "Dei o presente a ela", "Eu dei o presente a ela", "Dei o presente pra ela",
        "Eu dei o presente pra ela", "Dei-lhe o presente", "Eu lhe dei o presente"],
       "El portugués no duplica el objeto («le... a ella»): dei o presente para ela, o eu lhe dei."),
    fx(W, 1, "Vou comprar-lo amanhã.", "comprar-lo", "comprá-lo", "pronome",
       "Tras -r el pronombre es -lo y la r cae: comprá-lo. «comprar-lo» nunca."),
    fx(W, 1, "Eu se lo disse ontem.", "se lo disse", "disse para ele", "espanol",
       "«se lo» es español. En portugués: disse para ele (o disse-lhe, formal)."),
    gd(W, 1, [["comprar o carro", "comprá-lo"], ["ver a praia", "vê-la"], ["fazer o bolo", "fazê-lo"]],
       "abrir a janela → ___", "abri-la", "abrí-la",
       "En -ar y -er la tilde marca la vocal acentuada; en -ir no hace falta: abri-la, parti-lo."),
    gd(W, 1, [["vi o João", "vi-o"], ["conheço a Ana", "conheço-a"], ["comprei os pães", "comprei-os"]],
       "fiz o bolo → ___", "fi-lo", "fiz-o",
       "Tras -z (como tras -r y -s) la consonante cae y el pronombre pasa a -lo: fi-lo. Es registro escrito."),
    sc(W, 1, ["Vou comprá-lo.", "Quero vendê-la.", "Preciso abri-la.", "Vamos fazê-lo.", "Fi-lo ontem.", "Vi-o ontem."],
       "¿Cuándo o / a se vuelven -lo / -la?",
       ["Cuando el verbo termina en -r, -s o -z, que se caen.",
        "Siempre que el pronombre va detrás del verbo.",
        "Solo con verbos en -ar."],
       "Cuando el verbo termina en -r, -s o -z, que se caen.",
       "comprar + o = comprá-lo, fiz + o = fi-lo; tras vocal queda o: vi-o. Tras nasal, -no: dão-no."),
    ty(W, 1, "Escribí «fazer» + «o» en la norma escrita.", "fazer + o = ___", "fazê-lo",
       "Cae la r, o pasa a lo y la e lleva circunflejo: fazê-lo."),

    # --- part 2 ---
    ch(W, 2, "Você vem ___ ao Maracanã?", ["comigo", "com mim", "conmigo"], "comigo",
       "com + eu = comigo (con g: no «conmigo»)."),
    ch(W, 2, "Esse presente é para ___?", ["mim", "mí", "eu"], "mim",
       "Tras preposición: mim, con m final."),
    ch(W, 2, "Eles jantaram ___ ontem.", ["conosco", "com nós", "connós"], "conosco",
       "com + nós = conosco en Brasil."),
    cl(W, 2, "Ela sempre viaja ___. (con él)", "com ele",
       "Solo eu, tu y nós tienen forma propia con com; con él: com ele."),
    cl(W, 2, "Isso fica entre ___ e você.", "mim",
       "Tras entre también va mim: entre mim e você («entre vos y yo»)."),
    cl(W, 2, "Trouxe um café para ___ tomar. (yo)", "eu",
       "Ante infinitivo va el sujeto: para eu tomar. «para mim tomar» es error."),
    cl(W, 2, "Quer sair ___ amanhã? (conmigo)", "comigo",
       "com + eu = comigo."),
    tr(W, 2, "¿Esto es para mí?", "Isso é para mim?", ["Isto é para mim?", "Isso é pra mim?", "Isso é para mim"],
       "«para mí» = para mim."),
    tr(W, 2, "Vení con nosotros.", "Vem conosco", ["Venha conosco", "Vem com a gente", "Venha com a gente"],
       "com + nós = conosco; en el habla, com a gente."),
    fx(W, 2, "O chefe trouxe o documento para mim assinar.", "para mim assinar", "para eu assinar", "pronome",
       "Ante infinitivo el pronombre es sujeto: para eu assinar. Mim solo sin verbo detrás: é para mim."),
    gd(W, 2, [["para mim", "comigo"], ["para ti", "contigo"], ["para você", "com você"]],
       "para nós → ___", "conosco", "com nós",
       "com + nós = conosco. «com nós» solo se usa con un refuerzo: com nós dois, com nós mesmos."),
    ty(W, 2, "Escribí «com» + «eu» en portugués.", "com + eu = ___", "comigo",
       "com + eu = comigo; com + tu = contigo; com + nós = conosco."),
]

# ============================================================================
# Semana 17 — Futuro do presente
#   part 0: forma e irregulares · part 1: hablado / escrito · part 2: previsiones y clima
# ============================================================================
W = 17
ITEMS += [
    # --- part 0 ---
    ch(W, 0, "Amanhã eu ___ com o gerente.", ["falarei", "falaré", "falarai"], "falarei",
       "Futuro: infinitivo + -ei. «falaré» es español."),
    ch(W, 0, "Eles ___ em julho.", ["viajarão", "viajaram", "viajarán"], "viajarão",
       "Futuro de eles: -ão. Viajaram (sin tilde) es el perfeito."),
    ch(W, 0, "Nós ___ tudo amanhã.", ["faremos", "fazeremos", "haremos"], "faremos",
       "fazer pierde -ze-: farei, fará, faremos, farão."),
    ch(W, 0, "Você ___ tempo na sexta?", ["terá", "tenderá", "tendrá"], "terá",
       "ter es regular en futuro: terá. «tendrá» es español."),
    ch(W, 0, "O que ela ___ amanhã na reunião?", ["dirá", "dizerá", "dizirá"], "dirá",
       "dizer → direi, dirá, diremos, dirão."),
    ch(W, 0, "Os convidados ___ de Recife.", ["virão", "vendrão", "vinirão"], "virão",
       "vir es regular en futuro: virei, virá, viremos, virão («vendrán»)."),
    cl(W, 0, "Eu ___ (trazer) o vinho.", "trarei",
       "trazer pierde -ze-: trarei."),
    cl(W, 0, "A gente ___ (sair) às oito.", "sairá",
       "sair es regular en futuro: sairá. Con a gente, tercera del singular."),
    cl(W, 0, "Vocês ___ (poder) entrar depois das nove.", "poderão",
       "poder es regular en futuro: poderão («podrán»)."),
    cl(W, 0, "Nós ___ (pôr) as cadeiras na varanda.", "poremos",
       "pôr → porei, porá, poremos: el infinitivo pierde el circunflejo al sumar la terminación."),
    cl(W, 0, "O professor ___ (corrigir) as provas amanhã.", "corrigirá",
       "Futuro regular: corrigir + á."),
    cl(W, 0, "Eu ___ (ser) o primeiro a chegar.", "serei",
       "ser: serei, será, seremos, serão."),
    tr(W, 0, "Haré lo posible.", "Farei o possível", ["Eu farei o possível"],
       "fazer → farei. «Lo posible» = o possível."),
    tr(W, 0, "Tendremos una reunión el lunes.", "Teremos uma reunião na segunda",
       ["Teremos uma reunião na segunda-feira", "Nós teremos uma reunião na segunda",
        "Nós teremos uma reunião na segunda-feira", "Vamos ter uma reunião na segunda",
        "Vamos ter uma reunião na segunda-feira", "A gente vai ter uma reunião na segunda",
        "A gente vai ter uma reunião na segunda-feira", "Teremos uma reunião segunda-feira",
        "Teremos uma reunião segunda"],
       "ter es regular en futuro: teremos. «El lunes» = na segunda(-feira)."),
    tr(W, 0, "Vendrán mañana.", "Virão amanhã",
       ["Eles virão amanhã", "Elas virão amanhã", "Vocês virão amanhã", "Eles vão vir amanhã",
        "Vão vir amanhã", "Eles vêm amanhã"],
       "vir → virão: sin la d de «vendrán»."),
    fx(W, 0, "Amanhã eu fazerei o jantar.", "fazerei", "farei", "verbo_irregular",
       "fazer es uno de los tres irregulares del futuro: farei."),
    fx(W, 0, "Eles tendrão muito trabalho.", "tendrão", "terão", "espanol",
       "El futuro de ter es regular: terão. La d viene del español."),
    gd(W, 0, [["comer", "comerei"], ["vender", "venderei"], ["beber", "beberei"]], "fazer → ___", "farei", "fazerei",
       "Casi todo es infinitivo + -ei, pero fazer pierde la sílaba -ze-: farei."),
    gd(W, 0, [["escrever", "escreverei"], ["ler", "lerei"], ["correr", "correrei"]], "dizer → ___", "direi", "dizerei",
       "dizer → direi, como fazer → farei."),
    gd(W, 0, [["ter", "terei"], ["poder", "poderei"], ["saber", "saberei"]], "trazer → ___", "trarei", "trazerei",
       "ter, poder y saber son regulares en portugués (al revés que en español); trazer, en cambio, pierde -ze-: trarei."),
    sc(W, 0, ["Eu falarei.", "Ela comerá.", "Nós partiremos.", "Eles farão.", "Você dirá.", "Eu trarei."],
       "¿Cómo se forma el futuro?",
       ["Infinitivo entero + -ei, -á, -emos, -ão; fazer, dizer y trazer pierden -ze-.",
        "Raíz del presente + -rei; los irregulares son los mismos que en español.",
        "Infinitivo sin -r + -ei, -á, -emos, -ão."],
       "Infinitivo entero + -ei, -á, -emos, -ão; fazer, dizer y trazer pierden -ze-.",
       "Base = infinitivo entero (falar-ei). Solo tres irregulares: farei, direi, trarei."),
    ty(W, 0, "Escribí el futuro de «vir» para «eu».", "eu ___ (vir)", "virei",
       "vir es regular: virei («vendré»)."),
    ty(W, 0, "Escribí el futuro de «dizer» para «eles».", "eles ___ (dizer)", "dirão",
       "dizer → direi, dirá, diremos, dirão."),

    # --- part 1 ---
    ch(W, 1, "Amanhã eu ___ cozinhar uma moqueca.", ["vou", "irei", "vai"], "vou",
       "Al hablar, el futuro es ir + infinitivo: vou cozinhar. Irei cozinhar suena a discurso.",
       prompt="Elegí lo más natural en una charla."),
    ch(W, 1, "Sábado a gente ___ para Ilha Grande.", ["vai", "vamos", "irá"], "vai",
       "a gente + tercera del singular; en la charla, presente de ir con valor futuro.",
       prompt="Elegí lo más natural en una charla."),
    ch(W, 1, "(dizer + lhe, eu, futuro, muy formal)", ["Dir-lhe-ei", "Direi-lhe", "Dizer-lhe-ei"], "Dir-lhe-ei",
       "La mesóclise mete el pronombre entre la base (dir-) y la terminación (-ei). En Brasil se prefiere eu lhe direi.",
       prompt="¿Cuál es la forma con el pronombre dentro del verbo?"),
    cl(W, 1, "Amanhã eu ___ trabalhar cedo. (ir, habla)", "vou",
       "vou + infinitivo es el futuro del habla."),
    cl(W, 1, "Eu ___ direi a verdade. (a usted, formal en Brasil)", "lhe",
       "En Brasil se evita la mesóclise poniendo el pronombre delante: eu lhe direi."),
    cl(W, 1, "Semana que vem nós ___ (ir) visitar a Bia. (habla)", "vamos",
       "ir + infinitivo: vamos visitar."),
    tr(W, 1, "Mañana voy a trabajar temprano.", "Amanhã vou trabalhar cedo",
       ["Amanhã eu vou trabalhar cedo", "Eu vou trabalhar cedo amanhã", "Vou trabalhar cedo amanhã",
        "Amanhã trabalharei cedo", "Amanhã eu trabalharei cedo"],
       "vou + infinitivo es lo natural; trabalharei también es correcto, más formal."),
    tr(W, 1, "Te voy a llamar a la noche.", "Vou te ligar à noite",
       ["Eu vou te ligar à noite", "Vou ligar para você à noite", "Eu vou ligar para você à noite",
        "Vou ligar pra você à noite", "Te ligo à noite", "Eu te ligo à noite", "Vou te ligar hoje à noite",
        "Eu vou te ligar hoje à noite"],
       "El pronombre va delante del infinitivo en Brasil: vou te ligar. «a la noche» = à noite."),
    fx(W, 1, "Irei ir à praia amanhã.", "Irei ir", "Irei", "tempo",
       "Futuro de ir: irei, sin repetir el verbo. Al hablar: vou à praia amanhã."),
    sc(W, 1, ["Amanhã vou trabalhar. (charla)", "Sábado a gente vai pra praia. (charla)",
              "O presidente viajará amanhã. (noticia)", "Choverá no litoral. (pronóstico)",
              "Prometo que voltarei. (promesa)", "Vou te ligar depois. (charla)"],
       "¿Cuándo se usa el futuro simple (viajará, choverá)?",
       ["En textos escritos, noticias, pronósticos y promesas; al hablar, vou + infinitivo.",
        "Siempre que la acción es futura, como en español.",
        "Solo para el futuro lejano; para mañana, vou + infinitivo."],
       "En textos escritos, noticias, pronósticos y promesas; al hablar, vou + infinitivo.",
       "El futuro simple es formal o solemne. En una charla, vou + infinitivo o el presente con una marca de tiempo."),

    # --- part 2 ---
    ch(W, 2, "___ que vai chover hoje?", ["Será", "Seria", "Serás"], "Será",
       "Será que...? es la forma brasileña de la pregunta dudosa: ¿irá a llover?"),
    ch(W, 2, "Hoje ___ muito calor no Rio.", ["faz", "fazem", "hace"], "faz",
       "fazer + calor/frio es impersonal: faz, en singular."),
    ch(W, 2, "Olha o céu: amanhã ___ sol.", ["fará", "fazerá", "hará"], "fará",
       "fazer → fará en futuro."),
    ch(W, 2, "Prometo que ___ todo dia.", ["ligarei", "ligaré", "ligarão"], "ligarei",
       "Promesa de eu: ligarei."),
    cl(W, 2, "Segundo a previsão, ___ (chover) muito no fim de semana.", "choverá",
       "Pronóstico escrito: futuro simple. Al hablar: vai chover.", alt=["vai chover"]),
    cl(W, 2, "Hoje ___ (estar) nublado.", "está",
       "Para el clima del momento: estar. Hoje está nublado."),
    cl(W, 2, "___ (ser) que ela esqueceu da reunião?", "Será",
       "Será que + cualquier tiempo: ¿se habrá olvidado?"),
    cl(W, 2, "Amanhã ___ (fazer) frio em Curitiba.", "fará",
       "fazer → fará; al hablar, vai fazer.", alt=["vai fazer"]),
    tr(W, 2, "¿Lloverá mañana?", "Será que vai chover amanhã?",
       ["Vai chover amanhã?", "Choverá amanhã?", "Será que chove amanhã?", "Será que choverá amanhã?"],
       "Para preguntar con duda, lo más brasileño es Será que...?"),
    tr(W, 2, "Hace mucho calor.", "Faz muito calor",
       ["Está muito calor", "Está fazendo muito calor", "Está muito quente"],
       "faz calor (impersonal, singular); muito, nunca «muy» ni «mucho»."),
    tr(W, 2, "Prometo que volveré.", "Prometo que voltarei",
       ["Eu prometo que voltarei", "Prometo que vou voltar", "Eu prometo que vou voltar"],
       "Las promesas admiten el futuro simple: voltarei."),
    fx(W, 2, "Hoje fazem muito calor em Copacabana.", "fazem", "faz", "concordancia",
       "fazer con el clima es impersonal y va en singular: faz calor."),
]

# ============================================================================
# Semana 18 — Futuro do pretérito e cortesia
#   part 0: forma · part 1: cortesía · part 2: sugerir, imaginar, futuro del pasado
# ============================================================================
W = 18
ITEMS += [
    # --- part 0 ---
    ch(W, 0, "Eu ___ de um suco de caju.", ["gostaria", "gostaría", "gustaria"], "gostaria",
       "Condicional: infinitivo + -ia, sin tilde en eu: gostaria."),
    ch(W, 0, "Com mais dinheiro, nós ___ em Santa Teresa.", ["moraríamos", "morariamos", "moraríam"], "moraríamos",
       "Solo la forma de nós lleva tilde: moraríamos."),
    ch(W, 0, "Eu nunca ___ isso.", ["faria", "fazeria", "haria"], "faria",
       "fazer → faria (como farei en futuro)."),
    ch(W, 0, "Vocês ___ um quarto livre para hoje?", ["teriam", "tendriam", "teríam"], "teriam",
       "ter es regular en condicional: teriam («tendrían»)."),
    ch(W, 0, "O que você ___ para ele?", ["diria", "dizeria", "diría"], "diria",
       "dizer → diria, sin tilde."),
    cl(W, 0, "Você ___ (poder) repetir, por favor?", "poderia",
       "poder es regular: poderia («podría»)."),
    cl(W, 0, "Com esse calor, eu ___ (ficar) na praia o dia todo.", "ficaria",
       "Imaginar: condicional. ficar → ficaria."),
    cl(W, 0, "Eu ___ (trazer) mais cerveja, mas o carro está cheio.", "traria",
       "trazer → traria (pierde -ze-)."),
    cl(W, 0, "Nós ___ (sair) mais cedo, mas o metrô está fechado.", "sairíamos",
       "sair es regular: sairíamos («saldríamos»)."),
    cl(W, 0, "Um carro novo ___ (custar) muito caro.", "custaria",
       "Condicional regular: custaria."),
    tr(W, 0, "Nunca diría eso.", "Eu nunca diria isso",
       ["Nunca diria isso", "Eu jamais diria isso", "Jamais diria isso", "Eu nunca diria isto", "Nunca diria isto"],
       "dizer → diria. «eso» = isso."),
    tr(W, 0, "Me gustaría un café.", "Eu gostaria de um café",
       ["Gostaria de um café", "Eu queria um café", "Queria um café"],
       "gostar sigue pidiendo de: gostaria de um café."),
    fx(W, 0, "Eu fazeria tudo por você.", "fazeria", "faria", "verbo_irregular",
       "fazer → faria: los mismos tres irregulares que en futuro."),
    fx(W, 0, "Você podria me ajudar?", "podria", "poderia", "espanol",
       "poder es regular en condicional: poderia. «podria» es español disfrazado."),
    gd(W, 0, [["comer", "comeria"], ["vender", "venderia"], ["beber", "beberia"]], "fazer → ___", "faria", "fazeria",
       "Infinitivo + -ia, salvo fazer, dizer y trazer, que pierden -ze-: faria."),
    gd(W, 0, [["escrever", "escreveria"], ["ler", "leria"], ["correr", "correria"]], "dizer → ___", "diria", "dizeria",
       "dizer → diria, como direi en futuro."),
    gd(W, 0, [["ter", "teria"], ["poder", "poderia"], ["saber", "saberia"]], "trazer → ___", "traria", "trazeria",
       "ter, poder y saber son regulares (teria, poderia, saberia); trazer, no: traria."),
    sc(W, 0, ["Eu falaria.", "Eu falarei.", "Eu faria.", "Eu farei.", "Eu diria.", "Eu direi."],
       "¿Qué relación hay entre el futuro y el condicional?",
       ["Tienen la misma base; el condicional cambia -ei por -ia.",
        "El condicional se forma sobre el imperfeito.",
        "No tienen relación: cada uno tiene sus irregulares."],
       "Tienen la misma base; el condicional cambia -ei por -ia.",
       "Misma base (falar-, far-, dir-, trar-) y otra terminación: -ei → -ia. Si sabés uno, sabés el otro."),
    ty(W, 0, "Escribí el condicional de «ter» para «eu».", "eu ___ (ter)", "teria",
       "ter es regular: teria («tendría»)."),
    ty(W, 0, "Escribí el condicional de «fazer» para «nós».", "nós ___ (fazer)", "faríamos",
       "far- + -íamos: faríamos, con tilde."),

    # --- part 1 ---
    ch(W, 1, "Garçom, você ___ me trazer a conta?", ["poderia", "podria", "poderría"], "poderia",
       "Cortesía: poderia. poder es regular: poder + ia."),
    ch(W, 1, "Eu ___ fazer uma reserva para quatro pessoas.", ["gostaria de", "gostaria", "gustaría de"], "gostaria de",
       "gostar pide de también en condicional: gostaria de fazer."),
    ch(W, 1, "___ possível trocar de quarto?", ["Seria", "Sería", "Seriam"], "Seria",
       "Seria possível...? es un pedido muy cortés. Sin tilde en la i."),
    ch(W, 1, "Eu ___ um mate e um biscoito Globo.", ["queria", "quero", "quis"], "queria",
       "Al pedir, el imperfeito queria suaviza como un condicional. Quero suena brusco.",
       prompt="Elegí la forma más amable y natural al hablar."),
    cl(W, 1, "Eu ___ (gostar) de ver o cardápio.", "gostaria",
       "gostaria de + infinitivo: pedido cortés."),
    cl(W, 1, "Você se ___ (importar) de fechar a janela?", "importaria",
       "Você se importaria de...? = ¿le molestaría...?"),
    cl(W, 1, "Moço, você ___ (poder) me passar o sal? (habla, imperfeito)", "podia",
       "En el habla, podia reemplaza a poderia con la misma cortesía."),
    cl(W, 1, "Eu ___ (querer) uma água de coco, por favor. (habla)", "queria",
       "Eu queria... = quería, me gustaría. Muy natural en Brasil."),
    tr(W, 1, "¿Me podría traer la cuenta?", "Você poderia me trazer a conta?",
       ["Poderia me trazer a conta?", "O senhor poderia me trazer a conta?", "A senhora poderia me trazer a conta?",
        "Você podia me trazer a conta?", "Poderia trazer-me a conta?", "Você poderia trazer a conta?",
        "Poderia trazer a conta?"],
       "poderia + infinitivo; el pronombre, delante del infinitivo: me trazer."),
    tr(W, 1, "Quisiera hacer una reserva.", "Eu gostaria de fazer uma reserva",
       ["Gostaria de fazer uma reserva", "Eu queria fazer uma reserva", "Queria fazer uma reserva"],
       "«Quisiera» = gostaria de o queria. Nada de subjuntivo."),
    tr(W, 1, "¿Sería posible cambiar de habitación?", "Seria possível trocar de quarto?",
       ["Seria possível mudar de quarto?", "Seria possível trocar de quarto"],
       "Seria possível + infinitivo. «Habitación» de hotel = quarto."),
    fx(W, 1, "Eu gostaria um café, por favor.", "gostaria um", "gostaria de um", "regencia",
       "gostar pide de siempre: gostaria de um café."),
    sc(W, 1, ["Eu queria um café.", "Eu gostaria de um café.", "Você podia me ajudar?",
              "Você poderia me ajudar?", "Eu ia adorar!", "Eu adoraria!"],
       "¿Qué hace el imperfeito en estas frases?",
       ["Reemplaza al condicional al hablar, con la misma cortesía.",
        "Cuenta algo que pasaba antes y ya no.",
        "Es un error frecuente de los brasileños."],
       "Reemplaza al condicional al hablar, con la misma cortesía.",
       "En el habla de Brasil, queria, podia e ia + infinitivo hacen el trabajo del condicional."),

    # --- part 2 ---
    ch(W, 2, "Você ___ conhecer a Lapa.", ["deveria", "deberia", "devería"], "deveria",
       "«Deberías» = deveria (con v y sin tilde)."),
    ch(W, 2, "No seu lugar, eu ___ a moqueca.", ["pediria", "pidiria", "pediría"], "pediria",
       "pedir es regular en condicional: pediria."),
    ch(W, 2, "Ela disse que ___ às oito.", ["chegaria", "chegaría", "chegariam"], "chegaria",
       "Futuro visto desde el pasado: condicional. Ela → chegaria."),
    ch(W, 2, "Eu sabia que você ___ do Rio.", ["gostaria", "gostaría", "gostariam"], "gostaria",
       "Sabía que te gustaría: condicional, y gostar con de."),
    cl(W, 2, "___ (ser) melhor ir de metrô.", "Seria",
       "Seria melhor + infinitivo: sugerencia suave."),
    cl(W, 2, "Você ___ (dever) descansar mais. (habla, imperfeito)", "devia",
       "Al hablar, devia hace de deveria: você devia descansar."),
    cl(W, 2, "Ele prometeu que ___ (trazer) o violão.", "traria",
       "Futuro en el pasado: traria."),
    cl(W, 2, "Eles disseram que ___ (vir) de Niterói.", "viriam",
       "vir es regular: viriam («vendrían»)."),
    tr(W, 2, "Deberías probar el açaí.", "Você deveria provar o açaí",
       ["Deveria provar o açaí", "Você devia provar o açaí", "Devia provar o açaí",
        "Você deveria experimentar o açaí", "Você devia experimentar o açaí"],
       "Consejo: deveria (o devia, al hablar)."),
    tr(W, 2, "En tu lugar, yo me quedaría.", "No seu lugar, eu ficaria",
       ["No seu lugar eu ficaria", "No teu lugar, eu ficaria", "Eu, no seu lugar, ficaria", "No seu lugar, ficaria"],
       "«quedarse» = ficar, sin pronombre. «En tu lugar» = no seu lugar."),
    tr(W, 2, "Dijo que vendría.", "Ele disse que viria",
       ["Disse que viria", "Ela disse que viria", "Ele disse que ia vir", "Ela disse que ia vir", "Disse que ia vir"],
       "vir → viria. Al hablar, ia vir."),
    fx(W, 2, "Ela disse que viría mais tarde.", "viría", "viria", "ortografia",
       "El condicional no lleva tilde en la i: viria. Solo nós la lleva: viríamos."),
]

# ============================================================================
# Semana 19 — Comparativos e superlativos
#   part 0: más, menos, tan, irregulares · part 1: superlativo, -íssimo, bem / mesmo
# ============================================================================
W = 19
_GP19 = "Mirá los tres ejemplos (comparativo) y completá el cuarto."
ITEMS += [
    # --- part 0 ---
    ch(W, 0, "O Rio é ___ quente do que Curitiba.", ["mais", "más", "mas"], "mais",
       "«más» es mais, con i. Mas (sin i) significa «pero»."),
    ch(W, 0, "Ipanema é mais cara ___ Botafogo.", ["do que", "de", "como"], "do que",
       "El segundo término va con do que (o que): mais cara do que Botafogo."),
    ch(W, 0, "O Maracanã é ___ que o Engenhão.", ["maior", "mais grande", "más grande"], "maior",
       "grande → maior. «mais grande» es error en portugués."),
    ch(W, 0, "Esse açaí é ___ que o de ontem.", ["melhor", "mais bom", "mais melhor"], "melhor",
       "bom → melhor; melhor ya es comparativo, no lleva mais."),
    ch(W, 0, "Salvador é tão quente ___ o Rio.", ["quanto", "que", "do que"], "quanto",
       "Igualdad: tão ... quanto (o como)."),
    ch(W, 0, "Não tenho ___ paciência quanto você.", ["tanta", "tão", "tanto"], "tanta",
       "Con sustantivo, tanto concuerda: tanta paciência. Tão va con adjetivos."),
    ch(W, 0, "O trânsito hoje está ___ do que ontem.", ["pior", "mais ruim", "mais mau"], "pior",
       "ruim / mau → pior. «mais ruim» no es la forma culta."),
    cl(W, 0, "O metrô é ___ rápido do que o ônibus. (más)", "mais",
       "mais + adjetivo + do que."),
    cl(W, 0, "Meu apartamento é ___ que o seu. (más chico)", "menor",
       "pequeno → menor; en Brasil «mais pequeno» casi no se usa."),
    cl(W, 0, "Ela canta ___ do que eu. (mejor)", "melhor",
       "melhor también es adverbio: canta melhor."),
    cl(W, 0, "Florianópolis é ___ bonita quanto o Rio. (tan)", "tão",
       "tão + adjetivo + quanto."),
    cl(W, 0, "Ele trabalha ___ quanto eu. (tanto)", "tanto",
       "Con verbo: tanto quanto."),
    cl(W, 0, "Esse tênis é ___ confortável do que o outro. (menos)", "menos",
       "menos + adjetivo + do que."),
    cl(W, 0, "Ela tem mais paciência do que ___. (yo)", "eu",
       "Tras do que va el pronombre sujeto: do que eu, nunca «do que mim»."),
    tr(W, 0, "São Paulo es más grande que Río.", "São Paulo é maior do que o Rio",
       ["São Paulo é maior que o Rio", "São Paulo é maior do que Rio", "São Paulo é maior que Rio"],
       "«más grande» = maior. Rio suele llevar artículo: o Rio."),
    tr(W, 0, "Este bar es mejor que el otro.", "Este bar é melhor do que o outro",
       ["Esse bar é melhor do que o outro", "Este bar é melhor que o outro", "Esse bar é melhor que o outro"],
       "bom → melhor; do que o outro."),
    tr(W, 0, "Soy tan alto como mi hermano.", "Eu sou tão alto quanto o meu irmão",
       ["Sou tão alto quanto o meu irmão", "Sou tão alto quanto meu irmão", "Eu sou tão alto quanto meu irmão",
        "Eu sou tão alto como o meu irmão", "Sou tão alto como meu irmão", "Eu sou tão alto como meu irmão",
        "Sou tão alto como o meu irmão"],
       "tão ... quanto / como. «tan» no existe."),
    tr(W, 0, "Hoy hace más calor que ayer.", "Hoje faz mais calor do que ontem",
       ["Hoje faz mais calor que ontem", "Hoje está mais quente do que ontem", "Hoje está mais quente que ontem",
        "Hoje está mais calor do que ontem"],
       "faz calor, en singular; mais ... do que."),
    fx(W, 0, "O Pão de Açúcar é mais grande do que eu pensava.", "mais grande", "maior", "espanol",
       "grande tiene comparativo propio: maior. «mais grande» es calco del español."),
    fx(W, 0, "Minha irmã é mais velha do que mim.", "do que mim", "do que eu", "pronome",
       "Tras do que, pronombre sujeto: do que eu. Mim solo tras preposición."),
    gd(W, 0, [["caro", "mais caro"], ["barato", "mais barato"], ["bonito", "mais bonito"]],
       "grande → ___", "maior", "mais grande",
       "La regla es mais + adjetivo, pero grande tiene forma propia: maior.", prompt=_GP19),
    gd(W, 0, [["rápido", "mais rápido"], ["alto", "mais alto"], ["lindo", "mais lindo"]],
       "bom → ___", "melhor", "mais bom",
       "bom → melhor, como «mejor».", prompt=_GP19),
    gd(W, 0, [["quente", "mais quente"], ["frio", "mais frio"], ["longe", "mais longe"]],
       "ruim → ___", "pior", "mais ruim",
       "ruim → pior. «mais ruim» se oye, pero la forma correcta es pior.", prompt=_GP19),
    sc(W, 0, ["O Rio é mais quente do que Curitiba.", "O Rio é mais quente que Curitiba.",
              "Ela é mais alta do que eu.", "O metrô é menos caro que o táxi.",
              "Ele tem mais amigos do que eu.", "Hoje está mais frio que ontem."],
       "¿Cómo se introduce el segundo término de la comparación?",
       ["Con do que o con que, indistintamente.", "Solo con do que; que es un error.",
        "Con de, como en «más de»."],
       "Con do que o con que, indistintamente.",
       "mais / menos ... do que o ... que: las dos son correctas. De solo va con números: mais de cem pessoas."),
    ty(W, 0, "Escribí el comparativo de «pequeno» que se usa en Brasil.", "pequeno → ___", "menor",
       "pequeno → menor. «mais pequeno» es típico de Portugal."),

    # --- part 1 ---
    ch(W, 1, "É a praia mais bonita ___ Brasil.", ["do", "de o", "que o"], "do",
       "Superlativo: o mais ... de (contraído): do Brasil."),
    ch(W, 1, "Esse restaurante é ___.", ["caríssimo", "carísimo", "carissimo"], "caríssimo",
       "-íssimo, con doble s y tilde: caríssimo."),
    ch(W, 1, "O hotel é ___ perto da praia.", ["bem", "muy", "bom"], "bem",
       "bem delante de adjetivo o adverbio = muy: bem perto."),
    ch(W, 1, "É caro ___! Trinta reais por um coco?", ["mesmo", "bem", "muito"], "mesmo",
       "mesmo detrás = realmente: é caro mesmo."),
    ch(W, 1, "Ele é o ___ jogador do time.", ["melhor", "mais bom", "mais melhor"], "melhor",
       "Superlativo de bom: o melhor."),
    ch(W, 1, "A feijoada da minha avó é ___!", ["ótima", "bonísima", "muito ótima"], "ótima",
       "ótimo = buenísimo. Ya es superlativo: no lleva muito."),
    cl(W, 1, "Foi o pior dia ___ minha vida.", "da",
       "o pior ... de + a = da minha vida."),
    cl(W, 1, "Essa prova foi ___. (fácil, superlativo culto)", "facílima",
       "fácil → facílimo, facílima (-il → -ílimo)."),
    cl(W, 1, "O Leblon é um bairro ___. (rico → -íssimo)", "riquíssimo",
       "rico → riquíssimo: c → qu para conservar el sonido."),
    cl(W, 1, "___ assim, eu fui à praia. (aun)", "Mesmo",
       "mesmo assim = aun así."),
    cl(W, 1, "Esse show foi ___. (malísimo)", "péssimo",
       "péssimo es el superlativo de ruim / mau: malísimo."),
    cl(W, 1, "O Cristo é o lugar mais famoso ___ cidade.", "da",
       "de + a cidade = da cidade."),
    tr(W, 1, "Es la playa más linda de Río.", "É a praia mais bonita do Rio",
       ["É a praia mais linda do Rio", "Esta é a praia mais bonita do Rio", "Essa é a praia mais bonita do Rio",
        "Esta é a praia mais linda do Rio", "Essa é a praia mais linda do Rio"],
       "a praia mais bonita do Rio: sin repetir el artículo delante de mais."),
    tr(W, 1, "El hotel está muy cerca.", "O hotel é bem perto",
       ["O hotel fica bem perto", "O hotel está bem perto", "O hotel é muito perto", "O hotel fica muito perto",
        "O hotel está muito perto"],
       "bem perto o muito perto; para ubicar, en Brasil se usa mucho ficar."),
    tr(W, 1, "Aun así, fui.", "Mesmo assim, eu fui", ["Mesmo assim, fui", "Mesmo assim eu fui", "Mesmo assim fui"],
       "mesmo assim = aun así."),
    tr(W, 1, "Fue el mejor día del año.", "Foi o melhor dia do ano", [],
       "o melhor + sustantivo + do."),
    fx(W, 1, "É o bairro mais caro que o Rio.", "que o Rio", "do Rio", "preposicion",
       "El superlativo relativo va con de: o bairro mais caro do Rio."),
    fx(W, 1, "Esse vestido é muy caro.", "muy", "muito", "muito",
       "«muy» no existe en portugués: muito (o bem) caro."),
    sc(W, 1, ["O hotel é bem perto.", "Está bem frio hoje.", "A comida está bem gostosa.",
              "Você fala bem português.", "Ela dança bem.", "É bem caro."],
       "¿Qué significa bem delante de un adjetivo o un adverbio?",
       ["«Muy»: bem caro = muy caro.", "«Bien», con matiz: bem caro = caro de buena manera.",
        "«Poco»: bem caro = apenas caro."],
       "«Muy»: bem caro = muy caro.",
       "Delante de adjetivo o adverbio, bem intensifica (bem perto = muy cerca). Detrás de un verbo sigue siendo «bien»: fala bem."),
    ty(W, 1, "Escribí el superlativo en -íssimo de «caro».", "caro → ___", "caríssimo",
       "Cae la vocal final y se suma -íssimo: caríssimo."),
]

# ============================================================================
# Semana 20 — Indefinidos, negação e quantidade
#   part 0: tudo / todo, indefinidos, cantidad · part 1: negar
# ============================================================================
W = 20
ITEMS += [
    # --- part 0 ---
    ch(W, 0, "Comi ___ e ainda estou com fome.", ["tudo", "todo", "toda"], "tudo",
       "Sin sustantivo detrás, «todo» = tudo."),
    ch(W, 0, "___ bem com você?", ["Tudo", "Todo", "Toda"], "Tudo",
       "Tudo bem? = ¿todo bien? Pronombre invariable."),
    ch(W, 0, "___ os meus amigos foram ao bloco.", ["Todos", "Tudos", "Tudo"], "Todos",
       "Con sustantivo, todo concuerda: todos os meus amigos. «tudos» no existe."),
    ch(W, 0, "Vou à academia ___ dia.", ["todo", "tudo", "cada o"], "todo",
       "todo dia (sin artículo) = todos los días."),
    ch(W, 0, "Não tenho ___ ideia.", ["nenhuma", "nenhum", "ninguna"], "nenhuma",
       "ideia es femenino: nenhuma ideia."),
    ch(W, 0, "Tem ___ aí?", ["alguém", "algum", "alguno"], "alguém",
       "Persona indeterminada: alguém (alguien)."),
    ch(W, 0, "Tinha ___ pessoas na praia.", ["muitas", "muitos", "muito"], "muitas",
       "Ante sustantivo, muito concuerda: muitas pessoas."),
    cl(W, 0, "Você entendeu ___? (todo)", "tudo",
       "Sin sustantivo: tudo."),
    cl(W, 0, "___ a cidade parou para ver o jogo. (toda)", "Toda",
       "Con sustantivo femenino: toda a cidade."),
    cl(W, 0, "___ mundo gosta de praia. (todo el mundo)", "Todo",
       "todo mundo = todos, todo el mundo; verbo en singular."),
    cl(W, 0, "Você quer ___ coisa? (alguna)", "alguma",
       "alguma coisa = algo."),
    cl(W, 0, "Ela é ___ simpática. (muy)", "muito",
       "Ante adjetivo, muito no varía: muito simpática."),
    cl(W, 0, "Comi ___: estou passando mal. (demasiado)", "demais",
       "demais = demasiado; también «muchísimo» (bom demais)."),
    cl(W, 0, "Tenho ___ tempo hoje. (poco)", "pouco",
       "pouco concuerda como muito: pouco tempo, poucas horas."),
    tr(W, 0, "Entendí todo.", "Entendi tudo", ["Eu entendi tudo"],
       "Sin sustantivo: tudo."),
    tr(W, 0, "Todos los días voy a la playa.", "Todo dia vou à praia",
       ["Todos os dias vou à praia", "Todo dia eu vou à praia", "Todos os dias eu vou à praia", "Vou à praia todo dia",
        "Vou à praia todos os dias", "Eu vou à praia todo dia", "Eu vou à praia todos os dias",
        "Todo dia vou para a praia", "Todo dia vou pra praia"],
       "todo dia o todos os dias; a + a praia = à praia."),
    tr(W, 0, "No tengo ningún problema.", "Não tenho nenhum problema",
       ["Eu não tenho nenhum problema", "Não tenho problema nenhum", "Eu não tenho problema nenhum"],
       "«ningún» = nenhum; también detrás: problema nenhum."),
    tr(W, 0, "Había mucha gente.", "Tinha muita gente",
       ["Havia muita gente", "Tinha muitas pessoas", "Havia muitas pessoas"],
       "gente es femenino singular: muita gente."),
    fx(W, 0, "Todo está bem, pode ficar tranquilo.", "Todo está", "Tudo está", "espanol",
       "Sin sustantivo, «todo» se dice tudo: tudo está bem."),
    fx(W, 0, "Não vi ningún amigo na festa.", "ningún", "nenhum", "espanol",
       "«ningún» es nenhum en portugués."),
    gd(W, 0, [["o dia", "o dia todo"], ["a semana", "a semana toda"], ["o bolo", "o bolo todo"]],
       "(sin sustantivo) comi → ___", "comi tudo", "comi todo",
       "Con sustantivo, todo / toda; solo, sin sustantivo, tudo: comi tudo."),
    gd(W, 0, [["um livro", "nenhum livro"], ["um carro", "nenhum carro"], ["uma casa", "nenhuma casa"]],
       "uns amigos → ___", "nenhum amigo", "nenhuns amigos",
       "nenhum va casi siempre en singular: nenhum amigo. «nenhuns» existe, pero es rarísimo."),
    sc(W, 0, ["Comi tudo.", "Tudo bem?", "Ela sabe tudo.", "Todo dia vou à praia.",
              "Toda a cidade parou.", "Todos os amigos vieram."],
       "¿Cuándo va tudo y cuándo todo?",
       ["tudo va solo (pronombre); todo, toda, todos van con un sustantivo.",
        "tudo es para cosas; todo, para personas.",
        "tudo es plural y todo es singular."],
       "tudo va solo (pronombre); todo, toda, todos van con un sustantivo.",
       "tudo = «todo» sin sustantivo (invariable). todo / toda / todos / todas acompañan a un sustantivo."),
    ty(W, 0, "Escribí «ninguna» en portugués.", "___ (femenino, ante sustantivo)", "nenhuma",
       "nenhum / nenhuma, con nh y m."),

    # --- part 1 ---
    ch(W, 1, "___ veio à festa.", ["Ninguém", "Não ninguém", "Ninguno"], "Ninguém",
       "Delante del verbo, la palabra negativa va sola: ninguém veio."),
    ch(W, 1, "Não vi ___ na praia.", ["ninguém", "alguém", "ninguno"], "ninguém",
       "Doble negación: não ... ninguém."),
    ch(W, 1, "— Não gosto de chuva. — Eu ___.", ["também não", "tampoco", "também"], "também não",
       "«tampoco» = também não. Também solo afirmaría lo contrario."),
    ch(W, 1, "Não bebo ___ café nem chá.", ["nem", "ni", "não"], "nem",
       "«ni» = nem: nem ... nem."),
    ch(W, 1, "— Você vai ao jogo? — ___.", ["Vou", "Sim vou", "Sí"], "Vou",
       "En Brasil se contesta repitiendo el verbo: vou."),
    ch(W, 1, "Eu ___ fui a Manaus.", ["nunca", "jamás", "não nunca"], "nunca",
       "nunca delante del verbo va solo, sin não."),
    cl(W, 1, "Não comi ___ hoje. (nada)", "nada",
       "não ... nada."),
    cl(W, 1, "___ sabe onde ele está. (nadie)", "Ninguém",
       "ninguém = nadie, con nh y tilde."),
    cl(W, 1, "___ eu! (ni)", "Nem",
       "Nem eu = ni yo (tampoco yo)."),
    cl(W, 1, "— Gostou do filme? — ___! (sí, me gustó)", "Gostei",
       "Respuesta con el verbo: gostei."),
    cl(W, 1, "Não sei ___. (negación al final, habla)", "não",
       "Não sei não: la negación repetida al final es típica del habla brasileña."),
    cl(W, 1, "Ela não fala ___ com ninguém. (nunca)", "nunca",
       "Detrás del verbo, nunca necesita não delante."),
    tr(W, 1, "No vi a nadie.", "Não vi ninguém", ["Eu não vi ninguém"],
       "Sin «a» personal: não vi ninguém."),
    tr(W, 1, "Yo tampoco.", "Eu também não", ["Nem eu", "Também não"],
       "«tampoco» = também não; también nem eu."),
    tr(W, 1, "Nadie sabe.", "Ninguém sabe", [],
       "ninguém delante del verbo, sin não."),
    tr(W, 1, "Ni lo pienses.", "Nem pensar", ["Nem pensar!", "Nem pense nisso"],
       "Nem pensar! = ¡ni lo pienses!, ¡ni loco!"),
    fx(W, 1, "Eu tampoco vou.", "tampoco", "também não", "espanol",
       "«tampoco» es español; en Brasil: eu também não vou."),
    fx(W, 1, "Não tem nadie em casa.", "nadie", "ninguém", "espanol",
       "«nadie» = ninguém."),
    gd(W, 1, [["Eu vou.", "Eu também."], ["Ela gosta.", "Ela também."], ["Nós temos.", "Nós também."]],
       "Eu não vou. → ___", "Eu também não.", "Eu também.",
       "Para sumarse a una negación hay que negar: eu também não (o nem eu).",
       alt=["Nem eu.", "Eu também não", "Nem eu"]),
    sc(W, 1, ["Não vi ninguém.", "Ninguém veio.", "Não comi nada.", "Nada aconteceu.",
              "Não fui nunca.", "Nunca fui."],
       "¿Cuándo hace falta não?",
       ["Cuando la palabra negativa va después del verbo.",
        "Siempre: ninguém, nada y nunca necesitan não.",
        "Nunca: con ninguém o nada, não sobra."],
       "Cuando la palabra negativa va después del verbo.",
       "Como en español: não vi ninguém / ninguém veio. La palabra negativa delante del verbo reemplaza a não."),
    ty(W, 1, "Escribí «tampoco» como se dice en Brasil.", "Eu ___.", "também não",
       "tampouco existe, pero suena a libro: eu também não.", alt=["também não."]),
]

# ============================================================================
# Semana 21 — Pretérito perfeito composto e mais-que-perfeito
#   part 0: forma y participios · part 1: tenho feito ≠ he hecho · part 2: tinha feito
# ============================================================================
W = 21
_GP21 = "Mirá los tres ejemplos (ter + participio) y completá el cuarto."
ITEMS += [
    # --- part 0 ---
    ch(W, 0, "Eles ___ estudado muito.", ["têm", "tem", "han"], "têm",
       "ter en presente, eles: têm (con circunflejo)."),
    ch(W, 0, "O que você tem ___ ultimamente?", ["feito", "fazido", "hecho"], "feito",
       "fazer → feito."),
    ch(W, 0, "Não tenho ___ a Bia.", ["visto", "vido", "vista"], "visto",
       "ver → visto; con ter el participio no concuerda."),
    ch(W, 0, "Ela tem ___ com o Rafa.", ["saído", "saída", "salido"], "saído",
       "Con ter, participio invariable en -o: tem saído."),
    cl(W, 0, "Eu tenho ___ (dormir) mal.", "dormido",
       "Participio regular en -ido."),
    cl(W, 0, "Nós temos ___ (ir) à praia todo fim de semana.", "ido",
       "ir → ido."),
    cl(W, 0, "Você tem ___ (escrever) para a sua mãe?", "escrito",
       "escrever → escrito."),
    cl(W, 0, "Eles ___ (ter) trabalhado muito.", "têm",
       "eles têm, con circunflejo."),
    cl(W, 0, "O que vocês têm ___ (dizer) sobre o projeto?", "dito",
       "dizer → dito."),
    tr(W, 0, "Vengo trabajando mucho.", "Tenho trabalhado muito",
       ["Eu tenho trabalhado muito", "Estou trabalhando muito", "Eu estou trabalhando muito", "Ando trabalhando muito"],
       "«vengo + gerundio» = tenho + participio: tenho trabalhado."),
    tr(W, 0, "¿Qué andás haciendo?", "O que você tem feito?",
       ["O que tem feito?", "Que você tem feito?", "O que você anda fazendo?"],
       "tem feito = viene haciendo (de un tiempo a esta parte)."),
    fx(W, 0, "Ultimamente tenho fazido muito exercício.", "fazido", "feito", "participio",
       "fazer tiene participio irregular: feito."),
    gd(W, 0, [["falar", "tenho falado"], ["comer", "tenho comido"], ["dormir", "tenho dormido"]],
       "fazer → ___", "tenho feito", "tenho fazido",
       "fazer → feito: irregular, como «hecho».", prompt=_GP21),
    gd(W, 0, [["beber", "tenho bebido"], ["correr", "tenho corrido"], ["vender", "tenho vendido"]],
       "ver → ___", "tenho visto", "tenho vido",
       "ver → visto.", prompt=_GP21),
    gd(W, 0, [["sair", "tenho saído"], ["pedir", "tenho pedido"], ["partir", "tenho partido"]],
       "dizer → ___", "tenho dito", "tenho dizido",
       "dizer → dito, como «dicho».", prompt=_GP21),
    ty(W, 0, "Escribí el participio de «abrir».", "abrir → ___", "aberto",
       "abrir → aberto (abierto)."),
    ty(W, 0, "Escribí el participio de «vir».", "vir → ___", "vindo",
       "vir → vindo: igual al gerundio."),

    # --- part 1 ---
    ch(W, 1, "Hoje eu ___ demais.", ["comi", "tenho comido", "hei comido"], "comi",
       "«He comido» (hoy) = comi: perfeito simple."),
    ch(W, 1, "Ultimamente ___ muito no Rio.", ["tem chovido", "ha chovido", "tem chovida"], "tem chovido",
       "Algo repetido hasta hoy (ultimamente): ter + participio invariable."),
    ch(W, 1, "Você já ___ a Salvador?", ["foi", "tem ido", "há ido"], "foi",
       "«¿Ya fuiste / has ido?» = já foi? Tem ido significaría «venís yendo»."),
    ch(W, 1, "Nunca ___ acarajé.", ["comi", "tenho comido", "he comido"], "comi",
       "Experiencia (nunca): perfeito simple."),
    ch(W, 1, "Nos últimos meses, eu ___ no Aterro.", ["tenho corrido", "tenho corrida", "hei corrido"], "tenho corrido",
       "Repetición hasta hoy: tenho corrido. El auxiliar es ter."),
    ch(W, 1, "Esta semana ___ duas vezes à academia.", ["fui", "tenho ido", "ia"], "fui",
       "Con un número de veces, perfeito simple: fui duas vezes."),
    cl(W, 1, "Ainda não ___ (almoçar).", "almocei",
       "«Todavía no he almorzado» = ainda não almocei (ç → c ante e)."),
    cl(W, 1, "Ultimamente eu ___ (dormir) pouco.", "tenho dormido",
       "Ultimamente + repetición: tenho dormido."),
    cl(W, 1, "Você ___ (ver) o João? Faz tempo que não o vejo.", "tem visto",
       "¿Lo venís viendo?: tem visto."),
    cl(W, 1, "Hoje eu ___ (acordar) às seis.", "acordei",
       "Hoje + hecho único: perfeito simple."),
    cl(W, 1, "A Ana ___ (trabalhar) muito nos últimos tempos.", "tem trabalhado",
       "Nos últimos tempos: tem trabalhado."),
    tr(W, 1, "Hoy he comido feijoada.", "Hoje eu comi feijoada",
       ["Hoje comi feijoada", "Comi feijoada hoje", "Eu comi feijoada hoje"],
       "«he comido» = comi."),
    tr(W, 1, "¿Ya has estado en Brasil?", "Você já esteve no Brasil?",
       ["Já esteve no Brasil?", "Você já foi ao Brasil?", "Já foi ao Brasil?", "Tu já estiveste no Brasil?"],
       "Experiencia: perfeito simple (esteve / foi). Brasil lleva artículo: no Brasil."),
    tr(W, 1, "Últimamente venimos saliendo poco.", "Ultimamente temos saído pouco",
       ["Ultimamente a gente tem saído pouco", "Ultimamente nós temos saído pouco"],
       "Repetición hasta hoy: temos saído (a gente tem saído)."),
    tr(W, 1, "Todavía no he visto esa película.", "Ainda não vi esse filme",
       ["Eu ainda não vi esse filme", "Ainda não vi aquele filme", "Ainda não assisti esse filme",
        "Ainda não assisti a esse filme", "Eu ainda não assisti esse filme", "Eu ainda não assisti a esse filme"],
       "ainda não + perfeito simple."),
    fx(W, 1, "Tenho visto esse filme ontem.", "Tenho visto", "Vi", "perfeito_composto",
       "Una sola vez, ayer: perfeito simple (vi). Tenho visto = vengo viendo."),
    fx(W, 1, "Hoje eu tenho acordado cedo.", "tenho acordado", "acordei", "perfeito_composto",
       "Hoje + un hecho: acordei. El composto sería una costumbre reciente."),
    sc(W, 1, ["Tenho trabalhado muito.", "Ultimamente tenho dormido mal.", "Tem chovido todo dia.",
              "Hoje trabalhei muito.", "Ontem dormi mal.", "Choveu no domingo."],
       "¿Qué indica ter + participio (tenho trabalhado)?",
       ["Algo repetido o continuo que llega hasta hoy.", "Algo que pasó una vez, hoy mismo.",
        "Algo que pasó hace mucho y ya terminó."],
       "Algo repetido o continuo que llega hasta hoy.",
       "tenho trabalhado = vengo trabajando. Lo que pasó una vez va en perfeito simple, aunque sea hoy."),
    sc(W, 1, ["Hoje comi feijoada.", "Você já foi a Salvador?", "Nunca vi o mar.",
              "Ainda não almocei.", "Esta semana fui ao cinema.", "Já li esse livro."],
       "¿Cómo se dice en portugués lo que en español va con «he + participio»?",
       ["Con el perfeito simple: comi, fui, vi.", "Con ter + participio: tenho comido.",
        "Con haver + participio: hei comido."],
       "Con el perfeito simple: comi, fui, vi.",
       "El perfeito simple cubre «comí» y «he comido». Tenho comido es otra cosa: vengo comiendo."),

    # --- part 2 ---
    ch(W, 2, "Quando cheguei ao Maracanã, o jogo já ___ começado.", ["tinha", "tem", "teve"], "tinha",
       "Anterior a otro pasado: tinha + participio."),
    ch(W, 2, "Nós já ___ jantado.", ["tínhamos", "tinhamos", "temos"], "tínhamos",
       "tínhamos lleva tilde (esdrújula)."),
    ch(W, 2, "Eu nunca ___ visto o mar antes daquela viagem.", ["tinha", "tenho", "tive"], "tinha",
       "Antes de un momento pasado: tinha visto."),
    cl(W, 2, "Ela ___ saído quando você ligou.", "tinha",
       "Había salido: tinha saído.", alt=["havia"]),
    cl(W, 2, "Quando chegamos, eles já tinham ___ (comer) tudo.", "comido",
       "Participio invariable con ter: comido."),
    cl(W, 2, "O filme ___ (terminar) quando entramos. (había terminado)", "tinha terminado",
       "Pasado del pasado: tinha terminado (escrito: havia terminado).", alt=["havia terminado"]),
    tr(W, 2, "Cuando llegué, ya se habían ido.", "Quando cheguei, eles já tinham ido embora",
       ["Quando eu cheguei, eles já tinham ido embora", "Quando cheguei, eles já tinham saído",
        "Quando eu cheguei, eles já tinham saído", "Quando cheguei, já tinham ido embora",
        "Quando cheguei, já tinham saído", "Quando cheguei, eles já haviam saído",
        "Quando cheguei, elas já tinham saído", "Quando cheguei, elas já tinham ido embora"],
       "«irse» = ir embora; había + participio = tinha + participio."),
    tr(W, 2, "Nunca había visto el mar.", "Eu nunca tinha visto o mar",
       ["Nunca tinha visto o mar", "Eu nunca havia visto o mar", "Nunca havia visto o mar"],
       "tinha visto (habla) o havia visto (escrito)."),
    fx(W, 2, "Quando cheguei, o show já tinha começada.", "começada", "começado", "participio",
       "Con ter, el participio no concuerda: tinha começado."),
]
