# -*- coding: utf-8 -*-
"""Palabras de la semana, estación 1 (semanas 1-13).

12 por semana, ninguna en la semana de jefe (13).  Palabras frecuentes del
campo léxico de la semana que un hispanohablante no adivina (o adivina mal):
falsos amigos y palabras muy de Brasil.  Cada ejemplo usa solo la gramática
vista hasta esa semana.
"""

VOCAB = {
1: [
    ["oi", "hola", "Oi, Bia! Tudo bem?", "Saludo informal de todo Brasil; con desconocidos o de mañana, mejor *bom dia*. La combinación típica: *Oi, tudo bem?*"],
    ["tchau", "chau", "Tchau, Martín! Até logo!", "Se escribe con *tch* pero suena como «chau». Más cálido: *tchau, um beijo* o *tchau, até logo*."],
    ["obrigado / obrigada", "gracias (concuerda con quien habla)", "Obrigada, Rafa! — De nada!", "Concuerda con quien habla: una mujer siempre dice *obrigada*. Se responde *de nada* o *imagina*."],
    ["desculpa", "perdón, disculpá", "Desculpa, você é o João?", "Sirve para pedir perdón y para abordar a alguien: *Desculpa, você é…?* Para pasar o interrumpir se usa *com licença*."],
    ["prazer", "mucho gusto", "Prazer, eu sou a Sofía, de Córdoba.", "Suele ir con *muito*: *muito prazer*. Al presentarte: *Prazer, eu sou…*; la respuesta típica es *o prazer é meu*."],
    ["valeu", "gracias, dale (coloquial)", "Valeu, cara! Até logo!", "Es el perfeito de *valer* usado como «gracias» informal. Entre amigos: *Valeu, cara!*; con desconocidos, mejor *obrigado*."],
    ["legal", "copado, buena onda (no «legal» de la ley)", "O Rafa é legal.", "Igual en masculino y femenino: *ele é legal*, *ela é legal*; plural *legais*. *Que legal!* = ¡qué bueno!"],
    ["beleza", "joya, todo bien (coloquial)", "E aí, tudo beleza? — Beleza!", "Coloquial: *beleza?* = ¿todo bien?, *beleza!* = dale, joya. Es femenino (*a beleza*, la belleza) y también se dice *tudo beleza?*"],
    ["apelido", "apodo (¡no «apellido»!)", "Meu nome é Rafael, mas meu apelido é Rafa.", "Falso amigo: *apelido* es el apodo; el apellido es *sobrenome*. Se pregunta *qual é o seu apelido?*"],
    ["sobrenome", "apellido", "Qual é o seu sobrenome? — É Gómez.", "Masculino, como *nome*: *o sobrenome*. En Brasil suele ir primero el apellido de la madre y al final el del padre."],
    ["moço / moça", "joven, señor (para llamar a alguien)", "Moço, você está livre?", "Para llamar a un mozo, vendedor o desconocido joven: *Moço, por favor!*; a una mujer, *moça*. A alguien mayor, *senhor* / *senhora*."],
    ["cara", "tipo, chabón (coloquial); también «cara»", "O João é um cara legal.", "Coloquial y siempre masculino aunque termine en -a: *o cara*, *um cara legal*. También muletilla: *Cara, que calor!*"],
],
2: [
    ["cadeira", "silla", "Tem duas cadeiras aqui.", "Falso amigo: la cadera es *quadril*. Patrón frecuente: -era española → *-eira* portugués (*madera → madeira*, *carrera → carreira*)."],
    ["janela", "ventana", "A sala tem três janelas.", "Femenino: *a janela*. Para abrirla y cerrarla: *abrir / fechar a janela*; *fechar* es cerrar."],
    ["caneta", "birome, lapicera", "Você tem uma caneta?", "Femenino: *a caneta*. Para pedirla: *Você tem uma caneta?* o *Me empresta uma caneta?* (¿me prestás…?)."],
    ["borracha", "goma de borrar (no «borracha» = ebria)", "Tem uma borracha aí?", "Falso amigo: es la goma de borrar y también el caucho. Ebria se dice *bêbada*."],
    ["lixo", "basura", "Onde está o lixo?", "La *x* suena «sh»: *li-sho*. Tirar algo: *jogar no lixo*; el tacho es *a lixeira*."],
    ["chave", "llave", "Você tem a chave? — Tenho!", "Ll española → *ch*: *llave → chave*, *lleno → cheio*, *llover → chover*. Femenino: *a chave*."],
    ["gaveta", "cajón", "A gaveta está aberta.", "Femenino: *a gaveta*; algo está *na gaveta* (em + a). Ojo: el ataúd es *caixão*, no «cajón»."],
    ["prateleira", "estante, repisa", "A prateleira é nova.", "Viene de *prato* (plato). Algo se pone *na prateleira* (em + a); la librería de pared es *a estante*."],
    ["copo", "vaso (para tomar); «copa» es taça", "Tem um copo de água?", "Masculino: *o copo*, el vaso para tomar; la copa de vino es *a taça*. Se pide *um copo de água*, con *de*."],
    ["xícara", "taza", "Tem uma xícara de café?", "Esdrújula con tilde: *xí-ca-ra*, con la *x* inicial como «sh». Recipiente + *de* + contenido: *uma xícara de café*."],
    ["garrafa", "botella", "São duas garrafas de água.", "En Brasil es cualquier botella, no un bidón. *Uma garrafa de vinho*; el termo es *garrafa térmica*."],
    ["tomada", "enchufe", "Tem uma tomada aqui?", "Es el participio de *tomar* usado como sustantivo: el enchufe de la pared. La ficha del aparato es *o plugue*."],
],
3: [
    ["rua", "calle", "Estou na rua Farme de Amoedo, em Ipanema.", "Femenino: *a rua*. Con *em* se contrae: *moro na rua X* (em + a). *Na rua* también = afuera, fuera de casa."],
    ["praça", "plaza", "A feira é na praça General Osório.", "*Ç* suena como «s». Con *em*: *na praça* (em + a). Plaza de estacionamiento no: eso es *vaga*."],
    ["prédio", "edificio (no «predio» = terreno)", "O prédio é em frente à praia.", "Falso amigo: edificio, no terreno (eso es *terreno* o *lote*). Los pisos son *andares*: *um prédio de dez andares*."],
    ["loja", "negocio, tienda", "Tem uma loja de biquínis na esquina.", "Femenino: *a loja*; la *j* suena como la «y» rioplatense. *Loja de roupas* = tienda de ropa."],
    ["padaria", "panadería", "A padaria é ao lado do metrô.", "*-aria* = *-ería*: *padaria*, *livraria*, *sorveteria*. En Brasil la padaria es también café: ahí se desayuna."],
    ["calçada", "vereda", "A calçada de Copacabana é de pedra portuguesa.", "Falso amigo: la calzada de los autos es *a rua* o *a pista*; *calçada* es la vereda. *Calçadão* = vereda ancha, rambla."],
    ["perto", "cerca", "O hotel é perto da praia.", "Pide *de*, que se contrae: *perto da praia*, *perto do metrô*. Sin complemento va solo: *é aqui perto*."],
    ["longe", "lejos", "O Cristo é longe daqui?", "Pide *de*, como *perto*: *longe daqui* (de + aqui), *longe do centro*. Invariable: *a praia é longe*."],
    ["boteco", "bar de barrio, bodegón", "Estou no boteco com o Rafa.", "Coloquial y cariñoso; variantes *botequim* y *buteco*. Con *em*: *estou no boteco*."],
    ["morro", "cerro; también favela", "O Cristo está no morro do Corcovado.", "En Río *morro* nombra al cerro y, por extensión, a la favela construida en él: *subir o morro*."],
    ["embaixo", "abajo, debajo", "O gato está embaixo da mesa.", "Una sola palabra, con *de* + lugar: *embaixo da mesa*. Su opuesto se escribe separado: *em cima*."],
    ["em cima", "arriba, encima", "A chave está em cima da mesa.", "Dos palabras (*embaixo* es una). Con *de*: *em cima da mesa* = sobre la mesa; *lá em cima* = allá arriba."],
],
4: [
    ["vermelho", "rojo", "A camisa do Flamengo é vermelha e preta.", "Concuerda: *camisa vermelha*, *carros vermelhos*. Ojo: *roxo*, que parece «rojo», es violeta."],
    ["amarelo", "amarillo", "A camisa da seleção é amarela.", "Concuerda: *a camisa amarela*. Coloquial: *amarelar* = arrugar, echarse atrás por miedo."],
    ["preto", "negro (color)", "O Rafa tem um cachorro preto.", "Es la palabra común para el color: *sapato preto*; *café preto* = café solo. *Negro* se usa más para personas y en sentido figurado."],
    ["roxo", "violeta, morado (no «rojo»)", "O açaí é roxo.", "Falso amigo: violeta, no rojo (*vermelho*). Un moretón es *um roxo*: *fiquei com um roxo na perna*."],
    ["cinza", "gris", "O céu está cinza hoje.", "Como color suele quedar invariable: *céu cinza*, *camisas cinza*. Como sustantivo es la ceniza: *a cinza*."],
    ["magro", "flaco", "O Lucas é alto e magro.", "Concuerda: *alto e magro*, *alta e magra*. Su opuesto es *gordo*; para suavizar se usa *gordinho*."],
    ["baixo", "bajo (de estatura)", "A Bia é baixa e morena.", "Sirve para estatura, volumen y lugar: *ela é baixa*, *fala baixo* (en voz baja). *X* tras diptongo suena «sh»."],
    ["esquisito", "raro (no «exquisito»)", "O vizinho é muito esquisito.", "Falso amigo: raro, extraño. Exquisito (rico) es *delicioso* o *uma delícia*: *o bolo está uma delícia*."],
    ["chato", "pesado, aburrido (no «chato»)", "O filme é muito chato.", "Falso amigo: pesado, que molesta o aburre: *que chato!* = ¡qué embole! Muy común para gente y situaciones."],
    ["engraçado", "gracioso, divertido", "O Rafa é muito engraçado.", "Es lo que hace reír. En portugués *gracioso* es más bien delicado, con gracia. *Que engraçado!* = ¡qué gracioso!"],
    ["loiro", "rubio", "Ela é loira e tem olhos azuis.", "También *louro* (más formal). Concuerda: *loiro*, *loira*. *Louro* también es el laurel y el loro."],
    ["cabelo", "pelo (de la cabeza)", "Ela tem o cabelo cacheado.", "Singular para toda la cabellera: *o cabelo dela*, *cortar o cabelo*. El pelo del cuerpo o de animal es *pelo*."],
],
5: [
    ["acordar", "despertarse (no «acordar»)", "Eu acordo às seis todo dia.", "Falso amigo: despertarse, sin *se*: *eu acordo às seis*. Despertar a otro: *acordar alguém*. Acordarse es *lembrar*."],
    ["cedo", "temprano", "A gente acorda cedo para ir à praia.", "Adverbio invariable: *acordo cedo*. Opuesto: *tarde*. *Mais cedo* = más temprano; *cedinho* = tempranito."],
    ["almoçar", "almorzar", "Eu almoço num restaurante perto do escritório.", "Regular en -ar: *eu almoço*, *a gente almoça*. El sustantivo es *o almoço*: *o que tem para o almoço?*"],
    ["jantar", "cenar; la cena", "À noite a gente janta em casa.", "Verbo (*a gente janta*) y sustantivo masculino (*o jantar*). En el habla también se dice *a janta*."],
    ["café da manhã", "desayuno", "Tomo o café da manhã na padaria.", "Literal «café de la mañana». Se usa con *tomar*: *tomo café da manhã*. En Portugal es *pequeno-almoço*."],
    ["manhã", "mañana (parte del día)", "De manhã eu corro no calçadão.", "*Nh* = ñ. Con *de*: *de manhã* (a la mañana), *de tarde*, *de noite*. Mañana (día siguiente) es *amanhã*."],
    ["escritório", "oficina (de trabajo)", "Ela trabalha num escritório no Centro.", "Falso amigo: es la oficina. *Oficina* es el taller; el escritorio (mueble) es *a mesa* o *a escrivaninha*."],
    ["oficina", "taller mecánico (no «oficina»)", "O carro está na oficina.", "Falso amigo: taller mecánico o de reparación; también taller de curso: *oficina de teatro*. La oficina es *escritório*."],
    ["garçom", "mozo, camarero", "O garçom do boteco é muito simpático.", "Nasal final en *-om*; plural *garçons*, femenino *garçonete*. Para llamarlo alcanza *Moço!* o *Garçom!*"],
    ["pedreiro", "albañil", "O pedreiro trabalha no prédio ao lado.", "De *pedra* (piedra). Sufijo de oficio *-eiro*: *pedreiro*, *padeiro*, *cozinheiro*, *carteiro*."],
    ["funcionário", "empleado", "Os funcionários do banco chegam às oito.", "Cualquier empleado, no solo del Estado: *os funcionários do banco*. El empleado estatal es *funcionário público*."],
    ["morar", "vivir (en un lugar)", "Eu moro em Botafogo, perto do metrô.", "Para la vivienda se usa *morar*, no *viver*: *moro em Botafogo*. Pide *em*: *moro no Rio*, *moro na rua X*."],
],
6: [
    ["combinar", "arreglar, quedar en (un plan)", "Vamos combinar um chope no sábado?", "Arreglar un plan: *combinamos um chope*. En el habla, *combinar de* + infinitivo: *combinamos de sair*. *Combinado!* = ¡quedamos así!"],
    ["topar", "prenderse, aceptar (un plan)", "Você topa ir ao samba hoje?", "Sin preposición: *topa ir?*, *topo um chope*. Coloquial: *topar com alguém* = cruzarse con alguien."],
    ["rolê", "salida, vuelta (coloquial)", "Vamos dar um rolê na Lapa?", "Coloquial, aguda con *ê*. Va con *dar*: *dar um rolê* = dar una vuelta, salir un rato."],
    ["balada", "boliche, joda (no «balada»)", "Hoje tem balada? — Não, prefiro ficar em casa.", "Falso amigo: el boliche o la salida nocturna, sobre todo en São Paulo. *Ir para a balada*; *baladeiro* = el que sale mucho."],
    ["chope", "chopp, cerveza tirada", "Dois chopes, por favor!", "Masculino: *o chope*, plural *chopes*. Se pide *um chope* o *me vê um chope*; afectuoso: *chopinho*."],
    ["convidar", "invitar", "Ela convida a gente para a festa.", "Pide *para* + evento: *convidar alguém para a festa*. El invitado es *o convidado*; la invitación, *o convite*."],
    ["curtir", "disfrutar; «likear»", "Eu curto muito samba.", "Sin preposición: *curto samba*, *curti a festa*. En redes, *curtir* = dar me gusta; el like es *a curtida*."],
    ["folga", "franco, día libre", "Hoje é meu dia de folga.", "*Estar de folga* = tener franco; *dia de folga* = día libre. Coloquial: *folgado* = caradura, abusador."],
    ["grana", "plata (coloquial)", "Não posso sair, estou sem grana.", "Coloquial y femenino: *a grana*. *Estar sem grana* = estar sin plata. Neutro: *dinheiro*."],
    ["a fim de", "con ganas de", "Estou a fim de ir à praia.", "*Estar a fim de* + infinitivo = tener ganas de: *estou a fim de sair*. *Estar a fim de alguém* = gustarte alguien."],
    ["passear", "pasear", "No domingo a gente passeia no Aterro.", "Verbo en *-ear*: agrega *i* en las formas acentuadas: *eu passeio*, *a gente passeia*. El paseo: *o passeio*."],
    ["ingresso", "entrada (para un show; no «ingreso»)", "Você tem ingresso para o show?", "Falso amigo: la entrada para un show o partido. El ingreso de dinero es *renda*. *Comprar ingresso*."],
],
7: [
    ["segunda-feira", "lunes", "Na segunda-feira o museu não abre.", "Los días se cuentan desde el domingo: el lunes es el «segundo». En el habla, sin *-feira*: *na segunda*."],
    ["terça-feira", "martes", "A aula é na terça-feira, às sete.", "Femenino y con *em*: *na terça-feira*. Para costumbre, plural: *às terças* = los martes."],
    ["quarta-feira", "miércoles", "Quarta-feira tem jogo no Maracanã.", "En el habla: *quarta*. *Quarta-feira de Cinzas* = miércoles de ceniza, fin del carnaval. Plural: *quartas-feiras*."],
    ["quinta-feira", "jueves", "Na quinta-feira o boteco fica cheio.", "Con *em* + artículo: *na quinta*. *Quinta* sola también es «quinta» ordinal: *a quinta rua*."],
    ["sexta-feira", "viernes", "Sexta-feira é dia de samba na Pedra do Sal.", "En el habla: *sexta*. En redes, *Sextou!* = ¡llegó el viernes! Plural: *às sextas* = los viernes."],
    ["hoje", "hoy", "Hoje é dia três de março.", "*H* muda y *j* como la «y» rioplatense: suena «ôyi». *Hoje em dia* = hoy en día."],
    ["amanhã", "mañana (el día siguiente)", "Amanhã eu saio cedo.", "Mañana (día siguiente). Combinado: *amanhã de manhã* = mañana a la mañana; *de manhã* sola es «a la mañana»."],
    ["meia", "media; seis (al dictar números)", "Meu telefone é nove, meia, oito, dois…", "Al dictar números, el 6 se dice *meia* (de *meia dúzia*) para no confundir *seis* con *três*. También: *meia* = media, calcetín."],
    ["troco", "vuelto", "Você tem troco para cem?", "Masculino: *o troco*. *Tem troco para cem?* = ¿tenés cambio de cien? *Pode ficar com o troco* = quedate con el vuelto."],
    ["cartão", "tarjeta", "Aceita cartão?", "Plural en *-ões*: *cartões*. Se paga *no cartão* o *com cartão*, *de crédito* o *de débito*."],
    ["atrasado", "atrasado, tarde", "O ônibus está atrasado.", "Con *estar*: *estou atrasado* = llego tarde. Verbo *atrasar* (*o voo atrasou*); sustantivo *o atraso*."],
    ["aniversário", "cumpleaños (no solo «aniversario»)", "Meu aniversário é em julho.", "Es el cumpleaños de una persona, y también aniversario. Se saluda *Feliz aniversário!* o simplemente *Parabéns!*"],
],
8: [
    ["fim de semana", "fin de semana", "O que você vai fazer no fim de semana?", "*Fim* termina en *m* nasal. Con *em* + artículo: *no fim de semana*. Plural: *fins de semana*."],
    ["depois", "después", "Depois do almoço, vou dormir um pouco.", "Con *de* ante sustantivo o infinitivo: *depois do almoço*, *depois de comer*. Solo: *depois eu te falo*."],
    ["ainda", "todavía", "Ainda estou esperando o ônibus.", "Va antes del verbo: *ainda estou esperando*. *Ainda não* = todavía no; *ainda bem* = menos mal."],
    ["agora", "ahora", "Agora estou trabalhando.", "*Até agora* = hasta ahora. Coloquial: *agorinha* = hace un ratito o ya mismo."],
    ["já", "ya", "Já estou chegando!", "*Já vou!* = ¡ya voy!; *já volto* = ya vuelvo. «Ya no» suele ser *não… mais*: *não moro mais lá*."],
    ["logo", "enseguida, pronto", "O show vai começar logo.", "Más que «luego»: enseguida, pronto. *Até logo* = hasta luego; *logo depois* = justo después."],
    ["churrasco", "asado", "No domingo vai ter churrasco na casa da Bia.", "Masculino. *Fazer um churrasco* = hacer un asado; *a churrascaria* es el restaurante de carnes."],
    ["sítio", "casa de campo, quinta (no «sitio»)", "A gente vai passar o fim de semana num sítio em Petrópolis.", "Falso amigo: chacra o casa de campo. «Sitio» es *lugar*; sitio web, *site*. *Passar o fim de semana no sítio*."],
    ["trilha", "sendero, caminata", "Vamos fazer a trilha do Morro Dois Irmãos.", "Sendero, y también *trilha sonora* (banda sonora). *Fazer uma trilha* = hacer una caminata por el monte."],
    ["cachoeira", "cascada", "Vamos conhecer uma cachoeira na Floresta da Tijuca.", "Femenino: *a cachoeira*. *Tomar banho de cachoeira* = bañarse en la cascada."],
    ["arrumar", "ordenar, arreglar", "Estou arrumando a casa.", "Ordenar (*arrumar o quarto*), preparar (*arrumar a mala*), conseguir (*arrumar um emprego*). *Arrumar-se* = arreglarse para salir."],
    ["faxina", "limpieza a fondo", "No sábado vou fazer faxina.", "Va con *fazer*: *fazer faxina*. Quien la hace es *a faxineira*. La *x* suena «sh»."],
],
9: [
    ["ônibus", "colectivo, micro", "Pego o ônibus na esquina.", "Igual en singular y plural: *o ônibus*, *os ônibus*. *Ir de ônibus*; *pegar o ônibus* = tomar el colectivo."],
    ["metrô", "subte", "O metrô vai até a Barra.", "Aguda con *ô* cerrada. *Ir de metrô*; la estación es *a estação de metrô*."],
    ["esquerda", "izquierda", "A estação fica à esquerda.", "Con *à* (a + a): *à esquerda* = a la izquierda. *Virar à esquerda* = doblar a la izquierda."],
    ["direita", "derecha", "Você vira à direita na segunda rua.", "*À direita* = a la derecha; derecho, sin doblar, es *em frente* o *reto*. *Direito* (masculino) = derecho, la ley."],
    ["pegar", "tomar (un transporte), agarrar", "Eu pego o metrô em Botafogo.", "Verbo comodín: *pegar o ônibus*, *pegar um táxi*, *pegar um resfriado*. Falso amigo: golpear es *bater*."],
    ["descer", "bajar(se)", "Desço na estação Cardeal Arcoverde.", "Bajar(se), sin *se*: *desço aqui*. Del vehículo, con *de*: *descer do ônibus*. Opuesto: *subir*."],
    ["ponto", "parada (de colectivo)", "O ponto de ônibus fica em frente à padaria.", "*Ponto de ônibus* = parada. En el colectivo: *Vou descer no próximo ponto*."],
    ["sinal", "semáforo", "Você vira à esquerda no sinal.", "En Río el semáforo es *o sinal*; en São Paulo, *o farol*. Plural: *sinais*."],
    ["carona", "aventón, que te lleven", "Ela dá carona para a gente.", "Con *dar* y *pegar*: *dar carona* = llevar a alguien en tu auto; *pegar carona* = ir con alguien, hacer dedo."],
    ["rodoviária", "terminal de micros", "O ônibus para São Paulo sai da rodoviária.", "Terminal de ómnibus de larga distancia; viene de *rodovia* (ruta). Con *de*: *sai da rodoviária*."],
    ["virar", "doblar; darse vuelta", "O táxi vira na rua da praia.", "Doblar: *virar à direita*. También volverse: *ele virou médico*. *Se virar* = arreglárselas."],
    ["engarrafamento", "embotellamiento", "Tem engarrafamento na Avenida Brasil.", "De *garrafa*: tránsito «embotellado». En el habla: *peguei trânsito* = me agarró el tránsito."],
],
10: [
    ["irmão / irmã", "hermano / hermana", "Meu irmão mora em Niterói.", "*Os irmãos* incluye hermanos y hermanas. Ojo con la nasal: *irmão*, *irmã*, plural *irmãs*."],
    ["avô / avó", "abuelo / abuela", "Minha avó é mineira.", "Solo cambia el acento: *avô* (ô cerrada) es el abuelo, *avó* (ó abierta) la abuela. *Os avós* = los abuelos."],
    ["sogro / sogra", "suegro / suegra", "O sogro dela é português.", "*Sogro* con o cerrada; *sogra* y *sogros*, con o abierta. *Os sogros* = los suegros."],
    ["namorado / namorada", "novio / novia", "A namorada dele é carioca.", "*Namorar* = estar de novio: *eles namoram há dois anos*. Falso amigo: *noivo* es el prometido."],
    ["quarto", "dormitorio, pieza (no solo «cuarto»)", "Meu quarto tem vista para o mar.", "Dormitorio, y también cuarto (¼) u ordinal. *Quarto de hóspedes* = cuarto de huéspedes."],
    ["geladeira", "heladera", "A cerveja está na geladeira.", "De *gelo* (hielo), como *gelado*. *Pôr na geladeira*. En Portugal se dice *frigorífico*."],
    ["fogão", "cocina (el artefacto)", "O fogão da nossa casa é velho.", "De *fogo* (fuego); plural *fogões*. La cocina (habitación) es *a cozinha*; el horno, *o forno*."],
    ["travesseiro", "almohada", "Esse travesseiro é muito duro.", "Masculino: *o travesseiro*; la funda es *a fronha*. *Almofada* es el almohadón del sillón."],
    ["lençol", "sábana", "Os lençóis estão no armário.", "Plural irregular: *lençóis* (-ol → -óis). No confundir con *lenço*, pañuelo."],
    ["óculos", "anteojos (siempre plural)", "Onde estão os meus óculos?", "Siempre plural, con artículo y verbo en plural: *os meus óculos estão aqui*. *Óculos de sol* = anteojos de sol."],
    ["carteira", "billetera; registro (de conducir)", "Minha carteira está na mochila.", "Billetera y también documento: *carteira de motorista* = registro; *carteira de trabalho* = libreta laboral."],
    ["guarda-chuva", "paraguas", "Esse guarda-chuva é seu?", "Masculino, *guarda* + *chuva*; plural *guarda-chuvas*. La sombrilla de playa es *guarda-sol*."],
],
11: [
    ["ontem", "ayer", "Ontem fui ao Maracanã.", "Termina en *-em* nasal. Va con perfeito: *ontem fui*, *ontem choveu*. *Ontem à noite* = anoche."],
    ["anteontem", "anteayer", "Anteontem choveu muito.", "*Ante* + *ontem*; en el habla también *antes de ontem*. Con perfeito: *anteontem choveu*."],
    ["mala", "valija (no «mala»)", "Arrumei a mala ontem à noite.", "Falso amigo: valija. Hacerla: *arrumar* o *fazer a mala*. «Mala» (adjetivo) es *má*: *uma má ideia*."],
    ["voo", "vuelo", "O voo atrasou duas horas.", "Sin tilde desde el Acuerdo de 1990 (antes *vôo*). Verbo *voar*: *voei para o Rio*."],
    ["esquecer", "olvidar(se)", "Esqueci o passaporte no hotel!", "Dos construcciones: *esqueci o passaporte* o *me esqueci do passaporte*. Ojo a la grafía: *eu esqueço* (c → ç)."],
    ["chegar", "llegar", "Cheguei ao Galeão às seis.", "Norma: *chegar a* (*cheguei ao Rio*); en el habla, *chegar em*: *cheguei no Rio*. Perfeito: *cheguei*, con *gu*."],
    ["ficar", "quedarse; quedar", "Fiquei três dias em Paraty.", "Comodín: quedarse (*fiquei em casa*), estar ubicado (*onde fica?*), volverse (*fiquei feliz*). Perfeito: *fiquei*, *ficou*."],
    ["pousada", "posada, hostería", "Ficamos numa pousada na Ilha Grande.", "Hotel chico, típico de pueblos turísticos como Paraty. *Ficar numa pousada* = alojarse en una posada."],
    ["ir embora", "irse", "Ela foi embora cedo da festa.", "*Embora* tras *ir* = irse: *vou embora*, *ela foi embora*. Sola, *embora* significa «aunque»."],
    ["saudade", "nostalgia, extrañar", "Senti muita saudade do Rio.", "Con *ter*, *sentir* o *estar com*, más *de*: *tenho saudade de você* = te extraño. *Que saudade!*"],
    ["demorar", "tardar", "O ônibus demorou muito.", "Tardar: *demorou duas horas*; *demorar para* + infinitivo = tardar en. Coloquial: *Demorou!* = ¡dale!"],
    ["enfim", "por fin", "Enfim chegamos à praia!", "Por fin, y también «en fin» para cerrar un tema: *Enfim, vamos embora*. Una sola palabra."],
],
12: [
    ["costas", "espalda (siempre plural)", "Estou com dor nas costas.", "Siempre plural: *as costas*. *Estou com dor nas costas* (em + as). *A costa*, en singular, es la del mar."],
    ["barriga", "panza", "Comi muito e estou com dor de barriga.", "*Dor de barriga* = dolor de panza. Femenino: *a barriga*. *Estou com dor de barriga* = me duele la panza."],
    ["joelho", "rodilla", "Machuquei o joelho no futebol.", "Masculino: *o joelho*; *lh* suena parecido a «li». *De joelhos* = de rodillas."],
    ["ombro", "hombro", "Dói o ombro direito.", "Sin *h*: *o ombro*. *Encolher os ombros* = encogerse de hombros. Doler con sujeto: *dói o ombro*."],
    ["pescoço", "cuello", "Ela está com dor no pescoço.", "Masculino y neutro, sin tono despectivo: *dor no pescoço*. El cuello de la camisa es *a gola*."],
    ["tosse", "tos", "Tome este xarope para a tosse.", "Femenino: *a tosse*. Verbo *tossir*: *eu tusso*, *ele tosse*. *Estar com tosse* = tener tos."],
    ["machucar", "lastimar(se)", "Cuidado, não se machuque!", "Lastimar(se), muchas veces sin pronombre: *machuquei o joelho* (c → qu). *Machucado* = lastimado; también la herida."],
    ["receita", "receta (médica o de cocina)", "Sem receita, a farmácia não vende o remédio.", "Receta médica y de cocina. *Sem receita* = sin receta. *A Receita Federal* es el fisco de Brasil."],
    ["colher", "cuchara", "Tome uma colher de xarope.", "Sustantivo femenino con *é* abierta: *a colher*. Con *ê* cerrada es el verbo cosechar. *Uma colher de sopa*."],
    ["panela", "olla", "Coloque o feijão na panela.", "Femenino: *a panela*. *Panela de pressão* = olla a presión; *panelaço* = cacerolazo."],
    ["lembrar", "acordarse, recordar", "Você lembra do nome da farmácia?", "En el habla, *lembrar de*: *lembro do nome*. La norma pide *lembrar-se de* o *lembrar* + objeto: *lembro o nome*."],
    ["escova de dentes", "cepillo de dientes", "Esqueci a escova de dentes!", "*Escovar os dentes* = cepillarse los dientes. *Escova* sola también es el brushing del peluquero."],
],
13: [],
}
