# -*- coding: utf-8 -*-
"""Palabras de la semana, estación 1 (semanas 1-13).

12 por semana, ninguna en la semana de jefe (13).  Palabras frecuentes del
campo léxico de la semana que un hispanohablante no adivina (o adivina mal):
falsos amigos y palabras muy de Brasil.  Cada ejemplo usa solo la gramática
vista hasta esa semana.
"""

VOCAB = {
1: [
    ["oi", "hola", "Oi, Bia! Tudo bem?"],
    ["tchau", "chau", "Tchau, Martín! Até logo!"],
    ["obrigado / obrigada", "gracias (concuerda con quien habla)", "Obrigada, Rafa! — De nada!"],
    ["desculpa", "perdón, disculpá", "Desculpa, você é o João?"],
    ["prazer", "mucho gusto", "Prazer, eu sou a Sofía, de Córdoba."],
    ["valeu", "gracias, dale (coloquial)", "Valeu, cara! Até logo!"],
    ["legal", "copado, buena onda (no «legal» de la ley)", "O Rafa é legal."],
    ["beleza", "joya, todo bien (coloquial)", "E aí, tudo beleza? — Beleza!"],
    ["apelido", "apodo (¡no «apellido»!)", "Meu nome é Rafael, mas meu apelido é Rafa."],
    ["sobrenome", "apellido", "Qual é o seu sobrenome? — É Gómez."],
    ["moço / moça", "joven, señor (para llamar a alguien)", "Moço, você está livre?"],
    ["cara", "tipo, chabón (coloquial); también «cara»", "O João é um cara legal."],
],
2: [
    ["cadeira", "silla", "Tem duas cadeiras aqui."],
    ["janela", "ventana", "A sala tem três janelas."],
    ["caneta", "birome, lapicera", "Você tem uma caneta?"],
    ["borracha", "goma de borrar (no «borracha» = ebria)", "Tem uma borracha aí?"],
    ["lixo", "basura", "Onde está o lixo?"],
    ["chave", "llave", "Você tem a chave? — Tenho!"],
    ["gaveta", "cajón", "A gaveta está aberta."],
    ["prateleira", "estante, repisa", "A prateleira é nova."],
    ["copo", "vaso (para tomar); «copa» es taça", "Tem um copo de água?"],
    ["xícara", "taza", "Tem uma xícara de café?"],
    ["garrafa", "botella", "São duas garrafas de água."],
    ["tomada", "enchufe", "Tem uma tomada aqui?"],
],
3: [
    ["rua", "calle", "Estou na rua Farme de Amoedo, em Ipanema."],
    ["praça", "plaza", "A feira é na praça General Osório."],
    ["prédio", "edificio (no «predio» = terreno)", "O prédio é em frente à praia."],
    ["loja", "negocio, tienda", "Tem uma loja de biquínis na esquina."],
    ["padaria", "panadería", "A padaria é ao lado do metrô."],
    ["calçada", "vereda", "A calçada de Copacabana é de pedra portuguesa."],
    ["perto", "cerca", "O hotel é perto da praia."],
    ["longe", "lejos", "O Cristo é longe daqui?"],
    ["boteco", "bar de barrio, bodegón", "Estou no boteco com o Rafa."],
    ["morro", "cerro; también favela", "O Cristo está no morro do Corcovado."],
    ["embaixo", "abajo, debajo", "O gato está embaixo da mesa."],
    ["em cima", "arriba, encima", "A chave está em cima da mesa."],
],
4: [
    ["vermelho", "rojo", "A camisa do Flamengo é vermelha e preta."],
    ["amarelo", "amarillo", "A camisa da seleção é amarela."],
    ["preto", "negro (color)", "O Rafa tem um cachorro preto."],
    ["roxo", "violeta, morado (no «rojo»)", "O açaí é roxo."],
    ["cinza", "gris", "O céu está cinza hoje."],
    ["magro", "flaco", "O Lucas é alto e magro."],
    ["baixo", "bajo (de estatura)", "A Bia é baixa e morena."],
    ["esquisito", "raro (no «exquisito»)", "O vizinho é muito esquisito."],
    ["chato", "pesado, aburrido (no «chato»)", "O filme é muito chato."],
    ["engraçado", "gracioso, divertido", "O Rafa é muito engraçado."],
    ["loiro", "rubio", "Ela é loira e tem olhos azuis."],
    ["cabelo", "pelo (de la cabeza)", "Ela tem o cabelo cacheado."],
],
5: [
    ["acordar", "despertarse (no «acordar»)", "Eu acordo às seis todo dia."],
    ["cedo", "temprano", "A gente acorda cedo para ir à praia."],
    ["almoçar", "almorzar", "Eu almoço num restaurante perto do escritório."],
    ["jantar", "cenar; la cena", "À noite a gente janta em casa."],
    ["café da manhã", "desayuno", "Tomo o café da manhã na padaria."],
    ["manhã", "mañana (parte del día)", "De manhã eu corro no calçadão."],
    ["escritório", "oficina (de trabajo)", "Ela trabalha num escritório no Centro."],
    ["oficina", "taller mecánico (no «oficina»)", "O carro está na oficina."],
    ["garçom", "mozo, camarero", "O garçom do boteco é muito simpático."],
    ["pedreiro", "albañil", "O pedreiro trabalha no prédio ao lado."],
    ["funcionário", "empleado", "Os funcionários do banco chegam às oito."],
    ["morar", "vivir (en un lugar)", "Eu moro em Botafogo, perto do metrô."],
],
6: [
    ["combinar", "arreglar, quedar en (un plan)", "Vamos combinar um chope no sábado?"],
    ["topar", "prenderse, aceptar (un plan)", "Você topa ir ao samba hoje?"],
    ["rolê", "salida, vuelta (coloquial)", "Vamos dar um rolê na Lapa?"],
    ["balada", "boliche, joda (no «balada»)", "Hoje tem balada? — Não, prefiro ficar em casa."],
    ["chope", "chopp, cerveza tirada", "Dois chopes, por favor!"],
    ["convidar", "invitar", "Ela convida a gente para a festa."],
    ["curtir", "disfrutar; «likear»", "Eu curto muito samba."],
    ["folga", "franco, día libre", "Hoje é meu dia de folga."],
    ["grana", "plata (coloquial)", "Não posso sair, estou sem grana."],
    ["a fim de", "con ganas de", "Estou a fim de ir à praia."],
    ["passear", "pasear", "No domingo a gente passeia no Aterro."],
    ["ingresso", "entrada (para un show; no «ingreso»)", "Você tem ingresso para o show?"],
],
7: [
    ["segunda-feira", "lunes", "Na segunda-feira o museu não abre."],
    ["terça-feira", "martes", "A aula é na terça-feira, às sete."],
    ["quarta-feira", "miércoles", "Quarta-feira tem jogo no Maracanã."],
    ["quinta-feira", "jueves", "Na quinta-feira o boteco fica cheio."],
    ["sexta-feira", "viernes", "Sexta-feira é dia de samba na Pedra do Sal."],
    ["hoje", "hoy", "Hoje é dia três de março."],
    ["amanhã", "mañana (el día siguiente)", "Amanhã eu saio cedo."],
    ["meia", "media; seis (al dictar números)", "Meu telefone é nove, meia, oito, dois…"],
    ["troco", "vuelto", "Você tem troco para cem?"],
    ["cartão", "tarjeta", "Aceita cartão?"],
    ["atrasado", "atrasado, tarde", "O ônibus está atrasado."],
    ["aniversário", "cumpleaños (no solo «aniversario»)", "Meu aniversário é em julho."],
],
8: [
    ["fim de semana", "fin de semana", "O que você vai fazer no fim de semana?"],
    ["depois", "después", "Depois do almoço, vou dormir um pouco."],
    ["ainda", "todavía", "Ainda estou esperando o ônibus."],
    ["agora", "ahora", "Agora estou trabalhando."],
    ["já", "ya", "Já estou chegando!"],
    ["logo", "enseguida, pronto", "O show vai começar logo."],
    ["churrasco", "asado", "No domingo vai ter churrasco na casa da Bia."],
    ["sítio", "casa de campo, quinta (no «sitio»)", "A gente vai passar o fim de semana num sítio em Petrópolis."],
    ["trilha", "sendero, caminata", "Vamos fazer a trilha do Morro Dois Irmãos."],
    ["cachoeira", "cascada", "Vamos conhecer uma cachoeira na Floresta da Tijuca."],
    ["arrumar", "ordenar, arreglar", "Estou arrumando a casa."],
    ["faxina", "limpieza a fondo", "No sábado vou fazer faxina."],
],
9: [
    ["ônibus", "colectivo, micro", "Pego o ônibus na esquina."],
    ["metrô", "subte", "O metrô vai até a Barra."],
    ["esquerda", "izquierda", "A estação fica à esquerda."],
    ["direita", "derecha", "Você vira à direita na segunda rua."],
    ["pegar", "tomar (un transporte), agarrar", "Eu pego o metrô em Botafogo."],
    ["descer", "bajar(se)", "Desço na estação Cardeal Arcoverde."],
    ["ponto", "parada (de colectivo)", "O ponto de ônibus fica em frente à padaria."],
    ["sinal", "semáforo", "Você vira à esquerda no sinal."],
    ["carona", "aventón, que te lleven", "Ela dá carona para a gente."],
    ["rodoviária", "terminal de micros", "O ônibus para São Paulo sai da rodoviária."],
    ["virar", "doblar; darse vuelta", "O táxi vira na rua da praia."],
    ["engarrafamento", "embotellamiento", "Tem engarrafamento na Avenida Brasil."],
],
10: [
    ["irmão / irmã", "hermano / hermana", "Meu irmão mora em Niterói."],
    ["avô / avó", "abuelo / abuela", "Minha avó é mineira."],
    ["sogro / sogra", "suegro / suegra", "O sogro dela é português."],
    ["namorado / namorada", "novio / novia", "A namorada dele é carioca."],
    ["quarto", "dormitorio, pieza (no solo «cuarto»)", "Meu quarto tem vista para o mar."],
    ["geladeira", "heladera", "A cerveja está na geladeira."],
    ["fogão", "cocina (el artefacto)", "O fogão da nossa casa é velho."],
    ["travesseiro", "almohada", "Esse travesseiro é muito duro."],
    ["lençol", "sábana", "Os lençóis estão no armário."],
    ["óculos", "anteojos (siempre plural)", "Onde estão os meus óculos?"],
    ["carteira", "billetera; registro (de conducir)", "Minha carteira está na mochila."],
    ["guarda-chuva", "paraguas", "Esse guarda-chuva é seu?"],
],
11: [
    ["ontem", "ayer", "Ontem fui ao Maracanã."],
    ["anteontem", "anteayer", "Anteontem choveu muito."],
    ["mala", "valija (no «mala»)", "Arrumei a mala ontem à noite."],
    ["voo", "vuelo", "O voo atrasou duas horas."],
    ["esquecer", "olvidar(se)", "Esqueci o passaporte no hotel!"],
    ["chegar", "llegar", "Cheguei ao Galeão às seis."],
    ["ficar", "quedarse; quedar", "Fiquei três dias em Paraty."],
    ["pousada", "posada, hostería", "Ficamos numa pousada na Ilha Grande."],
    ["ir embora", "irse", "Ela foi embora cedo da festa."],
    ["saudade", "nostalgia, extrañar", "Senti muita saudade do Rio."],
    ["demorar", "tardar", "O ônibus demorou muito."],
    ["enfim", "por fin", "Enfim chegamos à praia!"],
],
12: [
    ["costas", "espalda (siempre plural)", "Estou com dor nas costas."],
    ["barriga", "panza", "Comi muito e estou com dor de barriga."],
    ["joelho", "rodilla", "Machuquei o joelho no futebol."],
    ["ombro", "hombro", "Dói o ombro direito."],
    ["pescoço", "cuello", "Ela está com dor no pescoço."],
    ["tosse", "tos", "Tome este xarope para a tosse."],
    ["machucar", "lastimar(se)", "Cuidado, não se machuque!"],
    ["receita", "receta (médica o de cocina)", "Sem receita, a farmácia não vende o remédio."],
    ["colher", "cuchara", "Tome uma colher de xarope."],
    ["panela", "olla", "Coloque o feijão na panela."],
    ["lembrar", "acordarse, recordar", "Você lembra do nome da farmácia?"],
    ["escova de dentes", "cepillo de dientes", "Esqueci a escova de dentes!"],
],
13: [],
}
