# -*- coding: utf-8 -*-
"""Palabras de la semana, estação 2 (semanas 14-26).

[palabra en portugués, significado en español, oración de ejemplo].
12 por semana; la semana 26 (CHEFÃO) no tiene.  Los ejemplos usan solo la
gramática vista hasta esa semana.
"""

VOCAB = {

14: [
    ["gostoso", "rico, sabroso (comida); agradable", "Esse pastel de queijo está muito gostoso!"],
    ["pastel", "empanada frita (no «pastel» de torta)", "Na feira de domingo a gente come pastel com caldo de cana."],
    ["aipim", "mandioca, yuca (así se dice en Río)", "No boteco pedimos aipim frito com o chope."],
    ["chope", "cerveza tirada", "Depois da praia, tomamos um chope gelado no Leblon."],
    ["petisco", "algo para picar, picada", "Os petiscos desse bar são ótimos: bolinho de bacalhau e pastel."],
    ["feijão", "porotos (y el guiso diario de porotos)", "No Brasil, arroz com feijão é o almoço de todo dia."],
    ["violão", "guitarra criolla, acústica (no «violín»)", "Meu amigo toca bossa nova no violão."],
    ["torcer", "hinchar por un equipo; retorcer", "Eu torço pelo Flamengo, e você?"],
    ["time", "equipo (de fútbol)", "Qual é o seu time do coração?"],
    ["goleiro", "arquero", "O goleiro defendeu o pênalti no último minuto."],
    ["pelada", "picado de fútbol, partido informal", "Toda quinta tem pelada na areia de Copacabana."],
    ["academia", "gimnasio (no una academia de estudios)", "Vou à academia três vezes por semana."],
],

15: [
    ["brincar", "jugar (los chicos); bromear", "Quando eu era pequeno, brincava na rua até tarde."],
    ["brinquedo", "juguete", "Meu brinquedo favorito era um carrinho de madeira."],
    ["pular", "saltar", "As crianças pulavam as ondas em Copacabana."],
    ["boneca", "muñeca (el juguete)", "Minha irmã tinha uma boneca de pano."],
    ["pipa", "barrilete (el juguete)", "No verão, os meninos soltavam pipa no Aterro do Flamengo."],
    ["apontador", "sacapuntas", "Eu sempre esquecia o apontador na escola."],
    ["saudade", "añoranza; extrañar", "Tenho saudade da casa da minha avó."],
    ["moleque", "pibe, chico (coloquial)", "Os moleques jogavam bola na rua todo dia."],
    ["bagunça", "lío, desorden", "Meu quarto era uma bagunça."],
    ["bonde", "tranvía", "O bonde de Santa Teresa passava na frente da nossa casa."],
    ["costumar", "soler", "A gente costumava passar as férias em Petrópolis."],
    ["sítio", "quinta, casa de campo (no «sitio», lugar)", "Meus avós tinham um sítio em Minas Gerais."],
],

16: [
    ["presente", "regalo (y también «presente»)", "Comprei um presente para a minha mãe e dei para ela ontem."],
    ["embrulhar", "envolver (para regalo)", "Você pode embrulhar para presente, por favor?"],
    ["lembrancinha", "recuerdito, souvenir", "Trouxe uma lembrancinha do Rio para você."],
    ["emprestar", "prestar", "Me empresta seu carregador? Te devolvo amanhã."],
    ["sacola", "bolsa (de compras)", "— Quer uma sacola? — Não precisa, obrigado."],
    ["vitrine", "vidriera", "Vi um tênis lindo na vitrine e comprei."],
    ["carona", "aventón: llevar a alguien en auto", "Você me dá uma carona até Botafogo?"],
    ["quebrar o galho", "dar una mano, sacar de un apuro", "Obrigado pelo guarda-chuva: você quebrou o galho!"],
    ["camelô", "vendedor ambulante", "Comprei esses óculos de sol de um camelô no centro."],
    ["pechinchar", "regatear", "Na feira, a Bia sempre pechincha e consegue um desconto."],
    ["trocar", "cambiar (una cosa por otra)", "A camisa ficou pequena: posso trocá-la?"],
    ["encomenda", "paquete, pedido (por encargo)", "Minha encomenda chegou e o porteiro a recebeu."],
],

17: [
    ["chuva", "lluvia", "A previsão diz que amanhã teremos chuva forte."],
    ["garoa", "llovizna", "Em São Paulo, a garoa não para o dia todo."],
    ["abafado", "pesado, sofocante (el clima)", "Hoje está muito abafado: acho que vai chover à tarde."],
    ["guarda-chuva", "paraguas", "Leva o guarda-chuva, que vai chover."],
    ["estágio", "pasantía (no «estadio»)", "No ano que vem farei um estágio numa empresa de tecnologia."],
    ["vaga", "vacante, puesto; lugar libre", "Abriu uma vaga de professor na escola do meu bairro."],
    ["prova", "examen, prueba", "Amanhã teremos prova de matemática."],
    ["formatura", "graduación, fiesta de egreso", "A formatura será em dezembro."],
    ["prazo", "plazo", "O prazo para entregar o trabalho termina sexta-feira."],
    ["demitir", "despedir (del trabajo)", "A empresa vai demitir vinte pessoas."],
    ["expediente", "horario de trabajo", "O expediente termina às seis."],
    ["folga", "franco, día libre", "Amanhã é minha folga: vou à praia."],
],

18: [
    ["cardápio", "menú, carta", "Você poderia me trazer o cardápio, por favor?"],
    ["garçom", "mozo", "O garçom foi muito simpático."],
    ["gorjeta", "propina", "No Brasil, a gorjeta de dez por cento já vem na conta."],
    ["sobremesa", "postre (no «sobremesa»)", "De sobremesa, eu gostaria de um pudim."],
    ["guardanapo", "servilleta", "Moço, você poderia me trazer mais guardanapos?"],
    ["talheres", "cubiertos", "Faltam os talheres na nossa mesa."],
    ["diária", "tarifa por noche (en un hotel)", "A diária do hotel inclui café da manhã."],
    ["prato feito", "plato del día barato (el PF)", "No centro, o prato feito custa uns vinte reais."],
    ["conserto", "arreglo, reparación (no «concierto»)", "O conserto do ar-condicionado sairia muito caro."],
    ["encanador", "plomero", "Seria bom chamar um encanador: o chuveiro está pingando."],
    ["faxina", "limpieza a fondo", "Sábado a gente faz faxina na casa toda."],
    ["saideira", "la última ronda antes de irse", "Vamos tomar a saideira e ir embora?"],
],

19: [
    ["saia", "pollera", "Essa saia é mais curta do que a outra."],
    ["casaco", "abrigo, campera", "No Rio quase ninguém precisa de casaco."],
    ["calça", "pantalón (no «calza»)", "Essa calça jeans é mais barata na outra loja."],
    ["tênis", "zapatillas", "Meu tênis novo é mais confortável do que o velho."],
    ["chinelo", "ojotas", "Carioca vai à padaria de chinelo."],
    ["sunga", "malla (slip) de hombre", "Na praia de Ipanema, muitos homens usam sunga, não bermuda."],
    ["gravata", "corbata", "No trabalho ele usa terno e gravata, mesmo no calor."],
    ["cinto", "cinturón", "Esse cinto de couro é caríssimo."],
    ["tamanho", "talle, tamaño", "Tem esse vestido num tamanho menor?"],
    ["prestação", "cuota", "Comprei a televisão em dez prestações."],
    ["à vista", "al contado", "Pagando à vista, o preço é bem menor."],
    ["brechó", "tienda de ropa usada", "Comprei essa jaqueta num brechó em Botafogo: foi baratíssima."],
],

20: [
    ["de jeito nenhum", "de ninguna manera", "Pagar trinta reais num coco? De jeito nenhum!"],
    ["à beça", "un montón (coloquial)", "Tinha gente à beça no bloco."],
    ["demais", "demasiado; muchísimo", "Essa praia é linda demais!"],
    ["nossa!", "¡uy!, ¡guau!", "Nossa, que calor!"],
    ["puxa", "¡uh! (lástima o sorpresa)", "Puxa, que pena que você não veio."],
    ["imagina", "¡de nada!, ¡para nada!", "— Obrigada pela ajuda! — Imagina!"],
    ["sei lá", "qué sé yo", "— Onde ele está? — Sei lá, ninguém sabe."],
    ["bater papo", "charlar", "A gente ficou batendo papo no calçadão até meia-noite."],
    ["bacana", "bárbaro, piola", "Seu apartamento é muito bacana!"],
    ["combinado", "trato hecho, quedamos así", "— Às oito no Arpoador? — Combinado!"],
    ["à toa", "sin hacer nada; sin motivo", "Passei o domingo à toa, sem fazer nada."],
    ["beleza", "¿todo bien? / dale (y «belleza»)", "— Beleza? — Beleza, e você?"],
],

21: [
    ["sumir", "desaparecer", "Você sumiu! Por onde tem andado?"],
    ["emagrecer", "adelgazar", "Ela tem corrido todo dia e emagreceu cinco quilos."],
    ["engravidar", "quedar embarazada", "A Carla engravidou e vai ter gêmeos."],
    ["aposentar-se", "jubilarse", "Meu pai se aposentou no ano passado e agora pesca todo dia."],
    ["noivo", "prometido (no «novio» de salir)", "A Bia e o noivo vão casar em maio."],
    ["careca", "pelado, calvo", "O Rafa ficou careca: raspou a cabeça."],
    ["virar", "convertirse en; doblar", "Aquela padaria antiga virou um restaurante chique."],
    ["largar", "dejar, abandonar", "Ele largou o emprego e foi morar em Paraty."],
    ["aliás", "por cierto; mejor dicho", "Aliás, você soube que a Ana tem um namorado novo?"],
    ["pois é", "y sí, así es", "— O Rio tem mudado muito. — Pois é."],
    ["de repente", "de golpe; (habla) a lo mejor", "De repente a gente vai ao cinema amanhã, não sei."],
    ["rolar", "pasar, suceder (coloquial)", "E aí, o que rolou na festa?"],
],

22: [
    ["cartório", "escribanía, registro civil", "A assinatura foi reconhecida no cartório."],
    ["boleto", "boleta de pago (no «pasaje»)", "O boleto já foi pago pelo aplicativo."],
    ["senha", "contraseña; número de turno", "No banco, peguei uma senha e esperei quarenta minutos."],
    ["prefeitura", "municipalidad", "A obra foi feita pela prefeitura."],
    ["manchete", "titular (de diario)", "A manchete de hoje: «Metrô é fechado por causa da chuva»."],
    ["enchente", "inundación", "Várias ruas foram fechadas por causa da enchente."],
    ["carimbo", "sello", "O formulário precisa do carimbo da empresa."],
    ["assinatura", "firma; suscripción", "O contrato está pronto: só falta a sua assinatura."],
    ["despachante", "gestor (de trámites)", "Contratei um despachante para renovar a carteira de motorista."],
    ["greve", "huelga", "Os ônibus pararam: os motoristas estão em greve."],
    ["desabamento", "derrumbe", "Ninguém foi ferido no desabamento do prédio."],
    ["boato", "rumor", "A notícia era só um boato."],
],

23: [
    ["namorar", "ser novio de, salir con (sin preposición)", "Tomara que ela namore alguém bacana."],
    ["brigar", "pelearse, discutir", "Espero que vocês não briguem por isso."],
    ["ciúme", "celos", "Ele tem ciúme de todo mundo."],
    ["cafuné", "caricia en el pelo", "Não tem nada melhor do que um cafuné antes de dormir."],
    ["tontura", "mareo (no «tontería»)", "É normal que você sinta tontura depois da vacina."],
    ["enjoo", "náusea; mareo (en barco)", "Tomei um remédio para o enjoo antes de pegar a barca."],
    ["plantão", "guardia (médica, de farmacia)", "É melhor que você procure o plantão do hospital."],
    ["machucar", "lastimar, hacerse daño", "Cuidado para não se machucar no jogo."],
    ["desabafar", "desahogarse", "Às vezes é importante que a gente desabafe com um amigo."],
    ["magoar", "herir (los sentimientos)", "Não quero que você fique magoada comigo."],
    ["dica", "consejo, dato", "Uma dica: beba muita água no verão carioca."],
    ["fazer as pazes", "amigarse, reconciliarse", "Tomara que eles façam as pazes logo."],
],

24: [
    ["roteiro", "itinerario; guion", "Montamos um roteiro de cinco dias pelo litoral da Bahia."],
    ["trilha", "sendero", "A trilha da Pedra Bonita é fácil, desde que você vá cedo."],
    ["cachoeira", "cascada", "Embora a água seja gelada, vale a pena entrar na cachoeira."],
    ["orçamento", "presupuesto", "Nosso orçamento para a viagem é de três mil reais."],
    ["adiar", "postergar", "Caso chova, vamos adiar o passeio."],
    ["desistir", "desistir, abandonar un plan", "Não desista da viagem só por causa do preço!"],
    ["pôr do sol", "atardecer, puesta de sol", "No verão, muita gente aplaude o pôr do sol no Arpoador."],
    ["mochilão", "viaje de mochilero", "Quero fazer um mochilão pela América do Sul antes que acabem as férias."],
    ["fuso horário", "huso horario, diferencia horaria", "Confira o fuso horário antes de marcar a reunião."],
    ["lotado", "lleno, repleto", "No carnaval, o metrô fica lotado."],
    ["topar", "aceptar (una propuesta), animarse", "Vamos a Petrópolis sábado? Você topa?"],
    ["bate-volta", "ida y vuelta en el día", "Fizemos um bate-volta do Rio a Petrópolis."],
],

25: [
    ["cara", "tipo, chabón (coloquial)", "O cara que mora no terceiro andar toca violão."],
    ["gente boa", "buena gente, buena onda", "O dono do quiosque é gente boa."],
    ["metido", "creído, agrandado", "Ele é bonito, mas é muito metido."],
    ["fofo", "tierno, adorable", "O cachorro que a gente adotou é muito fofo."],
    ["treco", "cosa, chirimbolo (coloquial)", "Que treco é esse que você comprou na feira?"],
    ["sobrado", "casa de dos plantas", "Moramos num sobrado cuja varanda dá para a rua."],
    ["morro", "cerro; (en Río) favela", "Do alto do morro, a vista da baía é incrível."],
    ["orla", "costanera, borde de la playa", "A orla de Copacabana tem uns quatro quilômetros."],
    ["calçadão", "paseo junto al mar", "O calçadão, cujo desenho imita ondas, é de pedra portuguesa."],
    ["barraca", "puesto de playa; carpa", "Alugamos cadeira e guarda-sol na barraca do Seu Zé."],
    ["estojo", "cartuchera, estuche", "Onde está o estojo em que guardei os óculos?"],
    ["magrelo", "flaco (coloquial)", "Aquele menino magrelo que joga no gol é meu primo."],
],

26: [],

}
