# -*- coding: utf-8 -*-
"""Palabras de la semana, estação 2 (semanas 14-26).

[palabra en portugués, significado en español, oración de ejemplo].
12 por semana; la semana 26 (CHEFÃO) no tiene.  Los ejemplos usan solo la
gramática vista hasta esa semana.
"""

VOCAB = {

14: [
    ["gostoso", "rico, sabroso (comida); agradable", "Esse pastel de queijo está muito gostoso!", "Para comida suele ir con *estar*: *está gostoso*. Aplicado a una persona significa «está buena/o», con tono sexual: cuidado."],
    ["pastel", "empanada frita (no «pastel» de torta)", "Na feira de domingo a gente come pastel com caldo de cana.", "Falso amigo: empanada frita de feria. La torta es *bolo*. Combo clásico: *pastel com caldo de cana*."],
    ["aipim", "mandioca, yuca (así se dice en Río)", "No boteco pedimos aipim frito com o chope.", "Mismo tubérculo, tres nombres: *aipim* en Río, *mandioca* en São Paulo, *macaxeira* en el Nordeste. Masculino: *o aipim*."],
    ["farofa", "harina de mandioca tostada (acompaña la feijoada)", "Feijoada sem farofa não é feijoada!", "Femenino: *a farofa*. Coloquial: *farofeiro* = el que lleva la comida de casa a la playa, algo despectivo."],
    ["petisco", "algo para picar, picada", "Os petiscos desse bar são ótimos: bolinho de bacalhau e pastel.", "Masculino; el verbo es *petiscar* = picar. Diminutivo muy usado: *um petisquinho*."],
    ["feijão", "porotos (y el guiso diario de porotos)", "No Brasil, arroz com feijão é o almoço de todo dia.", "Masculino y colectivo: *o feijão*. *Arroz com feijão* también significa «lo básico, lo de siempre»."],
    ["violão", "guitarra criolla, acústica (no «violín»)", "Meu amigo toca bossa nova no violão.", "Falso amigo: la guitarra acústica; el violín es *violino* y la eléctrica, *guitarra*. Sin artículo: *tocar violão*."],
    ["torcer", "hinchar por un equipo; retorcer", "Eu torço pelo Flamengo, e você?", "Hinchar pide *por* o *para*: *torço pelo Flamengo*. La hinchada es *a torcida*; el hincha, *o torcedor*."],
    ["time", "equipo (de fútbol)", "Qual é o seu time do coração?", "Del inglés *team*, masculino: *o time*. *Time do coração* = el cuadro del que sos hincha. En Portugal: *equipa*."],
    ["goleiro", "arquero", "O goleiro defendeu o pênalti no último minuto.", "*Gol* + sufijo de oficio *-eiro*. Atajar se dice *defender*: *o goleiro defendeu o pênalti*."],
    ["pelada", "picado de fútbol, partido informal", "Toda quinta tem pelada na areia de Copacabana.", "Coloquial y femenino: *jogar uma pelada*. Ojo: *pelado* / *pelada* también es «desnudo»."],
    ["academia", "gimnasio (no una academia de estudios)", "Vou à academia três vezes por semana.", "Falso amigo: gimnasio. *Ir à academia*; entrenar en el habla es *malhar*."],
],

15: [
    ["brincar", "jugar (los chicos); bromear", "Quando eu era pequeno, brincava na rua até tarde.", "Jugar de chico: *brincar de* + juego (*brincar de esconde-esconde*). Un deporte se *joga*: *jogar bola*. También bromear: *estou brincando*."],
    ["brinquedo", "juguete", "Meu brinquedo favorito era um carrinho de madeira.", "De *brincar*: lo que se usa para jugar. Masculino: *o brinquedo*; la juguetería es *loja de brinquedos*."],
    ["pular", "saltar", "As crianças pulavam as ondas em Copacabana.", "*Pular corda* = saltar la soga; *pular uma página* = saltearla. *Pular carnaval* = ir a bailar al carnaval."],
    ["boneca", "muñeca (el juguete)", "Minha irmã tinha uma boneca de pano.", "Femenino; el muñeco es *boneco*. El material va con *de*: *boneca de pano* = muñeca de trapo."],
    ["pipa", "barrilete (el juguete)", "No verão, os meninos soltavam pipa no Aterro do Flamengo.", "Femenino. *Soltar pipa* = remontar barrilete. En otras regiones: *papagaio* o *pandorga*."],
    ["apontador", "sacapuntas", "Eu sempre esquecia o apontador na escola.", "De *apontar* = sacarle punta (y también señalar). Masculino: *o apontador*."],
    ["esconde-esconde", "las escondidas (juego)", "A gente brincava de esconde-esconde na casa da minha avó.", "Juego = verbo repetido: *esconde-esconde*, *pega-pega* (la mancha). Va con *brincar de*."],
    ["moleque", "pibe, chico (coloquial)", "Os moleques jogavam bola na rua todo dia.", "Coloquial; femenino *moleca*. *Molecagem* = travesura. Puede ser cariñoso o despectivo según el tono."],
    ["quintal", "patio, fondo (de una casa)", "A casa dos meus avós tinha um quintal enorme.", "Falso amigo: el patio o fondo de la casa, no una quinta. *No quintal* (em + o)."],
    ["bonde", "tranvía", "O bonde de Santa Teresa passava na frente da nossa casa.", "Masculino: *o bonde*. El de Santa Teresa es el tranvía histórico de Río."],
    ["costumar", "soler", "A gente costumava passar as férias em Petrópolis.", "*Costumar* + infinitivo, sin preposición: *costumo acordar cedo*. Pasado habitual: *costumava* + infinitivo."],
    ["merenda", "colación, merienda escolar", "Na escola, a merenda era pão com manteiga e suco.", "La comida que da la escuela: *merenda escolar*. La merienda de la tarde, en el habla común, es *lanche*."],
],

16: [
    ["presente", "regalo (y también «presente»)", "Comprei um presente para a minha mãe e dei para ela ontem.", "Regalo: *dar um presente para alguém*; *de presente* = de regalo. También es el tiempo verbal y «presente» (que está)."],
    ["embrulhar", "envolver (para regalo)", "Você pode embrulhar para presente, por favor?", "*Embrulhar para presente* = envolver para regalo. *Embrulhar o estômago* = revolver el estómago."],
    ["lembrancinha", "recuerdito, souvenir", "Trouxe uma lembrancinha do Rio para você.", "Diminutivo de *lembrança* (recuerdo). *Mande lembranças* = mandá saludos."],
    ["emprestar", "prestar", "Me empresta seu carregador? Te devolvo amanhã.", "Prestar: *me empresta?* Pedir prestado se dice *pegar emprestado*: *peguei o livro emprestado*."],
    ["sacola", "bolsa (de compras)", "— Quer uma sacola? — Não precisa, obrigado.", "Bolsa de compras. *Bolsa* es la cartera de mujer, y también la beca: *bolsa de estudos*."],
    ["vitrine", "vidriera", "Vi um tênis lindo na vitrine e comprei.", "Femenino: *a vitrine*, del francés. *Olhar vitrine* = mirar vidrieras sin comprar."],
    ["fiado", "al fiado (pagar después)", "O dono da padaria vendia fiado para os vizinhos.", "Sin artículo, como adverbio: *vender fiado*, *comprar fiado*. Viene de *fiar* (confiar)."],
    ["quebrar o galho", "dar una mano, sacar de un apuro", "Obrigado pelo guarda-chuva: você quebrou o galho!", "Coloquial, literal «romper la rama». Se conjuga *quebrar*: *você quebrou o galho*. *Um quebra-galho* = solución provisoria."],
    ["camelô", "vendedor ambulante", "Comprei esses óculos de sol de um camelô no centro.", "Aguda con *ô*. *Comprar no camelô*; *camelódromo* = mercado de vendedores ambulantes."],
    ["pechinchar", "regatear", "Na feira, a Bia sempre pechincha e consegue um desconto.", "Regatear. El precio regalado es *uma pechincha*: *essa camisa foi uma pechincha*."],
    ["trocar", "cambiar (una cosa por otra)", "A camisa ficou pequena: posso trocá-la?", "Cambiar una cosa por otra, con *por*: *trocar por um tamanho maior*. También cambiar dinero: *trocar dinheiro*."],
    ["encomenda", "paquete, pedido (por encargo)", "Minha encomenda chegou e o porteiro a recebeu.", "Paquete o pedido. *Fazer uma encomenda* = encargar algo; *de encomenda* = hecho a pedido."],
],

17: [
    ["chuva", "lluvia", "A previsão diz que amanhã teremos chuva forte.", "Ll- española → *ch-*: *lluvia → chuva*, *llover → chover*. *Tomar chuva* = mojarse con la lluvia."],
    ["garoa", "llovizna", "Em São Paulo, a garoa não para o dia todo.", "Típica de São Paulo, la *terra da garoa*. Verbo: *garoar* = lloviznar."],
    ["abafado", "pesado, sofocante (el clima)", "Hoje está muito abafado: acho que vai chover à tarde.", "Clima húmedo y pesado: *está abafado*. De *abafar* = sofocar, tapar; también tapar un escándalo."],
    ["trovão", "trueno", "Amanhã teremos chuva com trovões à tarde.", "Plural *trovões*. El rayo es *o raio* y el relámpago, *o relâmpago*. Verbo: *trovejar*."],
    ["aula", "clase (no el salón)", "A aula de português começará às oito.", "Falso amigo: la clase (el evento); el salón es *a sala de aula*. *Dar aula* = dar clase."],
    ["ensino médio", "secundario (la escuela)", "Ano que vem meu filho terminará o ensino médio.", "Los años finales antes de la universidad; antes viene el *ensino fundamental*. *Ensino* = enseñanza."],
    ["prova", "examen, prueba", "Amanhã teremos prova de matemática.", "Examen escolar. *Fazer uma prova* = rendir; *passar na prova* = aprobar. También prueba de algo: *a prova do crime*."],
    ["formatura", "graduación, fiesta de egreso", "A formatura será em dezembro.", "Graduación y fiesta de egreso. Verbo: *formar-se* = recibirse: *ela se formou em direito*."],
    ["lição de casa", "tarea (para el hogar)", "Depois da escola farei a lição de casa.", "Más de São Paulo; en Río se oye más *dever de casa*. *Fazer a lição* = hacer la tarea."],
    ["trampo", "laburo (coloquial, São Paulo)", "Amanhã vou chegar tarde no trampo.", "Coloquial paulista; verbo *trampar* = laburar. Neutro: *trabalho*."],
    ["férias", "vacaciones", "Nas férias de julho iremos a Salvador.", "Siempre plural: *as férias*, *nas férias*. *Estar de férias* = estar de vacaciones."],
    ["cansativo", "cansador, agotador", "A semana será cansativa: teremos três provas.", "Lo que cansa: *uma semana cansativa*. Quien se cansa está *cansado*."],
],

18: [
    ["cardápio", "menú, carta", "Você poderia me trazer o cardápio, por favor?", "Masculino: *o cardápio*. En Portugal se dice *ementa*; *menu* también se entiende."],
    ["freguês", "cliente (habitual)", "O dono do boteco conhece cada freguês pelo nome.", "Cliente habitual; femenino *freguesa*. *A freguesia* = la clientela."],
    ["gorjeta", "propina", "No Brasil, a gorjeta de dez por cento já vem na conta.", "En restaurantes suele venir en la cuenta como *os dez por cento*, que es opcional. *Deixar gorjeta* = dejar propina."],
    ["sobremesa", "postre (no «sobremesa»)", "De sobremesa, eu gostaria de um pudim.", "Falso amigo: postre. *De sobremesa* = de postre. La charla de después de comer no tiene nombre fijo."],
    ["guardanapo", "servilleta", "Moço, você poderia me trazer mais guardanapos?", "Masculino: *o guardanapo*. *Guardanapo de papel* = servilleta de papel."],
    ["talheres", "cubiertos", "Faltam os talheres na nossa mesa.", "Casi siempre plural; singular *o talher*. Las piezas: *garfo* (tenedor), *faca* (cuchillo), *colher* (cuchara)."],
    ["diária", "tarifa por noche (en un hotel)", "A diária do hotel inclui café da manhã.", "Precio por día; en hoteles, por noche. La *diarista* es la empleada doméstica que cobra por día."],
    ["prato feito", "plato del día barato (el PF)", "No centro, o prato feito custa uns vinte reais.", "Abreviado *PF*: arroz, feijão, carne y ensalada a precio fijo. *Feito* es el participio de *fazer*."],
    ["conserto", "arreglo, reparación (no «concierto»)", "O conserto do ar-condicionado sairia muito caro.", "Con *s* es arreglo; con *c*, *concerto* es el concierto, y suenan igual. Verbo: *consertar* = arreglar."],
    ["encanador", "plomero", "Seria bom chamar um encanador: a pia está pingando.", "De *cano* (caño). En Portugal: *canalizador*. En el habla carioca también se le dice *bombeiro*."],
    ["chuveiro", "ducha", "O chuveiro do quarto não esquenta: você poderia mandar alguém?", "De *chuva*: la ducha. Bañarse es *tomar banho*, aunque sea en ducha. El *chuveiro elétrico* calienta el agua en el cabezal."],
    ["saideira", "la última ronda antes de irse", "Vamos tomar a saideira e ir embora?", "De *sair* (salir). Se pide *a saideira*: la última antes de irse, que casi nunca es la última."],
],

19: [
    ["saia", "pollera", "Essa saia é mais curta do que a outra.", "Ojo: *saia* es pollera y también «salga» (de *sair*). *Saia justa* = situación incómoda."],
    ["casaco", "abrigo, campera", "No Rio quase ninguém precisa de casaco.", "Masculino: abrigo o campera en general. El saco del traje es *o paletó*; el traje entero, *o terno*."],
    ["calça", "pantalón (no «calza»)", "Essa calça jeans é mais barata na outra loja.", "Suele ir en singular: *a calça jeans*, *essa calça*. La calza es *legging*."],
    ["tênis", "zapatillas", "Meu tênis novo é mais confortável do que o velho.", "Igual en singular y plural, y nombra el par: *meu tênis novo*. También el deporte: *jogar tênis*."],
    ["chinelo", "ojotas", "Carioca vai à padaria de chinelo.", "Ojota (tipo Havaianas); la pantufla es *pantufa*. *Pé de chinelo* = alguien de poca monta."],
    ["sunga", "malla (slip) de hombre", "Na praia de Ipanema, muitos homens usam sunga, não bermuda.", "Femenino: *a sunga*, la malla ajustada de hombre. La malla tipo short es *bermuda*."],
    ["gravata", "corbata", "No trabalho ele usa terno e gravata, mesmo no calor.", "Femenino: *a gravata*. *Terno e gravata* = traje y corbata."],
    ["cinto", "cinturón", "Esse cinto de couro é caríssimo.", "Masculino: *o cinto*; *cinto de segurança* = cinturón de seguridad. *A cintura* es la cintura."],
    ["tamanho", "talle, tamaño", "Tem esse vestido num tamanho menor?", "*Que tamanho você usa?* = ¿qué talle usás? Los talles: *P, M, G* (pequeno, médio, grande). *Nh* = ñ."],
    ["prestação", "cuota", "Comprei a televisão em dez prestações.", "*Em dez prestações* = en diez cuotas. También se dice *parcelado*: *em dez vezes sem juros*."],
    ["brinco", "aro (de oreja)", "Esses brincos de prata são mais baratos do que os de ouro.", "Masculino, casi siempre plural: *os brincos*. No confundir con *brinquedo* (juguete)."],
    ["brechó", "tienda de ropa usada", "Comprei essa jaqueta num brechó em Botafogo: foi baratíssima.", "Aguda con *ó*: *um brechó*. Ropa usada es *roupa de segunda mão*."],
],

20: [
    ["de jeito nenhum", "de ninguna manera", "Pagar trinta reais num coco? De jeito nenhum!", "*Jeito* = manera. Doble negación normal: *não vou de jeito nenhum*. Sola, como respuesta: *De jeito nenhum!*"],
    ["um monte de", "un montón de", "Tinha um monte de gente no bloco.", "Coloquial: *um monte de* + sustantivo sin artículo: *um monte de gente*, *um monte de coisas*. Neutro: *muito*, *muitos*."],
    ["demais", "demasiado; muchísimo", "Essa praia é linda demais!", "Va después: *linda demais* = hermosísima, *comi demais* = comí demasiado. *Os demais* = los demás."],
    ["nossa!", "¡uy!, ¡guau!", "Nossa, que calor!", "De *Nossa Senhora!*: sorpresa, admiración o susto. Muy frecuente: *Nossa, que calor!*"],
    ["puxa", "¡uh! (lástima o sorpresa)", "Puxa, que pena que você não veio.", "De *puxar* (tirar). Sorpresa o lástima: *Puxa, que pena!*; también *Puxa vida!*"],
    ["imagina", "¡de nada!, ¡para nada!", "— Obrigada pela ajuda! — Imagina!", "Imperativo de *imaginar*: respuesta amable a *obrigado* o a una disculpa, como «¡por favor, nada que ver!»."],
    ["sei lá", "qué sé yo", "— Onde ele está? — Sei lá, ninguém sabe.", "*Sei* (de *saber*, irregular: *eu sei*) + *lá*. También muletilla de duda: *sei lá, acho que sim*."],
    ["bater papo", "charlar", "A gente ficou batendo papo no calçadão até meia-noite.", "*Papo* = charla: *um bate-papo* = una charla; *papo furado* = pavadas. Se conjuga *bater*: *batemos papo*."],
    ["bacana", "bárbaro, piola", "Seu apartamento é muito bacana!", "Coloquial e invariable en género: *um cara bacana*, *uma festa bacana*. Parecido a *legal*."],
    ["combinado", "trato hecho, quedamos así", "— Às oito no Arpoador? — Combinado!", "Participio de *combinar* que sella un acuerdo. Refrán: *o combinado não sai caro* = lo pactado evita problemas."],
    ["tanto faz", "da igual", "— Praia ou piscina? — Tanto faz, as duas são ótimas.", "Fórmula fija: me da igual. Con pronombre: *para mim tanto faz*."],
    ["fala sério!", "¡no te puedo creer!, ¡hablá en serio!", "— Ninguém veio à festa. — Fala sério!", "Imperativo de *falar*: incredulidad o fastidio. Coloquial; parecido: *tá de brincadeira!* = ¡me estás cargando!"],
],

21: [
    ["sumir", "desaparecer", "Você sumiu! Por onde tem andado?", "*Você sumiu!* = ¡no te vi más! Irregular en la vocal: *eu sumo*, *ele some*."],
    ["emagrecer", "adelgazar", "Ela tem corrido todo dia e emagreceu cinco quilos.", "De *magro*; opuesto: *engordar*. Sin *de*: *emagreceu cinco quilos*. Ojo a la grafía: *eu emagreço*."],
    ["engravidar", "quedar embarazada", "A Carla engravidou e vai ter gêmeos.", "De *grávida*. Sin *se*: *ela engravidou*. Falso amigo: *embaraçada* es avergonzada."],
    ["aposentar-se", "jubilarse", "Meu pai se aposentou no ano passado e agora pesca todo dia.", "Pronominal: *ele se aposentou*. El jubilado es *aposentado*; la jubilación, *a aposentadoria*."],
    ["casamento", "casamiento, boda", "O casamento da Bia tem sido o assunto da família.", "Boda y matrimonio. *Casar com* alguien, con o sin *se*: *eles (se) casaram*."],
    ["careca", "pelado, calvo", "O Rafa ficou careca: raspou a cabeça.", "Adjetivo y sustantivo, igual en género: *ficou careca*, *um careca*. Ojo: *pelado* es desnudo."],
    ["caçula", "el hermano menor, el más chico", "O caçula da família entrou na faculdade.", "El hijo o hermano menor, igual en género: *o caçula*, *a caçula*. Viene del quimbundo, lengua de Angola."],
    ["parar de", "dejar de (hacer algo)", "Meu pai parou de fumar e tem dormido melhor.", "*Parar de* + infinitivo = dejar de: *parei de fumar*. Sin *de*, *parar* = detenerse."],
    ["aliás", "por cierto; mejor dicho", "Aliás, você soube que a Ana tem um namorado novo?", "Agrega un dato de paso (*aliás, você soube…?*) o corrige lo dicho: *amanhã, aliás, depois de amanhã*."],
    ["pois é", "y sí, así es", "— O Rio tem mudado muito. — Pois é.", "Muy brasileño para darle la razón al otro sin agregar nada: «y sí». *Pois* solo = pues, entonces."],
    ["neném", "bebé", "O neném da vizinha tem chorado a noite toda.", "Aguda con *-ém* nasal, igual en género: *o neném*, *a neném*. Sinónimo: *bebê*."],
    ["rolar", "pasar, suceder (coloquial)", "E aí, o que rolou na festa?", "Coloquial: *o que rolou?* = ¿qué pasó? *Vai rolar* = se va a hacer. Sentido literal: rodar."],
],

22: [
    ["delegacia", "comisaría", "O roubo foi registrado na delegacia de Copacabana.", "De *delegado* (el comisario). *Ir à delegacia*. *Delegacia da Mulher* = comisaría de la mujer."],
    ["boletim de ocorrência", "denuncia policial (el BO)", "Depois do assalto, foi feito um boletim de ocorrência.", "Se abrevia *BO*: *fazer um BO* = hacer la denuncia. *Ocorrência* = hecho, incidente."],
    ["RG", "documento de identidad (como el DNI)", "Meu RG foi roubado e já pedi outro.", "Sigla de *Registro Geral*; se lee «erre-gê». Masculino: *o RG*. También se dice *a identidade*."],
    ["prefeitura", "municipalidad", "A obra foi feita pela prefeitura.", "El intendente es *o prefeito*. *A prefeitura do Rio* = la municipalidad de Río."],
    ["CPF", "número de contribuyente (se pide en todo trámite)", "Para abrir a conta, o CPF é exigido.", "*Cadastro de Pessoas Físicas*; se lee «cê-pê-efe». Te lo piden hasta en la farmacia: *CPF na nota?*"],
    ["xerox", "fotocopia", "A xerox do documento precisa ser autenticada.", "Marca convertida en nombre común: *tirar xerox* = sacar fotocopia."],
    ["lotérica", "agencia de lotería (donde también se pagan cuentas)", "A conta de luz pode ser paga na lotérica.", "Abreviatura de *casa lotérica*: ahí se juega a la *Mega-Sena* y se pagan boletas y cuentas."],
    ["caixa eletrônico", "cajero automático", "O caixa eletrônico está quebrado desde ontem.", "*O caixa* es el cajero (máquina o persona); *a caixa* es la caja, el objeto."],
    ["pedágio", "peaje", "O preço do pedágio foi aumentado de novo.", "*Pagar o pedágio*. El puesto donde se paga en la ruta es *a praça de pedágio*."],
    ["passeata", "marcha, manifestación", "A passeata foi organizada pelos estudantes.", "Marcha a pie; *manifestação* es el término general. *Fazer uma passeata*."],
    ["desabamento", "derrumbe", "Ninguém foi ferido no desabamento do prédio.", "De *desabar* = derrumbarse: *o prédio desabou*. El alud de tierra es *deslizamento*."],
    ["bombeiro", "bombero", "O incêndio foi apagado pelos bombeiros.", "De *bomba* (la de agua). En el habla de Río, *bombeiro* también es el plomero."],
],

23: [
    ["namorar", "ser novio de, salir con (sin preposición)", "Tomara que ela namore alguém bacana.", "Sin preposición: *namorar alguém*, nunca «con». *Eles namoram* = están de novios. *O namoro* = el noviazgo."],
    ["brigar", "pelearse, discutir", "Espero que vocês não briguem por isso.", "Pelearse sin *se*: *eles brigaram*; con alguien: *brigar com*. Subjuntivo con *gu*: *que vocês não briguem*."],
    ["ciúme", "celos", "Ele tem ciúme de todo mundo.", "*Ter ciúme de alguém* = tener celos; también en plural, *ciúmes*. Celoso = *ciumento*."],
    ["cafuné", "caricia en el pelo", "Não tem nada melhor do que um cafuné antes de dormir.", "Sin equivalente en español; de origen africano. Va con *fazer*: *fazer cafuné em alguém*."],
    ["tontura", "mareo (no «tontería»)", "É normal que você sinta tontura depois da vacina.", "Falso amigo: mareo. *Estar com tontura*. La tontería es *bobagem*."],
    ["enjoo", "náusea; mareo (en barco)", "Tomei um remédio para o enjoo antes de pegar a barca.", "Sin tilde desde 1990 (antes *enjôo*). Verbo *enjoar*, también = hartarse: *enjoei dessa música*."],
    ["posto de saúde", "salita, centro de salud del barrio", "É melhor que você vá ao posto de saúde.", "*Posto* = puesto: *posto de gasolina*, *posto de saúde*. Atiende el *SUS*, el sistema público de salud."],
    ["curativo", "curita, apósito", "É bom que você troque o curativo todo dia.", "Apósito o curación: *fazer um curativo*. La curita de marca es *Band-Aid*."],
    ["encontro", "cita (romántica); encuentro", "Tomara que ela goste do encontro de sábado.", "Cita romántica y encuentro. *Encontrar-se com alguém* = verse con alguien."],
    ["levar um fora", "que te larguen o te rechacen", "Espero que ele não leve um fora de novo.", "*Levar um fora* = ser rechazado; *dar um fora* = rechazar a alguien o meter la pata. Se conjuga *levar*."],
    ["dica", "consejo, dato", "Uma dica: beba muita água no verão carioca.", "Femenino: *uma dica*. *Dar uma dica* = pasar un dato, dar una pista."],
    ["fazer as pazes", "amigarse, reconciliarse", "Tomara que eles façam as pazes logo.", "Siempre plural: *fazer as pazes com alguém*. Se conjuga *fazer*: *que eles façam as pazes*."],
],

24: [
    ["roteiro", "itinerario; guion", "Montamos um roteiro de cinco dias pelo litoral da Bahia.", "Itinerario y guion de cine: *roteirista* = guionista. *Montar um roteiro* = armar un itinerario."],
    ["feriadão", "fin de semana largo", "Caso faça sol no feriadão, vamos a Búzios.", "Aumentativo de *feriado*: fin de semana largo. Tomarse el día puente es *enforcar*: *enforcar a sexta*."],
    ["mirante", "mirador", "Do mirante Dona Marta, a vista do Rio é incrível.", "Masculino: *o mirante*. En portugués *mirar* es apuntar; para mirar se usa *olhar*."],
    ["orçamento", "presupuesto", "Nosso orçamento para a viagem é de três mil reais.", "Presupuesto de gastos y también cotización: *pedir um orçamento*. *Nosso orçamento é de…*"],
    ["adiar", "postergar", "Caso chova, vamos adiar o passeio.", "De *a* + *dia*. Con *para* + fecha: *adiamos para sexta*. El sustantivo: *o adiamento*."],
    ["canga", "pareo (de playa)", "Leva uma canga para que a gente possa sentar na areia.", "Femenino: *a canga*. Sirve de lona para sentarse en la arena y de pareo."],
    ["pôr do sol", "atardecer, puesta de sol", "No verão, muita gente aplaude o pôr do sol no Arpoador.", "*Pôr* con tilde es el verbo poner («ponerse del sol»). Masculino y sin guiones desde 1990: *o pôr do sol*."],
    ["estrada", "ruta, carretera", "Vamos sair cedo, antes que a estrada fique cheia.", "Ruta, camino. *Pegar a estrada* = salir a la ruta; *estrada de terra* = camino de tierra."],
    ["aproveitar", "aprovechar, disfrutar", "Aproveite as férias, embora sejam curtas!", "Sin *de*: *aproveite as férias*. Con *se* + *de* es abusar: *aproveitar-se de alguém*."],
    ["lotado", "lleno, repleto", "No carnaval, o metrô fica lotado.", "Lleno de gente, sobre todo transporte o lugares: *o metrô fica lotado*."],
    ["passagem", "pasaje (boleto de viaje)", "Compre a passagem antes que o preço suba.", "Boleto de viaje: *passagem de avião*, *de ônibus*. Las palabras en *-agem* son femeninas: *a passagem*, *a viagem*."],
    ["bate-volta", "ida y vuelta en el día", "Fizemos um bate-volta do Rio a Petrópolis.", "*Bater* + *voltar*: ida y vuelta en el día, sin dormir allá. *Fazer um bate-volta*."],
],

25: [
    ["sujeito", "tipo, sujeto", "O sujeito que mora no terceiro andar toca violão.", "Tipo, fulano, algo coloquial: *um sujeito estranho*. También adjetivo: *sujeito a mudanças* = sujeto a cambios."],
    ["gente boa", "buena gente, buena onda", "O dono do quiosque é gente boa.", "Invariable, aunque sea uno solo: *ele é gente boa*, *ela é gente boa*."],
    ["metido", "creído, agrandado", "Ele é bonito, mas é muito metido.", "Creído, agrandado; en el habla, *metido a besta*. El entrometido es *intrometido*."],
    ["fofo", "tierno, adorable", "O cachorro que a gente adotou é muito fofo.", "Tierno, adorable; también blando: *travesseiro fofo*. Muy usado con bebés y mascotas."],
    ["treco", "cosa, chirimbolo (coloquial)", "Que treco é esse que você comprou na feira?", "Coloquial y masculino: *esse treco* = esa cosa. Sinónimos: *troço*, *negócio*."],
    ["sobrado", "casa de dos plantas", "Moramos num sobrado cujo portão é azul.", "Falso amigo: casa de dos plantas. Lo que sobra es *sobrando*: *tem comida sobrando*."],
    ["varanda", "balcón, galería", "O apartamento cuja varanda dá para o mar é o mais caro.", "Balcón o galería: *a varanda dá para o mar*. *Dar para* = dar a, tener vista a."],
    ["boné", "gorra", "O menino que perdeu o boné está chorando.", "Aguda con *é*, masculino: *o boné*. Se usa con *usar* o *pôr*: *pôr o boné*."],
    ["calçadão", "paseo junto al mar", "O calçadão, cujo desenho imita ondas, é de pedra portuguesa.", "Aumentativo de *calçada* (vereda). El de Copacabana tiene las ondas de piedra portuguesa."],
    ["barraca", "puesto de playa; carpa", "Alugamos cadeira e guarda-sol na barraca do Seu Zé.", "En la playa, el puesto que alquila silla y sombrilla; en el camping, la carpa: *montar a barraca*."],
    ["estojo", "cartuchera, estuche", "Onde está o estojo em que guardei os óculos?", "Masculino: *o estojo*. *Estojo de óculos* = estuche de anteojos."],
    ["magrelo", "flaco (coloquial)", "Aquele menino magrelo que joga no gol é meu primo.", "Coloquial, a veces cariñoso: *magrelo*, *magrela*. En el habla, *magrela* también es la bici."],
],

26: [],

}
