# -*- coding: utf-8 -*-
"""Palabras de la semana, estação 2 (semanas 14-26).

[palabra en portugués, significado en español, oración de ejemplo].
12 por semana; la semana 26 (CHEFÃO) no tiene.  Los ejemplos usan solo la
gramática vista hasta esa semana.
"""

VOCAB = {

14: [
    ["gostoso", "rico, sabroso (comida); agradable", "Esse pastel de queijo está muito gostoso!"],
    ["pastel", "empanada frita (no «pastel» de torta)", "Na feira de domingo a gente come pastel com caldo de cana."],
    ["aipim", "mandioca, yuca (así se dice en Río)", "No boteco pedimos aipim frito com o chope."],
    ["farofa", "harina de mandioca tostada (acompaña la feijoada)", "Feijoada sem farofa não é feijoada!"],
    ["petisco", "algo para picar, picada", "Os petiscos desse bar são ótimos: bolinho de bacalhau e pastel."],
    ["feijão", "porotos (y el guiso diario de porotos)", "No Brasil, arroz com feijão é o almoço de todo dia."],
    ["violão", "guitarra criolla, acústica (no «violín»)", "Meu amigo toca bossa nova no violão."],
    ["torcer", "hinchar por un equipo; retorcer", "Eu torço pelo Flamengo, e você?"],
    ["time", "equipo (de fútbol)", "Qual é o seu time do coração?"],
    ["goleiro", "arquero", "O goleiro defendeu o pênalti no último minuto."],
    ["pelada", "picado de fútbol, partido informal", "Toda quinta tem pelada na areia de Copacabana."],
    ["academia", "gimnasio (no una academia de estudios)", "Vou à academia três vezes por semana."],
],

15: [
    ["brincar", "jugar (los chicos); bromear", "Quando eu era pequeno, brincava na rua até tarde."],
    ["brinquedo", "juguete", "Meu brinquedo favorito era um carrinho de madeira."],
    ["pular", "saltar", "As crianças pulavam as ondas em Copacabana."],
    ["boneca", "muñeca (el juguete)", "Minha irmã tinha uma boneca de pano."],
    ["pipa", "barrilete (el juguete)", "No verão, os meninos soltavam pipa no Aterro do Flamengo."],
    ["apontador", "sacapuntas", "Eu sempre esquecia o apontador na escola."],
    ["esconde-esconde", "las escondidas (juego)", "A gente brincava de esconde-esconde na casa da minha avó."],
    ["moleque", "pibe, chico (coloquial)", "Os moleques jogavam bola na rua todo dia."],
    ["quintal", "patio, fondo (de una casa)", "A casa dos meus avós tinha um quintal enorme."],
    ["bonde", "tranvía", "O bonde de Santa Teresa passava na frente da nossa casa."],
    ["costumar", "soler", "A gente costumava passar as férias em Petrópolis."],
    ["merenda", "colación, merienda escolar", "Na escola, a merenda era pão com manteiga e suco."],
],

16: [
    ["presente", "regalo (y también «presente»)", "Comprei um presente para a minha mãe e dei para ela ontem."],
    ["embrulhar", "envolver (para regalo)", "Você pode embrulhar para presente, por favor?"],
    ["lembrancinha", "recuerdito, souvenir", "Trouxe uma lembrancinha do Rio para você."],
    ["emprestar", "prestar", "Me empresta seu carregador? Te devolvo amanhã."],
    ["sacola", "bolsa (de compras)", "— Quer uma sacola? — Não precisa, obrigado."],
    ["vitrine", "vidriera", "Vi um tênis lindo na vitrine e comprei."],
    ["fiado", "al fiado (pagar después)", "O dono da padaria vendia fiado para os vizinhos."],
    ["quebrar o galho", "dar una mano, sacar de un apuro", "Obrigado pelo guarda-chuva: você quebrou o galho!"],
    ["camelô", "vendedor ambulante", "Comprei esses óculos de sol de um camelô no centro."],
    ["pechinchar", "regatear", "Na feira, a Bia sempre pechincha e consegue um desconto."],
    ["trocar", "cambiar (una cosa por otra)", "A camisa ficou pequena: posso trocá-la?"],
    ["encomenda", "paquete, pedido (por encargo)", "Minha encomenda chegou e o porteiro a recebeu."],
],

17: [
    ["chuva", "lluvia", "A previsão diz que amanhã teremos chuva forte."],
    ["garoa", "llovizna", "Em São Paulo, a garoa não para o dia todo."],
    ["abafado", "pesado, sofocante (el clima)", "Hoje está muito abafado: acho que vai chover à tarde."],
    ["trovão", "trueno", "Amanhã teremos chuva com trovões à tarde."],
    ["aula", "clase (no el salón)", "A aula de português começará às oito."],
    ["ensino médio", "secundario (la escuela)", "Ano que vem meu filho terminará o ensino médio."],
    ["prova", "examen, prueba", "Amanhã teremos prova de matemática."],
    ["formatura", "graduación, fiesta de egreso", "A formatura será em dezembro."],
    ["lição de casa", "tarea (para el hogar)", "Depois da escola farei a lição de casa."],
    ["trampo", "laburo (coloquial, São Paulo)", "Amanhã vou chegar tarde no trampo."],
    ["férias", "vacaciones", "Nas férias de julho iremos a Salvador."],
    ["cansativo", "cansador, agotador", "A semana será cansativa: teremos três provas."],
],

18: [
    ["cardápio", "menú, carta", "Você poderia me trazer o cardápio, por favor?"],
    ["freguês", "cliente (habitual)", "O dono do boteco conhece cada freguês pelo nome."],
    ["gorjeta", "propina", "No Brasil, a gorjeta de dez por cento já vem na conta."],
    ["sobremesa", "postre (no «sobremesa»)", "De sobremesa, eu gostaria de um pudim."],
    ["guardanapo", "servilleta", "Moço, você poderia me trazer mais guardanapos?"],
    ["talheres", "cubiertos", "Faltam os talheres na nossa mesa."],
    ["diária", "tarifa por noche (en un hotel)", "A diária do hotel inclui café da manhã."],
    ["prato feito", "plato del día barato (el PF)", "No centro, o prato feito custa uns vinte reais."],
    ["conserto", "arreglo, reparación (no «concierto»)", "O conserto do ar-condicionado sairia muito caro."],
    ["encanador", "plomero", "Seria bom chamar um encanador: a pia está pingando."],
    ["chuveiro", "ducha", "O chuveiro do quarto não esquenta: você poderia mandar alguém?"],
    ["saideira", "la última ronda antes de irse", "Vamos tomar a saideira e ir embora?"],
],

19: [
    ["saia", "pollera", "Essa saia é mais curta do que a outra."],
    ["casaco", "abrigo, campera", "No Rio quase ninguém precisa de casaco."],
    ["calça", "pantalón (no «calza»)", "Essa calça jeans é mais barata na outra loja."],
    ["tênis", "zapatillas", "Meu tênis novo é mais confortável do que o velho."],
    ["chinelo", "ojotas", "Carioca vai à padaria de chinelo."],
    ["sunga", "malla (slip) de hombre", "Na praia de Ipanema, muitos homens usam sunga, não bermuda."],
    ["gravata", "corbata", "No trabalho ele usa terno e gravata, mesmo no calor."],
    ["cinto", "cinturón", "Esse cinto de couro é caríssimo."],
    ["tamanho", "talle, tamaño", "Tem esse vestido num tamanho menor?"],
    ["prestação", "cuota", "Comprei a televisão em dez prestações."],
    ["brinco", "aro (de oreja)", "Esses brincos de prata são mais baratos do que os de ouro."],
    ["brechó", "tienda de ropa usada", "Comprei essa jaqueta num brechó em Botafogo: foi baratíssima."],
],

20: [
    ["de jeito nenhum", "de ninguna manera", "Pagar trinta reais num coco? De jeito nenhum!"],
    ["um monte de", "un montón de", "Tinha um monte de gente no bloco."],
    ["demais", "demasiado; muchísimo", "Essa praia é linda demais!"],
    ["nossa!", "¡uy!, ¡guau!", "Nossa, que calor!"],
    ["puxa", "¡uh! (lástima o sorpresa)", "Puxa, que pena que você não veio."],
    ["imagina", "¡de nada!, ¡para nada!", "— Obrigada pela ajuda! — Imagina!"],
    ["sei lá", "qué sé yo", "— Onde ele está? — Sei lá, ninguém sabe."],
    ["bater papo", "charlar", "A gente ficou batendo papo no calçadão até meia-noite."],
    ["bacana", "bárbaro, piola", "Seu apartamento é muito bacana!"],
    ["combinado", "trato hecho, quedamos así", "— Às oito no Arpoador? — Combinado!"],
    ["tanto faz", "da igual", "— Praia ou piscina? — Tanto faz, as duas são ótimas."],
    ["fala sério!", "¡no te puedo creer!, ¡hablá en serio!", "— Ninguém veio à festa. — Fala sério!"],
],

21: [
    ["sumir", "desaparecer", "Você sumiu! Por onde tem andado?"],
    ["emagrecer", "adelgazar", "Ela tem corrido todo dia e emagreceu cinco quilos."],
    ["engravidar", "quedar embarazada", "A Carla engravidou e vai ter gêmeos."],
    ["aposentar-se", "jubilarse", "Meu pai se aposentou no ano passado e agora pesca todo dia."],
    ["casamento", "casamiento, boda", "O casamento da Bia tem sido o assunto da família."],
    ["careca", "pelado, calvo", "O Rafa ficou careca: raspou a cabeça."],
    ["caçula", "el hermano menor, el más chico", "O caçula da família entrou na faculdade."],
    ["parar de", "dejar de (hacer algo)", "Meu pai parou de fumar e tem dormido melhor."],
    ["aliás", "por cierto; mejor dicho", "Aliás, você soube que a Ana tem um namorado novo?"],
    ["pois é", "y sí, así es", "— O Rio tem mudado muito. — Pois é."],
    ["neném", "bebé", "O neném da vizinha tem chorado a noite toda."],
    ["rolar", "pasar, suceder (coloquial)", "E aí, o que rolou na festa?"],
],

22: [
    ["delegacia", "comisaría", "O roubo foi registrado na delegacia de Copacabana."],
    ["boletim de ocorrência", "denuncia policial (el BO)", "Depois do assalto, foi feito um boletim de ocorrência."],
    ["RG", "documento de identidad (como el DNI)", "Meu RG foi roubado e já pedi outro."],
    ["prefeitura", "municipalidad", "A obra foi feita pela prefeitura."],
    ["CPF", "número de contribuyente (se pide en todo trámite)", "Para abrir a conta, o CPF é exigido."],
    ["xerox", "fotocopia", "A xerox do documento precisa ser autenticada."],
    ["lotérica", "agencia de lotería (donde también se pagan cuentas)", "A conta de luz pode ser paga na lotérica."],
    ["caixa eletrônico", "cajero automático", "O caixa eletrônico está quebrado desde ontem."],
    ["pedágio", "peaje", "O preço do pedágio foi aumentado de novo."],
    ["passeata", "marcha, manifestación", "A passeata foi organizada pelos estudantes."],
    ["desabamento", "derrumbe", "Ninguém foi ferido no desabamento do prédio."],
    ["bombeiro", "bombero", "O incêndio foi apagado pelos bombeiros."],
],

23: [
    ["namorar", "ser novio de, salir con (sin preposición)", "Tomara que ela namore alguém bacana."],
    ["brigar", "pelearse, discutir", "Espero que vocês não briguem por isso."],
    ["ciúme", "celos", "Ele tem ciúme de todo mundo."],
    ["cafuné", "caricia en el pelo", "Não tem nada melhor do que um cafuné antes de dormir."],
    ["tontura", "mareo (no «tontería»)", "É normal que você sinta tontura depois da vacina."],
    ["enjoo", "náusea; mareo (en barco)", "Tomei um remédio para o enjoo antes de pegar a barca."],
    ["posto de saúde", "salita, centro de salud del barrio", "É melhor que você vá ao posto de saúde."],
    ["curativo", "curita, apósito", "É bom que você troque o curativo todo dia."],
    ["encontro", "cita (romántica); encuentro", "Tomara que ela goste do encontro de sábado."],
    ["levar um fora", "que te larguen o te rechacen", "Espero que ele não leve um fora de novo."],
    ["dica", "consejo, dato", "Uma dica: beba muita água no verão carioca."],
    ["fazer as pazes", "amigarse, reconciliarse", "Tomara que eles façam as pazes logo."],
],

24: [
    ["roteiro", "itinerario; guion", "Montamos um roteiro de cinco dias pelo litoral da Bahia."],
    ["feriadão", "fin de semana largo", "Caso faça sol no feriadão, vamos a Búzios."],
    ["mirante", "mirador", "Do mirante Dona Marta, a vista do Rio é incrível."],
    ["orçamento", "presupuesto", "Nosso orçamento para a viagem é de três mil reais."],
    ["adiar", "postergar", "Caso chova, vamos adiar o passeio."],
    ["canga", "pareo (de playa)", "Leva uma canga para que a gente possa sentar na areia."],
    ["pôr do sol", "atardecer, puesta de sol", "No verão, muita gente aplaude o pôr do sol no Arpoador."],
    ["estrada", "ruta, carretera", "Vamos sair cedo, antes que a estrada fique cheia."],
    ["aproveitar", "aprovechar, disfrutar", "Aproveite as férias, embora sejam curtas!"],
    ["lotado", "lleno, repleto", "No carnaval, o metrô fica lotado."],
    ["passagem", "pasaje (boleto de viaje)", "Compre a passagem antes que o preço suba."],
    ["bate-volta", "ida y vuelta en el día", "Fizemos um bate-volta do Rio a Petrópolis."],
],

25: [
    ["sujeito", "tipo, sujeto", "O sujeito que mora no terceiro andar toca violão."],
    ["gente boa", "buena gente, buena onda", "O dono do quiosque é gente boa."],
    ["metido", "creído, agrandado", "Ele é bonito, mas é muito metido."],
    ["fofo", "tierno, adorable", "O cachorro que a gente adotou é muito fofo."],
    ["treco", "cosa, chirimbolo (coloquial)", "Que treco é esse que você comprou na feira?"],
    ["sobrado", "casa de dos plantas", "Moramos num sobrado cujo portão é azul."],
    ["varanda", "balcón, galería", "O apartamento cuja varanda dá para o mar é o mais caro."],
    ["boné", "gorra", "O menino que perdeu o boné está chorando."],
    ["calçadão", "paseo junto al mar", "O calçadão, cujo desenho imita ondas, é de pedra portuguesa."],
    ["barraca", "puesto de playa; carpa", "Alugamos cadeira e guarda-sol na barraca do Seu Zé."],
    ["estojo", "cartuchera, estuche", "Onde está o estojo em que guardei os óculos?"],
    ["magrelo", "flaco (coloquial)", "Aquele menino magrelo que joga no gol é meu primo."],
],

26: [],

}
