# -*- coding: utf-8 -*-
"""Palabras de la semana — Estação 3 (semanas 27-39).

15 palabras por semana, 0 en la semana del chefão (39).  Campo léxico de
SAI_FARE; se priorizan falsos amigos y palabras muy usadas en Brasil.
Cada ejemplo usa solo gramática vista hasta esa semana.
"""

VOCAB = {

27: [  # Planes de vida, mudanzas
    ["a mudança", "la mudanza; también «el cambio»", "Quando a mudança chegar, a gente monta os móveis."],
    ["o aluguel", "el alquiler", "Se o aluguel subir de novo, vamos para Niterói."],
    ["o fiador", "el garante (de un alquiler)", "Sem fiador, a imobiliária pede um seguro."],
    ["o condomínio", "las expensas; también «el consorcio, el edificio»", "O condomínio do prédio é caro, mas tem porteiro."],
    ["a imobiliária", "la inmobiliaria", "Assim que a imobiliária ligar, eu te aviso."],
    ["o prédio", "el edificio", "Moro num prédio antigo em Copacabana."],
    ["o carreto", "el flete (pequeña mudanza)", "Se o carreto chegar cedo, a gente termina hoje."],
    ["o papelão", "el cartón", "Guarda as caixas de papelão para a próxima mudança."],
    ["encaixotar", "embalar en cajas", "Quando vocês encaixotarem os livros, escrevam o nome na caixa."],
    ["o síndico", "el administrador del edificio (vecino elegido)", "O síndico disse que a obra termina em março."],
    ["a quitinete", "el monoambiente", "Enquanto eu estiver sozinho, uma quitinete basta."],
    ["a aposentadoria", "la jubilación", "Quando eu me aposentar, quero morar perto do mar."],
    ["a poupança", "la caja de ahorro; los ahorros", "Se eu juntar dinheiro na poupança, compro um apartamento."],
    ["a caução", "el depósito de garantía", "A caução é de três meses de aluguel."],
    ["o rumo", "el rumbo", "Depois da faculdade, ele mudou de rumo e foi para Salvador."],
],

28: [  # Sueños, decisiones
    ["o sonho", "el sueño (deseo); también «la bola de fraile»", "Meu sonho seria morar em Santa Teresa."],
    ["o azar", "la mala suerte (¡no «el azar»!)", "Que azar! Choveu justo no dia do passeio."],
    ["a sorte", "la suerte", "Se eu tivesse sorte, ganharia na Mega-Sena."],
    ["largar", "dejar, abandonar", "Se pudesse, largaria o emprego e abriria um quiosque na praia."],
    ["topar", "aceptar, animarse a algo", "Você toparia passar um ano em Portugal?"],
    ["encarar", "enfrentar", "Ela encarou a mudança com coragem."],
    ["a coragem", "el coraje, la valentía (femenino)", "Se eu tivesse a coragem dela, já estaria longe daqui."],
    ["desistir", "renunciar, darse por vencido", "Não desista agora: falta pouco."],
    ["cogitar", "considerar, pensar en (una posibilidad)", "Nunca cogitei morar fora do Rio."],
    ["à toa", "sin motivo; al pedo", "Ninguém larga tudo à toa."],
    ["ousar", "atreverse, osar", "Quem ousaria dizer isso ao presidente?"],
    ["o sítio", "la quinta, la chacra (¡no «el sitio»!)", "Se fosse rico, compraria um sítio na serra."],
    ["o mochilão", "el viaje de mochilero", "Queria que você viesse comigo no mochilão pela Bahia."],
    ["apostar", "apostar", "Aposto que ele não vem."],
    ["prestes a", "a punto de", "Estava prestes a desistir quando recebi a notícia."],
],

29: [  # Estudio, trabajo, derechos
    ["o vestibular", "el examen de ingreso a la universidad", "É importante vocês estudarem para o vestibular desde cedo."],
    ["a bolsa", "la beca; también «la cartera»", "Ela ganhou uma bolsa para estudar em Coimbra."],
    ["a matrícula", "la inscripción", "A matrícula abre na segunda: não esqueçam de fazer."],
    ["o estágio", "la pasantía", "Consegui um estágio numa editora do centro."],
    ["a folga", "el franco, el día libre", "Amanhã é minha folga: vou à praia!"],
    ["a greve", "la huelga, el paro", "Os professores entraram em greve por melhores salários."],
    ["demitir", "despedir (del trabajo)", "A empresa demitiu vinte funcionários."],
    ["a carteira assinada", "el trabajo en blanco", "Com carteira assinada, você tem direito a férias."],
    ["o décimo terceiro", "el aguinaldo", "Vou usar o décimo terceiro para pagar as dívidas."],
    ["reprovar", "desaprobar (un examen o a alguien)", "O professor reprovou metade da turma."],
    ["o cursinho", "el curso preuniversitario", "Fiz cursinho um ano antes de passar."],
    ["o concurso", "el concurso público (examen para cargos del Estado)", "Ele estuda para concurso há dois anos."],
    ["a vaga", "la vacante; también «el lugar para estacionar»", "Tem uma vaga de garçom no boteco da esquina."],
    ["o desemprego", "el desempleo", "O desemprego caiu este ano."],
    ["a apostila", "el cuadernillo, el apunte", "Trouxe as apostilas para vocês estudarem juntos."],
],

30: [  # Arrepentimientos, historia personal
    ["o arrependimento", "el arrepentimiento", "Meu único arrependimento é não ter aprendido a nadar."],
    ["vacilar", "mandarse una macana; fallarle a alguien (coloquial)", "Vacilei: se tivesse ligado, ela não teria ficado chateada."],
    ["desabafar", "desahogarse", "Precisava desabafar e liguei para minha irmã."],
    ["a mágoa", "el resentimiento, la herida", "Não guardo mágoa de ninguém."],
    ["magoar", "herir, lastimar (sentimientos)", "Espero que não tenha magoado você."],
    ["perder o bonde", "perder el tren (una oportunidad)", "Se tivesse aceitado a proposta, não teria perdido o bonde."],
    ["amadurecer", "madurar", "Depois da viagem, ela amadureceu muito."],
    ["o sucesso", "el éxito (¡no «el suceso»!)", "O livro fez sucesso no Brasil inteiro."],
    ["a escolha", "la elección", "Se tivesse feito outra escolha, hoje moraria em Lisboa."],
    ["o orgulho", "el orgullo", "Tenho orgulho da minha história."],
    ["de repente", "de repente; también «quizás, capaz que»", "De repente a gente se encontra no bloco."],
    ["deixar pra lá", "dejar pasar, no darle importancia", "Esquece isso, deixa pra lá."],
    ["tomar jeito", "sentar cabeza", "Quando ele tiver tomado jeito, a gente conversa."],
    ["o reencontro", "el reencuentro", "O reencontro da turma foi num boteco da Lapa."],
    ["recomeçar", "empezar de nuevo", "Aos quarenta, ela recomeçou a vida em Recife."],
],

31: [  # Prensa, entrevistas, chismes
    ["a fofoca", "el chisme", "A vizinha disse que tinha uma fofoca sobre o síndico."],
    ["o fofoqueiro", "el chismoso", "Ele é tão fofoqueiro que contou para o prédio inteiro."],
    ["a manchete", "el titular", "A manchete dizia que o metrô ia fechar."],
    ["a matéria", "la nota periodística; también «la materia»", "Li uma matéria sobre a história da Lapa."],
    ["o boato", "el rumor", "Espalharam o boato de que a praia estava fechada."],
    ["o babado", "el chisme jugoso (coloquial)", "Menina, tenho um babado pra te contar!"],
    ["o furo", "la primicia; también «el agujero»", "O jornal deu o furo antes de todo mundo."],
    ["a pauta", "el temario, la agenda de temas", "O repórter perguntou se o assunto estava na pauta."],
    ["a imprensa", "la prensa", "Durante a ditadura, a imprensa sofreu censura."],
    ["o noticiário", "el noticiero", "O noticiário informou que haveria chuva forte."],
    ["divulgar", "difundir, dar a conocer", "O governo divulgou que os números tinham melhorado."],
    ["flagrar", "pescar, sorprender (in fraganti)", "O fotógrafo flagrou o cantor no calçadão."],
    ["o âncora", "el conductor del noticiero", "O âncora anunciou que a entrevista seria no dia seguinte."],
    ["a cobertura", "la cobertura (periodística); también «el penthouse»", "A cobertura do carnaval começou cedo."],
    ["a coletiva", "la conferencia de prensa", "Na coletiva, o técnico afirmou que ia continuar."],
],

32: [  # Carteles, anuncios, reglas
    ["a placa", "el cartel, la señal; también «la patente»", "A placa dizia: aluga-se."],
    ["o cartaz", "el afiche", "Colaram cartazes do bloco por toda a Lapa."],
    ["puxe", "tire (en las puertas)", "Na porta está escrito «puxe», não «empurre»."],
    ["empurre", "empuje (en las puertas)", "Empurre a porta com força."],
    ["o pedestre", "el peatón", "O sinal abre para os pedestres a cada dois minutos."],
    ["a faixa", "la senda peatonal; el carril; la franja", "Atravesse na faixa."],
    ["o degrau", "el escalón", "Cuidado com o degrau!"],
    ["achados e perdidos", "objetos perdidos", "Deixaram meu guarda-chuva nos achados e perdidos."],
    ["a liquidação", "la liquidación, las rebajas", "Tem liquidação de verão no shopping."],
    ["o expediente", "el horario de atención", "O expediente vai das nove às cinco."],
    ["a senha", "el número (de turno); también «la contraseña»", "Pegue uma senha e aguarde."],
    ["o guichê", "la ventanilla", "Dirija-se ao guichê número três."],
    ["à vista", "al contado", "Dão desconto para pagamento à vista."],
    ["vedado", "prohibido (formal)", "É vedada a entrada de animais."],
    ["a entrada franca", "la entrada libre y gratuita", "No domingo o museu tem entrada franca."],
],

33: [  # Literatura, prensa escrita
    ["o sebo", "la librería de usados", "Achei um Machado de Assis antigo num sebo do centro."],
    ["o romance", "la novela (¡no «el romance»!)", "«Dom Casmurro» é um romance de Machado de Assis."],
    ["a novela", "la telenovela", "A novela das nove parou o país."],
    ["o conto", "el cuento", "Clarice Lispector escreveu contos inesquecíveis."],
    ["a crônica", "la crónica (texto breve del diario, género brasileño)", "Rubem Braga escrevia crônicas sobre o Rio."],
    ["o / a personagem", "el personaje", "Capitu é a personagem mais discutida da literatura brasileira."],
    ["o enredo", "la trama, el argumento", "O enredo de «Vidas Secas» se passa no sertão."],
    ["a capa", "la tapa (de un libro, una revista)", "A capa do livro é linda."],
    ["a orelha", "la solapa; también «la oreja»", "Li a orelha e resolvi comprar o livro."],
    ["folhear", "hojear", "Folheei o jornal no café."],
    ["o trecho", "el fragmento, el pasaje; el tramo", "Leia este trecho de «Os Lusíadas» em voz alta."],
    ["a obra-prima", "la obra maestra", "«Grande Sertão: Veredas» é a obra-prima de Guimarães Rosa."],
    ["o rodapé", "el pie de página; el zócalo", "A nota de rodapé explica a palavra."],
    ["a tiragem", "la tirada (de ejemplares)", "O jornal tinha uma tiragem enorme nos anos 50."],
    ["o cordel", "la literatura de cordel (folletos nordestinos)", "Na feira de São Cristóvão vendem-se cordéis."],
],

34: [  # Debates, medio ambiente, sociedad
    ["o desmatamento", "la deforestación", "O desmatamento da Amazônia é tema de debate no mundo inteiro."],
    ["a queimada", "la quema (de campos o selva)", "As queimadas aumentam na seca."],
    ["o aquecimento", "el calentamiento", "O aquecimento global, contudo, não é só culpa do Brasil."],
    ["a enchente", "la inundación", "Choveu três dias; por isso, houve enchente na cidade."],
    ["a seca", "la sequía", "A seca do sertão aparece em «Vidas Secas», de Graciliano Ramos."],
    ["o esgoto", "las cloacas, las aguas servidas", "Grande parte do esgoto ainda vai para a baía."],
    ["o saneamento", "el saneamiento (agua y cloacas)", "Sem saneamento, não há saúde pública."],
    ["a poluição", "la contaminación", "A poluição da Baía de Guanabara é um problema antigo."],
    ["a comunidade", "la comunidad; en Río, también «la favela»", "A comunidade organizou um mutirão de limpeza."],
    ["a coleta seletiva", "la recolección diferenciada de residuos", "O prédio aderiu à coleta seletiva."],
    ["a mata", "el bosque, la selva", "Resta pouco da Mata Atlântica original."],
    ["o lixão", "el basural a cielo abierto", "O lixão de Gramacho, em Duque de Caxias, fechou em 2012."],
    ["o agrotóxico", "el agroquímico, el pesticida", "O uso de agrotóxicos divide opiniões."],
    ["o canudo", "el sorbete, la pajita", "O Rio proibiu os canudos de plástico em 2018."],
    ["a cidadania", "la ciudadanía", "Votar é um exercício de cidadania, mas não o único."],
],

35: [  # Trámites, trabajo, vínculos
    ["o cartório", "el registro civil / la escribanía", "Casamos no cartório de Botafogo."],
    ["a certidão", "el acta, la partida (de nacimiento, etc.)", "Preciso da certidão de nascimento para o passaporte."],
    ["o carimbo", "el sello", "Sem carimbo, o documento não vale."],
    ["o comprovante", "el comprobante", "Guarde o comprovante de residência."],
    ["o boleto", "la boleta de pago (¡no «el pasaje»!)", "Paguei o boleto do condomínio no app."],
    ["o prazo", "el plazo", "O prazo para a matrícula termina sexta."],
    ["o despachante", "el gestor (de trámites)", "Contratei um despachante para tirar o documento."],
    ["a assinatura", "la firma; también «la suscripción»", "Falta a sua assinatura aqui embaixo."],
    ["a firma", "la empresa (¡no «la firma»!)", "Ele trabalha numa firma de engenharia."],
    ["a procuração", "el poder (notarial)", "Assinei uma procuração para minha mãe."],
    ["o noivo / a noiva", "el prometido / la prometida (¡no «el novio» de salir!)", "A noiva chegou ao cartório atrasada."],
    ["o noivado", "el compromiso (antes de casarse)", "O noivado durou dois anos."],
    ["a aliança", "el anillo de compromiso o de bodas; la alianza", "Ele esqueceu a aliança em casa!"],
    ["a paquera", "el levante, el flirteo", "Ela conheceu o marido numa paquera no Baixo Gávea."],
    ["o cônjuge", "el cónyuge", "O cônjuge também deve assinar."],
],

36: [  # Horarios, direcciones, textos formales
    ["à vontade", "cómodo, a gusto; a discreción", "Fica à vontade, a casa é sua."],
    ["às pressas", "a las apuradas", "Saímos às pressas para pegar a barca."],
    ["à beça", "un montón (coloquial)", "Tinha gente à beça no Aterro."],
    ["à risca", "al pie de la letra", "Segui a receita à risca."],
    ["à prestação", "en cuotas", "Comprei a geladeira à prestação."],
    ["à beira-mar", "a orillas del mar, frente al mar", "Jantamos num quiosque à beira-mar."],
    ["o quarteirão", "la cuadra, la manzana", "A padaria fica a dois quarteirões daqui."],
    ["a rodoviária", "la terminal de ómnibus", "O ônibus para Búzios sai da rodoviária às sete."],
    ["a orla", "la costanera, el borde costero", "Andamos pela orla de Copacabana até o Leme."],
    ["o sinal", "el semáforo; también «la señal»", "Vire à direita no segundo sinal."],
    ["o fuso horário", "el huso horario", "O Rio tem o mesmo fuso horário que Buenos Aires."],
    ["o plantão", "la guardia (de turno)", "A farmácia de plantão fica aberta à noite."],
    ["às cegas", "a ciegas", "Não assine nada às cegas."],
    ["o cruzamento", "el cruce, la intersección", "O acidente foi no cruzamento da Barata Ribeiro."],
    ["a travessa", "el pasaje, la calle corta; también «la fuente (de horno)»", "Moro numa travessa da Rua do Catete."],
],

37: [  # Ciencia, trámites, tecnología
    ["baixar", "descargar; también «bajar»", "Baixe o aplicativo e cadastre a senha."],
    ["a tela", "la pantalla; también «el lienzo»", "A tela do meu celular quebrou."],
    ["o carregador", "el cargador", "Não coube o carregador na mochila."],
    ["a pesquisa", "la investigación; la encuesta; la búsqueda", "A pesquisa da Fiocruz obteve bons resultados."],
    ["o pesquisador", "el investigador", "Os pesquisadores preveem mais calor no Rio."],
    ["a descoberta", "el descubrimiento", "Foi uma descoberta que mudou a medicina."],
    ["a pasta", "la carpeta (¡no «la pasta»!)", "Salve o arquivo nesta pasta."],
    ["a planilha", "la planilla de cálculo", "Mantenho os gastos numa planilha."],
    ["apagar", "borrar; también «apagar la luz»", "Apaguei a mensagem sem querer."],
    ["salvar", "guardar (un archivo); también «salvar»", "Não esqueça de salvar antes de fechar."],
    ["a nuvem", "la nube", "As fotos estão na nuvem."],
    ["a tomada", "el enchufe (de pared)", "Não tem tomada perto da cama."],
    ["travar", "colgarse, trabarse (un dispositivo)", "O computador travou de novo."],
    ["digitar", "tipear, escribir en el teclado", "Digite o código que chegou por SMS."],
    ["a rede", "la red; también «la hamaca»", "Caiu a rede do prédio inteiro."],
],

38: [  # Charlas, redes, series
    ["a galera", "la gente, los chicos, la barra", "A galera tá indo pra praia, cê vem?"],
    ["o cara", "el tipo, el chabón", "Aquele cara é gente boa."],
    ["maneiro", "copado (carioca)", "Que show maneiro!"],
    ["valeu", "gracias; dale", "Valeu pela carona!"],
    ["beleza", "dale, todo bien", "Beleza, a gente se vê às oito."],
    ["o rolê", "la salida, la vuelta (de paseo)", "Bora dar um rolê no Arpoador?"],
    ["zoar", "cargar, burlarse; divertirse", "Para de me zoar!"],
    ["curtir", "disfrutar; dar «me gusta»", "Curti muito o carnaval. E curti sua foto!"],
    ["a bagunça", "el desorden, el lío", "Seu quarto tá uma bagunça."],
    ["a treta", "el bardo, la pelea", "Deu treta no grupo da família."],
    ["bolado", "enojado o preocupado (carioca)", "Ele ficou bolado com a fofoca."],
    ["sacar", "entender, cachar (¡no «sacar»!)", "Saquei! Agora entendi a piada."],
    ["maratonar", "maratonear (series)", "Maratonei a série inteira no fim de semana."],
    ["partiu", "¡vamos!, ¡arrancamos! (coloquial)", "Partiu Maracanã!"],
    ["mó", "re, muy (coloquial carioca)", "Tá mó calor hoje."],
],

39: [],  # CHEFÃO

}
