# -*- coding: utf-8 -*-
"""Palabras de la semana — Estação 3 (semanas 27-39).

15 palabras por semana, 0 en la semana del chefão (39).  Campo léxico de
SAI_FARE; se priorizan falsos amigos y palabras muy usadas en Brasil.
Cada ejemplo usa solo gramática vista hasta esa semana.
"""

VOCAB = {

27: [  # Planes de vida, mudanzas
    ["a mudança", "la mudanza; también «el cambio»", "Quando a mudança chegar, a gente monta os móveis.", "De *mudar*: *mudar de casa* o *mudar-se para* + lugar = mudarse. *Fazer a mudança* = hacer la mudanza."],
    ["o aluguel", "el alquiler", "Se o aluguel subir de novo, vamos para Niterói.", "Plural *aluguéis*. Verbo *alugar*: *aluga-se* = se alquila. *Pagar o aluguel*."],
    ["o fiador", "el garante (de un alquiler)", "Sem fiador, a imobiliária pede um seguro.", "*Ser fiador de alguém* = salir de garante. Las alternativas típicas: *seguro-fiança* o *caução*."],
    ["o condomínio", "las expensas; también «el consorcio, el edificio»", "O condomínio do prédio é caro, mas tem porteiro.", "El edificio y la cuota mensual: *pagar o condomínio* = pagar las expensas. *Condomínio fechado* = barrio cerrado."],
    ["a imobiliária", "la inmobiliaria", "Assim que a imobiliária ligar, eu te aviso.", "De *imóvel* (inmueble). El que vende o alquila es *o corretor de imóveis*."],
    ["a vistoria", "la inspección (del inmueble al entrar o salir)", "Antes de entregar as chaves, a imobiliária faz a vistoria.", "Se hace al entrar y al salir del departamento. Verbo: *vistoriar*."],
    ["o carreto", "el flete (pequeña mudanza)", "Se o carreto chegar cedo, a gente termina hoje.", "Mudanza chica en camioneta: *contratar um carreto*. No confundir con *carreta* (camión con acoplado)."],
    ["o papelão", "el cartón", "Guarda as caixas de papelão para a próxima mudança.", "Aumentativo de *papel*. Coloquial: *fazer um papelão* = hacer un papelón."],
    ["encaixotar", "embalar en cajas", "Quando vocês encaixotarem os livros, escrevam o nome na caixa.", "*En* + *caixote* (cajón). Opuesto: *desencaixotar*. Regular: *encaixotei os livros*."],
    ["o síndico", "el administrador del edificio (vecino elegido)", "O síndico disse que a obra termina em março.", "Vecino elegido en la asamblea para administrar el *condomínio*. Femenino: *a síndica*."],
    ["a quitinete", "el monoambiente", "Enquanto eu estiver sozinho, uma quitinete basta.", "Del inglés *kitchenette*; también se escribe *kitnet*. Femenino: *a quitinete*."],
    ["a aposentadoria", "la jubilación", "Quando eu me aposentar, quero morar perto do mar.", "De *aposentar-se* (jubilarse). El jubilado es *o aposentado*."],
    ["a poupança", "la caja de ahorro; los ahorros", "Se eu juntar dinheiro na poupança, compro um apartamento.", "De *poupar* = ahorrar. *Conta poupança* = caja de ahorro. *Poupar alguém de algo* = ahorrarle algo."],
    ["a caução", "el depósito de garantía", "A caução é de três meses de aluguel.", "Femenino, plural *cauções*. Se devuelve al final del contrato: *três meses de caução*."],
    ["o rumo", "el rumbo", "Depois da faculdade, ele mudou de rumo e foi para Salvador.", "*Mudar de rumo* = cambiar de rumbo; *sem rumo* = sin rumbo. *Rumo a* = con destino a: *rumo ao Rio*."],
],

28: [  # Sueños, decisiones
    ["o sonho", "el sueño (deseo); también «la bola de fraile»", "Meu sonho seria morar em Santa Teresa.", "Sueño como deseo y lo que soñás. Tener sueño es otra palabra: *estou com sono*. Verbo: *sonhar com* = soñar con."],
    ["o azar", "la mala suerte (¡no «el azar»!)", "Que azar! Choveu justo no dia do passeio.", "Falso amigo: mala suerte. *Que azar!* = ¡qué mala pata! El azar (casualidad) es *o acaso*: *por acaso*."],
    ["a sorte", "la suerte", "Se eu tivesse sorte, ganharia na Mega-Sena.", "*Ter sorte* = tener suerte; *boa sorte!* = ¡suerte!; *por sorte* = por suerte. Opuesto: *azar*."],
    ["abrir mão de", "renunciar a", "Se fosse preciso, abriria mão do carro para morar perto da praia.", "Literal «abrir la mano». Pide *de*, que se contrae: *abrir mão do carro*. Se conjuga *abrir*: *abri mão*."],
    ["juntar", "ahorrar (juntar plata); también «juntar»", "Se eu juntasse dinheiro, passaria um ano em Portugal.", "*Juntar dinheiro* = ahorrar. También juntar cosas o gente: *juntar a galera*."],
    ["encarar", "enfrentar", "Ela encarou a mudança com coragem.", "Enfrentar: *encarar a mudança*, *encarar o problema*. Coloquial: *encarar alguém* = mirarlo fijo, desafiante."],
    ["a coragem", "el coraje, la valentía (femenino)", "Se eu tivesse a coragem dela, já estaria longe daqui.", "Femenino, como todas las palabras en *-agem*: *a coragem*. *Criar coragem* = animarse, juntar valor."],
    ["arcar com", "hacerse cargo de (gastos, consecuencias)", "Quem arcaria com as despesas se a gente fosse?", "Siempre con *com*: *arcar com as despesas*, *arcar com as consequências*. Registro formal."],
    ["cogitar", "considerar, pensar en (una posibilidad)", "Nunca cogitei morar fora do Rio.", "Más usado que en español: *nem cogitar* = ni pensarlo. Va sin preposición: *cogitar uma mudança*."],
    ["pra valer", "en serio, de verdad (coloquial)", "Se eu decidisse pra valer, mudaria amanhã.", "Coloquial; *pra* = *para*. Va después del verbo o el sustantivo: *decidir pra valer*, *um namoro pra valer*."],
    ["ousar", "atreverse, osar", "Quem ousaria dizer isso ao presidente?", "Con infinitivo directo: *ousar dizer*. *Ousado* = atrevido; *a ousadia* = el atrevimiento."],
    ["a chácara", "la quinta, la chacra", "Se fosse rico, compraria uma chácara na serra.", "Esdrújula con tilde, del quechua, como «chacra». Suele ser más chica que un *sítio*."],
    ["o intercâmbio", "el intercambio (estudiar o vivir un tiempo afuera)", "Queria que você fizesse um intercâmbio em Lisboa.", "*Fazer (um) intercâmbio* = estudiar o vivir un tiempo afuera. El que lo hace: *intercambista*."],
    ["apostar", "apostar", "Aposto que ele não vem.", "*Aposto que* + indicativo = apuesto a que, sin *a*. *Apostar em alguém* = confiar en alguien."],
    ["prestes a", "a punto de", "Estava prestes a desistir quando recebi a notícia.", "*Estar prestes a* + infinitivo = estar a punto de. Algo formal; en el habla también *a ponto de*."],
],

29: [  # Estudio, trabajo, derechos
    ["o vestibular", "el examen de ingreso a la universidad", "É importante vocês estudarem para o vestibular desde cedo.", "Masculino: *prestar* o *fazer vestibular* = rendir el ingreso. El que se prepara: *vestibulando*."],
    ["a bolsa", "la beca; también «la cartera»", "Ela ganhou uma bolsa para estudar em Coimbra.", "*Bolsa de estudos* = beca; *bolsista* = becario. *A Bolsa* también es la bolsa de valores."],
    ["a matrícula", "la inscripción", "A matrícula abre na segunda: não esqueçam de fazer.", "*Fazer a matrícula* = inscribirse; verbo *matricular-se*. La patente del auto no: eso es *placa*."],
    ["a carga horária", "la carga horaria", "A carga horária do curso é de vinte horas por semana.", "Total de horas de un curso o trabajo: *carga horária de quarenta horas semanais*."],
    ["o bico", "la changa; también «el pico»", "Faço uns bicos de garçom nos fins de semana.", "Coloquial: *fazer bico* = hacer changas. Literal es el pico del pájaro: *calar o bico* = cerrar el pico."],
    ["o piso salarial", "el salario mínimo de una categoría", "Os professores lutam para o piso salarial ser respeitado.", "*Piso* = mínimo; lo opuesto es *teto* (techo, máximo). El mínimo nacional es *o salário mínimo*."],
    ["a rescisão", "la rescisión del contrato; la liquidación final", "Depois da rescisão, ele tem direito a receber o FGTS.", "De *rescindir*: fin del contrato y la liquidación. Ahí se cobra el *FGTS*, el fondo del trabajador."],
    ["a carteira assinada", "el trabajo en blanco", "Com carteira assinada, você tem direito a férias.", "*Trabalhar de carteira assinada* = trabajar en blanco; sin ella, *sem carteira* o *na informalidade*."],
    ["o décimo terceiro", "el aguinaldo", "Vou usar o décimo terceiro para pagar as dívidas.", "*Décimo terceiro salário*: un sueldo extra que se cobra a fin de año. Ordinal compuesto, como en español."],
    ["reprovar", "desaprobar (un examen o a alguien)", "O professor reprovou metade da turma.", "*Reprovar alguém* = desaprobarlo; *ser reprovado* = no aprobar. Aprobar: *passar* o *ser aprovado*."],
    ["o cursinho", "el curso preuniversitario", "Fiz cursinho um ano antes de passar.", "Diminutivo de *curso* que nombra el preuniversitario para el *vestibular*. *Fazer cursinho*."],
    ["o concurso", "el concurso público (examen para cargos del Estado)", "Ele estuda para concurso há dois anos.", "Examen para entrar al Estado: *fazer concurso*, *passar num concurso*. *Concurseiro* = el que vive preparándolos."],
    ["o holerite", "el recibo de sueldo", "Confira o holerite para vocês saberem quanto descontaram.", "Palabra de São Paulo, por la marca Hollerith; en otras regiones, *contracheque*."],
    ["o desemprego", "el desempleo", "O desemprego caiu este ano.", "*Des-* + *emprego* (empleo). El desocupado es *desempregado*."],
    ["a apostila", "el cuadernillo, el apunte", "Trouxe as apostilas para vocês estudarem juntos.", "Material impreso de un curso o colegio. Femenino: *a apostila*, plural *apostilas*."],
],

30: [  # Arrepentimientos, historia personal
    ["o arrependimento", "el arrepentimiento", "Meu único arrependimento é não ter aprendido a nadar.", "De *arrepender-se de*: pronominal y con *de*: *me arrependo de não ter ido*."],
    ["vacilar", "mandarse una macana; fallarle a alguien (coloquial)", "Vacilei: se tivesse ligado, ela não teria ficado chateada.", "Coloquial: *vacilei* = la embarré. *Vacilão* = el que siempre falla. También dudar, como en español."],
    ["a lembrança", "el recuerdo; también «el souvenir»", "Tenho ótimas lembranças da casa da minha avó em Petrópolis.", "De *lembrar*. *Mande lembranças a todos* = mandá saludos a todos. También el souvenir."],
    ["a mágoa", "el resentimiento, la herida", "Não guardo mágoa de ninguém.", "*Guardar mágoa de alguém* = guardarle rencor. Verbo *magoar* = herir emocionalmente: *você me magoou*."],
    ["remoer", "darle vueltas (a algo que duele)", "Não adianta remoer: se tivesse dado certo, você estaria lá.", "*Re* + *moer* (moler): rumiar lo que duele. *Remoer o passado*."],
    ["perder o bonde", "perder el tren (una oportunidad)", "Se tivesse aceitado a proposta, não teria perdido o bonde.", "*Bonde* = tranvía: perder el tranvía es perder la oportunidad. Se conjuga *perder*: *perdi o bonde*."],
    ["amadurecer", "madurar", "Depois da viagem, ela amadureceu muito.", "De *maduro*: vale para fruta y para personas. Grafía: *eu amadureço* (c → ç)."],
    ["o sucesso", "el éxito (¡no «el suceso»!)", "O livro fez sucesso no Brasil inteiro.", "Falso amigo: éxito. *Fazer sucesso* = tener éxito. Un suceso (hecho) es *um acontecimento*."],
    ["a escolha", "la elección", "Se tivesse feito outra escolha, hoje moraria em Lisboa.", "De *escolher* = elegir: *fazer uma escolha*. Las elecciones políticas son *as eleições*."],
    ["o orgulho", "el orgullo", "Tenho orgulho da minha história.", "*Ter orgulho de* = estar orgulloso de: *tenho orgulho de você*. Adjetivo: *orgulhoso*."],
    ["a virada", "el giro, el vuelco", "Aquela viagem foi a grande virada da minha vida.", "De *virar*. *A virada do ano* = Año Nuevo; en deporte, *virada* = remontada."],
    ["deixar pra lá", "dejar pasar, no darle importancia", "Esquece isso, deixa pra lá.", "Fórmula del habla, casi siempre en imperativo: *deixa pra lá* = dejalo, no importa. *Pra* = *para*."],
    ["tomar jeito", "sentar cabeza", "Quando ele tiver tomado jeito, a gente conversa.", "*Jeito* = manera, compostura. En imperativo: *toma jeito!* = ¡sentá cabeza!"],
    ["o reencontro", "el reencuentro", "O reencontro da turma foi num boteco da Lapa.", "*Re-* + *encontro*. Verbo: *reencontrar* = volver a encontrar."],
    ["recomeçar", "empezar de nuevo", "Aos quarenta, ela recomeçou a vida em Recife.", "*Re-* + *começar*. *Recomeçar do zero* = empezar de cero; *o recomeço* = el nuevo comienzo."],
],

31: [  # Prensa, entrevistas, chismes
    ["a fofoca", "el chisme", "A vizinha disse que tinha uma fofoca sobre o síndico.", "Femenino. *Fazer fofoca* = chusmear. No confundir con *fofo* (tierno)."],
    ["o fofoqueiro", "el chismoso", "Ele é tão fofoqueiro que contou para o prédio inteiro.", "Femenino *fofoqueira*; sustantivo y adjetivo: *ele é fofoqueiro*."],
    ["o fuxico", "el chisme (coloquial)", "Parem com o fuxico: ela disse que não tinha nada a ver com isso.", "Coloquial, más del Nordeste y de Minas. Verbo: *fuxicar* = chusmear. La *x* suena «sh»."],
    ["a matéria", "la nota periodística; también «la materia»", "Li uma matéria sobre a história da Lapa.", "En periodismo, la nota: *uma matéria sobre…*. En la escuela, la asignatura: *qual é sua matéria favorita?*"],
    ["espalhar", "desparramar, difundir", "Alguém espalhou que o prédio ia ser vendido.", "*Espalhar a notícia* = difundirla; *espalhar-se* = desparramarse. *Lh* suena parecido a «li»."],
    ["o babado", "el chisme jugoso (coloquial)", "Menina, tenho um babado pra te contar!", "Coloquial: *tenho um babado pra te contar*. Literal: el volado de una prenda."],
    ["o furo", "la primicia; también «el agujero»", "O jornal deu o furo antes de todo mundo.", "*Dar um furo* = sacar la primicia. En el habla, *furar* = faltar a una cita: *ele furou*."],
    ["a pauta", "el temario, la agenda de temas", "O repórter perguntou se o assunto estava na pauta.", "*Estar na pauta* = estar en agenda. También el pentagrama de música."],
    ["a imprensa", "la prensa", "Durante a ditadura, a imprensa sofreu censura.", "De *imprimir*. *Liberdade de imprensa* = libertad de prensa."],
    ["o noticiário", "el noticiero", "O noticiário informou que haveria chuva forte.", "Masculino. En el habla se dice *o jornal*: *assistir ao jornal* = ver el noticiero."],
    ["divulgar", "difundir, dar a conocer", "O governo divulgou que os números tinham melhorado.", "Con objeto directo: *divulgou os números*. El sustantivo: *a divulgação*."],
    ["flagrar", "pescar, sorprender (in fraganti)", "O fotógrafo flagrou o cantor no calçadão.", "De *flagrante*: *em flagrante* = in fraganti. Coloquial: *um flagra* = una pescada."],
    ["o âncora", "el conductor del noticiero", "O âncora anunciou que a entrevista seria no dia seguinte.", "Persona: *o* o *a âncora*, según quien conduzca. *A âncora* también es el ancla del barco."],
    ["a cobertura", "la cobertura (periodística); también «el penthouse»", "A cobertura do carnaval começou cedo.", "Cobertura periodística, y también el departamento del último piso con terraza: *mora numa cobertura*."],
    ["a coletiva", "la conferencia de prensa", "Na coletiva, o técnico afirmou que ia continuar.", "Abreviatura de *entrevista coletiva*. *Dar uma coletiva* = dar una conferencia de prensa."],
],

32: [  # Carteles, anuncios, reglas
    ["a placa", "el cartel, la señal; también «la patente»", "A placa dizia: aluga-se.", "Cartel o señal: *placa de trânsito*. En el auto, la patente: *a placa do carro*."],
    ["o cartaz", "el afiche", "Colaram cartazes do bloco por toda a Lapa.", "Plural *cartazes*. *Estar em cartaz* = estar en cartel (película u obra)."],
    ["puxe", "tire (en las puertas)", "Na porta está escrito «puxe», não «empurre».", "Imperativo formal de *puxar* = tirar hacia vos. Ojo: parece «empuje» y es lo contrario."],
    ["empurre", "empuje (en las puertas)", "Empurre a porta com força.", "Imperativo formal de *empurrar*. Coloquial: *empurrar com a barriga* = patear para adelante."],
    ["o pedestre", "el peatón", "O sinal abre para os pedestres a cada dois minutos.", "*Faixa de pedestres* = senda peatonal. También adjetivo: *rua de pedestres*."],
    ["a faixa", "la senda peatonal; el carril; la franja", "Atravesse na faixa.", "*Faixa de pedestres* = senda peatonal; *faixa da esquerda* = carril izquierdo; *faixa etária* = franja de edad."],
    ["o degrau", "el escalón", "Cuidado com o degrau!", "Plural *degraus*. La escalera es *a escada*; cada escalón, *o degrau*."],
    ["achados e perdidos", "objetos perdidos", "Deixaram meu guarda-chuva nos achados e perdidos.", "*Achado* es participio de *achar* = encontrar. *Achar* también = opinar: *acho que sim*."],
    ["a liquidação", "la liquidación, las rebajas", "Tem liquidação de verão no shopping.", "*Estar em liquidação* = estar rebajado. Sinónimos: *promoção*, *saldão*."],
    ["a catraca", "el molinete", "No ônibus, você paga antes de passar pela catraca.", "El molinete de colectivo, subte o estadio: *passar pela catraca*."],
    ["a lixeira", "el tacho de basura", "Proibido jogar lixo fora da lixeira.", "De *lixo* (basura): *jogar na lixeira*. Sufijo *-eira* = recipiente, como *geladeira*, *cafeteira*."],
    ["o guichê", "la ventanilla", "Dirija-se ao guichê número três.", "Del francés *guichet*. Aguda con *ê*: *o guichê número três*."],
    ["o horário de funcionamento", "el horario de atención", "Horário de funcionamento: de segunda a sexta, das nove às seis.", "Rango horario con contracciones: *das nove às seis* (de + as, a + as). *De segunda a sexta*."],
    ["vedado", "prohibido (formal)", "É vedada a entrada de animais.", "Formal, de carteles y leyes; concuerda: *é vedada a entrada*. En el habla: *proibido*."],
    ["a entrada franca", "la entrada libre y gratuita", "No domingo o museu tem entrada franca.", "*Franco* = libre, gratuito. En el habla: *entrada grátis* o *gratuita*."],
],

33: [  # Literatura, prensa escrita
    ["o sebo", "la librería de usados", "Achei um Machado de Assis antigo num sebo do centro.", "Literalmente «sebo», grasa. *Comprar livro no sebo* = en una librería de usados."],
    ["o romance", "la novela (¡no «el romance»!)", "«Dom Casmurro» é um romance de Machado de Assis.", "Falso amigo: novela literaria. La relación amorosa también es *romance*. *Romancista* = novelista."],
    ["a novela", "la telenovela", "A novela das nove parou o país.", "Falso amigo: telenovela. *A novela das nove* = la del horario central. La novela literaria es *romance*."],
    ["o conto", "el cuento", "Clarice Lispector escreveu contos inesquecíveis.", "De *contar*. *Conto de fadas* = cuento de hadas; *contista* = cuentista."],
    ["a crônica", "la crónica (texto breve del diario, género brasileño)", "Rubem Braga escrevia crônicas sobre o Rio.", "Texto breve y personal sobre lo cotidiano, típico de los diarios. Cronistas: Rubem Braga, Fernando Sabino."],
    ["o / a personagem", "el personaje", "Capitu é a personagem mais discutida da literatura brasileira.", "Admite los dos géneros: *o personagem* o *a personagem*. Aunque termine en *-agem*, no es solo femenino."],
    ["o enredo", "la trama, el argumento", "O enredo de «Vidas Secas» se passa no sertão.", "La trama. En el carnaval, el tema del desfile de una escuela: de ahí el *samba-enredo*."],
    ["a capa", "la tapa (de un libro, una revista)", "A capa do livro é linda.", "*Capa dura* = tapa dura; *de capa* = en la tapa, en portada. También capa (prenda)."],
    ["a orelha", "la solapa; también «la oreja»", "Li a orelha e resolvi comprar o livro.", "Solapa del libro y oreja. *Estar de orelha em pé* = estar alerta, con la oreja parada."],
    ["folhear", "hojear", "Folheei o jornal no café.", "De *folha* (hoja). Verbo en *-ear*: *eu folheio*, *ele folheia*."],
    ["o trecho", "el fragmento, el pasaje; el tramo", "Leia este trecho de «Os Lusíadas» em voz alta.", "Fragmento de un texto o tramo de un camino: *um trecho da estrada*."],
    ["a obra-prima", "la obra maestra", "«Grande Sertão: Veredas» é a obra-prima de Guimarães Rosa.", "Con guion; plural *obras-primas*. *Prima* aquí significa «primera»."],
    ["o rodapé", "el pie de página; el zócalo", "A nota de rodapé explica a palavra.", "*Roda* + *pé*: al pie. *Nota de rodapé* = nota al pie. En la pared, el zócalo."],
    ["a tiragem", "la tirada (de ejemplares)", "O jornal tinha uma tiragem enorme nos anos 50.", "De *tirar* (imprimir, sacar copias). Femenino, como todas en *-agem*."],
    ["o cordel", "la literatura de cordel (folletos nordestinos)", "Na feira de São Cristóvão vendem-se cordéis.", "Folletos colgados de un *cordel* (cuerda) en las ferias: de ahí el nombre. Plural *cordéis*."],
],

34: [  # Debates, medio ambiente, sociedad
    ["o desmatamento", "la deforestación", "O desmatamento da Amazônia é tema de debate no mundo inteiro.", "De *mata* (selva): *desmatar* = talar. Masculino, como todas en *-mento*."],
    ["a queimada", "la quema (de campos o selva)", "As queimadas aumentam na seca.", "Participio femenino de *queimar* (quemar) usado como sustantivo. En plural, las de la temporada seca."],
    ["o aquecimento", "el calentamiento", "O aquecimento global, contudo, não é só culpa do Brasil.", "De *aquecer* = calentar. En deporte, *o aquecimento* = la entrada en calor."],
    ["o temporal", "la tormenta, el temporal fuerte", "Houve um temporal no Rio; mesmo assim, o metrô funcionou.", "Masculino. *Caiu um temporal* = se largó una tormenta."],
    ["a seca", "la sequía", "A seca do sertão aparece em «Vidas Secas», de Graciliano Ramos.", "El adjetivo *seco* hecho sustantivo. *O sertão* nordestino es la región de la seca."],
    ["o esgoto", "las cloacas, las aguas servidas", "Grande parte do esgoto ainda vai para a baía.", "Masculino. *Rede de esgoto* = red cloacal. Relacionado: *esgotar* = agotar: *os ingressos esgotaram*."],
    ["o saneamento", "el saneamiento (agua y cloacas)", "Sem saneamento, não há saúde pública.", "*Saneamento básico* = agua potable, cloacas y recolección de basura. De *sanear*."],
    ["a poluição", "la contaminación", "A poluição da Baía de Guanabara é um problema antigo.", "Verbo *poluir* = contaminar; *poluído* = contaminado. *Contaminar* se usa más para enfermedades y sustancias."],
    ["a comunidade", "la comunidad; en Río, también «la favela»", "A comunidade organizou um mutirão de limpeza.", "En Río *comunidade* es la forma respetuosa de decir favela. Plural *comunidades*."],
    ["a coleta seletiva", "la recolección diferenciada de residuos", "O prédio aderiu à coleta seletiva.", "*Coleta*, de *coletar* = recolectar. El reciclaje es *a reciclagem*."],
    ["a mata", "el bosque, la selva", "Resta pouco da Mata Atlântica original.", "*Mata Atlântica* = selva atlántica. Ojo: *mata* también es del verbo *matar*."],
    ["o lixão", "el basural a cielo abierto", "O lixão de Gramacho, em Duque de Caxias, fechou em 2012.", "Aumentativo de *lixo*, masculino. El relleno sanitario es *aterro sanitário*."],
    ["o agrotóxico", "el agroquímico, el pesticida", "O uso de agrotóxicos divide opiniões.", "Término brasileño con tono crítico; la industria dice *defensivo agrícola*."],
    ["o canudo", "el sorbete, la pajita", "O Rio proibiu os canudos de plástico em 2018.", "Sorbete, y también el diploma enrollado. Diminutivo frecuente: *canudinho*."],
    ["a cidadania", "la ciudadanía", "Votar é um exercício de cidadania, mas não o único.", "De *cidadão* (ciudadano), plural *cidadãos*. *Exercer a cidadania*."],
],

35: [  # Trámites, trabajo, vínculos
    ["a papelada", "el papelerío, los trámites", "A papelada do casamento levou dois meses.", "*Papel* + *-ada* (colectivo). *Resolver a papelada* = hacer los trámites."],
    ["a certidão", "el acta, la partida (de nacimiento, etc.)", "Preciso da certidão de nascimento para tirar o passaporte.", "Plural *certidões*. *Certidão de nascimento*, *de casamento*, *de óbito*."],
    ["a carteira de motorista", "el registro de conducir", "Traga a carteira de motorista e um comprovante de residência.", "Oficialmente *CNH*; en el habla, *carteira*. *Tirar a carteira* = sacar el registro."],
    ["o comprovante", "el comprobante", "Guarde o comprovante de residência.", "De *comprovar* = comprobar. *Comprovante de residência* = constancia de domicilio."],
    ["o protocolo", "el número de trámite o de reclamo", "Anote o número do protocolo para acompanhar o pedido.", "Número de trámite o reclamo: *anote o protocolo*. También protocolo (ceremonial)."],
    ["autenticar", "legalizar, certificar (una copia o firma)", "Você precisa autenticar a cópia do diploma.", "Se hace en el *cartório*: *cópia autenticada* = copia certificada."],
    ["o plano de saúde", "la prepaga, la obra social", "O contrato inclui plano de saúde para o cônjuge.", "Seguro médico privado, aparte del *SUS* público. *Ter plano de saúde*."],
    ["a taxa", "la tasa, el arancel", "Para tirar a segunda via, paga-se uma taxa.", "*Taxa de juros* = tasa de interés; *pagar uma taxa* = pagar un arancel. La *x* suena «sh»."],
    ["a firma", "la empresa (¡no «la firma»!)", "Ele trabalha numa firma de engenharia.", "Falso amigo: empresa. Firmar es *assinar*; la firma, *assinatura*. Solo en *reconhecer firma* (certificarla) *firma* es la firma."],
    ["a procuração", "el poder (notarial)", "Assinei uma procuração para minha mãe.", "*Dar uma procuração a alguém* = otorgarle un poder. El apoderado: *procurador*."],
    ["a união estável", "la unión convivencial (reconocida por la ley)", "Eles registraram a união estável antes de casar.", "*Estável* = estable. Se registra en el *cartório* y da derechos parecidos al casamiento."],
    ["o noivado", "el compromiso (antes de casarse)", "O noivado durou dois anos.", "De *noivo* (prometido): *ficar noivo* = comprometerse. Falso amigo: *noivo* no es novio."],
    ["a aliança", "el anillo de compromiso o de bodas; la alianza", "Ele esqueceu a aliança em casa!", "Anillo de compromiso o de bodas, y alianza política. En Brasil se lleva en la mano derecha durante el *noivado*."],
    ["a paquera", "el levante, el flirteo", "Ela conheceu o marido numa paquera no Baixo Gávea.", "Coloquial. Verbo *paquerar* = coquetear. También la persona: *minha paquera*."],
    ["o cônjuge", "el cónyuge", "O cônjuge também deve assinar.", "Masculino aunque sea mujer: *o cônjuge*. Palabra de trámites; en el habla, *marido* o *mulher*."],
],

36: [  # Horarios, direcciones, textos formales
    ["à vontade", "cómodo, a gusto; a discreción", "Fica à vontade, a casa é sua.", "Con *à* (a + a). *Fique à vontade* = ponete cómodo. Sola, *vontade* = ganas: *ter vontade de*."],
    ["às pressas", "a las apuradas", "Saímos às pressas para pegar a barca.", "Plural con crasis: *às* (a + as). *Pressa* = prisa: *estou com pressa* = estoy apurado."],
    ["às avessas", "al revés", "No carnaval, o mundo fica às avessas.", "Plural con crasis. *Avesso* = revés: *a camisa do avesso* = la camisa al revés."],
    ["à risca", "al pie de la letra", "Segui a receita à risca.", "*Risca* = raya. Casi siempre con *seguir*: *seguir à risca*."],
    ["à queima-roupa", "a quemarropa", "A jornalista fez a pergunta à queima-roupa.", "Crasis porque es locución femenina: *à queima-roupa*. *Queimar* + *roupa*."],
    ["à beira-mar", "a orillas del mar, frente al mar", "Jantamos num quiosque à beira-mar.", "*Beira* = orilla, borde: *à beira do rio*, *à beira da estrada*. Locución femenina con crasis."],
    ["o quarteirão", "la cuadra, la manzana", "A padaria fica a dois quarteirões daqui.", "Distancia con *a*, sin tilde: *a dois quarteirões daqui* = a dos cuadras. Plural *quarteirões*."],
    ["o retorno", "la vuelta en U (en la ruta); también «el regreso»", "Perdi a saída e tive que fazer o retorno.", "*Fazer o retorno* = pegar la vuelta. También respuesta: *dar retorno* = responder, devolver el llamado."],
    ["a ladeira", "la cuesta, la calle en subida", "Subimos a ladeira até Santa Teresa às pressas.", "Calle en subida: *subir* o *descer a ladeira*. Salvador y Olinda son famosas por sus *ladeiras*."],
    ["a contramão", "la contramano", "O táxi entrou na contramão na Barata Ribeiro.", "*Na contramão* = de contramano. Figurado: *na contramão da história*."],
    ["a baldeação", "el transbordo, la combinación (en el transporte)", "Para ir à Tijuca, faça baldeação na estação Estácio.", "*Fazer baldeação* = combinar de línea o de transporte. Plural *baldeações*."],
    ["o horário de pico", "la hora pico", "No horário de pico, o metrô vai lotado até a Central.", "*Pico* = punta. En São Paulo también se oye *hora do rush*."],
    ["às cegas", "a ciegas", "Não assine nada às cegas.", "Plural con crasis: *às cegas*. *Cego* = ciego."],
    ["o cruzamento", "el cruce, la intersección", "O acidente foi no cruzamento da Barata Ribeiro.", "De *cruzar*. Las calles se unen con *com*: *no cruzamento da Barata Ribeiro com a Siqueira Campos*."],
    ["a travessa", "el pasaje, la calle corta; también «la fuente (de horno)»", "Moro numa travessa da Rua do Catete.", "De *atravessar*: calle corta que une dos. En la cocina, la fuente: *uma travessa de lasanha*."],
],

37: [  # Ciencia, trámites, tecnología
    ["baixar", "descargar; también «bajar»", "Baixe o aplicativo e cadastre a senha.", "*Baixar um app* = descargar. También bajar: *baixar o preço*, *baixar o volume*."],
    ["a tela", "la pantalla; también «el lienzo»", "A tela do meu celular quebrou.", "Pantalla y lienzo. *Tela sensível ao toque* = pantalla táctil; *print da tela* = captura."],
    ["o carregador", "el cargador", "Não coube o carregador na mochila.", "De *carregar* = cargar. *Carregar o celular*; si se agota: *a bateria acabou*."],
    ["a pesquisa", "la investigación; la encuesta; la búsqueda", "A pesquisa da Fiocruz obteve bons resultados.", "Investigación, encuesta y búsqueda web: *fazer uma pesquisa*. Verbo: *pesquisar*."],
    ["o pesquisador", "el investigador", "Os pesquisadores preveem mais calor no Rio.", "Femenino *pesquisadora*. El investigador policial es *detetive* o *investigador*."],
    ["a descoberta", "el descubrimiento", "Foi uma descoberta que mudou a medicina.", "Participio de *descobrir* hecho sustantivo. Para 1500 se dice *o descobrimento do Brasil*."],
    ["a pasta", "la carpeta (¡no «la pasta»!)", "Salve o arquivo nesta pasta.", "Falso amigo: carpeta (física o de la compu). La pasta de comer es *massa*; *pasta de dente* = dentífrico."],
    ["a planilha", "la planilla de cálculo", "Mantenho os gastos numa planilha.", "Hoja de cálculo: *fazer uma planilha*. *Nh* = ñ."],
    ["apagar", "borrar; también «apagar la luz»", "Apaguei a mensagem sem querer.", "Borrar y apagar: *apagar a mensagem*, *apagar a luz*. Coloquial: *apaguei* = me dormí de golpe."],
    ["salvar", "guardar (un archivo); también «salvar»", "Não esqueça de salvar antes de fechar.", "*Salvar o arquivo* = guardarlo. *Guardar* se usa para objetos: *guardar as chaves*."],
    ["a nuvem", "la nube", "As fotos estão na nuvem.", "Femenino; plural *nuvens* (-m → -ns). *Estar nas nuvens* = estar en las nubes."],
    ["o cadastro", "el registro (de usuario), el alta", "Faça o cadastro no site e obtenha a senha.", "*Fazer o cadastro* = registrarse; verbo *cadastrar-se*. También padrón, base de datos."],
    ["travar", "colgarse, trabarse (un dispositivo)", "O computador travou de novo.", "Colgarse: *o celular travou*. También trabar: *travar a porta*. *Destravar* = desbloquear."],
    ["digitar", "tipear, escribir en el teclado", "Digite o código que chegou por SMS.", "De *dígito* (dedo). *Digite a senha* = ingrese la contraseña."],
    ["a rede", "la red; también «la hamaca»", "Caiu a rede do prédio inteiro.", "Red de pesca, de internet o social, y hamaca: *deitar na rede*. *Redes sociais*."],
],

38: [  # Charlas, redes, series
    ["a galera", "la gente, los chicos, la barra", "A galera tá indo pra praia, cê vem?", "Coloquial y femenino, con verbo en singular: *a galera tá indo*. Saludo grupal: *E aí, galera!*"],
    ["a parada", "la cosa, el asunto (carioca); también «la parada»", "Que parada é essa que cê tá falando?", "Carioca: *essa parada* = esa cosa, eso. Sirve para cualquier cosa sin nombre, como «el tema»."],
    ["maneiro", "copado (carioca)", "Que show maneiro!", "Carioca; concuerda: *show maneiro*, *festa maneira*. En otras regiones: *legal*."],
    ["falou", "chau; dale (al despedirse, coloquial)", "Falou, galera, até amanhã!", "Perfeito de *falar* congelado como despedida o «dale». Combo: *Falou, valeu!*"],
    ["caraca", "¡uh!, ¡guau! (carioca)", "Caraca, que golaço!", "Carioca, eufemismo de una palabrota: sorpresa o admiración. Como *nossa!*, pero más juvenil."],
    ["a resenha", "la juntada, la charla entre amigos (¡no «la reseña»!)", "Depois do jogo teve resenha lá em casa.", "En registro formal sí es reseña; en el habla, la charla o juntada después del partido."],
    ["zoar", "cargar, burlarse; divertirse", "Para de me zoar!", "*Zoar alguém* = cargarlo; *zoar* solo = joder, divertirse. Presente: *eu zoo*, *ele zoa*."],
    ["o zap", "el WhatsApp (coloquial)", "Me manda o endereço no zap.", "De *WhatsApp*; también *zap zap*. *Me manda no zap* = mandámelo por WhatsApp."],
    ["a zoeira", "la joda, el cachengue (coloquial)", "A zoeira no grupo da turma não para.", "De *zoar*. Frase hecha de internet: *a zoeira não tem limites*."],
    ["a treta", "el bardo, la pelea", "Deu treta no grupo da família.", "Coloquial: *deu treta* = se armó lío. Significado viejo: artimaña, trampa."],
    ["bolado", "enojado o preocupado (carioca)", "Ele ficou bolado com a fofoca.", "Carioca: *ficar bolado* = quedar enojado, preocupado o impactado. Concuerda: *bolada*."],
    ["sacar", "entender, cachar (¡no «sacar»!)", "Saquei! Agora entendi a piada.", "Coloquial: *saquei!* = ¡caché!, entendí. Sacar (quitar) es *tirar*; *sacar dinheiro* sí es retirar plata."],
    ["maratonar", "maratonear (series)", "Maratonei a série inteira no fim de semana.", "Con objeto directo: *maratonar uma série*. Viene de *maratona*."],
    ["partiu", "¡vamos!, ¡arrancamos! (coloquial)", "Partiu Maracanã!", "Perfeito de *partir* + destino sin preposición: *partiu praia!* Como pregunta: *partiu?* = ¿vamos?"],
    ["mó", "re, muy (coloquial carioca)", "Tá mó calor hoje.", "Coloquial carioca, de *maior*: *mó calor* = re calor. Solo en registro muy informal."],
],

39: [],  # CHEFÃO

}
