# -*- coding: utf-8 -*-
"""Palabras de la semana — Estação 4 (semanas 40-52).

15 palabras por semana, 0 en la semana del examen final (52).  Campo léxico
de SAI_FARE; se priorizan falsos amigos, registro formal y palabras muy
usadas en Brasil, sin repetir las de las estaciones 1-3.  Los ejemplos
mezclan el Rio cotidiano con historia, literatura y sociedad de Brasil y
Portugal, y usan solo gramática vista hasta esa semana.
"""

VOCAB = {

40: [  # Informes, textos académicos
    ["o relatório", "el informe", "O relatório do IBGE mostra que a população do Rio envelheceu."],
    ["o levantamento", "el relevamiento, el estudio de datos", "Um levantamento recente analisou os quilombos reconhecidos no estado do Rio."],
    ["a queda", "la caída, la baja", "Houve uma queda no número de turistas no inverno."],
    ["a alta", "la suba (de precios, de casos)", "A alta do aluguel em Botafogo preocupa os moradores."],
    ["apurar", "averiguar, investigar (no «apurarse»)", "A comissão vai apurar as causas do acidente no metrô."],
    ["a ressalva", "la salvedad, la reserva", "O parecer aprova o projeto, com uma ressalva sobre o custo."],
    ["a lacuna", "el vacío, la laguna (de información)", "O estudo aponta uma lacuna nas pesquisas sobre Palmares."],
    ["o empecilho", "el obstáculo, el impedimento", "A falta de verba é o principal empecilho para a obra."],
    ["abrangente", "amplio, abarcativo", "A Constituição de 1988 é um texto abrangente, com mais de duzentos artigos."],
    ["alavancar", "impulsar, apalancar", "O turismo pode alavancar a economia de Paraty."],
    ["aferir", "medir, evaluar", "É difícil aferir o impacto real do programa."],
    ["embasar", "fundamentar", "A autora embasa a tese em documentos do Arquivo Nacional."],
    ["acarretar", "acarrear, ocasionar", "O atraso da obra acarretou custos extras."],
    ["o patamar", "el nivel, el escalón", "O desemprego caiu para o menor patamar em dez anos."],
    ["cerca de", "alrededor de, unos (no «cerca de» lugar)", "Cerca de quatro milhões de africanos escravizados chegaram ao Brasil."],
],

41: [  # Machado de Assis, Clarice Lispector
    ["o desfecho", "el desenlace", "O desfecho de Dom Casmurro deixa a dúvida sem resposta."],
    ["outrora", "antaño, en otro tiempo", "A Lapa, outrora bairro boêmio, voltou a ter samba."],
    ["sequer", "siquiera, ni siquiera", "Ela saiu sem sequer olhar para trás."],
    ["mal", "apenas, no bien («mal chegou» = apenas llegó)", "Mal chegara a Lisboa, o poeta foi ao Chiado ver a estátua de Pessoa."],
    ["fitar", "mirar fijamente", "A personagem fitava o espelho sem se reconhecer."],
    ["o vulto", "el bulto, la silueta; también «figura importante»", "Um vulto passou pela janela do casarão."],
    ["cochilar", "dormitar, echarse una siestita", "O velho cochilava na varanda depois do almoço."],
    ["espreitar", "acechar, espiar", "Da janela, a vizinha espreitava quem entrava."],
    ["amiúde", "a menudo (literario)", "Brás Cubas conversa amiúde com o leitor."],
    ["porventura", "acaso, por casualidad", "Se porventura o senhor passar por Lisboa, visite o Chiado."],
    ["o lampejo", "el destello, el chispazo", "Teve um lampejo de esperança quando viu a carta."],
    ["ermo", "desierto, solitario (lugar)", "O sertão de Graciliano é um lugar ermo e seco."],
    ["debruçar-se", "asomarse, inclinarse (y dedicarse a un tema)", "Ela se debruçou na janela para ver o bonde passar."],
    ["o arrepio", "el escalofrío", "Senti um arrepio ao ler o último capítulo."],
    ["o soluço", "el sollozo; también «el hipo»", "Entre soluços, a moça contou o que acontecera."],
],

42: [  # Crónica, noticias
    ["desabar", "derrumbarse; también «largarse a llover»", "Um prédio antigo desabou no Centro; ninguém se feriu."],
    ["o deslizamento", "el desprendimiento, el alud de tierra", "Depois das chuvas, houve deslizamentos em Petrópolis."],
    ["apreender", "incautar, secuestrar (no «aprender»)", "A polícia apreendeu mercadorias falsificadas no camelódromo."],
    ["a estreia", "el estreno", "A estreia do filme lotou o cinema de Botafogo."],
    ["o engavetamento", "el choque en cadena", "Um engavetamento fechou a Ponte Rio-Niterói."],
    ["o vazamento", "la fuga, la filtración", "O vazamento de óleo chegou às praias do Nordeste."],
    ["o rombo", "el agujero (financiero), el desfalco", "Descoberto o rombo, o diretor pediu demissão."],
    ["o apagão", "el apagón", "Durante o apagão, os bares da Lapa acenderam velas."],
    ["a pane", "la falla, la avería", "Uma pane elétrica parou o VLT por uma hora."],
    ["interditar", "cortar, clausurar (calle, local)", "A prefeitura interditou a ciclovia depois da ressaca."],
    ["a ressaca", "la resaca; también «el mar de fondo»", "A ressaca derrubou parte da ciclovia na Avenida Niemeyer."],
    ["o arrastão", "el robo masivo en banda (en la playa)", "O arrastão em Ipanema virou manchete no dia seguinte."],
    ["o alagamento", "el anegamiento, la calle inundada", "Com o alagamento, o trânsito parou na Praça da Bandeira."],
    ["o saque", "el saqueo; también «la extracción de dinero»", "Fiz um saque no caixa eletrônico antes de ir à feira."],
    ["a estiagem", "la sequía, la temporada sin lluvia", "A estiagem no sertão inspirou Vidas Secas."],
],

43: [  # Trabajo, universidad, instituciones
    ["prezado", "estimado (en cartas)", "Prezado Senhor Diretor, venho por meio desta solicitar uma declaração."],
    ["atenciosamente", "atentamente (cierre formal)", "Atenciosamente, Sofía Méndez."],
    ["encaminhar", "derivar, reenviar", "Vou encaminhar seu pedido ao setor de matrículas."],
    ["o aguardo", "la espera («fico no aguardo»)", "Fico no aguardo de sua resposta."],
    ["o requerimento", "la solicitud formal por escrito", "O requerimento deve ser entregue na secretaria da UFRJ."],
    ["o ofício", "la nota oficial (entre instituciones); también «el oficio»", "A universidade enviou um ofício ao Ministério da Educação."],
    ["o ressarcimento", "el reembolso, el resarcimiento", "Solicito o ressarcimento das despesas da viagem."],
    ["a pendência", "el pendiente, el asunto por resolver", "Não há nenhuma pendência no seu cadastro."],
    ["deferir", "aprobar (un pedido); no «diferir»", "A coordenação deferiu o pedido de prorrogação."],
    ["indeferir", "rechazar (un pedido)", "O pedido foi indeferido por falta de documentos."],
    ["a prorrogação", "la prórroga", "Gostaria de solicitar a prorrogação do prazo de entrega."],
    ["a segunda via", "el duplicado", "Perdi o diploma e pedi a segunda via."],
    ["o atestado", "el certificado (médico, de conducta)", "Segue em anexo o atestado médico."],
    ["o remetente", "el remitente", "O e-mail voltou: o remetente estava errado."],
    ["rubricar", "firmar con iniciales cada página", "Rubrique todas as páginas do contrato, por favor."],
],

44: [  # Formación de palabras, diminutivos
    ["o cafezinho", "el cafecito (y la invitación a charlar)", "Depois da reunião, rolou um cafezinho na padaria."],
    ["rapidinho", "enseguida, en un segundo", "Espera aí, volto rapidinho."],
    ["o borracheiro", "el gomero", "O pneu furou e o borracheiro da esquina consertou."],
    ["o jornaleiro", "el canillita, el diariero", "O jornaleiro de Copacabana guarda o jornal para mim."],
    ["a mangueira", "el árbol de mango; también «la manguera»", "A escola de samba Mangueira tem o nome do morro."],
    ["o coqueiro", "el cocotero", "Deitei na rede à sombra do coqueiro."],
    ["o golaço", "el golazo", "Que golaço no Maracanã ontem!"],
    ["o casarão", "la casona", "O casarão de Santa Teresa virou centro cultural."],
    ["a chatice", "la pesadez, el embole", "Que chatice esperar três horas no consulado!"],
    ["a garotada", "los chicos, la muchachada", "A garotada joga futevôlei no fim da tarde."],
    ["a olhada", "el vistazo («dar uma olhada»)", "Dá uma olhada nesse livro sobre Oswald de Andrade."],
    ["a sujeira", "la suciedad, la mugre", "Depois do bloco, a sujeira na rua era enorme."],
    ["a bobeira", "la tontería («dar bobeira» = descuidarse)", "Não dá bobeira com o celular na praia."],
    ["o panelaço", "el cacerolazo", "Houve panelaço em vários bairros do Rio."],
    ["o portão", "el portón (no «puerta grande»)", "O porteiro abriu o portão do prédio."],
],

45: [  # Léxico traicionero
    ["o polvo", "el pulpo (no «polvo»)", "Em Portugal, o polvo à lagareiro é um prato típico."],
    ["contestar", "cuestionar, impugnar (no «responder»)", "Os historiadores contestam a imagem de uma escravidão branda."],
    ["reparar", "notar, fijarse («reparar em»); también «arreglar»", "Você reparou no azulejo português da fachada?"],
    ["latir", "ladrar (no «latir» del corazón)", "O cachorro do vizinho latiu a noite inteira."],
    ["largo", "ancho (no «largo»); también «plaza» (o Largo do Machado)", "A Avenida Presidente Vargas é larga e comprida."],
    ["a taça", "la copa", "Brindamos com uma taça de vinho do Porto."],
    ["o presunto", "el jamón (no «presunto»)", "Um misto-quente é pão com presunto e queijo."],
    ["a salsa", "el perejil (no «salsa»)", "Coloca um pouco de salsa no peixe."],
    ["a cena", "la escena (no «cena» = jantar)", "A cena final de Central do Brasil é inesquecível."],
    ["ruivo", "pelirrojo", "Meu sobrinho é ruivo e sardento."],
    ["a propina", "la coima, el soborno (no «propina» = gorjeta)", "O fiscal foi preso por cobrar propina."],
    ["o cachorro", "el perro (no «cachorro» = filhote)", "Passeio com o cachorro no Aterro todo dia."],
    ["o vaso", "la maceta; el inodoro (no «vaso» = copo)", "Comprei um vaso de barro para a samambaia."],
    ["pelado", "desnudo (no «pelado» = careca)", "Na praia de Abricó, no Rio, pode ficar pelado."],
    ["o balcão", "el mostrador, la barra (no «balcón» = varanda)", "Pedimos o pastel no balcão da pastelaria."],
],

46: [  # Regiones de Brasil, Portugal, África
    ["o autocarro", "el colectivo (PT; en Brasil «ônibus»)", "Em Lisboa, apanhei o autocarro para Belém."],
    ["o comboio", "el tren (PT; en Brasil «trem»)", "O comboio de Lisboa para Coimbra leva duas horas."],
    ["o telemóvel", "el celular (PT)", "Em Portugal, o celular se chama telemóvel."],
    ["o pequeno-almoço", "el desayuno (PT; en Brasil «café da manhã»)", "No hotel do Porto, o pequeno-almoço é servido até às dez."],
    ["o miúdo", "el chico, el nene (PT)", "Os miúdos brincavam na praça de Alfama."],
    ["fixe", "copado, genial (PT; en Brasil «legal»)", "Um amigo de Lisboa disse que o show foi muito fixe."],
    ["giro", "lindo, bonito (PT)", "Que vestido tão giro!, disse a portuguesa."],
    ["o sumo", "el jugo (PT; en Brasil «suco»)", "Pedi um sumo de laranja num café do Porto."],
    ["a macaxeira", "la mandioca (Nordeste; «aipim» en Rio)", "Em Recife, comi carne de sol com macaxeira."],
    ["o guri", "el pibe, el nene (Sur de Brasil)", "Em Porto Alegre, o guri torce pelo Grêmio."],
    ["oxente", "¡pero mirá!, ¿qué? (Nordeste)", "Oxente, você não conhece Jorge Amado?"],
    ["uai", "¡ué!, ¿y? (Minas Gerais)", "Uai, cadê o pão de queijo?"],
    ["bué", "mucho, muy (Angola, y hoy Lisboa)", "Em Luanda, dizem que a música é bué boa."],
    ["arretado", "genial; también «enojado» (Nordeste)", "O forró de ontem estava arretado!"],
    ["a casa de banho", "el baño (PT; en Brasil «banheiro»)", "Em Lisboa, perguntei onde era a casa de banho."],
],

47: [  # Debate público
    ["o embate", "el enfrentamiento, el choque", "O embate entre governo e oposição marcou a Constituinte."],
    ["o viés", "el sesgo; también «el bies»", "Toda pesquisa tem algum viés."],
    ["defasado", "desactualizado, atrasado", "O salário dos professores está defasado."],
    ["acirrado", "reñido, encarnizado", "A eleição de 1989 teve um segundo turno acirrado."],
    ["o descaso", "la desidia, el abandono", "O incêndio do Museu Nacional, em 2018, revelou anos de descaso."],
    ["a verba", "los fondos, la partida presupuestaria", "Falta verba para a despoluição da Baía de Guanabara."],
    ["escancarar", "dejar a la vista, abrir de par en par", "A pandemia escancarou a desigualdade nas favelas."],
    ["o ônus", "la carga, el costo", "O ônus da crise não pode cair só sobre os mais pobres."],
    ["o abaixo-assinado", "el petitorio con firmas", "Os moradores fizeram um abaixo-assinado contra o fechamento da escola."],
    ["o vereador", "el concejal", "A vereadora Marielle Franco foi assassinada no Rio em 2018."],
    ["o pleito", "la elección (en la prensa); el litigio", "O pleito de outubro terá urnas eletrônicas, como sempre."],
    ["a bancada", "el bloque (parlamentario)", "A bancada do Rio votou a favor do projeto."],
    ["a contrapartida", "la contraprestación; «em contrapartida» = en cambio", "A empresa recebeu o terreno e, como contrapartida, construiu uma praça."],
    ["enxugar", "secar; también «recortar, achicar (gastos)»", "O governo quer enxugar a máquina pública."],
    ["reivindicar", "reclamar (un derecho)", "Nas Diretas Já, milhões reivindicavam o voto para presidente."],
],

48: [  # Periodismo, divulgación
    ["alegar", "alegar (con matiz de excusa)", "O ministro alegou que não sabia de nada."],
    ["apontar", "señalar, indicar", "O estudo aponta que o nível do mar subiu em Copacabana."],
    ["salientar", "destacar, subrayar", "A autora salienta o papel das mulheres na Abolição."],
    ["o porta-voz", "el vocero", "O porta-voz da prefeitura negou o aumento da tarifa."],
    ["o depoimento", "el testimonio, la declaración", "Os depoimentos da Comissão da Verdade revelaram casos de tortura."],
    ["o desdobramento", "la derivación, la repercusión", "A reportagem teve desdobramentos políticos."],
    ["o jargão", "la jerga (técnica)", "O artigo evita o jargão acadêmico."],
    ["cunhar", "acuñar (una expresión)", "Foi Ribeiro Couto quem cunhou a expressão «homem cordial»; Sérgio Buarque a tornou famosa."],
    ["o lide", "el copete, el primer párrafo de la noticia", "Um bom lide responde: quem, o quê, quando e onde."],
    ["a reportagem", "el reportaje; también «el equipo de periodistas»", "Procurada pela reportagem, a empresa não respondeu."],
    ["ressaltar", "destacar, resaltar", "Os historiadores ressaltam que Zumbi resistiu por anos em Palmares."],
    ["veicular", "difundir, publicar (en un medio)", "A notícia foi veiculada no jornal da noite."],
    ["grifar", "subrayar, resaltar (en un texto)", "Grifei as frases mais importantes de Raízes do Brasil."],
    ["a chamada", "el titular breve, el anuncio; también «la llamada»", "A chamada na capa dizia: «Rio sem água»."],
    ["a fonte", "la fuente (de información); también «fuente de agua»", "O jornalista não revelou a fonte."],
],

49: [  # Registro culto y coloquial
    ["irado", "buenísimo (Rio, coloquial); también «enojado»", "O show do Circo Voador foi irado!"],
    ["sinistro", "impresionante, genial (Rio, coloquial); «siniestro»", "Esse golaço foi sinistro, mermão!"],
    ["sangue bom", "buena gente (coloquial)", "O dono do boteco é sangue bom."],
    ["demorou", "¡dale!, ¡de una! (Rio, coloquial)", "Praia amanhã cedo? — Demorou!"],
    ["suave", "tranqui, todo bien (coloquial)", "Tá tudo suave por aqui."],
    ["coé", "¿qué onda? (saludo carioca)", "Coé, Rafa, tudo certo?"],
    ["o mané", "el gil, el tonto (coloquial)", "Só um mané deixa a mochila sozinha na areia."],
    ["o papo reto", "hablar claro, sin vueltas (coloquial)", "Vou te dar um papo reto: você errou."],
    ["sussa", "tranqui (coloquial, de «sossegado»)", "Pode chegar mais tarde, tá sussa."],
    ["outrossim", "asimismo (muy formal)", "Outrossim, informo que o prazo foi prorrogado."],
    ["porquanto", "puesto que, ya que (formal)", "O pedido foi negado, porquanto faltavam documentos."],
    ["haja vista", "dado que, teniendo en cuenta (formal)", "A obra atrasou, haja vista as chuvas de verão."],
    ["destarte", "de este modo, así (muy formal)", "Destarte, conclui-se que a medida foi eficaz."],
    ["doravante", "de ahora en adelante (formal)", "Doravante, os pedidos serão feitos pelo site."],
    ["conquanto", "aunque (formal, + subjuntivo)", "Conquanto seja longo, o romance de Guimarães Rosa é fascinante."],
],

50: [  # Refranes, expresiones fijas
    ["fazer questão", "insistir, tener empeño", "Faço questão de te levar ao Pão de Açúcar."],
    ["dar certo", "salir bien, funcionar", "Tomara que o plano dê certo."],
    ["levar a sério", "tomar en serio", "Ninguém levou a sério o aviso de ressaca."],
    ["pisar na bola", "meter la pata", "Pisei na bola: esqueci o aniversário dela."],
    ["dar um jeito", "arreglárselas, buscarle la vuelta", "Não tem mesa, mas o garçom vai dar um jeito."],
    ["ficar de boa", "quedarse tranqui", "Domingo vou ficar de boa em casa."],
    ["pagar mico", "hacer el ridículo", "Paguei mico dançando samba no Sambódromo."],
    ["dar um bolo", "dejar plantado", "Ele me deu um bolo e não apareceu no bar."],
    ["cair a ficha", "caer la ficha", "Só depois caiu a ficha: era o Chico Buarque!"],
    ["puxar o saco", "chupar las medias, adular", "Ele vive puxando o saco do chefe."],
    ["segurar vela", "tocar el violín (acompañar a una pareja)", "Não quero segurar vela no cinema com vocês dois."],
    ["chutar o balde", "mandar todo al diablo", "Cansou do escritório e chutou o balde: foi morar em Trancoso."],
    ["tirar onda", "fanfarronear; también «cargar a alguien» (Rio)", "Ele adora tirar onda com o carro novo."],
    ["dar mole", "descuidarse; también «dar pie, mostrar interés» (Rio)", "Não dá mole com a carteira no ônibus."],
    ["encher linguiça", "rellenar, hablar sin decir nada", "O texto tem três páginas, mas metade é encher linguiça."],
],

51: [  # Repaso general
    ["pelo jeito", "por lo visto", "Pelo jeito, vai chover no desfile."],
    ["por acaso", "por casualidad; ¿acaso?", "Você viu, por acaso, minhas chaves?"],
    ["de vez", "definitivamente, para siempre", "Ela se mudou de vez para Lisboa."],
    ["de cara", "de entrada, enseguida", "Gostei de Salvador de cara."],
    ["de quebra", "de yapa, encima", "Fomos a Petrópolis e, de quebra, visitamos o Museu Imperial."],
    ["às escondidas", "a escondidas", "Na ditadura, muita gente lia Paulo Freire às escondidas."],
    ["ao léu", "a la deriva, sin rumbo", "Passei a tarde andando ao léu pelo Centro."],
    ["a torto e a direito", "a diestra y siniestra", "Ele distribui críticas a torto e a direito."],
    ["de mão beijada", "servido en bandeja, gratis", "Ninguém recebe nada de mão beijada."],
    ["de olho", "atento, vigilando («ficar de olho»)", "Fica de olho na bolsa no metrô."],
    ["em cima da hora", "sobre la hora", "Entregou a redação em cima da hora."],
    ["no fim das contas", "al final de cuentas", "No fim das contas, a viagem deu certo."],
    ["nem pensar", "¡ni loco!, ni en sueños", "Pagar cem reais por um chope? Nem pensar!"],
    ["por um triz", "por un pelo", "Pegamos o último barco para Niterói por um triz."],
    ["à mão", "a mano (hecho a mano; al alcance)", "Você tem uma caneta à mão?"],
],

52: [],
}
