# -*- coding: utf-8 -*-
"""Palabras de la semana — Estação 4 (semanas 40-52).

15 palabras por semana, 0 en la semana del examen final (52).  Campo léxico
de SAI_FARE; se priorizan falsos amigos, registro formal y palabras muy
usadas en Brasil, sin repetir las de las estaciones 1-3.  Los ejemplos
mezclan el Rio cotidiano con historia, literatura y sociedad de Brasil y
Portugal, y usan solo gramática vista hasta esa semana.
"""

VOCAB = {

40: [  # Informes, textos académicos
    ["o relatório", "el informe", "O relatório do IBGE mostra que a população do Rio envelheceu.", "De *relatar* = informar, relatar. *Fazer* o *apresentar um relatório*. Masculino."],
    ["o levantamento", "el relevamiento, el estudio de datos", "Um levantamento recente analisou os quilombos reconhecidos no estado do Rio.", "De *levantar* (datos): *fazer um levantamento* = hacer un relevamiento. También levantamiento de pesas."],
    ["a queda", "la caída, la baja", "Houve uma queda no número de turistas no inverno.", "De *cair*: *queda de preços* = baja de precios. *Ter uma queda por alguém* = tener debilidad por alguien."],
    ["a alta", "la suba (de precios, de casos)", "A alta do aluguel em Botafogo preocupa os moradores.", "*Em alta* = en suba, de moda: *a alta do dólar*. En el hospital, *receber alta* = recibir el alta."],
    ["apurar", "averiguar, investigar (no «apurarse»)", "A comissão vai apurar as causas do acidente no metrô.", "Falso amigo: averiguar (*apurar os fatos*) o contar votos (*a apuração*). Apurarse es *apressar-se*."],
    ["a ressalva", "la salvedad, la reserva", "O parecer aprova o projeto, com uma ressalva sobre o custo.", "*Com uma ressalva* = con una salvedad; *fazer uma ressalva*. Verbo: *ressalvar*."],
    ["a lacuna", "el vacío, la laguna (de información)", "O estudo aponta uma lacuna nas pesquisas sobre Palmares.", "Vacío de datos o de una ley: *preencher uma lacuna* = llenar un vacío. La laguna de agua es *lagoa*."],
    ["o empecilho", "el obstáculo, el impedimento", "A falta de verba é o principal empecilho para a obra.", "Masculino: *ser um empecilho para* algo. Sinónimos: *obstáculo*, *entrave*."],
    ["abrangente", "amplio, abarcativo", "A Constituição de 1988 é um texto abrangente, com mais de duzentos artigos.", "De *abranger* = abarcar. Igual en masculino y femenino: *uma lei abrangente*."],
    ["alavancar", "impulsar, apalancar", "O turismo pode alavancar a economia de Paraty.", "De *alavanca* (palanca). Muy de economía y empresas: *alavancar as vendas*."],
    ["aferir", "medir, evaluar", "É difícil aferir o impacto real do programa.", "Formal. Irregular en la primera persona: *eu afiro*, como *ferir → firo*."],
    ["embasar", "fundamentar", "A autora embasa a tese em documentos do Arquivo Nacional.", "*Embasar algo em* = fundamentarlo en. De *base*; sustantivo: *o embasamento*."],
    ["acarretar", "acarrear, ocasionar", "O atraso da obra acarretou custos extras.", "Con objeto directo: *acarretar custos*. Sinónimos: *causar*, *gerar*, *implicar*."],
    ["o patamar", "el nivel, el escalón", "O desemprego caiu para o menor patamar em dez anos.", "Nivel, y también el rellano de la escalera. *No menor patamar* = en el nivel más bajo."],
    ["cerca de", "alrededor de, unos (no «cerca de» lugar)", "Cerca de quatro milhões de africanos escravizados chegaram ao Brasil.", "Ante números = unos, aproximadamente: *cerca de mil pessoas*. «Cerca de» un lugar es *perto de*; *acerca de* = sobre."],
],

41: [  # Machado de Assis, Clarice Lispector
    ["o desfecho", "el desenlace", "O desfecho de Dom Casmurro deixa a dúvida sem resposta.", "De *desfechar*. Literario o de prensa: *um desfecho feliz*. En el habla: *o final*."],
    ["outrora", "antaño, en otro tiempo", "A Lapa, outrora bairro boêmio, voltou a ter samba.", "Literario: antaño. Se usa ante adjetivo o aposición: *outrora rica*, *outrora bairro boêmio*."],
    ["sequer", "siquiera, ni siquiera", "Ela saiu sem sequer olhar para trás.", "Casi siempre en contexto negativo: *nem sequer*, *sem sequer olhar*, *não disse sequer obrigado*."],
    ["mal", "apenas, no bien («mal chegou» = apenas llegó)", "Mal chegara a Lisboa, o poeta foi ao Chiado ver a estátua de Pessoa.", "*Mal* + verbo = apenas, no bien: *mal chegou, saiu*. El *chegara* del ejemplo es el pluscuamperfecto simple, literario."],
    ["fitar", "mirar fijamente", "A personagem fitava o espelho sem se reconhecer.", "Literario, con objeto directo: *fitar o espelho*. En el habla: *olhar fixamente*, *encarar*."],
    ["o vulto", "el bulto, la silueta; también «figura importante»", "Um vulto passou pela janela do casarão.", "Silueta difusa, y también persona ilustre: *um vulto da história*. *Tomar vulto* = cobrar importancia."],
    ["cochilar", "dormitar, echarse una siestita", "O velho cochilava na varanda depois do almoço.", "*Dar um cochilo* = echarse una siestita. Muy usado en el habla, no solo literario."],
    ["espreitar", "acechar, espiar", "Da janela, a vizinha espreitava quem entrava.", "Literario: acechar. *À espreita* = al acecho."],
    ["amiúde", "a menudo (literario)", "Brás Cubas conversa amiúde com o leitor.", "Literario e invariable. En el habla: *muitas vezes*, *com frequência*."],
    ["porventura", "acaso, por casualidad", "Se porventura o senhor passar por Lisboa, visite o Chiado.", "Formal, en condicionales y preguntas: *se porventura…*. En el habla: *por acaso*."],
    ["o lampejo", "el destello, el chispazo", "Teve um lampejo de esperança quando viu a carta.", "De *lampejar* = destellar. *Um lampejo de lucidez* = un chispazo de lucidez."],
    ["ermo", "desierto, solitario (lugar)", "O sertão de Graciliano é um lugar ermo e seco.", "Adjetivo y sustantivo: *um lugar ermo*, *o ermo*. Misma raíz griega que *eremita*."],
    ["debruçar-se", "asomarse, inclinarse (y dedicarse a un tema)", "Ela se debruçou na janela para ver o bonde passar.", "Con *sobre* o *em*: *debruçar-se na janela*. Figurado: *debruçar-se sobre um tema* = dedicarse a estudiarlo."],
    ["o arrepio", "el escalofrío", "Senti um arrepio ao ler o último capítulo.", "Verbo *arrepiar*: *fiquei arrepiado* = se me puso la piel de gallina."],
    ["o soluço", "el sollozo; también «el hipo»", "Entre soluços, a moça contou o que acontecera.", "Sollozo y también hipo: *estou com soluço*. Verbo: *soluçar*."],
],

42: [  # Crónica, noticias
    ["desabar", "derrumbarse; también «largarse a llover»", "Um prédio antigo desabou no Centro; ninguém se feriu.", "Sin *se*: *o prédio desabou*. Figurado: *desabar em lágrimas*; de la lluvia, *o céu desabou*."],
    ["o deslizamento", "el desprendimiento, el alud de tierra", "Depois das chuvas, houve deslizamentos em Petrópolis.", "*Deslizamento de terra*, de *deslizar*. Común en las laderas de Río y de la sierra."],
    ["apreender", "incautar, secuestrar (no «aprender»)", "A polícia apreendeu mercadorias falsificadas no camelódromo.", "Falso amigo casi gemelo: *apreender* = incautar; *aprender* = aprender. Sustantivo: *a apreensão* (también «inquietud»)."],
    ["a estreia", "el estreno", "A estreia do filme lotou o cinema de Botafogo.", "Sin tilde desde 1990 (antes *estréia*). Verbo *estrear* = estrenar: *eu estreio*."],
    ["o engavetamento", "el choque en cadena", "Um engavetamento fechou a Ponte Rio-Niterói.", "De *gaveta* (cajón): autos «encajonados». *Engavetar* también = cajonear un proyecto."],
    ["o vazamento", "la fuga, la filtración", "O vazamento de óleo chegou às praias do Nordeste.", "De *vazar* = perder líquido o filtrarse: *vazamento de dados* = filtración de datos."],
    ["o rombo", "el agujero (financiero), el desfalco", "Descoberto o rombo, o diretor pediu demissão.", "Agujero en las cuentas: *rombo nas contas públicas*. También el rombo de la geometría."],
    ["o apagão", "el apagón", "Durante o apagão, os bares da Lapa acenderam velas.", "Aumentativo en *-ão* de *apagar*, masculino: *o apagão*; plural *apagões*."],
    ["a pane", "la falla, la avería", "Uma pane elétrica parou o VLT por uma hora.", "Femenino, del francés *panne*. *Entrar em pane* = fallar, descomponerse."],
    ["interditar", "cortar, clausurar (calle, local)", "A prefeitura interditou a ciclovia depois da ressaca.", "Formal: *interditar a rua* = cortarla. El sustantivo es *a interdição*."],
    ["a ressaca", "la resaca; también «el mar de fondo»", "A ressaca derrubou parte da ciclovia na Avenida Niemeyer.", "Mar de fondo con olas fuertes, y también resaca del alcohol: *estou de ressaca*."],
    ["o arrastão", "el robo masivo en banda (en la playa)", "O arrastão em Ipanema virou manchete no dia seguinte.", "De *arrastar*: literal, red de arrastre. Aumentativo en *-ão*, masculino."],
    ["o alagamento", "el anegamiento, la calle inundada", "Com o alagamento, o trânsito parou na Praça da Bandeira.", "De *alagar* = inundar: *a rua alagou*. La crecida grande es *a enchente*."],
    ["o saque", "el saqueo; también «la extracción de dinero»", "Fiz um saque no caixa eletrônico antes de ir à feira.", "De *sacar*: *fazer um saque* = retirar plata. En vóley, el saque."],
    ["a estiagem", "la sequía, la temporada sin lluvia", "A estiagem no sertão inspirou Vidas Secas.", "Femenino en *-agem*, más técnico que *seca*. De *estiar* = dejar de llover."],
],

43: [  # Trabajo, universidad, instituciones
    ["prezado", "estimado (en cartas)", "Prezado Senhor Diretor, venho por meio desta solicitar uma declaração.", "Encabezado formal que concuerda: *Prezado Senhor*, *Prezada Senhora*. Más cercano: *Caro* / *Cara*."],
    ["atenciosamente", "atentamente (cierre formal)", "Atenciosamente, Sofía Méndez.", "Cierre estándar de mail formal, seguido del nombre. Entre conocidos: *Abraços* o *Um abraço*."],
    ["encaminhar", "derivar, reenviar", "Vou encaminhar seu pedido ao setor de matrículas.", "*Encaminhar algo a/para alguém*: *encaminhar o pedido ao setor*. En mails, reenviar (forward)."],
    ["o aguardo", "la espera («fico no aguardo»)", "Fico no aguardo de sua resposta.", "Fórmula fija de correo: *fico no aguardo* = quedo a la espera. Verbo: *aguardar* = esperar."],
    ["o requerimento", "la solicitud formal por escrito", "O requerimento deve ser entregue na secretaria da UFRJ.", "De *requerer*, irregular: *eu requeiro*. *Protocolar um requerimento* = presentarlo formalmente."],
    ["o ofício", "la nota oficial (entre instituciones); también «el oficio»", "A universidade enviou um ofício ao Ministério da Educação.", "Comunicado oficial numerado entre instituciones. También oficio, profesión."],
    ["o ressarcimento", "el reembolso, el resarcimiento", "Solicito o ressarcimento das despesas da viagem.", "De *ressarcir* = resarcir, reembolsar. Formal: *solicitar o ressarcimento de*."],
    ["a pendência", "el pendiente, el asunto por resolver", "Não há nenhuma pendência no seu cadastro.", "*Ter pendências* = tener asuntos pendientes. Adjetivo: *estar pendente*."],
    ["deferir", "aprobar (un pedido); no «diferir»", "A coordenação deferiu o pedido de prorrogação.", "Falso amigo: aprobar un pedido. Irregular: *eu defiro*. Diferir (postergar) es *adiar*."],
    ["indeferir", "rechazar (un pedido)", "O pedido foi indeferido por falta de documentos.", "Contrario de *deferir*. Casi siempre en pasiva: *o pedido foi indeferido*."],
    ["a prorrogação", "la prórroga", "Gostaria de solicitar a prorrogação do prazo de entrega.", "De *prorrogar*. En fútbol, *a prorrogação* = el alargue."],
    ["a segunda via", "el duplicado", "Perdi o diploma e pedi a segunda via.", "*Tirar a segunda via* = sacar un duplicado (documento, factura). *Via* = copia."],
    ["o atestado", "el certificado (médico, de conducta)", "Segue em anexo o atestado médico.", "*Atestado médico* = certificado médico. Verbo: *atestar* = certificar."],
    ["o remetente", "el remitente", "O e-mail voltou: o remetente estava errado.", "*Remetente* = quien envía; *destinatário* = quien recibe. De *remeter* = enviar."],
    ["rubricar", "firmar con iniciales cada página", "Rubrique todas as páginas do contrato, por favor.", "De *rubrica*, llana: *ru-BRI-ca*. Se rubrican las páginas y se firma (*assina*) la última."],
],

44: [  # Formación de palabras, diminutivos
    ["o cafezinho", "el cafecito (y la invitación a charlar)", "Depois da reunião, rolou um cafezinho na padaria.", "Diminutivo de *café*: con palabra aguda se usa *-zinho*. *Tomar um cafezinho* = invitación a charlar."],
    ["rapidinho", "enseguida, en un segundo", "Espera aí, volto rapidinho.", "Diminutivo como adverbio: *volto rapidinho*. El diminutivo suaviza pedidos: *um minutinho*."],
    ["o borracheiro", "el gomero", "O pneu furou e o borracheiro da esquina consertou.", "De *borracha* (caucho) + *-eiro* de oficio. El local es *a borracharia*."],
    ["o jornaleiro", "el canillita, el diariero", "O jornaleiro de Copacabana guarda o jornal para mim.", "De *jornal* (diario) + *-eiro*. Vende en *a banca de jornal*."],
    ["a mangueira", "el árbol de mango; también «la manguera»", "A escola de samba Mangueira tem o nome do morro.", "Árbol de mango y manguera. Sufijo *-eira* para árboles: *bananeira*, *laranjeira*, *mangueira*."],
    ["o coqueiro", "el cocotero", "Deitei na rede à sombra do coqueiro.", "*Coco* + *-eiro* (árbol). En la playa se toma *água de coco*."],
    ["o golaço", "el golazo", "Que golaço no Maracanã ontem!", "Aumentativo expresivo en *-aço*: *golaço*, *jogaço* (partidazo)."],
    ["o casarão", "la casona", "O casarão de Santa Teresa virou centro cultural.", "Aumentativo de *casa*, pero masculino, como casi todos en *-ão*: *o casarão*."],
    ["a chatice", "la pesadez, el embole", "Que chatice esperar três horas no consulado!", "*Chato* + *-ice* (cualidad), como *velhice*. *Que chatice!* = ¡qué embole!"],
    ["a garotada", "los chicos, la muchachada", "A garotada joga futevôlei no fim da tarde.", "*Garoto* + *-ada* (colectivo). Verbo en singular: *a garotada joga*."],
    ["a olhada", "el vistazo («dar uma olhada»)", "Dá uma olhada nesse livro sobre Oswald de Andrade.", "*Dar uma olhada* = echar un vistazo. Patrón *dar uma* + sustantivo en *-ada*: *dar uma passada*, *uma volta*."],
    ["a sujeira", "la suciedad, la mugre", "Depois do bloco, a sujeira na rua era enorme.", "De *sujo* (sucio) + *-eira*. *Fazer sujeira* = ensuciar; figurado, jugada sucia."],
    ["a bobeira", "la tontería («dar bobeira» = descuidarse)", "Não dá bobeira com o celular na praia.", "*Dar bobeira* = descuidarse; *que bobeira!* = ¡qué tontería! De *bobo*."],
    ["o panelaço", "el cacerolazo", "Houve panelaço em vários bairros do Rio.", "*Panela* + *-aço* (golpe, acción colectiva). Verbo: *bater panela*."],
    ["o portão", "el portón (no «puerta grande»)", "O porteiro abriu o portão do prédio.", "Aumentativo de *porta*, masculino como casi todos en *-ão*: *o portão*. Plural *portões*."],
],

45: [  # Léxico traicionero
    ["o polvo", "el pulpo (no «polvo»)", "Em Portugal, o polvo à lagareiro é um prato típico.", "Falso amigo: pulpo. El polvo es *pó* o *poeira*."],
    ["contestar", "cuestionar, impugnar (no «responder»)", "Os historiadores contestam a imagem de uma escravidão branda.", "Falso amigo: cuestionar, impugnar. Responder es *responder*. Sustantivo: *a contestação*."],
    ["reparar", "notar, fijarse («reparar em»); también «arreglar»", "Você reparou no azulejo português da fachada?", "*Reparar em* algo = notarlo: *reparou no azulejo?* También arreglar o reparar un daño."],
    ["latir", "ladrar (no «latir» del corazón)", "O cachorro do vizinho latiu a noite inteira.", "Falso amigo: ladrar. El corazón *bate*. El ladrido es *o latido*."],
    ["largo", "ancho (no «largo»); también «plaza» (o Largo do Machado)", "A Avenida Presidente Vargas é larga e comprida.", "Falso amigo: ancho. Largo (longitud) es *comprido*. *O Largo do Machado* = una plaza."],
    ["a taça", "la copa", "Brindamos com uma taça de vinho do Porto.", "Copa de vino y copa trofeo: *a Taça Libertadores*. El vaso común es *copo*."],
    ["o presunto", "el jamón (no «presunto»)", "Um misto-quente é pão com presunto e queijo.", "Falso amigo: jamón. «Presunto» (supuesto) es *suposto*."],
    ["a salsa", "el perejil (no «salsa»)", "Coloca um pouco de salsa no peixe.", "Falso amigo: perejil. La salsa de comer es *o molho*; el baile sí es *salsa*."],
    ["a cena", "la escena (no «cena» = jantar)", "A cena final de Central do Brasil é inesquecível.", "Falso amigo: escena. La cena es *o jantar*. *Fazer cena* = hacer un escándalo."],
    ["ruivo", "pelirrojo", "Meu sobrinho é ruivo e sardento.", "Concuerda: *ruivo*, *ruiva*. Ojo: el rubio es *loiro*."],
    ["a propina", "la coima, el soborno (no «propina» = gorjeta)", "O fiscal foi preso por cobrar propina.", "Falso amigo: coima. La propina al mozo es *gorjeta*. *Cobrar propina* = pedir coima."],
    ["o cachorro", "el perro (no «cachorro» = filhote)", "Passeio com o cachorro no Aterro todo dia.", "Falso amigo: perro adulto. El cachorro es *filhote*. *Cachorro-quente* = pancho."],
    ["o vaso", "la maceta; el inodoro (no «vaso» = copo)", "Comprei um vaso de barro para a samambaia.", "Falso amigo: maceta (*vaso de planta*) e inodoro (*vaso sanitário*). El vaso para tomar es *copo*."],
    ["pelado", "desnudo (no «pelado» = careca)", "Na praia de Abricó, no Rio, pode ficar pelado.", "Falso amigo: desnudo. El calvo es *careca*. *Pelada* también es el picado de fútbol."],
    ["o balcão", "el mostrador, la barra (no «balcón» = varanda)", "Pedimos o pastel no balcão da pastelaria.", "Falso amigo: mostrador o barra. El balcón es *varanda* o *sacada*. Plural *balcões*."],
],

46: [  # Regiones de Brasil, Portugal, África
    ["o autocarro", "el colectivo (PT; en Brasil «ônibus»)", "Em Lisboa, apanhei o autocarro para Belém.", "Portugal. Cambia también el verbo: allá *apanhar o autocarro*; en Brasil, *pegar o ônibus*."],
    ["o comboio", "el tren (PT; en Brasil «trem»)", "O comboio de Lisboa para Coimbra leva duas horas.", "Portugal. En Brasil *comboio* es una caravana de vehículos, y el tren es *trem*."],
    ["o telemóvel", "el celular (PT)", "Em Portugal, o celular se chama telemóvel.", "Portugal; en Brasil, *celular*. *Tele-* + *móvel*."],
    ["o pequeno-almoço", "el desayuno (PT; en Brasil «café da manhã»)", "No hotel do Porto, o pequeno-almoço é servido até às dez.", "Portugal, con guion. Ojo: en los dos países *almoço* es el almuerzo."],
    ["o miúdo", "el chico, el nene (PT)", "Os miúdos brincavam na praça de Alfama.", "Portugal; en Brasil, *garoto* o *criança*. En Brasil *miúdo* es menudo: *dinheiro miúdo*."],
    ["fixe", "copado, genial (PT; en Brasil «legal»)", "Um amigo de Lisboa disse que o show foi muito fixe.", "Portugal, invariable: *um tipo fixe*, *uma festa fixe*. La *x* suena «sh»."],
    ["giro", "lindo, bonito (PT)", "Que vestido tão giro!, disse a portuguesa.", "Portugal, concuerda: *giro*, *gira*. En Brasil *giro* es giro, vuelta."],
    ["o sumo", "el jugo (PT; en Brasil «suco»)", "Pedi um sumo de laranja num café do Porto.", "Portugal; en Brasil, *suco*. En Brasil *sumo* es el jugo que se exprime de algo: *o sumo do limão*."],
    ["a macaxeira", "la mandioca (Nordeste; «aipim» en Rio)", "Em Recife, comi carne de sol com macaxeira.", "Nordeste; en Río *aipim* y en São Paulo *mandioca*. La *x* suena «sh»."],
    ["o guri", "el pibe, el nene (Sur de Brasil)", "Em Porto Alegre, o guri torce pelo Grêmio.", "Sur de Brasil; femenino *guria*. De origen tupí-guaraní, como el «gurí» rioplatense."],
    ["oxente", "¡pero mirá!, ¿qué? (Nordeste)", "Oxente, você não conhece Jorge Amado?", "Nordeste, sobre todo Bahía: sorpresa o extrañeza. Variante corta: *oxe*."],
    ["uai", "¡ué!, ¿y? (Minas Gerais)", "Uai, cadê o pão de queijo?", "Minas Gerais: muletilla de sorpresa u obviedad, al principio o al final: *Uai, sô!*"],
    ["bué", "mucho, muy (Angola, y hoy Lisboa)", "Em Luanda, dizem que a música é bué boa.", "Angola y habla juvenil de Portugal: *bué* + adjetivo = muy; *bué de* + sustantivo = mucho."],
    ["arretado", "genial; también «enojado» (Nordeste)", "O forró de ontem estava arretado!", "Nordeste: elogio (buenísimo) o enojo, según el contexto y el tono."],
    ["a casa de banho", "el baño (PT; en Brasil «banheiro»)", "Em Lisboa, perguntei onde era a casa de banho.", "Portugal; en Brasil, *banheiro*. En ambos, *tomar banho* = bañarse, ducharse."],
],

47: [  # Debate público
    ["o embate", "el enfrentamiento, el choque", "O embate entre governo e oposição marcou a Constituinte.", "De *embater* = chocar. Formal, de prensa: *o embate político*."],
    ["o viés", "el sesgo; también «el bies»", "Toda pesquisa tem algum viés.", "Sesgo, y el bies de costura. *Olhar de viés* = mirar de reojo. Plural *vieses*."],
    ["defasado", "desactualizado, atrasado", "O salário dos professores está defasado.", "De *defasagem* (desfase). *Salário defasado* = que quedó atrás de la inflación."],
    ["acirrado", "reñido, encarnizado", "A eleição de 1989 teve um segundo turno acirrado.", "De *acirrar* = exacerbar. *Disputa acirrada*, *debate acirrado*."],
    ["o descaso", "la desidia, el abandono", "O incêndio do Museu Nacional, em 2018, revelou anos de descaso.", "*Descaso com* algo: *descaso com a saúde pública*. Casi siempre, crítica al poder público."],
    ["a verba", "los fondos, la partida presupuestaria", "Falta verba para a despoluição da Baía de Guanabara.", "Femenino y en singular: *falta verba* = faltan fondos. En plural, varias partidas: *as verbas*."],
    ["escancarar", "dejar a la vista, abrir de par en par", "A pandemia escancarou a desigualdade nas favelas.", "*Porta escancarada* = abierta de par en par. Figurado: exponer lo que estaba oculto."],
    ["o ônus", "la carga, el costo", "O ônus da crise não pode cair só sobre os mais pobres.", "Igual en plural: *os ônus*. Opuesto: *o bônus*. *O ônus da prova* = la carga de la prueba."],
    ["o abaixo-assinado", "el petitorio con firmas", "Os moradores fizeram um abaixo-assinado contra o fechamento da escola.", "*Abaixo* + *assinado*: «los abajo firmantes». Plural *abaixo-assinados*."],
    ["o vereador", "el concejal", "A vereadora Marielle Franco foi assassinada no Rio em 2018.", "Concejal municipal; el concejo es *a Câmara de Vereadores*. Femenino: *a vereadora*."],
    ["o pleito", "la elección (en la prensa); el litigio", "O pleito de outubro terá urnas eletrônicas, como sempre.", "Formal, de prensa: la elección. En derecho: pleito, demanda."],
    ["a bancada", "el bloque (parlamentario)", "A bancada do Rio votou a favor do projeto.", "Bloque de legisladores por partido, estado o tema: *bancada ruralista*. También la mesada de la cocina."],
    ["a contrapartida", "la contraprestación; «em contrapartida» = en cambio", "A empresa recebeu o terreno e, como contrapartida, construiu uma praça.", "*Em contrapartida* = en cambio, por otro lado: conector formal de contraste."],
    ["enxugar", "secar; también «recortar, achicar (gastos)»", "O governo quer enxugar a máquina pública.", "*Enxugar a louça* = secar los platos. Figurado: *enxugar custos* = recortar. La *x* suena «sh»."],
    ["reivindicar", "reclamar (un derecho)", "Nas Diretas Já, milhões reivindicavam o voto para presidente.", "Con objeto directo: *reivindicar direitos*. Sustantivo: *a reivindicação*."],
],

48: [  # Periodismo, divulgación
    ["alegar", "alegar (con matiz de excusa)", "O ministro alegou que não sabia de nada.", "*Alegar que* + indicativo. Tono de excusa: *alegou doença* = puso como excusa estar enfermo."],
    ["apontar", "señalar, indicar", "O estudo aponta que o nível do mar subiu em Copacabana.", "*Apontar que* + indicativo = señalar. También apuntar con el dedo y sacar punta."],
    ["salientar", "destacar, subrayar", "A autora salienta o papel das mulheres na Abolição.", "*Salientar que* + indicativo = destacar que. Adjetivo: *saliente* = que sobresale."],
    ["o porta-voz", "el vocero", "O porta-voz da prefeitura negou o aumento da tarifa.", "*Porta* (lleva) + *voz*. Plural *porta-vozes*. Igual en género: *a porta-voz*."],
    ["o depoimento", "el testimonio, la declaración", "Os depoimentos da Comissão da Verdade revelaram casos de tortura.", "De *depor* (declarar): *prestar depoimento* = declarar, dar testimonio."],
    ["o desdobramento", "la derivación, la repercusión", "A reportagem teve desdobramentos políticos.", "De *desdobrar* = desplegar. *Ter desdobramentos* = tener derivaciones."],
    ["o jargão", "la jerga (técnica)", "O artigo evita o jargão acadêmico.", "Del francés *jargon*. Plural *jargões*."],
    ["cunhar", "acuñar (una expresión)", "Foi Ribeiro Couto quem cunhou a expressão «homem cordial»; Sérgio Buarque a tornou famosa.", "*Cunhar uma expressão*, *cunhar um termo*. Literal: acuñar moneda. *Nh* = ñ."],
    ["o lide", "el copete, el primer párrafo de la noticia", "Um bom lide responde: quem, o quê, quando e onde.", "Del inglés *lead*: el primer párrafo, que responde quién, qué, cuándo y dónde."],
    ["a reportagem", "el reportaje; también «el equipo de periodistas»", "Procurada pela reportagem, a empresa não respondeu.", "Femenino en *-agem*. *Procurada pela reportagem* = consultada por nuestros periodistas: fórmula de prensa."],
    ["ressaltar", "destacar, resaltar", "Os historiadores ressaltam que Zumbi resistiu por anos em Palmares.", "*Ressaltar que* + indicativo. Sinónimos: *salientar*, *destacar*."],
    ["veicular", "difundir, publicar (en un medio)", "A notícia foi veiculada no jornal da noite.", "De *veículo* (medio de comunicación). Formal, de prensa, muchas veces en pasiva: *foi veiculada*."],
    ["grifar", "subrayar, resaltar (en un texto)", "Grifei as frases mais importantes de Raízes do Brasil.", "*Grifar* = subrayar o resaltar. *O grifo* = la cursiva o lo subrayado. *Grife* es otra cosa: marca de lujo."],
    ["a chamada", "el titular breve, el anuncio; también «la llamada»", "A chamada na capa dizia: «Rio sem água».", "Titular breve, llamada telefónica y lista: *fazer a chamada* = tomar lista."],
    ["a fonte", "la fuente (de información); también «fuente de agua»", "O jornalista não revelou a fonte.", "De información y de agua. *Revelar* o *proteger a fonte*."],
],

49: [  # Registro culto y coloquial
    ["irado", "buenísimo (Rio, coloquial); también «enojado»", "O show do Circo Voador foi irado!", "Carioca: buenísimo; en registro formal, enojado. Concuerda: *festa irada*."],
    ["sinistro", "impresionante, genial (Rio, coloquial); «siniestro»", "Esse golaço foi sinistro, mermão!", "Carioca: elogio fuerte; en registro formal, siniestro. El contexto decide."],
    ["sangue bom", "buena gente (coloquial)", "O dono do boteco é sangue bom.", "Coloquial e invariable: *ele é sangue bom*, *ela é sangue bom*. Como *gente boa*."],
    ["demorou", "¡dale!, ¡de una! (Rio, coloquial)", "Praia amanhã cedo? — Demorou!", "Perfeito de *demorar* congelado como «¡dale!»: acepta una propuesta con entusiasmo."],
    ["suave", "tranqui, todo bien (coloquial)", "Tá tudo suave por aqui.", "Coloquial: *tá suave* = está tranqui. Fuera de la jerga, suave."],
    ["coé", "¿qué onda? (saludo carioca)", "Coé, Rafa, tudo certo?", "De *qual é?*: saludo carioca muy informal. *Coé, mermão!*"],
    ["o mané", "el gil, el tonto (coloquial)", "Só um mané deixa a mochila sozinha na areia.", "Coloquial; viene de *Manuel*. Aguda con *é*. Sinónimo: *otário*."],
    ["o papo reto", "hablar claro, sin vueltas (coloquial)", "Vou te dar um papo reto: você errou.", "*Papo* = charla; *reto* = derecho. *Dar um papo reto* = hablar sin vueltas."],
    ["sussa", "tranqui (coloquial, de «sossegado»)", "Pode chegar mais tarde, tá sussa.", "Coloquial e invariable, de *sossegado*: *tá sussa*."],
    ["outrossim", "asimismo (muy formal)", "Outrossim, informo que o prazo foi prorrogado.", "Muy formal, de oficios y escritos jurídicos. En el habla: *além disso*."],
    ["porquanto", "puesto que, ya que (formal)", "O pedido foi negado, porquanto faltavam documentos.", "Formal: introduce la causa, con indicativo. En el habla: *porque*, *já que*."],
    ["haja vista", "dado que, teniendo en cuenta (formal)", "A obra atrasou, haja vista as chuvas de verão.", "Formal: *haja vista* + sustantivo o *que*. Es fórmula fija: suele quedar invariable."],
    ["destarte", "de este modo, así (muy formal)", "Destarte, conclui-se que a medida foi eficaz.", "Muy formal, arcaizante. En textos actuales: *assim*, *dessa forma*."],
    ["doravante", "de ahora en adelante (formal)", "Doravante, os pedidos serão feitos pelo site.", "Formal: de *de ora avante*. En el habla: *a partir de agora*."],
    ["conquanto", "aunque (formal, + subjuntivo)", "Conquanto seja longo, o romance de Guimarães Rosa é fascinante.", "Formal y con subjuntivo: *conquanto seja*. En el habla: *embora*."],
],

50: [  # Refranes, expresiones fijas
    ["fazer questão", "insistir, tener empeño", "Faço questão de te levar ao Pão de Açúcar.", "*Fazer questão de* + infinitivo = empeñarse en. *Não faço questão* = no me importa, me da igual."],
    ["dar certo", "salir bien, funcionar", "Tomara que o plano dê certo.", "*Dar certo* = salir bien; *dar errado* = salir mal. El sujeto es la cosa: *o plano deu certo*."],
    ["levar a sério", "tomar en serio", "Ninguém levou a sério o aviso de ressaca.", "Sin artículo: *levar a sério*. Relacionado: *não me leve a mal* = no me lo tomes a mal."],
    ["pisar na bola", "meter la pata", "Pisei na bola: esqueci o aniversário dela.", "Literal «pisar la pelota». Se conjuga *pisar*: *pisei na bola*."],
    ["dar um jeito", "arreglárselas, buscarle la vuelta", "Não tem mesa, mas o garçom vai dar um jeito.", "*Jeito* = manera: *dar um jeito* = encontrar la forma. De ahí el famoso *jeitinho brasileiro*."],
    ["ficar de boa", "quedarse tranqui", "Domingo vou ficar de boa em casa.", "Coloquial: *de boa* = tranqui. *Tô de boa* = estoy bien, sin drama."],
    ["pagar mico", "hacer el ridículo", "Paguei mico dançando samba no Sambódromo.", "*Mico* = mono; en el habla, papelón. Se conjuga *pagar*: *paguei mico*."],
    ["dar um bolo", "dejar plantado", "Ele me deu um bolo e não apareceu no bar.", "*Dar um bolo em alguém* = plantarlo; *levar um bolo* = que te planten."],
    ["cair a ficha", "caer la ficha", "Só depois caiu a ficha: era o Chico Buarque!", "Orden al revés que en español: *caiu a ficha*. Viene de las fichas del teléfono público."],
    ["puxar o saco", "chupar las medias, adular", "Ele vive puxando o saco do chefe.", "Algo vulgar. El adulador es *o puxa-saco*."],
    ["segurar vela", "tocar el violín (acompañar a una pareja)", "Não quero segurar vela no cinema com vocês dois.", "Literal «sostener la vela»: estar de más con una pareja. Se conjuga *segurar*."],
    ["chutar o balde", "mandar todo al diablo", "Cansou do escritório e chutou o balde: foi morar em Trancoso.", "Literal «patear el balde». *Chutar* = patear; también *chutar* = adivinar a ciegas en un examen."],
    ["tirar onda", "fanfarronear; también «cargar a alguien» (Rio)", "Ele adora tirar onda com o carro novo.", "*Tirar onda com* = presumir algo o cargar a alguien. Coloquial carioca."],
    ["dar mole", "descuidarse; también «dar pie, mostrar interés» (Rio)", "Não dá mole com a carteira no ônibus.", "*Dar mole* = descuidarse, o mostrar interés en alguien. *Mole* = blando; *é mole?* = ¿podés creer?"],
    ["encher linguiça", "rellenar, hablar sin decir nada", "O texto tem três páginas, mas metade é encher linguiça.", "Literal «rellenar chorizo»: meter relleno en un texto o discurso. Se conjuga *encher*."],
],

51: [  # Repaso general
    ["pelo jeito", "por lo visto", "Pelo jeito, vai chover no desfile.", "*Pelo* = por + o. Abre la frase: *pelo jeito, vai chover*. Sinónimo: *pelo visto*."],
    ["por acaso", "por casualidad; ¿acaso?", "Você viu, por acaso, minhas chaves?", "En preguntas suaviza el pedido: *você viu, por acaso…?* *Acaso* = azar, casualidad."],
    ["de vez", "definitivamente, para siempre", "Ela se mudou de vez para Lisboa.", "*De vez* = definitivamente. No confundir con *de vez em quando* = de vez en cuando."],
    ["de cara", "de entrada, enseguida", "Gostei de Salvador de cara.", "*De cara* = de entrada. *Cara* = rostro; *ficar de cara* = quedar asombrado."],
    ["de quebra", "de yapa, encima", "Fomos a Petrópolis e, de quebra, visitamos o Museu Imperial.", "*De quebra* = de yapa, además. Va entre comas, como inciso."],
    ["às escondidas", "a escondidas", "Na ditadura, muita gente lia Paulo Freire às escondidas.", "Plural con crasis: *às escondidas*. De *esconder*."],
    ["ao léu", "a la deriva, sin rumbo", "Passei a tarde andando ao léu pelo Centro.", "*Ao* = a + o. Casi siempre con verbos de moverse: *andar ao léu* = vagar sin rumbo."],
    ["a torto e a direito", "a diestra y siniestra", "Ele distribui críticas a torto e a direito.", "Frase fija: sin criterio, para todos lados. *Torto* = torcido."],
    ["de mão beijada", "servido en bandeja, gratis", "Ninguém recebe nada de mão beijada.", "Literal «de mano besada»: sin esfuerzo. Casi siempre en negativo: *ninguém dá nada de mão beijada*."],
    ["de olho", "atento, vigilando («ficar de olho»)", "Fica de olho na bolsa no metrô.", "*Ficar de olho em* = vigilar. *Estar de olho em alguém* = tenerle el ojo echado."],
    ["em cima da hora", "sobre la hora", "Entregou a redação em cima da hora.", "*Em cima da hora* = sobre la hora. *Em cima* = encima."],
    ["no fim das contas", "al final de cuentas", "No fim das contas, a viagem deu certo.", "*No* = em + o. Sinónimo: *afinal*. Abre la conclusión de un relato."],
    ["nem pensar", "¡ni loco!, ni en sueños", "Pagar cem reais por um chope? Nem pensar!", "Rechazo tajante, solo o al final. *Nem* = ni."],
    ["por um triz", "por un pelo", "Pegamos o último barco para Niterói por um triz.", "*Triz* solo vive en esta frase. *Escapar por um triz* = salvarse por un pelo."],
    ["à mão", "a mano (hecho a mano; al alcance)", "Você tem uma caneta à mão?", "Con crasis: *à mão*. *Feito à mão* = hecho a mano; *ter à mão* = tener a mano."],
],

52: [],
}
