# -*- coding: utf-8 -*-
"""El programa del año: portugués de Brasil hasta C1 para hispanohablantes.

Es la fuente única del temario.  La leen build_course.py, los tests y quien
escribe contenido (lecciones, ítems, lecturas, frases): cada pieza de
contenido de la semana N solo puede usar la gramática de las semanas 1..N.

Variedad: portugués brasileño (norma urbana culta, con lo coloquial marcado
como tal).  Las diferencias con el portugués europeo se señalan donde
importan (semana 46 y notas sueltas).

Orden: sigue la secuencia de los manuales para hispanohablantes (Bem-Vindo!,
Novo Avenida Brasil, Terra Brasil, Brasil Intercultural, Vamos nessa?) y los
«pontos críticos» de la bibliografía de Português para Falantes de Espanhol
(Almeida Filho 1995; Grannier 2002; Akerberg 2004; Ferreira 1995; Durão
1999): las formas que el español no tiene (futuro do subjuntivo, infinitivo
pessoal, crase, contracciones) y las que se parecen demasiado (pretérito
perfeito composto, gostar de, muito/muy, heterosemánticos) llegan con su
propia semana.  El imperfeito y el perfeito llegan en el primer trimestre;
el subjuntivo presente, en el segundo.
"""

SEASONS = [
    dict(n=1, name="Primeiros Passos", weeks=[1, 13], level="A1 → A2",
         blurb="Sonidos, género, artículos y contracciones, el presente completo y el pretérito perfeito."),
    dict(n=2, name="Pé na Estrada", weeks=[14, 26], level="A2 → B1",
         blurb="Imperfeito, pronombres, futuro, condicional, el perfeito composto y el subjuntivo presente."),
    dict(n=3, name="Mar Aberto", weeks=[27, 39], level="B1 → B2",
         blurb="Futuro do subjuntivo, infinitivo pessoal, condicionales, regencia, crase y el portugués hablado."),
    dict(n=4, name="O Cume", weeks=[40, 52], level="B2 → C1",
         blurb="Registro formal, formas reducidas, formación de palabras, variación y el examen final."),
]

# Qué se aprende a hacer cada semana y su campo léxico (una unidad
# comunicativa por semana, como en los manuales).
SAI_FARE = {
    1: ("Saludar, presentarte y deletrear tu nombre", "Saludos, tu / você, alfabeto"),
    2: ("Nombrar cosas y decir qué hay (tem / há)", "Casa, aula y objetos cotidianos"),
    3: ("Decir dónde están las cosas y la gente", "La ciudad, el barrio; contracciones"),
    4: ("Describir personas: nacionalidad, carácter y aspecto", "Países, colores, adjetivos"),
    5: ("Contar tu rutina y hablar de tu trabajo", "Profesiones, la semana, el día"),
    6: ("Hacer planes simples: ir, venir, poder, querer", "Tiempo libre, invitaciones"),
    7: ("Decir la hora, las fechas y los precios", "Números, días de la semana, meses"),
    8: ("Preguntar, contar lo que estás haciendo y lo que vas a hacer", "Planes del fin de semana"),
    9: ("Moverte por la ciudad y usar el transporte", "Direcciones, medios de transporte"),
    10: ("Hablar de tu familia y tus cosas", "Familia, la casa, objetos personales"),
    11: ("Contar lo que hiciste", "Ontem, o fim de semana, viajes"),
    12: ("Dar instrucciones y consejos; tu rutina diaria", "Cuerpo, salud, farmacia, recetas"),
    13: ("Manejarte en las situaciones cotidianas de A1 y A2", "Repaso de la primera estación"),
    14: ("Hablar de gustos, preferencias y necesidades", "Comida brasileña, música, deporte"),
    15: ("Describir cómo eran las cosas y contar recuerdos", "Infancia, escuela, ciudades antes"),
    16: ("Referirte a personas y cosas sin repetirlas", "Compras, regalos, favores"),
    17: ("Hablar del futuro y hacer previsiones", "Trabajo, estudios, el clima"),
    18: ("Pedir con cortesía, sugerir e imaginar", "Restaurante, hotel, servicios"),
    19: ("Comparar y elegir", "Ropa, precios, ciudades de Brasil"),
    20: ("Cuantificar, negar y reaccionar", "Conversación cotidiana"),
    21: ("Contar lo que viene pasando y lo que ya había pasado", "Novedades, cambios recientes"),
    22: ("Describir procesos y resultados", "Noticias breves, trámites"),
    23: ("Expresar deseos, dudas y recomendaciones", "Salud, relaciones, consejos"),
    24: ("Expresar finalidad, condición y concesión", "Proyectos, viajes, planes"),
    25: ("Definir y describir con precisión", "Personas, lugares, objetos"),
    26: ("Contar, opinar y planificar con soltura", "Repaso de la segunda estación"),
    27: ("Hablar de condiciones y momentos futuros", "Planes de vida, mudanzas"),
    28: ("Imaginar, poner condiciones y lamentar", "Sueños, decisiones"),
    29: ("Decir para qué y según quién con el infinitivo", "Estudio, trabajo, derechos"),
    30: ("Hablar de lo que pudo haber sido", "Arrepentimientos, historia personal"),
    31: ("Relatar lo que dijeron otros", "Prensa, entrevistas, chismes"),
    32: ("Hablar de normas, avisos y costumbres impersonales", "Carteles, anuncios, reglas"),
    33: ("Leer textos formales con pronombres enclíticos", "Literatura, prensa escrita"),
    34: ("Argumentar y conectar ideas", "Debates, medio ambiente, sociedad"),
    35: ("Usar los verbos con su preposición", "Trámites, trabajo, vínculos"),
    36: ("Escribir sin errores de crase", "Horarios, direcciones, textos formales"),
    37: ("Manejar los verbos irregulares menos frecuentes", "Ciencia, trámites, tecnología"),
    38: ("Entender y usar el portugués hablado de Brasil", "Charlas, redes, series"),
    39: ("Argumentar, relatar y matizar", "Repaso de la tercera estación"),
    40: ("Escribir con registro formal y nominalizaciones", "Informes, textos académicos"),
    41: ("Leer narrativa literaria", "Machado de Assis, Clarice Lispector"),
    42: ("Condensar información con gerundio y participio", "Crónica, noticias"),
    43: ("Escribir mails y cartas formales", "Trabajo, universidad, instituciones"),
    44: ("Ampliar vocabulario por derivación", "Formación de palabras, diminutivos"),
    45: ("Evitar los falsos amigos y heterosemánticos", "Léxico traicionero"),
    46: ("Reconocer variedades del portugués", "Regiones de Brasil, Portugal, África"),
    47: ("Matizar opiniones y sostener una tesis", "Debate público"),
    48: ("Resumir y reformular textos ajenos", "Periodismo, divulgación"),
    49: ("Pasar de lo coloquial a lo culto y viceversa", "Registro culto y coloquial"),
    50: ("Usar colocaciones y expresiones idiomáticas", "Refranes, expresiones fijas"),
    51: ("Repasar B2-C1 con soltura", "Repaso general"),
    52: ("Certificar tu C1", "Celpe-Bras (Avançado Superior) / C1"),
}

# Los tiempos del conjugador (docs/js/conjugator.js) y la semana en que se
# enseñan.  Antes de esa semana ningún ejercicio puede pedirlos ni usarlos
# como distractor.
TENSE_WEEK = {
    "presente": 5,              # ser, estar y ter desde la semana 1
    "gerundio": 8,              # estar + gerúndio
    "perfeito": 11,
    "imperativo": 12,
    "imperfeito": 15,
    "futuro": 17,
    "condicional": 18,          # futuro do pretérito
    "perfeitoComposto": 21,     # tenho falado: repetición hasta hoy
    "maisQuePerfeitoComposto": 21,  # tinha falado
    "participio": 22,           # pasiva y participios dobles
    "subjPresente": 23,
    "subjFuturo": 27,
    "subjImperfeito": 28,
    "infPessoal": 29,
    "subjPerfeito": 30,
    "subjMaisQuePerfeito": 30,
    "subjFuturoComposto": 30,
    "futuroComposto": 30,
    "condicionalComposto": 30,
    "maisQuePerfeito": 41,      # fizera: literario, se reconoce
}

WEEKS = [
    # ---------------- Estação 1: Primeiros Passos (A1 -> A2) ----------------
    dict(w=1, title="Sons, alfabeto, ser e estar", level="A1",
         focus="El portugués se escribe parecido al español, pero suena distinto.",
         keys=["Vocales abiertas y cerradas: avó / avô, é / ê, ó / ô.",
               "Vocales nasales: mão, bom, sim, pão; -m final no se pronuncia como m.",
               "lh = ll de «calle» antigua (trabalho), nh = ñ (vinho), ç = s (cabeça).",
               "En Brasil ti y di suenan chi y yi (tia, dia); -l final suena u (Brasil).",
               "r inicial y rr suenan como una j suave (rato, carro).",
               "ser, estar y ter en presente: los primeros verbos, de memoria."],
         v=["ser", "estar", "ter"], tenses=["presente"]),
    dict(w=2, title="Substantivos: gênero e número", level="A1",
         focus="Los plurales en -ões, -ãos y -ães, y los sustantivos que cambian de género.",
         keys=["-o → -os, -a → -as; -m → -ns (homem / homens).",
               "-ão → -ões casi siempre (limão / limões), a veces -ães o -ãos (pão / pães, mão / mãos).",
               "-l → -is (animal / animais, papel / papéis); -r, -z, -s → -es.",
               "Género distinto del español: o leite, o sangue, a árvore, o nariz, a ponte, a dor.",
               "-agem es femenino: a viagem, a garagem, a mensagem."],
         v=["ser", "estar", "ter"], tenses=["presente"]),
    dict(w=3, title="Artigos e contrações", level="A1",
         focus="El artículo se funde con la preposición: no, na, do, da, ao, pelo.",
         keys=["o, a, os, as; um, uma, uns, umas.",
               "em + o = no, em + a = na; de + o = do; a + o = ao; por + o = pelo.",
               "Artículo ante posesivo y nombre propio: a minha casa, o Pedro.",
               "Las contracciones son obligatorias: estou no Brasil (nunca «em o»)."],
         v=["ser", "estar", "ter"], tenses=["presente"]),
    dict(w=4, title="Adjetivos, cores e nacionalidades", level="A1",
         focus="Concordancia y las nacionalidades en -ês / -esa.",
         keys=["Adjetivos en -o (4 formas), en -e o consonante (2 formas).",
               "-ês → -esa: português / portuguesa; -ão → -ã (alemão / alemã).",
               "muito = muy y mucho: muito bonito, muito dinheiro (nunca «muy»).",
               "Plurales de adjetivos en -l: fácil / fáceis, azul / azuis."],
         v=["ser", "estar", "ter"], tenses=["presente"]),
    dict(w=5, title="Presente: verbos regulares", level="A1",
         focus="Las tres conjugaciones, você con verbo en tercera y «a gente».",
         keys=["-ar, -er, -ir: falo, falas, fala, falamos, falam.",
               "você / vocês conjugan como ele / eles: você fala, vocês falam.",
               "«a gente» = nosotros, con verbo en tercera singular: a gente fala.",
               "En Brasil el pronombre sujeto se dice mucho más que en español.",
               "Grafía: ficar → fico, conhecer → conheço, dirigir → dirijo."],
         v=["falar", "morar", "trabalhar", "comer", "beber", "abrir", "partir", "estudar"],
         tenses=["presente"]),
    dict(w=6, title="Presente: verbos irregulares", level="A1",
         focus="Los irregulares que cubren la mitad de lo que vas a decir.",
         keys=["ir (vou, vai, vamos, vão), fazer (faço), dizer (digo), trazer (trago).",
               "poder (posso), querer (quero), saber (sei), ver (vejo), vir (venho).",
               "dar (dou), pôr (ponho), sair (saio), ler (leio), ouvir (ouço), pedir (peço).",
               "Alternancia vocálica: dormir → durmo, preferir → prefiro, subir → sobe."],
         v=["ir", "fazer", "poder", "querer", "saber", "ver", "vir", "dizer", "dar", "sair", "pedir", "dormir"],
         tenses=["presente"]),
    dict(w=7, title="Números, horas e datas", level="A1",
         focus="Contar, fechar y decir la hora como en Brasil.",
         keys=["dois / duas, um / uma, duzentos / duzentas concuerdan en género.",
               "Los días son ordinales: segunda-feira, terça-feira… sábado, domingo.",
               "É uma hora, são duas horas; às três (con crase); meio-dia, meia-noite.",
               "meia = seis al dar un número de teléfono (três, meia, nove)."],
         v=["ser", "ter", "estar"], tenses=["presente"]),
    dict(w=8, title="Perguntas, ir + infinitivo e estar + gerúndio", level="A1",
         focus="Preguntar, decir lo que estás haciendo y lo que vas a hacer.",
         keys=["o que, quem, qual / quais, quanto, como, onde, quando, por que.",
               "por que (pregunta), porque (respuesta), por quê (al final), o porquê.",
               "vou + infinitivo es el futuro normal del habla: vou viajar amanhã.",
               "estar + gerúndio en Brasil (estou comendo); en Portugal «a comer»."],
         v=["ir", "estar", "fazer", "falar", "comer"], tenses=["presente", "gerundio"]),
    dict(w=9, title="Preposições de lugar e movimento", level="A2",
         focus="em, a, para, de, por: las que no se traducen una a una.",
         keys=["Estar / morar em: moro em Salvador, estou na praia.",
               "Ir a / ir para (en el habla, «ir no mercado»); chegar em (habla) / a (norma).",
               "Medios: de carro, de ônibus, de avião; pero a pé.",
               "por + o = pelo: passar pela praça; por aqui, por lá."],
         v=["ir", "vir", "chegar", "sair", "voltar"], tenses=["presente"]),
    dict(w=10, title="Possessivos e demonstrativos", level="A2",
         focus="seu puede ser «tuyo» o «suyo»; dele / dela resuelve la duda.",
         keys=["meu, teu, seu, nosso (con género y número): minha casa, meus pais.",
               "En Brasil seu = de você; para «de él / de ella», dele / dela: o carro dele.",
               "este / esse / aquele, y los neutros isto / isso / aquilo.",
               "Contracciones: neste, nesse, naquele, deste, desse, daquele."],
         v=["ser", "ter", "estar"], tenses=["presente"]),
    dict(w=11, title="Pretérito perfeito", level="A2",
         focus="El pasado que más vas a usar: equivale a «hablé» y también a «he hablado».",
         keys=["falei, falou, falamos, falaram; comi, comeu; abri, abriu.",
               "Irregulares: fui (ser e ir), fiz, tive, estive, pude, quis, disse, vi, vim, dei, soube, trouxe, pus.",
               "«Hoy he comido» se dice hoje eu comi: el perfeito cubre los dos pasados.",
               "Grafía: ficar → fiquei, chegar → cheguei, começar → comecei."],
         v=["falar", "comer", "abrir", "ser", "ir", "fazer", "ter", "estar", "poder", "dizer", "ver", "vir"],
         tenses=["perfeito"]),
    dict(w=12, title="Imperativo, reflexivos e rotina", level="A2",
         focus="Órdenes a você y la rutina diaria con el pronombre delante.",
         keys=["Imperativo de você (formal y escrito): fale, coma, abra; irregulares seja, vá, faça.",
               "En el habla de Brasil se usa la forma de tu: fala!, vem cá!, olha!",
               "Negativo: não fale / (habla) não fala.",
               "Reflexivos con pronombre delante en Brasil: eu me levanto, ele se chama.",
               "Menos reflexivos que en español: acordar (despertarse), lembrar (acordarse)."],
         v=["levantar-se", "chamar-se", "sentar-se", "deitar-se", "vestir-se", "lavar-se"],
         tenses=["presente", "imperativo"]),
    dict(w=13, title="CHEFÃO — Nível A2", level="A2", boss=True,
         focus="Examen de la primera estación: todo lo anterior, mezclado.",
         keys=["Plurales, género y contracciones sin pensarlo.",
               "Presente regular e irregular.",
               "Pretérito perfeito regular e irregular.",
               "Possessivos, demonstrativos, preposiciones de lugar.",
               "ir + infinitivo y estar + gerúndio."],
         v=["ser", "estar", "ter", "ir", "fazer", "poder", "querer"],
         tenses=["presente", "perfeito"]),

    # ---------------- Estação 2: Pé na Estrada (A2 -> B1) ----------------
    dict(w=14, title="Gostar de e verbos com preposição", level="A2",
         focus="«Gustar» al revés: en portugués el que gusta es el sujeto.",
         keys=["eu gosto de café, ela gosta de dançar: la persona es el sujeto.",
               "gostar de + o = gosto do filme; gosto da música.",
               "precisar de, lembrar de, depender de, sonhar com, pensar em, acreditar em.",
               "achar = creer, opinar: acho que sim; achar = encontrar."],
         v=["gostar", "precisar", "lembrar", "pensar", "achar"],
         tenses=["presente", "perfeito"]),
    dict(w=15, title="Pretérito imperfeito", level="A2",
         focus="No es cuestión de duración: es qué estás mirando.",
         keys=["falava, comia, abria; irregulares: era, tinha, vinha, punha.",
               "Imperfeito: fondo, costumbre, descripción, edad, hora.",
               "Perfeito: acción cerrada que hace avanzar el relato.",
               "Quando eu era criança, morava no interior; um dia, mudamos."],
         v=["falar", "comer", "abrir", "ser", "ter", "vir", "pôr", "estar"],
         tenses=["imperfeito", "perfeito"]),
    dict(w=16, title="Pronomes objeto", level="A2",
         focus="o, a, lhe, te, me: y lo que de verdad se dice en Brasil.",
         keys=["Directo: me, te, o, a, nos, os, as; indirecto: me, te, lhe, nos, lhes.",
               "Tras -r, -s, -z: comprá-lo, fi-lo; tras nasal: dão-no (norma escrita).",
               "Habla de Brasil: pronombre delante (me dá, te amo) y «ele» como objeto (vi ele).",
               "comigo, contigo, conosco; para mim (nunca «para mí» ni «para eu» ante nombre)."],
         v=["ver", "dar", "dizer", "conhecer", "encontrar"],
         tenses=["presente", "perfeito"]),
    dict(w=17, title="Futuro do presente", level="B1",
         focus="El futuro simple, más escrito que hablado.",
         keys=["Infinitivo + -ei, -ás, -á, -emos, -ão: falarei, comerá.",
               "Irregulares: farei, direi, trarei.",
               "En el habla: vou + infinitivo; el futuro simple suena formal.",
               "Previsiones y promesas: amanhã choverá, prometo que ligarei."],
         v=["falar", "fazer", "dizer", "trazer", "ser", "ir"],
         tenses=["futuro", "presente"]),
    dict(w=18, title="Futuro do pretérito e cortesia", level="B1",
         focus="El condicional: gostaria, poderia, seria.",
         keys=["Infinitivo + -ia, -ias, -ia, -íamos, -iam: falaria.",
               "Irregulares: faria, diria, traria.",
               "Cortesía: Eu gostaria de um café. Você poderia me ajudar?",
               "En el habla, el imperfeito lo reemplaza: eu queria um café."],
         v=["gostar", "poder", "fazer", "dizer", "ser", "ter"],
         tenses=["condicional", "imperfeito"]),
    dict(w=19, title="Comparativos e superlativos", level="B1",
         focus="mais... (do) que, e los irregulares que el español no tiene.",
         keys=["mais / menos ... (do) que; tão ... quanto / como.",
               "maior, menor, melhor, pior; «mais grande» es error.",
               "Superlativo: o mais caro; -íssimo (facílimo, felicíssimo).",
               "bem = muy (bem caro), y mesmo = realmente, incluso."],
         v=["ser", "estar", "custar"], tenses=["presente", "perfeito"]),
    dict(w=20, title="Indefinidos, negação e quantidade", level="B1",
         focus="tudo / todo, nada, ninguém, nenhum y la doble negación.",
         keys=["tudo (todo, pronombre) ≠ todo / toda (+ sustantivo): comi tudo; todo dia.",
               "algum / nenhum, alguém / ninguém, algo / nada.",
               "também não = tampoco; nem = ni.",
               "En el habla: «não sei não», la negación también al final."],
         v=["ter", "saber", "ver", "haver"], tenses=["presente", "perfeito"]),
    dict(w=21, title="Pretérito perfeito composto e mais-que-perfeito", level="B1",
         focus="«tenho feito» no es «he hecho»: es algo que se repite hasta hoy.",
         keys=["ter (presente) + participio = acción repetida o continua hasta ahora.",
               "Tenho trabalhado muito = vengo trabajando mucho.",
               "«He comido» se dice comi; «tenho comido» = vengo comiendo.",
               "Mais-que-perfeito: tinha feito (habla) = había hecho."],
         v=["trabalhar", "estudar", "fazer", "ver", "dizer"],
         tenses=["perfeitoComposto", "maisQuePerfeitoComposto"]),
    dict(w=22, title="Particípios e voz passiva", level="B1",
         focus="Participios dobles y la pasiva con ser y estar.",
         keys=["Irregulares: feito, dito, visto, escrito, aberto, posto, vindo.",
               "Dobles: pago / pagado, aceito / aceitado, ganho, gasto, entregue, morto.",
               "ter / haver + regular (tinha pagado); ser / estar + irregular (foi pago).",
               "Pasiva: a casa foi construída em 1920 (concuerda con el sujeto)."],
         v=["fazer", "escrever", "abrir", "pagar", "aceitar", "ganhar"],
         tenses=["participio", "perfeito"]),
    dict(w=23, title="Presente do subjuntivo", level="B1",
         focus="Deseo, duda y recomendación, casi como en español.",
         keys=["Raíz de la 1.ª persona del presente: faço → faça, tenho → tenha.",
               "Irregulares: seja, esteja, vá, dê, saiba, queira, haja.",
               "espero que, quero que, é importante que, talvez, tomara que.",
               "achar que / acreditar que con indicativo: acho que ele vem."],
         v=["falar", "fazer", "ter", "ser", "estar", "ir", "saber", "querer"],
         tenses=["subjPresente"]),
    dict(w=24, title="Subjuntivo: conjunções", level="B1",
         focus="para que, embora, antes que, até que, caso: siempre subjuntivo.",
         keys=["para que, a fim de que, antes que, sem que + subjuntivo.",
               "embora (aunque) siempre con subjuntivo: embora esteja cansado.",
               "caso = si (hipótesis): caso chova, fico em casa.",
               "Imperativo formal y negativo = subjuntivo: não faça isso."],
         v=["ser", "estar", "ter", "poder", "chover"],
         tenses=["subjPresente", "imperativo"]),
    dict(w=25, title="Pronomes relativos", level="B1",
         focus="que, quem, onde, o qual, cujo.",
         keys=["que para personas y cosas; quem tras preposición para personas.",
               "onde para lugares; o que = lo que.",
               "cujo / cuja concuerda con lo poseído: o autor cujo livro li.",
               "Preposición delante: a cidade em que moro, a pessoa de quem falei."],
         v=["morar", "falar", "conhecer", "gostar"],
         tenses=["presente", "perfeito", "imperfeito"]),
    dict(w=26, title="CHEFÃO — Nível B1", level="B1", boss=True,
         focus="Examen de la segunda estación.",
         keys=["Perfeito e imperfeito en el relato.",
               "Pronombres objeto y posesivos.",
               "Futuro, condicional y cortesía.",
               "Perfeito composto frente al pretérito.",
               "Subjuntivo presente y conjunciones."],
         v=["ser", "estar", "ter", "fazer", "ir", "poder"],
         tenses=["perfeito", "imperfeito", "futuro", "condicional", "subjPresente"]),

    # ---------------- Estação 3: Mar Aberto (B1 -> B2) ----------------
    dict(w=27, title="Futuro do subjuntivo", level="B1",
         focus="La forma que el español perdió: quando eu for, se você quiser.",
         keys=["Raíz de la 3.ª plural del perfeito sin -ram: fizeram → fizer, foram → for.",
               "quando, se, assim que, enquanto, como, onde + futuro próximo.",
               "Se você quiser, a gente vai (si querés…); quando eu chegar, te ligo.",
               "Regulares: falar → quando eu falar (igual al infinitivo)."],
         v=["ser", "ir", "fazer", "ter", "estar", "poder", "querer", "vir", "ver", "saber"],
         tenses=["subjFuturo", "futuro"]),
    dict(w=28, title="Imperfeito do subjuntivo e condicionais", level="B2",
         focus="se eu fosse, se eu tivesse: la hipótesis del presente.",
         keys=["Raíz de la 3.ª plural del perfeito: fizeram → fizesse, foram → fosse.",
               "Se + imperfeito do subjuntivo + futuro do pretérito: se eu pudesse, viajaria.",
               "Queria que você viesse; era importante que soubessem.",
               "Solo la forma en -sse: el portugués no tiene la de «-ra» para esto."],
         v=["ser", "ter", "fazer", "poder", "saber", "vir", "dizer", "querer"],
         tenses=["subjImperfeito", "condicional"]),
    dict(w=29, title="Infinitivo pessoal", level="B2",
         focus="El infinitivo con persona: para nós irmos, antes de vocês saírem.",
         keys=["Infinitivo + -es, -mos, -em: falar, falares, falar, falarmos, falarem.",
               "Con sujeto propio distinto: é bom vocês chegarem cedo.",
               "Tras preposición: para eles entenderem, sem nós sabermos.",
               "Reemplaza a «para que» + subjuntivo en el habla: para a gente ir."],
         v=["falar", "ser", "ter", "fazer", "ir", "saber", "sair"],
         tenses=["infPessoal", "subjPresente"]),
    dict(w=30, title="Tempos compostos e hipótese no passado", level="B2",
         focus="se eu tivesse sabido, teria ido: lo que pudo haber sido.",
         keys=["tenha feito, tivesse feito, tiver feito, teria feito, terei feito.",
               "Se tivesse chovido, teríamos ficado em casa.",
               "Espero que tenham gostado; quando tiver terminado, aviso.",
               "En el habla: se eu soubesse, tinha ido (imperfeito por condicional)."],
         v=["fazer", "ver", "ir", "saber", "chegar"],
         tenses=["subjMaisQuePerfeito", "condicionalComposto", "subjPerfeito", "subjFuturoComposto", "futuroComposto"]),
    dict(w=31, title="Discurso indireto e correlação de tempos", level="B2",
         focus="Contar lo que dijo otro, moviendo tiempos, pronombres y adverbios.",
         keys=["Ele disse: «vou» → Ele disse que ia.",
               "hoje → naquele dia, amanhã → no dia seguinte, aqui → lá.",
               "Imperativo → subjuntivo: pediu que eu fosse.",
               "Verbos de decir: afirmar, contar, comentar, pedir, perguntar se."],
         v=["dizer", "pedir", "perguntar", "contar", "afirmar"],
         tenses=["imperfeito", "subjImperfeito", "condicional", "maisQuePerfeitoComposto"]),
    dict(w=32, title="Voz passiva sintética e sujeito indeterminado", level="B2",
         focus="Vendem-se casas, precisa-se de funcionários, e cómo lo dice la gente.",
         keys=["Pasiva con se: vendem-se casas (concuerda); aluga-se apartamento.",
               "Con preposición no concuerda: precisa-se de vendedores.",
               "Sujeto indeterminado: falam que…, dizem que…",
               "En el habla: você genérico y «a gente»: aqui você paga na entrada."],
         v=["vender", "alugar", "precisar", "dizer", "falar"],
         tenses=["presente", "perfeito"]),
    dict(w=33, title="Colocação pronominal na escrita", level="B2",
         focus="Próclise, ênclise y mesóclise: lo que leerás en textos formales.",
         keys=["Ênclise por defecto en la escritura formal: Disse-me a verdade.",
               "Próclise obligatoria tras não, que, quem, advérbios: não me disse.",
               "Mesóclise (solo formal) con futuro y condicional: dir-lhe-ei, far-se-ia.",
               "En el habla de Brasil el pronombre va antes del verbo: me disse."],
         v=["dizer", "dar", "fazer", "ver"],
         tenses=["presente", "perfeito", "futuro", "condicional"]),
    dict(w=34, title="Conectores e coesão", level="B2",
         focus="porém, contudo, entretanto, no entanto, aliás, inclusive.",
         keys=["Adversativos: mas, porém, contudo, todavia, no entanto, entretanto (= sin embargo).",
               "Conclusivos: portanto, logo, por isso, então.",
               "Explicativos: pois, já que, uma vez que, visto que.",
               "aliás (es más, por cierto), inclusive (incluso), ou seja (o sea)."],
         v=["ser", "ter", "haver"], tenses=["presente", "perfeito", "subjPresente"]),
    dict(w=35, title="Regência verbal", level="B2",
         focus="Los verbos con su preposición, que muchas veces no es la del español.",
         keys=["assistir a (ver) / assistir (ayudar), obedecer a, preferir X a Y.",
               "namorar alguém (sin «con»), casar com, sonhar com, chegar a / em.",
               "Sin preposición en portugués: esperar alguém, ajudar alguém, visitar.",
               "Pronombre relativo con la preposición del verbo: o filme a que assisti."],
         v=["assistir", "obedecer", "preferir", "namorar", "casar", "chegar"],
         tenses=["presente", "perfeito"]),
    dict(w=36, title="Crase", level="B2",
         focus="à = a + a: cuándo lleva acento grave.",
         keys=["a (preposición) + a (artículo) = à: vou à praia.",
               "Truco: cambiá por un masculino; si queda «ao», va crase (vou ao mercado).",
               "Siempre en las horas: às três; nunca ante verbo ni masculino.",
               "àquele, àquela, àquilo; à moda de: bife à milanesa."],
         v=["ir", "chegar", "entregar", "referir-se"], tenses=["presente", "perfeito"]),
    dict(w=37, title="Verbos irregulares e derivados", level="B2",
         focus="Los derivados de ter, vir, pôr y ver, y los verbos en -ear / -iar.",
         keys=["manter, conter, obter como ter; intervir, convir como vir.",
               "propor, compor, supor como pôr; prever, rever como ver.",
               "-ear: passear → passeio; -iar regulares (copio) y odiar, mediar → odeio.",
               "caber (caibo), valer (valho), perder (perco), medir (meço)."],
         v=["manter", "obter", "intervir", "propor", "prever", "passear", "odiar", "caber", "valer", "perder"],
         tenses=["presente", "perfeito", "subjPresente"]),
    dict(w=38, title="Português falado do Brasil", level="B2",
         focus="né, tá, cadê, a gente, pra: lo que escuchás y no está en los libros.",
         keys=["Reducciones: tá (está), pra (para), pro (para o), cê (você), tô (estou).",
               "Marcadores: né, então, tipo, aí, pois é, sei lá, nossa!",
               "cadê? = ¿dónde está?; ter por haver: tem gente aqui.",
               "Registro: se escuchan, se entienden, se usan con amigos."],
         v=["estar", "ter", "ir", "ser"], tenses=["presente", "perfeito"]),
    dict(w=39, title="CHEFÃO — Nível B2", level="B2", boss=True,
         focus="Examen de la tercera estación.",
         keys=["Futuro do subjuntivo e infinitivo pessoal.",
               "Condicionales en presente y pasado.",
               "Discurso indirecto.",
               "Regencia y crase.",
               "Conectores y colocación pronominal."],
         v=["ser", "ter", "fazer", "ir", "poder", "saber"],
         tenses=["subjFuturo", "subjImperfeito", "infPessoal", "condicionalComposto"]),

    # ---------------- Estação 4: O Cume (B2 -> C1) ----------------
    dict(w=40, title="Registro formal e nominalização", level="B2",
         focus="Decir lo mismo con sustantivos: el estilo de los informes.",
         keys=["decidir → a decisão; aumentar → o aumento; analisar → a análise.",
               "haver existencial (há, havia) en lugar de ter en lo escrito.",
               "Verbos formales: realizar, efetuar, proceder a, constatar.",
               "Evitar repeticiones con sinónimos y pronombres."],
         v=["haver", "realizar", "analisar", "decidir"],
         tenses=["presente", "perfeito", "subjPresente"]),
    dict(w=41, title="Pretérito mais-que-perfeito simples e narrativa", level="C1",
         focus="fizera, dissera: el pluscuamperfecto literario.",
         keys=["Raíz de la 3.ª plural del perfeito: fizeram → fizera, disseram → dissera.",
               "Equivale a tinha feito; se lee en literatura y prensa.",
               "Expresiones fijas: quem me dera!, tomara!, pudera!",
               "Narración literaria: perfeito, imperfeito y mais-que-perfeito."],
         v=["fazer", "dizer", "ser", "ter", "ver"],
         tenses=["maisQuePerfeito", "maisQuePerfeitoComposto"]),
    dict(w=42, title="Orações reduzidas", level="C1",
         focus="Condensar con gerundio, participio e infinitivo.",
         keys=["Gerundio: chegando em casa, liguei (= quando cheguei).",
               "Participio: terminada a reunião, saímos (= depois que terminou).",
               "Infinitivo: ao chegar, ligou (= quando chegou).",
               "Concordancia del participio con su sujeto: feitas as contas."],
         v=["chegar", "terminar", "fazer", "ver"],
         tenses=["gerundio", "participio", "infPessoal"]),
    dict(w=43, title="Correspondência formal", level="C1",
         focus="Prezado, atenciosamente, o senhor, Vossa Senhoria.",
         keys=["Apertura: Prezado(a) Senhor(a), Caro(a); cierre: Atenciosamente, Cordialmente.",
               "Tratamiento: o senhor / a senhora; V. Sa. con verbo en tercera.",
               "Fórmulas: venho por meio desta, segue em anexo, fico no aguardo.",
               "Pedido formal: solicito, gostaria de solicitar, agradeceria se."],
         v=["solicitar", "agradecer", "informar", "enviar"],
         tenses=["presente", "condicional", "subjPresente"]),
    dict(w=44, title="Formação de palavras", level="C1",
         focus="Sufijos, prefijos, diminutivos y aumentativos.",
         keys=["-ção, -mento, -dade, -eza, -ice: nominalizar.",
               "-eiro / -eira: oficio y árbol (sapateiro, laranjeira).",
               "Diminutivos -inho / -zinho con afecto (cafezinho, rapidinho).",
               "Aumentativos -ão / -ona (casarão, mulherona); -aço (golaço)."],
         v=["ser", "estar", "ter"], tenses=["presente", "perfeito"]),
    dict(w=45, title="Falsos amigos e heterossemânticos", level="C1",
         focus="Las palabras que parecen españolas y no lo son.",
         keys=["esquisito (raro), polvo (pulpo), borracha (goma), apelido (apodo).",
               "Heterogenéricos: o leite, a dor, o mel, a ponte.",
               "Heterotónicos: academia, alergia, nível, polícia.",
               "Engañan por el sentido: oficina (taller), escritório (oficina)."],
         v=["ser", "ter", "achar"], tenses=["presente", "perfeito"]),
    dict(w=46, title="Variação: Brasil, Portugal e África", level="C1",
         focus="Reconocer las variedades del portugués y sus diferencias.",
         keys=["Brasil: você, gerundio, próclise; Portugal: tu, «a + infinitivo», ênclise.",
               "Léxico: ônibus / autocarro, trem / comboio, celular / telemóvel.",
               "Regiones de Brasil: tu en el Sur y en el Norte; chiado carioca.",
               "Ortografía unificada (Acuerdo de 1990): pocas diferencias."],
         v=["estar", "ter", "fazer"], tenses=["presente", "perfeito", "imperfeito"]),
    dict(w=47, title="Argumentação e modalização", level="C1",
         focus="Sostener una tesis sin afirmarlo todo.",
         keys=["Modalizadores: é possível que, tudo indica que, ao que parece.",
               "Concesión: ainda que, mesmo que, por mais que + subjuntivo.",
               "Introducir argumentos: em primeiro lugar, além disso, por outro lado.",
               "Conclusión: em suma, diante do exposto, dessa forma."],
         v=["ser", "parecer", "indicar"], tenses=["subjPresente", "subjImperfeito", "condicional"]),
    dict(w=48, title="Resumo e reformulação", level="C1",
         focus="Resumir y parafrasear con verbos de decir precisos.",
         keys=["Verbos dicendi: afirmar, defender, alegar, sustentar, ressaltar.",
               "Atribuir: segundo o autor, de acordo com, conforme.",
               "Reformular: ou seja, isto é, em outras palavras.",
               "Resumen: sin opinión, en tercera persona, con conectores."],
         v=["afirmar", "defender", "ressaltar", "sustentar"],
         tenses=["presente", "perfeito", "subjPresente"]),
    dict(w=49, title="Registro culto e coloquial", level="C1",
         focus="Pasar de la charla al texto formal y al revés.",
         keys=["a gente vai → nós vamos; vi ele → vi-o; tem → há.",
               "pra → para; tá → está; cadê → onde está.",
               "Pronombres enclíticos y mesoclíticos en la escritura formal.",
               "Adecuar el vocabulario: legal → interessante, grana → dinheiro."],
         v=["haver", "estar", "ir", "ver"],
         tenses=["presente", "perfeito", "futuro"]),
    dict(w=50, title="Colocações e expressões idiomáticas", level="C1",
         focus="Lo que se dice junto: tomar uma decisão, pisar na bola.",
         keys=["Verbos soporte: tomar banho, fazer questão, dar certo, levar a sério.",
               "Expresiones: pisar na bola, dar um jeito, encher o saco, ficar de boa.",
               "Refranes: quem não tem cão caça com gato; de grão em grão.",
               "Colocaciones formales: tomar providências, levar em conta."],
         v=["dar", "fazer", "levar", "tomar"], tenses=["presente", "perfeito"]),
    dict(w=51, title="Revisão B2-C1", level="C1",
         focus="Todo el año en una semana: lo que más falla a un hispanohablante.",
         keys=["Futuro do subjuntivo, infinitivo pessoal, perfeito composto.",
               "Crase, regencia, contracciones.",
               "Falsos amigos y heterogenéricos.",
               "Registro culto y coloquial."],
         v=["ser", "ter", "fazer", "ir", "poder", "vir"],
         tenses=["subjFuturo", "subjImperfeito", "infPessoal", "perfeitoComposto"]),
    dict(w=52, title="Exame final C1", level="C1", boss=True,
         focus="Cinco pruebas como en el Celpe-Bras y los exámenes C1.",
         keys=["Compreensão oral y escrita.",
               "Estruturas y léxico.",
               "Produção escrita: texto argumentativo y carta formal."],
         v=["ser", "ter", "fazer", "ir", "poder", "saber"],
         tenses=["subjFuturo", "subjImperfeito", "infPessoal", "condicionalComposto"]),
]

REVIEW_WEEKS = (49, 50, 51)


def season_of(week: int) -> int:
    return next(s["n"] for s in SEASONS if s["weeks"][0] <= week <= s["weeks"][1])


def known_tenses(week: int) -> list:
    """Los tiempos que un ejercicio de esa semana puede usar."""
    return [t for t, w in sorted(TENSE_WEEK.items(), key=lambda x: x[1]) if w <= week]


assert [w["w"] for w in WEEKS] == list(range(1, 53))
assert set(SAI_FARE) == set(range(1, 53))
